// B"H
/**
 * @file CombatTargeting.js
 * @description Combat targeting sees explicit finite target proxies first. It
 * never recursively raycasts malformed animal visuals before safety checks.
 */
import * as THREE from "/games/scripts/build/three.module.js";
import { ensureCreatureLevel } from "../progression/CreatureLevelRuntime.js";
import { collectSafeRaycastLeaves } from "../../Olam/methods/helpers/mouse/RaycastSafety.js?v=reality-raycast-20260629-bh1";
const DEFAULT_HP = Object.freeze({ fox:180, rabbit:95, deer:260, goat:240, frog:120, bird:150, target:100 });
const SELECT_RADIUS = Object.freeze({ frog:1.65, rabbit:1.55, bird:1.8, fox:2.0, deer:2.35, goat:2.05, target:1.7 });
function dataOf(o) { if (o && !o.userData) o.userData = {}; return o?.userData || {}; }
function rootOf(o) { let n = o; while (n) { const d = dataOf(n); if (d.combatTargetOwner) return d.combatTargetOwner.mesh || d.combatTargetOwner; if (d.proceduralSkinnedAnimal || d.wildlifeActor || d.selectableCombatTarget || d.combatTargetProxy) return n; n = n.parent; } return o; }
function speciesOf(o) { const d = dataOf(o); return d.species || d.motion?.species || d.profile?.species || o?.def?.species || "target"; }
function nameOf(o) { const d = dataOf(o), s = speciesOf(o); return d.targetName || d.displayName || o?.name || `Wild ${s}`; }
function healthOf(o) { const d = dataOf(o); if (d.health) return d.health; if (d.combatHp === undefined) { const hp = DEFAULT_HP[speciesOf(o)] || DEFAULT_HP.target; d.combatHp = hp; d.combatMaxHp = hp; } return { get current() { return d.combatHp || 0; }, set current(v) { d.combatHp = Math.max(0, Number(v) || 0); }, get max() { return d.combatMaxHp || 1; }, set max(v) { d.combatMaxHp = Math.max(1, Number(v) || 1); } }; }
function bubbleRadius(species) { return SELECT_RADIUS[species] || SELECT_RADIUS.target; }
function markChildren(root, wrapper) { root?.traverse?.(child => { const d = dataOf(child); d.combatTargetOwner = wrapper; d.selectableCombatTarget = true; if (!/soft_shadow/i.test(child.name || "")) d.skipRaycast = false; }); }
function ensureSelectionBubble(root, species) { const d = dataOf(root); if (d.selectionBubble) return d.selectionBubble; const bubble = new THREE.Mesh(new THREE.SphereGeometry(bubbleRadius(species), 10, 8), new THREE.MeshBasicMaterial({ transparent:true, opacity:0, depthWrite:false })); bubble.name = `${root.name || species}_selection_bubble`; bubble.visible = false; bubble.userData = { combatTargetProxy:true, selectableCombatTarget:true, species, interactionLayer:"combat-target", skipOctree:true, noOctree:true, skipRaycast:false }; root.add(bubble); d.selectionBubble = bubble; return bubble; }
export function isLiveTarget(t) { const h = t?.health || healthOf(t?.mesh); return Boolean(t && t.mesh && t.mesh.visible !== false && !t.isDead && Number(h?.current ?? t.hp ?? 1) > 0); }
export function makeCombatTarget(object, playerLevel = 1) { const root = rootOf(object); if (!root?.isObject3D) return null; const d = dataOf(root); if (!d.proceduralSkinnedAnimal && !d.wildlifeActor && !d.selectableCombatTarget && !d.isEnemy && !d.combatTargetProxy) return null; if (d.combatTargetWrapper) { ensureCreatureLevel(d.combatTargetWrapper, playerLevel); return d.combatTargetWrapper; } const h = healthOf(root), species = speciesOf(root); const wrapper = { mesh:root, isReady:true, get name() { return nameOf(root); }, get hp() { return Number(h.current ?? 0); }, get maxHp() { return Number(h.max ?? 1); }, get health() { return h; }, get isDead() { return Number(h.current ?? 0) <= 0 || root.visible === false; }, def:{ species, color:species === "fox" ? 0xd46a24 : 0x8bcf68 }, takeDamage(amount = 0, source = {}) { if (typeof root.takeDamage === "function") return root.takeDamage(amount, source); h.current = Math.max(0, Number(h.current || 0) - Math.max(0, Number(amount) || 0)); dataOf(root).lastDamageAt = Date.now(); if (h.current <= 0) { root.visible = false; dataOf(root).dead = true; } return amount; } }; d.combatTargetWrapper = wrapper; d.combatTargetOwner = wrapper; d.selectableCombatTarget = true; const bubble = ensureSelectionBubble(root, species); bubble.userData.combatTargetOwner = wrapper; markChildren(root, wrapper); ensureCreatureLevel(wrapper, playerLevel); return wrapper; }
function traverse(root, fn) { root?.traverse?.(fn); }
export function collectCombatTargets(olam, enemies = []) { const out = [], level = Number((olam?.player || olam?.chossid)?.level || 1); for (const e of enemies || []) { ensureCreatureLevel(e, level); if (isLiveTarget(e) && !out.includes(e)) out.push(e); } for (const root of [olam?.scene, olam?.__livingRegionWildlifeRoot, olam?.nivrayimGroup].filter(Boolean)) traverse(root, o => { const t = makeCombatTarget(o, level); if (isLiveTarget(t) && !out.includes(t)) out.push(t); }); return out; }
export default class CombatTargeting {
  constructor(olam, onChange) { this.olam = olam; this.onChange = onChange; this.selected = null; this.raycaster = new THREE.Raycaster(); this.lastPointer = new THREE.Vector2(); this.marker = this.createMarker(); }
  createMarker() { const ring = new THREE.Mesh(new THREE.RingGeometry(1.25, 1.65, 48), new THREE.MeshBasicMaterial({ color:0xffd95a, side:THREE.DoubleSide, transparent:true, opacity:.92, depthWrite:false })); ring.rotation.x = -Math.PI / 2; ring.visible = false; ring.userData.skipOctree = true; ring.userData.skipRaycast = true; this.olam?.scene?.add?.(ring); return ring; }
  pointer() { const p = this.olam?.pointer || this.olam?.mouse || this.olam?.ayin?.pointer; return p && Number.isFinite(p.x) && Number.isFinite(p.y) ? p : this.lastPointer.set(0, 0); }
  selectableObjects(candidates) { const objects = []; for (const t of candidates.filter(isLiveTarget)) { const bubble = dataOf(t.mesh).selectionBubble || ensureSelectionBubble(t.mesh, t.def?.species || "target"); objects.push(...collectSafeRaycastLeaves(bubble, "combat", false)); if (!objects.length) objects.push(...collectSafeRaycastLeaves(t.mesh, "combat", true)); } this.olam.__combatRaycastTargetCount = objects.length; return objects; }
  selectFromPointer() { const camera = this.olam?.camera || this.olam?.activeCamera || this.olam?.ayin?.camera; if (!camera) return "none"; const candidates = collectCombatTargets(this.olam, this.olam?.combatManager?.enemies || []); this.raycaster.setFromCamera(this.pointer(), camera); const hit = this.raycaster.intersectObjects(this.selectableObjects(candidates), false)[0]; const target = hit ? this.findTarget(hit.object, candidates) : this.nearestProjectedTarget(this.pointer(), camera, candidates); if (!target) return "none"; if (target === this.selected) return "confirmed"; this.set(target); return "selected"; }
  nearestProjectedTarget(pointer, camera, candidates) { const pos = new THREE.Vector3(); let best = null, score = Infinity; for (const target of candidates.filter(isLiveTarget)) { target.mesh.getWorldPosition(pos); const pr = pos.clone().project(camera), d = Math.hypot(pr.x - pointer.x, pr.y - pointer.y), allowance = target.def?.species === "bird" ? .32 : .28; if (pr.z >= -1 && pr.z <= 1 && d < allowance && d < score) { best = target; score = d; } } return best; }
  nearestInRange(origin, forward, candidates, range = 50, cone = -1) { let best = null, score = Infinity; for (const t of candidates.filter(isLiveTarget)) { const v = t.mesh.position.clone().sub(origin), dist = v.length(); if (dist > range) continue; const dot = forward ? forward.dot(v.clone().setY(0).normalize()) : 1; if (dot < cone) continue; const s = dist - dot * 4; if (s < score) { score = s; best = t; } } return best; }
  findTarget(object, targets) { let n = object; while (n) { const owner = dataOf(n).combatTargetOwner; if (isLiveTarget(owner)) return owner; const direct = makeCombatTarget(n, Number((this.olam?.player || this.olam?.chossid)?.level || 1)); if (isLiveTarget(direct)) return direct; const found = targets.find(t => t?.mesh === n || t?.mesh === n.parent || t === n.nivraAwtsmoos); if (isLiveTarget(found)) return found; n = n.parent; } return null; }
  set(target) { this.selected = isLiveTarget(target) ? target : null; this.marker.visible = Boolean(this.selected?.mesh); this.onChange?.(this.selected); }
  update() { if (!isLiveTarget(this.selected)) return this.set(null); const p = this.selected.mesh.position; this.marker.position.set(p.x, p.y + .1, p.z); this.marker.rotation.z += .016; }
  dispose() { this.marker.removeFromParent(); this.marker.geometry.dispose(); this.marker.material.dispose(); }
}
