/* B"H
Visualizer helpers: public drawing spells offered to presets and custom JS.
*/
import { band } from './audioFeatures.js';
import { hebrewAt } from './hebrewLetters.js';
import { hebrewLightningBolts, hebrewLightningParticles } from './hebrewLightningModel.js';
import { hebrewRiverGlyphs } from './hebrewRiverModel.js';
import { screenSpeedStreaks } from './screenSpeedModel.js';
export const visualizerHelpers = { drawBars, drawWave, drawCircleWave, drawHebrewOrbit, drawHebrewRain, drawHebrewRiver, drawHebrewLightning, drawScreenSpeed, drawParticles, band, beat:f => !!f.features?.beat, clamp };
export function drawBars(ctx, source, frame) { const bars = Math.min(source.settings?.bars || 48, frame.freq.length), gap = 3, width = Math.max(2, source.w / bars - gap); ctx.fillStyle = source.settings?.barsColor || '#7c5cff'; for (let i = 0; i < bars; i++) { const h = Math.max(4, frame.freq[i] * source.h * (source.settings?.sensitivity || 1)); ctx.fillRect(i * (width + gap), source.h - h, width, h); } }
export function drawWave(ctx, source, frame) { ctx.strokeStyle = source.settings?.wave || '#83ffe7'; ctx.lineWidth = 3 + band(frame, 'pulse') * 7; ctx.beginPath(); frame.time.forEach((v, i) => { const x = i / (frame.time.length - 1) * source.w, y = source.h * .5 + v * source.h * .34; i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); }
export function drawCircleWave(ctx, source, frame) { const cx = source.w / 2, cy = source.h / 2, r = Math.min(source.w, source.h) * (.22 + band(frame, 'bass') * .16); ctx.strokeStyle = source.settings?.wave || '#83ffe7'; ctx.lineWidth = 4; ctx.beginPath(); for (let i = 0; i < frame.freq.length; i++) { const a = i / frame.freq.length * Math.PI * 2, rr = r + frame.freq[i] * 90; const x = cx + Math.cos(a) * rr, y = cy + Math.sin(a) * rr; i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); } ctx.closePath?.(); ctx.stroke(); }
export function drawHebrewOrbit(ctx, source, frame) { const text = source.settings?.hebrewText, r = Math.min(source.w, source.h) * (.24 + band(frame, 'mid') * .22); const cx = source.w / 2, cy = source.h / 2, count = 18; ctx.fillStyle = source.settings?.letters || '#ffd166'; ctx.font = `bold ${24 + band(frame, 'treble') * 18}px serif`; for (let i = 0; i < count; i++) { const a = frame.t * .9 + i * Math.PI * 2 / count; ctx.fillText(hebrewAt(i + frame.index, text), cx + Math.cos(a) * r, cy + Math.sin(a) * r); } }
export function drawHebrewRain(ctx, source, frame) { const text = source.settings?.hebrewText, cols = 24; ctx.fillStyle = source.settings?.letters || '#ffd166'; ctx.font = `${18 + band(frame, 'treble') * 18}px serif`; for (let i = 0; i < cols; i++) { const x = i / cols * source.w, y = (i * 37 + frame.t * (90 + band(frame, 'bass') * 220)) % source.h; ctx.fillText(hebrewAt(i + frame.index, text), x, y); } }
export function drawHebrewRiver(ctx, source, frame) { for (const g of hebrewRiverGlyphs(source, frame)) { ctx.shadowBlur = g.glow; ctx.shadowColor = source.settings?.letters || '#83ffe7'; ctx.globalAlpha = g.alpha; ctx.fillStyle = source.settings?.letters || '#d8fff7'; ctx.font = `bold ${g.size}px serif`; ctx.fillText(g.glyph, g.x, g.y); } ctx.globalAlpha = 1; ctx.shadowBlur = 0; }
export function drawHebrewLightning(ctx, source, frame) { ctx.strokeStyle = source.settings?.wave || '#e6fbff'; ctx.lineWidth = 2 + band(frame, 'bass') * 6; for (const b of hebrewLightningBolts(source, frame)) { ctx.beginPath(); b.points.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.stroke(); b.points.forEach(p => drawSpark(ctx, source, p, 16 + b.flash * 20, .7 + b.flash * .3)); } hebrewLightningParticles(source, frame).forEach(p => drawSpark(ctx, source, p, p.size, p.alpha)); }
export function drawScreenSpeed(ctx, source, frame) { const model = screenSpeedStreaks(source, frame); ctx.fillStyle = source.settings?.particles || '#83ffe7'; for (const s of model.streaks) { ctx.globalAlpha = s.alpha; ctx.fillRect(s.x, s.y, s.len * s.direction, 3 + model.energy * 8); } ctx.globalAlpha = 1; ctx.fillStyle = '#dbe7ff'; ctx.font = 'bold 18px monospace'; ctx.fillText(model.label, 18, 62); }
export function drawParticles(ctx, source, frame) { const count = 34, cx = source.w / 2, cy = source.h / 2; ctx.fillStyle = source.settings?.particles || '#83ffe7'; for (let i = 0; i < count; i++) { const a = i * 2.399 + frame.t, r = 20 + ((i * 31) % 140) * (.45 + band(frame, 'bass')); ctx.fillRect(cx + Math.cos(a) * r, cy + Math.sin(a) * r, 3 + band(frame, 'pulse') * 10, 3 + band(frame, 'pulse') * 10); } }
function drawSpark(ctx, source, p, size, alpha) { ctx.globalAlpha = alpha; ctx.fillStyle = source.settings?.particles || source.settings?.letters || '#ffffff'; ctx.font = `bold ${size}px serif`; ctx.fillText(p.glyph, p.x, p.y); ctx.globalAlpha = 1; }
function clamp(value, min = 0, max = 1) { return Math.max(min, Math.min(max, Number(value))); }
