/* B"H
Visualizer helpers: public drawing spells offered to presets and custom JS.
*/
import { band } from './audioFeatures.js';
import { hebrewAt } from './hebrewLetters.js';
export const visualizerHelpers = { drawBars, drawWave, drawCircleWave, drawHebrewOrbit, drawHebrewRain, drawParticles, band, beat:f => !!f.features?.beat, clamp };
export function drawBars(ctx, source, frame) { const bars = Math.min(source.settings?.bars || 48, frame.freq.length), gap = 3, width = Math.max(2, source.w / bars - gap); ctx.fillStyle = source.settings?.barsColor || '#7c5cff'; for (let i = 0; i < bars; i++) { const h = Math.max(4, frame.freq[i] * source.h * (source.settings?.sensitivity || 1)); ctx.fillRect(i * (width + gap), source.h - h, width, h); } }
export function drawWave(ctx, source, frame) { ctx.strokeStyle = source.settings?.wave || '#83ffe7'; ctx.lineWidth = 3 + band(frame, 'pulse') * 7; ctx.beginPath(); frame.time.forEach((v, i) => { const x = i / (frame.time.length - 1) * source.w, y = source.h * .5 + v * source.h * .34; i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); }
export function drawCircleWave(ctx, source, frame) { const cx = source.w / 2, cy = source.h / 2, r = Math.min(source.w, source.h) * (.22 + band(frame, 'bass') * .16); ctx.strokeStyle = source.settings?.wave || '#83ffe7'; ctx.lineWidth = 4; ctx.beginPath(); for (let i = 0; i < frame.freq.length; i++) { const a = i / frame.freq.length * Math.PI * 2, rr = r + frame.freq[i] * 90; const x = cx + Math.cos(a) * rr, y = cy + Math.sin(a) * rr; i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); } ctx.closePath?.(); ctx.stroke(); }
export function drawHebrewOrbit(ctx, source, frame) { const text = source.settings?.hebrewText, r = Math.min(source.w, source.h) * (.24 + band(frame, 'mid') * .22); const cx = source.w / 2, cy = source.h / 2, count = 18; ctx.fillStyle = source.settings?.letters || '#ffd166'; ctx.font = `bold ${24 + band(frame, 'treble') * 18}px serif`; for (let i = 0; i < count; i++) { const a = frame.t * .9 + i * Math.PI * 2 / count; ctx.fillText(hebrewAt(i + frame.index, text), cx + Math.cos(a) * r, cy + Math.sin(a) * r); } }
export function drawHebrewRain(ctx, source, frame) { const text = source.settings?.hebrewText, cols = 24; ctx.fillStyle = source.settings?.letters || '#ffd166'; ctx.font = `${18 + band(frame, 'treble') * 18}px serif`; for (let i = 0; i < cols; i++) { const x = i / cols * source.w, y = (i * 37 + frame.t * (90 + band(frame, 'bass') * 220)) % source.h; ctx.fillText(hebrewAt(i + frame.index, text), x, y); } }
export function drawParticles(ctx, source, frame) { const count = 34, cx = source.w / 2, cy = source.h / 2; ctx.fillStyle = source.settings?.particles || '#83ffe7'; for (let i = 0; i < count; i++) { const a = i * 2.399 + frame.t, r = 20 + ((i * 31) % 140) * (.45 + band(frame, 'bass')); ctx.fillRect(cx + Math.cos(a) * r, cy + Math.sin(a) * r, 3 + band(frame, 'pulse') * 10, 3 + band(frame, 'pulse') * 10); } }
function clamp(value, min = 0, max = 1) { return Math.max(min, Math.min(max, Number(value))); }
