// B"H
/** Compact action dock: real short fixed vessel, never a tall invisible column. */
const ACTIONS=[{cls:"attack-slot",icon:"⚔️",name:"Strike",label:"V",kind:"combatAttack"},{cls:"sword-slot",icon:"🗡️",name:"Sword",label:"1",kind:"combatEquip",weaponId:"cherev_hakodesh"},{cls:"bow-slot",icon:"🏹",name:"Bow",label:"2",kind:"combatEquip",weaponId:"keshes_haemes"},{cls:"staff-slot",icon:"🔯",name:"Staff",label:"3",kind:"combatEquip",weaponId:"mateh_hatorah"},{cls:"talk-slot",icon:"💬",name:"Talk",label:"C",kind:"pulse",code:"KeyC"},{cls:"bag-slot",icon:"🎒",name:"Bag",label:"I",kind:"inventory"}];
function stop(e){e?.preventDefault?.();e?.stopPropagation?.();}
function inventory(){return document.getElementById("inventoryScreen");}
function worker(){return window.mana?.socket?.eved||window.mana?.eved||null;}
function send(inner){worker()?.postMessage?.({olamPeula:inner});}
function addClass(el,n){if(el&&!el.classList.contains(n))el.classList.add(n);}
function removeClass(el,n){if(el?.classList.contains(n))el.classList.remove(n);}
function closeLoosePanels(){document.getElementById("awtsmoos-npc-overlay")?.remove();document.querySelectorAll(".awtsmoosContextMenu,.bz-panel,.construction-screen").forEach(el=>addClass(el,"hidden"));}
function showInventory(open){const inv=inventory();if(!inv)return;const hidden=inv.classList.contains("hidden");if(open&&!hidden)return;if(!open&&hidden)return;if(open){closeLoosePanels();removeClass(inv,"hidden");inv.dispatchEvent(new CustomEvent("awtsInventoryOpen",{bubbles:true}));return;}addClass(inv,"hidden");}
function pulse(code){send({setInput:{code}});setTimeout(()=>send({setInputOut:{code}}),120);}
function fire(a){if(a.kind==="inventory")return showInventory(Boolean(inventory()?.classList.contains("hidden")));if(a.kind==="pulse")return pulse(a.code);if(a.kind==="combatAttack")return send({combatAttack:{source:"actionBar",allowAutoFace:true,preferMelee:true,mobileAssist:true}});if(a.kind==="combatEquip")return send({combatEquip:{weaponId:a.weaponId,source:"actionBar"}});}
function bindTap(el,a){let last=0;el.addEventListener("pointerdown",e=>{stop(e);const at=performance.now();if(at-last<120)return;last=at;fire(a);},{passive:false});}
function button(a){return{className:`actionSlot ${a.cls}`,dataset:{awtsUi:"true",action:a.name},title:a.name,ready(el){bindTap(el,a);},children:[{className:"slotIcon",textContent:a.icon},{className:"slotName",textContent:a.name},{className:"slotKey",textContent:a.label}]};}
const css=`
#actionBar.combat-action-dock{position:fixed!important;left:50%!important;bottom:calc(10px + env(safe-area-inset-bottom,0px))!important;transform:translateX(-50%)!important;width:max-content!important;height:68px!important;min-height:0!important;max-height:68px!important;overflow:visible!important;display:flex!important;align-items:flex-end!important;justify-content:center!important;z-index:27000!important;pointer-events:none!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:0!important;margin:0!important;contain:layout style!important}
#actionSlots{position:relative!important;display:grid!important;grid-template-columns:repeat(6,54px)!important;gap:6px!important;padding:7px!important;width:max-content!important;height:auto!important;max-height:none!important;border-radius:17px!important;background:rgba(7,12,22,.82)!important;border:1px solid rgba(255,224,138,.36)!important;box-shadow:0 10px 24px rgba(0,0,0,.4)!important;backdrop-filter:blur(8px)!important;pointer-events:auto!important;box-sizing:border-box!important}
#actionBar .actionSlot{height:52px!important;min-height:52px!important;max-height:52px!important;width:54px!important;border-radius:12px!important;background:radial-gradient(circle at 50% 18%,rgba(112,141,160,.5),rgba(13,24,37,.96) 64%)!important;border:1px solid rgba(235,210,130,.48)!important;display:flex!important;align-items:center!important;justify-content:center!important;flex-direction:column!important;position:relative!important;overflow:hidden!important;touch-action:manipulation!important;color:#fff!important;padding:0!important;box-sizing:border-box!important}
#actionBar .attack-slot{background:radial-gradient(circle at 50% 18%,rgba(255,116,74,.68),rgba(81,25,22,.98) 70%)!important}#actionBar .slotIcon{font:900 19px/1 Arial!important}#actionBar .slotName{font:700 8px/1 Arial!important;color:#fff2bd!important;max-width:48px!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}#actionBar .slotKey{position:absolute!important;left:4px!important;bottom:3px!important;min-width:12px!important;height:12px!important;border-radius:4px!important;text-align:center!important;font:800 8px/12px Arial!important;color:#9fffd0!important;background:rgba(0,0,0,.55)!important}
@media(max-width:820px),(max-height:720px){#actionBar.combat-action-dock{left:50%!important;right:auto!important;bottom:calc(12px + env(safe-area-inset-bottom,0px))!important;transform:translateX(-50%)!important;width:min(56vw,360px)!important;height:50px!important;max-height:50px!important;align-items:flex-end!important}#actionSlots{grid-template-columns:repeat(6,minmax(28px,1fr))!important;gap:3px!important;padding:4px!important;width:100%!important;max-height:46px!important;border-radius:13px!important;box-sizing:border-box!important}#actionBar .actionSlot{height:36px!important;min-height:36px!important;max-height:36px!important;width:auto!important;border-radius:9px!important;padding:1px!important}#actionBar .slotIcon{font-size:14px!important}#actionBar .slotName{display:none!important}#actionBar .slotKey{font-size:7px!important;height:9px!important;line-height:9px!important;min-width:9px!important}}
@media(max-width:430px){#actionBar.combat-action-dock{width:min(54vw,260px)!important;height:48px!important;max-height:48px!important}#actionBar .actionSlot{height:34px!important;min-height:34px!important;max-height:34px!important}}
`;
export default{shaym:"action bar",id:"actionBar",className:"awtsmoosAction combat-action-dock open",awtsmoosClick:true,children:[{className:"slots",shaym:"action slots",id:"actionSlots",children:ACTIONS.map(button)},{tag:"style",innerHTML:css}],on:{updateActionSlots(){}}};
