// B"H
/** Grounding refuses jump arcs until descent is real and feet are near earth. */
import { ensureGroundCollisionWorld } from "../GroundCollisionWorld.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
const finite=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const MIN_AIR_MS=900, MIN_LAND_VY=-0.45, MAX_GROUND_GAP=0.095, MAX_LIFT=0.22;
function jumpAge(player){return Date.now()-Number(player?.__jumpStartedAt||0);}
export function rising(player){const vy=finite(player?.velocity?.y,0);return vy>.05||(player?.jumped&&!player?.onFloor&&vy>MIN_LAND_VY)||Date.now()<Number(player?.__jumpAirborneUntil||0)||Boolean(player?.jumped&&jumpAge(player)<MIN_AIR_MS);}
export function hitPayload(hit,c){return{distance:c.start.y-hit.y,position:hit.point,normal:hit.normal,object:hit.object,meshGroundAuthority:!hit.fallback&&(hit.source==="octree"||hit.source==="flat-test-ground"||hit.source==="initial-raycast-grounding"),fallback:hit.fallback,source:hit.source,surfaceKey:hit.surfaceKey||null,materialKey:hit.materialKey||null,biomeKey:hit.biomeKey||null,walkable:hit.walkable!==false,slopeDegrees:hit.slopeDegrees??null};}
function acceptable(hit){return hit&&Number.isFinite(hit.y)&&hit.walkable!==false&&!hit.fallback;}
function stillAirborne(player,feetY,targetFeet){const vy=finite(player?.velocity?.y,0);if(!player?.jumped)return false;if(jumpAge(player)<MIN_AIR_MS)return true;if(vy>MIN_LAND_VY)return true;if(feetY-targetFeet>MAX_GROUND_GAP)return true;return false;}
export function groundPlayer(olam,player,nearRadius,options={}){const c=player?.collider;if(!c?.start||!c?.end)return false;const radius=finite(c.radius||player.radius,.45),feetY=c.start.y-radius,hit=ensureGroundCollisionWorld(olam)?.groundAt(c.start.x,c.start.z,{fallback:feetY,radius:nearRadius,fallbackFn:options.fallbackFn});if(!acceptable(hit))return{grounded:false,hit:null};const targetFeet=hit.y+finite(options.slack,.01),gap=feetY-targetFeet;if(!options.force&&(rising(player)||stillAirborne(player,feetY,targetFeet))){player.onFloor=false;player.grounded=false;player.isOnGround=false;player.__lastGroundRefusal={at:Date.now(),reason:"jump-arc",vy:finite(player.velocity?.y,0),gap,age:jumpAge(player),minAirMs:MIN_AIR_MS};return{grounded:false,hit};}if(gap>MAX_GROUND_GAP&&!(player.onFloor&&Math.abs(gap)<.45))return{grounded:false,hit};const lift=targetFeet-feetY;if(!Number.isFinite(lift)||Math.abs(lift)>MAX_LIFT)return{grounded:false,hit};c.start.y+=lift;c.end.y+=lift;if(player.velocity)player.velocity.y=0;player.onFloor=true;player.grounded=true;player.isOnGround=true;player.jumped=false;player.groundHitResult=hitPayload(hit,c);player.__meshGroundAuthority={at:Date.now(),groundY:hit.y,lift,source:hit.source,fallback:false,mesh:hit.mesh||null,walkable:true};return{grounded:true,hit};}
