// B"H
import { getDefaultAlias, getAliasDetails, setDefaultAlias } from './api.js';
import { state } from './state.js';
import { loadNotificationPreview, notificationPreviewCard } from '/scripts/awtsmoos/social/shared/notificationsPreview.js';
const drawer=()=>document.querySelector('[data-profile-action-drawer]');
export function bindProfileInlineActions(){document.querySelectorAll('[data-profile-action]').forEach(btn=>btn.addEventListener('click',()=>openAction(btn)));}
async function openAction(btn){btn.setAttribute('aria-expanded','true');const panel=drawer();if(!panel)return;panel.hidden=false;panel.innerHTML=`<div class="profile-action-head"><h2>${title(btn.dataset.profileAction)}</h2><button type="button" data-close-profile-action>×</button></div><div data-profile-action-body></div>`;panel.querySelector('[data-close-profile-action]').addEventListener('click',()=>close(btn));const body=panel.querySelector('[data-profile-action-body]');if(btn.dataset.profileAction==='alias')body.append(await aliasDrawer());if(btn.dataset.profileAction==='notifications')body.append(await notificationDrawer());if(btn.dataset.profileAction==='heichel')body.append(heichelShortcut());panel.querySelector('button,a,input,select')?.focus({preventScroll:true});}
function close(btn){const p=drawer();if(p){p.hidden=true;p.replaceChildren();}btn?.setAttribute('aria-expanded','false');btn?.focus({preventScroll:true});}
function title(kind){return kind==='alias'?'Alias quick switcher':kind==='notifications'?'Notification preview':'Heichel shortcut';}
async function aliasDrawer(){if(!state.aliases.length){try{state.defaultAlias=await getDefaultAlias();state.aliases=await getAliasDetails();}catch{}}const box=document.createElement('div');box.className='profile-action-list';const status=document.createElement('p');status.className='g-social-status';box.append(...state.aliases.map(a=>aliasButton(a,status)),status,link('./alias-manage/','Open alias manager'));return box;}
function aliasButton(alias,status){const b=document.createElement('button');b.className='g-social-button';b.type='button';b.textContent=`@${alias.id}${alias.id===state.defaultAlias?' — default':''}`;b.setAttribute('aria-pressed',String(alias.id===state.defaultAlias));b.addEventListener('click',async()=>{status.dataset.tone='loading';status.textContent='Saving default alias…';try{await setDefaultAlias(alias.id);state.defaultAlias=alias.id;status.dataset.tone='success';status.textContent=`@${alias.id} is default.`;window.dispatchEvent(new CustomEvent('awtsmoosAliasChange',{detail:{id:alias.id}}));}catch(e){status.dataset.tone='error';status.textContent=e.message;}});return b;}
async function notificationDrawer(){const box=document.createElement('div');box.className='inline-notification-list';const alias=state.defaultAlias||await getDefaultAlias();try{const page=await loadNotificationPreview(alias,{limit:5});const items=page.items||[];box.replaceChildren(...(items.length?items.map(notificationPreviewCard):[empty('No recent notifications.')]),link('/notifications','Open full notifications'));}catch(e){box.replaceChildren(empty(e.message),link('/notifications','Open full notifications'));}return box;}
function heichelShortcut(){const box=document.createElement('div');box.className='profile-action-list';box.append(empty('Create a Heichel inline from Home, or open the full ownership cockpit for advanced editing.'),link(`/heichelos/manage-alias-heichelos/?alias=${encodeURIComponent(state.defaultAlias||'')}`,'Open Heichel cockpit'));return box;}
function link(href,text){const a=document.createElement('a');a.className='g-social-button primary';a.href=href;a.textContent=text;return a;}
function empty(text){const p=document.createElement('article');p.className='g-social-empty';p.textContent=text;return p;}
