import assert from 'node:assert/strict';
import { createMitzvahWorldRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/runtime/createMitzvahWorldRuntime.js';

const runtime = createMitzvahWorldRuntime({ interiors: { house: () => ({ id: 'house' }) } });
const door = { name: 'door_1', userData: { locked: false } };
runtime.bus.emit('openDoor', { door, player: { id: 'p1' } });
assert.equal(runtime.store.get('doors.door_1.isOpen'), true);
runtime.bus.emit('bless', { targetId: 'npc_reb_shlomo', intensity: 2 });
assert.equal(runtime.torahEnergy.snapshot()[0].intensity, 2);
assert.equal((await runtime.interiors.enter('house')).room.id, 'house');
runtime.bus.emit('collectItem', { itemId: 'Wood', qty: 3 });
assert.equal(runtime.inventory.count('Wood'), 3);
assert.equal(runtime.quests.count('collect', 'Wood'), 3);
runtime.bus.emit('npcInteract', { npc: { userData: { hasMission: true, missionId: 'gather_emerald_wood', markerType: 'quest' } } });
assert.equal(runtime.store.get('lastNpcInteraction').missionId, 'gather_emerald_wood');
runtime.bus.emit('openChumash', { item: { id: 'chumash' } });
assert.equal(runtime.store.get('chumash.passagesVisible') > 0, true);
runtime.bus.emit('openTorahDebate', { deckId: 'chumash_bereishis_opening' });
assert.equal(runtime.store.get('torahDebate.deckId'), 'chumash_bereishis_opening');
runtime.bus.emit('bindActionSlot', { slot: 0, action: 'collectItem', payload: { itemId: 'Wood', qty: 1 } });
runtime.bus.emit('activateActionSlot', { slot: 0 });
assert.equal(runtime.inventory.count('Wood'), 4);
assert.equal(runtime.store.get('actionBar.0'), 'collectItem');
assert.equal(runtime.diagnostics.summary().runtimeSystems >= 12, true);
console.log('B"H runtime bootstrap passed');
