import assert from 'node:assert/strict';
import { InteriorStreamingRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/interiors/InteriorStreamingRuntime.js';
import { RoomGraphRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/interiors/RoomGraphRuntime.js';
import { HousePersistenceRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/persistence/HousePersistenceRuntime.js';
import { IndoorZoneRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/interiors/IndoorZoneRuntime.js';
import { StairTraversalRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/navigation/StairTraversalRuntime.js';
import { InteractionPriorityRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/interactions/InteractionPriorityRuntime.js';
import { MissionDependencyRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/quests/MissionDependencyRuntime.js';
import { WorldStateSerializer } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/persistence/WorldStateSerializer.js';
import { DynamicWeatherRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/environment/DynamicWeatherRuntime.js';
import { DayNightRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/environment/DayNightRuntime.js';
import { NpcScheduleRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/npcs/NpcScheduleRuntime.js';
import { DebateBattleRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/debate/DebateBattleRuntime.js';
import { TorahEnergyOverlayRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/effects/TorahEnergyOverlayRuntime.js';
import { CraftingRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/crafting/CraftingRuntime.js';
import { MarketplaceRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/economy/MarketplaceRuntime.js';
import { SynagogueRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/synagogue/SynagogueRuntime.js';
import { DynamicEventRuntime } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/events/DynamicEventRuntime.js';
import { RuntimeLODSystem } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/performance/RuntimeLODSystem.js';
import { RuntimeManifestCompiler } from '../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/compiler/RuntimeManifestCompiler.js';

const interiors = new InteriorStreamingRuntime({ house: () => ({ rooms: ['entry'] }) });
assert.equal((await interiors.enter('house')).visits, 1);
assert.deepEqual(new RoomGraphRuntime([{ from: 'entry', to: 'upper' }]).path('entry', 'upper'), ['entry', 'upper']);
assert.equal(new HousePersistenceRuntime().recordDoor('h1', 'd1', true).doors.d1.isOpen, true);
assert.equal(new IndoorZoneRuntime({ h1: { audio: 'room' } }).enter('h1').audio, 'room');
const actor = { id: 'p', roomId: 'entry' };
assert.equal(new StairTraversalRuntime({ s1: { from: 'entry', to: 'upper' } }).traverse('s1', actor).roomId, 'upper');
assert.equal(new InteractionPriorityRuntime().pick([{ type: 'collectible' }, { type: 'door', distance: 3 }]).type, 'door');
const missions = new MissionDependencyRuntime({ first: {}, second: { requires: ['first'] } });
assert.equal(missions.complete('first').includes('second'), true);
const saved = new WorldStateSerializer().serialize({ wood: 6 });
assert.equal(new WorldStateSerializer().deserialize(saved).wood, 6);
assert.equal(new DynamicWeatherRuntime(['clear', 'rain']).advance().wetness, 1);
assert.equal(new DayNightRuntime(360).phase(), 'dawn');
const npc = { id: 'n1', userData: {} };
new NpcScheduleRuntime({ n1: { day: { action: 'learn', place: 'shul' } } }).apply(npc, 'day');
assert.equal(npc.userData.currentActivity, 'learn');
assert.equal(new DebateBattleRuntime().strike('pshat', 'sod').npcHp, 24);
assert.equal(new TorahEnergyOverlayRuntime().bless('npc').visible, true);
assert.equal(new CraftingRuntime({ bench: { requires: { wood: 2 }, output: 'bench' } }).craft('bench', { wood: 2 }).ok, true);
assert.equal(new MarketplaceRuntime({ wood: 3 }).buy({ buyer: { coins: 9, inventory: {} }, itemId: 'wood', qty: 2 }).ok, true);
const shul = new SynagogueRuntime({ minyanSize: 2 });
shul.arrive('a');
assert.equal(shul.arrive('b').hasMinyan, true);
assert.equal(new DynamicEventRuntime([{ id: 'rain_song' }]).trigger('rain_song').eventId, 'rain_song');
const obj = { userData: {} };
assert.equal(new RuntimeLODSystem({ near: 1, mid: 2 }).apply(obj, 3), 'sleep');
const compiled = new RuntimeManifestCompiler().compile({ objects: { a: {} }, interactions: {}, systems: { weather: {} } });
assert.equal(new RuntimeManifestCompiler().validate(compiled).counts.systems, 1);
console.log('B"H runtime expansion passed');
