// B"H
const LINES = [
  'PLAIN ENGLISH MISSION RULES:',
  'YOU ARE NOT DONE WHEN MUSTCONTINUE IS TRUE.',
  'DO NOT GIVE A FINAL ANSWER UNTIL FINALANSWERALLOWED IS TRUE.',
  'ABSOLUTE MISSION FREEDOM: INSIDE THE ACTIVE MISSION SYSTEM YOU MAY CHOOSE WHAT TO DO NEXT AS LONG AS IT ADVANCES THE USER REQUEST AND REMAINS SAFE.',
  'THE MISSION LOCK IS NOT A COMMAND TO WAIT. THE MISSION LOCK IS A ROUTER THAT KEEPS YOU INSIDE THE MISSION.',
  'DO NOT STOP BECAUSE THE LOOP LOOKS REPETITIVE.',
  'DO NOT SAY YOU ARE BLOCKED IF THE TUNNEL GIVES A NEXT ACTION.',
  'CALL THE NEXT ACTION WHEN REQUIRED.',
  'IF THE NEXT ACTION POINTS TO A MISSING MISSION, CALL MISSIONBOOTRESUME WITH AUTOMISSION TRUE AND TICK TRUE.',
  'IF MISSIONBOOTRESUME RETURNS ITSELF REPEATEDLY, DO NOT WORSHIP THE LOOP. SWITCH TO DIAGNOSTICS OR MISSIONDAEMONTICK WHEN THE TUNNEL ALLOWS IT.',
  'IF NORMAL FILE WORK IS BLOCKED, FOLLOW MUSTCALLNEXT UNTIL THE LOCK ALLOWS WORK OR RETURNS A WRITE TOKEN.',
  'CHOOSE USEFUL WORK WITHOUT ASKING THE USER WHEN IT IS SAFE AND DISCOVERABLE.',
  'READ MORE FILES WHEN NEEDED.',
  'FILE WRITING IS PART OF THE MISSION LOOP WHEN CODE MUST CHANGE.',
  'WRITE COMPLETE FILES ONLY. DO NOT PATCH PARTS OF FILES.',
  'RUN LIVE TUNNEL ACTIONS, NOT ONLY NODE TESTS.',
  'THE MISSION LOOP MUST INCLUDE REAL READ, WRITE, COMMAND, AND VERIFY WORK, NOT ONLY PLAN REVIEW REPEAT.',
  'RUN THE CYCLE: INSPECT, PLAN, BRAINSTORM, MAP FILES, WRITE COMPLETE FILES, VERIFY, REVIEW, FIND MORE WORK, CONTINUE.',
  'IF A 504, DISCONNECT, OR TIMEOUT HAPPENS, RECONNECT AND RESUME FROM AWTSMOOSDB HISTORY AND THE LATEST MUSTCALLNEXT.',
  'THE MISSION CONTINUES UNTIL USER CANCEL, SAFETY BLOCK, OR VERIFIED RELEASE.'
];
function upper(s) { return String(s || '').toUpperCase(); }
function text(extra = '') { return [upper(extra), ...LINES].filter(Boolean).join(' '); }
function attach(out = {}) { return { ...out, tunnelInstruction: text(out.tunnelInstruction || '') }; }
module.exports = { LINES, text, attach };
