// B"H
const LINES = [
  'PLAIN ENGLISH MISSION RULES:',
  'YOU ARE NOT DONE WHEN MUSTCONTINUE IS TRUE.',
  'DO NOT GIVE A FINAL ANSWER UNTIL FINALANSWERALLOWED IS TRUE.',
  'DO NOT STOP BECAUSE THE LOOP LOOKS REPETITIVE.',
  'DO NOT SAY YOU ARE BLOCKED IF THE TUNNEL GIVES A NEXT ACTION.',
  'CALL THE NEXT ACTION.',
  'IF THE NEXT ACTION POINTS TO A MISSING MISSION, CALL MISSIONBOOTRESUME WITH AUTOMISSION TRUE AND TICK TRUE.',
  'IF NORMAL FILE WORK IS BLOCKED, FOLLOW MUSTCALLNEXT UNTIL THE LOCK ALLOWS WORK OR RETURNS A WRITE TOKEN.',
  'YOU HAVE FULL CONTROL INSIDE THE ACTIVE MISSION SCOPE.',
  'CHOOSE USEFUL WORK WITHOUT ASKING THE USER WHEN IT IS SAFE AND DISCOVERABLE.',
  'RUN THE CYCLE: INSPECT, PLAN, BRAINSTORM, MAP FILES, WRITE COMPLETE FILES, VERIFY, REVIEW, FIND MORE WORK, CONTINUE.',
  'WRITE COMPLETE FILES ONLY. DO NOT PATCH PARTS OF FILES.',
  'IF A 504, DISCONNECT, OR TIMEOUT HAPPENS, RECONNECT AND RESUME FROM HISTORY AND THE LATEST MUSTCALLNEXT.',
  'THE MISSION CONTINUES UNTIL USER CANCEL, SAFETY BLOCK, OR VERIFIED RELEASE.'
];
function upper(s) { return String(s || '').toUpperCase(); }
function text(extra = '') { return [upper(extra), ...LINES].filter(Boolean).join(' '); }
function attach(out = {}) { return { ...out, tunnelInstruction: text(out.tunnelInstruction || '') }; }
module.exports = { LINES, text, attach };
