// B"H
const Covenant = require('./continuationCovenant.js');
/**
 * B"H
 * The tunnel speaks in simple flame:
 * not done, keep going, remember the aim.
 */
const LINES = Object.freeze([
  'PLAIN ENGLISH MISSION RULES:',
  ...Covenant.PLAIN_ENGLISH,
  'DO NOT GIVE A FINAL ANSWER UNTIL FINALANSWERALLOWED IS TRUE.',
  'DO NOT STOP BECAUSE THE CURRENT COMMAND TREE ENDED.',
  'DO NOT STOP BECAUSE THE CURRENT QUEUE LOOKS EMPTY.',
  'DO NOT STOP BECAUSE ONE ACTION RETURNED OK.',
  'ABSOLUTE MISSION FREEDOM: INSIDE THE ACTIVE MISSION SYSTEM YOU MAY CHOOSE WHAT TO DO NEXT AS LONG AS IT ADVANCES THE USER REQUEST AND REMAINS SAFE.',
  'THE MISSION LOCK IS NOT A COMMAND TO WAIT. THE MISSION LOCK IS A ROUTER THAT KEEPS YOU INSIDE THE MISSION.',
  'DO NOT SAY YOU ARE BLOCKED IF THE TUNNEL GIVES A NEXT ACTION.',
  'CALL THE NEXT ACTION WHEN REQUIRED.',
  'IF NORMAL FILE WORK IS BLOCKED, FOLLOW MUSTCALLNEXT UNTIL THE LOCK ALLOWS WORK OR RETURNS A WRITE TOKEN.',
  'CHOOSE USEFUL WORK WITHOUT ASKING THE USER WHEN IT IS SAFE AND DISCOVERABLE.',
  'RUN THE CYCLE: INSPECT, PLAN, BRAINSTORM, MAP FILES, WRITE COMPLETE FILES, VERIFY, REVIEW, FIND MORE WORK, CONTINUE.',
  'IF A 504, DISCONNECT, OR TIMEOUT HAPPENS, RECONNECT AND RESUME FROM AWTSMOOSDB HISTORY AND THE LATEST MUSTCALLNEXT.',
  'THE MISSION CONTINUES UNTIL USER CANCEL, SAFETY BLOCK, LEASE EXPIRATION, FATAL CORRUPTION, TOOL ACCESS LOSS, OR USER-APPROVED RELEASE.'
]);
function upper(s) { return String(s || '').toUpperCase(); }
function text(extra = '') { return [upper(extra), ...LINES, ...Covenant.QUESTIONS].filter(Boolean).join(' '); }
function attach(out = {}) {
  const tunnelInstruction = text(out.tunnelInstruction || '');
  return {
    ...out,
    tunnelInstruction,
    plainEnglishMissionRules: LINES,
    checkpointMessage: out.checkpointMessage || Covenant.checkpointMessage()
  };
}
module.exports = { LINES, text, attach };
