// B"H
function createBossProtocol(env){
  function defaults(input={}){return {enabled:input.bossProtocol===true||input.bossProtocol==='true'||input.selfBoss===true||input.selfBoss==='true',minimumCycles:env.num(input.minimumProtocolCycles,12),minimumIdeasPerBrainstorm:env.num(input.minimumIdeasPerBrainstorm,50),minimumStagesPerCycle:8,currentCycle:1,currentStage:env.ProtocolStages.first(),startedAt:env.now(),answers:[]};}
  function ensureBossProtocol(m,input={}){m.bossProtocol ||= defaults(input);m.protocolCycles ||= [];if(!m.protocolCycles.length)startCycle(m,1);return m.bossProtocol;}
  function start(m,input={}){m.bossProtocol=defaults({...input,bossProtocol:true});m.protocolCycles=[];startCycle(m,1);env.ContinuationQueue.ensure(m);return protocolStatus(m);}
  function startCycle(m,no){m.protocolCycles ||= [];const existing=m.protocolCycles.find(c=>c.cycleNo===no);if(existing)return existing;const cycle={id:`protocol_cycle_${String(no).padStart(3,'0')}`,cycleNo:no,stages:{},createdAt:env.now()};m.protocolCycles.push(cycle);return cycle;}
  function currentCycle(m){ensureBossProtocol(m);return m.protocolCycles.find(c=>c.cycleNo===m.bossProtocol.currentCycle)||startCycle(m,m.bossProtocol.currentCycle);}
  function stageContent(m,stage,input={}){if(input.content)return String(input.content);if(stage==='WILD_BRAINSTORM')return wild(input.count||m.bossProtocol?.minimumIdeasPerBrainstorm||50);return [`# ${stage}`,env.ProtocolPrompts.prompt(stage),input.note||'',input.proof||''].filter(Boolean).join('\n\n');}
  function wild(count){return Array.from({length:Math.max(50,Number(count)||50)},(_,i)=>`${i+1}. Improvement ${i+1}: strengthen boss protocol from angle ${i%10} with tests, artifacts, gates, queue, and proof.`).join('\n');}
  function runStage(config,m,input={}){ensureBossProtocol(m,input);const stage=input.stage||m.bossProtocol.currentStage||env.ProtocolStages.first();const cycle=currentCycle(m);if(!env.ProtocolStages.canRun(cycle,stage))return {ok:false,error:'stage_prerequisites_missing',stage,missing:env.ProtocolStages.prerequisites(stage).filter(x=>!cycle.stages?.[x]?.complete)};const content=stageContent(m,stage,input);const meta={ideaCount:env.ProtocolQueue.ideasFromText(content).length,fileCount:(content.match(/geelooy\/apps\/tunnel/g)||[]).length,proof:input.proof,novelty:input.novelty,riskReduction:input.riskReduction};const score=env.ProtocolScoring.scoreStage(stage,content,meta);const artifact=env.ProtocolArtifacts.write(config,m,m.bossProtocol.currentCycle,env.ProtocolStages.artifactName(stage),content);const rec={stage,complete:env.ProtocolScoring.pass(score),artifact,score,at:env.now(),contentPreview:content.slice(0,500)};cycle.stages[stage]=rec;if(stage==='WILD_BRAINSTORM')rec.queuedIdeas=env.ProtocolQueue.feed(m,env,content).length;if(stage==='STAGE_REVIEW')rec.review=env.ProtocolReview.review(input);advance(m,stage);env.event(m,'boss_protocol_stage',stage,{cycleNo:cycle.cycleNo,complete:rec.complete,artifact:artifact.relative});return {ok:true,stage:rec,protocol:protocolStatus(m),gate:env.ProtocolGates.gate(m.bossProtocol,cycle,stage)};}
  function advance(m,stage){const n=env.ProtocolStages.next(stage);if(n===env.ProtocolStages.first()){m.bossProtocol.currentCycle+=1;m.bossProtocol.currentStage=n;startCycle(m,m.bossProtocol.currentCycle);return;}m.bossProtocol.currentStage=n;}
  function protocolAnswer(m,input={}){ensureBossProtocol(m,input);const parsed=env.ProtocolGates.parse(input.multipleChoiceAnswer||input.answer||input.choice);if(!parsed.ok)return {ok:false,error:'protocol_answer_must_be_one_exact_letter',parsed};const entry={at:env.now(),cycle:m.bossProtocol.currentCycle,stage:input.stage||m.bossProtocol.currentStage,answer:parsed.key};m.bossProtocol.answers.push(entry);env.event(m,'boss_protocol_answer',parsed.key,entry);return {ok:true,parsed,entry,next:protocolNext(m)};}
  function protocolNext(m){ensureBossProtocol(m);const cycle=currentCycle(m);return {action:'missionProtocolStage',missionId:m.id,cycle:m.bossProtocol.currentCycle,stage:m.bossProtocol.currentStage,prompt:env.ProtocolPrompts.prompt(m.bossProtocol.currentStage),artifact:env.ProtocolStages.artifactName(m.bossProtocol.currentStage),gate:env.ProtocolGates.gate(m.bossProtocol,cycle,m.bossProtocol.currentStage)};}
  function protocolStatus(m){ensureBossProtocol(m);const current=currentCycle(m);const completedCycles=(m.protocolCycles||[]).filter(c=>env.ProtocolStages.completeCycleStages(c.stages)).length;return {enabled:m.bossProtocol.enabled,currentCycle:m.bossProtocol.currentCycle,currentStage:m.bossProtocol.currentStage,minimumCycles:m.bossProtocol.minimumCycles,completedCycles,currentCycleComplete:env.ProtocolStages.completeCycleStages(current.stages),latestGateAnswered:(m.bossProtocol.answers||[]).length>0,cycles:m.protocolCycles.length,nextAction:{action:'missionProtocolStage',missionId:m.id,cycle:m.bossProtocol.currentCycle,stage:m.bossProtocol.currentStage}};}
  return {defaults,ensureBossProtocol,start,runStage,protocolAnswer,protocolNext,protocolStatus};
}
module.exports={createBossProtocol};
