// B"H
const crypto = require('crypto');
function now(){return new Date().toISOString();}
function id(prefix){return `${prefix}_${Date.now().toString(36)}_${crypto.randomBytes(3).toString('hex')}`;}
function arr(v){return Array.isArray(v)?v:(v?[String(v)]:[]);}
function task(m,title,kind='expansion'){const t={id:id('task'),title,status:'open',kind,createdAt:now(),evidence:[]};m.tasks ||= [];m.tasks.push(t);return t;}
function ev(m,claim,kind='inference'){const e={id:id('evidence'),kind,claim,ok:false,confidence:'assumed',at:now()};m.evidence ||= [];m.evidence.push(e);return e;}
const FAMILIES=['tests','documentation','research','architecture','performance','security','reliability','ux','observability','deployment','future-evolution'];
const QUESTIONS=['What assumption did this action make?','What evidence would disprove completion?','What test is still missing?','What documentation would another agent need?','What hidden dependency appeared?','What performance or scale risk remains?','What security or destructive-action risk remains?','What should be checkpointed before continuing?'];
function ensureExpansionState(m){m.expansions ||= [];m.plannedActualDeltas ||= [];m.evidenceDebt ||= [];m.improvementPlans ||= [];m.missionFamilies ||= [];return m;}
function families(m){ensureExpansionState(m);const have=new Set(m.missionFamilies.map(f=>f.name));const made=[];for(const name of FAMILIES){if(have.has(name))continue;const f={id:id('family'),name,status:'open',createdAt:now(),tasks:[]};m.missionFamilies.push(f);f.tasks.push(task(m,`Inspect ${name} gaps for mission: ${m.goal}`,'family').id);made.push(f);}return made;}
function evidenceDebt(m){ensureExpansionState(m);const debt=[];for(const e of (m.evidence||[])){if(e.confidence==='assumed'||e.ok===false){const d={id:id('debt'),evidenceId:e.id,claim:e.claim,need:'replace assumption with observed proof',createdAt:now()};m.evidenceDebt.push(d);debt.push(d);task(m,`Prove or falsify evidence claim: ${e.claim}`,'evidence-debt');}}if(!(m.evidence||[]).length){const e=ev(m,'mission has no observed evidence yet','missing-evidence');debt.push({id:id('debt'),evidenceId:e.id,claim:e.claim,need:'record observed proof',createdAt:now()});task(m,'Record first observed evidence for mission','evidence-debt');}return debt;}
function planDelta(m,input={}){ensureExpansionState(m);const planned=arr(input.planned||input.plan||m.definitionOfDone);const actual=arr(input.actual||input.done||(m.tasks||[]).filter(t=>t.status==='done').map(t=>t.title));const missing=planned.filter(x=>!actual.some(y=>String(y).toLowerCase().includes(String(x).toLowerCase())));const d={id:id('delta'),planned,actual,missing,createdAt:now()};m.plannedActualDeltas.push(d);for(const item of missing)task(m,`Complete planned-vs-actual missing item: ${item}`,'planned-actual');return d;}
function expansionQuestions(m){return QUESTIONS.map(text=>({id:id('expq'),text,choices:['A covered with proof','B missing work remains','C blocked with proof','D unsafe/destructive'],requiredWhenUnproven:'B',createdAt:now()}));}
function expand(m,input={}){ensureExpansionState(m);const madeFamilies=families(m);const debt=evidenceDebt(m);const delta=planDelta(m,input);const questions=expansionQuestions(m);m.questions ||= [];m.questions.push(...questions);const shadow=['Add/verify tests','Write/update docs','Run self-review','Checkpoint/handoff','Search hidden dependencies'].map(x=>task(m,`${x} after latest work on: ${m.goal}`,'shadow'));const run={id:id('expansion'),createdAt:now(),families:madeFamilies.length,evidenceDebt:debt.length,missing:delta.missing,questions:questions.length,shadowTasks:shadow.length};m.expansions.push(run);return run;}
function improvementPlan(m,input={}){ensureExpansionState(m);const ideas=['Simplify architecture','Add stronger stress tests','Improve observability','Document recovery path','Automate post-deploy verification','Reduce 504 risk','Audit security/destructive actions','Improve UX/error messages'];const plan={id:id('improve'),createdAt:now(),mode:input.mode||'post-completion',ideas:ideas.map(title=>({title,status:'proposed'}))};m.improvementPlans.push(plan);for(const idea of ideas)task(m,`Improvement: ${idea}`,'improvement');return plan;}
function postCompletion(m,input={}){const verification=input.verification||'post-completion improvement mode';const e=ev(m,verification,'post-completion-review');const ex=expand(m,input);const plan=improvementPlan(m,{mode:'after-completion'});m.status='active';return {evidence:e,expansion:ex,improvementPlan:plan,message:'Completion opened improvement mode; continue until new work is verified.'};}
module.exports={ensureExpansionState,families,evidenceDebt,planDelta,expand,improvementPlan,postCompletion};
