// B"H
/** @file InputInteract.js @description Stable NPC selection; door taps route to doors without erasing friendly target. */
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=door-roof-target-20260708-bh2";
import { toggleNearestDoor } from "../../worlds/mitzvahWorld/region/houses/door/DoorInteractionRuntime.js?compact=true&v=door-wall-source-fix-20260708-bh4";
import { clearTarget } from "./InputTargeting.js?compact=true&v=door-roof-target-20260708-bh2";
import { nearPlayer, positionOf } from "./InputTrace.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
const tmp=new THREE.Vector3();
function pos(e){if(e?.raycastMesh?.getWorldPosition)return e.raycastMesh.getWorldPosition(tmp.clone());if(e?.interactionMesh?.getWorldPosition)return e.interactionMesh.getWorldPosition(tmp.clone());if(e?.mesh?.getWorldPosition)return e.mesh.getWorldPosition(tmp.clone());return positionOf(e);}
function playerPos(o){return pos(o?.player||o?.chossid);}function dist(a,b){return a&&b&&a.distanceTo?a.distanceTo(b):Infinity;}function source(p={}){return String(p.source||p.type||"");}function isDoorTap(p={}){return /door|mobile-door-tap/i.test(source(p));}
function isDoor(n){return n?.type==="interactiveDoor"||n?.type==="cottageDoor"||n?.interactionKind==="door"||n?.doorState;}
function interactRouteDoor(o,p={}){const pp=playerPos(o);let best=null,bestD=Infinity;for(const n of o.interactableNivrayim||[]){if(!isDoor(n))continue;const d=dist(pp,pos(n));if(d<bestD){best=n;bestD=d;}}if(!best||bestD>Number(best.proximity||best.interactionRadius||10.5))return false;const result=best.ayshPeula?.("accepted interaction",{...(p||{}),player:o.player||o.chossid,explicit:true,source:p.source||"mobile-interact-nearest-door",distance:bestD,directDoor:true});o.__lastDoorTapInteract={at:Date.now(),door:best.name||best.doorState?.id,distance:bestD,source:source(p),result:Boolean(result)};return result!==false;}
function interactNpc(o,p={}){if(isDoorTap(p))return false;const npc=o?.__selectedFriendlyNpc;if(!npc||npc.interactable===false)return false;const actor={...(p||{}),type:"contextmenu",contextMenu:true,explicit:true,isPointer:true,directHit:true,source:p.source||"interact",player:o.player||o.chossid};const range=Number(npc.talkDistance||npc.proximity||7);if(!nearPlayer(o,npc,range)){o.__lastNpcTooFar={at:Date.now(),npc:npc.name,range};o.ayshPeula?.("ui event","effectsOverlay",{text:"Move closer.",color:"#ffd966",replace:true});return true;}return npc.openGuideMenu?.(actor,true)||npc.ayshPeula?.("accepted interaction",actor)||true;}
export function interact(o,p={}){if(isDoorTap(p)){clearTarget(o,"door-not-combat");if(interactRouteDoor(o,p))return true;if(toggleNearestDoor(o))return true;}if(interactNpc(o,p))return true;if(interactRouteDoor(o,p))return true;if(toggleNearestDoor(o))return true;o.ayshPeula?.("ui event","effectsOverlay",{text:"NOTHING TO INTERACT",color:"#ffd966"});return false;}
export { toggleNearestDoor };
