// B"H
/** @file InputTargeting.js @description Exact ray targeting: no projected NPC fallback from empty air. */
import * as THREE from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
import PointerUpdater from "../../methods/interaction/PointerUpdater.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { ownerFromHit, raycastTargets } from "../../methods/helpers/mouse/MouseRaycastTargets.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { selectNpcTarget, isNpcTargeted } from "../../../dvarim/npc/NpcTargetRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();const TAP_MAX_PX=18,TAP_MAX_MS=750,SYNTH_MOUSE_BLOCK_MS=900;const now=()=>Date.now();
function selected(o){return o?.__selectedFriendlyNpc||o?.currentTarget||o?.targetedNivra||null;}function cameraOf(o){return o?.ayin?.camera||o?.camera||o?.activeCamera||null;}function sizeOf(o){const e=o?.renderer?.domElement;return{w:o?.width||e?.clientWidth||innerWidth||1,h:o?.height||e?.clientHeight||innerHeight||1};}
function xyOf(p={}){const t=p.changedTouches?.[0]||p.touches?.[0]||p;return{x:Number(t.clientX??t.x),y:Number(t.clientY??t.y)};}function kind(src="",p={}){const s=String(src||p.source||p.type||"").toLowerCase();if(/touchstart|pointerdown/.test(s))return"down";if(/touchend|pointerup|mouseup|tap|click|mousedown|combatselectpointer/.test(s))return"up";return"other";}function touch(src,p){return Boolean(p.isTouch||p.touches||p.changedTouches||/touch|mobile|tap|pointer/.test(String(src||p.source||p.type||"").toLowerCase()));}
function gid(o){o.__npcGestureSeq=Number(o.__npcGestureSeq||0)+1;return`g${o.__npcGestureSeq}_${now()}`;}function recordDown(o,p,src){const xy=xyOf(p);if(Number.isFinite(xy.x))o.__npcTapStart={x:xy.x,y:xy.y,at:now(),source:src,gestureId:gid(o)};return false;}
function duplicate(o,src,p){if(touch(src,p))return false;const l=o.__lastTouchNpcGesture;if(!l)return false;const xy=xyOf(p),age=now()-Number(l.at||0),m=Number.isFinite(xy.x)?Math.hypot(xy.x-l.x,xy.y-l.y):0;return age<SYNTH_MOUSE_BLOCK_MS&&m<28;}
function clean(o,p,src){if(duplicate(o,src,p))return null;if(!touch(src,p))return{ok:true,gestureId:gid(o),...xyOf(p)};const st=o.__npcTapStart,xy=xyOf(p);o.__npcTapStart=null;if(!st)return{ok:true,gestureId:gid(o),...xy};const moved=Math.hypot(xy.x-st.x,xy.y-st.y),age=now()-st.at,ok=moved<=TAP_MAX_PX&&age<=TAP_MAX_MS;if(ok)o.__lastTouchNpcGesture={at:now(),x:xy.x,y:xy.y,gestureId:st.gestureId,source:src};return ok?{ok,gestureId:st.gestureId,...xy,age,moved}:null;}
function npcAtPointer(o,p={},src="tap"){const cam=cameraOf(o),xy=xyOf(p),s=sizeOf(o);if(!cam||!Number.isFinite(xy.x)||!Number.isFinite(xy.y))return null;pointer.x=xy.x/s.w*2-1;pointer.y=-(xy.y/s.h)*2+1;raycaster.setFromCamera(pointer,cam);let hit=null;try{hit=raycaster.intersectObjects(raycastTargets(o,"interaction"),false).find(h=>h.object?.userData?.tightNpcTapProxy||h.object?.userData?.selectableTarget)||null;}catch(e){o.__lastNpcRaycastError=String(e?.message||e);}const npc=ownerFromHit(hit);if(!npc||(!npc.friendlyNpc&&!npc.selectableTarget))return null;npc.__lastPointerHitDirect=true;return npc;}
function openNpc(n,o,p,src,g){const actor={...p,source:src,type:src,isTouch:touch(src,p),directHit:true,cleanTap:true,secondTap:true,gestureId:g.gestureId,player:o.player||o.chossid};n.__lastOpenGestureId=g.gestureId;o.__lastNpcTapSelection={at:now(),source:src,name:n.name,opened:true,gestureId:g.gestureId,proof:"exact-hit-second-tap-only-bh1"};return n.openGuideMenu?.(actor,true)||n.ayshPeula?.("accepted interaction",actor)||true;}
function targetOrOpen(o,p,src,g){const npc=npcAtPointer(o,p,src);if(!npc)return false;if(isNpcTargeted(o,npc)&&npc.__selectedGestureId!==g.gestureId)return openNpc(npc,o,p,src,g);selectNpcTarget(npc,{source:src,type:src,isTouch:touch(src,p),directHit:true,cleanTap:true,gestureId:g.gestureId});npc.__selectedGestureId=g.gestureId;o.__lastNpcTapSelection={at:now(),source:src,name:npc.name,hit:true,opened:false,gestureId:g.gestureId};return true;}
export function updatePointerFromPacket(o,p={}){const xy=xyOf(p);if(Number.isFinite(xy.x))PointerUpdater.update(o,xy.x,xy.y);return{x:o.pointer?.x,y:o.pointer?.y};}
export function clearTarget(o,reason){o.combatManager?.targeting?.set?.(null);o.__selectedCombatTarget=null;o.__lastCombatTargetClear={at:now(),reason};return true;}
export function selectFromTap(o,p={},src="tap"){const pt=updatePointerFromPacket(o,p),k=kind(src,p);if(k==="down"&&touch(src,p))return recordDown(o,p,src);const g=clean(o,p,src);if(!g)return false;if(targetOrOpen(o,p,src,g))return true;const result=o.combatManager?.selectTargetFromPointer?.({source:src,isTouch:touch(src,p)});o.__lastCombatTapSelection={at:now(),source:src,result,pointer:pt,isTouch:touch(src,p),gestureId:g.gestureId};return result==="selected"||result==="confirmed";}
