// B"H
/**
 * Shared inline Awtsmoos mail composer.
 * The Awtsmoos speaks through one contract-safe vessel: alias, recipient,
 * subject, body, URLSearchParams, announced outcomes, focus return, fallback.
 */
const SEND_BASE = '/api/social/mail/sendTo';
function cleanAlias(value){return String(value||'').trim().replace(/^@/,'');}
function option(alias, selected){const id=cleanAlias(alias?.id||alias);return new Option(`@${id}${id===selected?' — default':''}`,id,false,id===selected);}
function fallbackHref(to=''){return `/email${to?`?to=${encodeURIComponent(cleanAlias(to))}`:''}`;}
function setStatus(node, tone, text){node.dataset.tone=tone;node.textContent=text;}
function updateDisabled(form){const from=cleanAlias(form.fromAlias.value),to=cleanAlias(form.toAlias.value);form.querySelector('[data-inline-message-send]').disabled=!(from&&to);form.querySelector('[data-inline-message-fallback]').href=fallbackHref(to);}
async function send(form,status){const from=cleanAlias(form.fromAlias.value),to=cleanAlias(form.toAlias.value);if(!from||!to)return setStatus(status,'error','Choose a sender alias and recipient first.');setStatus(status,'loading','Sending living transmission…');const url=`${SEND_BASE}/${encodeURIComponent(to)}/from/${encodeURIComponent(from)}`;const body=new URLSearchParams({subject:form.subject.value||'',content:form.body.value||''});const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const data=await res.json().catch(()=>({}));if(!res.ok||data.error)throw new Error(data.error?.message||data.message||res.statusText||'Message failed.');setStatus(status,'success','Transmission sent. Email route remains available below.');form.body.value='';}
export function inlineMessaging({aliases=[],defaultAlias='',to='',opener=null,onClose=null}={}){const box=document.createElement('form');box.className='inline-message-composer';box.innerHTML=`<label>From alias<select name="fromAlias" data-inline-message-from></select></label><label>Recipient alias<input name="toAlias" autocomplete="username" placeholder="recipient alias"></label><label>Subject<input name="subject" placeholder="Subject"></label><label>Body<textarea name="body" rows="5" placeholder="Write the transmission..."></textarea></label><p class="g-social-status" data-inline-message-status aria-live="polite"></p><div class="inline-message-actions"><button class="g-social-button primary" type="submit" data-inline-message-send>Send transmission</button><a class="g-social-button" data-inline-message-fallback href="/email">Open full mail</a></div>`;const ids=aliases.map(a=>cleanAlias(a?.id||a)).filter(Boolean);if(defaultAlias&&!ids.includes(cleanAlias(defaultAlias)))ids.unshift(cleanAlias(defaultAlias));box.fromAlias.replaceChildren(...ids.map(id=>option(id,cleanAlias(defaultAlias))));box.toAlias.value=cleanAlias(to);const status=box.querySelector('[data-inline-message-status]');box.addEventListener('input',()=>updateDisabled(box));box.addEventListener('keydown',e=>{if(e.key==='Escape')onClose?.(opener);});box.addEventListener('submit',async e=>{e.preventDefault();try{await send(box,status);}catch(err){setStatus(status,'error',err.message);}});updateDisabled(box);return box;}
export { SEND_BASE, fallbackHref };
