// B"H
/** Remaining safe API sweep beyond the full mutation harness. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const DosDB = require('../../ayzarim/DosDB/index.js');
const { createApiKey } = require('../../geelooy/api/social/helper/apiKeys.js');
const origin = 'http://127.0.0.1:8080';
const repo = process.cwd();
const dbRoot = path.resolve(repo, '../../dayuhChadash');
const run = `ars${Date.now().toString(36).slice(-8)}`;
const ids = { user:`${run}_u`, owner:`${run}_own`, editor:`${run}_ed`, outsider:`${run}_out`, heichel:`${run}_h`, series:`${run}_s`, post:`${run}_p`, note:'' };
const report = { BH:'B"H', run, pass:[], blocked:[], fail:[], routeInventory:{ total:0, sample:[] }, cleanup:[] };
const pass=(name,d={})=>report.pass.push({name,...d});
const block=(name,d={})=>report.blocked.push({name,...d});
const fail=(name,e,d={})=>report.fail.push({name,error:String(e?.stack||e),...d});
async function key(){const db=new DosDB(dbRoot);await db.init();const made=await createApiKey({$i:{db,request:{user:{info:{userId:ids.user}},headers:{}},$_POST:{label:'remaining sweep'}},userid:ids.user});return made.success.key;}
async function req(route,{method='GET',data=null,apiKey=''}={}){const final=apiKey&&data?{apiKey,...data}:data;const r=await fetch(origin+route,{method,headers:{...(apiKey?{authorization:`Bearer ${apiKey}`,'x-awtsmoos-api-key':apiKey}:{}),...(final?{'content-type':'application/x-www-form-urlencoded'}:{})},body:final?new URLSearchParams(final).toString():undefined,redirect:'follow'});const text=await r.text();let json;try{json=text?JSON.parse(text):null}catch{json={raw:text.slice(0,300)}}return{status:r.status,ok:r.status>=200&&r.status<300,json,text};}
const good=r=>r.ok&&!r.json?.error;
async function must(name,p,check=()=>true){const r=await p;assert.ok(good(r),`${name} ${r.status} ${r.text}`);assert.ok(check(r),`${name} check ${r.text}`);pass(name,{status:r.status});return r;}
async function maybe(name,p,check=()=>true){const r=await p;if(good(r)&&check(r))pass(name,{status:r.status});else block(name,{status:r.status,text:String(r.text).slice(0,400)});return r;}
async function expectReject(name,p){const r=await p;if(!good(r)||r.json?.error||r.json?.ok===false)pass(name,{status:r.status,expectedReject:true,code:r.json?.error?.code||r.json?.code||null});else block(name,{status:r.status,text:'Expected rejection but accepted'});return r;}
function routeInventory(){const files=fs.readdirSync('geelooy/api/social').filter(f=>f.startsWith('_awtsmoos')&&f.endsWith('.js'));const routes=[];for(const f of files){const s=fs.readFileSync(`geelooy/api/social/${f}`,'utf8');for(const m of s.matchAll(/["'`]\/(?:[^"'`\\]|\\.)+["'`]\s*:/g)){routes.push({file:f,route:m[0].slice(1).split(/["'`]/)[0]});}}report.routeInventory.total=routes.length;report.routeInventory.sample=routes.slice(0,80);fs.writeFileSync('AI_TEMP/api_full_stress/route-inventory.json',JSON.stringify(routes,null,2));pass('route inventory generated',{routes:routes.length});}
async function seed(apiKey){await must('seed owner alias',req('/api/social/aliases',{method:'POST',apiKey,data:{aliasName:'Remaining Owner',inputId:ids.owner,description:run}}));await must('seed editor alias',req('/api/social/aliases',{method:'POST',apiKey,data:{aliasName:'Remaining Editor',inputId:ids.editor,description:run}}));await must('seed outsider alias',req('/api/social/aliases',{method:'POST',apiKey,data:{aliasName:'Remaining Outsider',inputId:ids.outsider,description:run}}));await must('seed heichel',req(`/api/social/alias/${ids.owner}/heichelos`,{method:'POST',apiKey,data:{aliasId:ids.owner,inputId:ids.heichel,heichelId:ids.heichel,name:run,heichelName:run,description:run,isPublic:'yes'}}));await must('seed series',req(`/api/social/heichelos/${ids.heichel}/addNewSeries`,{method:'POST',apiKey,data:{aliasId:ids.owner,inputId:ids.series,seriesId:ids.series,seriesName:run,title:run,parentSeriesId:'root',description:run}}));await must('seed post',req(`/api/social/content/heichelos/${ids.heichel}/posts`,{method:'POST',apiKey,data:{aliasId:ids.owner,postId:ids.post,title:run,content:run,seriesId:ids.series,sections:JSON.stringify([{id:`${run}_sec`,title:run,content:run}])}}));}
async function methodGuards(apiKey){await expectReject('method guard meta POST',req('/api/social/meta',{method:'POST'}));await expectReject('method guard search POST',req('/api/social/search',{method:'POST'}));await expectReject('method guard bulk GET',req('/api/social/bulk'));await expectReject('method guard content posts GET',req(`/api/social/content/heichelos/${ids.heichel}/posts`));await expectReject('method guard profile history PUT',req(`/api/social/profiles/${ids.owner}/history`,{method:'PUT'}));await expectReject('method guard followers POST',req(`/api/social/followers/alias/${ids.owner}`,{method:'POST'}));}
async function compatibility(apiKey){await expectReject('v2 social meta is gone',req('/api/v2/social/meta'));await expectReject('v2 social openapi is gone',req('/api/v2/social/openapi.json'));await must('compat legacy profile batch',req(`/api/social/profile/batch?aliases=${ids.owner}`),r=>r.json.ok);await must('compat legacy profile feed',req(`/api/social/profile/feed?aliases=${ids.owner}`),r=>r.json.ok);await must('compat old heichel read',req(`/api/social/heichelos/${ids.heichel}`));await must('compat old series details',req(`/api/social/heichelos/${ids.heichel}/series/${ids.series}/details`));await must('compat old sections read',req(`/api/social/content/heichelos/${ids.heichel}/posts/${ids.post}/sections`));}
async function notifications(apiKey){const n=await must('notify create extra',req(`/api/social/notifications/${ids.owner}`,{method:'POST',apiKey,data:{fromAliasId:ids.editor,type:'remaining',title:run,body:run,entity:JSON.stringify({run}),actionUrl:'/'}}));ids.note=n.json?.success?.id||n.json?.details?.id||n.json?.id||'';await must('notify list unread/all',req(`/api/social/notifications/${ids.owner}?includeRead=yes`,{apiKey}));if(ids.note){await maybe('notify mark read',req(`/api/social/notifications/${ids.owner}/${ids.note}/read`,{method:'POST',apiKey,data:{aliasId:ids.owner,notificationId:ids.note}}));await must('notify unread count',req(`/api/social/notifications/${ids.owner}/unread/count`,{apiKey}));await must('notify poll',req(`/api/social/notifications/${ids.owner}/poll?since=0`,{apiKey}));}else block('notify id unavailable');}
async function keysAndPlatform(apiKey){await must('keys verify valid',req('/api/social/keys/verify',{apiKey}));await expectReject('keys verify invalid',req('/api/social/keys/verify?apiKey=bad_bad_bad'));await must('platform feed home smoke',req(`/api/social/feed/home?aliasId=${ids.owner}&limit=3`));await must('platform feed trending smoke',req('/api/social/feed/trending?limit=3'));await expectReject('platform cache get missing returns CACHE_MISS',req('/api/social/cache/get?key=missing_remaining_sweep'));await must('migrations dryRun safe',req(`/api/social/migrations/posts/v2/dryRun?heichelId=${ids.heichel}&seriesId=${ids.series}`));}
async function governanceNegatives(apiKey){await expectReject('governance outsider add editor fail',req(`/api/social/heichelos/${ids.heichel}/editors`,{method:'POST',apiKey,data:{aliasId:ids.outsider,editorAliasId:ids.editor}}));await expectReject('governance outsider settings fail',req(`/api/social/heichelos/${ids.heichel}/settings/submissions`,{method:'POST',apiKey,data:{aliasId:ids.outsider,settings:JSON.stringify({allowPublicSubmissions:false,run})}}));await maybe('governance owner settings still ok',req(`/api/social/heichelos/${ids.heichel}/settings/submissions`,{method:'POST',apiKey,data:{aliasId:ids.owner,settings:JSON.stringify({allowPublicSubmissions:true,run})}}));}
async function residueTextScan(){const names=[];function walk(d){if(!fs.existsSync(d))return;for(const n of fs.readdirSync(d)){const p=path.join(d,n);if(n.includes(run))names.push(p);else if(fs.statSync(p).isDirectory())walk(p)}}walk(dbRoot);for(const p of names.sort((a,b)=>b.length-a.length)){if(fs.existsSync(p)){fs.rmSync(p,{recursive:true,force:true});report.cleanup.push(p)}}const after=[];walk(dbRoot);if(after.length)block('residue filename remains',{after});else pass('residue filename clean',{removed:report.cleanup.length});const grep=await new Promise(res=>{const cp=require('child_process').spawn('grep',['-RIl',run,`${dbRoot}/social`]);let out='';cp.stdout.on('data',d=>out+=d);cp.on('close',()=>res(out.trim().split('\n').filter(Boolean).slice(0,20)));});if(grep.length)block('residue text scan found references',{grep});else pass('residue text scan clean');}
async function cleanup(apiKey){await maybe('cleanup delete seeded post',req(`/api/social/heichelos/${ids.heichel}/series/${ids.series}/post/${ids.post}`,{method:'DELETE',apiKey,data:{aliasId:ids.owner}}));await maybe('cleanup delete seeded series',req(`/api/social/heichelos/${ids.heichel}/series/root/deleteSubSeries/${ids.series}`,{method:'DELETE',apiKey,data:{aliasId:ids.owner}}));await maybe('cleanup delete seeded heichel',req(`/api/social/alias/${ids.owner}/heichelos/${ids.heichel}`,{method:'DELETE',apiKey,data:{aliasId:ids.owner}}));await residueTextScan();}
async function main(){routeInventory();const apiKey=await key();try{await seed(apiKey);await methodGuards(apiKey);await compatibility(apiKey);await notifications(apiKey);await keysAndPlatform(apiKey);await governanceNegatives(apiKey);}catch(e){fail('remaining sweep exception before cleanup',e)}finally{await cleanup(apiKey).catch(e=>fail('cleanup exception',e))}console.log(JSON.stringify(report,null,2));if(report.fail.length)process.exit(1);}
main();
