// B"H
/** @file BuySellRuntime.js @description Peruta transactions with trainer gates, repair, upgrade, and receipts. */
import { merchantProfile, merchantItems } from "./MerchantInventoryRuntime.js";
import { buyPrice, sellPrice, repairPrice } from "./PerutaPricingRuntime.js";
import { weaponStats } from "../../equipment/runtime/WeaponStatCatalog.js";
export class BuySellRuntime {
  constructor(runtime,wallet){ this.runtime=runtime; this.wallet=wallet; this.history=[]; this.inventory=new Map([["player",[]]]); this.conditions=new Map(); }
  inv(actorId="player"){ if(!this.inventory.has(actorId)) this.inventory.set(actorId,[]); return this.inventory.get(actorId); }
  itemFor(merchantId,itemId){ return merchantItems(merchantId).find(x=>x.id===itemId)||weaponStats(itemId)||null; }
  gate(actorId,item){ return this.runtime?.trainers?.canUse?.(actorId,item) || {ok:true,missing:[]}; }
  record(tx){ this.history.push({...tx,at:Date.now()}); this.history=this.history.slice(-200); return tx; }
  buy(actorId="player",merchantId="blacksmith",itemId){ const merchant=merchantProfile(merchantId), item=this.itemFor(merchantId,itemId); if(!item) return this.record({ok:false,reason:"missing-item",actorId,merchantId,itemId}); const gate=this.gate(actorId,item); if(!gate.ok) return this.record({ok:false,reason:"trainer-required",actorId,merchantId,itemId,gate}); const price=buyPrice(item,merchant), paid=this.wallet.spend(actorId,price,`buy:${itemId}`); if(!paid.ok) return this.record({ok:false,reason:"not-enough-perutas",actorId,merchantId,itemId,price,balance:paid.balance}); this.inv(actorId).push(itemId); this.conditions.set(`${actorId}:${itemId}`, item.condition??1); return this.record({ok:true,type:"buy",actorId,merchantId,itemId,price,balance:paid.balance}); }
  sell(actorId="player",merchantId="blacksmith",itemId){ const inv=this.inv(actorId), index=inv.indexOf(itemId); if(index<0) return this.record({ok:false,reason:"not-owned",actorId,merchantId,itemId}); const merchant=merchantProfile(merchantId), item=this.itemFor(merchantId,itemId)||{id:itemId,buy:10,sell:5,condition:1}; const price=sellPrice({...item,condition:this.condition(actorId,itemId)},merchant); inv.splice(index,1); const balance=this.wallet.add(actorId,price,`sell:${itemId}`); return this.record({ok:true,type:"sell",actorId,merchantId,itemId,price,balance}); }
  condition(actorId,itemId){ return this.conditions.get(`${actorId}:${itemId}`) ?? (weaponStats(itemId)?.condition ?? 1); }
  damageItem(actorId,itemId,amount=.1){ const key=`${actorId}:${itemId}`, next=Math.max(.05,this.condition(actorId,itemId)-amount); this.conditions.set(key,next); return this.record({ok:true,type:"damage",actorId,itemId,condition:next}); }
  repair(actorId="player",merchantId="blacksmith",itemId){ if(!this.inv(actorId).includes(itemId)) return this.record({ok:false,reason:"not-owned",actorId,merchantId,itemId}); const item={...(this.itemFor(merchantId,itemId)||weaponStats(itemId)||{}),condition:this.condition(actorId,itemId)}, merchant=merchantProfile(merchantId), price=repairPrice(item,merchant), paid=this.wallet.spend(actorId,price,`repair:${itemId}`); if(!paid.ok) return this.record({ok:false,reason:"not-enough-perutas",actorId,itemId,price,balance:paid.balance}); this.conditions.set(`${actorId}:${itemId}`,1); return this.record({ok:true,type:"repair",actorId,merchantId,itemId,price,balance:paid.balance,condition:1}); }
  upgrade(actorId="player",merchantId="blacksmith",itemId){ const item=weaponStats(itemId), nextId=item?.upgradePath?.[0]; if(!nextId) return this.record({ok:false,reason:"no-upgrade",actorId,itemId}); const bought=this.buy(actorId,merchantId,nextId); if(!bought.ok) return {...bought,type:"upgrade"}; this.inv(actorId).splice(this.inv(actorId).indexOf(itemId),1); return this.record({ok:true,type:"upgrade",actorId,merchantId,itemId,nextId,price:bought.price,balance:bought.balance}); }
  snapshot(actorId="player"){ return { actorId, inventory:[...this.inv(actorId)], conditions:Object.fromEntries([...this.conditions].filter(([k])=>k.startsWith(`${actorId}:`))), history:this.history.filter(x=>x.actorId===actorId).slice(-40) }; }
}
export function createBuySellRuntime(runtime,wallet){ return new BuySellRuntime(runtime,wallet); }
export default createBuySellRuntime;
