// B"H
/** @file MerchantInventoryRuntime.js @description Merchants carry weapons, ammo, and clothes through icon-first peruta economy. */
import { WEAPON_STATS, weaponList } from "../../equipment/runtime/WeaponStatCatalog.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { AMMO_ITEMS, ammoList } from "../../equipment/runtime/AmmoCatalog.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { CLOTHING_STATS } from "../../gear/runtime/ClothingStatCatalog.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
const byGenre=(...genres)=>weaponList().filter(w=>genres.includes(w.genre)).map(w=>w.id);
const ammo=(...ids)=>ammoList().filter(a=>!ids.length||ids.includes(a.id)).map(a=>a.id);
const MERCHANTS={ blacksmith:{label:"Blacksmith",icon:"⚒",markup:1.05,sellRate:1,categories:["Blades","Blunt","Tools"],items:[...byGenre("knife","dagger","shortSword","longSword","greatSword","axe","hammer","spear"),"builderHammer"]}, tailor:{label:"Tailor",icon:"🧥",markup:1,sellRate:1,categories:["Clothes"],items:["blackHat","velvetYarmulka","roundGlasses","longCoat","whiteShirt","darkPants","leatherShoes","simpleBelt","workGloves"]}, scribe:{label:"Scribe",icon:"אב",markup:.95,sellRate:1.05,categories:["Letters","Holy"],items:[...byGenre("hebrewBow","holyWeapon","letterWeapon","wand"),"glowingLetterArrow","alefArrow"]}, bowyer:{label:"Bowyer",icon:"🏹",markup:1.1,sellRate:.95,categories:["Ranged","Ammo"],items:[...byGenre("bow","crossbow","sling","throwingStone","hebrewBow"),...ammo()]}, farmer:{label:"Farmer",icon:"🌾",markup:.9,sellRate:1,categories:["Tools","Animals"],items:[...byGenre("farmingTool","stick","sling"),"reedArrow"]}, carpenter:{label:"Carpenter",icon:"🪵",markup:1,sellRate:1,categories:["Tools","Furniture"],items:[...byGenre("craftingTool","hammer","staff"),"woodenStaff","learnerStaff","cedarStaff"]}, trainer:{label:"Trainer",icon:"✦",markup:.85,sellRate:.75,categories:["Training"],items:[...byGenre("hands","trainingWeapon","stick","throwingStone"),"paddedSword"]}, animalSeller:{label:"Animal Seller",icon:"🐐",markup:1.2,sellRate:.85,categories:["Animals"],items:[]}, bookSeller:{label:"Book Seller",icon:"📘",markup:1,sellRate:1,categories:["Books"],items:[]}, furnitureSeller:{label:"Furniture Seller",icon:"🪑",markup:1.15,sellRate:.8,categories:["Furniture"],items:[]}, foodSeller:{label:"Food Seller",icon:"🍎",markup:.9,sellRate:.7,categories:["Food"],items:[]} };
export function merchantProfile(id="blacksmith"){ return {id,supply:1,demand:1,regionMultiplier:1,...(MERCHANTS[id]||MERCHANTS.blacksmith)}; }
export function merchantItems(id="blacksmith"){ const m=merchantProfile(id); return m.items.map(itemId=>({id:itemId,...(WEAPON_STATS[itemId]||AMMO_ITEMS[itemId]||CLOTHING_STATS[itemId]||{}),merchantId:id})); }
export function merchantTypes(){ return Object.keys(MERCHANTS); }
export default {merchantProfile,merchantItems,merchantTypes};
