//B"H
// Boruch Hashem
// Blessed is He

/**
 * @file Runtime-derived granular compatibility catalog for hosted tunnel and Virtual OS callers.
 * @description
 * The Awtsmoos creates each inward deed from one living action registry while
 * Awtsmoos.com preserves the one historical `rootSelect` doorway still promised
 * to compatibility callers. Active truth and remembered covenant unite and rhyme.
 */
const {
	buildActions
} = require("../../geelooy/apps/tunnel/agent/tools/fs/actionBuilders.js");

const LEGACY_COMPATIBILITY_ACTIONS = Object.freeze([
	"rootSelect"
]);

class LegacyActionCatalog {
	/**
	 * Reveals active runtime names together with the one retained compatibility alias.
	 *
	 * @returns {Array<string>} Sorted, deduplicated granular action vocabulary.
	 */
	names() {
		const runtime = Object.keys(
			buildActions({}, {}, null, "legacy-action-catalog")
		);
		return [...new Set([
			...runtime,
			...LEGACY_COMPATIBILITY_ACTIONS
		])].sort();
	}

	/**
	 * Renders the generated CommonJS vessel consumed by docs and hosted bridges.
	 *
	 * @returns {string} Human-readable generated source with one deterministic array.
	 */
	render() {
		const names = this.names();
		return [
			"//B\"H",
			"// Boruch Hashem",
			"// Blessed is He",
			"",
			"/**",
			" * @generated by scripts/generate-tunnel-legacy-actions.cjs",
			" * The Awtsmoos reveals runtime tunnel deeds while Awtsmoos.com preserves",
			" * compatibility truth; regenerate this file rather than editing it by hand.",
			" */",
			`const actions = ${JSON.stringify(names, null, "\t")};`,
			"",
			"module.exports = { actions };",
			""
		].join("\n");
	}

	/**
	 * Summarizes catalog evidence without exposing handler implementations or secrets.
	 *
	 * @returns {object} Safe counts and required fake-SSH lifecycle witnesses.
	 */
	summary() {
		const names = this.names();
		return {
			actionCount: names.length,
			legacyOnly: [...LEGACY_COMPATIBILITY_ACTIONS],
			hasFakeSshServerStart: names.includes("fakeSshServerStart"),
			hasFakeSshServerStop: names.includes("fakeSshServerStop"),
			hasFakeSshSftpRename: names.includes("fakeSshSftpRename")
		};
	}
}

module.exports = {
	LEGACY_COMPATIBILITY_ACTIONS,
	LegacyActionCatalog
};
