// B"H
(function htmlCssTables(root) {
  const tables = root.AwtsEctIdTables = root.AwtsEctIdTables || {};

  /** B"H. Markup and style atoms: tags, attrs, CSS props, units, keywords. */
  tables.tags = "html head body title meta link script style main section article div span p h1 h2 h3 h4 h5 h6 header footer nav aside button output input textarea form label select option optgroup datalist fieldset legend ul ol li dl dt dd a img picture source canvas svg path circle rect line polyline polygon ellipse g defs use symbol table thead tbody tfoot tr td th template slot dialog details summary video audio track iframe figure figcaption pre code blockquote strong em small br hr progress meter time data".split(" ");
  tables.attrs = "id class href src alt title type value name width height viewBox cx cy r d x y x1 y1 x2 y2 fill stroke role aria-label aria-hidden aria-expanded placeholder checked disabled selected readonly multiple min max step pattern required data-key data-id for method action target rel media async defer crossorigin integrity content charset http-equiv lang dir tabindex style hidden".split(" ");
  tables.cssProps = "padding padding-top padding-right padding-bottom padding-left margin margin-top margin-right margin-bottom margin-left border border-width border-style border-color border-radius background background-color background-image background-size background-position color display position top left right bottom gap row-gap column-gap grid-template-columns grid-template-rows grid-column grid-row flex flex-direction flex-wrap justify-content align-items align-content list-style font font-family font-weight font-size line-height letter-spacing text-align text-decoration width height min-width min-height max-width max-height transform transform-origin translate rotate scale transition transition-property transition-duration transition-timing-function animation animation-name animation-duration animation-timing-function animation-iteration-count opacity fill stroke stroke-width box-shadow filter backdrop-filter overflow overflow-x overflow-y z-index cursor pointer-events touch-action user-select object-fit object-position white-space word-break visibility content".split(" ");
  tables.units = ["px", "%", "rem", "em", "deg", "rad", "turn", "fr", "s", "ms", "vh", "vw", "vmin", "vmax", "ch", "ex", "cm", "mm", "in", "pt", "pc"];
  tables.cssKeywords = "block inline inline-block grid inline-grid flex inline-flex none contents flow-root absolute relative fixed sticky static visible hidden auto center start end stretch baseline pointer default solid dashed dotted double transparent currentColor inherit initial unset revert white black red green blue bold normal lighter bolder serif sans-serif monospace uppercase lowercase capitalize nowrap wrap linear-gradient radial-gradient conic-gradient repeat no-repeat cover contain scale rotate translate ease ease-in ease-out ease-in-out alternate infinite forwards backwards both running paused border-box content-box".split(" ");
  tables.cssValueKinds = ["keyword", "color", "dimension", "number", "string", "linearGradient", "shadow", "transform", "calc", "var", "repeat", "url", "function", "pair", "quad"];
})(typeof self !== "undefined" ? self : globalThis);
