// B"H
/** @file DoorInteractionRuntime.js @description Player-facing cottage door open/close/lock runtime. */
import { patchWorldState, readWorldState } from "../../../../../../systems/worldState/WorldStateStore.js";
import { setDoorVisualState } from "./DoorAnimationRuntime.js";
function playerPosition(olam) { return (olam?.player || olam?.chossid)?.mesh?.position || null; }
function dist2(a,b) { const dx=a.x-b.x,dz=a.z-b.z; return dx*dx+dz*dz; }
function toast(olam, message, color="#ffe680") { olam?.ayshPeula?.("ui event", "effectsOverlay", { text:message, color }); }
function doorEntries(root) { const out = []; root?.traverse?.(child => { if (child.userData?.doorHingePivot && child.userData?.doorState) out.push({ pivot:child, state:child.userData.doorState }); }); return out; }
export function nearestDoor(olam, root = olam?.__livingRegionCottageRoot) { const p = playerPosition(olam); if (!p || !root) return null; let best = null, bestD = Infinity; for (const entry of doorEntries(root)) { const wp = entry.pivot.getWorldPosition ? entry.pivot.getWorldPosition(entry.pivot.position.clone()) : entry.pivot.position; const d = dist2(p, wp); if (d < bestD) { best = entry; bestD = d; } } return best && bestD < 16 ? best : null; }
export function openDoor(olam, doorId, root = olam?.__livingRegionCottageRoot) { for (const entry of doorEntries(root)) if (entry.state.id === doorId) { if (entry.state.locked) return toast(olam, "LOCKED", "#ffcc66"), false; entry.state.open = true; setDoorVisualState(root, doorId, entry.state); patchWorldState(olam, `doors.${doorId}`, entry.state); toast(olam, "DOOR OPEN", "#9fffd0"); return true; } return false; }
export function closeDoor(olam, doorId, root = olam?.__livingRegionCottageRoot) { for (const entry of doorEntries(root)) if (entry.state.id === doorId) { entry.state.open = false; setDoorVisualState(root, doorId, entry.state); patchWorldState(olam, `doors.${doorId}`, entry.state); toast(olam, "DOOR CLOSED", "#d8c6a3"); return true; } return false; }
export function unlockDoor(olam, doorId, keyId, root = olam?.__livingRegionCottageRoot) { for (const entry of doorEntries(root)) if (entry.state.id === doorId && entry.state.keyId === keyId) { entry.state.locked = false; patchWorldState(olam, `doors.${doorId}`, entry.state); toast(olam, "UNLOCKED", "#9fffd0"); return true; } return false; }
export function toggleNearestDoor(olam, root = olam?.__livingRegionCottageRoot) { const entry = nearestDoor(olam, root); if (!entry) return toast(olam, "NO DOOR", "#ffd966"), false; const saved = readWorldState(olam, `doors.${entry.state.id}`, entry.state); Object.assign(entry.state, saved); return entry.state.open ? closeDoor(olam, entry.state.id, root) : openDoor(olam, entry.state.id, root); }
export function installDoorInteractionRuntime(olam, cottageRoot) { if (!olam || !cottageRoot) return null; olam.__livingRegionCottageRoot = cottageRoot; cottageRoot.userData ||= {}; cottageRoot.userData.doorRuntimeInstalled = true; cottageRoot.userData.toggleNearestDoor = () => toggleNearestDoor(olam, cottageRoot); return cottageRoot.userData.toggleNearestDoor; }
export default { installDoorInteractionRuntime, toggleNearestDoor, openDoor, closeDoor, unlockDoor };
