// B"H
/** @file interaction.js @description Do not clear NPC target during mobile touch-down; pointerup/click handles second tap. */
import { clearCombatTarget, highlightTarget, isInteractiveTarget, isNpcTarget, selectCombatTarget } from "./ClickTargetPolicy.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { clearFriendlyNpcTarget, explainNpcWait, isNpcTargeted, npcInteractionDecision, selectNpcTarget } from "../../../dvarim/npc/NpcTargetRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
function payload(player,event={},directHit=false){const button=Number.isFinite(Number(event?.button))?Number(event.button):0,type=event?.type||(button===2?"contextmenu":"click"),isTouch=event?.isTouch===true||event?.pointerType==="touch"||String(type).includes("touch")||String(type).includes("pointer");return{type,explicit:true,isPointer:true,isTap:Boolean(event?.isTap||isTouch),isTouch,pointerType:isTouch?"touch":"mouse",button,buttons:Number(event?.buttons||0),contextMenu:button===2||type==="contextmenu",player,event,clientX:event?.clientX,clientY:event?.clientY,directHit,source:"player-click",gestureId:event?.timeStamp||Date.now()};}
function ownerFromHit(object,hit){let cursor=hit?.nivraAwtsmoos||object?.nivraAwtsmoos||object;while(cursor&&!cursor.nivraAwtsmoos&&cursor.parent)cursor=cursor.parent;return cursor?.nivraAwtsmoos||hit?.nivraAwtsmoos||null;}
function setPointerFromEvent(olam,event={}){if(!olam||event.clientX===undefined)return;const r=olam.boundingRect;if(!r)return;olam.pointer.x=((event.clientX-r.left)/r.width)*2-1;olam.pointer.y=-((event.clientY-r.top)/r.height)*2+1;}
function tell(olam,text,color="#8de8ff"){return olam?.ayshPeula?.("ui event","effectsOverlay",{text,color});}
function directClickedNivra(player){const niv=player?.intersected?.niv||null;return niv&&!niv.wasSealayked&&niv.type!=="chossid"?niv:null;}
function clearAll(player,event={}){if(/pointerdown|touchstart/i.test(String(event.type||""))&&player?.olam?.__selectedFriendlyNpc)return true;player.clearNpcTarget?.();clearFriendlyNpcTarget(player?.olam);return false;}
function openInteractiveTarget(player,niv,event,directHit=true){niv.ayshPeula?.("accepted interaction",payload(player,event,directHit));return true;}
function targetNpc(player,niv,p){player.clearNpcTarget();player.targetedNpc=niv;highlightTarget(niv.mesh,true,0xffd95a);selectNpcTarget(niv,p);tell(player.olam,"Target selected. Tap the target again to talk.","#8de8ff");return true;}
function handleNpcClick(player,niv,event){const p=payload(player,event,true),decision=npcInteractionDecision(niv,p);if(decision.action==="target"||!isNpcTargeted(player.olam,niv))return targetNpc(player,niv,p);player.targetedNpc=niv;highlightTarget(niv.mesh,true,0xffd95a);if(decision.action==="wait"){tell(player.olam,decision.message||explainNpcWait(niv,p),"#ffd966");return true;}return openInteractiveTarget(player,niv,event,true);}
export default{actionList:{Delete(self){self?.selected?.niv?.ayshPeula("sealayk");},Grab(self){self?.selected?.niv?.ayshPeula("sealayk");self.removeIntersected();self.makeRay?.();self.placeBlockOnRay?.();}},handleClick(event={}){event?.preventDefault?.();setPointerFromEvent(this.olam,event);this.checkHover?.(this.olam,true);const niv=directClickedNivra(this);if(!niv)return clearAll(this,event);if(isNpcTarget(niv))return handleNpcClick(this,niv,event);this.clearNpcTarget();clearFriendlyNpcTarget(this.olam);if(isInteractiveTarget(niv))return openInteractiveTarget(this,niv,event,true);if(event.button!==2&&selectCombatTarget(this,niv,event))return true;this.selectIntersected?.();return true;},clearNpcTarget(){if(this.targetedNpc?.mesh)highlightTarget(this.targetedNpc.mesh,false);this.targetedNpc=null;clearCombatTarget(this);},async selectIntersected(){if(!this.intersected||this.selected)return;highlightTarget(this.intersected.niv.mesh,true,0xdd0022);this.selected=this.intersected;await tell(this.olam,"SELECTED","#ffd95a");},removeIntersected(){this.intersected?.niv?.ayshPeula?.("mouseLeave",this);this.olam.hoveredNivra=null;this.intersected=null;this.selected=null;},toggleSelectedMenu(){},selectMenuOption(){},setEntityHighlight(rootObj,active,colorHex=0x00ff00){highlightTarget(rootObj,active,colorHex);},async checkHover(olam,nohtml=true){if(!olam.isLookingForSomething)return;if(olam.isOverUI||this.state==="talking"||this.nivraTalkingTo)return this.removeIntersected();const hit=olam.ayin.getHovered(this.getRayStart(),this.getRayDirection()),niv=ownerFromHit(hit?.object,hit);if(this.intersected&&this.intersected.niv!==niv)this.removeIntersected();if(!niv||niv.wasSealayked||niv.type==="chossid")return;if(this.intersected?.niv!==niv){niv.ayshPeula?.("mouseEnter",this);this.intersected={niv,ob:hit?.object,hit};}olam.hoveredNivra=niv;if(!nohtml&&isNpcTarget(niv))await tell(olam,`TARGET ${niv.name||"NPC"}`,"#ffd95a");}};
