// B"H
/** Registers Chossid and loads fresh model animation prep. */
import * as THREE from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
import Chai from "../../chai/index.js?compact=true&v=grass-chossid-stepwise-20260707-bh1";
import { applyCameraStart } from './lifecycle/cameraStart.js?compact=true&v=lava-camera-axis-20260609-bh640';
import { ensureFallbackBody } from './lifecycle/fallbackBody.js?compact=true&v=compact-engine-20260702-bh2';
import { prepareChossidModel } from './lifecycle/model.js?compact=true&v=grass-chossid-stepwise-20260707-bh1';
function traceVisibility(chossid, stage, extra = {}) { const payload = { seal:'grass-chossid-stepwise-20260707-bh1', stage, name:chossid?.name, hasMesh:Boolean(chossid?.mesh), hasModel:Boolean(chossid?.modelMesh), meshName:chossid?.mesh?.name || null, modelName:chossid?.modelMesh?.name || null, modelParentIsRoot:chossid?.modelMesh?.parent === chossid?.mesh, visibleBody:chossid?.__visibleBodyState || null, at:Date.now(), ...extra }; chossid.olam.__movementTrace ||= []; chossid.olam.__movementTrace.push({ kind:'MODEL_VISIBILITY_TRACE', ...payload }); chossid.olam.__movementTrace = chossid.olam.__movementTrace.slice(-260); if (globalThis.__AWTSMOOS_MODEL_VISIBILITY_LOGS__ === true) console.info('B"H | MODEL_VISIBILITY_TRACE', payload); }
function ensureVisibleChossidBody(chossid) { const realModelPrepared = prepareChossidModel(chossid), fallbackVisible = ensureFallbackBody(chossid); chossid.__visibleBodyState = { realModelPrepared, fallbackVisible, modelParentIsRoot:chossid?.modelMesh?.parent === chossid?.mesh, animation:chossid.__chossidGlbAnimationRuntime || null, at:Date.now() }; traceVisibility(chossid, 'ensure-visible-body', { realModelPrepared, fallbackVisible }); return realModelPrepared || fallbackVisible; }
function registerPlayer(chossid) { if (!chossid?.olam) return; chossid.olam.chossid = chossid; chossid.olam.player = chossid; if (!chossid.olam.ayin) return; chossid.olam.ayin.target = chossid; applyCameraStart(chossid); }
export default { async heescheel(olam) { await Chai.prototype.heescheel.call(this, olam); if (!this.position || isNaN(this.position.x)) this.setPosition(new THREE.Vector3(0, 5, 10)); if (typeof this.setupInputListeners === 'function') this.setupInputListeners(olam); traceVisibility(this, 'after-heescheel'); }, async ready() { await Chai.prototype.ready.call(this); registerPlayer(this); ensureVisibleChossidBody(this); this.inventory?.hydrateItems?.(); if (this.optionsSpeed) this.speed = this.optionsSpeed; this.inventory?.updateUI?.(); this.updateAppearance?.(); traceVisibility(this, 'after-ready'); }, async afterBriyah() { await Chai.prototype.afterBriyah.call(this, this); ensureVisibleChossidBody(this); this.updateAppearance?.(); if (this.olam) this.olam.ayshPeula('save player position'); this.olam.on('wheel', ({ deltaY }) => { if (this.activeObject && this.setDistanceFromRay) { this.distanceFromRay += deltaY * 0.005; this.setDistanceFromRay(this.distanceFromRay); } else if (this.olam.ayin) this.olam.ayin.zoom(deltaY); }); traceVisibility(this, 'after-afterBriyah'); }, async started() { this.iconPath = 'chossid.svg'; this.iconType = 'centered'; this.setupDefaultInventory?.(); } };
