// B"H
/** Chossid frame loop: physics first, then one honest animation request. */
import Chai from "../../chai/index.js?compact=true&v=up-down-jump-ground-20260709-bh4";
const n = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
function dtSeconds(deltaTime) { const v = Number(deltaTime); if (!Number.isFinite(v) || v <= 0) return 1 / 60; return v > 1 ? Math.min(0.08, v / 1000) : Math.min(0.08, v); }
function motionMoving(chossid) { const m = chossid?.moving || {}; const input = !!(m.forward || m.backward || m.stridingLeft || m.stridingRight || m.turningLeft || m.turningRight); const vx = n(chossid?.velocity?.x, 0), vz = n(chossid?.velocity?.z, 0); return input || Math.hypot(vx, vz) > 0.08 || chossid.isWalking === true; }
function airborne(chossid) { const vy = n(chossid?.velocity?.y, 0); return chossid.onFloor === false || chossid.grounded === false || vy > 0.08 || vy < -0.65; }
function wantedClip(chossid) { const vy = n(chossid?.velocity?.y, 0); if (chossid?.moving?.jump || airborne(chossid)) return vy < -1.2 ? "falling" : "jump"; if (motionMoving(chossid)) return chossid?.moving?.running ? "run" : "walk"; return "stand"; }
function timeScale(chossid, clip) { if (clip === "run") return n(chossid.runAnimationTimeScale, 0.58); if (clip === "walk") return n(chossid.walkAnimationTimeScale, 0.72); if (clip === "jump") return n(chossid.jumpAnimationTimeScale, 0.82); if (clip === "falling") return n(chossid.fallAnimationTimeScale, 0.72); return n(chossid.idleAnimationTimeScale, 0.52); }
function chooseFinalClip(chossid) { if (!chossid?.animationMixer || !chossid.animations?.length || typeof chossid.playChaweeyoos !== "function") return; const clip = wantedClip(chossid); if (chossid.__finalChossidClip === clip && chossid.currentAction) return; chossid.__finalChossidClip = clip; chossid.__lastMotionAction = clip; chossid.playChaweeyoos(clip, { duration:0.08, timeScale:timeScale(chossid, clip), force:true, loop:clip !== "jump" && clip !== "falling" }); }
function advanceGlbMixer(chossid, deltaTime) { if (!chossid?.animationMixer || !chossid.animations?.length) return; chooseFinalClip(chossid); chossid.animationMixer.update(dtSeconds(deltaTime)); const stats = chossid.__awtsmoosPlayerAnimationStats || { frames:0, advanced:0 }; stats.frames += 1; stats.advanced += 1; stats.currentClip = chossid.currentAction?._clip?.name || null; stats.requested = chossid.__finalChossidClip || null; stats.actionTime = Number(chossid.currentAction?.time || 0); stats.mixerTime = Number(chossid.animationMixer.time || 0); stats.onFloor = chossid.onFloor; stats.isWalking = chossid.isWalking; stats.velocity = { x:n(chossid.velocity?.x), y:n(chossid.velocity?.y), z:n(chossid.velocity?.z) }; stats.seal = "idle-jump-truth-20260709-bh6"; chossid.__awtsmoosPlayerAnimationStats = stats; if (chossid.olam) chossid.olam.__lastPlayerAnimationStats = stats; globalThis.__AWTS_LAST_PLAYER_ANIMATION_STATS__ = stats; }
export default { heesHawvoos(deltaTime) { if (!this.startedAll) { this.olam.ayshPeula("ready from chossid"); this.startedAll = true; } if (!this.olam.isPlayingCutscene) this.controls(deltaTime); if (this.olam && this.olam.isLookingForSomething) this.checkHover(this.olam, false); if (this.koach !== undefined && this.maxKoach !== undefined && this.koach < this.maxKoach) { this.koach += deltaTime * 2; if (this.koach > this.maxKoach) this.koach = this.maxKoach; if (!this.lastKoachUpdate || Date.now() - this.lastKoachUpdate > 1000) { if (typeof this.updateStatsUI === "function") this.updateStatsUI(); this.lastKoachUpdate = Date.now(); } } if (typeof this.adjustDOF === "function") this.adjustDOF(); if (typeof this.postProcessing === "function") this.postProcessing(); Chai.prototype.heesHawvoos.call(this, deltaTime); advanceGlbMixer(this, deltaTime); } };
