// B"H
/** @file InstallCompleteMitzvahWorld.js @description Complete installer with loading, animation, actors, equipment, gear stats, and peruta economy. */
import { installMitzvahWorldRuntime } from "./InstallMitzvahWorldRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { installGeneratedWorldActors } from "./InstallGeneratedWorldActors.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { installBetterLoadingPlan } from "./InstallBetterLoadingPlan.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { installAnimationRuntime } from "../../animations/runtime/InstallAnimationRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { installEquippedWeaponFeaturePack } from "../../equipment/runtime/EquippedWeaponFeaturePack.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { installEconomyFeaturePack } from "../../economy/runtime/EconomyFeaturePack.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { createGearSlotRuntime } from "../../gear/runtime/GearSlotRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { resolveEquipmentStats } from "../../gear/runtime/EquipmentStatsResolver.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
export function installCompleteMitzvahWorld(seed={}){ const install=installMitzvahWorldRuntime(seed); const loading=installBetterLoadingPlan(install.runtime); const animation=installAnimationRuntime(install.runtime); const equipment=installEquippedWeaponFeaturePack(install.runtime); const economy=installEconomyFeaturePack(install.runtime, seed.economy||{}); const gear=createGearSlotRuntime(install.runtime); install.runtime.gear={ slots:gear, resolveStats:(actorId="player")=>resolveEquipmentStats({ gearSlots:gear.snapshot(actorId).slots, weaponId:equipment.state.current(actorId)?.itemId }) }; const actors=installGeneratedWorldActors(install.runtime, seed.worldIntent||install.world); install.runtime.markReady("runtime:playable",{proof:"installer-smoke",loadingSteps:loading.steps.length,animationClips:animation.clips.length,equipmentItems:equipment.items.length}); install.runtime.markReady("runtime:complete-six-step",{actors}); return { ...install, loading, animation, equipment, economy, gear:install.runtime.gear, actors, proof:install.runtime.snapshot() }; }
export default installCompleteMitzvahWorld;
