// B"H
/** @module TerrainMaterialScribe @description Solid-first terrain, deferred procedural texture revelation. */
import * as THREE from "/games/scripts/build/three.module.js";
import { getGeneratedAsset, putGeneratedAsset, makeGeneratedCacheKey, estimateGeneratedAssetCache } from "../../../systems/cache/GeneratedAssetCache.js?v=generated-cache-spine-20260701-bh1";
const TEXTURE_VERSION = "terrain-texture-shader-20260701-bh2-solid-first";
const clamp = value => Math.max(0, Math.min(255, Math.round(value)));
const lerp = (a, b, t) => a + (b - a) * t;
const smooth = value => { const t = Math.max(0, Math.min(1, value)); return t * t * (3 - 2 * t); };
const PALETTES = Object.freeze({ safegrass:{ solid:0x4fa33f, lo:[42,104,38], hi:[95,166,70], road:[132,92,48], stone:[136,132,112] }, dirtGrass:{ solid:0x6b8f42, lo:[48,92,38], hi:[116,150,76], road:[130,96,58], stone:[126,118,96] }, desert:{ solid:0xb0844e, lo:[104,76,45], hi:[176,132,78], road:[154,105,56], stone:[165,142,105] }, sand:{ solid:0xc49a5b, lo:[120,95,56], hi:[194,154,91], road:[160,118,67], stone:[178,158,120] }, lavaBasin:{ solid:0x74482a, lo:[58,34,24], hi:[116,72,42], road:[126,84,44], stone:[88,70,62] } });
function post(stage, data = {}) { globalThis.postMessage?.({ type:"worker_progress", stage, cacheKind:"terrain-texture", generation:{ what:"terrain shader texture", why:"solid terrain is shown immediately; detailed shader texture generates in the background and hot-swaps in play" }, ...data }); }
function soon(fn) { if (typeof setTimeout === "function") setTimeout(fn, 0); else Promise.resolve().then(fn); }
function hash(x, y, seed = 1) { const value = Math.sin(x * 127.1 + y * 311.7 + seed * 91.3) * 43758.5453; return value - Math.floor(value); }
function noise(x, y, seed = 1) { const ix = Math.floor(x), iy = Math.floor(y), fx = smooth(x - ix), fy = smooth(y - iy); return lerp(lerp(hash(ix, iy, seed), hash(ix + 1, iy, seed), fx), lerp(hash(ix, iy + 1, seed), hash(ix + 1, iy + 1, seed), fx), fy); }
function fbm(x, y, seed) { return noise(x, y, seed) * .52 + noise(x * 2.07, y * 2.07, seed + 11) * .31 + noise(x * 4.13, y * 4.13, seed + 29) * .17; }
function ridgeNoise(x, y, seed) { const n = fbm(x, y, seed); return 1 - Math.abs(n * 2 - 1); }
function segmentDistance(px, pz, a, b) { const ax = Number(a?.[0] || 0), az = Number(a?.[1] || 0), bx = Number(b?.[0] || 0), bz = Number(b?.[1] || 0), dx = bx - ax, dz = bz - az, lengthSq = dx * dx + dz * dz || 1, t = Math.max(0, Math.min(1, ((px - ax) * dx + (pz - az) * dz) / lengthSq)); return Math.hypot(px - (ax + dx * t), pz - (az + dz * t)); }
function roadMask(x, z, roads = []) { let mask = 0; for (const road of roads) for (let i = 1; i < (road?.points || []).length; i += 1) { const d = segmentDistance(x, z, road.points[i - 1], road.points[i]), width = Number(road.width || 9) * .5, feather = Number(road.feather || 8); mask = Math.max(mask, 1 - smooth(Math.max(0, d - width) / Math.max(.001, feather))); } return Math.max(0, Math.min(1, mask)); }
function patchMask(x, z, patches = []) { let mask = 0; for (const patch of patches) { const dx = x - Number(patch.x || 0), dz = z - Number(patch.z || 0), radius = Math.max(1, Number(patch.radius || 20)), d = Math.hypot(dx, dz) / radius; mask = Math.max(mask, (1 - smooth(Math.min(1, d))) * Number(patch.strength ?? 1)); } return Math.max(0, Math.min(1, mask)); }
function typeOf(terrain = {}) { const raw = String(terrain.textureType || terrain.material || "safegrass"); if (/lava|basalt|ash/i.test(raw)) return "lavaBasin"; if (/desert/i.test(raw)) return "desert"; if (/sand/i.test(raw)) return "sand"; if (/dirt/i.test(raw)) return "dirtGrass"; return "safegrass"; }
function mix(a, b, t) { return [lerp(a[0], b[0], t), lerp(a[1], b[1], t), lerp(a[2], b[2], t)]; }
function put(data, index, rgb) { data[index] = clamp(rgb[0]); data[index + 1] = clamp(rgb[1]); data[index + 2] = clamp(rgb[2]); data[index + 3] = 255; }
function cacheKey(terrain, size) { return makeGeneratedCacheKey({ kind:"terrain-texture", version:TEXTURE_VERSION, seed:terrain.seed || terrain.name || terrain.surfaceKey || "terrain", source:terrain.name || terrain.textureType || "terrain", settings:{ size, width:terrain.width, depth:terrain.depth, textureType:terrain.textureType, roads:terrain.roads || [], dirtPatches:terrain.dirtPatches || [] } }); }
function makeTextureData(terrain = {}, size = 768) { const data = new Uint8Array(size * size * 4), width = Number(terrain.width || 320), depth = Number(terrain.depth || 300), roads = terrain.roads || [], patches = terrain.dirtPatches || [], palette = PALETTES[typeOf(terrain)]; for (let y = 0; y < size; y += 1) for (let x = 0; x < size; x += 1) { const u = x / (size - 1), v = y / (size - 1), wx = (u - .5) * width, wz = (v - .5) * depth, broad = fbm(u * 9.2, v * 9.2, 40), fine = fbm(u * 58, v * 58, 91), grit = fbm(u * 144, v * 144, 181), blade = Math.max(0, Math.sin((u * 211 + v * 59 + fine * 9) * Math.PI)), road = roadMask(wx, wz, roads), dirt = Math.max(road, patchMask(wx, wz, patches)), stone = smooth(Math.max(0, fbm(u * 22 - 2, v * 22 + 5, 76) - .66) / .25), crack = smooth(Math.max(0, ridgeNoise(u * 38, v * 38, 312) - .78) / .18); let color = mix(palette.lo, palette.hi, broad * .58 + fine * .24 + blade * blade * .18); color = mix(color, [palette.hi[0] + 18, palette.hi[1] + 20, palette.hi[2] + 8], Math.max(0, blade - .72) * (1 - dirt)); color = mix(color, palette.road, dirt * (.70 + fine * .26)); color = mix(color, [palette.road[0] * .62, palette.road[1] * .58, palette.road[2] * .54], dirt * crack * .58); color = mix(color, [palette.road[0] + 48, palette.road[1] + 38, palette.road[2] + 24], dirt * grit * .16); color = mix(color, palette.stone, stone * (1 - road * .5)); if (typeOf(terrain) === "safegrass" && hash(Math.floor(u * 130), Math.floor(v * 130), 601) > .986 && road < .2) color = [color[0] + 86, color[1] + 38, color[2] + (hash(x, y, 77) > .5 ? 90 : -12)]; put(data, (y * size + x) * 4, color); } return data; }
function textureFrom(value, size, terrain, source) { const data = value instanceof Uint8Array ? value : new Uint8Array(value); const texture = new THREE.DataTexture(data, size, size, THREE.RGBAFormat, THREE.UnsignedByteType); texture.colorSpace = THREE.SRGBColorSpace; texture.wrapS = texture.wrapT = THREE.MirroredRepeatWrapping; texture.repeat.set(Math.max(2, Number(terrain.width || 320) / 70), Math.max(2, Number(terrain.depth || 300) / 70)); texture.magFilter = THREE.LinearFilter; texture.minFilter = THREE.LinearMipmapLinearFilter; texture.generateMipmaps = true; texture.anisotropy = 16; texture.needsUpdate = true; texture.userData ||= {}; Object.assign(texture.userData, { generatedCacheSource:source, solidFirstHydration:true }); return texture; }
function makeSolidMaterial(terrain = {}) { const palette = PALETTES[typeOf(terrain)] || PALETTES.safegrass; const mat = new THREE.MeshLambertMaterial({ color:palette.solid, side:THREE.DoubleSide }); mat.userData = { proceduralTerrainTexture:true, solidFirstTerrain:true, hydrated:false, surfaceKey:typeOf(terrain) }; return mat; }
function installTexture(material, map, source) { if (!material || !map) return; material.map = map; material.color.setHex(0xffffff); material.needsUpdate = true; material.userData.hydrated = true; material.userData.generatedTerrainCache = true; material.userData.generatedTerrainTextureSource = source; }
async function hydrate(material, terrain, size) { const key = cacheKey(terrain, size), started = performance.now(); try { post("cache:terrain-texture:lookup", { cacheStatus:"checking", cacheKey:key, label:`checking cached terrain texture ${size}x${size}` }); const hit = await getGeneratedAsset(key); if (hit?.value) { installTexture(material, textureFrom(hit.value, size, terrain, "indexeddb-hit"), "indexeddb-hit"); post("cache:terrain-texture:hit", { cacheStatus:"hit", cacheKey:key, bytes:hit.bytes, elapsedMs:Math.round(performance.now() - started), label:"terrain texture hot-swapped from IndexedDB" }); return; } post("cache:terrain-texture:miss", { cacheStatus:"miss", cacheKey:key, label:"solid terrain remains visible while texture generates" }); const data = makeTextureData(terrain, size); installTexture(material, textureFrom(data, size, terrain, "generated-background"), "generated-background"); const buffer = data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength); post("texture:terrain:background-installed", { cacheStatus:"generated", cacheKey:key, bytes:buffer.byteLength, elapsedMs:Math.round(performance.now() - started), label:"background terrain texture hot-swapped into live world" }); const saved = await putGeneratedAsset(key, buffer, { kind:"terrain-texture", version:TEXTURE_VERSION, size }); const estimate = await estimateGeneratedAssetCache(); post(saved.ok ? "cache:terrain-texture:stored" : "cache:terrain-texture:store-skipped", { cacheStatus:saved.ok ? "stored" : "store-skipped", cacheKey:key, cacheBytes:estimate.bytes, cacheEntries:estimate.entries, label:saved.ok ? "terrain texture cached for next load" : "cache unavailable; live texture still installed" }); } catch (error) { post("texture:terrain:background-error", { cacheStatus:"error", cacheKey:key, message:error?.message || String(error), label:"terrain stayed solid-color because background texture failed" }); } }
export default class TerrainMaterialScribe { static async scribe(data = {}) { const size = Math.max(384, Math.min(768, Number(data.textureSize || 512))); const material = makeSolidMaterial(data); post("texture:terrain:solid-ready", { percent:100, cacheStatus:"solid-first", label:"solid-color terrain material ready immediately; shader texture is deferred" }); soon(() => hydrate(material, data, size)); return material; } }
