// B"H
/** Mobile touch covenant: joystick and camera touches are independent fingers. */
import SefiraOfInput from './SefiraOfInput.js?v=npc-scroll-pass-through-20260609-bh638';
const SEAL = 'multi-touch-joystick-camera-20260702-bh6', WALK = ['KeyW','KeyS','KeyQ','KeyE'];
const MOBILE_RE = /Mobile|Android|iPhone|iPad|iPod/i, list = x => Array.from(x || []), by = (ts, id) => list(ts).find(t => t.identifier === id);
const post = (w, t, p) => w?.postMessage?.({ [t]:p });
const isJoy = t => !!t?.closest?.('#joystick-container,#joystick-base,#joystick-thumb');
const isUi = t => SefiraOfInput.isUI(t) && !isJoy(t);
function touchCapable() { return typeof window !== 'undefined' && ('ontouchstart' in window || navigator.maxTouchPoints > 0 || MOBILE_RE.test(navigator.userAgent || '')); }
function settings() { try { return { deadzone:10, ...JSON.parse(localStorage.getItem('awtsmoosMobileSettings') || '{}'), naturalJoystick:true }; } catch { return { deadzone:10, naturalJoystick:true }; } }
function trace(stage, p = {}) { window.__AWTSMOOS_TOUCH_TRACE__ ||= []; window.__AWTSMOOS_TOUCH_TRACE__.push({ at:Date.now(), seal:SEAL, stage, ...p }); window.__AWTSMOOS_TOUCH_TRACE__ = window.__AWTSMOOS_TOUCH_TRACE__.slice(-120); }
function thumb(dx, dy) { const el = document.getElementById('joystick-thumb'); if (!el) return; const m = Math.min(44, Math.hypot(dx, dy)), a = Math.atan2(dy, dx); el.style.transform = `translate(${Math.cos(a) * m}px, ${Math.sin(a) * m}px)`; }
function resetThumb() { const el = document.getElementById('joystick-thumb'); if (el) el.style.transform = 'translate(0,0)'; }
function analog(dx, dy) { const dz = Number(settings().deadzone) || 10, len = Math.hypot(dx, dy); if (len < dz) return { vectorX:0, vectorY:0, pressed:false }; const scale = Math.min(1, len / 58); return { vectorX:Math.max(-1, Math.min(1, dx / 58)) * scale, vectorY:Math.max(-1, Math.min(1, dy / 58)) * scale, pressed:true }; }
function desired(dx, dy) { const a = analog(dx, dy), dz = .18, s = new Set(); if (!a.pressed) return s; if (a.vectorY < -dz) s.add('KeyW'); if (a.vectorY > dz) s.add('KeyS'); if (a.vectorX < -dz) s.add('KeyQ'); if (a.vectorX > dz) s.add('KeyE'); return s; }
function state(down, dx = 0, dy = 0) { const a = analog(dx, dy); return { FORWARD:down.has('KeyW'), BACKWARD:down.has('KeyS'), LEFT_STRIDE:down.has('KeyQ'), RIGHT_STRIDE:down.has('KeyE'), vectorX:a.vectorX, vectorY:a.vectorY, analogActive:a.pressed, screenRelative:true, source:'screen-vector-joystick', seal:SEAL, at:Date.now() }; }
function sync(worker, active, set, dx = 0, dy = 0) { for (const code of WALK) { const wants = set.has(code), has = active.has(code); if (wants && !has) { post(worker, 'keydown', { code, seal:SEAL }); active.add(code); } else if (!wants && has) { post(worker, 'keyup', { code, seal:SEAL }); active.delete(code); } } post(worker, 'mobileMove', state(set, dx, dy)); }
function release(worker, active) { sync(worker, active, new Set(), 0, 0); resetThumb(); trace('joystick-release'); }
function drive(worker, origin, p, active, label) { const dx = p.pageX - origin.x, dy = p.pageY - origin.y; thumb(dx, dy); const d = desired(dx, dy); sync(worker, active, d, dx, dy); trace('joystick-drive', { label, dx:Math.round(dx), dy:Math.round(dy), desired:[...d], quiet:true }); }
function bindPointer(worker, active) { let id = null, o = null; window.addEventListener('pointerdown', e => { if (e.pointerType === 'touch' || !isJoy(e.target) || id !== null) return; id = e.pointerId; o = { x:e.pageX, y:e.pageY }; e.target?.setPointerCapture?.(id); drive(worker, o, e, active, 'pointer'); e.preventDefault(); e.stopPropagation(); }, { passive:false, capture:true }); window.addEventListener('pointermove', e => { if (e.pointerId !== id || !o) return; drive(worker, o, e, active, 'pointer'); e.preventDefault(); e.stopPropagation(); }, { passive:false, capture:true }); const end = e => { if (e.pointerId !== id) return; id = null; o = null; release(worker, active); e.preventDefault(); e.stopPropagation(); }; window.addEventListener('pointerup', end, { passive:false, capture:true }); window.addEventListener('pointercancel', end, { passive:false, capture:true }); }
function adoptGaze(touches, jid, gid) { if (gid !== null && by(touches, gid)) return null; const next = list(touches).find(t => t.identifier !== jid && !isJoy(t.target) && !isUi(t.target)); return next ? { id:next.identifier, last:{ x:next.pageX, y:next.pageY } } : { id:null, last:null }; }
function bindTouch(worker, active) {
  let jid = null, jo = null, gid = null, gl = null;
  window.addEventListener('touchstart', e => { let owned = false; for (const t of list(e.changedTouches)) { if (isJoy(t.target) && jid === null) { jid = t.identifier; jo = { x:t.pageX, y:t.pageY }; drive(worker, jo, t, active, 'touch'); owned = true; continue; } if (!isUi(t.target) && gid === null) { gid = t.identifier; gl = { x:t.pageX, y:t.pageY }; post(worker, 'touchstart', { button:0, clientX:t.clientX, clientY:t.clientY, pointerType:'touch', isTouch:true, seal:SEAL }); owned = true; } } if (owned) { e.preventDefault(); e.stopPropagation(); } }, { passive:false, capture:true });
  window.addEventListener('touchmove', e => { let owned = false; const joy = by(e.touches, jid); if (joy && jo) { drive(worker, jo, joy, active, 'touch'); owned = true; } const adopted = adoptGaze(e.touches, jid, gid); if (adopted) { gid = adopted.id; gl = adopted.last; } const gaze = by(e.touches, gid); if (gaze && gl) { post(worker, 'cameraDrag', { dx:(gaze.pageX - gl.x) * 2.2, dy:(gaze.pageY - gl.y) * 1.4, seal:SEAL, multiTouch:true }); gl = { x:gaze.pageX, y:gaze.pageY }; owned = true; } if (owned) e.preventDefault(); }, { passive:false, capture:true });
  const end = e => { let ended = false; for (const t of list(e.changedTouches)) { if (t.identifier === jid) { jid = null; jo = null; release(worker, active); ended = true; } if (t.identifier === gid) { gid = null; gl = null; ended = true; } } const adopted = adoptGaze(e.touches, jid, gid); if (adopted) { gid = adopted.id; gl = adopted.last; } if (ended) e.preventDefault?.(); };
  window.addEventListener('touchend', end, { passive:false, capture:true }); window.addEventListener('touchcancel', end, { passive:false, capture:true });
}
export default class TouchOrchestrator { static bind(worker) { trace('bind-attempt', { prev:window.__awtsmoosTouchOrchestratorBound, touchCapable:touchCapable() }); if (window.__awtsmoosTouchOrchestratorBound === SEAL) return; window.__awtsmoosTouchOrchestratorBound = SEAL; const active = new Set(); bindPointer(worker, active); bindTouch(worker, active); trace('bind-complete', { seal:SEAL }); } }
