// B"H
/** @file TouchOrchestrator.js @description Chapter 429: joystick obeys settings. */
import SefiraOfInput from './SefiraOfInput.js?v=npc-scroll-pass-through-20260609-bh638';
const SEAL='android-settings-joystick-20260612-bh2', WALK=['KeyW','KeyS','KeyQ','KeyE'];
const touchCapable=()=>typeof window!=='undefined'&&('ontouchstart'in window||navigator.maxTouchPoints>0||/Mobile|Android|iPhone|iPad|iPod/i.test(navigator.userAgent||''));
const list=x=>Array.from(x||[]), by=(touches,id)=>list(touches).find(t=>t.identifier===id), dist=(a,b)=>Math.hypot(a.pageX-b.pageX,a.pageY-b.pageY), post=(w,t,p)=>w?.postMessage?.({[t]:p});
function settings(){try{return{invertY:true,invertX:true,deadzone:10,camera:1,...JSON.parse(localStorage.getItem('awtsmoosMobileSettings')||'{}')}}catch{return{invertY:true,invertX:true,deadzone:10,camera:1}}}
function trace(stage,p={}){window.__AWTSMOOS_TOUCH_TRACE__||=[];window.__AWTSMOOS_TOUCH_TRACE__.push({at:Date.now(),seal:SEAL,stage,...p});window.__AWTSMOOS_TOUCH_TRACE__=window.__AWTSMOOS_TOUCH_TRACE__.slice(-120);if(!p.quiet&&window.__AWTSMOOS_INPUT_TRACE__===true)console.info('B"H | TOUCH_ORCHESTRATOR_TRACE',{seal:SEAL,stage,...p});}
function isJoy(t){return!!t?.closest?.('#joystick-container,#joystick-base,#joystick-thumb')} function isUi(t){return SefiraOfInput.isUI(t)&&!isJoy(t)}
function thumb(dx,dy){const el=document.getElementById('joystick-thumb');if(!el)return;const a=Math.atan2(dy,dx),m=Math.min(48,Math.hypot(dx,dy));el.style.transform=`translate(${Math.cos(a)*m}px, ${Math.sin(a)*m}px)`} function reset(){const el=document.getElementById('joystick-thumb');if(el)el.style.transform='translate(0,0)'}
function desired(dx,dy){const s=settings(), dz=Number(s.deadzone)||10, d=new Set(); if(Math.hypot(dx,dy)<dz)return d; const up=s.invertY?'KeyS':'KeyW', down=s.invertY?'KeyW':'KeyS', left=s.invertX?'KeyE':'KeyQ', right=s.invertX?'KeyQ':'KeyE'; if(dy<-dz)d.add(up); if(dy>dz)d.add(down); if(dx<-dz)d.add(left); if(dx>dz)d.add(right); return d;}
function state(d){return{FORWARD:d.has('KeyW'),BACKWARD:d.has('KeyS'),LEFT_STRIDE:d.has('KeyQ'),RIGHT_STRIDE:d.has('KeyE'),source:'android-settings-joystick',seal:SEAL,settings:settings(),at:Date.now()}}
function sync(w,active,d){for(const code of WALK){const wants=d.has(code),has=active.has(code);if(wants&&!has){post(w,'keydown',{code,seal:SEAL});active.add(code)}else if(!wants&&has){post(w,'keyup',{code,seal:SEAL});active.delete(code)}}post(w,'mobileMove',state(d))}
function release(w,a){sync(w,a,new Set());reset();trace('joystick-release',{active:[]})} function drive(w,o,p,a,label){const dx=p.pageX-o.x,dy=p.pageY-o.y;thumb(dx,dy);const d=desired(dx,dy);sync(w,a,d);trace('joystick-drive',{label,desired:[...d],dx:Math.round(dx),dy:Math.round(dy),quiet:true})}
function bindPointer(w,a){let id=null,o=null;window.addEventListener('pointerdown',e=>{if(!isJoy(e.target)||id!==null)return;id=e.pointerId;o={x:e.pageX,y:e.pageY};e.target?.setPointerCapture?.(id);drive(w,o,e,a,'pointer');trace('pointer-start',{id});e.preventDefault();e.stopPropagation()},{passive:false,capture:true});window.addEventListener('pointermove',e=>{if(e.pointerId!==id||!o)return;drive(w,o,e,a,'pointer');e.preventDefault();e.stopPropagation()},{passive:false,capture:true});const end=e=>{if(e.pointerId!==id)return;id=null;o=null;release(w,a);e.preventDefault();e.stopPropagation()};window.addEventListener('pointerup',end,{passive:false,capture:true});window.addEventListener('pointercancel',end,{passive:false,capture:true})}
function bindTouch(w,a){let jid=null,jo=null,gid=null,gl=null,pid=null,pl=0;window.addEventListener('touchstart',e=>{for(const t of list(e.changedTouches)){if(isJoy(t.target)&&jid===null){jid=t.identifier;jo={x:t.pageX,y:t.pageY};drive(w,jo,t,a,'touch');trace('touch-start',{id:jid});e.preventDefault();e.stopPropagation();continue} if(isUi(t.target))continue; if(gid===null){gid=t.identifier;gl={x:t.pageX,y:t.pageY};post(w,'mousedown',{button:2,clientX:t.clientX,clientY:t.clientY,seal:SEAL})}else if(pid===null&&t.identifier!==gid){pid=t.identifier;const first=by(e.touches,gid);if(first)pl=dist(first,t)} e.preventDefault()}},{passive:false,capture:true});window.addEventListener('touchmove',e=>{const joy=by(e.touches,jid);if(joy&&jo)drive(w,jo,joy,a,'touch');const gaze=by(e.touches,gid), pinch=by(e.touches,pid), cam=Number(settings().camera)||1;if(gaze&&pinch){const nd=dist(gaze,pinch),delta=nd-pl;if(Math.abs(delta)>1)post(w,'wheel',{deltaY:-delta*3.5,seal:SEAL});pl=nd;e.preventDefault();return} if(gaze&&gl){const dx=gaze.pageX-gl.x,dy=gaze.pageY-gl.y;if(Math.abs(dx)+Math.abs(dy)>0)post(w,'cameraDrag',{dx:dx*2.2*cam,dy:dy*1.4*cam,seal:SEAL});gl={x:gaze.pageX,y:gaze.pageY}} if(joy||gaze)e.preventDefault()},{passive:false,capture:true});const end=e=>{for(const t of list(e.changedTouches)){if(t.identifier===jid){jid=null;jo=null;release(w,a)} if(t.identifier===gid){gid=null;gl=null;post(w,'mouseup',{button:2,seal:SEAL})} if(t.identifier===pid){pid=null;pl=0}}};window.addEventListener('touchend',end,{passive:false,capture:true});window.addEventListener('touchcancel',end,{passive:false,capture:true})}
export default class TouchOrchestrator{static bind(worker){const prev=window.__awtsmoosTouchOrchestratorBound;trace('bind-attempt',{prev,touchCapable:touchCapable(),settings:settings()});if(prev===SEAL)return;window.__awtsmoosTouchOrchestratorBound=SEAL;const active=new Set();bindPointer(worker,active);bindTouch(worker,active);trace('bind-complete',{seal:SEAL,settings:settings()})}}
