// B"H
/** Mobile touch covenant: the thumb now sends a real analog screen vector.
 * Up means away through the camera, right means screen-right. The Awtsmoos
 * removes the crooked mirror and lets the hand speak plainly.
 */
import SefiraOfInput from './SefiraOfInput.js?v=npc-scroll-pass-through-20260609-bh638';
const SEAL='screen-vector-joystick-20260702-bh2';
const WALK=['KeyW','KeyS','KeyQ','KeyE'];
const MOBILE_RE=/Mobile|Android|iPhone|iPad|iPod/i;
const list=x=>Array.from(x||[]), by=(ts,id)=>list(ts).find(t=>t.identifier===id);
const post=(w,t,p)=>w?.postMessage?.({[t]:p});
const isJoy=t=>!!t?.closest?.('#joystick-container,#joystick-base,#joystick-thumb');
const isUi=t=>SefiraOfInput.isUI(t)&&!isJoy(t);
function touchCapable(){return typeof window!=='undefined'&&('ontouchstart'in window||navigator.maxTouchPoints>0||MOBILE_RE.test(navigator.userAgent||''));}
function settings(){try{return{deadzone:10,...JSON.parse(localStorage.getItem('awtsmoosMobileSettings')||'{}'),naturalJoystick:true};}catch{return{deadzone:10,naturalJoystick:true};}}
function trace(stage,p={}){window.__AWTSMOOS_TOUCH_TRACE__||=[];window.__AWTSMOOS_TOUCH_TRACE__.push({at:Date.now(),seal:SEAL,stage,...p});window.__AWTSMOOS_TOUCH_TRACE__=window.__AWTSMOOS_TOUCH_TRACE__.slice(-120);}
function thumb(dx,dy){const el=document.getElementById('joystick-thumb');if(!el)return;const m=Math.min(44,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);el.style.transform=`translate(${Math.cos(a)*m}px, ${Math.sin(a)*m}px)`;}
function resetThumb(){const el=document.getElementById('joystick-thumb');if(el)el.style.transform='translate(0,0)';}
function analog(dx,dy){const dz=Number(settings().deadzone)||10, len=Math.hypot(dx,dy);if(len<dz)return{vectorX:0,vectorY:0,pressed:false};const scale=Math.min(1,len/58);return{vectorX:Math.max(-1,Math.min(1,dx/58))*scale,vectorY:Math.max(-1,Math.min(1,dy/58))*scale,pressed:true};}
function desired(dx,dy){const a=analog(dx,dy), dz=.18, s=new Set();if(!a.pressed)return s;if(a.vectorY<-dz)s.add('KeyW');if(a.vectorY>dz)s.add('KeyS');if(a.vectorX<-dz)s.add('KeyQ');if(a.vectorX>dz)s.add('KeyE');return s;}
function state(down,dx=0,dy=0){const a=analog(dx,dy);return{FORWARD:down.has('KeyW'),BACKWARD:down.has('KeyS'),LEFT_STRIDE:down.has('KeyQ'),RIGHT_STRIDE:down.has('KeyE'),vectorX:a.vectorX,vectorY:a.vectorY,analogActive:a.pressed,screenRelative:true,source:'screen-vector-joystick',seal:SEAL,at:Date.now()};}
function sync(worker,active,set,dx=0,dy=0){for(const code of WALK){const wants=set.has(code),has=active.has(code);if(wants&&!has){post(worker,'keydown',{code,seal:SEAL});active.add(code);}else if(!wants&&has){post(worker,'keyup',{code,seal:SEAL});active.delete(code);}}post(worker,'mobileMove',state(set,dx,dy));}
function release(worker,active){sync(worker,active,new Set(),0,0);resetThumb();trace('joystick-release');}
function drive(worker,o,p,active,label){const dx=p.pageX-o.x,dy=p.pageY-o.y;thumb(dx,dy);const d=desired(dx,dy);sync(worker,active,d,dx,dy);trace('joystick-drive',{label,dx:Math.round(dx),dy:Math.round(dy),desired:[...d],quiet:true});}
function bindPointer(worker,active){let id=null,o=null;window.addEventListener('pointerdown',e=>{if(!isJoy(e.target)||id!==null)return;id=e.pointerId;o={x:e.pageX,y:e.pageY};e.target?.setPointerCapture?.(id);drive(worker,o,e,active,'pointer');e.preventDefault();e.stopPropagation();},{passive:false,capture:true});window.addEventListener('pointermove',e=>{if(e.pointerId!==id||!o)return;drive(worker,o,e,active,'pointer');e.preventDefault();e.stopPropagation();},{passive:false,capture:true});const end=e=>{if(e.pointerId!==id)return;id=null;o=null;release(worker,active);e.preventDefault();e.stopPropagation();};window.addEventListener('pointerup',end,{passive:false,capture:true});window.addEventListener('pointercancel',end,{passive:false,capture:true});}
function bindTouch(worker,active){let jid=null,jo=null,gid=null,gl=null;window.addEventListener('touchstart',e=>{for(const t of list(e.changedTouches)){if(isJoy(t.target)&&jid===null){jid=t.identifier;jo={x:t.pageX,y:t.pageY};drive(worker,jo,t,active,'touch');e.preventDefault();e.stopPropagation();continue;}if(isUi(t.target))continue;if(gid===null){gid=t.identifier;gl={x:t.pageX,y:t.pageY};post(worker,'touchstart',{button:0,clientX:t.clientX,clientY:t.clientY,pointerType:'touch',isTouch:true,seal:SEAL});e.preventDefault();}}},{passive:false,capture:true});window.addEventListener('touchmove',e=>{const joy=by(e.touches,jid);if(joy&&jo){drive(worker,jo,joy,active,'touch');e.preventDefault();}const gaze=by(e.touches,gid);if(gaze&&gl&&!joy){post(worker,'cameraDrag',{dx:(gaze.pageX-gl.x)*2.2,dy:(gaze.pageY-gl.y)*1.4,seal:SEAL});gl={x:gaze.pageX,y:gaze.pageY};e.preventDefault();}},{passive:false,capture:true});const end=e=>{for(const t of list(e.changedTouches)){if(t.identifier===jid){jid=null;jo=null;release(worker,active);}if(t.identifier===gid){gid=null;gl=null;}}};window.addEventListener('touchend',end,{passive:false,capture:true});window.addEventListener('touchcancel',end,{passive:false,capture:true});}
export default class TouchOrchestrator{static bind(worker){trace('bind-attempt',{prev:window.__awtsmoosTouchOrchestratorBound,touchCapable:touchCapable()});if(window.__awtsmoosTouchOrchestratorBound===SEAL)return;window.__awtsmoosTouchOrchestratorBound=SEAL;const active=new Set();bindPointer(worker,active);bindTouch(worker,active);trace('bind-complete',{seal:SEAL});}}
