// B"H
/** AnimalRenderableFactory.js — skinned bodies plus near colored anatomical details. */
import * as THREE from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
import { ensureRenderBackend } from "../../../../../../rendering/RendererProvider.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { normalizeAnimalSpecies, speciesProfile } from "../render/AnimalSpeciesProfiles.js?compact=true&v=realistic-generated-animals-20260706-bh1";
import { createAnimalRigBlueprint } from "./AnimalRigBlueprints.js?compact=true&v=single-mesh-animals-20260621-bh1";
import { createAnimalSurfaceBlueprint } from "./AnimalSurfaceBlueprint.js?compact=true&v=realistic-generated-animals-20260706-bh1";
import { solveAnimalSkinWeights } from "./AnimalSkinWeightSolver.js?compact=true&v=single-mesh-animals-20260621-bh1";
import { animalMaterialIntent, animalCombatStats } from "./AnimalMaterialIntent.js?compact=true&v=realistic-generated-animals-20260706-bh1";
import { animalAnimationBlueprints } from "./AnimalAnimationBlueprints.js?compact=true&v=single-mesh-animals-20260621-bh1";
import { attachAnimalAnimationController } from "./AnimalAnimationController.js?compact=true&v=single-mesh-animals-20260621-bh1";
import { addCrispAnimalDetailMeshes } from "./AnimalCrispDetailMeshes.js?compact=true&v=crisp-mesh-anatomy-20260706-bh1";
const DISPLAY={fox:"Fox",rabbit:"Rabbit",deer:"Deer",goat:"Goat",cow:"Cow",frog:"Frog",bird:"Bird",boar:"Boar",chicken:"Chicken"};
const KOSHER=new Set(["cow","goat","deer"]), matCache=new Map();
function mat(k,c,rough=.8){const id=`${k}:${c}`; if(!matCache.has(id)) matCache.set(id,new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:0,flatShading:false})); return matCache.get(id);}
function make(kind,geo,color,pos,scale,rot=[0,0,0]){const m=new THREE.Mesh(geo,mat(kind,color)); m.name=`real_${kind}`; m.position.set(...pos); m.scale.set(...scale); m.rotation.set(...rot); Object.assign(m.userData||={}, {animalDetailMesh:true,stableAnimalPart:true,wildlifeActor:true,skipOctree:true,noOctree:true}); return m;}
function sealDetail(root, child){child.nivraAwtsmoos=root; child.castShadow=false; child.receiveShadow=true; root.add(child);}
const G={eye:new THREE.SphereGeometry(.045,10,8),nose:new THREE.SphereGeometry(.06,10,8),spot:new THREE.SphereGeometry(.08,8,6),cone:new THREE.ConeGeometry(.08,.28,8),tusk:new THREE.ConeGeometry(.035,.22,8),comb:new THREE.ConeGeometry(.055,.18,6)};
function eyes(root,p){const y=p.height*1.16,z=p.body.torso[2]*.92+p.body.snout[2]*.55,x=p.body.head[0]*.3; for(const s of[-1,1]) sealDetail(root,make("eye",G.eye,0x050303,[s*x,y,z],[1,1,1])); sealDetail(root,make("nose",G.nose,0x1a0c08,[0,y-.05,z+p.body.snout[2]*.48],[1.15,.75,.75]));}
function horns(root,p,species){if(!p.markings?.horns)return; const y=p.height*1.36,z=p.body.torso[2]*.8,x=p.body.head[0]*.42; for(const s of[-1,1]){sealDetail(root,make("horn",G.cone,0xd9c995,[s*x,y,z],[species==="deer"?.8:.6,species==="deer"?1.7:1.15,.8],[0,0,s*.25])); if(species==="deer") sealDetail(root,make("antler",new THREE.BoxGeometry(.26,.035,.035),0xd9c995,[s*(x+.09),y+.16,z-.04],[1,1,1],[0,0,s*.25]));}}
function markings(root,p,species){if(p.markings?.spots){for(let i=0;i<8;i++) sealDetail(root,make("spot",G.spot,species==="frog"?0x214f20:0xf4dfaa,[(i%4-.5)*.12,p.height*.9,(i-4)*.09],[1,.22,.8]));} if(species==="fox") sealDetail(root,make("tailTip",new THREE.SphereGeometry(.16,10,8),0xf7ead0,[0,p.height*.82,-p.body.torso[2]*.95-p.tail.length*.65],[1,.8,1.4])); if(species==="boar"){for(const s of[-1,1]) sealDetail(root,make("tusk",G.tusk,0xf4ead0,[s*.16,p.height*1.03,p.body.torso[2]*1.03],[1,1,1],[Math.PI/2,0,s*.55])); sealDetail(root,make("bristle",new THREE.BoxGeometry(.08,.42,.12),0x2b1b16,[0,p.height*1.18,-.08],[1,1,5.5]));} if(species==="chicken") sealDetail(root,make("comb",G.comb,0xc91520,[0,p.height*1.35,p.body.torso[2]*.84],[1,1.2,1]));}
function addDetails(root,species,p){eyes(root,p); horns(root,p,species); markings(root,p,species); addCrispAnimalDetailMeshes(root,species,p,{make,seal:sealDetail}); root.userData.realisticGeneratedDetailMeshes=root.children.length; root.userData.realisticAnimalMeshUpgrade="colored-eyes-nose-horns-spots-tail-tusks-comb-crisp-anatomy";}
function sealMesh(mesh){for(const mat of (Array.isArray(mesh.material)?mesh.material:[mesh.material]).filter(Boolean)){mat.transparent=false;mat.opacity=1;mat.depthWrite=true;mat.depthTest=true;mat.alphaTest=0;mat.needsUpdate=true;} Object.assign(mesh.userData||={}, {singleMeshAnimal:true,selectableCombatTarget:true,skipRaycast:false});}
function updateHealth(root){const h=root.userData?.health;if(h?.max)root.userData.healthPct=Math.max(0,Math.min(1,h.current/h.max));}
function evade(root,source){const h=root.userData?.health||{},s=root.userData?.species||"";return Math.abs(Math.sin(((h.hitsTaken||0)*97+s.length*31)*12.9898)*43758.5453)%1 < (h.evasion+(root.userData.airborne&&!source?.antiAir?h.flightEvasion:0));}
function combat(root){root.takeDamage=(amount=0,source={})=>{const h=root.userData.health;if(!h||h.dead)return 0;h.hitsTaken++; if(evade(root,source)){h.lastResult="evaded";return 0;} const applied=Math.min(Math.max(1,(Number(amount)||1)*(1-h.armor)),Math.max(1,h.max/h.minHitsToKill)); h.current=Math.max(0,h.current-applied); Object.assign(h,{lastResult:"damaged",lastDamage:applied,dead:h.current<=0}); updateHealth(root); if(h.dead)root.userData.animalAnimationController?.play?.("death",.08); return applied;}; root.healAnimal=a=>{const h=root.userData.health;h.current=Math.min(h.max,h.current+Math.max(0,Number(a)||0));h.dead=false;updateHealth(root);};}
export function createAnimalRenderable(species="rabbit",data={}){species=normalizeAnimalSpecies(species); const backend=ensureRenderBackend(), profile=speciesProfile(species), rig=createAnimalRigBlueprint(species,profile), surface=createAnimalSurfaceBlueprint(species,profile), skin=solveAnimalSkinWeights(surface,rig); surface.skinIndices=skin.skinIndices; surface.skinWeights=skin.skinWeights; const skeletonPack=backend.skeleton(rig); const mesh=backend.skinnedMesh({geometry:backend.geometry(surface),material:backend.material(animalMaterialIntent(species,profile)),skeletonPack,name:`realistic_generated_${species}_${data.id||"wild"}`}); const stats=animalCombatStats(species,data); backend.mark(mesh,{wildlifeActor:true,species,displayName:DISPLAY[species]||"Animal",targetName:DISPLAY[species]||"Animal",debugName:`realistic_generated_animal_${species}_${data.id||"wild"}`,profile,proceduralSkinnedAnimal:true,singleMeshAnimal:true,renderMeshCount:1,renderBackend:backend.name,skinnedMesh:mesh,skeletonPack,boneCount:skeletonPack.bones.length,surfaceMetadata:surface.metadata||null,health:{current:stats.maxHealth,max:stats.maxHealth,armor:stats.armor,evasion:stats.evasion,flightEvasion:stats.flightEvasion,minHitsToKill:stats.minHitsToKill,hitsTaken:0,dead:false},faction:species==="fox"||species==="boar"?"hostile":"neutral",selectableCombatTarget:true,realisticAnimal:true,realisticBodyUpgrade:true,airborne:species==="bird",kosherEligible:KOSHER.has(species),carcassEnabled:true}); sealMesh(mesh); addDetails(mesh,species,profile); const controller=attachAnimalAnimationController(backend,mesh,animalAnimationBlueprints(species)); backend.mark(mesh,{animalAnimationController:controller,clipCount:Object.keys(controller.actions||{}).length,meshChildrenAllowed:mesh.children.length}); combat(mesh); updateHealth(mesh); return mesh;}
export default createAnimalRenderable;
