// B"H
/**
 * @file AnimalSurfaceBlueprint.js
 * @description
 * Advanced single-mesh animal surface compiler. The Awtsmoos hides detail in
 * the one vessel itself: ears, horns, beard, muzzle, paws, wing vanes, tail
 * fullness, belly, chest, haunch and species silhouette are all vertices of the
 * same mesh, not separate render fragments.
 */
const SEG = 22;
const push = (m, v, uv = [0,0], tag = "body") => (m.positions.push(v[0], v[1], v[2]), m.uvs.push(uv[0], uv[1]), m.tags.push(tag), m.positions.length / 3 - 1);
function ovalAt(m, c, r, tag, v = 0, twist = 0) { const ids=[]; for (let i=0;i<SEG;i++) { const t=i/SEG*Math.PI*2+twist, rib=1+Math.sin(t*3)*.035+Math.cos(t*5)*.018; ids.push(push(m,[c[0]+Math.cos(t)*r[0]*rib,c[1]+Math.sin(t)*r[1]*(1+Math.cos(t*2)*.025),c[2]],[i/SEG,v],tag)); } return ids; }
function connect(m,a,b,flip=false){ for(let i=0;i<SEG;i++){ const n=(i+1)%SEG; flip?m.indices.push(a[i],b[n],b[i],a[i],a[n],b[n]):m.indices.push(a[i],b[i],b[n],a[i],b[n],a[n]); } }
function cap(m,ids,c,tag,flip=false){ const center=push(m,c,[.5,.5],tag); for(let i=0;i<SEG;i++){ const n=(i+1)%SEG; flip?m.indices.push(center,ids[n],ids[i]):m.indices.push(center,ids[i],ids[n]); } }
function tube(m, centers, radii, tag, closeStart=true, closeEnd=true){ let prev=null, first=null, last=null; centers.forEach((c,i)=>{ const ids=ovalAt(m,c,radii[i]||radii[radii.length-1],tag,i/Math.max(1,centers.length-1),i*.17); if(!first) first=ids; if(prev) connect(m,prev,ids); prev=ids; last=ids; }); if(closeStart&&first) cap(m,first,centers[0],tag,true); if(closeEnd&&last) cap(m,last,centers[centers.length-1],tag,false); return {first,last}; }
function socket(m,c,r,limb,tag){ const s=ovalAt(m,c,r,tag,.5); connect(m,s,limb); }
function fin(m, a, b, c, tag){ const i=push(m,a,[0,0],tag), j=push(m,b,[1,0],tag), k=push(m,c,[.5,1],tag); m.indices.push(i,j,k); }

function body(m,p){ const t=p.body.torso, long=t[2], fox=p.tail?.kind==="bushy"?.05:0; return tube(m,[[0,p.height*.68,-long*.7],[0,p.height*.72,-long*.46],[0,p.height*.76,-long*.18],[0,p.height*.82,long*.12],[0,p.height*.88,long*.42],[0,p.height*.84,long*.6]],[[p.body.hips[0]*.9,p.body.hips[1]*1.03],[p.body.hips[0]*1.16,p.body.hips[1]*1.08],[t[0]*1.12,t[1]*1.08+fox],[t[0]*1.04,t[1]*1.05],[p.body.chest[0]*1.05,p.body.chest[1]*1.12],[p.body.chest[0]*.78,p.body.chest[1]*.9]],"body",true,true); }
function legCenters(x,z,p,hind){ const l=p.legs.length*(hind&&p.legs.hindScale?p.legs.hindScale:1),y0=p.height*.68,y1=Math.max(.035,p.height*.07); return [[x,y0,z],[x*.97,y0-l*.28,z+(hind?-.13:.06)],[x*.93,y0-l*.61,z+(hind?.08:-.04)],[x,y1,z+.14]]; }
function limb(m,x,z,p,tag,hind=false){ const c=legCenters(x,z,p,hind), t=p.legs.thickness, r=[[t*1.72,t*1.28],[t*1.08,t*.9],[t*.78,t*.66],[p.legs.foot[0]*1.15,p.legs.foot[1]*1.1]]; const made=tube(m,c,r,tag,false,true); socket(m,c[0],[t*1.45,t*1.1],made.first,tag); }
function neckHead(m,p){ const t=p.body.torso,sn=p.body.snout,beak=p.wings?.span?1.15:1; const c=[[0,p.height*.88,t[2]*.49],[0,p.height*.99,t[2]*.64],[0,p.height*1.08,t[2]*.8],[0,p.height*1.15,t[2]*.95],[0,p.height*1.12,t[2]*.95+sn[2]*.52*beak],[0,p.height*1.08,t[2]*.95+sn[2]*beak]]; const r=[[p.body.neck[0],p.body.neck[1]],[p.body.neck[0]*.9,p.body.neck[1]*1.08],[p.body.head[0]*.7,p.body.head[1]*.86],[p.body.head[0]*1.06,p.body.head[1]],[sn[0],sn[1]],[sn[0]*.36,sn[1]*.44]]; const made=tube(m,c,r,"head",false,true); socket(m,c[0],[p.body.neck[0]*.98,p.body.neck[1]],made.first,"neck"); }
function tail(m,p){ const len=p.tail?.length||0; if(!len) return; const z0=-p.body.torso[2]*.68,y=p.height*.76,fat=p.tail.kind==="bushy"?1.85:1; const made=tube(m,[[0,y,z0],[0,y+.035,z0-len*.26],[0,y+.07,z0-len*.55],[0,y+.09,z0-len*.82],[0,y+.06,z0-len]],[[p.tail.radius*fat,p.tail.radius*.95*fat],[p.tail.radius*1.15*fat,p.tail.radius*.9*fat],[p.tail.radius*.92*fat,p.tail.radius*.72*fat],[p.tail.radius*.48*fat,p.tail.radius*.4*fat],[p.tail.radius*.15,p.tail.radius*.14]],"tail",false,true); socket(m,[0,y,z0],[p.tail.radius,p.tail.radius*.78],made.first,"tail"); }
function ears(m,p,species){ const z=p.body.torso[2]*.96,y=p.height*1.27,wide=p.body.head[0]*.72; if(species==="frog") return; for(const side of[-1,1]){ if(species==="cow"||species==="goat"||species==="deer") tube(m,[[side*wide,y-.06,z],[side*(wide+.06),y+.16,z+.02],[side*(wide+.02),y+.27,z+.04]],[[.035,.07],[.03,.09],[.012,.035]],"ear",true,true); else fin(m,[side*wide,y-.1,z],[side*(wide+.22),y+.35,z+.02],[side*(wide-.02),y+.12,z+.08],"ear"); } }
function horns(m,p,species){ if(!["goat","deer","cow"].includes(species)) return; const z=p.body.torso[2]*.93,y=p.height*1.32,wide=p.body.head[0]*.42; for(const side of[-1,1]){ const len=species==="deer"?.46:species==="goat"?.32:.2; tube(m,[[side*wide,y,z],[side*(wide+.07),y+len*.45,z-.02],[side*(wide+.12),y+len,z-.05]],[[.035,.035],[.025,.025],[.012,.012]],"horn",true,true); if(species==="deer") for(let i=1;i<3;i++) tube(m,[[side*(wide+.08),y+len*(.38+i*.18),z-.04],[side*(wide+.18),y+len*(.48+i*.18),z-.08]],[[.012,.012],[.006,.006]],"antlerTine",true,true); } }
function beardMane(m,p,species){ if(!["goat","cow","deer"].includes(species)) return; const z=p.body.torso[2]*1.08,y=p.height*.98; tube(m,[[0,y,z],[0,y-.12,z+.04],[0,y-.24,z+.02]],[[.12,.035],[.1,.025],[.035,.012]],species==="goat"?"beard":"dewlap",true,true); }
function wings(m,p){ if(!p.wings) return; const y=p.height*.82,z=p.body.torso[2]*.12; for(const side of[-1,1]){ const made=tube(m,[[side*p.body.chest[0]*.82,y,z],[side*.42,y-.01,z-.14],[side*.72,y-.055,z-.38],[side*.54,y-.08,z-.62]],[[.045,.14],[.04,.28],[.028,.2],[.016,.06]],"wing",true,true); for(let i=0;i<5;i++) fin(m,[side*.2,y-.02,z-.08-i*.08],[side*(.5+i*.04),y-.04,z-.18-i*.08],[side*(.25+i*.025),y-.12,z-.22-i*.08],"featherVane"); } }
function frogPads(m,p){ if(p.tail?.kind!=="none") return; for(const side of[-1,1]) tube(m,[[side*.32,p.height*.12,.28],[side*.5,p.height*.075,.46]],[[.09,.025],[.2,.038]],"webbedFoot",true,true); }

export function createAnimalSurfaceBlueprint(species,p){ const mesh={ positions:[], uvs:[], indices:[], tags:[], metadata:{ closedSurface:true,caps:true,bridgedSockets:true,anatomicalUpgrade:true,advancedSingleMeshAnimal:true,segmentCount:SEG } }; body(mesh,p); neckHead(mesh,p); ears(mesh,p,species); horns(mesh,p,species); beardMane(mesh,p,species); for(const side of[-1,1]){ limb(mesh,side*p.legs.stanceX,p.legs.stanceZ,p,"foreLeg",false); if(species!=="bird") limb(mesh,side*p.legs.stanceX,-p.legs.stanceZ,p,"hindLeg",true); } tail(mesh,p); wings(mesh,p); frogPads(mesh,p); mesh.metadata.vertexCount=mesh.positions.length/3; mesh.metadata.triangleCount=mesh.indices.length/3; mesh.metadata.detailTags=[...new Set(mesh.tags)]; return mesh; }
export default createAnimalSurfaceBlueprint;
