// B"H
/** @file AnimalAnimationController.js @description Velocity-aware blended animal animation with planted feet, muscle sway, and species gait truth. */
const ROLE = Object.freeze({ patrol:"walk", wander:"walk", forage:"walk", drink:"eat", eat:"eat", graze:"eat", climb:"walk", flock:"flee", chase:"run", hunt:"stalk", flee:"flee", fleePlayer:"flee", panic:"flee", desperateFlee:"flee", takeoffAlarm:"flee", alarmCircle:"flee", circleGlide:"flee", hopPeck:"eat", landNest:"eat", glideHome:"flee", returnNest:"flee", followHerd:"walk", cohereHerd:"walk", followFamily:"walk", socialIdle:"idle_alert", protectYoung:"run", restDen:"idle_breath", returnDen:"walk", hide:"idle_alert", windup:"pounce", strike:"pounce", attack:"bite", recover:"recoil", dead:"death", death:"death", limp:"limp" });
const ACTIVE = new Set(["run", "flee", "pounce", "bite"]), LOCOMOTION = new Set(["walk", "trot", "run", "flee", "stalk", "limp"]), PAWS = ["fore_l_paw", "fore_r_paw", "hind_l_paw", "hind_r_paw"];
function dataOf(root) { if (!root.userData) root.userData = {}; return root.userData; }
function boneMap(root) { return dataOf(root).skeletonPack?.boneMap || {}; }
function setEuler(bone, x = 0, y = 0, z = 0) { if (bone?.rotation) bone.rotation.set(x, y, z); }
function setPos(bone, x = 0, y = 0, z = 0) { if (bone?.position) bone.position.set(x, y, z); }
function n(v, f = 0) { return Number.isFinite(Number(v)) ? Number(v) : f; }
function filterIntent(intent = {}, map = {}) { const removed = [], kept = []; for (const tr of intent.tracks || []) { if (tr && map[tr.boneId]) kept.push(tr); else if (tr) removed.push(tr.boneId || "unknown"); } return { kept:Object.assign({}, intent, { tracks:kept, removedTracks:removed }), removed }; }
function distance(a, b) { if (!a || !b) return 0; const dx = n(a.x) - n(b.x), dz = n(a.z) - n(b.z); return Math.sqrt(dx*dx + dz*dz); }
export class AnimalAnimationController {
  constructor(backend, root, clipIntents = []) { this.backend = backend; this.root = root; this.mesh = dataOf(root).skinnedMesh || root; this.bones = boneMap(root); this.mixer = backend.mixer(this.mesh); this.actions = {}; this.current = null; this.time = 0; this.state = "idle_breath"; this.speed = 1; this.velocity = 0; this.lastPosition = root.position?.clone?.() || null; this.removedTracks = []; this.layers = { breathing:true, tail:true, ears:true, sniff:true, spine:true, pawPulse:true, proceduralMuscle:true, footPlant:true, weightShift:true, velocityBlend:true }; clipIntents.forEach(intent => this.add(intent)); const data = dataOf(root); Object.assign(data, { sinusoidalLayer:true, proceduralMuscleSystem:true, footPlantSystem:true, velocityAwareAnimation:true, proceduralMotionLayers:Object.keys(this.layers), animationMixerTarget:this.mesh === root ? "root-fallback" : "skinnedMesh", removedAnimationTracks:this.removedTracks, bindingSafe:this.mesh !== root && Boolean(this.mesh.skeleton) }); }
  add(intent) { const filtered = filterIntent(intent, this.bones); this.removedTracks.push(...filtered.removed.map(boneId => ({ clip:intent.name || "clip", boneId }))); if (!filtered.kept.tracks?.length) return; const clip = this.backend.clip(filtered.kept), action = this.mixer.clipAction(clip); action.userData = { intent:filtered.kept }; this.actions[filtered.kept.role || filtered.kept.name] = action; dataOf(this.root).clipCount = Object.keys(this.actions).length; dataOf(this.root).filteredAnimationTracks = (dataOf(this.root).filteredAnimationTracks || 0) + filtered.kept.tracks.length; }
  role(state) { const direct = this.actions[state] ? state : ROLE[state]; if (direct && this.actions[direct]) return direct; return this.velocity > 1.7 && this.actions.run ? "run" : this.velocity > .75 && this.actions.trot ? "trot" : this.actions.idle_breath ? "idle_breath" : Object.keys(this.actions)[0]; }
  play(state = "idle_breath", fade = .18) { const name = this.role(state), next = this.actions[name] || this.actions.idle_breath; if (!next || next === this.current) return; next.enabled = true; next.reset().fadeIn(fade).play(); if (this.current) this.current.fadeOut(fade); this.current = next; this.state = name; }
  layerAmp() { if (ACTIVE.has(this.state)) return 1.2; if (this.state === "stalk") return .45; if (this.state === "eat") return .7; return LOCOMOTION.has(this.state) ? .7 : .38; }
  updateVelocity(dt) { const p = this.root.position, last = this.lastPosition; this.velocity = last && p ? distance(p, last) / Math.max(.001, dt) : this.velocity * .92; if (p?.clone) this.lastPosition = p.clone(); dataOf(this.root).animationVelocity = this.velocity; }
  applyFootPlant(t, amp) { const data = dataOf(this.root), plant = {}, cadence = LOCOMOTION.has(this.state) ? 8.5 + Math.min(5, this.velocity) : 3.5; for (let i=0;i<PAWS.length;i++) { const name = PAWS[i], bone = this.bones[name]; if (!bone) continue; const phase = i % 2 ? Math.PI : 0, wave = Math.sin(t * cadence + phase), planted = wave < .05; plant[name] = planted ? "planted" : "swing"; setPos(bone, 0, planted ? 0 : Math.max(0, wave) * .07 * amp, planted ? -.015 : Math.cos(t * cadence + phase) * .05 * amp); } data.footPlantProof = plant; }
  applyMuscle(t, amp) { const sprint = ACTIVE.has(this.state) ? .14 : LOCOMOTION.has(this.state) ? .07 : .035, breath = Math.sin(t * 2.4) * .025 * amp; dataOf(this.root).muscleBulge = { chest:Math.max(0, Math.sin(t * 8)) * sprint, haunch:Math.max(0, Math.sin(t * 7.1 + Math.PI)) * sprint, breath:Math.abs(breath), velocity:this.velocity }; }
  applySinusoidal(dt) { this.time += dt * (this.speed + Math.min(1.5, this.velocity * .08)); const t = this.time, amp = this.layerAmp(), b = this.bones, breath = Math.sin(t * 2.4) * .025 * amp, fast = Math.sin(t * 9) * .035 * amp; setEuler(b.spine_0, breath*.5, 0, Math.sin(t*1.7)*.018*amp); setEuler(b.spine_1, breath, Math.sin(t*1.1)*.018*amp, Math.sin(t*2.2)*.025*amp); setEuler(b.chest, breath*.8 + fast*.18, 0, Math.sin(t*2)*.018*amp); setEuler(b.neck_0, Math.sin(t*2.1)*.035*amp, Math.sin(t*1.3)*.03*amp, 0); setEuler(b.neck_1, Math.sin(t*2.5)*.045*amp, Math.sin(t*1.6)*.04*amp, 0); setEuler(b.head, Math.sin(t*2.8)*.035*amp, Math.sin(t*1.9)*.07*amp, Math.sin(t*3.1)*.018*amp); setEuler(b.jaw, this.state === "eat" ? .16 + Math.max(0, Math.sin(t*18))*.22 : Math.max(0, Math.sin(t*1.2))*.025, 0, 0); setEuler(b.ear_l, Math.sin(t*5.7)*.06*amp, 0, Math.max(0,Math.sin(t*3.3))*.18*amp); setEuler(b.ear_r, Math.sin(t*4.9+1.2)*.055*amp, 0, Math.max(0,Math.sin(t*2.9+2))*.16*amp); for (let i=0;i<6;i++) setEuler(b[`tail_${i}`], Math.sin(t*2+i*.7)*.035*amp, Math.sin(t*3.2+i*.55)*.18*amp, Math.sin(t*1.7+i*.33)*.04*amp); this.applyFootPlant(t, amp); this.applyMuscle(t, amp); }
  update(dt = 1 / 60, state = "wander") { const delta = Math.min(.08, Math.max(.001, n(dt, 1 / 60))); this.updateVelocity(delta); this.play(this.role(state), LOCOMOTION.has(this.role(state)) ? .1 : .18); if (this.mixer) this.mixer.update(delta * (this.speed + Math.min(1.5, this.velocity * .08))); this.applySinusoidal(delta); }
}
export function attachAnimalAnimationController(backend, root, clips) { const c = new AnimalAnimationController(backend, root, clips); dataOf(root).animalAnimationController = c; c.play("idle_breath", 0); return c; }
export default AnimalAnimationController;
