// B"H
/** @file AnimalAnimationBlueprints.js @description Contact-aware animal gait bank with walk/trot/run/hop/flutter and attack clips. */
function k(time, value) { return { time, value }; }
function rot(boneId, keys) { return { kind:"rotation", boneId, keys }; }
function pos(boneId, keys) { return { kind:"position", boneId, keys }; }
function key(t, amp, phase = 0, lift = 0) { return [Math.sin(t * Math.PI * 2 + phase) * amp + lift, Math.max(0, Math.sin(t * Math.PI * 2 + phase)) * amp * .16, Math.cos(t * Math.PI * 2 + phase) * amp * .22]; }
function wave(duration, amp, phase = 0, lift = 0, samples = 13) { const out = []; for (let i = 0; i < samples; i++) { const t = i / (samples - 1); out.push(k(t * duration, key(t, amp, phase, lift))); } return out; }
function sway(duration, amp, axis = 2, phase = 0, samples = 13) { const out = []; for (let i = 0; i < samples; i++) { const t = i / (samples - 1), v = [0,0,0]; v[axis] = Math.sin(t * Math.PI * 2 + phase) * amp; out.push(k(t * duration, v)); } return out; }
function foot(duration, lift, phase = 0, samples = 9) { const out = []; for (let i = 0; i < samples; i++) { const t = i / (samples - 1), s = Math.sin(t * Math.PI * 2 + phase); out.push(k(t * duration, [0, Math.max(0, s) * lift, Math.cos(t * Math.PI * 2 + phase) * lift * .8])); } return out; }
function limbTracks(duration, amp, lift, gaitPhase = 0) { return [
  rot("fore_l_upper", wave(duration, amp, gaitPhase)), rot("fore_l_knee", wave(duration, amp*.55, gaitPhase + Math.PI, -amp*.1)), pos("fore_l_paw", foot(duration, lift, gaitPhase)),
  rot("hind_r_upper", wave(duration, amp*.98, gaitPhase)), rot("hind_r_knee", wave(duration, amp*.62, gaitPhase + Math.PI, -amp*.1)), pos("hind_r_paw", foot(duration, lift*.95, gaitPhase)),
  rot("fore_r_upper", wave(duration, amp, gaitPhase + Math.PI)), rot("fore_r_knee", wave(duration, amp*.55, gaitPhase, -amp*.1)), pos("fore_r_paw", foot(duration, lift, gaitPhase + Math.PI)),
  rot("hind_l_upper", wave(duration, amp*.98, gaitPhase + Math.PI)), rot("hind_l_knee", wave(duration, amp*.62, gaitPhase, -amp*.1)), pos("hind_l_paw", foot(duration, lift*.95, gaitPhase + Math.PI)) ]; }
function gait(name, duration, amp, options = {}) { const lift = options.lift ?? amp*.11, tail = options.tail ?? amp*.25, spine = options.spine ?? amp*.09; return { name, role:name, duration, procedural:true, contactAware:true, tracks:[ ...limbTracks(duration, amp, lift, options.phase || 0), rot("root", sway(duration, amp*.025, 0, Math.PI*.5)), rot("spine_0", sway(duration, spine*.55, 2, Math.PI*.25)), rot("spine_1", sway(duration, spine, 2, Math.PI*.75)), rot("chest", sway(duration, spine*.7, 0, Math.PI*.1)), rot("neck_1", sway(duration, amp*.08, 1, Math.PI*.4)), rot("head", sway(duration, amp*.07, 0, Math.PI*.6)), rot("tail_1", sway(duration, tail*.7, 1, 0)), rot("tail_2", sway(duration, tail, 1, Math.PI*.28)), rot("tail_4", sway(duration, tail*.75, 1, Math.PI*.62)) ] }; }
function simple(name, duration, tracks, extra = {}) { return Object.assign({ name, duration, role:name, tracks, procedural:true, contactAware:true }, extra); }
function idle(name, duration, breath, alert = 0) { return simple(name, duration, [rot("spine_0", sway(duration, breath*.4, 0, 0)), rot("spine_1", sway(duration, breath, 0, Math.PI*.12)), rot("chest", sway(duration, breath*.9, 0, Math.PI*.18)), rot("neck_1", sway(duration, breath*.45 + alert*.08, 1, Math.PI*.35)), rot("head", sway(duration, breath*.25 + alert*.12, 1, Math.PI*.52)), rot("ear_l", sway(duration, alert*.4, 2, 0)), rot("ear_r", sway(duration, alert*.33, 2, Math.PI*.45)), rot("tail_2", sway(duration, breath*1.8 + alert*.2, 1, Math.PI*.25))]); }
function bite() { return simple("bite", .46, [rot("neck_1", [k(0,[.05,0,0]), k(.16,[-.22,0,0]), k(.29,[.18,0,0]), k(.46,[.03,0,0])]), rot("head", [k(0,[0,0,0]), k(.15,[-.64,0,0]), k(.28,[.18,0,0]), k(.46,[0,0,0])]), rot("jaw", [k(0,[0,0,0]), k(.14,[.44,0,0]), k(.24,[-.08,0,0]), k(.46,[0,0,0])])], { attackWindow:[.14,.27] }); }
function pounce() { return simple("pounce", .72, [rot("root", [k(0,[0,0,0]), k(.24,[-.18,0,0]), k(.44,[.26,0,0]), k(.72,[0,0,0])]), pos("root", [k(0,[0,0,0]), k(.34,[0,.16,.34]), k(.54,[0,.04,.74]), k(.72,[0,0,.98])]), rot("hind_l_upper", [k(0,[-.45,0,0]), k(.28,[.78,0,0]), k(.72,[0,0,0])]), rot("hind_r_upper", [k(0,[-.45,0,0]), k(.28,[.78,0,0]), k(.72,[0,0,0])]), rot("fore_l_upper", [k(0,[.22,0,0]), k(.42,[-.74,0,0]), k(.72,[0,0,0])]), rot("fore_r_upper", [k(0,[.22,0,0]), k(.42,[-.74,0,0]), k(.72,[0,0,0])])], { attackWindow:[.38,.55] }); }
function eat() { return simple("eat", 1.35, [rot("neck_0", [k(0,[.55,0,0]), k(.55,[.72,0,0]), k(1.35,[.55,0,0])]), rot("head", [k(0,[.32,0,0]), k(.3,[.18,0,0]), k(.62,[.42,0,0]), k(1.35,[.32,0,0])]), rot("jaw", [k(0,[.05,0,0]), k(.18,[.38,0,0]), k(.36,[.05,0,0]), k(.58,[.42,0,0]), k(1.35,[.05,0,0])])]); }
function recoil() { return simple("recoil", .42, [rot("root", [k(0,[0,0,0]), k(.16,[.22,0,0]), k(.42,[0,0,0])]), rot("chest", [k(0,[0,0,0]), k(.16,[.44,0,0]), k(.42,[0,0,0])]), rot("head", [k(0,[0,0,0]), k(.16,[.35,0,0]), k(.42,[0,0,0])])]); }
function death() { return simple("death", 1.2, [rot("root", [k(0,[0,0,0]), k(.55,[0,0,1.35]), k(1.2,[0,0,1.58])]), pos("root", [k(0,[0,0,0]), k(.55,[0,-.22,0]), k(1.2,[0,-.42,0])]), rot("head", [k(0,[0,0,0]), k(.7,[.92,0,0]), k(1.2,[1.1,0,0])])]); }
function hop(name, duration, amp) { return simple(name, duration, [pos("root", [k(0,[0,0,0]), k(duration*.35,[0,amp*.28,amp*.5]), k(duration*.6,[0,amp*.04,amp*.95]), k(duration,[0,0,1.05])]), rot("hind_l_upper", wave(duration, amp*.9, 0)), rot("hind_r_upper", wave(duration, amp*.9, 0)), rot("fore_l_upper", wave(duration, amp*.45, Math.PI)), rot("fore_r_upper", wave(duration, amp*.45, Math.PI))]); }
function turn(name, side) { return simple(name, .62, [rot("root", [k(0,[0,0,0]), k(.31,[0,side*.38,0]), k(.62,[0,0,0])]), rot("spine_1", [k(0,[0,0,0]), k(.31,[0,side*.2,side*.08]), k(.62,[0,0,0])]), rot("head", [k(0,[0,0,0]), k(.2,[0,side*.55,0]), k(.62,[0,0,0])])]); }
function speciesScale(species) { if (species === "fox") return { quick:1.18, tail:1.45, alert:.42 }; if (species === "deer") return { quick:.86, tail:.45, alert:.28 }; if (species === "goat") return { quick:.92, tail:.35, alert:.22 }; if (species === "cow") return { quick:.62, tail:.3, alert:.16 }; if (species === "frog") return { quick:1.05, tail:.05, alert:.12, hop:true }; if (species === "bird") return { quick:1.35, tail:.7, alert:.34, hop:true }; return { quick:1.08, tail:.6, alert:.3, hop:true }; }
export function animalAnimationBlueprints(species = "rabbit") { const s = speciesScale(species); const locomotion = s.hop ? [hop("walk", .82 / s.quick, .38), hop("trot", .58 / s.quick, .54), hop("run", .42 / s.quick, .72), hop("flee", .36 / s.quick, .82)] : [gait("walk", 1.1 / s.quick, .28, { tail:s.tail*.18, lift:.035 }), gait("trot", .72 / s.quick, .47, { tail:s.tail*.28, lift:.06 }), gait("run", .5 / s.quick, .7, { tail:s.tail*.4, spine:.13, lift:.08 }), gait("flee", .42 / s.quick, .8, { tail:s.tail*.5, spine:.16, lift:.1 })]; return [idle("idle_breath", 2.4, .035, .08), idle("idle_alert", 1.35, .04, s.alert), idle("sniff", 1.05, .03, s.alert*.75), ...locomotion, gait("stalk", 1.55 / s.quick, .18, { tail:s.tail*.08, spine:.045, lift:.02 }), gait("limp", 1.25 / s.quick, .2, { tail:s.tail*.12, spine:.09, lift:.025 }), bite(), pounce(), eat(), recoil(), death(), turn("turn_left", 1), turn("turn_right", -1)]; }
export default animalAnimationBlueprints;
