// B"H
/** @file AnimalSurfaceBlueprint.js @description Opaque closed anatomical animal surface arrays with ribs, hips, paws, wings, and species silhouettes. */
const SEG = 18;
function push(mesh, v, uv = [0,0], tag = "body") { mesh.positions.push(v[0], v[1], v[2]); mesh.uvs.push(uv[0], uv[1]); mesh.tags.push(tag); return mesh.positions.length / 3 - 1; }
function ovalAt(mesh, center, radius, tag, v = 0, twist = 0) { const ids = []; for (let i = 0; i < SEG; i++) { const t = i / SEG * Math.PI * 2 + twist; const rib = 1 + Math.sin(t * 3) * .035; ids.push(push(mesh, [center[0] + Math.cos(t) * radius[0] * rib, center[1] + Math.sin(t) * radius[1], center[2]], [i / SEG, v], tag)); } return ids; }
function connect(mesh, a, b, flip = false) { for (let i = 0; i < SEG; i++) { const n = (i + 1) % SEG; flip ? mesh.indices.push(a[i], b[n], b[i], a[i], a[n], b[n]) : mesh.indices.push(a[i], b[i], b[n], a[i], b[n], a[n]); } }
function cap(mesh, ids, center, tag, flip = false) { const c = push(mesh, center, [.5,.5], tag); for (let i = 0; i < SEG; i++) { const n = (i + 1) % SEG; flip ? mesh.indices.push(c, ids[n], ids[i]) : mesh.indices.push(c, ids[i], ids[n]); } }
function tube(mesh, centers, radii, tag, closeStart = true, closeEnd = true) { let prev = null, first = null, last = null; centers.forEach((c, i) => { const ids = ovalAt(mesh, c, radii[i] || radii[radii.length - 1], tag, i / Math.max(1, centers.length - 1), i * .18); if (!first) first = ids; if (prev) connect(mesh, prev, ids); prev = ids; last = ids; }); if (closeStart && first) cap(mesh, first, centers[0], tag, true); if (closeEnd && last) cap(mesh, last, centers[centers.length - 1], tag, false); return { first, last }; }
function bridgeSocket(mesh, socketCenter, socketRadius, limbFirst, tag) { const socket = ovalAt(mesh, socketCenter, socketRadius, tag, .5); connect(mesh, socket, limbFirst); }
function legCenters(x, z, p, hind) { const l = p.legs.length * (hind && p.legs.hindScale ? p.legs.hindScale : 1), y0 = p.height * .68, y1 = Math.max(.035, p.height * .07); return [[x,y0,z],[x * .97,y0-l*.28,z+(hind?-.12:.06)],[x*.93,y0-l*.61,z+(hind?.07:-.04)],[x,y1,z+.13]]; }
function limb(mesh, x, z, p, tag, hind = false) { const c = legCenters(x, z, p, hind); const t = p.legs.thickness; const r = [[t*1.65,t*1.22],[t*1.08,t*.9],[t*.8,t*.66],[p.legs.foot[0],p.legs.foot[1]]]; const made = tube(mesh, c, r, tag, false, true); bridgeSocket(mesh, c[0], [t*1.45,t*1.1], made.first, tag); }
function body(mesh, p) { const t = p.body.torso, long = t[2]; return tube(mesh, [[0,p.height*.7,-long*.62],[0,p.height*.72,-long*.42],[0,p.height*.76,-long*.16],[0,p.height*.8,long*.12],[0,p.height*.84,long*.4],[0,p.height*.82,long*.55]], [[p.body.hips[0]*.88,p.body.hips[1]*.92],[p.body.hips[0]*1.1,p.body.hips[1]],[t[0]*1.08,t[1]*1.03],[t[0],t[1]],[p.body.chest[0],p.body.chest[1]*1.04],[p.body.chest[0]*.76,p.body.chest[1]*.88]], "body", true, true); }
function neckHead(mesh, p) { const t = p.body.torso, sn = p.body.snout; const c = [[0,p.height*.88,t[2]*.48],[0,p.height*.98,t[2]*.62],[0,p.height*1.07,t[2]*.78],[0,p.height*1.12,t[2]*.94],[0,p.height*1.1,t[2]*.94+sn[2]*.52],[0,p.height*1.07,t[2]*.94+sn[2]]]; const r = [[p.body.neck[0],p.body.neck[1]],[p.body.neck[0]*.88,p.body.neck[1]*1.08],[p.body.head[0]*.7,p.body.head[1]*.84],[p.body.head[0],p.body.head[1]],[sn[0],sn[1]],[sn[0]*.38,sn[1]*.46]]; const made = tube(mesh, c, r, "head", false, true); bridgeSocket(mesh, c[0], [p.body.neck[0]*.98,p.body.neck[1]], made.first, "neck"); }
function tail(mesh, p) { const len = p.tail?.length || 0; if (!len) return; const z0 = -p.body.torso[2]*.66, y = p.height*.76; const fat = p.tail.kind === "bushy" ? 1.55 : 1; const made = tube(mesh, [[0,y,z0],[0,y+.03,z0-len*.32],[0,y+.05,z0-len*.68],[0,y+.07,z0-len]], [[p.tail.radius*fat,p.tail.radius*.9*fat],[p.tail.radius*fat,p.tail.radius*.82*fat],[p.tail.radius*.62*fat,p.tail.radius*.54*fat],[p.tail.radius*.2,p.tail.radius*.18]], "tail", false, true); bridgeSocket(mesh, [0,y,z0], [p.tail.radius,p.tail.radius*.78], made.first, "tail"); }
function wings(mesh, p) { if (!p.wings) return; const y = p.height*.82, z = p.body.torso[2]*.12; for (const side of [-1,1]) tube(mesh, [[side*p.body.chest[0]*.82,y,z],[side*.42,y-.01,z-.14],[side*.68,y-.05,z-.38],[side*.5,y-.08,z-.58]], [[.04,.13],[.035,.26],[.025,.18],[.015,.06]], "wing", true, true); }
function frogPads(mesh, p) { if (p.tail?.kind !== "none") return; for (const side of [-1,1]) tube(mesh, [[side*.32,p.height*.12,.28],[side*.48,p.height*.08,.45]], [[.09,.025],[.18,.035]], "webbedFoot", true, true); }
export function createAnimalSurfaceBlueprint(species, p) { const mesh = { positions:[], uvs:[], indices:[], tags:[], metadata:{ closedSurface:true, caps:true, bridgedSockets:true, anatomicalUpgrade:true, segmentCount:SEG } }; body(mesh, p); neckHead(mesh, p); for (const side of [-1,1]) { limb(mesh, side*p.legs.stanceX, p.legs.stanceZ, p, "foreLeg", false); if (species !== "bird") limb(mesh, side*p.legs.stanceX, -p.legs.stanceZ, p, "hindLeg", true); } tail(mesh, p); wings(mesh, p); frogPads(mesh, p); mesh.metadata.vertexCount = mesh.positions.length / 3; mesh.metadata.triangleCount = mesh.indices.length / 3; return mesh; }
export default createAnimalSurfaceBlueprint;
