// B"H
/**
 * The Awtsmoos turns data into a city of tests: every selector a gate, every
 * canvas a window, every transform a storm that must still reveal truth.
 * @returns {Record<string,string>} complete runtime files for Mekrava.
 */
export function buildRuntimeFiles() {
  return { 'index.html': buildHtml(), 'mega-v2-worker.js': buildWorker() };
}

function css() {
  return `body{margin:0;background:#050b18;color:white;font-family:system-ui,sans-serif}.page{width:960px;height:640px;overflow:hidden;background:linear-gradient(135deg,#07162b,#132b55);display:flex;gap:8px;padding:10px;box-sizing:border-box}.left{display:grid;grid-template-rows:92px 1fr 132px;gap:8px;width:620px}.right{display:flex;flex-direction:column;gap:8px;flex:1}.card{position:relative;background:linear-gradient(135deg,#162c4e,#07101f);border:2px solid #48dcff;border-radius:16px;padding:8px;box-shadow:0 0 14px #00d9ff66}.sticky{position:absolute;top:6px;right:8px;background:#ffe14a;color:#07101f;border:2px solid white;border-radius:999px;padding:4px 9px;font-weight:800}.nested{display:flex;gap:7px;height:100%}.gridnest{display:grid;grid-template-columns:1fr 1fr;gap:7px;flex:1}.mini{background:#08162a;border:2px solid #8290ff;border-radius:12px;padding:5px;overflow:hidden}.tinygrid{display:grid;grid-template-columns:1fr 1fr;gap:5px}.control{background:#06152a;color:white;border:2px solid #00d9ff;border-radius:8px;padding:5px}.rainbow{height:15px;background:linear-gradient(90deg,red,orange,yellow,lime,cyan,blue,magenta);border:2px solid white;border-radius:99px}.clip{height:72px;overflow:hidden}.overlap{height:116px}.float{position:absolute;border:2px solid white;border-radius:10px;padding:6px;font-size:12px}.z1{left:28px;top:48px;background:#f40070;transform:rotate(-8deg);z-index:1}.z2{left:86px;top:66px;background:#00d9ff;color:#06101f;transform:scale(1.1);z-index:2}.z3{left:154px;top:42px;background:#ffe14a;color:#06101f;transform:translate(8px,16px) rotate(7deg);z-index:3}h1{font-size:22px;margin:0}h2{font-size:15px;margin:0 0 4px}.small{font-size:10px}.mid{text-align:center;font-size:18px}.big{text-align:right;font-size:28px;font-weight:900}.svgbox{background:#08162a;border:2px solid #00d9ff;border-radius:10px;height:74px}`;
}

function buildHtml() {
  return `<!doctype html><html><head><style>${css()}</style></head><body><main class="page">
<section class="left"><header class="card"><h1>MEGA MERKAVA V2 IMMENSE STRESS</h1><div class="sticky">STICKY SIM</div><p class="small">nested flex→grid→flex, overflow, z-index, shadow, rotate, scale, translate, SVG, ImageData, tiled pattern witness, WebGL texture state</p><div class="rainbow"></div></header>
<section class="card nested"><div class="gridnest"><div class="mini"><b>DOM CANVAS</b><canvas id="dom" width="285" height="132"></canvas></div><div class="mini"><b>OFFSCREEN</b><canvas id="off" width="285" height="132"></canvas></div><div class="mini"><b>WORKER</b><canvas id="worker" width="285" height="132"></canvas></div><div class="mini"><b>TILE + IMAGE DATA</b><canvas id="pattern" width="285" height="132"></canvas></div></div><div class="mini" style="width:180px"><h2>Mixed Text</h2><p class="small">left aligned tiny text</p><p class="mid">CENTER 18</p><p class="big">RIGHT 28</p><div class="svgbox"><svg width="166" height="72"><rect x="8" y="8" width="70" height="44" fill="magenta"/><circle cx="112" cy="36" r="24" fill="cyan"/><text x="18" y="66" fill="white">SVG WITNESS</text></svg></div></div></section>
<section class="card overlap"><h2>Z-INDEX / TRANSFORM / SHADOW</h2><div class="float z1">ROTATE</div><div class="float z2">SCALE</div><div class="float z3">TRANSLATE</div></section></section>
<aside class="right"><section class="card"><h2>WEBGL STATE WITNESS</h2><canvas id="webgl" width="288" height="172"></canvas></section><section class="card clip"><h2>OVERFLOW CLIP</h2><div style="height:120px;background:linear-gradient(180deg,red,yellow,lime,cyan,blue,magenta);transform:rotate(3deg);box-shadow:0 0 22px white"></div></section><section class="card"><h2>DARK CONTROLS</h2><div class="tinygrid"><input class="control" value="NAME V2"><select class="control"><option>MODE RENDER</option></select><textarea class="control">NOTE readable</textarea><button class="control">BUTTON</button></div></section><section class="card"><h2>LOWER STRIPS</h2><canvas id="strip" width="288" height="108"></canvas></section></aside>
<script>${clientScript()}</script></main></body></html>`;
}

function clientScript() {
  return `window.megaV2={ready:false};const pi=Math.PI*2;function rainbow(x,w,h){const g=x.createLinearGradient(0,0,w,0);['red','orange','yellow','lime','cyan','blue','magenta'].forEach((c,i)=>g.addColorStop(i/6,c));x.fillStyle=g;x.fillRect(0,0,w,h)}function label(x,t,y=124){x.fillStyle='white';x.font='13px sans-serif';x.fillText(t,12,y)}function pathCircle(x){x.strokeStyle='white';x.lineWidth=4;const p=new Path2D();p.ellipse(144,66,66,34,.22,0,pi);x.stroke(p)}const d=document.getElementById('dom').getContext('2d');rainbow(d,285,132);d.fillStyle='rgba(0,0,0,.5)';d.fillRect(24,18,230,82);pathCircle(d);label(d,'DOM PATH2D');const oc=new OffscreenCanvas(220,94),ox=oc.getContext('2d');rainbow(ox,220,94);ox.fillStyle='magenta';ox.fillRect(30,18,150,54);ox.rotate(.08);ox.fillStyle='cyan';ox.fillRect(96,22,54,45);label(ox,'INNER OFF',86);const off=document.getElementById('off').getContext('2d');off.fillStyle='#06121c';off.fillRect(0,0,285,132);off.drawImage(oc.transferToImageBitmap(),30,14);label(off,'OFFSCREEN NESTED');const w=new Worker('mega-v2-worker.js');w.onmessage=e=>{const wx=document.getElementById('worker').getContext('2d');wx.drawImage(e.data.bitmap,20,12,240,96);label(wx,'WORKER BITMAP');window.megaV2.worker=e.data.ok};w.postMessage({});const pat=document.getElementById('pattern').getContext('2d');for(let y=0;y<132;y+=18){for(let x=0;x<285;x+=18){pat.fillStyle=((x+y)/18)%2?'yellow':'blue';pat.fillRect(x,y,18,18)}}const img=pat.createImageData(64,32);for(let i=0;i<img.data.length;i+=4){img.data[i]=255;img.data[i+1]=(i/4)%255;img.data[i+2]=50;img.data[i+3]=255}pat.putImageData(img,104,50);label(pat,'TILED IMAGEDATA');const gl=document.getElementById('webgl').getContext('webgl');gl.viewport(0,0,288,172);gl.clearColor(.08,.02,.35,1);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,0,1]),gl.STATIC_DRAW);const tex=gl.createTexture();gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,2,2,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([255,0,0,255,0,255,255,255,255,255,0,255,255,0,255,255]));const vs=gl.createShader(gl.VERTEX_SHADER),fs=gl.createShader(gl.FRAGMENT_SHADER),pr=gl.createProgram();gl.shaderSource(vs,'attribute vec2 p;void main(){gl_Position=vec4(p,0,1);}');gl.shaderSource(fs,'precision mediump float;void main(){gl_FragColor=vec4(1,.8,.1,1);}');gl.compileShader(vs);gl.compileShader(fs);gl.attachShader(pr,vs);gl.attachShader(pr,fs);gl.linkProgram(pr);gl.useProgram(pr);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,3);const s=document.getElementById('strip').getContext('2d');rainbow(s,288,108);s.drawImage(oc.transferToImageBitmap(),18,18,110,48);s.fillStyle='rgba(0,0,0,.45)';s.fillRect(142,18,120,62);label(s,'DRAWIMAGE STRIP',96);window.megaV2.ready=true;window.megaV2.commands=document.textureArena.snapshot().commands.length;`;
}

function buildWorker() {
  return `onmessage=()=>{const c=new OffscreenCanvas(240,96),x=c.getContext('2d');const g=x.createLinearGradient(0,0,240,0);['lime','cyan','blue','magenta'].forEach((v,i)=>g.addColorStop(i/3,v));x.fillStyle=g;x.fillRect(0,0,240,96);x.fillStyle='black';x.fillRect(18,18,88,48);x.fillStyle='yellow';x.fillRect(128,22,58,42);x.strokeStyle='white';x.lineWidth=4;const p=new Path2D();p.arc(120,48,34,0,6.283);x.stroke(p);postMessage({ok:true,bitmap:c.transferToImageBitmap()});};`;
}
