// B"H
/** @file cottage.js @description Simple brick village cottage; visible meshes are the collision source. */
import * as THREE from "/games/scripts/build/three.module.js";
import { finite } from "../math.js";
import { markDecorative } from "../decor.js";
import { lambertNoise, basicGlow } from "../lambert.js?v=shader-lambert-20260604-bh437";
const box=(w,h,d,mat)=>new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);
const mat=(color,alt,ctx)=>lambertNoise(color,alt,ctx);
function solid(mesh,name){mesh.name=name;Object.assign(mesh.userData||={}, {isSolid:true,addToOctree:true,skipOctree:false,noOctree:false,visibleCollisionSource:true,useExactGeometryCollider:true});return mesh;}
function decor(obj){markDecorative(obj);return obj;}
function windowBox(x,y,z,ctx){const g=new THREE.Group();g.add(box(1.0,.82,.08,mat(0x3a2417,0x4c2d18,ctx)));const sill=box(1.12,.13,.16,new THREE.MeshLambertMaterial({color:0x5b3a1f}));sill.position.set(0,-.52,.05);g.add(sill);g.position.set(x,y,z);return decor(g);}
function lantern(x,y,z){const g=new THREE.Group();g.add(box(.16,.42,.16,new THREE.MeshLambertMaterial({color:0x24150c})));const glow=new THREE.Mesh(new THREE.SphereGeometry(.28,12,8),basicGlow(0xffb45d,.33));g.add(glow);g.position.set(x,y,z);return decor(g);}
function ivy(x,z,h){const mesh=new THREE.Mesh(new THREE.PlaneGeometry(1.1,h),new THREE.MeshLambertMaterial({color:0x2f6f2f,transparent:true,opacity:.72,side:THREE.DoubleSide}));mesh.position.set(x,h/2,z);return decor(mesh);}
function gable(w,h,z,ctx,name){const hw=w/2,geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute([-hw,0,z, hw,0,z, 0,h,z],3));geo.setIndex([0,1,2]);geo.computeVertexNormals();return solid(new THREE.Mesh(geo,mat(0xb8aa89,0x9b8d72,ctx)),name);}
function roofPanel(w,len,thick,color,ctx,name,side){const g=new THREE.BoxGeometry(w,thick,len);const m=mat(color,0x9e3c25,ctx);const mesh=solid(new THREE.Mesh(g,m),name);mesh.rotation.x=side*.43;return mesh;}
function addBrickLines(group,w,d,h,ctx){const m=mat(0x8d6b45,0x6d4d32,ctx);for(let y=.45;y<h-.25;y+=.42){for(const z of [-d/2-.016,d/2+.016]){const r=box(w,.035,.035,m);r.position.set(0,y,z);group.add(solid(r,`visible_brick_mortar_row_${z>0?'front':'back'}_${y.toFixed(1)}`));}}}
function doorSpec(op,d,h){return{x:finite(op.doorX,0),width:finite(op.doorWidth,1.45),height:finite(op.doorHeight,Math.min(2.5,h*.68)),y:finite(op.doorY,Math.min(1.25,h*.34)),z:d/2+finite(op.doorFaceGap,.08)};}
function addFrontDetails(group,op,w,d,h,ctx){const ds=doorSpec(op,d,h);const door=box(ds.width,ds.height,.14,mat(finite(op.doorColor,0x4b2c18),0x4b2c18,ctx));door.name="visual_cottage_door_contract_aligned";door.position.set(ds.x,ds.y,ds.z);group.add(decor(door));const lx=Math.max(-w*.36,ds.x-ds.width*1.45-1.1),rx=Math.min(w*.36,ds.x+ds.width*1.45+1.1);group.add(windowBox(rx,h*.51,d/2+.1,ctx),windowBox(lx,h*.5,d/2+.1,ctx),lantern(ds.x+ds.width*.95,h*.5,d/2+.25),ivy(w*.44,d/2+.12,Math.min(3.4,h*.82)));}
export function createCottage(op={},ctx={}){const w=finite(op.width,8),d=finite(op.depth,6),h=finite(op.height,4.2),renderCtx={renderer:ctx.renderer||ctx.olam?.renderer||op.renderer};const group=new THREE.Group();group.name=op.name||"AwtsmoosCottage_visible_triangle_house";const wall=solid(box(w,h,d,mat(finite(op.wallColor,0xb8aa89),0x9b8d72,renderCtx)),"visual_cottage_brick_wall_mass");wall.position.y=h/2;group.add(wall);addBrickLines(group,w,d,h,renderCtx);const roofColor=finite(op.roofColor,0x9e3c25),over=.42,rise=1.28,roofW=Math.sqrt((d/2+over)**2+rise**2);const left=roofPanel(w+over*2,roofW,.22,roofColor,renderCtx,"visual_cottage_roof_left_continuous",-1);left.position.set(0,h+rise*.5,-(d/4+over*.23));const right=roofPanel(w+over*2,roofW,.22,roofColor,renderCtx,"visual_cottage_roof_right_continuous",1);right.position.set(0,h+rise*.5,d/4+over*.23);group.add(left,right);const fg=gable(w,h*.01+rise,d/2+.02,renderCtx,"visual_front_triangular_gable");fg.position.y=h;const bg=gable(w,h*.01+rise,-d/2-.02,renderCtx,"visual_back_triangular_gable");bg.position.y=h;bg.rotation.y=Math.PI;group.add(fg,bg);addFrontDetails(group,op,w,d,h,renderCtx);group.position.set(finite(op.position?.x),finite(op.position?.y),finite(op.position?.z));group.rotation.y=finite(op.rotationY,0);group.scale.setScalar(finite(op.scale,1));Object.assign(group.userData||={}, {cottageGenerator:"awtsmoos3d",doorContractAligned:true,visibleHouseOctreeOnly:true,doorX:finite(op.doorX,0)});return group;}
