// B"H
/** @file AnimalRuntimeFactory.js @description Animals are living leveled entities with physiology, needs, moves, herds, feeding, and XP value. */
import { speciesProfile } from "./KosherAnimalSpecies.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { animalGenes } from "./AnimalGeneticsModel.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { animalBehaviorPlan } from "./AnimalBehaviorModel.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { animalPhysiology } from "./AnimalPhysiologyModel.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { animalDailyNeeds, tickAnimalNeeds } from "./AnimalDailyNeeds.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { buildHerd } from "./AnimalHerdRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { createAnimalFeedingRuntime } from "./AnimalFeedingRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { animalCombatProfile } from "./AnimalCombatProfile.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { dangerForPosition } from "../../world/runtime/DistanceDangerRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
export function createAnimalEntity(spec={},world={}){ const species=spec.species||"sheep", seed=spec.seed||spec.name||species, genes=animalGenes(species,seed), needs=animalDailyNeeds(spec), position=spec.position||{x:0,z:0}, danger=dangerForPosition(position), level=spec.level||Math.max(1,danger.level-1), physiology=animalPhysiology(species,genes), combat=animalCombatProfile({species,level,physiology}); return { id:spec.id||`animal_${species}_${String(seed).replace(/\s+/g,"_")}`, kind:"animal", name:spec.name||species, tags:["animal",species,"kosher",`level:${level}`], level, position, danger, profile:speciesProfile(species), genes, physiology, combat, moves:combat.moves, stats:combat.stats, xpValue:combat.xpValue, behavior:animalBehaviorPlan({...spec,needs},world), herdId:spec.herdId||`${species}_herd`, needs, availableFoods:spec.availableFoods||[], senses:{smell:.8,hearing:.7,sight:species.match(/duck|goose|dove|pigeon|chicken|turkey/)? .9:.65}, realism:"leveled-physiology-herd-needs-feeding-v3" }; }
export function tickAnimalEntity(animal,dt=1,world={},feeding=null){ const needs=tickAnimalNeeds(animal.needs||{},dt), next={...animal,needs,behavior:animalBehaviorPlan({...animal,needs},world)}; if(["seek-food","seek-water"].includes(next.behavior.state)&&feeding) return feeding.feed(next,world); return next; }
export function installAnimals(runtime,specs=[],world={}){ const animals=specs.map(spec=>createAnimalEntity(spec,world)), herds=buildHerd(animals), feeding=createAnimalFeedingRuntime(runtime); for(const animal of animals) runtime?.registerEntity?.(animal); for(const herd of herds) runtime?.registerEntity?.({id:`herd_${herd.id}`,kind:"herd",tags:["herd",herd.species],...herd}); const api={animals,herds,feeding,tick:(dt=1,w=world)=>animals.map((a,i)=>animals[i]=tickAnimalEntity(a,dt,w,feeding)), snapshot:()=>({count:animals.length,herds:herds.length,levels:animals.map(a=>a.level),feeding:feeding.snapshot()})}; runtime.animals=api; runtime?.markReady?.("animals:runtime",{count:animals.length,herds:herds.length,realism:"leveled-physiology-herd-needs-feeding-v3"}); return animals; }
export default createAnimalEntity;
