// B"H
import { createRequire } from 'module';
import fs from 'fs/promises';
import os from 'os';
import path from 'path';
import assert from 'assert/strict';
const require = createRequire(import.meta.url);
const Lock = require('../../mission/lock/index.js');
const Firewall = require('../../mission/firewall/index.js');
const Receipts = require('../../mission/toolReceipts/index.js');
const Quota = require('../../mission/evidenceQuota/index.js');
const Oath = require('../../mission/oath/index.js');
const Snapshot = require('../../mission/snapshot/index.js');
const StopAudit = require('../../mission/stopAudit/index.js');
const Takeover = require('../../mission/takeover/index.js');
const Deadman = require('../../mission/deadman/index.js');
const Final = require('../../mission/finalInterceptor/index.js');
const root = await fs.mkdtemp(path.join(os.tmpdir(), 'mission-hardening-'));
const config = { root, repoRoot: process.cwd() };
let lock = Lock.start(config, { action:'missionStart', missionId:'m1', mustCallNext:{ action:'missionNext', missionId:'m1' } }, { autoSeedNext8:false, minimumRuntimeMs:0 });
lock.minimumUntil = new Date(Date.now() - 1000).toISOString(); lock.evidenceQuotas = { inspection:1, verification:1, review:0, repeatBetter:0 }; Lock.set(config, lock);
let denied = Firewall.check(config, 'write', lock, { path:'x.js' });
assert.equal(denied.ok, false); assert(denied.missionWriteToken);
let wrongPath = Firewall.check(config, 'write', lock, { action:'write', path:'other.js', missionWriteToken:denied.missionWriteToken });
assert.equal(wrongPath.ok, false);
let allowed = Firewall.check(config, 'write', lock, { action:'write', path:'x.js', missionWriteToken:denied.missionWriteToken });
assert.equal(allowed.ok, true);
Receipts.after(config, { action:'read' }, { ok:true, action:'read' });
let q1 = Quota.issues(config, lock); assert(q1.issues.some(x => x.startsWith('quota_verification')));
Receipts.after(config, { action:'commandRun' }, { ok:true, action:'commandRun' });
let q2 = Quota.issues(config, lock); assert.equal(q2.issues.length, 0);
assert.equal(Oath.accept(config, lock, { agentId:'alpha' }).agentId, 'alpha');
assert.equal(Snapshot.take(config, lock, 'test').reason, 'test');
lock.updatedAt = new Date(Date.now() - 999999).toISOString(); assert.equal(Deadman.stale(lock, 1000), true);
assert.equal(Takeover.claim(lock, 'beta').owner, 'beta');
let intercepted = Final.intercept(lock, { ok:true, action:'missionReport', finalAnswerAllowed:true });
StopAudit.after(config, lock, intercepted); assert.equal(StopAudit.list(config).length, 1);
console.log(JSON.stringify({ ok:true, token:denied.missionWriteToken.slice(0,7), quota:q2.issues.length, stopAttempts:StopAudit.list(config).length }, null, 2));
