// B"H
import { createRequire } from 'module';
import fs from 'fs/promises';
import os from 'os';
import path from 'path';
import assert from 'assert/strict';
const require = createRequire(import.meta.url);
const Lock = require('../../mission/lock/index.js');
const Boot = require('../../mission/boot/index.js');
const Firewall = require('../../mission/firewall/index.js');
const Court = require('../../mission/releaseCourt/index.js');
const Final = require('../../mission/finalInterceptor/index.js');
const root = await fs.mkdtemp(path.join(os.tmpdir(), 'boot-firewall-token-'));
const config = { root, repoRoot: process.cwd() };
let lock = Lock.start(config, { action:'missionStart', missionId:'m1', mustCallNext:{ action:'noop', missionId:'m1' } }, { autoSeedNext8:false, minimumRuntimeMs:0 });
lock.next8Completed = true; lock.repeatBetterDone = true; lock.verificationSeen = true; lock.evidenceQuotas = { inspection:0, verification:0, implementation:0, review:0, repeatBetter:0 }; lock.minimumUntil = new Date(Date.now() - 1000).toISOString(); Lock.set(config, lock);
const boot = await Boot.resume(config, { tick:false }, () => ({}));
assert.equal(boot.resumed, true);
assert.equal(Firewall.classify('read'), 'missionEvidence');
const writeDenied = Firewall.check(config, 'write', lock, {});
assert.equal(writeDenied.ok, false);
assert(writeDenied.missionWriteToken);
assert.equal(Firewall.check(config, 'write', lock, { missionStepAuthorized:true }).ok, true);
let first = Court.guard(config, lock, { ok:true, action:'missionFinalize', finalAnswerAllowed:true, mustContinue:false }, {});
assert.equal(first.finalAnswerAllowed, false);
assert(first.releaseToken);
Lock.update(config, first, {});
lock = Lock.active(config);
let second = Court.guard(config, lock, { ok:true, action:'missionFinalize', finalAnswerAllowed:true, mustContinue:false }, { releaseToken:first.releaseToken });
assert.equal(second.finalAnswerAllowed, true);
let intercepted = Final.intercept(lock, { ok:true, action:'missionReport', finalAnswerAllowed:true });
assert.equal(intercepted.finalAnswerAllowed, false);
console.log(JSON.stringify({ ok:true, boot:boot.resumed, token:first.releaseToken.slice(0,7), firewall:Firewall.classify('read') }, null, 2));
