// B"H
/** @file index.js @description Minimal scene loader with specific village object proof and no slow asset-size sweep. */
import instantiate from "./instantiateMezuzahDirect.js?compact=true&v=npc-source-body-prune-20260708-bh1";
import lifecycle from "./lifecycle.js?compact=true&v=fps-door-target-idle-20260708-bh1";
import TimeTracker from "../../../utils/TimeTracker.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { diagEvent, installDiagnosticsNotice } from "../../../utils/AwtsmoosDiagnostics.js?compact=true&v=village-diagnostics-20260612-bh2";
import { scheduleVillageGrounding } from "./villageGrounding.js?compact=true&v=hard-player-grounding-20260701-bh1";
import { applyEntryRuntime } from "./entryRuntime/applyEntryRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { runMitzvahWorldPostBuild } from "../../worlds/mitzvahWorld/postbuild/MitzvahWorldPostBuild.js?compact=true&v=vehicles-u-mount-20260706-bh1";
import { postWorkerProgress } from "../../oyved/core/protocol/WorkerProtocol.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { makeWorkerWorldReport } from "../../../../systems/visuals/WorkerWorldReport.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { ensureStarterStationZone } from "../../../../systems/starterStation/StarterStationBuilder.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import PLAYER_SCHOOL_CHECKLIST from "../../../../systems/schools/PlayerSchoolChecklist.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
const RESTORED_VISUAL_TYPES=["VillagePictureProp","VillageTreeField","VillageHeroTree","VillageGrassField","VillageStonePath","VillageBackdrop","VillageSkyLayers"];
const flag=(olam,name)=>Boolean(olam?.baseInfo?.[name]||olam?.baseInfo?.testWorldFlags?.[name]);
function mark(stage,fields={}){console.info('B"H | LOAD_NIVRAYIM_PROOF',{stage,...fields});postWorkerProgress(`load-nivrayim:${stage}`,fields);}
function authoredCount(nivrayim){if(!nivrayim||typeof nivrayim!=="object")return 0;if(Array.isArray(nivrayim))return nivrayim.length;return Object.values(nivrayim).reduce((s,v)=>s+(Array.isArray(v)?v.length:v&&typeof v==="object"?Object.keys(v).length:0),0);}
function isPlayerSoul(nivra){return nivra?.type==="chossid"||nivra?.constructor?.name==="Chossid";}
function registerPlayerSouls(olam,list,stage){let count=0;for(const nivra of list||[]){if(!isPlayerSoul(nivra))continue;nivra.olam=olam;nivra.heesHawveh=true;olam.chossid=nivra;olam.player=nivra;if(!olam.nivrayim.includes(nivra))olam.nivrayim.push(nivra);count++;}if(count)diagEvent("player-registered",{stage,count,nivrayim:olam.nivrayim.length});}
function performanceDefinitions(nivrayim){if(!nivrayim||typeof nivrayim!=="object"||Array.isArray(nivrayim))return nivrayim;const next={};for(const[k,v]of Object.entries(nivrayim))next[k]=v;return next;}
function publishWorldReport(olam,scene,nivrayimMade,startedAt,postbuild,starterStation){const report=makeWorkerWorldReport({olam,scene,nivrayim:nivrayimMade,elapsedMs:performance.now()-startedAt,source:olam?.baseInfo?.id||olam?.baseInfo?.shaym||null,postbuild,starterStation});olam.__awtsmoosWorkerWorldReport=report;mark("world-report",{worldReport:report});return report;}
async function runPostbuildTruth(olam,scene,nivrayimMade){if(flag(olam,"skipMitzvahWorldPostBuild"))return{ok:true,skipped:true,elapsedMs:0,source:"skipMitzvahWorldPostBuild"};const started=performance.now();try{await runMitzvahWorldPostBuild({olam,scene,nivrayim:nivrayimMade,worldData:olam.baseInfo||{},source:olam.baseInfo?.id||olam.baseInfo?.shaym||null});return{ok:true,elapsedMs:Math.round(performance.now()-started),source:"runMitzvahWorldPostBuild"};}catch(error){return{ok:false,elapsedMs:Math.round(performance.now()-started),source:"runMitzvahWorldPostBuild",error:error?.message||String(error)};}}
async function runStarterStationTruth(olam,scene){if(flag(olam,"skipStarterStation"))return{ok:true,skipped:true,elapsedMs:0,source:"skipStarterStation"};const started=performance.now();olam.__playerSchoolChecklist=PLAYER_SCHOOL_CHECKLIST;try{const report=await ensureStarterStationZone({olam,scene,source:olam?.baseInfo?.id||olam?.baseInfo?.shaym||"mitzvahWorld"});report.elapsedMs=Math.round(performance.now()-started);return report;}catch(error){return{ok:false,error:error?.message||String(error),elapsedMs:Math.round(performance.now()-started)};}}
export default class LoadNivrayim{async addObject(type,options){return await instantiate.addObject.call(this,type,options);}async loadNivrayim(nivrayim){const startedAt=performance.now();try{installDiagnosticsNotice();TimeTracker.start("LOAD_NIVRAYIM");const defs=performanceDefinitions(nivrayim);mark("start",{authored:authoredCount(nivrayim),optimizedAuthored:authoredCount(defs),restoredVisualTypes:RESTORED_VISUAL_TYPES});const nivrayimMade=instantiate.parseDefinitions.call(this,defs);mark("parse-done",{count:nivrayimMade.length,elapsedMs:Math.round(performance.now()-startedAt)});registerPlayerSouls(this,nivrayimMade,"after-parse");this.totalSize=0;for(const nivra of nivrayimMade){nivra.olam=this;nivra.assetSize=0;nivra.loadingAssetSize=0;}mark("asset-size-skipped",{reason:"minimal-may-new-year-scene",count:nivrayimMade.length});await lifecycle.runHeescheel.call(this,nivrayimMade);mark("heescheel-done",{elapsedMs:Math.round(performance.now()-startedAt),nivrayim:this.nivrayim.length});registerPlayerSouls(this,nivrayimMade,"after-heescheel");await lifecycle.runMadeAll.call(this,nivrayimMade);mark("madeAll-done");for(const nivra of nivrayimMade)await this.doPlaceholderAndEntityLogic(nivra);mark("placeholder-done");await lifecycle.runReady.call(this,nivrayimMade);mark("ready-done");await lifecycle.runAfterBriyah.call(this,nivrayimMade);mark("afterBriyah-done");if(!flag(this,"skipVillageGrounding")){scheduleVillageGrounding(this,nivrayimMade);mark("village-grounding-scheduled");}applyEntryRuntime(this,defs||{});mark("entry-runtime-done");const postbuild=await runPostbuildTruth(this,this.scene,nivrayimMade);mark(postbuild.ok?"postbuild-done":"postbuild-error",{postbuild});const starterStation=await runStarterStationTruth(this,this.scene);const worldReport=publishWorldReport(this,this.scene,nivrayimMade,startedAt,postbuild,starterStation);this.ayshPeula("updateProgress",{loadedNivrayim:Date.now(),workerWorldReport:worldReport});if(!this.enlightened&&typeof this.ohr==="function"){try{this.ohr();}catch(error){console.error('B"H | OHR_FAILED',{message:error?.message||String(error)});}}TimeTracker.finish("LOAD_NIVRAYIM","Minimal scene loaded with proof logs.");mark("done",{count:nivrayimMade.length,elapsedMs:Math.round(performance.now()-startedAt)});return nivrayimMade||[];}catch(error){console.error('B"H | LOAD_NIVRAYIM_FATAL',{message:error?.message||String(error),stack:String(error?.stack||'').slice(0,1200)});diagEvent("load-nivrayim-failed",{message:error?.message||String(error)},"error");mark("error",{message:error?.message||String(error)});return[];}}}
