// B"H
/** @file index.js @description Parser-plain compact scene loader with quiet proofs unless explicitly debugged. */
import instantiate from "./instantiateMezuzahDirect.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import lifecycle from "./lifecycle.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import TimeTracker from "../../../utils/TimeTracker.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import { diagEvent, installDiagnosticsNotice } from "../../../utils/AwtsmoosDiagnostics.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import { scheduleVillageGrounding } from "./villageGrounding.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import { applyEntryRuntime } from "./entryRuntime/applyEntryRuntime.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import { runMitzvahWorldPostBuild } from "../../worlds/mitzvahWorld/postbuild/MitzvahWorldPostBuild.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import { postWorkerProgress } from "../../oyved/core/protocol/WorkerProtocol.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import { makeWorkerWorldReport } from "../../../../systems/visuals/WorkerWorldReport.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import { ensureStarterStationZone } from "../../../../systems/starterStation/StarterStationBuilder.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import PLAYER_SCHOOL_CHECKLIST from "../../../../systems/schools/PlayerSchoolChecklist.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
const RESTORED_VISUAL_TYPES = ["VillagePictureProp", "VillageTreeField", "VillageHeroTree", "VillageGrassField", "VillageStonePath", "VillageBackdrop", "VillageSkyLayers"];
function now() { return typeof performance !== "undefined" && performance.now ? performance.now() : Date.now(); }
function msg(error) { return error?.message ? error.message : String(error || "unknown"); }
function flag(olam, name) { const b = olam?.baseInfo, t = b?.testWorldFlags; return Boolean(b?.[name] || t?.[name]); }
function extend(a, b) { return { ...(a || {}), ...(b || {}) }; }
function shouldLog(stage) { return globalThis.__AWTS_DEBUG_LOAD_NIVRAYIM__ === true || /^(start|error|done|world-report)$/.test(stage); }
function mark(stage, fields) { const payload = extend(fields, { stage:"load-nivrayim:" + stage, action:"Loading world scene", subAction:"World loader step: " + stage }); globalThis.__LOAD_NIVRAYIM_LAST_PROOF__ = payload; if (shouldLog(stage)) console.info('B"H | LOAD_NIVRAYIM_PROOF', payload); postWorkerProgress("load-nivrayim:" + stage, payload); }
function authoredCount(nivrayim) { if (!nivrayim || typeof nivrayim !== "object") return 0; if (Array.isArray(nivrayim)) return nivrayim.length; let total = 0; for (const k in nivrayim) { const v = nivrayim[k]; total += Array.isArray(v) ? v.length : v && typeof v === "object" ? Object.keys(v).length : 0; } return total; }
function isPlayerSoul(nivra) { return Boolean(nivra && (nivra.type === "chossid" || nivra.constructor?.name === "Chossid")); }
function registerPlayerSouls(olam, list, stage) { let count = 0; for (const nivra of list || []) { if (!isPlayerSoul(nivra)) continue; nivra.olam = olam; nivra.heesHawveh = true; olam.chossid = nivra; olam.player = nivra; if (olam.nivrayim.indexOf(nivra) < 0) olam.nivrayim.push(nivra); count++; } if (count) diagEvent("player-registered", { stage, count, nivrayim:olam.nivrayim.length }); }
function performanceDefinitions(nivrayim) { return !nivrayim || typeof nivrayim !== "object" || Array.isArray(nivrayim) ? nivrayim : { ...nivrayim }; }
function sourceName(olam) { const b = olam?.baseInfo; return b ? b.id || b.shaym || null : null; }
function publishWorldReport(olam, scene, nivrayimMade, startedAt, postbuild, starterStation) { const report = makeWorkerWorldReport({ olam, scene, nivrayim:nivrayimMade, elapsedMs:now() - startedAt, source:sourceName(olam), postbuild, starterStation }); olam.__awtsmoosWorkerWorldReport = report; mark("world-report", { worldReport:report }); return report; }
async function runPostbuildTruth(olam, scene, nivrayimMade) { const started = now(); if (flag(olam, "skipMitzvahWorldPostBuild")) return { ok:true, skipped:true, elapsedMs:0, source:"skipMitzvahWorldPostBuild" }; try { await runMitzvahWorldPostBuild({ olam, scene, nivrayim:nivrayimMade, worldData:olam?.baseInfo || {}, source:sourceName(olam) }); return { ok:true, elapsedMs:Math.round(now() - started), source:"runMitzvahWorldPostBuild" }; } catch (error) { return { ok:false, elapsedMs:Math.round(now() - started), source:"runMitzvahWorldPostBuild", error:msg(error) }; } }
async function runStarterStationTruth(olam, scene) { const started = now(); if (flag(olam, "skipStarterStation")) return { ok:true, skipped:true, elapsedMs:0, source:"skipStarterStation" }; olam.__playerSchoolChecklist = PLAYER_SCHOOL_CHECKLIST; try { const report = await ensureStarterStationZone({ olam, scene, source:sourceName(olam) || "mitzvahWorld" }); report.elapsedMs = Math.round(now() - started); return report; } catch (error) { return { ok:false, error:msg(error), elapsedMs:Math.round(now() - started) }; } }
export default class LoadNivrayim { async addObject(type, options) { return await instantiate.addObject.call(this, type, options); } async loadNivrayim(nivrayim) { const startedAt = now(); let defs, nivrayimMade = [], postbuild, starterStation, worldReport; try { installDiagnosticsNotice(); TimeTracker.start("LOAD_NIVRAYIM"); defs = performanceDefinitions(nivrayim); mark("start", { authored:authoredCount(nivrayim), optimizedAuthored:authoredCount(defs), restoredVisualTypes:RESTORED_VISUAL_TYPES }); nivrayimMade = instantiate.parseDefinitions.call(this, defs); mark("parse-done", { count:nivrayimMade.length, elapsedMs:Math.round(now() - startedAt) }); registerPlayerSouls(this, nivrayimMade, "after-parse"); this.totalSize = 0; for (const nivra of nivrayimMade) { nivra.olam = this; nivra.loadingAssetSize = 0; if (!Number.isFinite(Number(nivra.assetSize))) nivra.assetSize = 0; } mark("asset-size-skipped", { reason:"minimal-scene-no-slow-sweep", count:nivrayimMade.length }); await lifecycle.runHeescheel.call(this, nivrayimMade); mark("heescheel-done", { elapsedMs:Math.round(now() - startedAt), nivrayim:this.nivrayim.length }); registerPlayerSouls(this, nivrayimMade, "after-heescheel"); await lifecycle.runMadeAll.call(this, nivrayimMade); mark("madeAll-done", {}); for (const nivra of nivrayimMade) await this.doPlaceholderAndEntityLogic(nivra); mark("placeholder-done", {}); await lifecycle.runReady.call(this, nivrayimMade); mark("ready-done", {}); await lifecycle.runAfterBriyah.call(this, nivrayimMade); mark("afterBriyah-done", {}); if (!flag(this, "skipVillageGrounding")) { scheduleVillageGrounding(this, nivrayimMade); mark("village-grounding-scheduled", {}); } applyEntryRuntime(this, defs || {}); mark("entry-runtime-done", {}); postbuild = await runPostbuildTruth(this, this.scene, nivrayimMade); mark(postbuild.ok ? "postbuild-done" : "postbuild-error", { postbuild }); starterStation = await runStarterStationTruth(this, this.scene); worldReport = publishWorldReport(this, this.scene, nivrayimMade, startedAt, postbuild, starterStation); this.ayshPeula("updateProgress", { loadedNivrayim:Date.now(), workerWorldReport:worldReport }); if (!this.enlightened && typeof this.ohr === "function") { try { this.ohr(); } catch (error) { console.error('B"H | OHR_FAILED', { message:msg(error) }); } } TimeTracker.finish("LOAD_NIVRAYIM", "Minimal scene loaded with quiet proof ledger."); mark("done", { count:nivrayimMade.length, elapsedMs:Math.round(now() - startedAt) }); return nivrayimMade || []; } catch (error) { console.error('B"H | LOAD_NIVRAYIM_FATAL', { message:msg(error), stack:String(error?.stack || "").slice(0, 1200) }); diagEvent("load-nivrayim-failed", { message:msg(error) }, "error"); mark("error", { message:msg(error) }); return []; } } }
