// B"H
/**
 * @file villageGrounding.js
 * @description
 * Chapter 571: Colliders are baked only after the village is still.
 *
 * The house-wall bug returned because collider clones entered octree while
 * visual props were still being grounded/posed. This version separates three
 * phases: visual settle, verification settle, final collider bake. The final
 * bake is delayed and guarded so it runs once, after the visual meshes report
 * finite final world matrices.
 */
import * as THREE from "/games/scripts/build/three.module.js";
const RAY = new THREE.Raycaster();
const DOWN = new THREE.Vector3(0, -1, 0);
const TYPES = new Set(["villagePictureProp", "villageTreeField", "villageGrassField", "interactiveNpc", "interactiveDoor", "villageHouseCollider", "villageFenceCollider", "villageRoadCollider", "chossid"]);
const DOORWAY = new THREE.Vector3(0, 0, 2.68);
const num = (v, f = 0) => Number.isFinite(Number(v)) ? Number(v) : f;
const isLiving = n => n?.type === "interactiveNpc" || n?.type === "chossid";
const authoredY = n => Boolean(n?.useAuthoredY || n?.options?.useAuthoredY || n?.mesh?.userData?.useAuthoredY || /Collider$/.test(n?.type || ""));
function isVillageWorld(olam, made = []) { const i = olam?.baseInfo || {}, id = String(i.id || i.shaym || i.title || "").toLowerCase(); return id.includes("village") || made.some(n => TYPES.has(n?.type)); }
function terrainMeshes(olam) { const out = []; for (const n of olam?.nivrayim || []) if (n?.type === "proceduralTerrain" && n.mesh) out.push(n.mesh); if (!out.length) olam?.scene?.traverse?.(o => { if (o?.userData?.isTerrain) out.push(o); }); return out; }
function terrainLawY(olam, x, z) { const law = olam?.awtsmoosTerrainLaw; if (!law?.data?.heightPoints) return null; let best = null; for (const p of law.data.heightPoints) { const dx = x - num(law.position?.x) - num(p.x), dz = z - num(law.position?.z) - num(p.z), d = dx * dx + dz * dz; if (!best || d < best.d) best = { d, y: num(law.position?.y) + num(p.y) }; } return best?.y ?? null; }
function groundAt(olam, meshes, x, z) { const lawY = terrainLawY(olam, x, z); if (Number.isFinite(lawY)) return lawY; if (!meshes.length) return 0; RAY.set(new THREE.Vector3(x, 220, z), DOWN); RAY.far = 520; return RAY.intersectObjects(meshes, true).filter(hit => !hit.object?.userData?.skipRaycast)[0]?.point?.y ?? 0; }
function worldPoint(root) { const p = new THREE.Vector3(); root?.getWorldPosition?.(p); return p; }
function worldMinY(root) { root?.updateMatrixWorld?.(true); const box = new THREE.Box3().setFromObject(root); return !box.isEmpty() && Number.isFinite(box.min.y) ? box.min.y : null; }
function finiteObject(root) { let ok = Boolean(root?.isObject3D); root?.updateMatrixWorld?.(true); root?.traverse?.(child => { if (!child.isObject3D) return; const p = new THREE.Vector3(); child.getWorldPosition(p); if (![p.x, p.y, p.z].every(Number.isFinite)) ok = false; }); return ok; }
function liftOf(n) { return num(n?.options?.groundLift ?? n?.groundLift ?? n?.originalOptions?.groundLift, 0); }
function syncLiving(n, y) { const p = n.mesh?.position || n.modelMesh?.position || { x: 0, z: 0 }; if (typeof n.setPosition === "function") n.setPosition(new THREE.Vector3(num(p.x), y, num(p.z))); else if (n.mesh?.position) n.mesh.position.y = y; n.velocity?.set?.(0, 0, 0); Object.assign(n, { onFloor: true, isOnGround: true, grounded: true }); n._syncMesh?.(1 / 60); }
function allCandidates(olam, made) { const seen = new Set(), list = []; for (const n of [...(made || []), ...(olam?.nivrayim || [])]) if (n && (TYPES.has(n.type) || n?.mesh?.userData?.villageDecor) && !seen.has(n)) { seen.add(n); list.push(n); } for (const n of [olam?.chossid, olam?.player]) if (n && !seen.has(n)) { seen.add(n); list.push(n); } return list; }
function visualByName(c, name) { return c.find(n => n?.mesh && n?.name === name); }
function firstKind(c, kind) { return c.find(n => n?.type === "villagePictureProp" && n.options?.kind === kind); }
function groundOne(olam, meshes, n) { const root = n?.mesh || n?.modelMesh; if (!root?.isObject3D) return null; if (authoredY(n) && !isLiving(n)) return { name: n.name, type: n.type, authoredY: root.position.y, moved: false }; const p = worldPoint(root), y = groundAt(olam, meshes, p.x, p.z) + liftOf(n); if (isLiving(n)) { syncLiving(n, y); return { name: n.name, type: n.type, groundY: y, moved: true }; } const minY = worldMinY(root); if (minY === null) return null; const delta = y - minY; if (Math.abs(delta) > 0.0001) root.position.y += delta; root.updateMatrixWorld(true); return { name: n.name, type: n.type, groundY: y, minY, moved: Math.abs(delta) > 0.0001 }; }
function alignDoor(c) { const door = c.find(n => n?.type === "interactiveDoor" && n.mesh), house = visualByName(c, door?.options?.targetName) || firstKind(c, "gableHouse"); if (!door || !house?.mesh) return null; if (door.alignToHouseTransform?.(house.mesh)) return { name: door.name, type: door.type, targetName: house.name, method: "contract", moved: true }; const p = DOORWAY.clone(); house.mesh.localToWorld(p); door.mesh.position.copy(p); door.mesh.rotation.y = house.mesh.rotation.y; door.mesh.updateMatrixWorld(true); return { name: door.name, type: door.type, targetName: house.name, method: "fallback", moved: true }; }
function colliderReady(collider, visual) { return Boolean(collider?.mesh && finiteObject(collider.mesh) && (!visual?.mesh || finiteObject(visual.mesh))); }
function bakeFinalColliders(olam, c) { const out = []; for (const collider of c.filter(n => n?.type === "villageHouseCollider" && n.mesh)) { const visual = visualByName(c, collider.options?.targetName) || firstKind(c, "gableHouse"); const ready = colliderReady(collider, visual); const aligned = ready && visual?.mesh ? collider.alignToFinalHouseTransform?.(visual.mesh) || false : false; out.push({ name: collider.name, type: collider.type, targetName: visual?.name, ready, aligned, phase: "final-only-after-settle", octreeMeshesAdded: aligned ? collider.addFinalCollidersToOctree?.(olam) || 0 : 0 }); } for (const collider of c.filter(n => n?.type === "villageFenceCollider" && n.mesh)) { const ready = colliderReady(collider); out.push({ name: collider.name, type: collider.type, ready, phase: "final-only-after-settle", octreeMeshesAdded: ready ? collider.addFinalCollidersToOctree?.(olam) || 0 : 0 }); } for (const collider of c.filter(n => n?.type === "villageRoadCollider" && n.mesh)) { const visual = visualByName(c, collider.targetName || collider.options?.targetName) || firstKind(c, "pictureDirtPath"); const ready = colliderReady(collider, visual); const aligned = ready && visual?.mesh ? collider.alignToFinalRoadTransform?.(visual.mesh) || false : false; out.push({ name: collider.name, type: collider.type, targetName: visual?.name, ready, aligned, phase: "final-only-after-settle", octreeMeshesAdded: aligned ? collider.addFinalCollidersToOctree?.(olam) || 0 : 0 }); } return out; }
function settleVisuals(olam, made) { const meshes = terrainMeshes(olam), candidates = allCandidates(olam, made), report = candidates.map(n => groundOne(olam, meshes, n)).filter(Boolean); const door = alignDoor(candidates); if (door) report.push(door); return { candidates, report }; }
export function groundVillageNow(olam, made = [], final = true) { if (!isVillageWorld(olam, made)) return []; const { candidates, report } = settleVisuals(olam, made); if (final && !olam.__villageFinalCollidersBaked) { olam.__villageFinalCollidersBaked = true; olam.__villageFinalColliderBakedAt = Date.now(); report.push(...bakeFinalColliders(olam, candidates)); } console.info(final ? "B\"H | VILLAGE_FINAL_COLLIDERS_AFTER_ALL_SETTLE" : "B\"H | VILLAGE_VISUAL_SETTLE_NO_COLLIDERS", report); return report; }
export function scheduleVillageGrounding(olam, made = []) { if (!isVillageWorld(olam, made) || olam.__villageGroundingScheduled) return; olam.__villageGroundingScheduled = true; const raf = globalThis.requestAnimationFrame || (fn => setTimeout(fn, 32)); const afterFrames = (frames, fn) => frames <= 0 ? fn() : raf(() => afterFrames(frames - 1, fn)); afterFrames(2, () => setTimeout(() => groundVillageNow(olam, made, false), 180)); afterFrames(5, () => setTimeout(() => groundVillageNow(olam, made, false), 700)); afterFrames(8, () => setTimeout(() => groundVillageNow(olam, made, true), 1650)); }
