// B"H
const childProcess = require("child_process");
const path = require("path");
const fsp = require("fs/promises");
const crypto = require("crypto");
const { FOUR_MINUTES_MS } = require("../../lib/config.js");
const { shellArgs, fallbackShellArgs } = require("./shells.js");
const OUTPUT_DIR = ".awtsmoos/command-output";
const DEFAULT_MAX_OUTPUT_FILES = 200;
const DEFAULT_MAX_OUTPUT_AGE_MS = 12 * 60 * 60 * 1000;
function cleanRel(given, root) { let s = String(given || ".").replace(/\\/g, "/").replace(/^\/+/, ""); const rootName = path.basename(root).toLowerCase(); if (s.toLowerCase() === rootName) return "."; if (s.toLowerCase().startsWith(rootName + "/")) s = s.slice(rootName.length + 1); return s || "."; }
function safeCwd(config, given) { const root = path.resolve(config.root), raw = String(given || ".").trim(), cwd = path.isAbsolute(raw) ? path.resolve(raw) : path.resolve(root, cleanRel(raw, root)); if (!cwd.toLowerCase().startsWith(root.toLowerCase())) throw new Error("Command cwd outside root is blocked: " + cwd); return cwd; }
function trimOutput(text, max) { text = String(text || ""); return text.length <= max ? { text, truncated:false } : { text:text.slice(0, max), truncated:true }; }
function clamp(value, min, max, fallback) { return Number.isFinite(value) ? Math.max(min, Math.min(max, Math.floor(value))) : fallback; }
function outputRetention(config = {}) { const got = config.commandOutputRetention || config.outputRetention || {}; return { maxFiles:clamp(Number(got.maxFiles || process.env.AWTSMOOS_COMMAND_OUTPUT_MAX_FILES || DEFAULT_MAX_OUTPUT_FILES), 5, 5000, DEFAULT_MAX_OUTPUT_FILES), maxAgeMs:clamp(Number(got.maxAgeMs || process.env.AWTSMOOS_COMMAND_OUTPUT_MAX_AGE_MS || DEFAULT_MAX_OUTPUT_AGE_MS), 60_000, 7 * 24 * 60 * 60 * 1000, DEFAULT_MAX_OUTPUT_AGE_MS) }; }
async function spillOutput(config, kind, text) { const dir = path.join(config.root, OUTPUT_DIR); await fsp.mkdir(dir, { recursive:true }); await pruneCommandOutput(config); const name = `cmdout_${Date.now().toString(36)}_${crypto.randomBytes(4).toString("hex")}_${kind}.txt`; const rel = `${OUTPUT_DIR}/${name}`; await fsp.writeFile(path.join(config.root, rel), String(text || ""), "utf8"); const cleanup = await pruneCommandOutput(config); return { ref:rel, bytes:Buffer.byteLength(String(text || ""), "utf8"), retention:cleanup.summary }; }
async function pruneCommandOutput(config, overrides = {}) { const policy = { ...outputRetention(config), ...overrides }, dir = path.join(config.root, OUTPUT_DIR); await fsp.mkdir(dir, { recursive:true }); let entries = []; try { entries = await fsp.readdir(dir, { withFileTypes:true }); } catch {} const now = Date.now(), files = []; for (const entry of entries) { if (!entry.isFile() || !entry.name.startsWith("cmdout_") || !entry.name.endsWith(".txt")) continue; const full = path.join(dir, entry.name), stat = await fsp.stat(full).catch(() => null); files.push({ name:entry.name, full, mtimeMs:stat?.mtimeMs || 0 }); } files.sort((a, b) => b.mtimeMs - a.mtimeMs); let deleted = 0; for (let i = 0; i < files.length; i++) { if (i < policy.maxFiles && now - files[i].mtimeMs <= policy.maxAgeMs) continue; try { await fsp.unlink(files[i].full); deleted++; } catch {} } return { ok:true, action:"commandOutputGarbageCollect", policy, beforeFiles:files.length, deleted, afterFiles:Math.max(0, files.length - deleted), summary:{ maxFiles:policy.maxFiles, maxAgeMs:policy.maxAgeMs, deleted } }; }
function commandMaxTimeout() { const n = Number(process.env.AWTSMOOS_COMMAND_MAX_TIMEOUT_MS || 24 * 60 * 60 * 1000); return Number.isFinite(n) ? Math.max(FOUR_MINUTES_MS, Math.min(n, 7 * 24 * 60 * 60 * 1000)) : 24 * 60 * 60 * 1000; }
function boundedTimeout(value, fallback = FOUR_MINUTES_MS) { const n = Number(value || fallback || FOUR_MINUTES_MS); if (!Number.isFinite(n)) return FOUR_MINUTES_MS; return Math.max(1000, Math.min(Math.floor(n), commandMaxTimeout())); }
function execPicked(config, picked, command, cwd, timeoutMs, maxOutput) {
  return new Promise(resolve => {
    const startedAt = Date.now();
    childProcess.execFile(picked.file, picked.args, { cwd, timeout:timeoutMs, windowsHide:false, maxBuffer:maxOutput + 20000 }, async (err, stdout, stderr) => {
      const out = trimOutput(stdout, maxOutput), er = trimOutput(stderr, maxOutput), stdoutSpill = out.truncated ? await spillOutput(config, "stdout", stdout) : null, stderrSpill = er.truncated ? await spillOutput(config, "stderr", stderr) : null;
      const durationMs = Date.now() - startedAt, timedOut = err?.killed === true || err?.signal === "SIGTERM" || /timed out|timeout/i.test(err?.message || "");
      resolve({ err, response:{ ok:!err, action:"commandRun", command, shell:picked.shell, shellFile:picked.file, cwd, exitCode:err?.code ?? 0, signal:err?.signal || null, durationMs, timeoutMs, timedOut, stdout:out.text, stderr:er.text, stdoutRef:stdoutSpill?.ref || null, stderrRef:stderrSpill?.ref || null, stdoutBytes:stdoutSpill?.bytes || Buffer.byteLength(String(stdout || ""), "utf8"), stderrBytes:stderrSpill?.bytes || Buffer.byteLength(String(stderr || ""), "utf8"), outputRetention:stdoutSpill?.retention || stderrSpill?.retention || null, truncated:out.truncated || er.truncated, guidance:out.truncated || er.truncated ? "Read stdoutRef/stderrRef with the read action before retention expires." : timedOut ? "Command hit timeout. Raise timeoutMs or AWTSMOOS_COMMAND_MAX_TIMEOUT_MS for longer local work." : null, error:err ? err.message : null } });
    });
  });
}
async function runCommand(config, payload = {}) { if (!config.allowCommands || !config.tools.command || !config.command.enabled) return { ok:false, action:"commandRun", error:"commands_disabled", message:"Enable commands, then Save Config." }; const command = String(payload.command || "").trim(); if (!command) return { ok:false, action:"commandRun", error:"missing_command" }; const shell = payload.shell || config.command.defaultShell || (process.platform === "win32" ? "powershell" : "bash"), cwd = safeCwd(config, payload.cwd || "."), timeoutMs = boundedTimeout(payload.timeoutMs, config.command.timeoutMs), maxOutput = Math.max(1000, Math.min(Number(payload.maxChars || config.command.maxOutput || 120000), Number(process.env.AWTSMOOS_COMMAND_MAX_OUTPUT_CHARS || 5_000_000))); const first = await execPicked(config, shellArgs(shell, command), command, cwd, timeoutMs, maxOutput); if (first.err && first.err.code === "ENOENT") { const second = await execPicked(config, fallbackShellArgs(command), command, cwd, timeoutMs, maxOutput); second.response.firstShellError = first.response.error; return second.response; } return first.response; }
module.exports = { runCommand, safeCwd, boundedTimeout, pruneCommandOutput, outputRetention };
