// B"H
/**
 * @file PhysicsGroundRuntime.js
 * @purpose The Awtsmoos lets a jump arc breathe: ascent, crest, descent, then one
 * honest landing. Terrain law may catch a falling vessel only when the feet are
 * actually near the earth, never merely because downward velocity began.
 */
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import TerrainMath from "../../../../../dvarim/terrain/core/TerrainMath.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import { ensurePlayerCollisionBubble } from "../../../../../Olam/worlds/mitzvahWorld/collision/PlayerCollisionBubble.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import { clearAirTrajectory } from "./PhysicsAirRuntime.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
import { finite, numeric, steepSlopeY } from "./PhysicsNumbers.js?compact=true&v=tree-visible-perf-jump-20260708-bh1";
const groundRay = new THREE.Ray(), GROUND_GAP = .065, DEEP_OVERLAP = -.18, MAX_LANDING_SPEED = 34, MIN_JUMP_AIR_MS = 420;
export function jumpRising(player) { const vy = Number(player?.velocity?.y || 0); return vy > .05 || Boolean(player?.jumped && !player?.onFloor && vy > -.35); }
export function inAirborneLock(player) { return Date.now() < Number(player?.__jumpAirborneUntil || 0); }
function jumpTooFresh(player) { return Boolean(player?.jumped && Date.now() - Number(player.__jumpStartedAt || 0) < MIN_JUMP_AIR_MS); }
function realGround(hit) { return Boolean(hit && !hit.fallback && (hit.meshGroundAuthority || hit.source === "octree" || hit.source === "initial-raycast-grounding" || hit.lawFallback || hit.source === "terrain-law")); }
export function canAcceptGroundContact(player, hit, options = {}) { if (!hit?.normal || !player?.collider || !realGround(hit)) return false; if (hit.normal.y <= steepSlopeY()) return false; if (!options.allowCoyote && (inAirborneLock(player) || jumpRising(player) || jumpTooFresh(player))) return false; const radius = numeric(player.collider.radius, numeric(player.radius, .45)), gap = numeric(hit.distance, Infinity) - radius, vy = numeric(player.velocity?.y, 0); if (vy > .08 || vy < -MAX_LANDING_SPEED) return false; return gap <= GROUND_GAP && gap >= DEEP_OVERLAP; }
export function terrainFallbackY(player, x, z, fallback) { const law = player?.olam?.awtsmoosTerrainLaw; if (!law?.data) return fallback; const y = numeric(law.position?.y, 0) + TerrainMath.calculateHeightAt(x - numeric(law.position?.x, 0), z - numeric(law.position?.z, 0), law.data); return finite(y) ? y : fallback; }
function lawHit(player) { const law = player?.olam?.awtsmoosTerrainLaw, start = player?.collider?.start; if (!law?.data || !start) return false; const lx = start.x - numeric(law.position?.x, 0), lz = start.z - numeric(law.position?.z, 0), y = terrainFallbackY(player, start.x, start.z, NaN); if (!finite(y)) return false; const e = 1.25, hx1 = TerrainMath.calculateHeightAt(lx + e, lz, law.data), hx0 = TerrainMath.calculateHeightAt(lx - e, lz, law.data), hz1 = TerrainMath.calculateHeightAt(lx, lz + e, law.data), hz0 = TerrainMath.calculateHeightAt(lx, lz - e, law.data), normal = new THREE.Vector3(-(hx1 - hx0) / (e * 2), 1, -(hz1 - hz0) / (e * 2)).normalize(); return { distance:start.y - y, position:new THREE.Vector3(start.x, y, start.z), normal, object:{ name:"awtsmoosTerrainLawFallback" }, lawFallback:true, fallback:false, source:"terrain-law" }; }
export function bestGroundHit(player) { const start = player?.collider?.start; if (!start) return false; const bubble = ensurePlayerCollisionBubble(player?.olam); bubble?.updateFromPlayer?.(player); const radius = numeric(player?.collider?.radius, numeric(player?.radius, .45)), feetY = start.y - radius, mesh = bubble?.olam?.__awtsmoosGroundCollisionWorld?.groundAt?.(start.x, start.z, { fallback:feetY, radius:bubble.nearRadius, fallbackFn:(x, z, fallback) => terrainFallbackY(player, x, z, fallback) }); if (mesh && finite(mesh.y) && !mesh.fallback) return { distance:start.y - mesh.y, position:mesh.point || new THREE.Vector3(start.x, mesh.y, start.z), normal:mesh.normal || new THREE.Vector3(0, 1, 0), object:mesh.object || { name:mesh.mesh || "terrain" }, meshGroundAuthority:true, fallback:false, source:mesh.source || "mesh-ground" }; groundRay.origin.copy(start); groundRay.direction.set(0, -1, 0); const oct = player.olam?.worldOctree?.rayIntersect?.(groundRay); return oct || lawHit(player); }
export function clampToTerrainFloor(player, slack = .015) { if (jumpRising(player) || inAirborneLock(player) || jumpTooFresh(player)) return false; const bubble = ensurePlayerCollisionBubble(player?.olam), hit = bestGroundHit(player); if (!canAcceptGroundContact(player, hit)) return false; const grounded = bubble?.groundPlayer?.(player, { slack, fallbackFn:(x, z, fallback) => terrainFallbackY(player, x, z, fallback) }), start = player?.collider?.start, radius = numeric(player?.collider?.radius, numeric(player?.radius, .45)); if (!start || !finite(hit.position?.y)) return false; const target = hit.position.y + radius + slack, delta = target - start.y; if (!grounded && (!finite(delta) || Math.abs(delta) > .16)) return false; if (!grounded) player.collider.translate({ x:0, y:delta, z:0 }); player.onFloor = true; player.grounded = true; player.isOnGround = true; player.jumped = false; if (player.velocity) player.velocity.y = 0; clearAirTrajectory(player); player.__lastGroundedAt = Date.now(); player.__lastGroundClamp = { at:Date.now(), delta:grounded ? 0 : delta, groundY:hit.position.y, source:hit.object?.name || "ground" }; return true; }
