// B"H
/** @file ContinuousEventRouter.js @description Routes worker pulses and real 3D movie actions. */
import RenderTrace from "../../methods/canvas/RenderTrace.js";
import { rememberCanvasPayload } from "./CanvasMemory.js";
import { buildPlayerRuntimeProbe } from "./PlayerRuntimeProbe.js?v=real-3d-actions-20260707-bh1";
import { destroyWorld } from "./WorldDisposal.js?v=visible-root-binding-20260610-bh710";
import { resetAfterSpikeDeath, enableAfterSpikeReset } from "./SpikeResetActions.js?v=visible-root-binding-20260610-bh710";
import { runMitzvahProof } from "./MitzvahProofRuntime.js?v=combat-quest-story-20260705-bh1";
import { playMovie3DAction } from "./Movie3DActionRuntime.js?v=real-3d-actions-20260707-bh1";
const MOBILE_MOVE_FLAGS = Object.freeze(["FORWARD","BACKWARD","LEFT_STRIDE","RIGHT_STRIDE"]);
function routerTrace(olam,stage,payload={}){const at=Date.now(),active=Array.isArray(payload.active)?payload.active.length:0,cadence=active>0?900:2200;if(olam.__lastContinuousRouterTraceAt&&at-olam.__lastContinuousRouterTraceAt<cadence)return;olam.__lastContinuousRouterTraceAt=at;olam.__movementTrace||=[];olam.__movementTrace.push({at,stage,...payload});olam.__movementTrace=olam.__movementTrace.slice(-80);}
async function takeInCanvas(olam,payload){rememberCanvasPayload(payload);RenderTrace.speak("worker_route:takeInCanvas_received",{width:payload?.width,height:payload?.height,hasOlam:Boolean(olam),hasAyin:Boolean(olam?.ayin),hasCamera:Boolean(olam?.activeCamera||olam?.ayin?.camera)});olam.takeInCanvas(payload.canvas,payload.devicePixelRatio);if(typeof olam.setSize==="function")await olam.setSize(payload.width,payload.height);if(typeof olam.heesHawvoos==="function")olam.heesHawvoos();self.postMessage({type:"canvas_transferred",payload:{width:payload.width,height:payload.height,devicePixelRatio:payload.devicePixelRatio,rendererReady:Boolean(olam.renderer),hasCamera:Boolean(olam.activeCamera||olam.ayin?.camera),sceneChildren:olam.scene?.children?.length||0}});}
async function resize(olam,payload){if(typeof olam.setSize==="function")await olam.setSize(payload.width,payload.height);olam.ayshPeula("resize",payload);}
function applyMobileMove(olam,payload={}){olam.inputs||={};MOBILE_MOVE_FLAGS.forEach(flag=>{olam.inputs[flag]=payload[flag]===true;});olam.__lastMobileMove={at:Date.now(),...payload};const active=MOBILE_MOVE_FLAGS.filter(flag=>olam.inputs[flag]);routerTrace(olam,"mobileMove-applied-active-router",{active,source:payload.source||"unknown",seal:payload.seal||null});}
function postPlayerProbe(olam,payload={}){const probe=buildPlayerRuntimeProbe(olam);self.postMessage({type:"playerProbeResult",payload:{id:payload.id||null,...probe}});routerTrace(olam,"playerProbe-result",{id:payload.id||null,visualPass:probe.visualPass,capsulePass:probe.capsulePass,clip:probe.animation?.currentClip});}
function olamPeula(olam,payload){for(const p in payload)olam.ayshPeula(p,payload[p]);}
function awtsCode(olam,payload){try{const me={olam};eval(payload);}catch(e){console.error("B\"H - AWTS_CODE error:",e);}}
async function mitzvahProof(olam,payload){await runMitzvahProof(olam,payload||{});}
function movie3DAction(olam,payload){const report=playMovie3DAction(olam,payload||{});self.postMessage?.({type:"movie3DActionResult",payload:report});routerTrace(olam,"movie3DAction",report);}
const low=value=>String(value||"").toLowerCase();
function testFeatureText(object){const data=object?.userData||{};return low([object?.name,object?.type,data.kind,data.type,data.recipe,data.houseId,data.surfaceKey,data.materialKey,data.biomeKey].filter(Boolean).join(" "));}
function setTestVisible(object,visible,key){object.userData||={};const originalKey=`awtsmoosTestOriginalVisible:${key}`;if(object.userData[originalKey]==null)object.userData[originalKey]=object.visible!==false;object.visible=visible?object.userData[originalKey]!==false:false;}
function setTextureEnabled(material,enabled){if(!material)return false;material.userData||={};if(material.userData.awtsmoosTestOriginalMap===undefined)material.userData.awtsmoosTestOriginalMap=material.map||null;if(material.userData.awtsmoosTestOriginalNormalMap===undefined)material.userData.awtsmoosTestOriginalNormalMap=material.normalMap||null;material.map=enabled?material.userData.awtsmoosTestOriginalMap:null;material.normalMap=enabled?material.userData.awtsmoosTestOriginalNormalMap:null;material.needsUpdate=true;return true;}
function applyTestFeatureFlags(olam,payload={}){const flags={grassVisuals:payload.grassVisuals!==false,houseVisuals:payload.houseVisuals!==false,terrainTextures:payload.terrainTextures!==false,workerPlayerMixer:payload.workerPlayerMixer===true};globalThis.__AWTSMOOS_TEST_FEATURE_FLAGS__=flags;globalThis.__AWTSMOOS_ENABLE_WORKER_PLAYER_MIXER__=flags.workerPlayerMixer;const report={at:Date.now(),flags,affected:{grass:0,houses:0,textures:0},collisionUnaffected:true};olam?.scene?.traverse?.(object=>{const text=testFeatureText(object);if(/grass|flora|flower|meadow|safegrass/.test(text)){setTestVisible(object,flags.grassVisuals,"grass");report.affected.grass+=1;}if(/house|cottage|building|roof|doorway|bakery|rebbe|toolmaker|trainer/.test(text)&&!/collider|octree|collision/.test(text)){setTestVisible(object,flags.houseVisuals,"house");report.affected.houses+=1;}if(/terrain|ground|grass|safegrass|dirt|road|path/.test(text)){const materials=Array.isArray(object.material)?object.material:object.material?[object.material]:[];for(const material of materials)if(setTextureEnabled(material,flags.terrainTextures))report.affected.textures+=1;}});if(olam)olam.__AWTSMOOS_TEST_FEATURE_REPORT__=report;self.postMessage?.({type:"test_feature_flags_result",payload:report});}
const actionMap=Object.freeze({takeInCanvas,destroyWorld,resize,resetAfterSpikeDeath,enableAfterSpikeReset,mobileMove:applyMobileMove,playerProbe:postPlayerProbe,mitzvahProof,testFeatureFlags:applyTestFeatureFlags,movie3DAction,olamPeula,awtsCode,cameraDrag:(olam,payload)=>{if(olam.ayin?.rotateAroundTarget)olam.ayin.rotateAroundTarget(payload.dx,payload.dy);},keydown:(olam,payload)=>olam.ayshPeula("keydown",payload),keyup:(olam,payload)=>olam.ayshPeula("keyup",payload),mousedown:(olam,payload)=>{if(olam.yichud)olam.yichud.handleEvent(payload,true);olam.ayshPeula("mousedown",payload);},mouseup:(olam,payload)=>olam.ayshPeula("mouseup",payload),mousemove:(olam,payload)=>{if(olam.yichud)olam.yichud.handleEvent(payload,false);olam.ayshPeula("mousemove",payload);},wheel:(olam,payload)=>olam.ayshPeula("wheel",payload)});
function resolvePromiseEvent(key,payload,promiseMap){const resolvingEvents=["htmlCreated","htmlActioned","htmlDeleted","htmlActionsed","uiEvented","htmlGot"];if(!resolvingEvents.includes(key)||!payload?.id||!promiseMap.has(payload.id))return false;promiseMap.get(payload.id)(payload);promiseMap.delete(payload.id);return true;}
export class ContinuousEventRouter{static actionMap=actionMap;static async route(olam,key,payload,promiseMap){if(!olam&&key!=="vessel_ready")return;const action=this.actionMap[key];if(typeof action==="function")return void await action(olam,payload);if(resolvePromiseEvent(key,payload,promiseMap))return;if(olam?.ayshPeula)olam.ayshPeula(key,payload);}}
