// B"H
/**
 * @file AdvancedTreeOnly.js
 * @description
 * Chapter 1020: one gate for every visible tree in MitzvahWorld.
 * The Awtsmoos seals the forest to a single source: geelooy/libs heroTree.
 */
import * as THREE from "/games/scripts/build/three.module.js";
import { createHeroTree } from "/libs/awtsmoos3d/tree/heroTree.js?v=advanced-tree-only-20260614-bh1";
import TerrainMath from "../../../../../dvarim/terrain/core/TerrainMath.js";
const ROOT_FLAG = Object.freeze({ advancedGeelooyLibsTree: true, onlyApprovedTreeSource: true, treeSource: "/libs/awtsmoos3d/tree/heroTree.js", villageDecor: true, skipOctree: true, noOctree: true, skipRaycast: true });
const n = (v, f = 0) => Number.isFinite(Number(v)) ? Number(v) : f;
function terrainY(olam, x, z, fallback = 0) { const law = olam?.awtsmoosTerrainLaw; if (!law?.data) return fallback; return n(law.position?.y) + TerrainMath.calculateHeightAt(x - n(law.position?.x), z - n(law.position?.z), law.data); }
function roots(count = 11) { const g = new THREE.Group(); g.name = "advanced_tree_roots_from_single_tree_api"; const geo = new THREE.CylinderGeometry(.08, .2, 1, 8, 1), mat = new THREE.MeshLambertMaterial({ color: 0x4c2b16 }); for (let i = 0; i < count; i++) { const a = i / count * Math.PI * 2, m = new THREE.Mesh(geo, mat); m.name = "advanced_library_tree_surface_root"; m.position.set(Math.cos(a) * .75, .08, Math.sin(a) * .75); m.scale.set(.9, 2.1 + (i % 4) * .28, .9); m.rotation.set(Math.PI / 2, a, 0); Object.assign(m.userData, ROOT_FLAG); g.add(m); } return g; }
function profileOptions(options = {}, index = 0) { const kind = options.kind || options.species || "oak", ancient = options.age === "ancient" || options.ancient === true, pine = kind === "pine", apple = kind === "apple"; return { name: options.name || `advanced_tree_${kind}_${index}`, trunkHeight: n(options.trunkHeight, ancient ? 11 : apple ? 6 : pine ? 9 : 8), crownRadius: n(options.crownRadius, ancient ? 7 : apple ? 4.5 : pine ? 3.6 : 5), crownHeight: n(options.crownHeight, pine ? 6.4 : 4.2), limbCount: n(options.limbCount, ancient ? 56 : pine ? 38 : 44), leafCount: n(options.leafCount, ancient ? 980 : pine ? 680 : 780), barkColor: options.barkColor ?? (pine ? 0x4d321f : 0x684020), branchColor: options.branchColor ?? (pine ? 0x3f2a1a : 0x4d2b17), leafColor: options.leafColor ?? (pine ? 0x236f35 : apple ? 0x65a342 : 0x4e9b38), rotationY: n(options.rotationY, 0), scale: n(options.scale, ancient ? 1.12 : .92) }; }
export function buildAdvancedTree(olam, options = {}, index = 0) { const x = n(options.x ?? options.position?.x), z = n(options.z ?? options.position?.z), y = n(options.y ?? options.position?.y, terrainY(olam, x, z, n(options.groundY))); const wrap = new THREE.Group(); wrap.name = options.name || `ONLY_APPROVED_ADVANCED_TREE_${index}`; wrap.position.set(x, y + n(options.groundLift, .012), z); const hero = createHeroTree(profileOptions(options, index), { olam, renderer: olam?.renderer }); hero.name = `geelooy_libs_hero_tree_${index}`; wrap.add(hero); wrap.add(roots(n(options.rootCount, 13))); Object.assign(wrap.userData, ROOT_FLAG, { kind: options.kind || options.species || "oak", index }); wrap.traverse(child => Object.assign(child.userData ||= {}, ROOT_FLAG)); return wrap; }
export function markApprovedTree(root) { root?.traverse?.(child => Object.assign(child.userData ||= {}, ROOT_FLAG)); if (root?.userData) Object.assign(root.userData, ROOT_FLAG); return root; }
export function approvedTreeStats(root) { let total = 0, approved = 0; root?.traverse?.(o => { const name = String(o.name || "").toLowerCase(); const looksTree = name.includes("tree") || o.userData?.heroTree || o.userData?.advancedGeelooyLibsTree; if (looksTree) { total++; if (o.userData?.advancedGeelooyLibsTree || o.userData?.onlyApprovedTreeSource) approved++; } }); return { treeLikeObjects: total, approvedTreeObjects: approved, unapprovedTreeObjects: total - approved }; }
export default { buildAdvancedTree, markApprovedTree, approvedTreeStats };
