// B"H
/** @file RegionTreeRenderer.js @description Visible preset forest with mobile-safe count and no per-frame traversal. */
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { rand } from "./RegionRandom.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { sealRegionVisual } from "./RegionSeal.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { buildAdvancedTree, approvedTreeStats, registerTreeTrunkColliders } from "./AdvancedTreeOnly.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
const ANCHORS=Object.freeze([[18,28,"olive","mature"],[-34,42,"oak","mature"],[46,-18,"apple","mature"],[-62,-24,"oak","ancient"],[84,64,"pine","mature"],[118,86,"pine","ancient"],[-96,18,"apple","mature"],[22,96,"willow","mature"],[-128,72,"oak","ancient"],[146,26,"pine","mature"],[72,-72,"apple","mature"],[-42,-86,"olive","mature"]]);
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const isMobile=()=>globalThis.matchMedia?.("(pointer: coarse), (max-width: 820px)")?.matches||/Android|iPhone|iPad|Mobile/i.test(navigator.userAgent||"");
function proof(stage,fields={}){const p={stage,seal:"full-chain-cache-bust-20260708-bh10",...fields};globalThis.__AWTS_REGION_TREE_RENDERER_PROOF__ ||= [];globalThis.__AWTS_REGION_TREE_RENDERER_PROOF__.push(p);if(globalThis.__AWTS_REGION_TREE_RENDERER_PROOF__.length>32)globalThis.__AWTS_REGION_TREE_RENDERER_PROOF__.shift();if(globalThis.__AWTS_DEBUG_TREES__===true)console.info('B"H | REGION_TREE_RENDERER_PROOF',p);}
function reportTrees(r){return r?.instances&&Array.isArray(r.instances.trees)?r.instances.trees:[];}
function fallback(count){return Array.from({length:count},(_,i)=>{const a=i*2.399963,rad=34+Math.sqrt(rand(i,1))*185,k=["oak","pine","apple","willow","olive"][i%5];return{x:-25+Math.cos(a)*rad,z:32+Math.sin(a)*rad*.72,kind:k,age:i%9===0?"ancient":"mature",sourcePath:"RegionTreeRenderer/fallback"};});}
function specs(reportData){const anchored=ANCHORS.map((a,i)=>({x:a[0],z:a[1],kind:a[2],age:a[3],name:`starter_procedural_core_tree_${i}`,starterAnchor:true,sourcePath:"RegionTreeRenderer/anchors"}));const generated=reportTrees(reportData).map((t,i)=>({...t,sourcePath:t.sourcePath||`region-report-tree-${i}`}));return[...anchored,...(generated.length?generated:fallback(48))];}
function targetCount(){return isMobile()?14:28;}
function optionsFor(source={},index=0){const kind=source.kind||source.species||["oak","pine","apple","willow","olive"][index%5],ancient=source.age==="ancient",pine=kind==="pine",x=n(source.x??source.position?.x),z=n(source.z??source.position?.z);return{...source,name:source.name||`procedural_core_region_tree_${index}`,x,y:source.y??source.position?.y,z,kind,age:source.age||"mature",rotationY:n(source.rotationY,rand(index,9)*Math.PI*2),scale:ancient?(pine?1.12:1.08):pine?.88+rand(index,10)*.18:.76+rand(index,10)*.2,groundLift:.01,sourcePath:source.sourcePath||"RegionTreeRenderer/optionsFor"};}
function addTree(root,olam,source,index){const options=optionsFor(source,index),tree=buildAdvancedTree(olam,options,index);Object.assign(tree.userData||={}, {regionProceduralCoreTree:true,skipRaycast:true});tree.visible=true;tree.frustumCulled=true;root.add(tree);return tree;}
export function buildTreeRenderer(olam,reportData={}){const all=specs(reportData),count=targetCount(),root=new THREE.Group();root.name="living_region_procedural_core_tree_forest";root.visible=true;root.frustumCulled=false;for(let i=0;i<count;i++)addTree(root,olam,all[i%all.length],i);const registered=registerTreeTrunkColliders(root,olam),audit=approvedTreeStats(root);root.userData.colliderSources=[];root.userData.tick=null;root.userData.stats={trees:count,nearTrees:count,approvedProceduralCoreTrees:audit.approvedTreeObjects,drawCallsEstimate:count*3,mobileBudget:isMobile(),proceduralCoreForest:true,registeredTrunkColliders:registered.length,colliderSources:0};if(olam)olam.__livingRegionProceduralTreeProof={...root.userData.stats,audit,attached:true,rootName:root.name};proof("forest-created",{count,registered:registered.length,audit});return sealRegionVisual(root,{proceduralCoreForest:true,onlyApprovedTreeSource:true,manyTrees:true,bboxGroundedTrees:true,fullerTreeGenerator:true,treeWindTick:false});}
export default buildTreeRenderer;
