// B"H
/** @file RegionFlowerRenderer.js @description More flower heads through layered instancing and seasonal memory. */
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { makeInstancedLayer } from "./RegionInstancer.js?compact=true&v=awtsmoos-instancer-20260614-bh2";
import { samplePolyline, offsetPoint } from "./RegionPolyline.js?compact=true&v=awtsmoos-polyline-20260614-bh2";
import { rand } from "./RegionRandom.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { sealRegionVisual } from "./RegionSeal.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { budgetedQualityCount } from "./RegionQuality.js?compact=true&v=awtsmoos-quality-20260614-bh2";
const P=Object.freeze([0xffee88,0xd6a7ff,0xffffff,0xff9bd2,0x9be27a,0x7dd3fc,0xfbbf24,0xff7a7a,0xc084fc,0xfef08a]);
function reps(r){return r?.instances&&Array.isArray(r.instances.flowers)?r.instances.flowers:[];} function pts(roads){return Array.isArray(roads?.main?.points)?roads.main.points:[];} function road(roads){const path=samplePolyline(pts(roads),3.2),out=[];path.forEach((p,i)=>{out.push(offsetPoint(p,2+rand(i,1)*7));out.push(offsetPoint(p,-2-rand(i,2)*7));});return out;}
function meadow(i,ring=1){const a=i*2.399963,r=16+Math.sqrt(rand(i,11))*235*ring;return{x:Math.cos(a)*r+(rand(i,5)-.5)*22,z:Math.sin(a)*r*.68+(rand(i,6)-.5)*18};}
function flowerAt(b,i,scale=1,lift=.42){const s=(.08+rand(i,7)*.16)*scale;return{x:b.x+(rand(i,3)-.5)*6,z:b.z+(rand(i,4)-.5)*6,sx:s,sy:.045+rand(i,8)*.075,sz:s,yaw:rand(i,9)*6.28,lift:lift+rand(i,10)*.24,color:P[i%P.length]};}
function spec(s,i){return flowerAt({x:+s.x||0,z:+s.z||0},i,+s.scale||1,.42);} function buildLayer(olam,name,count,bases,offset,scale,lift,specs){return makeInstancedLayer({olam,name,geometry:'flower',material:'daisyPetal',count,build:i=>specs.length?spec(specs[(i+offset)%specs.length],i+offset):flowerAt(bases[(i+offset)%Math.max(1,bases.length)]||meadow(i+offset,scale),i+offset,scale,lift)});}
export function buildFlowerRenderer(olam,roads={},report={}){const root=new THREE.Group();root.name='living_region_many_head_wildflower_lod_fields'; const specs=reps(report),bases=[...road(roads),...Array.from({length:80},(_,i)=>meadow(i,1))]; const near=Math.min(1400,Math.max(900,budgetedQualityCount(olam,1200,'grassDistance',1400))),mid=1300,far=900; root.add(buildLayer(olam,'near_many_wildflower_heads',near,bases,0,1.1,.42,specs)); root.add(buildLayer(olam,'mid_tiny_wildflower_color_heads',mid,bases,2000,.72,.34,specs)); root.add(buildLayer(olam,'far_meadow_flower_sparkles',far,bases,5000,.45,.26,specs)); root.userData.stats={flowers:near+mid+far,near,mid,far,drawCalls:3,seasonalMemory:true,species:P.length,moreFlowerHeads:true,smartFlowerLOD:true,hyperrealWithoutGeometryDebt:true}; root.userData.worldMemory={spring:'dense bloom',summer:'gold lavender blue',rain:'brighter roadsides',drought:'seed heads and sparse petals'}; return sealRegionVisual(root,{groundedFlowers:true,seasonalMemory:true,hyperrealFlowers:true,moreFlowerHeads:true,smartLOD:true});}
