// B"H
/**
 * @file RegionWildlifeRenderer.js
 * @description
 * Chapter 1017: wildlife remains selectable after region sealing.
 */
import * as THREE from "/games/scripts/build/three.module.js";
import { groundY } from "./RegionGround.js";
import { rand } from "./RegionRandom.js";
import { sealRegionVisual } from "./RegionSeal.js";
import { advanceNeeds } from "../wildlife/AnimalNeedsModel.js";
import { buildAnimal } from "../wildlife/render/AnimalBodyForge.js?v=solid-body-fur-animals-20260614-bh1";
import { animateAnimal } from "../wildlife/render/AnimalAnimator.js?v=solid-body-fur-animals-20260614-bh1";
const COUNTS = { rabbit: 18, fox: 6, deer: 8, frog: 12, goat: 6, bird: 8 };
const TARGET_FLAGS = { wildlifeActor: true, realisticWildlife: true, selectableCombatTarget: true, skipRaycast: false, interactionLayer: "explicit-interaction" };
function animalsFromReport(report) { return report.wildlife?.animals?.length ? report.wildlife.animals : fallbackAnimals(); }
function fallbackAnimals() { const out = []; for (const [species, count] of Object.entries(COUNTS)) for (let i = 0; i < count; i++) out.push({ id: `${species}_${i}`, species, x: (rand(i, 1) - .5) * 320, z: (rand(i, 2) - .5) * 160, state: "wander", needs: {} }); return out; }
function makeRayProxy(root) { const box = new THREE.Box3().setFromObject(root), size = box.getSize(new THREE.Vector3()), center = box.getCenter(new THREE.Vector3()); const geo = new THREE.SphereGeometry(Math.max(.7, size.length() * .34), 12, 8); const mat = new THREE.MeshBasicMaterial({ color: 0xffff00, transparent: true, opacity: .001, depthWrite: false }); const proxy = new THREE.Mesh(geo, mat); proxy.name = "wildlife_mobile_tap_target_proxy"; proxy.position.copy(center.sub(root.position)); Object.assign(proxy.userData, TARGET_FLAGS, { awtsmoosRayProxy: true, combatTargetProxy: true }); root.add(proxy); root.userData.raycastMesh = proxy; }
function restoreRayFlags(root) { Object.assign(root.userData, TARGET_FLAGS); root.traverse(child => { if (child.userData?.combatTargetProxy || child.name === "solid_fur_textured_body_mesh") Object.assign(child.userData, TARGET_FLAGS); }); }
function actor(animal, i, olam) { const species = animal.species || "rabbit", root = buildAnimal(species, animal, olam); const x = animal.x ?? 0, z = animal.z ?? 0; root.position.set(x, groundY(olam, x, z) + .04, z); root.userData.motion = { ...animal, baseX: x, baseZ: z, phase: rand(i, 3) * 100, radius: animal.territory?.radius || 22, speed: animal.traits?.speed || root.userData.profile?.speed || .8, needs: { ...(animal.needs || {}) } }; makeRayProxy(root); restoreRayFlags(root); sealRegionVisual(root, TARGET_FLAGS); restoreRayFlags(root); return root; }
function nearest(root, species, from) { let best = null, d = Infinity; for (const c of root.children) { const m = c.userData.motion; if (!m || m.species !== species) continue; const n = c.position.distanceTo(from.position); if (n < d) { best = c; d = n; } } return { best, d }; }
function chooseState(root, animal, m, olam) { advanceNeeds(m.needs, .016); const player = olam.player || olam.chossid, pp = player?.mesh?.position; if (animal.userData.species === "fox") { const r = nearest(root, "rabbit", animal); return r.best && r.d < 42 ? { state: r.d < 2.4 ? "attack" : "hunt", target: r.best.position } : { state: "patrol" }; } if (animal.userData.species === "rabbit") { const f = nearest(root, "fox", animal); return f.best && f.d < 50 ? { state: "flee", target: f.best.position } : { state: m.needs.hunger > .55 ? "graze" : "hide" }; } if (animal.userData.species === "deer" && pp && animal.position.distanceTo(pp) < 20) return { state: "fleePlayer", target: pp }; if (animal.userData.species === "frog") return { state: "drink" }; if (animal.userData.species === "goat") return { state: "climb" }; if (animal.userData.species === "bird") return { state: "flock" }; return { state: "graze" }; }
function moveAnimal(c, m, decision, root, olam, t) { let x = m.baseX + Math.cos(t * m.speed + m.phase) * m.radius, z = m.baseZ + Math.sin(t * m.speed * .8 + m.phase) * m.radius * .45; if (decision.target && decision.state.startsWith("flee")) { x += (c.position.x - decision.target.x) * .035; z += (c.position.z - decision.target.z) * .035; } if (decision.target && ["hunt", "attack"].includes(decision.state)) { x += (decision.target.x - c.position.x) * .055; z += (decision.target.z - c.position.z) * .055; } const bounce = ["rabbit", "frog", "bird"].includes(m.species) ? Math.abs(Math.sin(t * 7 + m.phase)) * .14 : Math.abs(Math.sin(t * 2 + m.phase)) * .04; c.position.set(x, groundY(olam, x, z) + .04 + bounce + (m.species === "bird" ? 5 + Math.sin(t + m.phase) * 2 : 0), z); c.rotation.y = Math.atan2(z - m.baseZ, x - m.baseX) - Math.PI / 2; }
function tickRoot(root, olam, dt = 1 / 60) { root.userData.time = (root.userData.time || 0) + Math.min(.08, Math.max(.001, Number(dt) || 1 / 60)); const t = root.userData.time; for (const c of root.children) { const m = c.userData.motion; if (!m) continue; const decision = chooseState(root, c, m, olam); m.state = decision.state; moveAnimal(c, m, decision, root, olam, t); animateAnimal(c, dt, m.state); c.userData.state = m.state; } root.userData.stats = summarize(root); }
function summarize(root) { const states = {}; for (const c of root.children) states[c.userData.state || c.userData.motion?.state || "unknown"] = (states[c.userData.state || c.userData.motion?.state || "unknown"] || 0) + 1; return { wildlife: root.children.length, states, furTextured: true, solidAnimalBodies: true, selectableCombatTargets: true }; }
export function buildWildlifeRenderer(olam, report = {}) { const root = new THREE.Group(); root.name = "living_region_realistic_solid_fur_selectable_wildlife_runtime"; animalsFromReport(report).forEach((a, i) => root.add(actor(a, i, olam))); root.userData.tick = dt => tickRoot(root, olam, dt); root.userData.stats = summarize(root); return sealRegionVisual(root, { realisticWildlife: true, solidAnimalBodies: true, skipRaycast: true }); }
export function installWildlifeTicker(olam, root) { if (!olam || !root?.userData?.tick || olam.__livingRegionWildlifeTicker) return; const ticker = { name: "living_region_wildlife_ticker", type: "livingRegionTicker", isReady: true, heesHawveh: true, heesHawvoos: dt => root.userData.tick(dt) }; olam.__livingRegionWildlifeTicker = ticker; olam.__livingRegionWildlifeRoot = root; if (Array.isArray(olam.nivrayim) && !olam.nivrayim.includes(ticker)) olam.nivrayim.push(ticker); }
