// B"H
/** Scheduler-driven NPC slices without per-frame visual LOD flicker. */
import { groundY } from "./RegionGround.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { rand } from "./RegionRandom.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { getWorldInterestScheduler } from "../../runtime/WorldInterestScheduler.js?compact=true&v=world-interest-20260621-bh1";
import { rebuildNpcSpatialHash } from "../../../../../systems/npc/NpcSpatialHash.js?compact=true&v=world-interest-20260621-bh1";
import { collectNpcLodDiagnostics } from "../../../../../systems/npc/NpcLodDiagnostics.js?compact=true&v=deferred-npc-glb-20260705-bh1";
import { installNpcLodRuntime } from "../../../../../systems/npc/NpcLodRuntime.js?compact=true&v=deferred-npc-glb-20260705-bh1";
const NPC_TYPES=new Set(["interactiveNpc","customNpc","medabeir"]);
const isNpc=e=>e&&NPC_TYPES.has(e.type);
const posOf=e=>e?.mesh?.position||null;
const budgetOf=()=>globalThis?.__AWTSMOOS_PERFORMANCE_MODE__?.budget||{};
const livePlayerPosition=olam=>(olam?.player||olam?.chossid)?.mesh?.position||null;
function phaseAt(time){const d=(time%96)/96;return d<.25?"morning":d<.56?"noon":d<.78?"evening":"night";}
function face(mesh,x,z){const dx=x-mesh.position.x,dz=z-mesh.position.z;if(Math.hypot(dx,dz)>.001)mesh.rotation.y=Math.atan2(dx,dz);}
function sliceSize(){const raw=Number(budgetOf().npcSocialSlice);return Number.isFinite(raw)?Math.max(2,Math.min(12,Math.floor(raw))):7;}
function schedulerFor(olam){const b=budgetOf();return getWorldInterestScheduler(olam,{near:b.npcDistance||48,mid:(b.npcDistance||48)*1.8,far:(b.treeDistance||120)*2.2,budget:{near:24,mid:9,far:3,sleep:1,npc:10,social:4}});}
function setMotion(npc,role){if(npc.motionRole===role&&npc.__isWalking===(role==="walk"))return false;npc.__isWalking=role==="walk";npc.motionRole=role;npc.userData||={};npc.userData.motionRole=role;npc.playNpcMotion?.(role);if(npc.mesh?.userData)npc.mesh.userData.motionRole=role;return true;}
function sealVisible(npc){npc.mesh?.traverse?.(child=>{if(child?.isObject3D&&!child.userData?.awtsmoosRayProxy&&!child.userData?.isPlayerFallback)child.visible=true;});if(npc.mesh)npc.mesh.visible=true;}
function seedNpc(npc,index,olam,schedule={}){const p=posOf(npc);if(!p||npc.__livingRegionNpcRuntime)return;const home=schedule.home||{x:p.x,z:p.z};npc.__livingRegionNpcRuntime={schedule,homeX:home.x,homeZ:home.z,phase:rand(index,40)*99,speed:schedule.speed||.78,activePhase:"morning",destination:{x:home.x,z:home.z},wait:rand(index,90)*4,waypoint:0,lastGround:0};npc.heesHawveh=true;npc.isReady=true;p.y=groundY(olam,p.x,p.z)+(npc.groundLift||.02);setMotion(npc,"idle");sealVisible(npc);}
function chooseDestination(m,phase){const s=m.schedule?.phases?.[phase]||{x:m.homeX,z:m.homeZ};m.waypoint++;const a=rand(m.waypoint,m.phase)*Math.PI*2,r=1.2+rand(m.phase,m.waypoint)*3.8;m.destination={x:(s.x??m.homeX)+Math.cos(a)*r,z:(s.z??m.homeZ)+Math.sin(a)*r};m.wait=1.4+rand(m.waypoint,71)*4.2;}
function updateNpc(npc,olam,time,dt,level){const mesh=npc.mesh,m=npc.__livingRegionNpcRuntime;if(!mesh||!m)return false;sealVisible(npc);const pp=livePlayerPosition(olam);if(pp&&mesh.position.distanceTo(pp)<(npc.talkDistance||8)){face(mesh,pp.x,pp.z);setMotion(npc,"idle");return true;}if(level==="frozen")return false;const phase=phaseAt(time+m.phase*.02);if(phase!==m.activePhase){m.activePhase=phase;chooseDestination(m,phase);}const dx=m.destination.x-mesh.position.x,dz=m.destination.z-mesh.position.z,distance=Math.hypot(dx,dz);if(distance<.2){m.wait-=dt;setMotion(npc,"idle");if(m.wait<=0)chooseDestination(m,phase);}else{const slow=level==="low"?.35:level==="medium"?.65:1,step=Math.min(distance,dt*m.speed*slow);mesh.position.x+=dx/distance*step;mesh.position.z+=dz/distance*step;face(mesh,m.destination.x,m.destination.z);setMotion(npc,"walk");}if(time-m.lastGround>(level==="full"?.3:1.2)){mesh.position.y=groundY(olam,mesh.position.x,mesh.position.z)+(npc.groundLift||.02);m.lastGround=time;}return true;}
function schedulesFromReport(report){return Array.isArray(report?.npcSchedules?.schedules)?report.npcSchedules.schedules:[];}
function nextNpcSlice(ticker,npcs){const count=Math.min(sliceSize(),npcs.length),out=[];for(let i=0;i<count;i++)out.push(npcs[(ticker.cursor+i)%npcs.length]);ticker.cursor=(ticker.cursor+count)%Math.max(1,npcs.length);return out;}
export function installRegionNpcRuntime(olam,report={}){if(!olam||olam.__livingRegionNpcTicker)return null;const npcs=(olam.nivrayim||[]).filter(isNpc),schedules=schedulesFromReport(report);npcs.forEach((npc,i)=>seedNpc(npc,i,olam,schedules[i%Math.max(1,schedules.length)]));rebuildNpcSpatialHash(olam);installNpcLodRuntime(olam);const ticker={name:"living_region_npc_schedule_ticker",type:"livingRegionTicker",isReady:true,heesHawveh:true,time:0,acc:0,gridAcc:0,cursor:0,stats:{checks:0,allowed:0,updated:0,slices:0,gridRebuilds:1},heesHawvoos(dt=1/60){const d0=Math.min(.08,Number(dt)||1/60);this.acc+=d0;this.gridAcc+=d0;if(this.gridAcc>1.4){rebuildNpcSpatialHash(olam);this.gridAcc=0;this.stats.gridRebuilds++;}if(this.acc<.2||!npcs.length)return;const d=Math.min(.3,this.acc);this.acc=0;this.time+=d;this.stats.slices++;const scheduler=schedulerFor(olam);for(const npc of nextNpcSlice(this,npcs)){this.stats.checks++;if(!scheduler.allow(npc,olam,"npc"))continue;this.stats.allowed++;if(updateNpc(npc,olam,this.time,d,scheduler.animationLevel(npc,olam)))this.stats.updated++;}olam.__livingRegionNpcRuntimeStats={...olam.__livingRegionNpcRuntimeStats,scheduler:scheduler.report(),ticker:this.stats,lod:collectNpcLodDiagnostics(olam),lodFlickerDisabled:true};}};olam.__livingRegionNpcTicker=ticker;olam.__livingRegionNpcRuntimeStats={npcs:npcs.length,schedules:schedules.length,animationDriven:true,sliced:true,schedulerDriven:true,spatialHash:true,sliceSize:sliceSize(),lodFlickerDisabled:true};if(Array.isArray(olam.nivrayim))olam.nivrayim.push(ticker);return ticker;}
