// B"H
/** Wildlife actors: selectable while alive, lootable after death, grounded always. */
import { ensureWildlifeCombat } from "../../../../../systems/creatures/WildlifeCombatAdapter.js";
import { makeLootableCorpse, lootPayload } from "../../../../../systems/loot/LootRuntime.js";
import { groundY } from "./RegionGround.js";
import { sealRegionVisual } from "./RegionSeal.js";
import { FLAGS, clearSpawn, countMeshes, radius, safe, speed } from "./RegionWildlifeData.js?v=perf-tight-collision-20260703-bh5";
import { buildStableAnimal } from "./RegionStableAnimalShape.js?v=perf-tight-collision-20260703-bh4";
function registerInteractable(olam, root) { if (!olam || !root) return; olam.interactableNivrayim ||= []; if (!olam.interactableNivrayim.includes(root)) olam.interactableNivrayim.push(root); }
function openLoot(root) { const olam = root.__awtsmoosOlam, id = root.userData?.lootableCorpseId || root.lootableCorpseId; if (!id) return false; globalThis.__MITZVAH_OPEN_LOOT__?.(id); olam?.ayshPeula?.("ui event", "loot", lootPayload(olam, id)); return true; }
function actorAction(root, peula) { const action = String(peula?.action || peula || ""); if (/mouseEnter|hover/i.test(action)) { root.userData.hovered = true; return true; } if (/mouseLeave/i.test(action)) { root.userData.hovered = false; return true; } if (root.userData?.dead || root.userData?.lootable) return /accepted interaction|click|pointerdown|interact/.test(action) ? openLoot(root) : false; root.__awtsmoosOlam?.combatManager?.selectTarget?.(root); return true; }
function installActorActions(root) { root.ayshPeula = peula => actorAction(root, peula); root.interact = () => actorAction(root, { action:"accepted interaction" }); root.userData.onInteract = () => actorAction(root, { action:"accepted interaction" }); }
function takeDamageFactory(root) { return (amount = 0) => { const health = root.userData.health; if (health.dead) return 0; health.hitsTaken += 1; health.current = Math.max(0, Number(health.current || 0) - Math.max(1, Number(amount) || 1)); health.dead = health.current <= 0; root.userData.healthPct = health.current / Math.max(1, health.max || 1); root.traverse?.(child => { if (child.material?.emissive) child.material.emissive.setHex(0x664400); }); setTimeout(() => root.traverse?.(child => child.material?.emissive?.setHex?.(0x000000)), 90); if (health.dead) markCorpse(root); return amount; }; }
function markCorpse(root) { root.userData.dead = true; root.userData.lootable = true; root.userData.selectableCombatTarget = false; root.userData.interactable = true; root.userData.interactionLabel = "Loot carcass"; root.rotation.z = Math.PI / 2; root.position.y += 0.08; root.scale.multiplyScalar(0.92); root.traverse?.(child => { Object.assign(child.userData ||= {}, { selectableCombatTarget:false, deadWildlifeCorpse:true, interactable:true, skipRaycast:false }); if (child.material) { child.material.transparent = false; child.material.opacity = 1; } }); if (!root.__lootCorpseCreated) { const corpse = makeLootableCorpse(root.__awtsmoosOlam, root, { reason:"wildlife-corpse", position:root.position.clone?.() || root.position }); root.__lootCorpseCreated = true; root.userData.lootableCorpseId = corpse?.corpseId || root.userData.lootableCorpseId; root.lootableCorpseId = root.userData.lootableCorpseId; } installActorActions(root); registerInteractable(root.__awtsmoosOlam, root); }
function restoreChildOwners(root) { root.traverse?.(child => { child.nivraAwtsmoos = root; Object.assign(child.userData ||= {}, { wildlifeActor:true, selectableCombatTarget:!root.userData?.dead, combatTargetRoot:root, skipOctree:true, noOctree:true, skipRaycast:false }); }); }
export function restoreFlags(root) { const meshes = countMeshes(root); Object.assign(root.userData, FLAGS, { stableNormalAnimal:true, renderMeshCount:meshes, singleMeshVerified:false, visualRepairMode:true, interactionLayer:"explicit-interaction" }); root.nivraAwtsmoos = root; root.takeDamage ||= takeDamageFactory(root); installActorActions(root); restoreChildOwners(root); }
export function makeActor(animal, index, olam, backend) { const species = animal.species || "rabbit", root = buildStableAnimal(species, animal, backend), point = clearSpawn(olam, safe(animal.x), safe(animal.z), index), lift = root.userData?.profile?.groundLift || 0.18; root.position.set(point.x, groundY(olam, point.x, point.z) + lift, point.z); root.userData.motion = { id:animal.id, species, homeX:point.x, homeZ:point.z, phase:index * 0.17, seed:index * 17 + species.length, radius:radius(animal), speed:speed(animal, root), vx:0, vz:0, destX:point.x, destZ:point.z, waypoint:0, wait:0.25, attackCooldown:0, animTime:0, wingBeat:species === "bird" ? 6 : 0, altitude:species === "bird" ? 2.4 : 0, groundLift:lift }; root.userData.fullGameplayAnimal = true; root.userData.detailedNearAnimal = false; root.__awtsmoosOlam = olam; restoreFlags(root); ensureWildlifeCombat(root, olam); sealRegionVisual(root, { ...FLAGS, skipRaycast:false, skipOctree:true, noOctree:true }); restoreFlags(root); return root; }
