// B"H
/** @file CottageDoorSystem.js @description Hinged cottage door mesh, lock state, open angle, and collider descriptor. */
import * as THREE from "/games/scripts/build/three.module.js";
import { COTTAGE_BRICK_PALETTE as P } from "./CottageBrickPalette.js";
import { defaultDoorState } from "./door/DoorStateIndex.js?v=door-state-index-20260615-bh2";
function material(color) { return new THREE.MeshLambertMaterial({ color, transparent:false, opacity:1, depthWrite:true, depthTest:true }); }
function part(name, size, pos, color, data = {}) { const mesh = new THREE.Mesh(new THREE.BoxGeometry(...size), material(color)); mesh.name = name; mesh.position.set(...pos); Object.assign(mesh.userData ||= {}, data, { cottageDoorPart:true, opacitySealed:true }); return mesh; }
export function buildCottageDoor(house = {}, spec = {}) { const state = defaultDoorState(house), root = new THREE.Group(), width = spec.doorWidth || 1.28, height = spec.doorHeight || 2.15, depth = .16, z = (spec.depth || house.sz || 5.4) / 2 + .13, hingeX = state.hinge === "left" ? -width/2 : width/2; root.name = `cottage_door_system_${house.id}`; root.position.set(hingeX,0,z); Object.assign(root.userData ||= {}, { cottageDoorSystem:true, doorHingePivot:true, houseId:house.id, doorState:state, colliderPosition:[0,height/2,z], colliderSize:[width,height,.24] }); const panelX = state.hinge === "left" ? width/2 : -width/2; const panel = part(`${state.id}_panel`, [width,height,depth], [panelX,height/2,0], P.door.color, { doorPanel:true, doorId:state.id, closedCollider:true }); const trim = part(`${state.id}_trim`, [width+.2,height+.18,.2], [panelX,height/2,0], P.door.trim, { doorTrim:true, doorId:state.id }); const knobX = panelX + (state.hinge === "left" ? width*.32 : -width*.32); const knob = new THREE.Mesh(new THREE.SphereGeometry(.065, 10, 8), material(P.door.metal)); knob.name = `${state.id}_knob`; knob.position.set(knobX, height*.52, depth*.62); Object.assign(knob.userData ||= {}, { cottageDoorPart:true, doorKnob:true, doorId:state.id, opacitySealed:true }); root.add(trim, panel, knob); const collider = { id:state.id, category:"closed-door", owner:house.id, position:[0,height/2,z], size:[width,height,.24], yaw:0, door:true, open:false, locked:state.locked, hinge:state.hinge, visibleTwin:state.id }; root.userData.colliderSources = [collider]; return { root, state, collider }; }
export default buildCottageDoor;
