// B"H
/** @file CottageBrickBuilder.js @description Builds visible staggered cottage brick walls, beams, roof, chimney, windows, and collider records. */
import * as THREE from "/games/scripts/build/three.module.js";
import { COTTAGE_BRICK_PALETTE as P } from "./CottageBrickPalette.js";
function mat(color) { return new THREE.MeshLambertMaterial({ color, transparent:false, opacity:1, depthWrite:true, depthTest:true }); }
function box(name, size, pos, color, data = {}) { const m = new THREE.Mesh(new THREE.BoxGeometry(...size), mat(color)); m.name = name; m.position.set(...pos); m.castShadow = false; m.receiveShadow = true; Object.assign(m.userData ||= {}, data, { cottageVisual:true, opacitySealed:true }); return m; }
function brickColor(row, col) { return (row + col) % 3 === 0 ? P.wall.alt : P.wall.color; }
function addWall(group, house, side, spec, colliders) { const { width, depth, height, brick } = spec, rows = Math.ceil(height / brick[1]); const front = side === "front", back = side === "back", left = side === "left", right = side === "right"; const length = front || back ? width : depth, z = front ? depth/2 : back ? -depth/2 : 0, x = right ? width/2 : left ? -width/2 : 0; const yaw = left || right ? Math.PI/2 : 0, doorHalf = front ? spec.doorWidth/2 : 0; for (let r=0;r<rows;r++) { const y = r*brick[1] + brick[1]/2; const cols = Math.ceil(length / brick[0]); for (let c=0;c<cols;c++) { const offset = r % 2 ? brick[0]/2 : 0, along = -length/2 + c*brick[0] + offset; if (front && Math.abs(along) < doorHalf && y < spec.doorHeight) continue; const bx = left || right ? x : along, bz = left || right ? along : z; const b = box(`cottage_${house.id}_${side}_brick_${r}_${c}`, [brick[0]*.94, brick[1]*.92, brick[2]], [bx,y,bz], brickColor(r,c), { cottageBrick:true, houseId:house.id, side }); b.rotation.y = yaw; group.add(b); } } colliders.push({ id:`${house.id}_${side}_wall`, category:"cottage-wall", owner:house.id, position:[x,height/2,z], size:front||back ? [width,height,.32] : [.32,height,depth], yaw, doorGap:front ? { width:spec.doorWidth, height:spec.doorHeight } : null }); }
function addBeams(group, house, spec) { const w=spec.width,d=spec.depth,h=spec.height; [[0,h+.08,d/2],[0,h+.08,-d/2],[w/2,h+.08,0],[-w/2,h+.08,0]].forEach((p,i)=>{ const s=i<2?[w+.35,.18,.22]:[.22,.18,d+.35]; group.add(box(`cottage_${house.id}_beam_${i}`, s, p, P.beam.color, { cottageBeam:true, houseId:house.id })); }); }
function addRoof(group, house, spec) { const w=spec.width+.8,d=spec.depth+.9,h=spec.height+.45; for (const side of [-1,1]) { const r = box(`cottage_${house.id}_roof_${side}`, [w*.58,.18,d], [side*w*.17,h,d*.02], P.roof.color, { cottageRoof:true, houseId:house.id, visualOnly:true }); r.rotation.z = side*.58; group.add(r); } group.add(box(`cottage_${house.id}_ridge_beam`, [.22,.22,d+.18], [0,h+.28,0], P.beam.color, { cottageRoof:true, houseId:house.id })); group.add(box(`cottage_${house.id}_chimney`, [.42,.9,.42], [w*.2,h+.65,-d*.18], P.foundation.color, { cottageChimney:true, houseId:house.id })); }
function addWindows(group, house, spec) { const y=spec.height*.58, z=spec.depth/2+.11; for (const x of [-spec.width*.28, spec.width*.28]) { group.add(box(`cottage_${house.id}_window_frame_${x}`, [.62,.52,.08], [x,y,z], P.window.frame, { cottageWindow:true, houseId:house.id })); group.add(box(`cottage_${house.id}_window_glass_${x}`, [.44,.34,.085], [x,y,z+.01], P.window.glass, { cottageWindowGlass:true, houseId:house.id, visualOnly:true })); group.add(box(`cottage_${house.id}_window_sill_${x}`, [.7,.08,.16], [x,y-.31,z+.02], P.window.sill, { cottageWindow:true, houseId:house.id })); } }
export function cottageSpec(house = {}) { return { width:house.sx || 6.2, depth:house.sz || 5.4, height:house.sy || 3.2, brick:P.wall.size, doorWidth:house.door?.width || 1.28, doorHeight:house.door?.height || 2.15 }; }
export function buildCottageBricks(house = {}) { const group = new THREE.Group(), spec = cottageSpec(house), colliders = []; group.name = `cottage_brick_system_${house.id}`; Object.assign(group.userData ||= {}, { cottageBrickSystem:true, houseId:house.id, colliderSources:colliders }); ["front","back","left","right"].forEach(side => addWall(group, house, side, spec, colliders)); addBeams(group, house, spec); addRoof(group, house, spec); addWindows(group, house, spec); return { group, colliders, spec }; }
export default buildCottageBricks;
