// B"H
/** @file CottageBrickBuilder.js @description Builds visible staggered cottage brick walls, beams, roof, chimney, windows, and collider records. */
import * as THREE from "/games/scripts/build/three.module.js";
import { COTTAGE_BRICK_PALETTE as P } from "./CottageBrickPalette.js";
import { materialWithTexture } from "../../materials/ProceduralTextureKit.js?v=intense-dirt-grain-20260615-bh904";
function mat(color) { return new THREE.MeshLambertMaterial({ color, transparent:false, opacity:1, depthWrite:true, depthTest:true }); }
const WALL_MATERIALS = new Map();
function wallMat() { if (!WALL_MATERIALS.has("brick")) WALL_MATERIALS.set("brick", materialWithTexture("brick", { size:384 })); return WALL_MATERIALS.get("brick"); }
function meshMaterial(color) { return color && color.isMaterial ? color : mat(color); }
function box(name, size, pos, color, data = {}) { const m = new THREE.Mesh(new THREE.BoxGeometry(...size), meshMaterial(color)); m.name = name; m.position.set(...pos); m.castShadow = false; m.receiveShadow = true; Object.assign(m.userData ||= {}, data, { cottageVisual:true, opacitySealed:true }); return m; }
function addWallPiece(group, house, side, name, size, pos, yaw = 0) { const piece = box(`cottage_${house.id}_${side}_${name}`, size, pos, wallMat(), { cottageWallSection:true, houseId:house.id, side, texturedBrickWall:true }); piece.rotation.y = yaw; group.add(piece); return piece; }
function addWall(group, house, side, spec, colliders) { const { width, depth, height, brick } = spec; const front = side === "front", back = side === "back", left = side === "left", right = side === "right"; const z = front ? depth/2 : back ? -depth/2 : 0, x = right ? width/2 : left ? -width/2 : 0; const yaw = left || right ? Math.PI/2 : 0, thick = brick[2]; if (front) { const sideW = Math.max(.2, (width - spec.doorWidth) / 2), sideX = spec.doorWidth / 2 + sideW / 2; addWallPiece(group, house, side, "left_door_jamb", [sideW, spec.doorHeight, thick], [-sideX, spec.doorHeight/2, z], yaw); addWallPiece(group, house, side, "right_door_jamb", [sideW, spec.doorHeight, thick], [sideX, spec.doorHeight/2, z], yaw); addWallPiece(group, house, side, "lintel_wall", [width, Math.max(.2, height - spec.doorHeight), thick], [0, spec.doorHeight + Math.max(.2, height - spec.doorHeight)/2, z], yaw); } else { addWallPiece(group, house, side, "single_textured_wall", [left||right ? depth : width, height, thick], [x, height/2, z], yaw); } colliders.push({ id:`${house.id}_${side}_wall`, category:"cottage-wall", owner:house.id, position:[x,height/2,z], size:front||back ? [width,height,.32] : [.32,height,depth], yaw, doorGap:front ? { width:spec.doorWidth, height:spec.doorHeight } : null }); }
function addBeams(group, house, spec) { const w=spec.width,d=spec.depth,h=spec.height; [[0,h+.08,d/2],[0,h+.08,-d/2],[w/2,h+.08,0],[-w/2,h+.08,0]].forEach((p,i)=>{ const s=i<2?[w+.35,.18,.22]:[.22,.18,d+.35]; group.add(box(`cottage_${house.id}_beam_${i}`, s, p, P.beam.color, { cottageBeam:true, houseId:house.id })); }); }
function addRoof(group, house, spec) { group.userData.roofHandledByCottageRoofBuilder = true; }
function addWindows(group, house, spec) { const y=spec.height*.58, z=spec.depth/2+.11; for (const x of [-spec.width*.28, spec.width*.28]) { group.add(box(`cottage_${house.id}_window_frame_${x}`, [.62,.52,.08], [x,y,z], P.window.frame, { cottageWindow:true, houseId:house.id })); group.add(box(`cottage_${house.id}_window_glass_${x}`, [.44,.34,.085], [x,y,z+.01], P.window.glass, { cottageWindowGlass:true, houseId:house.id, visualOnly:true })); group.add(box(`cottage_${house.id}_window_sill_${x}`, [.7,.08,.16], [x,y-.31,z+.02], P.window.sill, { cottageWindow:true, houseId:house.id })); } }
export function cottageSpec(house = {}) { return { width:house.sx || 6.2, depth:house.sz || 5.4, height:house.sy || 3.2, brick:P.wall.size, doorWidth:house.door?.width || 1.28, doorHeight:house.door?.height || 2.15 }; }
export function buildCottageBricks(house = {}) { const group = new THREE.Group(), spec = cottageSpec(house), colliders = []; group.name = `cottage_brick_system_${house.id}`; Object.assign(group.userData ||= {}, { cottageBrickSystem:true, houseId:house.id, colliderSources:colliders }); ["front","back","left","right"].forEach(side => addWall(group, house, side, spec, colliders)); addBeams(group, house, spec); addRoof(group, house, spec); addWindows(group, house, spec); return { group, colliders, spec }; }
export default buildCottageBricks;
