// B"H
/** @file CottageInteriorBuilder.js @description Builds socketed visible interiors using split semantic prop modules. */
import * as THREE from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
import { COTTAGE_BRICK_PALETTE as P } from "./CottageBrickPalette.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { interiorSockets } from "./interior/InteriorSocketPlanner.js?compact=true&v=cottage-interior-sockets-20260615-bh3";
import { buildInteriorProp } from "./interior/InteriorPropBuilder.js?compact=true&v=cottage-interior-props-20260615-bh3";
import { npcSocketForHouse } from "./interior/InteriorNpcSockets.js?compact=true&v=cottage-interior-npc-sockets-20260615-bh3";
function mat(color) { return new THREE.MeshLambertMaterial({ color, transparent:false, opacity:1, depthWrite:true, depthTest:true }); }
function box(name, size, pos, color, data = {}) { const m = new THREE.Mesh(new THREE.BoxGeometry(...size), mat(color)); m.name = name; m.position.set(...pos); Object.assign(m.userData ||= {}, data, { cottageInterior:true, opacitySealed:true, skipOctree:true, noOctree:true }); return m; }
function defaultProps(house = {}) { const profession = house.profession || "home"; const props = [{ kind:"bed", socket:"bed" }, { kind:"table", socket:"table" }, { kind:"lamp", socket:"lamp" }, { kind:"chest", socket:"storage" }, { kind:"shelf", socket:"storage" }, { kind:"hearth", socket:"hearth" }]; if (profession === "blacksmith") props.push({ kind:"anvil", socket:"profession" }); if (profession === "baker") props.push({ kind:"oven", socket:"hearth" }); if (profession === "scribe") props.push({ kind:"desk", socket:"profession" }); if (profession === "healer") props.push({ kind:"herb_rack", socket:"profession" }); if (profession === "tailor") props.push({ kind:"loom", socket:"profession" }); return props; }
export function buildCottageInterior(house = {}, spec = {}) { const group = new THREE.Group(); group.name = `cottage_interior_${house.id}`; const sockets = interiorSockets(house, spec), props = Array.isArray(house.interiorProps) && house.interiorProps.length ? house.interiorProps : defaultProps(house); Object.assign(group.userData ||= {}, { cottageInteriorSystem:true, houseId:house.id, visualOnly:true, sockets, npcSockets:{ resident:npcSocketForHouse(house,"resident"), worker:npcSocketForHouse(house,"worker"), visitor:npcSocketForHouse(house,"visitor") } }); group.add(box(`${house.id}_wood_floor`, [spec.width || house.sx || 6, .08, spec.depth || house.sz || 5], [0,.04,0], P.floor.color, { interiorProp:"floor" })); props.forEach(item => group.add(buildInteriorProp(house, item, sockets))); return { group, props, sockets }; }
export default buildCottageInterior;
