// B"H
/** @file HousePlanner.js @description Houses are families, doors, interiors, repairs, and memory, not props. */
import { interiorFor } from "./HouseInteriorSpawner.js";
const JOBS=["blacksmith","baker","scribe","tailor","healer","farmer","teacher","weaver"];
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
function baseHouse(i,src={}){ const profession=src.profession||src.trade||JOBS[i%JOBS.length], id=src.id||`cottage_${i}`, x=n(src.x,-42+(i%5)*22), z=n(src.z,-22+Math.floor(i/5)*24), lockId=src.door?.lockId||`${id}_front_lock`, keyId=src.door?.keyId||`${id}_key`; return { ...src, id, houseId:id, x, z, sx:n(src.sx,6.2), sy:n(src.sy,3.2), sz:n(src.sz,5.4), yaw:n(src.yaw??src.rotationY,(i%2?.12:-.08)), rotationY:n(src.rotationY??src.yaw,(i%2?.12:-.08)), owner:src.owner||`family_${i}`, family:{ name:src.family?.name||`Bayis ${i+1}`, members:src.family?.members||[`${profession}_parent`,`child_${i}`] }, profession, style:"cottage-brick", age:n(src.age,8+i*3), condition:n(src.condition,.82), repairs:src.repairs||[], history:src.history||[`Built for ${profession} work`], cottage:true, brickSystem:true, doorWidth:1.28, doorHeight:2.15, door:{ width:1.28,height:2.15,hinge:i%2?"right":"left",locked:false,lockId,keyId,owner:`family_${i}` }, windows:[{side:"front",x:-1.7,y:1.85},{side:"front",x:1.7,y:1.85},{side:"left",z:0,y:1.7}], interiorProps:src.interiorProps||interiorFor(profession), yard:{radius:8,gate:"front"}, colliderProfile:"cottage-brick-door-gap", worldMemory:{ repairs:0, visits:0, weatherDamage:0 } }; }
function fromReport(report={}){ const raw=report?.houses||report?.village?.houses||report?.parcels?.houses||report?.kingdom?.houses||[]; return Array.isArray(raw)&&raw.length?raw.map((h,i)=>baseHouse(i,h)):null; }
export function planHouses(report={}){ const count=Number.isFinite(Number(report.count))?Number(report.count):10; return fromReport(report)||Array.from({length:count},(_,i)=>baseHouse(i)); }
export function buildHousePlan(options={}){ return planHouses(options); }
export function houseColliderFootprints(report={}){ return planHouses(report).map(h=>({ id:h.id,houseId:h.id,x:h.x,z:h.z,sx:h.sx,sy:h.sy,sz:h.sz,yaw:h.yaw,rotationY:h.rotationY,doorWidth:h.doorWidth,doorHeight:h.doorHeight,door:h.door,style:h.style,family:h.family,condition:h.condition })); }
export default planHouses;
