// B"H
import assert from "node:assert/strict";
import { installProgressionFeaturePack } from "../geelooy/games/mitzvahWorld/ckidsAwtsmoos/progression/runtime/ProgressionFeaturePack.js";
import { xpForLevel } from "../geelooy/games/mitzvahWorld/ckidsAwtsmoos/progression/runtime/LevelCurveRuntime.js";
import { installTrainerFeaturePack } from "../geelooy/games/mitzvahWorld/ckidsAwtsmoos/trainers/runtime/TrainerFeaturePack.js";
import { installEconomyFeaturePack } from "../geelooy/games/mitzvahWorld/ckidsAwtsmoos/economy/runtime/EconomyFeaturePack.js";
import { installSoundFeaturePack } from "../geelooy/games/mitzvahWorld/ckidsAwtsmoos/audio/runtime/SoundFeaturePack.js";
import { weaponList, weaponStats } from "../geelooy/games/mitzvahWorld/ckidsAwtsmoos/equipment/runtime/WeaponStatCatalog.js";
import { ammoList } from "../geelooy/games/mitzvahWorld/ckidsAwtsmoos/equipment/runtime/AmmoCatalog.js";
import { merchantItems } from "../geelooy/games/mitzvahWorld/ckidsAwtsmoos/economy/runtime/MerchantInventoryRuntime.js";
import { statsUiState } from "../geelooy/games/mitzvahWorld/ckidsAwtsmoos/ui/runtime/StatsUiState.js";
const runtime={entities:new Map(),ready:[],registerEntity(e){this.entities.set(e.id,e);return e;},markReady(k,v){this.ready.push([k,v]);}};
const progression=installProgressionFeaturePack(runtime);
const trainers=installTrainerFeaturePack(runtime);
const economy=installEconomyFeaturePack(runtime,{startingPerutas:9000});
const sound=installSoundFeaturePack(runtime,{});
assert.equal(runtime.sound.snapshot().enabled,true);
assert.equal(runtime.music, undefined);
assert.equal(sound.play("slash").played,false);
assert.equal(sound.snapshot().last.type,"sword");
const weapons=weaponList();
assert.ok(weapons.filter(w=>w.genre.includes("Sword")||w.genre==="shortSword"||w.genre==="longSword"||w.genre==="greatSword").length>=8);
assert.ok(weapons.filter(w=>w.genre==="staff"||w.id.includes("Staff")).length>=6);
assert.ok(ammoList().length>=6);
assert.ok(merchantItems("bowyer").some(i=>i.kind==="ammo"));
let lowGate=trainers.canUse("player", weaponStats("mitzvahGreatSword"));
assert.equal(lowGate.ok,false);
assert.equal(lowGate.levelMissing,true);
progression.ensure("player",{level:12,xp:xpForLevel(12)});
trainers.train("player","sword",4,{});
assert.equal(trainers.canUse("player", weaponStats("mitzvahGreatSword")).ok,true);
let shop=economy.shop({actorId:"player",merchantId:"blacksmith",selectedId:"mitzvahGreatSword",runtime,equippedId:"simpleSword"});
assert.equal(shop.iconFirst,true);
assert.equal(shop.minimalText,true);
assert.equal(shop.dialogue,"");
assert.ok(shop.selected.icon);
assert.ok(shop.preview.stats.iconGrid.length>=5);
assert.ok(shop.actionIcons.buy.icon);
const bought=economy.buy("player","blacksmith","mitzvahGreatSword");
assert.equal(bought.ok,true);
sound.play("buy");
assert.equal(sound.snapshot().last.type,"coin");
const stats=statsUiState({entity:weaponStats("mitzvahGreatSword"),compare:weaponStats("simpleSword")});
assert.equal(stats.compact,true);
assert.equal(stats.minimalText,true);
assert.ok(stats.iconGrid.some(x=>x.key==="damage"&&x.delta>0));
console.log("B'H mitzvahWorld.iconSfxWeaponsStats.smoke passed", {weapons:weapons.length, ammo:ammoList().length, icons:shop.preview.stats.iconGrid.length, sfx:sound.snapshot().count});
