# B"H
[Unit]
StartLimitIntervalSec=120
StartLimitBurst=10

[Service]
WorkingDirectory=/mnt/HC_Volume_102267213/releases/current
Environment=AWTSMOOS_TANACH_INDEX=/mnt/HC_Volume_102267213/dayuhChadash-runtime/ai/comment-rag/tanach.hebrew.search.fs.awtsdb
ExecStart=
ExecStart=/usr/bin/node --max-http-header-size=131072 /mnt/HC_Volume_102267213/releases/current/index.js
Restart=always
RestartSec=2
MemoryMax=1536M
