// B"H
import * as THREE from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
const CLASSES={terrain:{repeat:[34,34],roughness:.96},grass:{repeat:[42,42],roughness:.9},bark:{repeat:[10,16],roughness:.94},roof:{repeat:[9,7],roughness:.88},wall:{repeat:[7,7],roughness:.86},animal:{repeat:[5,3],roughness:.82},head:{repeat:[3.5,2.5],roughness:.78},ui:{repeat:[1,1],roughness:.7},default:{repeat:[2,2],roughness:.85}};
const RX={terrain:/terrain|ground|soil|path|road|hill|floor/i,grass:/grass|meadow|field/i,bark:/bark|trunk|branch|wood/i,roof:/roof|thatch|tile/i,wall:/wall|stone|plaster|brick|house/i,animal:/fur|animal|fox|rabbit|deer|goat|cow|frog|bird|body|tail|leg|paw/i,head:/head|face|snout|muzzle|ear|eye|nose|mouth|beard|hair/i,ui:/ui|hud|button|icon|glyph|marker|sprite|font|text/i};
export function classifyTextureTarget(label=""){for(const [k,r]of Object.entries(RX))if(r.test(label))return k;return"default"}
export function maxAnisotropy(scope=globalThis){try{return(scope.__AWTSMOOS_RENDERER__||scope.renderer||scope.mana?.renderer)?.capabilities?.getMaxAnisotropy?.()||8}catch{return 8}}
export function texturePolicyFor(label="",scope=globalThis){const kind=classifyTextureTarget(label),base=CLASSES[kind]||CLASSES.default;return{kind,repeat:base.repeat,roughness:base.roughness,wrap:kind==="ui"?THREE.ClampToEdgeWrapping:THREE.MirroredRepeatWrapping,minFilter:THREE.LinearMipmapLinearFilter,magFilter:THREE.LinearFilter,colorSpace:THREE.SRGBColorSpace,anisotropy:Math.min(16,maxAnisotropy(scope))}}
export function applyTexturePolicy(texture,label="",scope=globalThis){if(!texture)return null;const p=texturePolicyFor(label,scope);texture.colorSpace=p.colorSpace;texture.wrapS=p.wrap;texture.wrapT=p.wrap;texture.magFilter=p.magFilter;texture.minFilter=p.minFilter;texture.generateMipmaps=true;texture.anisotropy=Math.max(Number(texture.anisotropy)||1,p.anisotropy);if(texture.repeat?.set)texture.repeat.set(p.repeat[0],p.repeat[1]);texture.userData||={};texture.userData.hyperrealTexturePolicy={kind:p.kind,repeat:p.repeat,anisotropy:texture.anisotropy,at:Date.now()};texture.needsUpdate=true;return p}
export function applyMaterialPolicy(material,label="",scope=globalThis){if(!material)return null;const p=texturePolicyFor(label,scope);material.roughness=Math.max(Number(material.roughness)||0,p.roughness);material.userData||={};material.userData.hyperrealMaterialPolicy={kind:p.kind,roughness:material.roughness,at:Date.now()};material.needsUpdate=true;return p}
export default {classifyTextureTarget,texturePolicyFor,applyTexturePolicy,applyMaterialPolicy,maxAnisotropy};
