// B"H
/** @file SeamlessTextureTuning.js @description Hyperreal ping-pong texture fitting for live scene materials. */
import { applyTexturePolicy, applyMaterialPolicy } from './HyperrealTexturePolicy.js';
import { stampDetailIntent } from './MaterialDetailLayers.js';
const MAP_KEYS=Object.freeze(['map','normalMap','roughnessMap','metalnessMap','bumpMap','alphaMap','aoMap','emissiveMap','specularMap','displacementMap']);
function eachMaterial(object,visit){const mats=Array.isArray(object?.material)?object.material:[object?.material];for(const material of mats)if(material)visit(material,object)}
function label(object,material,texture){return[object?.name,object?.type,object?.userData?.kind,object?.userData?.species,material?.name,texture?.name,texture?.userData?.kind,texture?.source?.data?.src].filter(Boolean).join(' ')}
export function tuneSeamlessTextures(scene,scope=globalThis){const report={scanned:0,materials:0,textures:0,pingpong:0,linearized:0,mipmapped:0,headFixes:0,skipped:0,detailIntents:0,examples:[]};scene?.traverse?.(object=>{report.scanned++;eachMaterial(object,(material)=>{report.materials++;const matPolicy=applyMaterialPolicy(material,label(object,material,null),scope);stampDetailIntent(material,matPolicy?.kind||'default',1);report.detailIntents++;let touched=false;for(const key of MAP_KEYS){const texture=material?.[key];if(!texture){report.skipped++;continue}const policy=applyTexturePolicy(texture,label(object,material,texture),scope);report.textures++;report.pingpong+=policy?.kind==='ui'?0:1;report.linearized++;report.mipmapped++;if(policy?.kind==='head')report.headFixes++;touched=true;if(report.examples.length<18)report.examples.push({object:object.name||object.type||'unnamed',material:material.name||'material',key,repeat:policy?.repeat,kind:policy?.kind})}if(touched){material.userData||={};material.userData.awtsmoosTextureFit='hyperreal-policy-pingpong-mipmap-detail';material.needsUpdate=true}})});scope.__AWTSMOOS_TEXTURE_PINGPONG_REPORT__=report;return report}
export default tuneSeamlessTextures;
