// B"H
const crypto = require("crypto");
const { readStore, writeStore } = require("../core/store.js");
const { attachConversationToPreview } = require("../core/conversationStore.js");
const { DEFAULT_SETTINGS, aiPolicyCheck, deniesSecretPath, mergedSettings, normalizePreview, normalizeAccess } = require("./previewPolicy.js");
function id(prefix = "view") { return `${prefix}_${crypto.randomBytes(12).toString("hex")}`; }
function now() { return Date.now(); }
function baseUrl() { return "https://awtsmoos.com"; }
function ensure(store, userId) { store.previewGateway = store.previewGateway || { users:{} }; const users = store.previewGateway.users; users[userId] = users[userId] || { settings:{ ...DEFAULT_SETTINGS }, previews:{} }; users[userId].settings = mergedSettings(users[userId].settings); users[userId].previews = users[userId].previews || {}; return users[userId]; }
function settingsGet(userId) { return ensure(readStore(), userId).settings; }
function settingsSet(userId, patch = {}) { const store = readStore(), bucket = ensure(store, userId); bucket.settings = mergedSettings({ ...bucket.settings, ...patch }); writeStore(store); return bucket.settings; }
function createPreview(userId, input = {}) { const store = readStore(), bucket = ensure(store, userId), policy = aiPolicyCheck(input, bucket.settings); if (!policy.ok) return policy; const normalized = normalizePreview(input, bucket.settings), sourcePath = normalized.path || normalized.source?.path || ""; if (["file", "folder"].includes(normalized.kind) && deniesSecretPath(sourcePath, bucket.settings)) return { ok:false, error:"preview_secret_path_denied", path:sourcePath }; const previewId = id("view"), at = now(); const preview = attachConversationToPreview({ BH:"B\"H", ok:true, id:previewId, ownerUserId:userId, tunnelName:normalized.tunnelName || normalized.targetVessel || "awtsmoos-virtual-os", targetVessel:normalized.targetVessel || normalized.tunnelName || "awtsmoos-virtual-os", kind:normalized.kind, title:normalized.title || titleFor(normalized), source:normalized.source || sourceFor(normalized), visibility:normalized.visibility, access:normalized.access || { userIds:[], emails:[] }, allowDownload:normalized.allowDownload, allowFolderBrowse:normalized.allowFolderBrowse, allowSearch:normalized.allowSearch, allowRaw:normalized.allowRaw, createdBy:normalized.createdBy || (normalized.ai ? "ai" : "user"), aiEditable:normalized.aiEditable !== false, createdAt:at, expiresAt:at + normalized.ttlSeconds * 1000, openedCount:0, revoked:false }, input); bucket.previews[previewId] = preview; writeStore(store); return withUrls(preview); }
function titleFor(input) { if (input.kind === "proxy") return `Proxy ${input.url || input.port || "server"}`; if (input.kind === "page") return input.title || "Dynamic Awtsmoos Page"; return input.title || input.path || input.actionId || "Awtsmoos Preview"; }
function sourceFor(input) { if (input.kind === "page") return { html:input.html || "", css:input.css || "", data:input.data || null }; if (input.kind === "proxy") return { url:input.url || "", port:input.port || null, path:input.proxyPath || input.path || "/" }; if (input.kind === "action") return { actionId:input.actionId || "", result:input.result || null }; if (input.kind === "live") return { commandId:input.commandId || input.jobId || input.actionId || "" }; return { path:input.path || input.p || "." }; }
function withUrls(preview) { const url = `${baseUrl()}/view/${encodeURIComponent(preview.id)}`; return { ...preview, url, viewUrl:url, rawUrl:`${url}/raw`, wsUrl:`${url}/ws`, accessSummary:accessSummary(preview) }; }
function accessSummary(preview = {}) { if (preview.visibility === "public") return "Anyone with the link can view until expiry."; const users = preview.access?.userIds?.length || 0, emails = preview.access?.emails?.length || 0; return users || emails ? `Private: owner plus ${users + emails} invited account(s).` : "Private: only the owner account can view."; }
function getPreview(userId, previewId, options = {}) { const store = readStore(), bucket = ensure(store, userId || "anonymous"), preview = bucket.previews[String(previewId || "")]; if (!active(preview)) return null; if (!previewAllowed(preview, options.identity || { userId }, options)) return null; preview.openedCount += options.countOpen === false ? 0 : 1; writeStore(store); return withUrls(preview); }
function findPreviewAny(previewId) { const store = readStore(), users = store.previewGateway?.users || {}; for (const [userId, bucket] of Object.entries(users)) { const preview = bucket.previews?.[previewId]; if (active(preview)) return { userId, preview:withUrls(preview) }; } return null; }
function previewAllowed(preview, ident = {}, options = {}) { if (!active(preview)) return false; if (preview.visibility === "public" || preview.visibility === "tunnel-open") return true; if (preview.visibility === "one-time" && preview.openedCount > 0 && options.countOpen !== false) return false; if (!ident?.ok && !ident?.userId) return false; const userId = ident.userId || "", email = String(ident.email || ident.mail || "").toLowerCase(); if (userId && userId === preview.ownerUserId) return true; const access = preview.access || {}; return Boolean((userId && access.userIds?.includes(userId)) || (email && access.emails?.includes(email))); }
function active(preview) { return Boolean(preview && !preview.revoked && preview.expiresAt > now()); }
function listPreviews(userId) { const store = readStore(), bucket = ensure(store, userId); return Object.values(bucket.previews).filter(active).map(withUrls).sort((a, b) => b.createdAt - a.createdAt); }
function revokePreview(userId, previewId) { const store = readStore(), bucket = ensure(store, userId); if (!bucket.previews[previewId]) return { ok:false, error:"preview_not_found" }; bucket.previews[previewId].revoked = true; writeStore(store); return { ok:true, id:previewId }; }
function updatePreview(userId, previewId, patch = {}) { const store = readStore(), bucket = ensure(store, userId), existing = bucket.previews[previewId]; if (!existing) return { ok:false, error:"preview_not_found" }; const policy = aiPolicyCheck({ ...existing, ...patch }, bucket.settings); if (!policy.ok) return policy; const next = normalizePreview({ ...existing, ...patch }, bucket.settings); bucket.previews[previewId] = { ...existing, ...next, access:normalizeAccess(next.access || existing.access), updatedAt:now() }; writeStore(store); return withUrls(bucket.previews[previewId]); }
function grantPreview(userId, previewId, accessPatch = {}) { const existing = findOwned(userId, previewId); if (!existing.ok) return existing; const access = mergeAccess(existing.preview.access, accessPatch); return updatePreview(userId, previewId, { access }); }
function revokePreviewAccess(userId, previewId, accessPatch = {}) { const existing = findOwned(userId, previewId); if (!existing.ok) return existing; const remove = normalizeAccess(accessPatch), current = normalizeAccess(existing.preview.access); return updatePreview(userId, previewId, { access:{ userIds:current.userIds.filter(x => !remove.userIds.includes(x)), emails:current.emails.filter(x => !remove.emails.includes(x)) } }); }
function findOwned(userId, previewId) { const store = readStore(), bucket = ensure(store, userId), preview = bucket.previews[previewId]; if (!preview) return { ok:false, error:"preview_not_found" }; return { ok:true, preview }; }
function mergeAccess(oldAccess = {}, patch = {}) { const old = normalizeAccess(oldAccess), next = normalizeAccess(patch); return { userIds:[...new Set([...old.userIds, ...next.userIds])], emails:[...new Set([...old.emails, ...next.emails])] }; }
module.exports = { createPreview, findPreviewAny, getPreview, grantPreview, listPreviews, previewAllowed, revokePreview, revokePreviewAccess, settingsGet, settingsSet, updatePreview, withUrls };
