// B"H
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { findBrowser } from "../tests/chrome/ChromePath.js";
import { launchChrome } from "../tests/chrome/ChromeLauncher.js";
import { connectCdp } from "../tests/chrome/ChromeDevTools.js";
const args=Object.fromEntries(process.argv.slice(2).map(a=>{const[k,...v]=a.replace(/^--/,"").split("=");return[k,v.join("=")||true]}));
const seconds=Number(args.seconds||45),fps=Number(args.fps||10),frames=Math.floor(seconds*fps);
const out=String(args.out||`/Users/awtsmoos/Movies/mitzvahWorld/chossid-glb-real-3d-multi-angle-actions-${Date.now()}.mp4`);
const proof=String(args.proofDir||"ai_thoughts/20260707-004045-full-repair-no-freeze-loading-ui-targeting-doors/proof/single-multi-angle-movie");
const frameDir=`${proof}/frames`;mkdirSync(frameDir,{recursive:true});rmSync(frameDir,{recursive:true,force:true});mkdirSync(frameDir,{recursive:true});mkdirSync(out.replace(/\/[^/]+$/,""),{recursive:true});
const url=`http://127.0.0.1:8080/games/mitzvahWorld/?compact=true&path=village.json&awtsMovieCapture=single-multi-angle-${Date.now()}`;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function ev(c,e,t=30000){const r=await c.send("Runtime.evaluate",{expression:e,awaitPromise:true,returnByValue:true},t);if(r.exceptionDetails)throw new Error(r.exceptionDetails.text||"eval failed");return r.result?.value}
async function ready(c){for(let i=0;i<260;i++){const p=await ev(c,"(()=>{const canvas=document.querySelector('canvas'),m=window.__AWTSMOOS_ACTIVE_WORKER_MANAGER__||window.__AWTSMOOS_MANAGER__?.socket||window.__AWTSMOOS_MANAGER__;return{ok:!!(canvas&&canvas.width>0&&canvas.height>0&&m),w:canvas?.width,h:canvas?.height,href:location.href,title:document.title,body:document.body?.innerText?.slice(0,160),veil:!!document.getElementById('awtsmoosLoadingVeil')}})()").catch(e=>({ok:false,error:String(e)}));if(p.ok)return p;await sleep(500)}throw new Error("game not playable for movie") }
const timeline=[[0,5,"walk",true,.55,"wide-left"],[5,10,"walk",true,-.38,"wide-right"],[10,15,"run",true,.85,"low-orbit"],[15,20,"jump",false,-.75,"hero-front"],[20,25,"talk",false,.45,"dialogue-close"],[25,30,"punch",false,-.55,"action-side"],[30,35,"stab",false,.65,"action-reverse"],[35,40,"dance",false,-.8,"celebration-orbit"],[40,45,"run",true,.35,"final-track"]];
function beat(t){return timeline.find(b=>t>=b[0]&&t<b[1])||timeline.at(-1)}
function driveExpression(i){const t=i/fps,b=beat(t),local=t-b[0],action=b[2],forward=b[3],angle=b[4],pulse=i%Math.max(2,Math.floor(fps/2))===0;return `(()=>{const m=window.__AWTSMOOS_ACTIVE_WORKER_MANAGER__||window.__AWTSMOOS_MANAGER__?.socket;const action=${JSON.stringify(action)},forward=${forward},pulse=${pulse};m?.postMessage?.({movie3DAction:{action,loop:action!=='jump',timeScale:action==='run'?1.25:1,id:'single-${i}'}});m?.postMessage?.({mobileMove:{FORWARD:forward,BACKWARD:false,LEFT_STRIDE:false,RIGHT_STRIDE:false,source:'single-multi-angle-movie'}});m?.postMessage?.({cameraDrag:{dx:${Math.round(angle*18)},dy:${Math.round(Math.sin(local*1.7)*5)}}});m?.postMessage?.({playerProbe:{id:'single-probe-${i}'}});function key(c,t='keydown'){const e=new KeyboardEvent(t,{bubbles:true,cancelable:true,code:c,key:c.replace('Key','').replace('Digit','')});window.dispatchEvent(e);document.dispatchEvent(e);document.querySelector('canvas')?.dispatchEvent(e)}forward?key('KeyW'):key('KeyW','keyup');action==='run'?key('ShiftLeft'):key('ShiftLeft','keyup');if(action==='jump'&&pulse)key('Space');if((action==='punch'||action==='stab')&&pulse)key('KeyX');return{frame:${i},time:${JSON.stringify(t.toFixed(2))},action,camera:${JSON.stringify(b[5])},forward,real3DOnly:true,overlay:false}})()`}
async function probe(c){return ev(c,"window.__AWTSMOOS_LAST_PLAYER_PROBE__||null").catch(()=>null)}
const browser=findBrowser();if(!browser.path)throw new Error("Chrome not found");
const chrome=await launchChrome(browser.path,url,9297,{width:1280,height:720});const events=[];
try{const client=await connectCdp(chrome.page.webSocketDebuggerUrl,e=>events.push(e));await client.send("Runtime.enable");await client.send("Page.enable");await client.send("Network.enable");const playable=await ready(client);const samples=[],probes=[];for(let i=0;i<frames;i++){samples.push(await ev(client,driveExpression(i)));await sleep(1000/fps);if(i%fps===0)probes.push(await probe(client));const shot=await client.send("Page.captureScreenshot",{format:"png",captureBeyondViewport:false},15000);writeFileSync(`${frameDir}/frame_${String(i).padStart(5,"0")}.png`,Buffer.from(shot.data,"base64"))}await ev(client,"(()=>{const m=window.__AWTSMOOS_ACTIVE_WORKER_MANAGER__||window.__AWTSMOOS_MANAGER__?.socket;m?.postMessage?.({mobileMove:{FORWARD:false,BACKWARD:false,LEFT_STRIDE:false,RIGHT_STRIDE:false}});return true})()");
const ff=spawnSync("ffmpeg",["-y","-framerate",String(fps),"-i",`${frameDir}/frame_%05d.png`,"-vf","scale=1280:720,format=yuv420p","-c:v","libx264","-pix_fmt","yuv420p","-movflags","+faststart",out],{encoding:"utf8"});if(ff.status!==0)throw new Error(ff.stderr);
const fp=spawnSync("ffprobe",["-v","error","-show_format","-show_streams","-count_frames","-print_format","json",out],{encoding:"utf8"});if(fp.status!==0)throw new Error(fp.stderr);
const clips=[...new Set(probes.map(p=>p?.animation?.currentClip).filter(Boolean))];const report={ok:true,output:resolve(out),outsideRepo:!resolve(out).includes("/Documents/awtsmoos/git/"),seconds,fps,frames,playable,actions:[...new Set(samples.map(s=>s.action))],cameras:[...new Set(samples.map(s=>s.camera))],clips,overlay:false,real3DOnly:true,ffprobe:JSON.parse(fp.stdout)};writeFileSync(`${proof}/single-multi-angle-report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));client.close?.()}finally{await chrome.close()}
