// B"H
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { spawn, spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { findBrowser } from '../tests/chrome/ChromePath.js';
import { connectCdp } from '../tests/chrome/ChromeDevTools.js';
const seconds=60,fps=24,frames=seconds*fps;
const out='/Users/awtsmoos/Movies/mitzvahWorld/masai-one-minute-journey-reusable-world.mp4';
const proof='ai_thoughts/latest-masai-one-minute-proof';const frameDir=`${proof}/frames`;mkdirSync(frameDir,{recursive:true});rmSync(frameDir,{recursive:true,force:true});mkdirSync(frameDir,{recursive:true});mkdirSync('/Users/awtsmoos/Movies/mitzvahWorld',{recursive:true});
const port=9867,url='http://127.0.0.1:8080/games/mitzvahWorld/tools/masaiOneMinuteJourneyMovie.html?render='+Date.now();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function json(u,opts){const r=await fetch(u,opts);if(!r.ok)throw new Error(`${r.status} ${u}`);return r.json()}
async function ev(c,e,t=30000){const r=await c.send('Runtime.evaluate',{expression:e,awaitPromise:true,returnByValue:true},t);if(r.exceptionDetails)throw new Error(r.exceptionDetails.text||'eval failed');return r.result?.value}
const chromePath=findBrowser().path;if(!chromePath)throw new Error('Chrome not found');const profile=join(tmpdir(),'awts-masai-minute-'+Date.now());
const chrome=spawn(chromePath,[`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'--no-first-run','--no-default-browser-check','--window-size=1280,720','about:blank'],{stdio:'ignore',detached:true});
try{for(let i=0;i<100;i++){try{await json(`http://127.0.0.1:${port}/json/version`);break}catch{await sleep(200)}}const target=await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(url)}`,{method:'PUT'});const client=await connectCdp(target.webSocketDebuggerUrl);await client.send('Runtime.enable');await client.send('Page.enable');let report=null;for(let i=0;i<160;i++){report=await ev(client,'window.__MASAI_ONE_MINUTE_REPORT__||null').catch(()=>null);if(report?.ok)break;const err=await ev(client,'window.__MASAI_MOVIE_ERROR__||null').catch(()=>null);if(err)throw new Error(err);await sleep(500)}if(!report?.ok)throw new Error('movie page did not become ready');const samples=[];for(let i=0;i<frames;i++){await sleep(1000/fps);if(i%24===0){const r=await ev(client,'window.__MASAI_ONE_MINUTE_REPORT__||null').catch(()=>null);if(r)samples.push(r)}const png=await client.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false},15000);writeFileSync(`${frameDir}/frame_${String(i).padStart(5,'0')}.png`,Buffer.from(png.data,'base64'))}const ff=spawnSync('ffmpeg',['-y','-framerate',String(fps),'-i',`${frameDir}/frame_%05d.png`,'-vf','scale=1280:720,format=yuv420p','-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart',out],{encoding:'utf8'});if(ff.status!==0)throw new Error(ff.stderr);const fp=spawnSync('ffprobe',['-v','error','-show_format','-show_streams','-count_frames','-print_format','json',out],{encoding:'utf8'});if(fp.status!==0)throw new Error(fp.stderr);const final={ok:true,output:resolve(out),outsideRepo:!resolve(out).includes('/Documents/awtsmoos/git/'),seconds,fps,frames,samples,regions:[...new Set(samples.map(s=>s.region))],clips:[...new Set(samples.map(s=>s.clip).filter(Boolean))],trees:report.trees,cliffs:report.cliffs,ffprobe:JSON.parse(fp.stdout)};writeFileSync(`${proof}/final-report.json`,JSON.stringify(final,null,2));spawnSync('open',[out]);console.log(JSON.stringify(final,null,2));client.close?.()}finally{try{process.kill(-chrome.pid)}catch{try{chrome.kill()}catch{}}}
