// B"H
/** Browser-side Stephen sample expression: FPS, visible UI, scene clues. */
export function browserSampleExpression(durationMs = 9000) {
  const duration = Math.max(3000, Math.min(30000, Number(durationMs) || 9000));
  return `new Promise(resolve => {
    const start = performance.now(), end = start + ${duration}, deltas = [], longTasks = [], actions = {};
    let last = performance.now(), observer = null;
    try { observer = new PerformanceObserver(list => list.getEntries().forEach(e => longTasks.push({ name:e.name, duration:e.duration, startTime:e.startTime }))); observer.observe({ entryTypes:['longtask'] }); } catch {}
    const count = name => actions[name] = (actions[name] || 0) + 1;
    const dispatch = (target, event) => { try { target?.dispatchEvent?.(event); } catch {} };
    const keyName = code => ({ KeyW:'w', KeyA:'a', KeyD:'d', KeyL:'l', Escape:'Escape', KeyF:'f', Space:' ' }[code] || code);
    function key(code, type='keydown') { const e = new KeyboardEvent(type, { bubbles:true, cancelable:true, code, key:keyName(code) }); dispatch(window,e); dispatch(document,e); dispatch(document.body,e); count(type + ':' + code); }
    const tap = code => { key(code, 'keydown'); setTimeout(() => key(code, 'keyup'), 70); };
    function clickCanvas() { const c = document.querySelector('canvas'), r = c?.getBoundingClientRect?.() || { left:100, top:100, width:800, height:450 }; const x=r.left+r.width*.5, y=r.top+r.height*.5; for (const t of ['mousemove','pointerdown','mousedown','pointerup','mouseup','click']) dispatch(c, new MouseEvent(t, { bubbles:true, cancelable:true, clientX:x, clientY:y, button:0, buttons:t.includes('down')?1:0 })); count('canvasClick'); }
    const moves = [() => key('KeyW','keydown'), () => tap('KeyF'), clickCanvas, () => tap('KeyL'), () => tap('Escape'), () => key('KeyW','keyup'), () => key('KeyA','keydown'), () => key('KeyA','keyup'), () => key('KeyD','keydown'), () => key('KeyD','keyup')];
    let moveIndex = 0; const actionTimer = setInterval(() => { moves[moveIndex % moves.length](); moveIndex += 1; }, 250);
    function frameStats(values) { const sorted = values.slice().sort((a,b)=>a-b), sum = values.reduce((a,b)=>a+b,0), avg = sum / Math.max(1, values.length); return { avgFrameMs:avg, fps:1000/Math.max(.001,avg), minFps:1000/Math.max(.001, sorted[sorted.length-1] || avg || 16.67), p95FrameMs:sorted[Math.floor(sorted.length*.95)] || 0, p99FrameMs:sorted[Math.floor(sorted.length*.99)] || 0, worstFrameMs:sorted[sorted.length-1] || 0, droppedFrames:values.filter(v=>v>34).length, longFrames:values.filter(v=>v>50).length }; }
    function findScene() { const roots = [window.__AWTSMOOS_OLAM__, window.olam, window.ikar?.olam, window.mana?.activeOlam, window.mana?.olam, window.mana, window.ikar].filter(Boolean); const seen = new WeakSet(), queue = roots.map((value, depth) => ({ value, path:'root' + depth, depth:0 })); while (queue.length && queue.length < 800) { const item = queue.shift(), value = item.value; if (!value || typeof value !== 'object' || seen.has(value)) continue; seen.add(value); if (value.children && typeof value.traverse === 'function') return { scene:value, path:item.path }; if (item.depth >= 5) continue; for (const key of Object.keys(value).slice(0, 60)) { try { const child = value[key]; if (child && typeof child === 'object') queue.push({ value:child, path:item.path + '.' + key, depth:item.depth + 1 }); } catch {} } } return null; }
    function sceneStats() { const found = findScene(); if (!found?.scene) return null; let objects=0, meshes=0, skinned=0, instanced=0; const materials=new Set(), textures=new Set(); found.scene.traverse(o => { objects++; if(o.isMesh) meshes++; if(o.isSkinnedMesh) skinned++; if(o.isInstancedMesh) instanced++; const mats=Array.isArray(o.material)?o.material:[o.material]; mats.filter(Boolean).forEach(m => { materials.add(m); ['map','normalMap','roughnessMap','metalnessMap','aoMap','alphaMap','emissiveMap','bumpMap'].forEach(k => { if(m[k]) textures.add(m[k]); }); }); }); return { path:found.path, objects, meshes, skinned, instanced, materials:materials.size, textures:textures.size }; }
    function visiblePanels() { return [...document.querySelectorAll('.mitzvahPanel, [role=dialog], .awtsmoosShlichusBook, #mitzvahCenter > *')].filter(el => { const s = getComputedStyle(el), r = el.getBoundingClientRect(); return s.display !== 'none' && s.visibility !== 'hidden' && r.width > 2 && r.height > 2; }).length; }
    function finish() { clearInterval(actionTimer); ['KeyW','KeyA','KeyD'].forEach(code => key(code,'keyup')); try { observer?.disconnect?.(); } catch {} const memory = performance.memory ? { usedJSHeapSize:performance.memory.usedJSHeapSize, totalJSHeapSize:performance.memory.totalJSHeapSize, jsHeapSizeLimit:performance.memory.jsHeapSizeLimit } : null; resolve({ name:'Stephen', url:location.href, title:document.title, readyState:document.readyState, bodyText:document.body?.innerText?.slice(0,700)||'', frameCount:deltas.length, ...frameStats(deltas), longTaskCount:longTasks.length, longTasks:longTasks.slice(-12), actions, memory, canvases:document.querySelectorAll('canvas').length, visiblePanels:visiblePanels(), scrollUi:window.__AWTSMOOS_SCROLL_UI__||null, postLoadFpsReport:window.__AWTSMOOS_POST_LOAD_FPS_REPORT__||null, postLoadProbe:window.__AWTSMOOS_POST_LOAD_FPS_PROBE__||null, textureReport:window.__AWTSMOOS_TEXTURE_PINGPONG_REPORT__||null, visualReport:window.__AWTSMOOS_VISUAL_TUNING__||null, rendererDiscovery:window.__AWTSMOOS_RENDERER_DISCOVERY__||null, performanceMode:window.__AWTSMOOS_PERFORMANCE_MODE__||null, fpsGuardian:window.__AWTSMOOS_FPS_GUARDIAN__||null, sceneStats:sceneStats(), globals:Object.fromEntries(['__AWTSMOOS_OLAM__','olam','ikar','mana','__AWTSMOOS_RENDERER__','renderer'].map(k=>[k,typeof window[k]])) }); }
    function frame(now) { deltas.push(now - last); last = now; now >= end ? finish() : requestAnimationFrame(frame); }
    requestAnimationFrame(frame);
  })`;
}
