// B"H
/**
 * @file classMap.js
 * @description
 * Chapter 1006: old procedural tree classes are not instantiable here.
 */
export default {
  Domem: "../../chayim/domem/index.js",
  Tzomayach: "../../chayim/tzomayach.js",
  Chai: "../../chayim/chai/index.js",
  Medabeir: "../../chayim/medabeir/index.js",
  Chossid: "../../chayim/chossid/index.js?v=stable-movement-restore-20260614-bh1",
  Tool: "../../dvarim/tool.js",
  Coin: "../../dvarim/coin.js",
  Container: "../../dvarim/container.js",
  Wheat: "../../dvarim/farming/wheat.js",
  Mill: "../../dvarim/farming/mill.js",
  Oven: "../../dvarim/farming/oven.js",
  Fire: "../../dvarim/fire.js",
  Lava: "../../dvarim/lava.js",
  Portal: "../../dvarim/portal.js",
  CollectableItem: "../../dvarim/collectableItem.js",
  CharacterMaker: "../../dvarim/characterMaker.js",
  CustomNpc: "../../dvarim/customNpc.js",
  NatureTool: "../../dvarim/nature/natureTool.js",
  ProceduralCloud: "../../dvarim/nature/proceduralCloud.js",
  ProceduralRiver: "../../dvarim/nature/proceduralRiver.js",
  Forest: "../../dvarim/nature/forest.js",
  ProceduralPool: "../../dvarim/nature/proceduralPool.js",
  ProceduralTerrain: "../../dvarim/terrain/ProceduralTerrain.js?v=village-no-safety-slab-20260609-bh622",
  Shovel: "../../dvarim/tools/shovel.js",
  Pickaxe: "../../dvarim/tools/pickaxe.js",
  RoadTool: "../../dvarim/tools/roadTool.js",
  LivingField: "../../utils/3d/procedural/nature/LivingField.js",
  Vehicle: "../../dvarim/vehicles/vehicle.js",
  ProceduralCar: "../../dvarim/vehicles/proceduralCar.js",
  GrapplingHook: "../../dvarim/tools/grapplingHook.js",
  Blueprint: "../../dvarim/tools/blueprint.js",
  FishingRod: "../../dvarim/tools/fishingRod.js",
  Sefer: "../../dvarim/tools/sefer.js",
  Teffilin: "../../dvarim/teffilin.js",
  VoxelTerrain: "../../dvarim/terrain/VoxelTerrain.js",
  Brick: "../../dvarim/brick.js",
  Stairs: "../../dvarim/stairs.js",
  Apparel: "../../dvarim/apparel.js",
  Mazik: "../../chayim/mazik.js",
  ElementalStaff: "../../dvarim/tools/elementalStaff.js",
  FluidSystem: "../../dvarim/nature/fluidSystem.js",
  InteractiveDoor: "../../dvarim/SimpleDoor.js",
  InteractiveNpc: "../../dvarim/npc/InteractiveNpc.js?v=direct-guide-ui-20260605-bh449",
  ProceduralSky: "../../dvarim/nature/ProceduralSky.js",
  ProceduralFlowerPatch: "../../dvarim/nature/ProceduralFlowerPatch.js",
  ProceduralRoad: "../../dvarim/architecture/ProceduralRoad.js",
  Collectable: "../../dvarim/Collectable.js",
  SolidBlock: "../../dvarim/architecture/SolidBlock.js",
  ProceduralBuilding: "../../dvarim/architecture/ProceduralBuilding.js",
  ProceduralFlora: "../../dvarim/nature/ProceduralFlora.js",
  VillageHeroTree: "../../dvarim/nature/VillageHeroTree.js?v=only-geelooy-libs-hero-tree-20260614-bh1",
  VillageHouseCollider: "../../dvarim/nature/VillageHouseCollider.js?v=lava-camera-axis-20260609-bh640",
  VillageFenceCollider: "../../dvarim/nature/VillageFenceCollider.js?v=lava-camera-axis-20260609-bh640",
  VillageRoadCollider: "../../dvarim/nature/VillageRoadCollider.js?v=detached-road-octree-20260605-bh449"
};
