// B"H
/** @file AbilityIndex.js @description Torah class ability catalog with trainer ranks, specializations, close/ranged contracts, and quote routes. */
const q = (id, text, bonus = 0) => ({ id, text, bonus });
const ch = (id, title, quotes) => ({ id, title, quotes });
const route = (id, title, chapters) => ({ id, title, chapters });
const ranks = (max, damageStep = .18, costStep = .08, unlockLevel = 1) => ({ max, damageStep, costStep, unlockLevel });
const cls = (tree, role, passives = []) => ({ tree, role, passives });
export const AbilityIndex = Object.freeze({
  shemaUnity: { id:"shemaUnity", name:"Shema Unity", category:"Mishnah", seferId:"siddur", power:22, cost:5, scale:"chochmah", icon:"ש", weaponHint:"cherev_hakodesh", rangeStyle:"close", minRange:0, maxRange:8, meleeSeries:2, requiresFacing:true, classPath:cls("Torah", "close", ["unity_resolve", "fear_breaker"]), ranks:ranks(4,.2,.06,1), text:"You declare the One Source like a doubled-edge close-range sword.", routes:[route("morning_prayer", "Morning Prayer", [ch("unity1", "Unity", [q("echad", "Hashem is One.", 0), q("acceptance", "The yoke becomes wings.", 3)])])] },
  amidahArrow: { id:"amidahArrow", name:"Amidah Arrow", category:"Hitbonenus", seferId:"siddur", power:30, cost:14, scale:"daat", icon:"ע", weaponHint:"keshes_haemes", rangeStyle:"long", minRange:7, maxRange:72, projectileRefine:true, requiresFacing:true, classPath:cls("Avodah", "ranged", ["steady_stance", "refined_aim"]), ranks:ranks(4,.16,.08,2), text:"The Amidah stands still, draws a bow, and refines distant harshness.", routes:[route("standing_prayer", "Standing Prayer", [ch("refinement", "Distant Refinement", [q("stand", "You stand rooted while the arrow rises.", 4), q("bow", "The bow carries refinement to the far place.", 8)])])] },
  tehillimSong: { id:"tehillimSong", name:"Tehillim Song", category:"Niggun", seferId:"tehillim", power:10, heal:14, cost:8, scale:"binah", icon:"נ", weaponHint:"mateh_hatorah", rangeStyle:"mid", minRange:0, maxRange:28, requiresFacing:false, classPath:cls("Chesed", "support", ["song_healing", "calm_aura"]), ranks:ranks(4,.12,.05,2), text:"A psalm sweetens the field.", routes:[route("shir_hamaalos", "Shir Hamaalos", [ch("joy1", "Song of Ascent", [q("lift", "From narrowness, the song rises.", 3), q("guard", "The Guardian of Israel does not sleep.", 5)])])] },
  tanyaWarmth: { id:"tanyaWarmth", name:"Tanya Warmth", category:"Chassidus", seferId:"tanya", power:18, cost:12, scale:"daat", icon:"ת", weaponHint:"cherev_hakodesh", rangeStyle:"close", minRange:0, maxRange:10, requiresFacing:true, classPath:cls("Chassidus", "close", ["inner_warmth"]), ranks:ranks(3,.2,.06,3), text:"You reveal the animal soul as a servant.", routes:[route("two_souls", "Two Souls", [ch("chapter1", "Inner Wrestling", [q("servant", "The animal soul can become a servant.", 4), q("chelek", "The soul is a portion from above.", 6)])])] },
  chumashLight: { id:"chumashLight", name:"Chumash Light", category:"Mishnah", seferId:"chumash", power:24, cost:14, scale:"chochmah", icon:"ח", weaponHint:"cherev_hakodesh", rangeStyle:"mid", minRange:0, maxRange:18, requiresFacing:true, classPath:cls("Torah", "mid", ["creation_light"]), ranks:ranks(3,.18,.07,3), text:"Creation speaks again through the letters.", routes:[route("bereishis", "Bereishis", [ch("creation", "Creation", [q("beginning", "In the beginning, the vessel opens.", 5), q("light", "Let there be light in the field.", 7)])])] },
  mishnahClarity: { id:"mishnahClarity", name:"Mishnah Clarity", category:"Mishnah", seferId:"mishnah", power:28, cost:16, scale:"chochmah", icon:"מ", weaponHint:"cherev_hakodesh", rangeStyle:"close", minRange:0, maxRange:12, requiresFacing:true, classPath:cls("Torah", "close", ["clear_judgment"]), ranks:ranks(3,.2,.08,4), text:"You clarify the case with precise Mishnah.", routes:[route("avos", "Pirkei Avos", [ch("avos1", "Chapter 1", [q("judge", "Judge every person favorably.", 0), q("teacher", "Make for yourself a teacher.", 3)]), ch("avos2", "Chapter 2", [q("mitzvah", "One mitzvah draws another mitzvah.", 7)])])] },
  zoharRay: { id:"zoharRay", name:"Zohar Ray", category:"Kabbalah", seferId:"zohar", power:34, cost:22, scale:"chochmah", icon:"ז", weaponHint:"keshes_haemes", rangeStyle:"long", minRange:4, maxRange:76, projectileRefine:true, requiresFacing:true, classPath:cls("Kabbalah", "ranged", ["hidden_light"]), ranks:ranks(3,.16,.1,6), text:"Hidden light enters the visible place.", routes:[route("hidden_light", "Ohr Haganuz", [ch("ray1", "Hidden Light", [q("line", "A thin line enters the emptied place.", 8), q("below", "Returning light rises from below.", 9)])])] }
});
export const BaseAbilityIds = Object.freeze(Object.keys(AbilityIndex));
export const AbilityClassPaths = Object.freeze(Object.fromEntries(BaseAbilityIds.map(id => [id, AbilityIndex[id].classPath])));
export function abilityRankInfo(id) { const a = AbilityIndex[id]; return a?.ranks || ranks(1, 0, 0, 1); }
export function quoteMove(abilityOrId, ri = 0, ci = 0, qi = 0) {
  const ability = typeof abilityOrId === "string" ? AbilityIndex[abilityOrId] : abilityOrId; if (!ability) return null;
  const r = ability.routes[Math.min(ri, ability.routes.length - 1)], c = r.chapters[Math.min(ci, r.chapters.length - 1)], quote = c.quotes[Math.min(qi, c.quotes.length - 1)];
  return { id:ability.id, name:ability.name, category:ability.category, seferId:ability.seferId, icon:ability.icon, cost:ability.cost, damage:(ability.power || 0) + (quote.bonus || 0), heal:ability.heal || 0, scale:ability.scale, weaponHint:ability.weaponHint, rangeStyle:ability.rangeStyle, minRange:ability.minRange || 0, maxRange:ability.maxRange || 30, meleeSeries:ability.meleeSeries || 1, projectileRefine:Boolean(ability.projectileRefine), requiresFacing:ability.requiresFacing !== false, rankInfo:ability.ranks, classPath:ability.classPath, routeTitle:r.title, chapterTitle:c.title, routeQuote:quote.text, passage:quote.text, description:`${ability.text} ${quote.text}`, path:{ abilityId:ability.id, routeId:r.id, chapterId:c.id, quoteId:quote.id } };
}
export function allQuoteMoves() { return BaseAbilityIds.map(id => quoteMove(id)).filter(Boolean); }
export default AbilityIndex;
