// B"H
/** Real gameplay terrain: square mirrored grass tiles, visible mesh is also octree terrain. */
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=square-grass-repeat-20260709-bh3";
import Domem from "../../chayim/domem/index.js?compact=true&v=single-player-mixer-fast-20260709-bh1";
import { markVisualGroundAuthority } from "./core/GroundMeshAuthority.js?compact=true&v=visible-ground-authority-20260701-bh1";
import TerrainGeometryEmanator from "./core/TerrainGeometryEmanator.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import TerrainMaterialScribe from "./core/TerrainMaterialScribe.js?compact=true&v=square-grass-repeat-20260709-bh3";
import { insertOctree, n, solidFlags, terrainData, triangleCount } from "./core/ProceduralTerrainHelpers.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
function proof(stage,data={}){const payload={stage,at:Date.now(),source:"ProceduralTerrain",...data};globalThis.__AWTSMOOS_REAL_TERRAIN_PROOF__=payload;globalThis.postMessage?.({type:"worker_progress",cacheKind:"square-grass-repeat",...payload});}
export default class ProceduralTerrain extends Domem{type="proceduralTerrain";constructor(op={},olam){super(op,olam);this.isSolid=op.isSolid!==false;this.terrainData=terrainData(op,this.isSolid,true);}publishTerrainLaw(){if(!this.olam)return;const p=this.mesh?.position||{x:0,y:0,z:0};this.olam.awtsmoosTerrainLaw={data:{...this.terrainData},position:{x:n(p.x),y:n(p.y),z:n(p.z)},source:this.name||"proceduralTerrain"};}async heescheel(olam){this.olam=olam;const geometry=TerrainGeometryEmanator.emanate(this.terrainData);const material=await TerrainMaterialScribe.scribe(this.terrainData,olam,this);this.mesh=new THREE.Mesh(geometry,material);this.mesh.name=this.name||"Sacred_Earth_Square_Grass_Repeat";this.mesh.nivraAwtsmoos=this;this.mesh.visible=true;this.mesh.frustumCulled=false;this.mesh.renderOrder=-80;if(this.position)this.mesh.position.set(n(this.position.x),n(this.position.y),n(this.position.z));this.mesh.updateMatrixWorld(true);markVisualGroundAuthority(this.mesh,this,olam);solidFlags(this.mesh,"real-visible-terrain",this.terrainData);Object.assign(this.mesh.userData||={},{realTerrainOctree:true,visibleTerrainIsCollider:true,fakeCollider:false,neverCullTerrain:true,neverHideTerrain:true,forceRuntimeVisible:true,repeatingGrassTexture:true,squareWorldTiles:true,mirroredRepeat:true,neverStretch:true,walkableGround:true});this.publishTerrainLaw();await olam.hoyseef(this);if(!this.mesh.parent&&olam.scene?.add)olam.scene.add(this.mesh);const added=this.isSolid?insertOctree(olam,this.mesh):false;proof("terrain:square-grass-repeat-mesh-added-to-octree",{name:this.mesh.name,parent:this.mesh.parent?.name||null,octreeAdded:added,triangles:triangleCount(geometry),material:this.mesh.material?.type,width:this.terrainData.width,depth:this.terrainData.depth,repeatX:this.mesh.material?.userData?.repeatX,repeatY:this.mesh.material?.userData?.repeatY,tileSize:this.mesh.material?.userData?.tileSize});this.isReady=true;}heesHawvoos(){}}
