// B"H
/** Icon-only player HUD: health, quest, target, inventory bag, X, R, T. */
const ID = "awts-player-facing-hud-guarantee";
const $ = s => document.querySelector(s);
const pct = (a, b) => Math.max(0, Math.min(100, (Number(a) / Math.max(1, Number(b))) * 100));
const safe = v => String(v ?? "").replace(/[&<>"']/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[c]));
const inventoryDefaults = [{ id:"chumash", name:"Chumash", qty:1 }, { id:"siddur", name:"Siddur", qty:1 }, { id:"bread", name:"Bread", qty:2 }, { id:"wood", name:"Wood", qty:4 }];
function state() {
  const olam = window.__AWTSMOOS_OLAM__ || window.olam || {}, player = olam.player || olam.oyved || window.__AWTSMOOS_PLAYER__ || {}, hs = window.__AWTSMOOS_PLAYER_HEALTH_STATE__ || {};
  const health = Number(hs.current ?? player.health ?? player.hp ?? 100), max = Number(hs.max ?? player.maxHealth ?? player.maxHp ?? 100);
  const targeting = window.__AWTSMOOS_TARGETING_STATE__ || {}, target = targeting.selected || window.__AWTSMOOS_SELECTED_TARGET__ || null, quest = olam.__activeQuest || window.__AWTSMOOS_ACTIVE_QUEST__ || null;
  const inventory = window.__AWTSMOOS_INVENTORY_STATE__?.items || player.inventory?.slots || player.items || inventoryDefaults;
  return { health:Number.isFinite(health) ? health : 100, max:Number.isFinite(max) ? max : 100, target, quest, inventory:Array.isArray(inventory) ? inventory : inventoryDefaults };
}
function style() { return `<style id="${ID}-style">
#${ID}{position:fixed;inset:0;z-index:2147482500;pointer-events:none;font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:white;text-shadow:0 2px 5px #000}#${ID} .hud-card{background:rgba(7,13,25,.82);border:1px solid rgba(255,217,102,.48);border-radius:10px;box-shadow:0 8px 18px rgba(0,0,0,.32);padding:8px 10px;pointer-events:auto}#${ID} .health{position:absolute;left:max(10px,env(safe-area-inset-left));top:max(10px,env(safe-area-inset-top));width:min(280px,70vw)}#${ID} .target{position:absolute;right:max(10px,env(safe-area-inset-right));top:max(10px,env(safe-area-inset-top));width:min(250px,62vw)}#${ID} .quest{position:absolute;left:max(10px,env(safe-area-inset-left));top:82px;width:min(280px,70vw);font-size:12px}#${ID} .inventory{position:absolute;right:max(10px,env(safe-area-inset-right));top:116px;width:min(250px,62vw);font-size:12px}#${ID} .inventory.closed .inventory-list{display:none}#${ID} .inventory-row{display:flex;justify-content:space-between;gap:10px;border-top:1px solid rgba(255,255,255,.1);padding:4px 0}#${ID} .actions{position:absolute;left:50%;bottom:calc(14px + env(safe-area-inset-bottom));transform:translateX(-50%);display:flex;gap:8px;align-items:center}#${ID} .icon-only-action{width:48px;height:48px;display:grid;place-items:center;font-size:24px;border-radius:12px;background:rgba(0,0,0,.62);border:1px solid rgba(255,217,102,.65);color:white;text-decoration:none;box-shadow:0 5px 14px rgba(0,0,0,.32)}#${ID} .icon-only-action.primary{background:rgba(255,217,102,.18)}#${ID} .icon-only-action.flash{outline:2px solid #fff3b0}#${ID} .bar{height:9px;border-radius:999px;overflow:hidden;background:rgba(255,255,255,.15);margin-top:5px}.fill{height:100%;background:#58dc72}#${ID} .low .fill{background:#ff6048}#${ID} .muted{opacity:.82;font-size:11px}#${ID} button{font:inherit;cursor:pointer}@media(max-width:760px){#${ID} .actions{bottom:calc(94px + env(safe-area-inset-bottom));gap:6px}#${ID} .icon-only-action{width:42px;height:42px;font-size:22px}#${ID} .target{top:72px}#${ID} .inventory{top:auto;bottom:calc(148px + env(safe-area-inset-bottom));right:8px}}
</style>`; }
function html() { return `${style()}<div class="hud-card health" data-hud="health"></div><button class="hud-card target active" data-hud="targeting" type="button"></button><div class="hud-card quest" data-hud="quest"></div><div class="hud-card inventory closed" data-hud="inventory-panel" id="inventory"></div><nav class="actions icon-only-action-bar" data-hud="action-bar" aria-label="Icon only action bar"><button class="icon-only-action primary" data-hud="x-action" aria-label="X action" title="X action" type="button">⚡</button><button class="icon-only-action primary" data-hud="r-action" aria-label="Read rest reload" title="R read/rest/reload" type="button">📖</button><a class="icon-only-action" data-hud="inventory-button" data-hud-link="inventory-bag" aria-label="Inventory bag" title="Inventory bag" href="#inventory">🎒</a><button class="icon-only-action" data-hud="target-button" aria-label="Target select" title="T target/select" type="button">🎯</button></nav>`; }
function ensureMobileButtons() { if (!$("#joystick-container")) document.body.insertAdjacentHTML("beforeend", `<div id="joystick-container" data-hud="joystick"><div id="joystick-base"><div id="joystick-thumb"></div></div></div>`); if (!$("#mobile-jump-button")) document.body.insertAdjacentHTML("beforeend", `<button id="mobile-jump-button" data-hud="jump" type="button">↑</button>`); }
function render(root) {
  const s = state(), low = s.health / Math.max(1, s.max) <= .3, targetName = s.target?.name || s.target?.userData?.name || "Friendly Rebbe", targetType = s.target?.type || s.target?.userData?.targetType || "friendly-npc";
  const targetHp = s.target?.health ?? s.target?.hp ?? s.target?.userData?.health ?? null, targetDistance = s.target?.distance ?? s.target?.userData?.distance ?? null;
  root.querySelector("[data-hud='health']").classList.toggle("low", low); root.querySelector("[data-hud='health']").innerHTML = `<b>Health</b> ${Math.round(s.health)}/${Math.round(s.max)}<div class="bar"><div class="fill" style="width:${pct(s.health, s.max)}%"></div></div>`;
  root.querySelector("[data-hud='targeting']").innerHTML = `<b>Target</b><div>${safe(targetName)}</div><div class="muted">${safe(targetType)}${targetDistance != null ? ` · ${Number(targetDistance).toFixed(1)}m` : ""}${targetHp != null ? ` · HP ${safe(targetHp)}` : ""} · tap/click/select · T/Y</div>`;
  root.querySelector("[data-hud='quest']").innerHTML = `<b>Quest</b><div>${safe(s.quest?.title || s.quest?.name || "Study with a friendly NPC")}</div><div class="muted">X interact · R read/rest/reload</div>`;
  const rows = s.inventory.slice(0, 8).map(item => `<div class="inventory-row"><span>${safe(item.name || item.id || item.item?.name || "Item")}</span><b>${safe(item.qty ?? item.amount ?? 1)}</b></div>`).join(""); root.querySelector("[data-hud='inventory-panel']").innerHTML = `<b>Inventory Bag</b><span class="muted"> · 🎒</span><div class="inventory-list">${rows}</div>`;
}
function flash(root, selector) { const el = root.querySelector(selector); if (!el) return; el.classList.add("flash"); setTimeout(() => el.classList.remove("flash"), 160); }
function bind(root) {
  if (root.__awtsHudBound) return; root.__awtsHudBound = true; const toggleInventory = event => { event?.preventDefault?.(); root.querySelector("[data-hud='inventory-panel']")?.classList.toggle("closed"); };
  root.querySelector("[data-hud='inventory-button']")?.addEventListener("click", toggleInventory); root.querySelector("[data-hud='targeting']")?.addEventListener("click", () => window.__AWTSMOOS_CYCLE_TARGET__?.(1)); root.querySelector("[data-hud='target-button']")?.addEventListener("click", () => window.__AWTSMOOS_CYCLE_TARGET__?.(1));
  root.querySelector("[data-hud='x-action']")?.addEventListener("click", () => { flash(root, "[data-hud='x-action']"); window.dispatchEvent(new CustomEvent("awtsmoos-ui-action", { detail:{ action:"x-action" } })); }); root.querySelector("[data-hud='r-action']")?.addEventListener("click", () => { flash(root, "[data-hud='r-action']"); window.dispatchEvent(new CustomEvent("awtsmoos-ui-action", { detail:{ action:"read-rest-reload" } })); });
  window.addEventListener("keydown", event => { if (event.code === "KeyI") { toggleInventory(event); flash(root, "[data-hud='inventory-button']"); } if (event.code === "KeyT") flash(root, "[data-hud='target-button']"); if (event.code === "KeyX") flash(root, "[data-hud='x-action']"); if (event.code === "KeyR") flash(root, "[data-hud='r-action']"); });
}
export function installPlayerFacingHudGuarantee() {
  if (typeof document === "undefined") return null; let root = document.getElementById(ID); if (!root) { root = document.createElement("div"); root.id = ID; root.innerHTML = html(); document.body.appendChild(root); }
  ensureMobileButtons(); bind(root); render(root); clearInterval(root.__awtsHudTimer); root.__awtsHudTimer = setInterval(() => render(root), 350);
  window.__AWTSMOOS_PLAYER_FACING_HUD_GUARANTEE__ = { ok:true, id:ID, has:() => ({ health:!!$("[data-hud='health']"), targeting:!!$("[data-hud='targeting']"), x:!!$("[data-hud='x-action']"), r:!!$("[data-hud='r-action']"), quest:!!$("[data-hud='quest']"), inventory:!!$("[data-hud='inventory-button']") && !!$("[data-hud='inventory-panel']"), actionBar:!!$("[data-hud='action-bar']"), iconOnly:!!$(".icon-only-action-bar"), inventoryBagLink:!!$("[data-hud-link='inventory-bag']"), joystick:!!$("#joystick-container"), jump:!!$("#mobile-jump-button") }) };
  return root;
}
if (typeof window !== "undefined") queueMicrotask(installPlayerFacingHudGuarantee);
