// B"H
const { objectSchema, string, integer, bool, object, array } = require('./primitives.js');
function isBatchAction(name) { return /^(actionBatch|commandBatch|aiCommandBatch|testMatrix|parallelActionBatch|forEachActionBatch|retryAction|assertAction|policyGuard|destructiveIntentGate|snapshotBeforeAfter|awtsmoosCommandTree|merkavaCommandTree|aiWorkflowLang|commandTree|workflowRun|workflowValidate)/i.test(name); }
function batchSchema(name) {
	if (String(name).toLowerCase() === 'retryaction') return retrySchema();
	return objectSchema({ action:string(`Action name, e.g. ${name}.`), steps:array(stepSchema()), actions:array(stepSchema()), workflow:object('Workflow object, array, or JSON string.'), commandTree:object('Command tree object, array, or JSON string.'), tree:object('Tree object, array, or JSON string.'), do:array(stepSchema()), content:string('JSON carrier: array of steps or object with steps/actions/workflow/commandTree/tree/do.'), params:object('Object carrier with steps/actions/workflow/commandTree/tree/do.'), body:string('JSON carrier alias.'), query:string('JSON carrier alias.'), goal:string('JSON carrier alias.'), actionsJson:string('JSON array/object carrier.'), workflow64:string('Base64 JSON workflow carrier.'), steps64:string('Base64 JSON steps carrier.'), dryRun:bool('Return plan without executing.'), validateOnly:bool('Validate and return plan.'), stopOnError:bool('Stop on first failed step; default true.'), maxSteps:integer('Safety cap for total steps.'), maxInlineBytes:integer('Compaction threshold.'), vars:object('Variables available as $vars.name.'), policy:object('Execution policy options.') });
}
function retrySchema() { return objectSchema({ controlRequestId:string('Exact durable request id returned by tunnelRequestPending.'), originalControlRequestId:string('Compatibility alias for the durable request id.'), requestedAction:string('Original action named by the pending receipt.'), requestAction:string('Original action alias.'), resumeToken:string('Resume token returned by the pending receipt.'), params:object('Recovery carrier returned by next.params or retryPayload.'), params64:string('Base64 JSON recovery carrier.'), retryPayload:object('Complete retryPayload from the pending receipt.'), originalRequest:object('Original request carrier.'), request:object('Request carrier.') }); }
function stepSchema() { return objectSchema({ action:string('Tunnel action to call.'), type:string('Action alias.'), call:string('Action alias.'), payload:object('Payload for child action.'), with:object('Payload alias.'), saveAs:string('Save result under named key.'), id:string('Step id.'), if:object('Condition.'), then:array(object('Steps.')), else:array(object('Steps.')), do:array(object('Nested steps.')), parallel:array(object('Parallel branches.')), forEach:object('Loop spec.'), retry:object('Retry spec.'), retries:integer('Retry count.'), assert:object('Assertion condition.'), onError:array(object('Error recovery steps.')) }); }
module.exports = { isBatchAction, batchSchema, retrySchema, stepSchema };
