// B"H
function renderToolCatalogYaml({ version, actions, tools, guidance }) { const lines = ['BH: B\\"H', `version: ${yamlValue(version)}`]; addGuidance(lines, guidance); addActions(lines, actions); addTools(lines, tools); return lines.join('\n') + '\n'; }
function addGuidance(lines, guidance) { if (!guidance?.chatgpt) return; lines.push('guidance:', '  chatgpt:', `    preferredAction: ${yamlValue(guidance.chatgpt.preferredAction || 'chatgptSeasonSaveAndContinue')}`, '    workflow:'); for (const line of guidance.chatgpt.workflow) lines.push(`      - ${yamlValue(line)}`); }
function addActions(lines, actions = {}) { lines.push('actions:'); for (const [kind, names] of Object.entries(actions)) { lines.push(`  ${kind}:`); for (const name of names) lines.push(`    - ${yamlValue(name)}`); } }
function addTools(lines, tools = []) { lines.push('tools:'); for (const tool of tools) { lines.push(`  - name: ${yamlValue(tool.name)}`); lines.push(`    kind: ${yamlValue(tool.kind)}`); lines.push(`    description: ${yamlValue(tool.description)}`); lines.push('    parameters:'); lines.push(...yamlSchema(tool.parameters, 6)); } }
function yamlSchema(schema = {}, indent = 0) { const pad = ' '.repeat(indent), lines = [`${pad}type: ${yamlValue(schema.type || 'object')}`, `${pad}additionalProperties: ${schema.additionalProperties !== false}`]; if (schema.required?.length) { lines.push(`${pad}required:`); schema.required.forEach(item => lines.push(`${pad}  - ${yamlValue(item)}`)); } lines.push(`${pad}properties:`); for (const [key, prop] of Object.entries(schema.properties || {})) addProp(lines, pad, key, prop); return lines; }
function addProp(lines, pad, key, prop = {}) { lines.push(`${pad}  ${key}:`); lines.push(`${pad}    type: ${yamlValue(prop.type || 'string')}`); if (prop.description) lines.push(`${pad}    description: ${yamlValue(prop.description)}`); if (prop.items) lines.push(`${pad}    items: ${yamlValue(prop.items.type || 'object')}`); }
function yamlValue(value) { return JSON.stringify(String(value ?? '')); }
module.exports = { renderToolCatalogYaml, yamlSchema, yamlValue };
