//B"H
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const live = require('../platform/live.js');
const rate = require('../platform/rateLimit.js');
const search = require('../platform/search.js');
const follow = require('../platform/follow.js');
const ops = require('../platform/ops.js');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'awt-platform-ops-'));
const $i = { db: { directory: tmp } };
live.subscribeLiveChannel({ $i, aliasId: 'alice', channel: 'h1' });
live.setPresence({ $i, aliasId: 'alice', channel: 'h1', status: 'typing' });
const ev = live.publishLiveEvent({ $i, channel: 'h1', type: 'graph', actor: 'alice', payload: { id: 'g1' } });
assert.equal(live.replayLiveEvents({ $i, channel: 'h1', since: 0 }).at(-1).id, ev.id);
assert.equal(rate.checkRateLimit({ $i, subject: 'alice', limit: 2 }).allowed, true);
assert.equal(rate.checkRateLimit({ $i, subject: 'alice', limit: 2 }).allowed, true);
assert.equal(rate.checkRateLimit({ $i, subject: 'alice', limit: 2 }).allowed, false);
search.indexSearchDocument({ $i, domain: 'post', id: 'p1', text: 'Awtsmoos beautiful graph search', entity: { type: 'post' } });
assert.equal(search.searchPacked({ $i, q: 'beautiful graph' })[0].id, 'p1');
assert.equal(follow.setRelationship({ $i, fromAlias: 'alice', toAlias: 'bob', type: 'follow' }).success.type, 'follow');
assert.equal(follow.listRelationships({ $i, aliasId: 'alice' }).success.length, 1);
assert.equal(ops.registerMedia({ $i, mediaId: 'm1', aliasId: 'alice', metadata: { mime: 'image/png' } }).status, 'registered');
assert.equal(ops.attachMedia({ $i, mediaId: 'm1', entity: { type: 'post', id: 'p1' } }).mediaId, 'm1');
assert.equal(ops.createModerationRecord({ $i, type: 'report', actor: 'bob', reason: 'test' }).status, 'open');
assert.equal(ops.enqueueJob({ $i, type: 'compact', payload: {} }).status, 'queued');
assert.equal(ops.recordMetric({ $i, name: 'fanout', value: 7 }).value, 7);
assert.equal(ops.cacheSet({ $i, key: 'feed:alice', value: { ok: true } }).value.ok, true);
assert.equal(ops.syncOp({ $i, aliasId: 'alice', op: 'draft.save' }).op, 'draft.save');
assert.equal(ops.compilePermission({ $i, subject: 'alice', resource: 'h1', rules: { allow: true } }).allow, true);
assert.equal(ops.federationImport({ $i, remoteHeichel: 'remote-h', signedPayload: { sig: 'demo' } }).remoteHeichel, 'remote-h');
fs.rmSync(tmp, { recursive: true, force: true });
console.log('B"H platformOps.test passed');
