// B"H
/** @file RuntimeVisualAudit.js @description Runtime proof: binding safety, closed animals, grounded trees, textures, and living ecosystem. */
function materialsOf(object) { if (!object || !object.material) return []; return Array.isArray(object.material) ? object.material : [object.material]; }
function dataOf(object) { return object && object.userData ? object.userData : {}; }
function materialData(material) { return material && material.userData ? material.userData : {}; }
function badMat(material) { const data = materialData(material); return Boolean(material && !material.map && !material.vertexColors && !data.proceduralTextureKit && !data.awtsmoosMaterialIntent && !data.noSolidColor && material.type !== "MeshBasicMaterial"); }
function sceneOf(context) { const olam = context && context.olam ? context.olam : context; return context && context.scene ? context.scene : olam && olam.scene ? olam.scene : null; }
function olamOf(context) { return context && context.olam ? context.olam : context; }
function isLeafPlane(object) { const name = String(object && object.name ? object.name : "").toLowerCase(); const geometry = object && object.geometry ? object.geometry : {}; return name.includes("leaf") && geometry.type === "PlaneGeometry"; }
function emptyStats() { return { skinnedAnimalRoots:0, skinnedAnimalMeshes:0, skinnedAnimalMissingSkinAttributes:0, animalBonesTotal:0, possibleNonSkinnedAnimalParts:0, attachmentMaterials:0, multiMaterialAnimals:0, bodyPartMaterialMeshes:0, birdActors:0, airborneAnimals:0, attackDifficultAnimals:0, lifeRuntimes:0, livingEcosystem:false, phasesComplete:0, brainActors:0, memoryActors:0, needActors:0, bindingUnsafeAnimals:0, skinnedMixerTargetWrong:0, animalOpenSurfaceWarnings:0, debugNameLeaks:0, floatingTrees:0, groundedTrees:0, approvedTrees:0, lastLifeSummary:null }; }
function animalStats(object, stats) { const data = dataOf(object), name = String(object.name || ""); if (name.includes("true_skinned_procedural")) stats.debugNameLeaks++; if (data.lifeRuntime) stats.lifeRuntimes++; if (data.lifeSummary) { stats.livingEcosystem = true; stats.phasesComplete = Math.max(stats.phasesComplete, data.lifeSummary.phasesComplete || 0); stats.lastLifeSummary = data.lifeSummary; } if (data.proceduralSkinnedAnimal) { stats.skinnedAnimalRoots++; stats.attachmentMaterials += data.attachmentMaterialCount || 0; if (data.multiMaterialAnimal) stats.multiMaterialAnimals++; if (data.species === "bird") stats.birdActors++; if (data.airborne) stats.airborneAnimals++; if (data.attackDifficult) stats.attackDifficultAnimals++; if (data.brain) stats.brainActors++; if (data.memory) stats.memoryActors++; if (data.needs) stats.needActors++; if (data.bindingSafe === false) stats.bindingUnsafeAnimals++; if (data.animationMixerTarget && data.animationMixerTarget !== "skinnedMesh") stats.skinnedMixerTargetWrong++; if (!data.surfaceMetadata || !data.surfaceMetadata.closedSurface) stats.animalOpenSurfaceWarnings++; } if (data.awtsmoosSkinnedMesh) { stats.skinnedAnimalMeshes++; stats.animalBonesTotal += data.boneCount || 0; if (!data.skinAttributeProof) stats.skinnedAnimalMissingSkinAttributes++; } if (data.animalAttachment) stats.bodyPartMaterialMeshes++; if ((data.wildlifeActor || name.toLowerCase().includes("animal") || name.toLowerCase().includes("wildlife")) && !data.proceduralSkinnedAnimal && !data.awtsmoosSkinnedMesh && object.parent && data.selectableCombatTarget) stats.possibleNonSkinnedAnimalParts++; }
function treeStats(object, stats) { const data = dataOf(object); if (!data.proceduralCoreTree) return; if (data.onlyApprovedTreeSource) stats.approvedTrees++; const proof = data.treeGroundingProof; if (!proof) return; stats.groundedTrees++; if (Math.abs(proof.floatingError || 0) > .08) stats.floatingTrees++; }
export async function ensureRuntimeVisualAudit(context = {}) {
  const olam = olamOf(context), scene = sceneOf(context); if (!scene) return null;
  let meshes = 0, untextured = 0, leafPlanes = 0; const bad = [], stats = emptyStats();
  scene.traverse(object => { animalStats(object, stats); treeStats(object, stats); if (!object.isMesh) return; meshes++; const name = String(object.name || ""); if (isLeafPlane(object)) { leafPlanes++; bad.push({ name, type:"leafPlane" }); } for (const material of materialsOf(object)) { if (badMat(material)) { untextured++; bad.push({ name, type:"untextured", mat:material.name || material.type }); break; } } });
  const report = { at:Date.now(), meshes, untextured, leafPlanes, skinnedAnimals:stats.skinnedAnimalRoots, skinnedAnimalMeshes:stats.skinnedAnimalMeshes, nonSkinnedAnimals:stats.possibleNonSkinnedAnimalParts, animalBonesTotal:stats.animalBonesTotal, missingSkinAttributes:stats.skinnedAnimalMissingSkinAttributes, bindingUnsafeAnimals:stats.bindingUnsafeAnimals, skinnedMixerTargetWrong:stats.skinnedMixerTargetWrong, animalOpenSurfaceWarnings:stats.animalOpenSurfaceWarnings, debugNameLeaks:stats.debugNameLeaks, bodyPartMaterialMeshes:stats.bodyPartMaterialMeshes, attachmentMaterials:stats.attachmentMaterials, multiMaterialAnimals:stats.multiMaterialAnimals, birdActors:stats.birdActors, airborneAnimals:stats.airborneAnimals, attackDifficultAnimals:stats.attackDifficultAnimals, approvedTrees:stats.approvedTrees, groundedTrees:stats.groundedTrees, floatingTrees:stats.floatingTrees, lifeRuntimes:stats.lifeRuntimes, livingEcosystem:stats.livingEcosystem, phasesComplete:stats.phasesComplete, brainActors:stats.brainActors, memoryActors:stats.memoryActors, needActors:stats.needActors, lifeSummary:stats.lastLifeSummary, grounding:olam ? olam.__finalGroundingReport || null : null, bad:bad.slice(0,60) };
  if (olam) olam.__AWTSMOOS_RUNTIME_VISUAL_AUDIT__ = report;
  const logs = typeof globalThis !== "undefined" && globalThis.__AWTSMOOS_VISUAL_AUDIT_LOGS__ === true;
  if (logs) console.info("B\"H | RUNTIME_VISUAL_AUDIT", report);
  return report;
}
export default { ensureRuntimeVisualAudit };
