// B"H
/** @file VillageEcologyRealityLayer.js @description Grounded ecology props with no cone/blob tree fallback geometry. */
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { ecologyAt, ecologyRand, ecologyStats } from "../../../../dvarim/nature/villagePicture/VillageEcologyAtlas.js?compact=true&v=village-ecology-atlas-20260612-bh1";
import { ecologyMaterial, ecologyMaterialStats } from "../../../../dvarim/nature/villagePicture/EcologySpecialMaterials.js?compact=true&v=zone-reality-20260614-bh812";
import { yAt, ecologyKind, roadMask, sealDecor } from "./VillagePolishGround.js?compact=true&v=awtsmoos-polish-ground-20260614-bh2";
const KEY = "__awtsmoosVillageEcologyRealityLayer", geos = new Map();
function geo(kind) { if (geos.has(kind)) return geos.get(kind); let g; if (kind === "cylinder") g = new THREE.CylinderGeometry(.5,.5,1,10); else if (kind === "sphere") g = new THREE.SphereGeometry(.5,10,8); else g = new THREE.BoxGeometry(1,1,1); geos.set(kind,g); return g; }
function seal(root) { if (!root) return root; const mark = c => { if (!c.userData) c.userData = {}; Object.assign(c.userData, { villageDecor:true, ecologyDecor:true, skipOctree:true, noOctree:true, skipRaycast:true }); }; if (typeof root.traverse === "function") root.traverse(mark); else mark(root); return root; }
function mesh(kind,mat,x,y,z,s,r=0) { const m = new THREE.Mesh(geo(kind), ecologyMaterial(mat,{simple:true,size:96,repeat:2})); m.position.set(x,y+s[1]*.5,z); m.scale.set(s[0],s[1],s[2]); m.rotation.set(0,r,0); m.receiveShadow = true; return seal(m); }
function veg(group,x,z,type) { group.add(mesh("cylinder",type,x,.02,z,[.11,.4,.11])); group.add(mesh("sphere","cabbageLeaf",x,.36,z,[.2,.1,.2])); }
function gardenBed(root,olam,x,z,rot=0) { const bed = new THREE.Group(); bed.position.set(x,yAt(olam,x,z)+.02,z); bed.rotation.y = rot; for (let i=-4;i<=4;i++) veg(bed,i*.3,Math.sin(i)*.08,i%3===0?"carrotSkin":i%3===1?"potatoSkin":"onionSkin"); bed.add(mesh("box","linenFabric",0,.01,.58,[3,.05,.12])); bed.add(mesh("box","linenFabric",0,.01,-.58,[3,.05,.12])); root.add(seal(bed)); }
function rockCluster(root,olam,x,z) { if (roadMask(x,z,4)>.45) return; const e=ecologyAt(x,z), base=yAt(olam,x,z)+.02, count=3+Math.floor(e.stone*5); for (let i=0;i<count;i++) { const a=i*2.399,r=.25+i*.18; root.add(mesh("sphere",i%2?"graniteRock":"slateStone",x+Math.cos(a)*r,base,z+Math.sin(a)*r,[.45+e.stone*.42,.25+e.stone*.22,.36],a)); if(e.moisture+e.shade>1.15) root.add(mesh("sphere","mossPatch",x+Math.cos(a)*(r+.18),base+.08,z+Math.sin(a)*(r+.18),[.2,.06,.18],a)); } }
function barkLog(root,olam,x,z,pine=false) { const y=yAt(olam,x,z)+.08,a=ecologyRand(x,z,8)*Math.PI; const m=mesh("cylinder",pine?"barkPine":"barkOak",x,y,z,[.18,1.35,.18],a); m.rotation.z=Math.PI/2; root.add(m); if(ecologyAt(x,z).moisture>.48) root.add(mesh("sphere","mushroomCap",x+.42,y+.05,z+.18,[.16,.13,.16],a)); }
function clothBundles(root,olam,x,z) { const y=yAt(olam,x,z)+.02; root.add(mesh("box","cottonFiber",x,y,z,[.72,.38,.48],.2)); root.add(mesh("box","linenFabric",x+.72,y,z+.18,[.66,.24,.42],-.15)); }
function mineralAccent(root,olam,x,z) { const y=yAt(olam,x,z)+.03; root.add(mesh("box","marbleWhite",x,y,z,[.45,.18,.45],.4)); if(ecologyRand(x,z,22)>.72) root.add(mesh("sphere","goldHammered",x+.28,y+.15,z+.15,[.12,.08,.12])); }
function flowerPatch(root,olam,x,z) { if(roadMask(x,z,3.8)>.4) return; const e=ecologyAt(x,z),base=yAt(olam,x,z)+.03,count=5+Math.floor(e.fertility*10); for(let i=0;i<count;i++){ const a=i*2.399,r=.12+i*.06; root.add(mesh("cylinder","cabbageLeaf",x+Math.cos(a)*r,base,z+Math.sin(a)*r,[.025,.28,.025],a)); root.add(mesh("sphere",i%2?"daisyPetal":"lavenderFlower",x+Math.cos(a)*r,base+.28,z+Math.sin(a)*r,[.1,.045,.1],a)); } }
function zone(root,olam,x,z) { const kind=ecologyKind(x,z),e=ecologyAt(x,z),jx=x+(ecologyRand(x,z,2)-.5)*10,jz=z+(ecologyRand(x,z,3)-.5)*10; if(kind==="village-square") return; if(kind==="sacred-grove"){barkLog(root,olam,jx,jz,e.seed>.5); flowerPatch(root,olam,jx+1.2,jz-.8); return;} if(kind==="orchard"){gardenBed(root,olam,jx,jz,e.seed*Math.PI); clothBundles(root,olam,jx+1.2,jz-.7); return;} if(kind==="trampled-road-edge"){if(e.stone>.45)rockCluster(root,olam,jx,jz); return;} if(e.fertility>.62)flowerPatch(root,olam,jx,jz); if(e.stone>.66)rockCluster(root,olam,jx,jz); if(e.shade>.68&&e.moisture>.48)barkLog(root,olam,jx+1.2,jz-.8,e.seed>.5); if(e.traffic>.64)clothBundles(root,olam,jx-1.4,jz+.6); if(e.mineral>.78)mineralAccent(root,olam,jx+.9,jz-.4); }
function build(olam) { const root=new THREE.Group(); root.name="village_ecology_zone_aware_reality_layer"; for(let x=-190;x<=190;x+=32) for(let z=-105;z<=105;z+=28) zone(root,olam,x,z); Object.assign(root.userData,{ecologyStats:ecologyStats(),materialStats:ecologyMaterialStats(),counts:{children:root.children.length,zoneAware:true,noConeFallback:true}}); return sealDecor(seal(root),{zoneAwareEcology:true}); }
export async function ensureVillageEcologyRealityLayer(context={}) { const olam=context.olam || context, scene=context.scene || (olam ? olam.scene : null); if(!scene || !olam) return null; if(olam[KEY]) return olam[KEY]; const root=build(olam); scene.add(root); olam[KEY]=root; return root; }
