// B"H
/** @file VillageEcologyRealityLayer.js @description Chapter 960: coherent ecology layer with local garden grounding fixed. */
import * as THREE from "/games/scripts/build/three.module.js";
import TerrainMath from "../../../../dvarim/terrain/core/TerrainMath.js";
import { ecologyAt, ecologyRand, ecologyStats } from "../../../../dvarim/nature/villagePicture/VillageEcologyAtlas.js?v=village-ecology-atlas-20260612-bh1";
import { ecologyMaterial, ecologyMaterialStats } from "../../../../dvarim/nature/villagePicture/EcologySpecialMaterials.js?v=complete-v3-ecology-materials-20260612-bh3";
const KEY = "__awtsmoosVillageEcologyRealityLayer";
const geos = new Map();
function geo(kind) { if (geos.has(kind)) return geos.get(kind); const g = kind === "cylinder" ? new THREE.CylinderGeometry(.5, .5, 1, 10) : kind === "sphere" ? new THREE.SphereGeometry(.5, 10, 8) : kind === "cone" ? new THREE.ConeGeometry(.5, 1, 10) : new THREE.BoxGeometry(1, 1, 1); geos.set(kind, g); return g; }
function yAt(olam, x, z) { const law = olam?.awtsmoosTerrainLaw; if (!law?.data) return 0; return (law.position?.y || 0) + TerrainMath.calculateHeightAt(x - (law.position?.x || 0), z - (law.position?.z || 0), law.data); }
function seal(root) { root.traverse?.(c => Object.assign(c.userData ||= {}, { villageDecor: true, ecologyDecor: true, skipOctree: true, noOctree: true, skipRaycast: true })); return root; }
function mesh(kind, mat, x, y, z, s, r = 0, simple = false) { const m = new THREE.Mesh(geo(kind), ecologyMaterial(mat, { simple, repeat: 2 })); m.position.set(x, y + s[1] * .5, z); m.scale.set(s[0], s[1], s[2]); m.rotation.set(0, r, 0); m.castShadow = false; m.receiveShadow = true; return seal(m); }
function gardenVeg(group, x, z, type) { group.add(mesh("cylinder", type, x, .02, z, [.12, .42, .12], 0, false)); group.add(mesh("sphere", "cabbageLeaf", x, .39, z, [.2, .1, .2], 0, true)); }
function gardenBed(root, olam, x, z, rot = 0) { const bed = new THREE.Group(); bed.position.set(x, yAt(olam, x, z) + .02, z); bed.rotation.y = rot; for (let i = -3; i <= 3; i++) gardenVeg(bed, i * .34, Math.sin(i) * .08, i % 3 === 0 ? "carrotSkin" : i % 3 === 1 ? "potatoSkin" : "onionSkin"); bed.add(mesh("box", "linenFabric", 0, .01, .52, [2.7, .05, .12], 0, true)); bed.add(mesh("box", "linenFabric", 0, .01, -.52, [2.7, .05, .12], 0, true)); root.add(seal(bed)); }
function rockCluster(root, olam, x, z) { const e = ecologyAt(x, z), base = yAt(olam, x, z) + .02, count = 3 + Math.floor(e.stone * 5); for (let i = 0; i < count; i++) { const a = i * 2.399, r = .25 + i * .18, mat = i % 2 ? "graniteRock" : "slateStone"; root.add(mesh("sphere", mat, x + Math.cos(a) * r, base, z + Math.sin(a) * r, [.45 + e.stone * .42, .25 + e.stone * .22, .36], a)); if (e.moisture + e.shade > 1.15) root.add(mesh("sphere", "mossPatch", x + Math.cos(a) * (r + .18), base + .08, z + Math.sin(a) * (r + .18), [.2, .06, .18], a, true)); } }
function barkLog(root, olam, x, z, pine = false) { const y = yAt(olam, x, z) + .08, a = ecologyRand(x, z, 8) * Math.PI; const m = mesh("cylinder", pine ? "barkPine" : "barkOak", x, y, z, [.18, 1.25, .18], a); m.rotation.z = Math.PI / 2; root.add(m); if (ecologyAt(x, z).moisture > .55) root.add(mesh("sphere", "mushroomCap", x + .42, y + .05, z + .18, [.16, .13, .16], a, false)); }
function clothBundles(root, olam, x, z) { const y = yAt(olam, x, z) + .02; root.add(mesh("box", "cottonFiber", x, y, z, [.72, .38, .48], .2, false)); root.add(mesh("box", "linenFabric", x + .72, y, z + .18, [.66, .24, .42], -.15, false)); }
function mineralAccent(root, olam, x, z) { const y = yAt(olam, x, z) + .03; root.add(mesh("box", "marbleWhite", x, y, z, [.45, .18, .45], .4, false)); if (ecologyRand(x, z, 22) > .72) root.add(mesh("sphere", "goldHammered", x + .28, y + .15, z + .15, [.12, .08, .12], 0, false)); }
function flowerPatch(root, olam, x, z) { const e = ecologyAt(x, z), base = yAt(olam, x, z) + .03, count = 5 + Math.floor(e.fertility * 10); for (let i = 0; i < count; i++) { const a = i * 2.399, r = .12 + i * .06; root.add(mesh("cylinder", "cabbageLeaf", x + Math.cos(a) * r, base, z + Math.sin(a) * r, [.025, .28, .025], a, true)); root.add(mesh("sphere", i % 2 ? "daisyPetal" : "lavenderFlower", x + Math.cos(a) * r, base + .28, z + Math.sin(a) * r, [.1, .045, .1], a, true)); } }
function build(olam) { const root = new THREE.Group(); root.name = "village_ecology_reality_atlas_layer"; Object.assign(root.userData, { ecologyStats: ecologyStats(), materialStats: ecologyMaterialStats() }); let gardens = 0, rocks = 0, logs = 0, cloth = 0, minerals = 0, flowers = 0; for (let x = -190; x <= 190; x += 28) for (let z = -105; z <= 105; z += 24) { const e = ecologyAt(x, z), jx = x + (ecologyRand(x, z, 2) - .5) * 10, jz = z + (ecologyRand(x, z, 3) - .5) * 10; if (e.fertility > .62 && e.traffic < .45) { flowerPatch(root, olam, jx, jz); flowers++; } if (e.stone > .66) { rockCluster(root, olam, jx, jz); rocks++; } if (e.shade > .68 && e.moisture > .48) { barkLog(root, olam, jx + 1.2, jz - .8, e.seed > .5); logs++; } if (e.traffic > .52 && e.soil > .48 && gardens < 10) { gardenBed(root, olam, jx, jz, e.seed * Math.PI); gardens++; } if (e.traffic > .64 && cloth < 8) { clothBundles(root, olam, jx - 1.4, jz + .6); cloth++; } if (e.mineral > .78 && minerals < 12) { mineralAccent(root, olam, jx + .9, jz - .4); minerals++; } } root.userData.counts = { gardens, rocks, logs, cloth, minerals, flowers }; return seal(root); }
export async function ensureVillageEcologyRealityLayer(context = {}) { const olam = context.olam || context, scene = context.scene || olam.scene; if (!scene || !olam || olam[KEY]) return olam?.[KEY] || null; const root = build(olam); scene.add(root); olam[KEY] = root; return root; }
