// B"H
/** LivingWorldRegistry: many named vessels of emergent civilization, not a numbered gimmick. */
export const LIVING_WORLD_IDEAS = Object.freeze([
  Object.freeze({ index:1, id:'long_term_ambitions', domain:'society', title:'Long Term Ambitions' }),
  Object.freeze({ index:2, id:'friendships', domain:'society', title:'Friendships' }),
  Object.freeze({ index:3, id:'rivalries', domain:'society', title:'Rivalries' }),
  Object.freeze({ index:4, id:'marriage', domain:'society', title:'Marriage' }),
  Object.freeze({ index:5, id:'births', domain:'society', title:'Births' }),
  Object.freeze({ index:6, id:'elder_passing', domain:'society', title:'Elder Passing' }),
  Object.freeze({ index:7, id:'leadership_succession', domain:'society', title:'Leadership Succession' }),
  Object.freeze({ index:8, id:'community_voting', domain:'society', title:'Community Voting' }),
  Object.freeze({ index:9, id:'apprentice_mastery', domain:'society', title:'Apprentice Mastery' }),
  Object.freeze({ index:10, id:'family_lineages', domain:'society', title:'Family Lineages' }),
  Object.freeze({ index:11, id:'hospitality_circles', domain:'society', title:'Hospitality Circles' }),
  Object.freeze({ index:12, id:'neighbor_favors', domain:'society', title:'Neighbor Favors' }),
  Object.freeze({ index:13, id:'conflict_mediation', domain:'society', title:'Conflict Mediation' }),
  Object.freeze({ index:14, id:'local_courts', domain:'society', title:'Local Courts' }),
  Object.freeze({ index:15, id:'public_honors', domain:'society', title:'Public Honors' }),
  Object.freeze({ index:16, id:'shame_and_forgiveness', domain:'society', title:'Shame And Forgiveness' }),
  Object.freeze({ index:17, id:'orphan_support', domain:'society', title:'Orphan Support' }),
  Object.freeze({ index:18, id:'elder_councils', domain:'society', title:'Elder Councils' }),
  Object.freeze({ index:19, id:'youth_clubs', domain:'society', title:'Youth Clubs' }),
  Object.freeze({ index:20, id:'guild_charters', domain:'society', title:'Guild Charters' }),
  Object.freeze({ index:21, id:'public_announcements', domain:'society', title:'Public Announcements' }),
  Object.freeze({ index:22, id:'communal_kitchens', domain:'society', title:'Communal Kitchens' }),
  Object.freeze({ index:23, id:'shared_childcare', domain:'society', title:'Shared Childcare' }),
  Object.freeze({ index:24, id:'matchmaking_networks', domain:'society', title:'Matchmaking Networks' }),
  Object.freeze({ index:25, id:'neighborhood_identity', domain:'society', title:'Neighborhood Identity' }),
  Object.freeze({ index:26, id:'belief_formation', domain:'cognition', title:'Belief Formation' }),
  Object.freeze({ index:27, id:'mistakes', domain:'cognition', title:'Mistakes' }),
  Object.freeze({ index:28, id:'rumor_distortion', domain:'cognition', title:'Rumor Distortion' }),
  Object.freeze({ index:29, id:'emotional_places', domain:'cognition', title:'Emotional Places' }),
  Object.freeze({ index:30, id:'personal_fears', domain:'cognition', title:'Personal Fears' }),
  Object.freeze({ index:31, id:'curiosity', domain:'cognition', title:'Curiosity' }),
  Object.freeze({ index:32, id:'personality_drift', domain:'cognition', title:'Personality Drift' }),
  Object.freeze({ index:33, id:'learning_by_observation', domain:'cognition', title:'Learning By Observation' }),
  Object.freeze({ index:34, id:'social_influence', domain:'cognition', title:'Social Influence' }),
  Object.freeze({ index:35, id:'emergent_traditions', domain:'cognition', title:'Emergent Traditions' }),
  Object.freeze({ index:36, id:'attention_span', domain:'cognition', title:'Attention Span' }),
  Object.freeze({ index:37, id:'trust_calibration', domain:'cognition', title:'Trust Calibration' }),
  Object.freeze({ index:38, id:'memory_decay', domain:'cognition', title:'Memory Decay' }),
  Object.freeze({ index:39, id:'dream_reports', domain:'cognition', title:'Dream Reports' }),
  Object.freeze({ index:40, id:'mood_contagion', domain:'cognition', title:'Mood Contagion' }),
  Object.freeze({ index:41, id:'habit_formation', domain:'cognition', title:'Habit Formation' }),
  Object.freeze({ index:42, id:'secret_keeping', domain:'cognition', title:'Secret Keeping' }),
  Object.freeze({ index:43, id:'surprise_reactions', domain:'cognition', title:'Surprise Reactions' }),
  Object.freeze({ index:44, id:'goal_reprioritization', domain:'cognition', title:'Goal Reprioritization' }),
  Object.freeze({ index:45, id:'moral_reflection', domain:'cognition', title:'Moral Reflection' }),
  Object.freeze({ index:46, id:'gratitude_memory', domain:'cognition', title:'Gratitude Memory' }),
  Object.freeze({ index:47, id:'jealousy_cooling', domain:'cognition', title:'Jealousy Cooling' }),
  Object.freeze({ index:48, id:'confusion_recovery', domain:'cognition', title:'Confusion Recovery' }),
  Object.freeze({ index:49, id:'confidence_arcs', domain:'cognition', title:'Confidence Arcs' }),
  Object.freeze({ index:50, id:'wisdom_growth', domain:'cognition', title:'Wisdom Growth' }),
  Object.freeze({ index:51, id:'predator_prey', domain:'ecology', title:'Predator Prey' }),
  Object.freeze({ index:52, id:'insects', domain:'ecology', title:'Insects' }),
  Object.freeze({ index:53, id:'pollination', domain:'ecology', title:'Pollination' }),
  Object.freeze({ index:54, id:'forest_succession', domain:'ecology', title:'Forest Succession' }),
  Object.freeze({ index:55, id:'soil_fertility', domain:'ecology', title:'Soil Fertility' }),
  Object.freeze({ index:56, id:'territories', domain:'ecology', title:'Territories' }),
  Object.freeze({ index:57, id:'migration', domain:'ecology', title:'Migration' }),
  Object.freeze({ index:58, id:'river_drift', domain:'ecology', title:'River Drift' }),
  Object.freeze({ index:59, id:'erosion', domain:'ecology', title:'Erosion' }),
  Object.freeze({ index:60, id:'fire_ecology', domain:'ecology', title:'Fire Ecology' }),
  Object.freeze({ index:61, id:'mushroom_blooms', domain:'ecology', title:'Mushroom Blooms' }),
  Object.freeze({ index:62, id:'seed_spread', domain:'ecology', title:'Seed Spread' }),
  Object.freeze({ index:63, id:'bird_nesting', domain:'ecology', title:'Bird Nesting' }),
  Object.freeze({ index:64, id:'fish_spawning', domain:'ecology', title:'Fish Spawning' }),
  Object.freeze({ index:65, id:'animal_dens', domain:'ecology', title:'Animal Dens' }),
  Object.freeze({ index:66, id:'drought_stress', domain:'ecology', title:'Drought Stress' }),
  Object.freeze({ index:67, id:'flood_plains', domain:'ecology', title:'Flood Plains' }),
  Object.freeze({ index:68, id:'bee_health', domain:'ecology', title:'Bee Health' }),
  Object.freeze({ index:69, id:'fruit_seasons', domain:'ecology', title:'Fruit Seasons' }),
  Object.freeze({ index:70, id:'grass_recovery', domain:'ecology', title:'Grass Recovery' }),
  Object.freeze({ index:71, id:'compost_cycles', domain:'ecology', title:'Compost Cycles' }),
  Object.freeze({ index:72, id:'fallen_logs', domain:'ecology', title:'Fallen Logs' }),
  Object.freeze({ index:73, id:'pond_life', domain:'ecology', title:'Pond Life' }),
  Object.freeze({ index:74, id:'moonlit_wildlife', domain:'ecology', title:'Moonlit Wildlife' }),
  Object.freeze({ index:75, id:'habitat_restoration', domain:'ecology', title:'Habitat Restoration' }),
  Object.freeze({ index:76, id:'inflation', domain:'economy', title:'Inflation' }),
  Object.freeze({ index:77, id:'shortages', domain:'economy', title:'Shortages' }),
  Object.freeze({ index:78, id:'merchant_competition', domain:'economy', title:'Merchant Competition' }),
  Object.freeze({ index:79, id:'regional_specialties', domain:'economy', title:'Regional Specialties' }),
  Object.freeze({ index:80, id:'monopolies', domain:'economy', title:'Monopolies' }),
  Object.freeze({ index:81, id:'labor_markets', domain:'economy', title:'Labor Markets' }),
  Object.freeze({ index:82, id:'bottlenecks', domain:'economy', title:'Bottlenecks' }),
  Object.freeze({ index:83, id:'transport_costs', domain:'economy', title:'Transport Costs' }),
  Object.freeze({ index:84, id:'seasonal_prices', domain:'economy', title:'Seasonal Prices' }),
  Object.freeze({ index:85, id:'craft_reputation', domain:'economy', title:'Craft Reputation' }),
  Object.freeze({ index:86, id:'credit_tabs', domain:'economy', title:'Credit Tabs' }),
  Object.freeze({ index:87, id:'debt_forgiveness', domain:'economy', title:'Debt Forgiveness' }),
  Object.freeze({ index:88, id:'auction_stalls', domain:'economy', title:'Auction Stalls' }),
  Object.freeze({ index:89, id:'bulk_orders', domain:'economy', title:'Bulk Orders' }),
  Object.freeze({ index:90, id:'festival_demand', domain:'economy', title:'Festival Demand' }),
  Object.freeze({ index:91, id:'perishable_goods', domain:'economy', title:'Perishable Goods' }),
  Object.freeze({ index:92, id:'storage_fees', domain:'economy', title:'Storage Fees' }),
  Object.freeze({ index:93, id:'artisan_signatures', domain:'economy', title:'Artisan Signatures' }),
  Object.freeze({ index:94, id:'quality_grades', domain:'economy', title:'Quality Grades' }),
  Object.freeze({ index:95, id:'trade_rumors', domain:'economy', title:'Trade Rumors' }),
  Object.freeze({ index:96, id:'barter_webs', domain:'economy', title:'Barter Webs' }),
  Object.freeze({ index:97, id:'repair_economy', domain:'economy', title:'Repair Economy' }),
  Object.freeze({ index:98, id:'charity_redistribution', domain:'economy', title:'Charity Redistribution' }),
  Object.freeze({ index:99, id:'shipping_delays', domain:'economy', title:'Shipping Delays' }),
  Object.freeze({ index:100, id:'local_taxes', domain:'economy', title:'Local Taxes' }),
  Object.freeze({ index:101, id:'road_improvement', domain:'construction', title:'Road Improvement' }),
  Object.freeze({ index:102, id:'emergent_paths', domain:'construction', title:'Emergent Paths' }),
  Object.freeze({ index:103, id:'bridge_wear', domain:'construction', title:'Bridge Wear' }),
  Object.freeze({ index:104, id:'maintenance', domain:'construction', title:'Maintenance' }),
  Object.freeze({ index:105, id:'roof_storm_damage', domain:'construction', title:'Roof Storm Damage' }),
  Object.freeze({ index:106, id:'village_expansion', domain:'construction', title:'Village Expansion' }),
  Object.freeze({ index:107, id:'neighborhood_identities', domain:'construction', title:'Neighborhood Identities' }),
  Object.freeze({ index:108, id:'public_gardens', domain:'construction', title:'Public Gardens' }),
  Object.freeze({ index:109, id:'community_storage', domain:'construction', title:'Community Storage' }),
  Object.freeze({ index:110, id:'irrigation', domain:'construction', title:'Irrigation' }),
  Object.freeze({ index:111, id:'well_digging', domain:'construction', title:'Well Digging' }),
  Object.freeze({ index:112, id:'lamp_posts', domain:'construction', title:'Lamp Posts' }),
  Object.freeze({ index:113, id:'bench_placement', domain:'construction', title:'Bench Placement' }),
  Object.freeze({ index:114, id:'market_awnings', domain:'construction', title:'Market Awnings' }),
  Object.freeze({ index:115, id:'school_expansion', domain:'construction', title:'School Expansion' }),
  Object.freeze({ index:116, id:'fence_repair', domain:'construction', title:'Fence Repair' }),
  Object.freeze({ index:117, id:'stone_paving', domain:'construction', title:'Stone Paving' }),
  Object.freeze({ index:118, id:'drainage_ditches', domain:'construction', title:'Drainage Ditches' }),
  Object.freeze({ index:119, id:'courtyard_upgrades', domain:'construction', title:'Courtyard Upgrades' }),
  Object.freeze({ index:120, id:'sukkah_frames', domain:'construction', title:'Sukkah Frames' }),
  Object.freeze({ index:121, id:'workshop_additions', domain:'construction', title:'Workshop Additions' }),
  Object.freeze({ index:122, id:'signposts', domain:'construction', title:'Signposts' }),
  Object.freeze({ index:123, id:'public_notice_boards', domain:'construction', title:'Public Notice Boards' }),
  Object.freeze({ index:124, id:'shade_trees', domain:'construction', title:'Shade Trees' }),
  Object.freeze({ index:125, id:'safe_crossings', domain:'construction', title:'Safe Crossings' }),
  Object.freeze({ index:126, id:'cloth', domain:'physics', title:'Cloth' }),
  Object.freeze({ index:127, id:'rope', domain:'physics', title:'Rope' }),
  Object.freeze({ index:128, id:'currents', domain:'physics', title:'Currents' }),
  Object.freeze({ index:129, id:'turbulence', domain:'physics', title:'Turbulence' }),
  Object.freeze({ index:130, id:'snow', domain:'physics', title:'Snow' }),
  Object.freeze({ index:131, id:'mud', domain:'physics', title:'Mud' }),
  Object.freeze({ index:132, id:'sand', domain:'physics', title:'Sand' }),
  Object.freeze({ index:133, id:'footprints', domain:'physics', title:'Footprints' }),
  Object.freeze({ index:134, id:'stacking', domain:'physics', title:'Stacking' }),
  Object.freeze({ index:135, id:'collapse', domain:'physics', title:'Collapse' }),
  Object.freeze({ index:136, id:'cart_suspension', domain:'physics', title:'Cart Suspension' }),
  Object.freeze({ index:137, id:'door_weight', domain:'physics', title:'Door Weight' }),
  Object.freeze({ index:138, id:'cloth_drying', domain:'physics', title:'Cloth Drying' }),
  Object.freeze({ index:139, id:'water_splash', domain:'physics', title:'Water Splash' }),
  Object.freeze({ index:140, id:'bucket_slosh', domain:'physics', title:'Bucket Slosh' }),
  Object.freeze({ index:141, id:'lantern_sway', domain:'physics', title:'Lantern Sway' }),
  Object.freeze({ index:142, id:'smoke_lift', domain:'physics', title:'Smoke Lift' }),
  Object.freeze({ index:143, id:'dust_trails', domain:'physics', title:'Dust Trails' }),
  Object.freeze({ index:144, id:'leaf_piles', domain:'physics', title:'Leaf Piles' }),
  Object.freeze({ index:145, id:'grain_pouring', domain:'physics', title:'Grain Pouring' }),
  Object.freeze({ index:146, id:'kneading_dough', domain:'physics', title:'Kneading Dough' }),
  Object.freeze({ index:147, id:'object_warmth', domain:'physics', title:'Object Warmth' }),
  Object.freeze({ index:148, id:'rain_drips', domain:'physics', title:'Rain Drips' }),
  Object.freeze({ index:149, id:'wind_chimes', domain:'physics', title:'Wind Chimes' }),
  Object.freeze({ index:150, id:'wagon_ruts', domain:'physics', title:'Wagon Ruts' }),
  Object.freeze({ index:151, id:'micro_expressions', domain:'animation', title:'Micro Expressions' }),
  Object.freeze({ index:152, id:'eye_contact', domain:'animation', title:'Eye Contact' }),
  Object.freeze({ index:153, id:'idle_talks', domain:'animation', title:'Idle Talks' }),
  Object.freeze({ index:154, id:'weight_shift', domain:'animation', title:'Weight Shift' }),
  Object.freeze({ index:155, id:'adaptive_gait', domain:'animation', title:'Adaptive Gait' }),
  Object.freeze({ index:156, id:'reaching', domain:'animation', title:'Reaching' }),
  Object.freeze({ index:157, id:'gestures', domain:'animation', title:'Gestures' }),
  Object.freeze({ index:158, id:'child_motion', domain:'animation', title:'Child Motion' }),
  Object.freeze({ index:159, id:'elder_motion', domain:'animation', title:'Elder Motion' }),
  Object.freeze({ index:160, id:'emotion_blending', domain:'animation', title:'Emotion Blending' }),
  Object.freeze({ index:161, id:'prayer_sway', domain:'animation', title:'Prayer Sway' }),
  Object.freeze({ index:162, id:'learning_posture', domain:'animation', title:'Learning Posture' }),
  Object.freeze({ index:163, id:'carrying_weight', domain:'animation', title:'Carrying Weight' }),
  Object.freeze({ index:164, id:'tool_handling', domain:'animation', title:'Tool Handling' }),
  Object.freeze({ index:165, id:'greeting_variations', domain:'animation', title:'Greeting Variations' }),
  Object.freeze({ index:166, id:'fatigue', domain:'animation', title:'Fatigue' }),
  Object.freeze({ index:167, id:'crowd_avoidance', domain:'animation', title:'Crowd Avoidance' }),
  Object.freeze({ index:168, id:'umbrella_posture', domain:'animation', title:'Umbrella Posture' }),
  Object.freeze({ index:169, id:'running_starts', domain:'animation', title:'Running Starts' }),
  Object.freeze({ index:170, id:'turn_anticipation', domain:'animation', title:'Turn Anticipation' }),
  Object.freeze({ index:171, id:'head_tracking', domain:'animation', title:'Head Tracking' }),
  Object.freeze({ index:172, id:'hand_tremor', domain:'animation', title:'Hand Tremor' }),
  Object.freeze({ index:173, id:'breathing', domain:'animation', title:'Breathing' }),
  Object.freeze({ index:174, id:'laugh_response', domain:'animation', title:'Laugh Response' }),
  Object.freeze({ index:175, id:'bowing_respect', domain:'animation', title:'Bowing Respect' }),
  Object.freeze({ index:176, id:'positional_talk', domain:'audio', title:'Positional Talk' }),
  Object.freeze({ index:177, id:'echo', domain:'audio', title:'Echo' }),
  Object.freeze({ index:178, id:'wind_trees', domain:'audio', title:'Wind Trees' }),
  Object.freeze({ index:179, id:'ambience_layers', domain:'audio', title:'Ambience Layers' }),
  Object.freeze({ index:180, id:'indoor_acoustics', domain:'audio', title:'Indoor Acoustics' }),
  Object.freeze({ index:181, id:'footstep_materials', domain:'audio', title:'Footstep Materials' }),
  Object.freeze({ index:182, id:'crowd_murmur', domain:'audio', title:'Crowd Murmur' }),
  Object.freeze({ index:183, id:'animal_calls', domain:'audio', title:'Animal Calls' }),
  Object.freeze({ index:184, id:'music_motifs', domain:'audio', title:'Music Motifs' }),
  Object.freeze({ index:185, id:'prayer_acoustics', domain:'audio', title:'Prayer Acoustics' }),
  Object.freeze({ index:186, id:'market_calls', domain:'audio', title:'Market Calls' }),
  Object.freeze({ index:187, id:'distant_bells', domain:'audio', title:'Distant Bells' }),
  Object.freeze({ index:188, id:'rain_on_roofs', domain:'audio', title:'Rain On Roofs' }),
  Object.freeze({ index:189, id:'floor_creaks', domain:'audio', title:'Floor Creaks' }),
  Object.freeze({ index:190, id:'page_turning', domain:'audio', title:'Page Turning' }),
  Object.freeze({ index:191, id:'fire_crackle', domain:'audio', title:'Fire Crackle' }),
  Object.freeze({ index:192, id:'wagon_wheels', domain:'audio', title:'Wagon Wheels' }),
  Object.freeze({ index:193, id:'tool_taps', domain:'audio', title:'Tool Taps' }),
  Object.freeze({ index:194, id:'muffled_rooms', domain:'audio', title:'Muffled Rooms' }),
  Object.freeze({ index:195, id:'water_flow', domain:'audio', title:'Water Flow' }),
  Object.freeze({ index:196, id:'night_insects', domain:'audio', title:'Night Insects' }),
  Object.freeze({ index:197, id:'festival_songs', domain:'audio', title:'Festival Songs' }),
  Object.freeze({ index:198, id:'quiet_library', domain:'audio', title:'Quiet Library' }),
  Object.freeze({ index:199, id:'children_playing', domain:'audio', title:'Children Playing' }),
  Object.freeze({ index:200, id:'storm_warning', domain:'audio', title:'Storm Warning' }),
  Object.freeze({ index:201, id:'learning_schedules', domain:'torah', title:'Learning Schedules' }),
  Object.freeze({ index:202, id:'beis_midrash', domain:'torah', title:'Beis Midrash' }),
  Object.freeze({ index:203, id:'halachic_consultation', domain:'torah', title:'Halachic Consultation' }),
  Object.freeze({ index:204, id:'charity_networks', domain:'torah', title:'Charity Networks' }),
  Object.freeze({ index:205, id:'hospitality_reputation', domain:'torah', title:'Hospitality Reputation' }),
  Object.freeze({ index:206, id:'emergent_chesed', domain:'torah', title:'Emergent Chesed' }),
  Object.freeze({ index:207, id:'celebrations', domain:'torah', title:'Celebrations' }),
  Object.freeze({ index:208, id:'traveling_scholars', domain:'torah', title:'Traveling Scholars' }),
  Object.freeze({ index:209, id:'spiritual_growth', domain:'torah', title:'Spiritual Growth' }),
  Object.freeze({ index:210, id:'hidden_kindness', domain:'torah', title:'Hidden Kindness' }),
  Object.freeze({ index:211, id:'shiur_chains', domain:'torah', title:'Shiur Chains' }),
  Object.freeze({ index:212, id:'question_memory', domain:'torah', title:'Question Memory' }),
  Object.freeze({ index:213, id:'chavrusa_matching', domain:'torah', title:'Chavrusa Matching' }),
  Object.freeze({ index:214, id:'sefer_lending', domain:'torah', title:'Sefer Lending' }),
  Object.freeze({ index:215, id:'tzedakah_routing', domain:'torah', title:'Tzedakah Routing' }),
  Object.freeze({ index:216, id:'meal_invitations', domain:'torah', title:'Meal Invitations' }),
  Object.freeze({ index:217, id:'lost_object_returns', domain:'torah', title:'Lost Object Returns' }),
  Object.freeze({ index:218, id:'peace_making', domain:'torah', title:'Peace Making' }),
  Object.freeze({ index:219, id:'visiting_sick', domain:'torah', title:'Visiting Sick' }),
  Object.freeze({ index:220, id:'comforting_mourners', domain:'torah', title:'Comforting Mourners' }),
  Object.freeze({ index:221, id:'honoring_elders', domain:'torah', title:'Honoring Elders' }),
  Object.freeze({ index:222, id:'teaching_children', domain:'torah', title:'Teaching Children' }),
  Object.freeze({ index:223, id:'blessing_moments', domain:'torah', title:'Blessing Moments' }),
  Object.freeze({ index:224, id:'gratitude_ledger', domain:'torah', title:'Gratitude Ledger' }),
  Object.freeze({ index:225, id:'private_victories', domain:'torah', title:'Private Victories' }),
  Object.freeze({ index:226, id:'sleeping_islands', domain:'engine', title:'Sleeping Islands' }),
  Object.freeze({ index:227, id:'hierarchical_scheduling', domain:'engine', title:'Hierarchical Scheduling' }),
  Object.freeze({ index:228, id:'multi_resolution_ai', domain:'engine', title:'Multi Resolution Ai' }),
  Object.freeze({ index:229, id:'behavior_lod', domain:'engine', title:'Behavior Lod' }),
  Object.freeze({ index:230, id:'predictive_streaming', domain:'engine', title:'Predictive Streaming' }),
  Object.freeze({ index:231, id:'gpu_vegetation', domain:'engine', title:'Gpu Vegetation' }),
  Object.freeze({ index:232, id:'parallel_pathfinding', domain:'engine', title:'Parallel Pathfinding' }),
  Object.freeze({ index:233, id:'event_npc_logic', domain:'engine', title:'Event Npc Logic' }),
  Object.freeze({ index:234, id:'frame_budget_sim', domain:'engine', title:'Frame Budget Sim' }),
  Object.freeze({ index:235, id:'deterministic_world', domain:'engine', title:'Deterministic World' }),
  Object.freeze({ index:236, id:'interest_rings', domain:'engine', title:'Interest Rings' }),
  Object.freeze({ index:237, id:'mutation_budgets', domain:'engine', title:'Mutation Budgets' }),
  Object.freeze({ index:238, id:'payload_compression', domain:'engine', title:'Payload Compression' }),
  Object.freeze({ index:239, id:'worker_batching', domain:'engine', title:'Worker Batching' }),
  Object.freeze({ index:240, id:'state_deltas', domain:'engine', title:'State Deltas' }),
  Object.freeze({ index:241, id:'rollback_checkpoints', domain:'engine', title:'Rollback Checkpoints' }),
  Object.freeze({ index:242, id:'trace_markers', domain:'engine', title:'Trace Markers' }),
  Object.freeze({ index:243, id:'adaptive_raycasts', domain:'engine', title:'Adaptive Raycasts' }),
  Object.freeze({ index:244, id:'ui_quiescence', domain:'engine', title:'Ui Quiescence' }),
  Object.freeze({ index:245, id:'stream_priorities', domain:'engine', title:'Stream Priorities' }),
  Object.freeze({ index:246, id:'scene_graph_culling', domain:'engine', title:'Scene Graph Culling' }),
  Object.freeze({ index:247, id:'animation_throttles', domain:'engine', title:'Animation Throttles' }),
  Object.freeze({ index:248, id:'audio_virtualization', domain:'engine', title:'Audio Virtualization' }),
  Object.freeze({ index:249, id:'physics_tiers', domain:'engine', title:'Physics Tiers' }),
  Object.freeze({ index:250, id:'save_compaction', domain:'engine', title:'Save Compaction' }),
  Object.freeze({ index:251, id:'historical_archives', domain:'world', title:'Historical Archives' }),
  Object.freeze({ index:252, id:'civilization_evolution', domain:'world', title:'Civilization Evolution' }),
  Object.freeze({ index:253, id:'festivals', domain:'world', title:'Festivals' }),
  Object.freeze({ index:254, id:'emergencies', domain:'world', title:'Emergencies' }),
  Object.freeze({ index:255, id:'cleanliness', domain:'world', title:'Cleanliness' }),
  Object.freeze({ index:256, id:'hidden_stories', domain:'world', title:'Hidden Stories' }),
  Object.freeze({ index:257, id:'pilgrims', domain:'world', title:'Pilgrims' }),
  Object.freeze({ index:258, id:'caravans', domain:'world', title:'Caravans' }),
  Object.freeze({ index:259, id:'landmarks', domain:'world', title:'Landmarks' }),
  Object.freeze({ index:260, id:'world_memory', domain:'world', title:'World Memory' }),
  Object.freeze({ index:261, id:'regional_politics', domain:'world', title:'Regional Politics' }),
  Object.freeze({ index:262, id:'weather_history', domain:'world', title:'Weather History' }),
  Object.freeze({ index:263, id:'public_mood', domain:'world', title:'Public Mood' }),
  Object.freeze({ index:264, id:'collective_goals', domain:'world', title:'Collective Goals' }),
  Object.freeze({ index:265, id:'village_myths', domain:'world', title:'Village Myths' }),
  Object.freeze({ index:266, id:'cemetery_records', domain:'world', title:'Cemetery Records' }),
  Object.freeze({ index:267, id:'school_records', domain:'world', title:'School Records' }),
  Object.freeze({ index:268, id:'seasonal_décor', domain:'world', title:'Seasonal Décor' }),
  Object.freeze({ index:269, id:'law_changes', domain:'world', title:'Law Changes' }),
  Object.freeze({ index:270, id:'cultural_drift', domain:'world', title:'Cultural Drift' }),
  Object.freeze({ index:271, id:'story_scars', domain:'world', title:'Story Scars' }),
  Object.freeze({ index:272, id:'town_songs', domain:'world', title:'Town Songs' }),
  Object.freeze({ index:273, id:'architectural_style', domain:'world', title:'Architectural Style' }),
  Object.freeze({ index:274, id:'education_level', domain:'world', title:'Education Level' }),
  Object.freeze({ index:275, id:'community_destiny', domain:'world', title:'Community Destiny' }),
]);
export const LIVING_WORLD_BY_ID = Object.freeze(Object.fromEntries(LIVING_WORLD_IDEAS.map(item => [item.id, item])));
export function livingWorldIdeas(domain = null) { return LIVING_WORLD_IDEAS.filter(item => !domain || item.domain === domain); }
export function livingWorldIdea(id) { return LIVING_WORLD_BY_ID[id] || null; }
export function livingWorldDomains() { return [...new Set(LIVING_WORLD_IDEAS.map(item => item.domain))]; }
export default { LIVING_WORLD_IDEAS, LIVING_WORLD_BY_ID, livingWorldIdeas, livingWorldIdea, livingWorldDomains };
