// B"H
/**
 * LivingWorldRuntime
 * The coordinator: schedule -> movement -> memory -> rumor -> gossip -> mission
 * -> profession -> reputation -> world event -> economy price -> UI payload.
 */
import * as State from './LivingWorldState.js';
import { hydrateLivingWorldFromWorldState, persistLivingWorldToWorldState, livingWorldPersistenceSummary } from './LivingWorldPersistenceBridge.js';
import { applyEconomyPricing } from '../economy/EconomyPricingRuntime.js';
import { applyVendorPurchase } from '../economy/EconomyTransactionRuntime.js';
import { createNpcScheduleRuntime } from '../npc/NpcScheduleRuntime.js';
import { createNpcMemoryRuntime } from '../npc/NpcMemoryRuntime.js';
import { openNpcInteraction, npcInteractionIndex } from '../npc/NpcInteractionRuntime.js';
import { createRumor, propagateRumors } from '../npc/GossipRuntime.js';
import { createMissionRuntime } from '../missions/MissionRuntime.js';
import { progressActiveObjectives } from '../missions/MissionObjectiveRuntime.js';
import { createReputationRuntime } from '../reputation/ReputationRuntime.js';
import { createWorldEventRuntime } from '../world/WorldEventRuntime.js';
import { createProfessionRuntime } from '../professions/ProfessionRuntime.js';

function cap(scope){ const b=scope.__MITZVAH_WORLD_REALISM_BUDGET__||{}; return Math.max(1,Math.min(5,Number(b.scheduler?.maxTasksPerTick||b.maxTasksPerTick||3))); }
function publish(scope,type,payload){ scope.dispatchEvent?.(new CustomEvent('mitzvah-world:living-world',{detail:{type,payload}})); return payload; }
function ensureStore(scope, options){ const loaded=State.loadLivingWorldState(); const raw=options.store || scope.__MITZVAH_WORLD_STATE__ || loaded; const hydrated=options.skipWorldStateHydration ? raw : hydrateLivingWorldFromWorldState(raw); scope.__MITZVAH_WORLD_STATE__=State.normalizeLivingWorldState(hydrated); applyEconomyPricing(scope.__MITZVAH_WORLD_STATE__,{reason:'runtime-hydrate'}); return scope.__MITZVAH_WORLD_STATE__; }
function price(store,reason){ applyEconomyPricing(store,{reason}); State.commitUiPayloads(store); return store.economy?.prices||{}; }
function saveBoth(store, reason='living-world-runtime'){ price(store,reason); const saved=State.saveLivingWorldState(store); persistLivingWorldToWorldState(saved,{reason}); return saved; }

export function createLivingWorldRuntime(scope=globalThis, options={}){ const store=ensureStore(scope,options); const npcs=store.npcs; const scheduleRuntime=createNpcScheduleRuntime(npcs); const memoryRuntime=createNpcMemoryRuntime(store); const missionRuntime=createMissionRuntime(store); const reputationRuntime=createReputationRuntime(store); const worldEvents=createWorldEventRuntime(store); const professions=createProfessionRuntime(store); const runtimeState={ started:false, ticks:0, lastStep:null };
  function applySchedules(hour){ const rows=scheduleRuntime.tick(hour,{maxTasksPerTick:cap(scope)},store); for(const row of rows){ State.addMovementIntent(store,row.movementIntent); State.addMemory(store,row.npcId,{kind:'schedule_seen',text:`Went to ${row.place} for ${row.role}.`,role:row.role,place:row.place}); } return rows; }
  function applyCausalPlayerEcho(){ const memory=State.addMemory(store,'miriam_baker',{kind:'delivered',text:'The player delivered bread.',fact:'bread_delivery'}); if(!store.rumors.some(r=>r.topic==='bread_delivery')) State.addRumor(store,createRumor('miriam_baker','The player delivered bread.','bread_delivery')); reputationRuntime.add('reliability','village',1); return memory; }
  function applyEconomyAndMissions(){ if((store.economy.bread||0)<3 && !store.activeMissions.deliver_flour_for_bread_shortage) missionRuntime.accept('deliver_flour_for_bread_shortage'); if(store.villageProjects.farmerSick && !store.activeMissions.bring_soup_to_sick_farmer) missionRuntime.accept('bring_soup_to_sick_farmer'); if((store.villageProjects.benchRepair||0)<1 && !store.activeMissions.repair_beis_midrash_bench) missionRuntime.accept('repair_beis_midrash_bench'); return missionRuntime.all(); }
  function step(reason='tick', hour=store.clockHour){ store.clockHour=hour; const schedule=applySchedules(hour); const event=worldEvents.ambient(reason); const missionsBeforeCraft=applyEconomyAndMissions(); const crafted=professions.craft('challah','miriam_baker'); applyCausalPlayerEcho(); const rumors=propagateRumors(store,npcs.map(n=>n.id)); if(crafted) progressActiveObjectives(missionRuntime,'deliver_flour',1); const prices=price(store,`step:${reason}`); const missions=missionRuntime.all(); runtimeState.ticks+=1; runtimeState.lastStep={ reason, schedule, event, crafted, rumors, missionsBeforeCraft, missions, prices, uiPayloads:store.uiPayloads, reputation:reputationRuntime.snapshot() }; saveBoth(store,`step:${reason}`); return publish(scope,'step',runtimeState.lastStep); }
  const api={ state:runtimeState, store, npcs, scheduleRuntime, memoryRuntime, missionRuntime, reputationRuntime, worldEvents, professions, start(reason='manual'){runtimeState.started=true; State.recordLivingWorldEvent({type:'living-world-start',reason}); saveBoth(store,`start:${reason}`); return api;}, stop(reason='manual'){runtimeState.started=false; State.recordLivingWorldEvent({type:'living-world-stop',reason}); saveBoth(store,`stop:${reason}`); return api;}, step, speakToNpc(npcId,context={}){ return openNpcInteraction(npcId,{...context,store},npcs); }, acceptMission:id=>{ const result=missionRuntime.accept(id); saveBoth(store,`accept:${id}`); return result; }, progress:(kind,amount=1)=>{ const result=progressActiveObjectives(missionRuntime,kind,amount); saveBoth(store,`progress:${kind}`); return result; }, completeMission(id){ const done=missionRuntime.finish(id); if(done){ reputationRuntime.applyReward(done.reward); State.addMemory(store,done.sourceNpc||'miriam_baker',{kind:done.reward?.memory||'helped',text:`Completed ${done.title}.`}); saveBoth(store,`complete:${id}`); } return done; }, remember(npcId,event){ const result=memoryRuntime.remember(npcId,event); saveBoth(store,`remember:${npcId}`); return result; }, craft(id,crafter){ const result=professions.craft(id,crafter); saveBoth(store,`craft:${id}`); return result; }, buyVendorItem(item,ctx={}){ const result=applyVendorPurchase(item,{...ctx,store}); saveBoth(store,`vendor-buy:${item?.id||item}`); return result; }, reprice(reason='manual'){ return price(store,reason); }, persist(reason='manual'){ return persistLivingWorldToWorldState(store,{reason}); }, persistenceSummary(){ return livingWorldPersistenceSummary(); }, snapshot(){ price(store,'snapshot'); return { state:State.loadLivingWorldState(), store, npcIndex:npcInteractionIndex(npcs), lastStep:runtimeState.lastStep, uiPayloads:store.uiPayloads, persistence:livingWorldPersistenceSummary() }; } };
  scope.__MITZVAH_WORLD_LIVING_WORLD__=api; return api; }
export default createLivingWorldRuntime;
