// B"H
/**
 * LivingWorldVisibleBridge
 * Turns causal village state into the browser scrolls the player can actually
 * see: feed, tracker, gossip, service, map, reputation, schedule, economy.
 */
import { createLivingWorldRuntime } from './LivingWorldRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1';
import { commitUiPayloads } from './LivingWorldState.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1';
function line(v){ return String(v ?? '').replace(/_/g,' '); }
export function createLivingWorldVisiblePayload(runtime){ const rt=runtime || createLivingWorldRuntime(globalThis); const state=rt.store; commitUiPayloads(state); const ui=state.uiPayloads || {}; return { ambientFeed:{ events:ui.ambientEventFeedPayload||[], text:(ui.ambientEventFeedPayload||[]).slice(-6).map(e=>line(e.type||e.reason)) }, questTracker:{ active:ui.questTrackerRows||[] }, questMarkers:{ markers:(ui.mapMarkerPayload||[]).map((m,i)=>({ npcId:m.npcId||m.missionId||`world_${i}`, missionId:m.missionId||m.npcId||`event_${i}`, marker:m.kind==='quest'?'question':'exclamation', npcName:line(m.npcId||m.place||'Village'), title:line(m.reason||m.kind||m.missionId||'Living world') })) }, npcGossip:{ open:false, npcId:'miriam_baker', npcName:'Miriam', greeting:(ui.npcGossipPayload||[]).at(-1)?.currentText || 'The village has not begun gossip yet.', choices:(ui.npcGossipPayload||[]).slice(-4).map(r=>({ id:r.id, label:r.currentText, kind:r.topic })) }, serviceMenu:{ title:'Village Services', rows:[`Hearth: ${state.hearthLocation}`, `Visited: ${(state.servicesVisited||[]).length}`, `Bread price: ${state.economy?.prices?.bread}`] }, reputationSummary:ui.reputationSummaryPayload||state.reputation, scheduleDebug:ui.scheduleDebugPayload||state.npcSchedules, economySummary:ui.economySummaryPayload||state.economy, rawUiPayloads:ui }; }
export function emitLivingWorldVisiblePayload(scope=globalThis, runtime=null){ const payload=createLivingWorldVisiblePayload(runtime || scope.__MITZVAH_WORLD_LIVING_WORLD__); scope.__MITZVAH_LIVING_WORLD_VISIBLE_PAYLOAD__=payload; scope.__MITZVAH_UI_BRIDGE__?.receive?.('livingWorldVisible', payload); scope.dispatchEvent?.(new CustomEvent('mitzvah-world:visible-payload',{detail:payload})); return payload; }
export function installLivingWorldVisibleBridge(scope=globalThis){ const runtime=scope.__MITZVAH_WORLD_LIVING_WORLD__ || createLivingWorldRuntime(scope); scope.__MITZVAH_WORLD_LIVING_WORLD__=runtime; scope.__MITZVAH_RENDER_LIVING_WORLD__=()=>emitLivingWorldVisiblePayload(scope,runtime); scope.addEventListener?.('mitzvah-world:living-world',()=>scope.__MITZVAH_RENDER_LIVING_WORLD__()); runtime.start('visible-bridge'); runtime.step('visible-bridge', runtime.store.clockHour || 8); return scope.__MITZVAH_RENDER_LIVING_WORLD__(); }
export default { createLivingWorldVisiblePayload, emitLivingWorldVisiblePayload, installLivingWorldVisibleBridge };
