// B"H
#include <node_api.h>
#include <stdint.h>
#include <stdlib.h>
#include "awtai_f32_project.h"
#include "awtai_fused_ffn.h"
#include "awtai_mmap_project.h"
#include "awtai_model_map.h"
#include "awtai_project_threaded.h"
#include "awtai_quant_dispatch.h"

static napi_value fail(napi_env e,const char*m){napi_throw_error(e,NULL,m);return NULL;}
static int32_t i32(napi_env e,napi_value v,const char*n){int32_t o=0;if(napi_get_value_int32(e,v,&o)!=napi_ok)napi_throw_error(e,NULL,n);return o;}
static int64_t i64(napi_env e,napi_value v,const char*n){int64_t o=0;if(napi_get_value_int64(e,v,&o)!=napi_ok)napi_throw_error(e,NULL,n);return o;}
static int32_t thr(napi_env e,napi_value*a,size_t c,int i){return c<=(size_t)i?1:i32(e,a[i],"B'H thread count");}
static int ta(napi_env e,napi_value v,napi_typedarray_type x,void**d,size_t*l,const char*n){napi_typedarray_type t;size_t off;napi_value ab;if(napi_get_typedarray_info(e,v,&t,l,d,&ab,&off)!=napi_ok||t!=x){napi_throw_error(e,NULL,n);return 0;}return 1;}
static char* str(napi_env e,napi_value v){size_t l=0;napi_get_value_string_utf8(e,v,NULL,0,&l);char*s=malloc(l+1);if(!s)return NULL;napi_get_value_string_utf8(e,v,s,l+1,&l);return s;}
static napi_value u64(napi_env e,uint64_t v){napi_value o;napi_create_bigint_uint64(e,v,&o);return o;}

static napi_value project_rows(napi_env e,napi_callback_info info){size_t c=6;napi_value a[6];if(napi_get_cb_info(e,info,&c,a,NULL,NULL)!=napi_ok||c<5)return fail(e,"B'H projectRows args");int type=i32(e,a[1],"type"),r=i32(e,a[2],"rows"),cols=i32(e,a[3],"cols"),threads=thr(e,a,c,5);void*raw=0,*x=0;size_t rl=0,xl=0;if(!ta(e,a[0],napi_uint8_array,&raw,&rl,"raw")||!ta(e,a[4],napi_float32_array,&x,&xl,"input"))return NULL;if(!awtai_type_supported(type)||r<=0||cols<=0||(int)xl<cols||rl<(size_t)awtai_row_bytes(type,cols)*(size_t)r)return fail(e,"B'H invalid projection");napi_value ab,out;void*y=0;if(napi_create_arraybuffer(e,(size_t)r*sizeof(float),&y,&ab)!=napi_ok)return fail(e,"alloc");awtai_project_threaded(type,raw,r,cols,x,y,threads);napi_create_typedarray(e,napi_float32_array,r,ab,0,&out);return out;}
static napi_value project_file_rows(napi_env e,napi_callback_info info){size_t c=7;napi_value a[7];if(napi_get_cb_info(e,info,&c,a,NULL,NULL)!=napi_ok||c<6)return fail(e,"B'H projectFileRows args");char*path=str(e,a[0]);if(!path)return fail(e,"path alloc");uint64_t off=(uint64_t)i64(e,a[1],"offset");int type=i32(e,a[2],"type"),r=i32(e,a[3],"rows"),cols=i32(e,a[4],"cols"),win=c>6?i32(e,a[6],"window"):256;void*x=0;size_t xl=0;if(!ta(e,a[5],napi_float32_array,&x,&xl,"input")){free(path);return NULL;}if(r<=0||cols<=0||(int)xl<cols){free(path);return fail(e,"B'H invalid file projection");}napi_value ab,out;void*y=0;if(napi_create_arraybuffer(e,(size_t)r*sizeof(float),&y,&ab)!=napi_ok){free(path);return fail(e,"alloc");}int ok=awtai_mmap_quant_project(path,off,type,r,cols,x,y,win);free(path);if(!ok)return fail(e,"B'H file projection failed");napi_create_typedarray(e,napi_float32_array,r,ab,0,&out);return out;}
static napi_value project_f32_rows(napi_env e,napi_callback_info info){size_t c=4;napi_value a[4];if(napi_get_cb_info(e,info,&c,a,NULL,NULL)!=napi_ok||c<4)return fail(e,"B'H projectF32Rows args");int r=i32(e,a[1],"rows"),cols=i32(e,a[2],"cols");void*w=0,*x=0;size_t wl=0,xl=0;if(!ta(e,a[0],napi_float32_array,&w,&wl,"weights")||!ta(e,a[3],napi_float32_array,&x,&xl,"input"))return NULL;if(r<=0||cols<=0||wl<(size_t)r*(size_t)cols||xl<(size_t)cols)return fail(e,"B'H invalid f32");napi_value ab,out;void*y=0;if(napi_create_arraybuffer(e,(size_t)r*sizeof(float),&y,&ab)!=napi_ok)return fail(e,"alloc");if(!awtai_project_f32_rows(w,r,cols,x,y))return fail(e,"B'H f32 failed");napi_create_typedarray(e,napi_float32_array,r,ab,0,&out);return out;}
static napi_value fused_ffn(napi_env e,napi_callback_info info){size_t c=10;napi_value a[10];if(napi_get_cb_info(e,info,&c,a,NULL,NULL)!=napi_ok||c<9)return fail(e,"B'H fusedFfn args");int gt=i32(e,a[1],"gt"),ut=i32(e,a[3],"ut"),dt=i32(e,a[5],"dt"),h=i32(e,a[6],"hidden"),f=i32(e,a[7],"ffn"),threads=thr(e,a,c,9);void*gr=0,*ur=0,*dr=0,*x=0;size_t gl=0,ul=0,dl=0,xl=0;if(!ta(e,a[0],napi_uint8_array,&gr,&gl,"gate")||!ta(e,a[2],napi_uint8_array,&ur,&ul,"up")||!ta(e,a[4],napi_uint8_array,&dr,&dl,"down")||!ta(e,a[8],napi_float32_array,&x,&xl,"input"))return NULL;if((int)xl<h||gl<(size_t)awtai_row_bytes(gt,h)*(size_t)f||ul<(size_t)awtai_row_bytes(ut,h)*(size_t)f||dl<(size_t)awtai_row_bytes(dt,f)*(size_t)h)return fail(e,"B'H short ffn");napi_value ab,out;void*y=0;if(napi_create_arraybuffer(e,(size_t)h*sizeof(float),&y,&ab)!=napi_ok)return fail(e,"alloc");if(!awtai_fused_ffn(gt,gr,ut,ur,dt,dr,h,f,x,y,threads))return fail(e,"B'H ffn failed");napi_create_typedarray(e,napi_float32_array,h,ab,0,&out);return out;}
static napi_value mmap_topk(napi_env e,napi_callback_info info){size_t c=6;napi_value a[6];if(napi_get_cb_info(e,info,&c,a,NULL,NULL)!=napi_ok||c<5)return fail(e,"B'H mmapTopK args");char*path=str(e,a[0]);if(!path)return fail(e,"path alloc");int r=i32(e,a[1],"rows"),cols=i32(e,a[2],"cols"),k=i32(e,a[4],"k"),win=c>5?i32(e,a[5],"window"):512;void*x=0;size_t xl=0;if(!ta(e,a[3],napi_float32_array,&x,&xl,"input")){free(path);return NULL;}awtai_topk_item*items=calloc((size_t)k,sizeof(*items));if(!items){free(path);return fail(e,"items alloc");}int ok=awtai_mmap_f32_topk(path,r,cols,x,k,win,items);free(path);if(!ok){free(items);return fail(e,"B'H mmap topk failed");}napi_value arr;napi_create_array_with_length(e,k,&arr);for(int i=0;i<k;i++){napi_value o,id,lg;napi_create_object(e,&o);napi_create_int32(e,items[i].id,&id);napi_create_double(e,items[i].logit,&lg);napi_set_named_property(e,o,"id",id);napi_set_named_property(e,o,"logit",lg);napi_set_element(e,arr,i,o);}free(items);return arr;}

static void finalize_map(napi_env e,void*data,void*hint){(void)e;(void)hint;awtai_model_map_destroy((AwtaiModelMap*)data);}
static AwtaiModelMap* model_arg(napi_env e,napi_value v){napi_value h=v;void*p=NULL;napi_valuetype t;if(napi_typeof(e,v,&t)!=napi_ok)return NULL;if(t==napi_object){napi_value maybe;if(napi_get_named_property(e,v,"handle",&maybe)==napi_ok)h=maybe;}if(napi_get_value_external(e,h,&p)!=napi_ok)return NULL;return (AwtaiModelMap*)p;}
static napi_value open_model_map(napi_env e,napi_callback_info info){size_t c=1;napi_value a[1];if(napi_get_cb_info(e,info,&c,a,NULL,NULL)!=napi_ok||c<1)return fail(e,"B'H openModelMap args");char*path=str(e,a[0]);if(!path)return fail(e,"path alloc");AwtaiModelMap*map=NULL;int ok=awtai_model_map_open(path,&map);free(path);if(!ok)return fail(e,"B'H openModelMap failed");napi_value obj,ext,pathv;napi_create_object(e,&obj);napi_create_external(e,map,finalize_map,NULL,&ext);napi_create_string_utf8(e,map->path,NAPI_AUTO_LENGTH,&pathv);napi_set_named_property(e,obj,"handle",ext);napi_set_named_property(e,obj,"path",pathv);napi_set_named_property(e,obj,"size",u64(e,map->size));napi_set_named_property(e,obj,"manifestLength",u64(e,map->manifest_length));napi_set_named_property(e,obj,"dataOffset",u64(e,map->data_offset));return obj;}
static napi_value close_model_map(napi_env e,napi_callback_info info){size_t c=1;napi_value a[1];if(napi_get_cb_info(e,info,&c,a,NULL,NULL)!=napi_ok||c<1)return fail(e,"B'H closeModelMap args");AwtaiModelMap*map=model_arg(e,a[0]);if(!map)return fail(e,"B'H invalid model map handle");awtai_model_map_close(map);napi_value out;napi_get_boolean(e,1,&out);return out;}

static napi_value init(napi_env e,napi_value exports){napi_property_descriptor d[]={{"projectRows",0,project_rows,0,0,0,napi_default,0},{"projectFileRows",0,project_file_rows,0,0,0,napi_default,0},{"projectF32Rows",0,project_f32_rows,0,0,0,napi_default,0},{"fusedFfn",0,fused_ffn,0,0,0,napi_default,0},{"mmapF32TopK",0,mmap_topk,0,0,0,napi_default,0},{"openModelMap",0,open_model_map,0,0,0,napi_default,0},{"closeModelMap",0,close_model_map,0,0,0,napi_default,0}};napi_define_properties(e,exports,7,d);return exports;}NAPI_MODULE(NODE_GYP_MODULE_NAME,init)
