// B"H
/** @file TrainerRuntime.js @description Data-driven trainer ranks, level gates, class paths, and ranked Torah passage scaling. */
import TrainerRegistry, { trainerById } from "./TrainerRegistry.js";
import { abilityRankInfo, AbilityClassPaths } from "../../tochen/torah/AbilityIndex.js";
function playerOf(olam) { return olam?.player || olam?.chossid || null; }
function emit(olam, name, payload) { olam?.ayshPeula?.("ui event", name, payload); }
export function ensureTrainerState(olam) { const p = playerOf(olam); if (!p) return null; p.trainerState ||= { learnedRanks:{}, specializations:{}, passives:{} }; return p.trainerState; }
export function rankKey(abilityId) { return String(abilityId || ""); }
export function currentRank(olam, abilityId) { return Math.max(1, Number(ensureTrainerState(olam)?.learnedRanks?.[rankKey(abilityId)] || 1)); }
export function canLearnRank(olam, trainerId, abilityId) { const trainer = trainerById(trainerId), p = playerOf(olam), info = abilityRankInfo(abilityId); if (!trainer || !p || !trainer.teaches.includes(abilityId)) return { ok:false, reason:"not-taught" }; const next = Number(ensureTrainerState(olam)?.learnedRanks?.[rankKey(abilityId)] || 0) + 1; if (next > info.max || !trainer.ranks.includes(next)) return { ok:false, reason:"max-rank", next, max:info.max }; if (Number(p.level || 1) < Number(info.unlockLevel || 1) + (next - 1) * 2) return { ok:false, reason:"level-gated", next }; return { ok:true, next, info, classPath:AbilityClassPaths[abilityId] }; }
export function learnRank(olam, trainerId, abilityId) { const check = canLearnRank(olam, trainerId, abilityId), state = ensureTrainerState(olam); if (!check.ok || !state) return false; state.learnedRanks[rankKey(abilityId)] = check.next; const path = check.classPath || {}; state.specializations[path.tree] = Math.max(Number(state.specializations[path.tree] || 0), check.next); for (const passive of path.passives || []) state.passives[passive] = true; emit(olam, "trainerLearned", { trainerId, abilityId, rank:check.next, classPath:path }); emit(olam, "effectsOverlay", { text:`${abilityId} RANK ${check.next}`, color:"#d7c8ff" }); return { abilityId, rank:check.next, classPath:path }; }
export function rankedPassage(olam, passage = {}) { const rank = currentRank(olam, passage.id), info = passage.rankInfo || abilityRankInfo(passage.id), dmgScale = 1 + (rank - 1) * Number(info.damageStep || .18), costScale = 1 + (rank - 1) * Number(info.costStep || .08); return { ...passage, rank, rankMax:info.max || 1, damage:Math.floor(Number(passage.damage || passage.power || 0) * dmgScale), heal:Math.floor(Number(passage.heal || 0) * dmgScale), cost:Math.max(1, Math.floor(Number(passage.cost || 0) * costScale)), classPath:passage.classPath || AbilityClassPaths[passage.id], description:`${passage.description || passage.text || ""} Rank ${rank}/${info.max || 1}.` }; }
export function trainerPayload(olam) { const state = ensureTrainerState(olam) || { learnedRanks:{}, specializations:{}, passives:{} }; return { trainers:TrainerRegistry, learned:state.learnedRanks, specializations:state.specializations, passives:state.passives }; }
export default { ensureTrainerState, currentRank, canLearnRank, learnRank, rankedPassage, trainerPayload };
