// B"H
/** @file ThreeHeldMeshBuilder.js @description Builds browser THREE weapon groups and faithful Node fallback groups. */
function node(name,descriptor){ return {name,descriptor,children:[],position:{x:0,y:0,z:0},rotation:{x:0,y:0,z:0},scale:{x:1,y:1,z:1},visible:true,userData:{},add(child){this.children.push(child); child.parent=this;}}; }
function fallbackPart(itemId,part){ const o=node(`${itemId}_${part.kind}`,{part}); Object.assign(o.position,part.pos||{}); Object.assign(o.rotation,part.rot||{}); Object.assign(o.scale,part.scale||{}); o.geometry={kind:part.kind,dims:part.dims||{}}; o.material={name:part.material}; return o; }
function material(THREE,name="held"){ const color=name.includes("gold")?0xffcc55:name.includes("silver")||name.includes("steel")?0xdde7ff:name.includes("wood")||name.includes("cedar")?0x775533:name.includes("glow")?0x88ccff:0xffffff; return new THREE.MeshStandardMaterial({name,color,emissive:name.includes("glow")?color:0x000000,emissiveIntensity:name.includes("glow")?.45:0}); }
function geometry(THREE,part){ const d=part.dims||{}; if(part.kind==="sphere") return new THREE.SphereGeometry(d.r||.05,16,12); if(part.kind==="cylinder") return new THREE.CylinderGeometry(d.r||.03,d.r||.03,d.h||1,16); if(part.kind==="cone") return new THREE.ConeGeometry(d.r||.05,d.h||.15,16); if(part.kind==="line") return new THREE.BoxGeometry(d.w||.012,d.h||.45,.01); if(part.kind==="arc") return new THREE.TorusGeometry((d.w||.6)/2,d.thick||.02,8,24,Math.PI); if(part.kind==="wedge") return new THREE.BoxGeometry(d.x||.2,d.y||.2,d.z||.04); if(part.kind==="text"||part.kind==="trail"||part.kind==="flame"||part.kind==="ring"||part.kind==="spiral"||part.kind==="cloth") return new THREE.BoxGeometry(d.x||.08,d.y||.08,d.z||.012); return new THREE.BoxGeometry(d.x||.05,d.y||.2,d.z||.05); }
function applyTransform(obj,part){ Object.assign(obj.position,part.pos||{}); Object.assign(obj.rotation,part.rot||{}); Object.assign(obj.scale,part.scale||{}); }
export function buildThreeHeldMesh(descriptor,THREE=globalThis.THREE){ if(!THREE?.Group||!THREE?.Mesh){ const group=node(descriptor?.id||"heldMesh",descriptor); group.userData={descriptor,awtsmoosHeldMesh:true,fallback:true}; for(const part of descriptor?.recipe?.parts||[]) group.add(fallbackPart(descriptor.itemId,part)); return group; } const group=new THREE.Group(); group.name=descriptor.id||`held_${descriptor.itemId}`; group.userData={descriptor,awtsmoosHeldMesh:true}; for(const part of descriptor.recipe?.parts||[]){ const mesh=new THREE.Mesh(geometry(THREE,part),material(THREE,part.material)); mesh.name=`${descriptor.itemId}_${part.kind}`; mesh.userData={part}; applyTransform(mesh,part); group.add(mesh); } return group; }
export default buildThreeHeldMesh;
