// B"H
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
process.env.AWTS_REMOTE_DESKTOP_STORE = path.join(os.tmpdir(), 'awts-rd-test-' + Date.now() + '.json');
const { buildActions } = require('../tools/fs/actions.js');
const { resetForTests } = require('../tools/fs/remoteDesktop/store.js');
(async () => {
  resetForTests();
  const config = { root: process.cwd(), allowWrite: false, allowSecrets: false };
  const actionNames = Object.keys(buildActions(config, { action:'remoteDesktopPolicy' }, null));
  assert.ok(actionNames.includes('chromeScreenshot'));
  assert.ok(actionNames.includes('remoteDesktopChromeScreenshotPush'));
  let actions = buildActions(config, { action:'remoteDesktopPlatformCapabilities' }, null);
  assert.equal((await actions.remoteDesktopPlatformCapabilities()).capabilities.watchOnlyFrameEnvelope, true);
  actions = buildActions(config, { action:'remoteDesktopChromeFramePlan' }, null);
  assert.equal((await actions.remoteDesktopChromeFramePlan()).plan.status, 'available-diagnostic-frame');
  actions = buildActions(config, { action:'remoteDesktopNativeHelperPlan' }, null);
  assert.ok((await actions.remoteDesktopNativeHelperPlan()).plan.android.includes('MediaProjection consent activity'));
  actions = buildActions(config, { action:'remoteDesktopPeerConnectionPlan' }, null);
  assert.ok((await actions.remoteDesktopPeerConnectionPlan()).plan.signaling.includes('fingerprint'));

  actions = buildActions(config, { action:'remoteDesktopHelperSkeletons' }, null);
  const skeletons = await actions.remoteDesktopHelperSkeletons();
  assert.ok(skeletons.helpers.android.modules.includes('CaptureService.kt'));
  actions = buildActions(config, { action:'remoteDesktopPeerStateTemplate', sessionId:'s1' }, null);
  assert.equal((await actions.remoteDesktopPeerStateTemplate()).peer.sessionId, 's1');
  actions = buildActions(config, { action:'remoteDesktopBrowserPeerScript' }, null);
  assert.ok((await actions.remoteDesktopBrowserPeerScript()).script.includes('RTCPeerConnection'));
  actions = buildActions(config, { action:'remoteDesktopCreateSession', mode:'control', target:'Chrome tab', requester:'tester', requesterContact:'room-7', purpose:'debug layout', scope:'one tab', ttlSeconds:120 }, null);
  const sessionId = (await actions.remoteDesktopCreateSession()).session.id;
  actions = buildActions(config, { action:'remoteDesktopGrantConsent', sessionId, grantMode:'watch' }, null);
  assert.equal((await actions.remoteDesktopGrantConsent()).session.watchGranted, true);
  actions = buildActions(config, { action:'remoteDesktopChromeFramePush', sessionId, snapshot:'DOM title: hello' }, null);
  const chromeFrame = await actions.remoteDesktopChromeFramePush();
  assert.equal(chromeFrame.ok, true);
  assert.equal(chromeFrame.frame.contentType, 'image/svg+xml');
  actions = buildActions(config, { action:'remoteDesktopFrameLatest', sessionId }, null);
  assert.equal((await actions.remoteDesktopFrameLatest()).frame.contentType, 'image/svg+xml');
  actions = buildActions(config, { action:'remoteDesktopHeartbeat', sessionId, fingerprint:'fp-1' }, null);
  assert.equal((await actions.remoteDesktopHeartbeat()).heartbeat.fingerprint, 'fp-1');
  actions = buildActions(config, { action:'remoteDesktopGrantConsent', sessionId, grantMode:'control' }, null);
  assert.equal((await actions.remoteDesktopGrantConsent()).session.controlGranted, true);
  actions = buildActions(config, { action:'remoteDesktopInputEvent', sessionId, type:'click' }, null);
  assert.equal((await actions.remoteDesktopInputEvent()).error, 'remote_desktop_mouse_not_granted');
  actions = buildActions(config, { action:'remoteDesktopGrantInput', sessionId, family:'mouse' }, null);
  assert.equal((await actions.remoteDesktopGrantInput()).session.mouseGranted, true);
  actions = buildActions(config, { action:'remoteDesktopInputEvent', sessionId, type:'click', x:7, y:8 }, null);
  assert.equal((await actions.remoteDesktopInputEvent()).ok, true);
  actions = buildActions(config, { action:'remoteDesktopInputEvent', sessionId, type:'keydown', key:'A' }, null);
  assert.equal((await actions.remoteDesktopInputEvent()).error, 'remote_desktop_keyboard_not_granted');
  actions = buildActions(config, { action:'remoteDesktopGrantInput', sessionId, family:'keyboard' }, null);
  assert.equal((await actions.remoteDesktopGrantInput()).session.keyboardGranted, true);

  actions = buildActions(config, { action:'remoteDesktopPermissionContract', sessionId }, null);
  const permissionContract = await actions.remoteDesktopPermissionContract();
  assert.equal(permissionContract.contract.hash.length, 64);
  actions = buildActions(config, { action:'remoteDesktopSessionSummary', sessionId }, null);
  assert.ok((await actions.remoteDesktopSessionSummary()).summary.countdownMs >= 0);
  actions = buildActions(config, { action:'remoteDesktopSignalSummary', sessionId }, null);
  assert.ok(Array.isArray((await actions.remoteDesktopSignalSummary()).summary.signals));
  actions = buildActions(config, { action:'remoteDesktopExport' }, null);
  assert.equal(fs.existsSync(process.env.AWTS_REMOTE_DESKTOP_STORE), true);
  console.log(JSON.stringify({ ok:true, checks:['chrome frame plan','native helper plan','peer plan','chrome frame push','heartbeat','mouse gate','keyboard gate','export','helper skeletons','peer scaffold','permission contract','session summary','signal summary'] }, null, 2));
})().catch(error => { console.error(error); process.exit(1); });
