// B"H
/** @file VillageHouseDoor.js @description Visible hinged door; no invisible octree body. */
import Domem from "../../chayim/domem/index.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import * as THREE from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
import { material as texturedMaterial } from "./villagePicture/geometryKit.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { COTTAGE, doorLeafLocal, doorwayLocalOffset } from "./villagePicture/cottage/cottageContract.js?compact=true&v=wide-door-low-floor-20260603-bh346";
import { registerLock, toggleLockable } from "../../systems/locks/LockStateRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { emitLockUi } from "../../systems/locks/LockUiRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f, wood=c=>texturedMaterial(c,{textureMode:"wood"}), brass=c=>texturedMaterial(c,{textureMode:"stone",emissive:0x2a1800,emissiveIntensity:.12});
function mark(mesh,owner,solid=false){mesh.nivraAwtsmoos=owner;Object.assign(mesh.userData||={}, {skipRaycast:false,renderHelper:false,interactiveDoorPart:true,isSolid:solid,explicitCollision:solid,addToOctree:solid,skipOctree:!solid,noOctree:!solid,useExactGeometryCollider:solid});return mesh;}
function part(root,owner,name,pos,size,mat,solid=false){const m=mark(new THREE.Mesh(new THREE.BoxGeometry(...size),mat),owner,solid);m.name=name;m.position.set(...pos);root.add(m);return m;}
export default class VillageHouseDoor extends Domem {
  type="interactiveDoor"; heesHawveh=true;
  constructor(op={},olam){super({...op,golem:null,isSolid:false,interactable:true},olam);this.options=op;this.scaleValue=COTTAGE.scale;this.open=Boolean(op.open);this.openAngle=num(op.openAngle,-1.55);this.target=this.open?this.openAngle:0;this.angle=this.target;this.proximity=num(op.proximity,9.5);this.colliderAdded=false;this.lock=null;}
  async heescheel(olam){this.olam=olam;this.mesh=this.buildDoor();this.mesh.position.copy(this.position.vector3());this.mesh.rotation.y=num(this.rotation?.y,0);this.mesh.scale.setScalar(this.scaleValue);this.mesh.nivraAwtsmoos=this;await olam.hoyseef(this);this.lock=registerLock(olam,{lockId:this.options.lockId||`${this.name||"house_door"}_lock`,keyId:this.options.keyId,locked:this.options.locked===true,ownerNpcId:this.options.ownerNpcId});this.syncDoorCollider(true);if(olam.interactableNivrayim&&!olam.interactableNivrayim.includes(this))olam.interactableNivrayim.push(this);this.isReady=true;}
  buildDoor(){const leaf=doorLeafLocal(),root=new THREE.Group();root.name=this.name||"VillageHouseDoor_visible_hinge_leaf";this.hinge=new THREE.Group();this.hinge.position.set(leaf.hingeX,leaf.centerY,leaf.z);const cx=leaf.width/2;this.doorLeaf=part(this.hinge,this,"visible_door_leaf_hinge_edge_octree",[cx,0,0],[leaf.width,leaf.height,leaf.thickness],wood(0x74411d),true);part(this.hinge,this,"door_top_bar",[cx,leaf.height*.26,-.045],[leaf.width*.86,.04,.034],wood(0x321806));part(this.hinge,this,"door_mid_bar",[cx,0,-.047],[leaf.width*.78,.034,.034],wood(0x321806));part(this.hinge,this,"door_bottom_bar",[cx,-leaf.height*.26,-.045],[leaf.width*.86,.035,.034],wood(0x321806));part(this.hinge,this,"door_knob_contract",[leaf.width-.08,-.02,-.058],[.03,.03,.026],brass(0xffd05a));root.add(this.hinge);root.traverse(c=>{c.nivraAwtsmoos=this;c.frustumCulled=false;});return root;}
  alignToHouseTransform(houseMesh){if(!this.mesh||!houseMesh?.isObject3D)return false;const o=doorwayLocalOffset(),p=new THREE.Vector3(o.x,o.y,o.z);houseMesh.localToWorld(p);this.mesh.position.copy(p);houseMesh.getWorldQuaternion(this.mesh.quaternion);this.mesh.scale.setScalar(COTTAGE.scale);this.mesh.updateMatrixWorld(true);this.syncDoorCollider(true);return true;}
  removeDoorCollider(){if(this.colliderAdded&&this.doorLeaf)this.olam?.worldOctree?.removeMesh?.(this.doorLeaf);this.colliderAdded=false;}
  syncDoorCollider(force=false){if(!this.doorLeaf||!this.olam?.worldOctree)return;if(this.open||Math.abs(this.angle)>.08)return this.removeDoorCollider();if(force)this.removeDoorCollider();if(!this.colliderAdded){this.doorLeaf.updateMatrixWorld(true);this.colliderAdded=Boolean(this.olam.worldOctree.addObject(this.doorLeaf));}}
  ayshPeula(peula){if(peula==="mouseEnter")return emitLockUi(this.olam,this.lock);if(peula==="mouseLeave")return this.olam?.ayshPeula?.("ui event","tooltip",{show:false});if(peula!=="accepted interaction"&&peula!=="pointerdown")return super.ayshPeula?.(peula);const result=toggleLockable(this.olam,this.lock);if(!result.ok)return emitLockUi(this.olam,result.lock),result;this.lock=result.lock;this.open=Boolean(result.open);this.target=this.open?this.openAngle:0;if(this.open)this.removeDoorCollider();this.olam?.ayshPeula?.("ui event","effectsOverlay",{text:this.open?"Door opened":"Door closed",color:"#ffd35b",replace:true});emitLockUi(this.olam,this.lock);return result;}
  heesHawvoos(dt){const t=Math.min(1,dt*8.5),ease=1-Math.pow(1-t,3);this.angle+=(this.target-this.angle)*ease;if(this.hinge)this.hinge.rotation.y=this.angle;if(this.open||Math.abs(this.angle)>.08)this.removeDoorCollider();else this.syncDoorCollider();}
}
