// B"H
/** @file VillagePictureProp.js @description Registers only visible house meshes into octree. No hidden colliders. */
import Domem from "../../chayim/domem/index.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import TerrainMath from "../terrain/core/TerrainMath.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { markDecorative } from "./villagePicture/geometryKit.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { VILLAGE_PICTURE_RECIPES } from "./villagePicture/recipeMap.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
const PROOF='B"H | VISIBLE_HOUSE_OCTREE_PROOF',doors=[];let doorBound=false;
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f,p3=(v={})=>Array.isArray(v)?{x:n(v[0]),y:n(v[1]),z:n(v[2])}:{x:n(v.x),y:n(v.y),z:n(v.z)};
function terrainY(o,x,z,f=0){const law=o?.awtsmoosTerrainLaw;return law?.data?n(law.position?.y)+TerrainMath.calculateHeightAt(x-n(law.position?.x),z-n(law.position?.z),law.data):f;}
function bbox(root){root.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(root),s=new THREE.Vector3(),c=new THREE.Vector3();b.getSize(s);b.getCenter(c);return{box:b,min:b.min.toArray(),max:b.max.toArray(),size:s.toArray(),center:c.toArray()};}
function rootOf(o){return o?.scene||o?.nivrayimGroup?.parent||null;}function inTree(r,n){for(let p=n;p;p=p.parent)if(p===r)return true;return false;}function push(a,i){if(Array.isArray(a)&&i&&!a.includes(i))a.push(i);}
function mount(o,m){const r=rootOf(o);if(r&&!inTree(r,m))r.add(m);}function scaleOf(opt){return Math.max(.05,n(opt.scale,1));}
function ground(m,y,l=0){m.updateMatrixWorld(true);const d=y+l-bbox(m).box.min.y;m.position.y+=d;m.updateMatrixWorld(true);return{delta:d,after:bbox(m)};}
function protect(root,kind,owner){root.visible=true;root.frustumCulled=false;root.nivraAwtsmoos=owner;root.traverse?.(x=>{x.frustumCulled=false;x.userData||={};if(x.userData.visibleHouseOctreeMesh){x.visible=true;x.userData.addToOctree=true;x.userData.skipOctree=false;x.userData.noOctree=false;x.userData.isSolid=true;x.userData.explicitCollision=true;x.userData.collisionBody=true;}else{x.userData.skipOctree=true;x.userData.noOctree=true;}if(x.userData.clickableDoor){x.visible=true;x.userData.skipRaycast=false;}else x.userData.skipRaycast=true;Object.assign(x.userData,{villageVisibleGuaranteed:true,kind,neverCullVillageProp:true,neverHideVillageProp:true,noInvisibleCollider:true});x.nivraAwtsmoos=x.userData.clickableDoor?x.nivraAwtsmoos||owner:owner;});}
function addVisibleToOctree(o,m){m.updateMatrixWorld(true);let ok=false;try{ok=Boolean(o?.worldOctree?.fromGraphNode?.(m))||ok;}catch{}try{ok=Boolean(o?.worldOctree?.addObject?.(m))||ok;}catch{}try{ok=Boolean(o?.worldOctree?.addMesh?.(m))||ok;}catch{}m.userData.octreeRegistered=ok;return ok;}
function installVisibleHouseOctree(owner,o){let count=0,names=[];owner.mesh.updateMatrixWorld(true);owner.mesh.traverse(m=>{if(!m.isMesh||!m.userData?.visibleHouseOctreeMesh)return;if(addVisibleToOctree(o,m)){count++;names.push(m.name);}});owner.mesh.userData.houseCollisionProof={visibleMeshesInOctree:count,names,noInvisibleColliders:true,noColliderSources:true,authority:'visible meshes only',seal:'visible-house-mesh-only-octree-20260708-bh1'};console.info(PROOF,owner.mesh.userData.houseCollisionProof);}
function dom(o){return o?.renderer?.domElement||o?.canvas||document.querySelector('canvas')||document;}function cam(o){return o?.camera||o?.activeCamera||o?.ayin?.camera||o?.chossid?.camera||o?.player?.camera||null;}function ndc(ev,el){const r=el.getBoundingClientRect?.()||{left:0,top:0,width:innerWidth,height:innerHeight};return new THREE.Vector2(((ev.clientX-r.left)/r.width)*2-1,-((ev.clientY-r.top)/r.height)*2+1);}
function bindDoor(o){if(doorBound||typeof window==='undefined')return;const el=dom(o),rc=new THREE.Raycaster();if(!el?.addEventListener)return;doorBound=true;el.addEventListener('pointerup',ev=>{const c=cam(o);if(!c)return;rc.setFromCamera(ndc(ev,el),c);const hit=rc.intersectObjects(doors,false)[0];if(!hit)return;hit.object.nivraAwtsmoos?.ayshPeula?.('pointerup',o.player||o.chossid);ev.preventDefault?.();ev.stopPropagation?.();},{passive:false});}
function animatePivot(pivot,target){pivot.userData.doorAnimTarget=target;clearInterval(pivot.userData.animTimer);pivot.userData.animTimer=setInterval(()=>{const y=pivot.rotation.y,d=(target-y)*.32;pivot.rotation.y=Math.abs(d)<.01?target:y+d;if(Math.abs(pivot.rotation.y-target)<.012){pivot.rotation.y=target;clearInterval(pivot.userData.animTimer);}},16);}
function installDoor(owner,o){let panel=null;owner.mesh.traverse(x=>{if(!panel&&x.userData?.clickableDoor)panel=x;});if(!panel)return;const pivot=panel.parent?.userData?.clickableDoorPivot?panel.parent:panel;const bridge={name:owner.name+'_door_bridge',interactable:true,mesh:panel,raycastMesh:panel,isOpen:false,ayshPeula(action){if(!/click|tap|pointerup|accepted interaction|interact/i.test(String(action)))return false;this.isOpen=!this.isOpen;animatePivot(pivot,this.isOpen?n(pivot.userData.doorOpenY,-1.48):n(pivot.userData.doorClosedY,0));owner.mesh.userData.doorState={open:this.isOpen,animated:true,axis:'left-hinge-y',at:Date.now()};console.info('B"H | HOUSE_ANIMATED_DOOR_PROOF',owner.mesh.userData.doorState);return true;}};panel.nivraAwtsmoos=bridge;Object.assign(panel.userData,{clickableDoor:true,tappableDoor:true,interactable:true,skipRaycast:false,skipOctree:true,noOctree:true,noInvisibleCollider:true});push(o.interactableNivrayim,bridge);push(o.meshesToInteractWith,panel);push(doors,panel);bindDoor(o);}
export default class VillagePictureProp extends Domem{type='villagePictureProp';heesHawveh=false;constructor(options={},olam){super({...options,isSolid:false,heesHawveh:false},olam);this.options=options;}async heescheel(o){this.olam=o;const kind=this.options.kind||'bench',recipe=VILLAGE_PICTURE_RECIPES[kind]||VILLAGE_PICTURE_RECIPES.bench,pos=p3(this.options.position),rot=p3(this.options.rotation),gy=terrainY(o,pos.x,pos.z,n(pos.y));this.mesh=recipe({...this.options,context:o,olam:o,name:this.name});this.mesh.name=this.name||'visible_'+kind;this.mesh.rotation.set(rot.x,rot.y,rot.z);this.mesh.scale.setScalar(scaleOf(this.options));protect(this.mesh,kind,this);this.mesh.position.set(pos.x,gy,pos.z);markDecorative(this.mesh);protect(this.mesh,kind,this);await o.hoyseef?.(this);mount(o,this.mesh);const gr=ground(this.mesh,gy,kind==='gableHouse'?.02:0);if(kind==='gableHouse'){installVisibleHouseOctree(this,o);installDoor(this,o);}this.isReady=true;o.__villageVisibleProofs||=[];const proof={stage:'visible-house-mesh-only-octree',name:this.mesh.name,kind,bbox:gr.after,houseCollision:this.mesh.userData.houseCollisionProof||null};o.__villageVisibleProofs.push(proof);globalThis.__VILLAGE_VISIBLE_PROOFS__=()=>o.__villageVisibleProofs;console.info(PROOF,proof);return this;}heesHawvoos(){}}
