// B"H
/** @file VillagePictureProp.js @description Engine-registered visible props: cottage returns, trees get finite bounds, no hidden colliders. */
import Domem from "../../chayim/domem/index.js?compact=true&v=village-prop-no-self-hoyseef-20260708-bh7";
import * as THREE from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
import TerrainMath from "../terrain/core/TerrainMath.js?compact=true&v=village-prop-no-self-hoyseef-20260708-bh7";
import { markDecorative } from "./villagePicture/geometryKit.js?compact=true&v=village-prop-no-self-hoyseef-20260708-bh7";
import { VILLAGE_PICTURE_RECIPES } from "./villagePicture/recipeMap.js?compact=true&v=village-prop-no-self-hoyseef-20260708-bh7";
const PROOF='B"H | VILLAGE_PICTURE_PROP_PROOF',doors=[];let doorBound=false;
const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const p3=(v={})=>Array.isArray(v)?{x:n(v[0]),y:n(v[1]),z:n(v[2])}:{x:n(v.x),y:n(v.y),z:n(v.z)};
const debug=()=>globalThis.__AWTS_DEBUG_VILLAGE__===true;
function proof(stage,data){const p={stage,at:Date.now(),...data};globalThis.__VILLAGE_VISIBLE_PROOFS__ ||= [];globalThis.__VILLAGE_VISIBLE_PROOFS__.push(p);if(globalThis.__VILLAGE_VISIBLE_PROOFS__.length>60)globalThis.__VILLAGE_VISIBLE_PROOFS__.shift();if(debug())console.info(PROOF,p);}
function terrainY(o,x,z,f=0){const law=o?.awtsmoosTerrainLaw;return law?.data?n(law.position?.y)+TerrainMath.calculateHeightAt(x-n(law.position?.x),z-n(law.position?.z),law.data):f;}
function bounds(root){root.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(root),s=new THREE.Vector3();b.getSize(s);if(!Number.isFinite(s.x)||b.isEmpty())s.set(1,1,1);return{box:b,size:{x:Math.max(.05,s.x),y:Math.max(.05,s.y),z:Math.max(.05,s.z)},assetSize:Math.max(.05,s.x*s.y*s.z)};}
function ground(m,y,l=0){const b=bounds(m),d=y+l-b.box.min.y;m.position.y+=d;m.updateMatrixWorld(true);return bounds(m);}

function registerReadyVessel(o, owner) {
  const mesh = owner?.mesh;
  if (!mesh) return owner;
  mesh.nivraAwtsmoos = owner;
  owner.mesh = mesh;
  if (o?.nivrayimGroup && mesh.parent !== o.nivrayimGroup) o.nivrayimGroup.add(mesh);
  else if (o?.scene && !mesh.parent) o.scene.add(mesh);
  if (Array.isArray(o?.nivrayim) && !o.nivrayim.includes(owner)) o.nivrayim.push(owner);
  if ((owner.interactable || owner.type === "interactiveDoor") && Array.isArray(o?.interactableNivrayim) && !o.interactableNivrayim.includes(owner)) o.interactableNivrayim.push(owner);
  return owner;
}
function metadata(owner,mesh,kind,b){owner.size=b.size;owner.dimensions=b.size;owner.assetSize=b.assetSize;owner.width=b.size.x;owner.height=b.size.y;owner.depth=b.size.z;Object.assign(mesh.userData||={}, {kind,villagePropBounds:b.size,assetSize:b.assetSize,readyFiniteBounds:true});}
function protect(root,kind,owner){root.visible=true;root.frustumCulled=false;root.nivraAwtsmoos=owner;root.traverse?.(x=>{x.visible=true;x.frustumCulled=false;x.userData||={};const solid=Boolean(x.userData.visibleHouseOctreeMesh);Object.assign(x.userData,{kind,neverCullVillageProp:true,neverHideVillageProp:true,villageVisibleGuaranteed:true,skipOctree:!solid,noOctree:!solid,addToOctree:solid,isSolid:solid,explicitCollision:solid,collisionBody:solid,noInvisibleCollider:!solid,skipRaycast:!x.userData.clickableDoor});x.nivraAwtsmoos=x.userData.clickableDoor?x.nivraAwtsmoos||owner:owner;});}
function addVisibleToOctree(o,m){m.updateMatrixWorld(true);let ok=false;for(const name of ["fromGraphNode","addObject","addMesh"])try{ok=Boolean(o?.worldOctree?.[name]?.(m))||ok;}catch{}m.userData.octreeRegistered=ok;return ok;}
function installVisibleHouseOctree(owner,o){let count=0,names=[];owner.mesh.traverse(m=>{if(m.isMesh&&m.userData?.visibleHouseOctreeMesh&&addVisibleToOctree(o,m)){count++;names.push(m.name);}});owner.mesh.userData.houseCollisionProof={visibleMeshesInOctree:count,names,noInvisibleColliders:true,authority:'visible meshes only'};proof('house-octree',owner.mesh.userData.houseCollisionProof);}
function push(a,i){if(Array.isArray(a)&&i&&!a.includes(i))a.push(i);}function dom(o){return o?.renderer?.domElement||o?.canvas||document.querySelector('canvas')||document;}function cam(o){return o?.camera||o?.activeCamera||o?.ayin?.camera||o?.chossid?.camera||o?.player?.camera||null;}
function ndc(ev,el){const r=el.getBoundingClientRect?.()||{left:0,top:0,width:innerWidth,height:innerHeight};return new THREE.Vector2(((ev.clientX-r.left)/r.width)*2-1,-((ev.clientY-r.top)/r.height)*2+1);}
function bindDoor(o){if(doorBound||typeof window==='undefined')return;const el=dom(o),rc=new THREE.Raycaster();if(!el?.addEventListener)return;doorBound=true;el.addEventListener('pointerup',ev=>{const c=cam(o);if(!c)return;rc.setFromCamera(ndc(ev,el),c);const hit=rc.intersectObjects(doors,false)[0];if(!hit)return;hit.object.nivraAwtsmoos?.ayshPeula?.('pointerup',o.player||o.chossid);ev.preventDefault?.();ev.stopPropagation?.();},{passive:false});}
function animatePivot(pivot,target){pivot.userData.doorAnimTarget=target;clearInterval(pivot.userData.animTimer);pivot.userData.animTimer=setInterval(()=>{const d=(target-pivot.rotation.y)*.32;pivot.rotation.y=Math.abs(d)<.01?target:pivot.rotation.y+d;if(Math.abs(pivot.rotation.y-target)<.012){pivot.rotation.y=target;clearInterval(pivot.userData.animTimer);}},16);}
function installDoor(owner,o){let panel=null;owner.mesh.traverse(x=>{if(!panel&&x.userData?.clickableDoor)panel=x;});if(!panel)return;const pivot=panel.parent?.userData?.clickableDoorPivot?panel.parent:panel,bridge={name:owner.name+'_door_bridge',interactable:true,mesh:panel,raycastMesh:panel,isOpen:false,ayshPeula(action){if(!/click|tap|pointerup|accepted interaction|interact/i.test(String(action)))return false;this.isOpen=!this.isOpen;animatePivot(pivot,this.isOpen?n(pivot.userData.doorOpenY,-1.48):n(pivot.userData.doorClosedY,0));owner.mesh.userData.doorState={open:this.isOpen,animated:true,at:Date.now()};proof('door-toggle',owner.mesh.userData.doorState);return true;}};panel.nivraAwtsmoos=bridge;Object.assign(panel.userData,{clickableDoor:true,tappableDoor:true,interactable:true,skipRaycast:false,skipOctree:true,noOctree:true,noInvisibleCollider:true});push(o.interactableNivrayim,bridge);push(o.meshesToInteractWith,panel);push(doors,panel);bindDoor(o);}
export default class VillagePictureProp extends Domem{type='villagePictureProp';heesHawveh=false;constructor(options={},olam){super({...options,isSolid:false,heesHawveh:false},olam);this.options=options;this.size={x:1,y:1,z:1};this.dimensions=this.size;this.assetSize=1;}async heescheel(o){this.olam=o;const kind=this.options.kind||'bench',recipe=VILLAGE_PICTURE_RECIPES[kind]||VILLAGE_PICTURE_RECIPES.bench,pos=p3(this.options.position),rot=p3(this.options.rotation),gy=terrainY(o,pos.x,pos.z,n(pos.y));this.mesh=recipe({...this.options,context:o,olam:o,name:this.name});this.mesh.name=this.name||'visible_'+kind;this.mesh.position.set(pos.x,gy,pos.z);this.mesh.rotation.set(rot.x,rot.y,rot.z);this.mesh.scale.setScalar(Math.max(.05,n(this.options.scale,1)));markDecorative(this.mesh);protect(this.mesh,kind,this);const b=ground(this.mesh,gy,kind==='gableHouse'?.02:0);metadata(this,this.mesh,kind,b);registerReadyVessel(o,this);if(kind==='gableHouse'){installVisibleHouseOctree(this,o);installDoor(this,o);}this.isReady=true;proof('prop-ready',{name:this.mesh.name,kind,size:this.size,assetSize:this.assetSize});return this;}heesHawvoos(){}}
