// B"H
/** @file LoadingProgressBridge.js @purpose Exact-stage solid-first loader that exits at playable proof. */
import { installGeneratedCacheGlobals, estimateGeneratedAssetCache } from "../../../systems/cache/GeneratedAssetCache.js?v=generated-cache-spine-20260701-bh1";
installGeneratedCacheGlobals();
const SEAL = "solid-first-playable-loader-20260702-bh11";
const IDS = { total:"genesisProgressBar", world:"genesisWorldBar", worker:"genesisWorkerBar", texture:"genesisTextureBar", action:"genesisActionText", sub:"genesisSubActionText", percent:"genesisPercentText", workerText:"genesisWorkerText", textureText:"genesisTextureText", log:"genesisProgressLog" };
const POINTS = [["entrypoint",4],["boot-runner",8],["angelic-invoker",12],["vessel_ready",18],["load-nivrayim:start",22],["load-nivrayim:parse",30],["load-nivrayim:asset-size",36],["load-nivrayim:heescheel",47],["texture:terrain:solid-ready",58],["load-nivrayim:madeAll",62],["load-nivrayim:placeholder",68],["load-nivrayim:ready",74],["load-nivrayim:afterBriyah",79],["load-nivrayim:village-grounding",83],["load-nivrayim:entry-runtime",86],["postbuild:battleLayer",90],["postbuild:finalGrounding",94],["postbuild:ready-for-first-render",98],["canvas_transferred",99],["loadedWorld",99],["world_final_ready",100]];
const PLAYABLE = [/postbuild:ready-for-first-render/, /load-nivrayim:done/, /canvas_transferred/, /loadedWorld/, /world_final_ready/];
const state = { total:0, world:0, worker:0, texture:0, hidden:false, finalReady:false, playable:false, log:[], timings:{}, startedAt:Date.now(), reason:"", cacheBytes:0, cacheEntries:0 };
let pending = null, paintQueued = false, heartbeat = null;
const doc = () => typeof document === "undefined" ? null : document;
const byId = id => doc()?.getElementById(id) || null;
const clamp = v => Math.max(0, Math.min(100, Number(v) || 0));
const fmt = b => b > 1048576 ? `${(b / 1048576).toFixed(1)} MB` : b > 1024 ? `${Math.round(b / 1024)} KB` : `${Math.round(b || 0)} B`;
function stagePercent(stage) { for (const [prefix, n] of POINTS) if (String(stage).startsWith(prefix)) return n; return state.total; }
function text(id, value) { const n = byId(id), v = value == null ? "" : String(value); if (n && n.textContent !== v) n.textContent = v; }
function width(id, value) { const n = byId(id); if (n) n.style.width = `${Math.round(clamp(value))}%`; }
function bar(key, value) { state[key] = Math.max(state[key], clamp(value)); width(IDS[key], state[key]); }
function exact(stage, data = {}) { const name = data.label || stage; const ms = data.elapsedMs != null ? ` · ${Math.round(Number(data.elapsedMs))}ms` : ""; const bytes = data.bytes ? ` · ${fmt(data.bytes)}` : ""; const cache = data.cacheStatus ? ` · cache:${data.cacheStatus}` : ""; return `${name}${cache}${bytes}${ms}`; }
function action(stage) { if (stage.includes("solid-ready")) return "Solid-color terrain ready — texture continues in background"; if (stage.includes("heescheel")) return "Forging exact vessel"; if (stage.includes("postbuild")) return "Building playable village layer"; if (stage.includes("finalGrounding")) return "Grounding humans, NPCs, animals"; if (stage.includes("battleLayer")) return "Spawning animals"; if (stage.includes("texture")) return "Background texture work"; if (stage.includes("error")) return "Load error"; return "Loading exact stage"; }
function record(line) { if (!line || state.log.at(-1) === line) return; state.log.push(String(line).slice(0, 240)); state.log = state.log.slice(-6); text(IDS.log, state.log.join("\n")); }
function snapshot() { return { ...state, log:[...state.log], canvasReady:Boolean(doc()?.querySelector?.("canvas")), seal:SEAL }; }
function ready(reason) { if (state.hidden) return true; state.playable = true; state.finalReady = true; state.reason = reason; state.total = state.world = state.worker = Math.max(99, state.total); width(IDS.total, 100); width(IDS.world, 100); width(IDS.worker, 100); text(IDS.percent, "100%"); text(IDS.action, "Playable now"); text(IDS.sub, `Loader removed at ${reason}; textures and polish continue while you play.`); if (typeof window !== "undefined") { window.__AWTSMOOS_BOOT_LOADED__ = true; window.__AWTSMOOS_LOADING_FINAL_READY__ = snapshot(); window.dispatchEvent?.(new CustomEvent("awtsmoos-game-ready", { detail:{ phase:"playable", reason, source:"solid-first-loader", seal:SEAL, payload:snapshot() } })); } setTimeout(reallyHide, 40); return true; }
function maybePlayable(stage) { return PLAYABLE.some(rx => rx.test(stage)); }
async function cacheNote() { const est = await estimateGeneratedAssetCache().catch(() => null); if (est?.ok) { state.cacheBytes = est.bytes; state.cacheEntries = est.entries; } }
function paint(input = {}) { if (!doc() || state.hidden) return; const stage = String(input.stage || input.kind || "progress"); state.timings[stage] = input.elapsedMs ?? state.timings[stage]; if (input.cacheBytes != null) state.cacheBytes = Number(input.cacheBytes) || 0; const p = input.total ?? input.amount ?? stagePercent(stage); bar("total", Math.min(99, p)); if (stage.includes("load") || stage.includes("postbuild") || input.world != null) bar("world", input.world ?? p); if (input.worker != null || stage) bar("worker", input.worker ?? p); if (stage.includes("texture") || input.texture != null) bar("texture", input.texture ?? input.percent ?? p); const line = exact(stage, input); text(IDS.percent, `${Math.round(state.total)}%`); text(IDS.action, input.action || action(stage)); text(IDS.sub, `${stage} — ${line}`); text(IDS.workerText, `${stage}`.slice(0, 110)); if (stage.includes("texture")) text(IDS.textureText, line.slice(0, 90)); record(`${stage} :: ${line}`); if (stage.startsWith("cache:")) cacheNote(); if (maybePlayable(stage)) ready(stage); }
export function update(input = {}) { if (state.hidden) return; pending = { ...(pending || {}), ...input }; if (paintQueued) return; paintQueued = true; (typeof requestAnimationFrame === "function" ? requestAnimationFrame : setTimeout)(() => { paintQueued = false; const next = pending; pending = null; paint(next || {}); }, 16); }
export function workerProgress(data = {}) { const stage = String(data.stage || data.text || "worker"); update({ ...data, stage }); }
export function textureProgress(data = {}) { update({ stage:`texture:${data.stage || "progress"}`, texture:clamp(data.percent), textureLabel:`${data.type || data.kind || "texture"} ${clamp(data.percent)}%`, ...data }); }
export function showError(error, label = "worker error") { update({ stage:"worker:error", action:"Worker error", label:String(label).slice(0, 100), log:String(error || label).slice(0, 160) }); }
export function markPlayable(reason = "playable") { return ready(reason); }
export function markFinalReady(reason = "world_final_ready") { return ready(reason); }
export function hideLoading(reason = "hide requested") { return ready(reason); }
export function scheduleHide() { return state.playable ? ready("scheduleHide") : false; }
export function isFinalReady() { return Boolean(state.finalReady); }
function removeAll(sel) { doc()?.querySelectorAll?.(sel)?.forEach(n => n.remove()); }
function reallyHide() { if (state.hidden) return; state.hidden = true; pending = null; stopLoadingHeartbeat(); removeAll(".loading,.loadingContent,.menu .rectangle,.menu.hidden.offscreen"); doc()?.documentElement?.classList?.add?.("awtsmoos-gameplay-dom-quiet"); }
function tick() { if (!state.hidden) record("still building: " + (state.log.at(-1) || "waiting for first playable stage")); }
export function startLoadingHeartbeat() { if (heartbeat || !doc() || state.hidden) return; heartbeat = setInterval(tick, 1400); cacheNote(); }
export function stopLoadingHeartbeat() { if (heartbeat) clearInterval(heartbeat); heartbeat = null; }
if (typeof window !== "undefined") { const q = Array.isArray(window.__AWTSMOOS_EARLY_LOADING_QUEUE__) ? window.__AWTSMOOS_EARLY_LOADING_QUEUE__.slice(-24) : []; window.__AWTSMOOS_LOADING_PROGRESS__ = { update, workerProgress, textureProgress, hideLoading, markFinalReady, markPlayable, scheduleHide, snapshot, isFinalReady, showError, seal:SEAL }; window.__AWTSMOOS_LOADING_BRIDGE_READY__ = true; q.forEach(update); window.addEventListener("awtsmoos-texture-progress", e => textureProgress(e.detail || {})); startLoadingHeartbeat(); }
export default { update, workerProgress, textureProgress, hideLoading, markFinalReady, markPlayable, scheduleHide, startLoadingHeartbeat, stopLoadingHeartbeat, snapshot, isFinalReady, showError };
