// B"H
/** @file LoadingProgressBridge.js @purpose Smooth, living loader that never looks frozen while modules descend. */
import { installGeneratedCacheGlobals, estimateGeneratedAssetCache } from "../../../systems/cache/GeneratedAssetCache.js?v=production-vessel-refresh-20260702-bh1";
installGeneratedCacheGlobals();
const SEAL = "living-loader-production-vessel-refresh-20260702-bh1";
const IDS = { total:"genesisProgressBar", world:"genesisWorldBar", worker:"genesisWorkerBar", texture:"genesisTextureBar", action:"genesisActionText", sub:"genesisSubActionText", percent:"genesisPercentText", workerText:"genesisWorkerText", textureText:"genesisTextureText", log:"genesisProgressLog" };
const POINTS = [["entrypoint",4],["boot-runner",8],["angelic-invoker",12],["vessel_ready",18],["load-nivrayim:start",22],["load-nivrayim:parse",30],["load-nivrayim:asset-size",36],["load-nivrayim:heescheel",47],["texture:terrain:solid-ready",58],["load-nivrayim:madeAll",62],["load-nivrayim:placeholder",68],["load-nivrayim:ready",74],["load-nivrayim:afterBriyah",79],["load-nivrayim:village-grounding",83],["load-nivrayim:entry-runtime",86],["postbuild:battleLayer",90],["postbuild:finalGrounding",94],["postbuild:ready-for-first-render",98],["canvas_transferred",99],["loadedWorld",99],["world_final_ready",100]];
const LABELS = [["world-engine:import:start","Summoning the fresh world engine"],["world-engine:import:error","Refreshing world engine route"],["postbuild:battleLayer","Building animal combat layer"],["postbuild:finalGrounding","Grounding players, NPCs, and animals"],["postbuild:ready-for-first-render","Preparing first playable frame"],["texture:terrain:solid-ready","Solid terrain ready"],["texture:terrain","Painting terrain quietly"],["load-nivrayim:village-grounding","Placing village people safely"],["load-nivrayim:entry-runtime","Starting player, camera, controls, and HUD"],["load-nivrayim:heescheel","Creating NPCs and animals"],["load-nivrayim:parse","Reading village map"],["load-nivrayim:asset-size","Checking needed models"],["load-nivrayim:ready","Connecting the playable world"],["load-nivrayim:start","Building minimum playable world"],["canvas_transferred","Opening the game view"],["loadedWorld","World playable"],["world_final_ready","World playable"],["entrypoint","Starting Mitzvah World"],["boot-runner","Starting world worker"],["angelic-invoker","Preparing game systems"],["vessel_ready","Preparing the scene"]];
const PLAYABLE = [/postbuild:ready-for-first-render/, /load-nivrayim:done/, /canvas_transferred/, /loadedWorld/, /world_final_ready/];
const state = { total:0, world:0, worker:0, texture:0, hidden:false, finalReady:false, playable:false, log:[], timings:{}, startedAt:Date.now(), lastRealAt:Date.now(), reason:"", cacheBytes:0, cacheEntries:0, rawStage:"" };
let pending = null, paintQueued = false, heartbeat = null;
const doc = () => typeof document === "undefined" ? null : document;
const byId = id => doc()?.getElementById(id) || null;
const clamp = v => Math.max(0, Math.min(100, Number(v) || 0));
const fmt = b => b > 1048576 ? `${(b / 1048576).toFixed(1)} MB` : b > 1024 ? `${Math.round(b / 1024)} KB` : `${Math.round(b || 0)} B`;
function stagePercent(stage) { for (const [prefix, n] of POINTS) if (String(stage).startsWith(prefix)) return n; return state.total; }
function human(stage, data = {}) { if (data.humanLabel) return String(data.humanLabel); if (data.label && !String(data.label).includes(":")) return String(data.label); for (const [prefix, label] of LABELS) if (String(stage).startsWith(prefix)) return label; if (String(stage).includes("error")) return "Refreshing the worker route"; return "Preparing Mitzvah World"; }
function text(id, value) { const n = byId(id), v = value == null ? "" : String(value); if (n && n.textContent !== v) n.textContent = v; }
function width(id, value) { const n = byId(id); if (n) n.style.width = `${Math.round(clamp(value))}%`; }
function bar(key, value) { state[key] = Math.max(state[key], clamp(value)); width(IDS[key], state[key]); }
function markAlive(stalled = false) { const d = doc(); d?.documentElement?.classList?.toggle?.("awtsmoos-loader-stalled", stalled); d?.body?.classList?.toggle?.("awtsmoos-loader-stalled", stalled); d?.documentElement?.classList?.add?.("awtsmoos-loader-alive"); }
function detail(label, data = {}) { const ms = data.elapsedMs != null ? ` · ${Math.round(Number(data.elapsedMs))}ms` : ""; const bytes = data.bytes ? ` · ${fmt(data.bytes)}` : ""; const cache = data.cacheStatus ? ` · cache ${data.cacheStatus}` : ""; return `${label}${cache}${bytes}${ms}`; }
function record(line) { if (!line || state.log.at(-1) === line) return; state.log.push(String(line).replace(/\s+/g, " ").slice(0, 120)); state.log = state.log.slice(-4); text(IDS.log, state.log.join("\n")); }
function snapshot() { return { ...state, log:[...state.log], canvasReady:Boolean(doc()?.querySelector?.("canvas")), seal:SEAL }; }
function maybePlayable(stage) { return PLAYABLE.some(rx => rx.test(stage)); }
async function cacheNote() { const est = await estimateGeneratedAssetCache().catch(() => null); if (est?.ok) { state.cacheBytes = est.bytes; state.cacheEntries = est.entries; } }
function reallyHide() { if (state.hidden) return; state.hidden = true; pending = null; stopLoadingHeartbeat(); doc()?.querySelectorAll?.(".loading,.loadingContent,.menu .rectangle,.menu.hidden.offscreen")?.forEach(n => n.remove()); doc()?.documentElement?.classList?.add?.("awtsmoos-gameplay-dom-quiet"); }
function ready(reason) { if (state.hidden) return true; state.playable = true; state.finalReady = true; state.reason = reason; state.total = state.world = state.worker = Math.max(99, state.total); width(IDS.total, 100); width(IDS.world, 100); width(IDS.worker, 100); text(IDS.percent, "100%"); text(IDS.action, "Playable now"); text(IDS.sub, "You can play now. Textures and polish continue quietly in the background."); if (typeof window !== "undefined") { window.__AWTSMOOS_BOOT_LOADED__ = true; window.__AWTSMOOS_LOADING_FINAL_READY__ = snapshot(); window.dispatchEvent?.(new CustomEvent("awtsmoos-game-ready", { detail:{ phase:"playable", reason, source:"living-loader", seal:SEAL, payload:snapshot() } })); } setTimeout(reallyHide, 40); return true; }
function paint(input = {}) { if (!doc() || state.hidden) return; const stage = String(input.stage || input.kind || "progress"); const label = human(stage, input); const synthetic = input.synthetic === true; if (!synthetic) state.lastRealAt = Date.now(); markAlive(false); state.rawStage = stage; state.timings[stage] = input.elapsedMs ?? state.timings[stage]; if (input.cacheBytes != null) state.cacheBytes = Number(input.cacheBytes) || 0; const p = input.total ?? input.amount ?? stagePercent(stage); bar("total", Math.min(99, p)); if (stage.includes("load") || stage.includes("postbuild") || input.world != null || stage.includes("world-engine")) bar("world", input.world ?? p); if (input.worker != null || stage) bar("worker", input.worker ?? Math.max(9, p)); if (stage.includes("texture") || input.texture != null) bar("texture", input.texture ?? input.percent ?? p); const line = detail(label, input); text(IDS.percent, `${Math.round(state.total)}%`); text(IDS.action, input.action || label); text(IDS.sub, input.subAction || line); text(IDS.workerText, label.slice(0, 90)); if (stage.includes("texture")) text(IDS.textureText, line.slice(0, 90)); record(input.log || line); if (stage.startsWith("cache:")) cacheNote(); if (maybePlayable(stage)) ready(stage); }
export function update(input = {}) { if (state.hidden) return; pending = { ...(pending || {}), ...input }; if (paintQueued) return; paintQueued = true; (typeof requestAnimationFrame === "function" ? requestAnimationFrame : setTimeout)(() => { paintQueued = false; const next = pending; pending = null; paint(next || {}); }, 16); }
export function workerProgress(data = {}) { update({ ...data, stage:String(data.stage || data.text || "worker") }); }
export function textureProgress(data = {}) { update({ stage:`texture:${data.stage || "progress"}`, texture:clamp(data.percent), ...data }); }
export function showError(error, label = "worker error") { update({ stage:"worker:error", total:Math.max(state.total, 54), worker:Math.max(state.worker, 42), action:"Refreshing worker route...", humanLabel:String(label).slice(0, 100), log:String(error || label).slice(0, 160), softError:true }); }
export function markPlayable(reason = "playable") { return ready(reason); }
export function markFinalReady(reason = "world_final_ready") { return ready(reason); }
export function hideLoading(reason = "hide requested") { return ready(reason); }
export function scheduleHide() { return state.playable ? ready("scheduleHide") : false; }
export function isFinalReady() { return Boolean(state.finalReady); }
function tick() { if (state.hidden) return; const age = Date.now() - state.lastRealAt; const stalled = age > 2600; markAlive(stalled); if (state.total > 0 && state.total < 96) { const bump = stalled ? 0.55 : 0.18; update({ stage:stalled ? "heartbeat:still-loading" : "heartbeat:breathing", total:Math.min(96, state.total + bump), world:Math.min(96, Math.max(state.world, state.total + bump * .7)), worker:Math.min(94, Math.max(state.worker, state.total + bump * .5)), synthetic:true, action:stalled ? "Still loading; route is alive..." : undefined, subAction:stalled ? "Fresh modules are being requested. The light keeps moving." : undefined, log:stalled ? "Still preparing first playable frame..." : undefined }); } }
export function startLoadingHeartbeat() { if (heartbeat || !doc() || state.hidden) return; heartbeat = setInterval(tick, 700); cacheNote(); markAlive(false); }
export function stopLoadingHeartbeat() { if (heartbeat) clearInterval(heartbeat); heartbeat = null; }
if (typeof window !== "undefined") { const q = Array.isArray(window.__AWTSMOOS_EARLY_LOADING_QUEUE__) ? window.__AWTSMOOS_EARLY_LOADING_QUEUE__.slice(-24) : []; window.__AWTSMOOS_LOADING_PROGRESS__ = { update, workerProgress, textureProgress, hideLoading, markFinalReady, markPlayable, scheduleHide, snapshot, isFinalReady, showError, seal:SEAL }; window.__AWTSMOOS_LOADING_BRIDGE_READY__ = true; q.forEach(update); window.addEventListener("awtsmoos-texture-progress", e => textureProgress(e.detail || {})); startLoadingHeartbeat(); }
export default { update, workerProgress, textureProgress, hideLoading, markFinalReady, markPlayable, scheduleHide, startLoadingHeartbeat, stopLoadingHeartbeat, snapshot, isFinalReady, showError };
