// B"H
/** @file WorkerMessageInterceptor.js @purpose Main-thread worker bridge with no blocking alerts. */
import { oyvedManagerLog } from "../log/MainTextLogger.js";
import { workerMessageToText, isWorkerTextLog } from "./WorkerMessageText.js";
import { recordWorkerProgress } from "../progress/WorkerProgressStore.js";
import LoadingProgress from "../../uiManager/logic/LoadingProgressBridge.js?v=real-meaningful-load-20260701-bh9";
const SEAL = "no-alert-perf-jump-20260701-bh9";
const VISIBLE_PROGRESS = new Set(["entrypoint:start", "boot-runner:start", "angelic-invoker:start", "vessel_ready", "message:pawsawch:received", "message:pawsawch:handleMessage:start", "message:pawsawch:handleMessage:done", "loadedWorld", "canvas_transferred", "world_final_ready"]);
const trimArray = (value, max) => Array.isArray(value) ? value.slice(-max) : [];
const nowStamp = () => new Date().toISOString();
function suppressUserBlocker(text, label = "worker") { window.__AWTSMOOS_SUPPRESSED_ALERTS__ ||= []; window.__AWTSMOOS_SUPPRESSED_ALERTS__.push({ at:Date.now(), label, text:String(text).slice(0, 500), seal:SEAL }); window.__AWTSMOOS_SUPPRESSED_ALERTS__ = trimArray(window.__AWTSMOOS_SUPPRESSED_ALERTS__, 50); }
function ensureLivingRegionMain() { window.__AWTSMOOS_LIVING_REGION_MAIN__ ||= { version:"living-region-main-proof-20260617-progress-single-voice", bootedAt:nowStamp(), received:[] }; return window.__AWTSMOOS_LIVING_REGION_MAIN__; }
function requestProbe() { const m = window.__AWTSMOOS_ACTIVE_WORKER_MANAGER__ || window.mana?.socket; const id = `groundDiag-${Date.now()}`; m?.postMessage?.({ playerProbe:{ id, seal:SEAL } }); return id; }
function latestGroundingDiag() { const probe = window.__AWTSMOOS_LAST_PLAYER_PROBE__; if (!probe?.visualClamp) return { warnings:["player grounding diagnostic not ready"], requestedWorkerProbe:true, requestId:requestProbe(), seal:SEAL }; return probe.visualClamp; }
function installWindowCollisionDiagnostics() { if (window.__AWTSMOOS_WINDOW_COLLISION_DIAG_INSTALLED__ === SEAL) return; window.__AWTSMOOS_WINDOW_COLLISION_DIAG_INSTALLED__ = SEAL; window.__AWTSMOOS_REQUEST_PLAYER_PROBE_FROM_MANAGER__ = requestProbe; window.__MITZVAH_PLAYER_GROUNDING_DIAG__ = latestGroundingDiag; window.__AWTS_COLLISION_DIAG__ = () => window.__AWTSMOOS_LAST_PLAYER_PROBE__?.collisionDiag || { windowBridge:true, seal:SEAL }; window.__AWTS_BUBBLE_DIAG__ = () => window.__AWTSMOOS_LAST_PLAYER_PROBE__?.bubbleDiag || { windowBridge:true, seal:SEAL }; window.__AWTS_GROUNDING_DIAG__ = latestGroundingDiag; }
function dispatchGameReadyPhase(stage, payload = {}) { try { window.dispatchEvent?.(new CustomEvent("awtsmoos-game-ready", { detail:{ phase:stage, source:"worker-progress", payload } })); } catch {} }
function rememberLivingRegion(type, payload) { const main = ensureLivingRegionMain(), entry = { at:nowStamp(), type, payload:payload || null }; main.received = trimArray([...(main.received || []), entry], 24); main.last = entry; if (type === "runtime") { main.runtimeStats = payload?.stats || payload || null; window.AWTSMOOS_LIVING_REGION_STATS = main.runtimeStats; } if (type === "director") { main.directorReport = payload?.report || payload || null; window.AWTSMOOS_LIVING_REGION_REPORT = main.directorReport; } window.AWTSMOOS_LIVING_REGION_MAIN = main; window.AWTSMOOS_REGION_DEBUG = window.AWTSMOOS_REGION_DEBUG || {}; window.AWTSMOOS_REGION_DEBUG.livingRegion = main; recordWorkerProgress(`living-region:${type}`, { type:`living-region:${type}`, payload }); }
function markVesselReady(manager) { if (manager.runtime) manager.runtime.vesselIsReady = true; manager._vesselIsReady = true; }
function markWorldLoaded(manager) { if (manager.runtime) manager.runtime.worldLoaded = true; manager._worldLoaded = true; }
function markCanvasTransferred(manager) { if (manager.runtime) manager.runtime.canvasTransferred = true; manager._canvasTransferred = true; }
function markLifecycle(manager, stage, data) { if (stage === "vessel_ready") { markVesselReady(manager); manager._dispatchPawsawch?.(); } if (stage === "loadedWorld") markWorldLoaded(manager); if (stage === "canvas_transferred") markCanvasTransferred(manager); if (stage === "world_final_ready") { markWorldLoaded(manager); markCanvasTransferred(manager); LoadingProgress.markFinalReady?.("worker final ready"); dispatchGameReadyPhase(stage, data); setTimeout(requestProbe, 250); } }
function handleProgress(manager, data) { const stage = String(data.stage || data.text || "unknown"); recordWorkerProgress(stage, data); markLifecycle(manager, stage, data); if (VISIBLE_PROGRESS.has(stage) || stage.includes(":")) return; }
function handlePlayerProbeResult(data) { const probe = data.payload || data; window.__AWTSMOOS_PLAYER_PROBES__ ||= []; window.__AWTSMOOS_LAST_PLAYER_PROBE__ = probe; window.__AWTSMOOS_PLAYER_PROBES__.push(probe); window.__AWTSMOOS_PLAYER_PROBES__ = trimArray(window.__AWTSMOOS_PLAYER_PROBES__, 40); window.__AWTSMOOS_LAST_GROUNDING_DIAG__ = probe.visualClamp || null; window.dispatchEvent?.(new CustomEvent("awtsmoos:player-probe-result", { detail:probe })); console.info('B"H | PLAYER_PROBE_RESULT_JSON ' + JSON.stringify(probe)); }
function handleWorkerGameplayFps(data) { const payload = data.payload || data; window.__AWTSMOOS_WORKER_GAMEPLAY_FPS__ = payload; window.AWTSMOOS_GAMEPLAY_FPS = payload; window.dispatchEvent?.(new CustomEvent("awtsmoos:worker-gameplay-fps", { detail:payload })); }
function handleError(data) { const text = workerMessageToText(data); oyvedManagerLog.error(text); suppressUserBlocker(text, data.type || "worker-error"); LoadingProgress.showError?.(text, "worker protocol error"); }
function handleTextLog(data) { const text = workerMessageToText(data); if (data.type === "worker_import_error_text" || data.type === "ERROR_TEXT") { oyvedManagerLog.error(text); suppressUserBlocker(text, data.type); LoadingProgress.showError?.(text, data.type); } }
export function interceptWorkerMessage(manager, event) { installWindowCollisionDiagnostics(); const data = event.data; if (data?.type === "worker_progress") { handleProgress(manager, data); return; } if (data?.type === "worker_gameplay_fps") { handleWorkerGameplayFps(data); return; } if (data?.type === "livingRegionRuntimeStats") { rememberLivingRegion("runtime", data.payload || data); return; } if (data?.type === "livingRegionDirectorReport") { rememberLivingRegion("director", data.payload || data); return; } if (data?.type === "render_trace") return; if (data?.type === "playerProbeResult") { handlePlayerProbeResult(data); return; } if (isWorkerTextLog(data)) { handleTextLog(data); return; } if (!data || typeof data !== "object") return; if (data.type === "ERROR" || data.type === "ERROR_TEXT") { handleError(data); return; } if (data.type === "vessel_ready") { markLifecycle(manager, "vessel_ready", data); recordWorkerProgress("vessel_ready", data); return; } if (data.type === "loadedWorld") { markLifecycle(manager, "loadedWorld", data); recordWorkerProgress("loadedWorld", data); return; } if (data.type === "canvas_transferred") { markLifecycle(manager, "canvas_transferred", data); recordWorkerProgress("canvas_transferred", data); return; } if (data.type === "world_final_ready") { markLifecycle(manager, "world_final_ready", data); recordWorkerProgress("world_final_ready", data); } }
