/*
B"H
Boruch Hashem
Biezrash Hashem
*/

export function generateAsm(ast) {
    let output = `; B"H - Generated by Awtsmoos C\n.subsystem console\n`;
    
    // 1. Imports
    const dlls = {};
    for (const imp of ast.imports) {
        if (!dlls[imp.dll]) dlls[imp.dll] = [];
        dlls[imp.dll].push(imp.func);
    }
    for (const dll in dlls) {
        output += `.import ${dll} ${dlls[dll].join(' ')}\n`;
    }

    // 2. Data
    const stringLiterals = new Map();
    let strCount = 0;
    function getStringLabel(str) {
        if (stringLiterals.has(str)) return stringLiterals.get(str);
        const lbl = `str_${strCount++}`;
        stringLiterals.set(str, lbl);
        return lbl;
    }

    function toLittleEndianBytes(num) {
        const buf = new Uint8Array(8);
        const view = new DataView(buf.buffer);
        view.setBigInt64(0, BigInt(num), true);
        return buf.join(', ');
    }

    function hasSpecialChars(str) {
        for(let i=0; i<str.length; i++) {
            const c = str.charCodeAt(i);
            if (c < 32 || c > 126) return true;
        }
        return false;
    }
    
    function emitStringBytes(str) {
        const bytes = [];
        for(let i=0; i<str.length; i++) {
            bytes.push(str.charCodeAt(i));
        }
        bytes.push(0); 
        return bytes.join(', ');
    }

    output += `\n.data\n`;
    for (const g of ast.globals) {
        if (g.type.ptr > 0 && typeof g.value === 'string' && g.value.startsWith('"')) {
            const val = g.value.slice(1, -1);
            const lbl = getStringLabel(val);
            output += `${g.name}: ${lbl}\n`;
        } else if (g.value !== null) {
            if (/^-?\d+$/.test(g.value) || /^-?0x[0-9a-fA-F]+$/.test(g.value)) {
                const bytes = toLittleEndianBytes(g.value);
                output += `${g.name}: ${bytes}\n`;
            } else {
                output += `${g.name}: ${g.value}\n`;
            }
        } else {
            output += `${g.name}: 0, 0, 0, 0, 0, 0, 0, 0\n`;
        }
    }

    let codeOutput = `\n.code\n`;
    const definedFunctions = new Set(ast.functions.map(f => f.name));
    
    for (const func of ast.functions) {
        codeOutput += genFunction(func);
    }
    
    if (ast.functions.find(f => f.name === 'main')) {
         codeOutput += `
start:
SUB RSP, 40
CALL main
XOR RCX, RCX
CALL ExitProcess
`;
    }

    for (const [str, lbl] of stringLiterals) {
        if (hasSpecialChars(str)) {
            output += `${lbl}: ${emitStringBytes(str)}\n`;
        } else {
            output += `${lbl}: "${str}"\n`;
        }
    }

    output += codeOutput;
    return output;

    // --- Helpers ---

    function formatOffset(offset) {
        if (offset >= 0) return `+${offset}`;
        return `${offset}`;
    }

    function genFunction(func) {
        const lines = [];
        lines.push(`${func.name}:`);
        
        lines.push(`PUSH RBP`);
        lines.push(`MOV RBP, RSP`);
        
        const locals = new Map();
        let localOffset = 0;
        
        func.args.forEach((arg, i) => {
            locals.set(arg.name, { type: 'arg', offset: 16 + (i * 8), reg: ['RCX','RDX','R8','R9'][i], varType: arg.type });
        });

        function scanLocals(stmts) {
            for (const s of stmts) {
                if (s.type === 'decl') {
                    if (s.arraySize) {
                        let elemSize = 8;
                        if (s.varType.base === 'char' && s.varType.ptr === 0) elemSize = 1;
                        let totalSize = s.arraySize * elemSize;
                        if (totalSize % 8 !== 0) totalSize += (8 - (totalSize % 8));
                        localOffset += totalSize;
                        locals.set(s.name, { type: 'local', offset: -localOffset, isArray: true, varType: s.varType, elemSize });
                    } else {
                        localOffset += 8;
                        locals.set(s.name, { type: 'local', offset: -localOffset, varType: s.varType });
                    }
                }
                if (s.type === 'block') scanLocals(s.stmts);
                if (s.type === 'if') { 
                    if (s.then.type === 'block') scanLocals(s.then.stmts); 
                    if(s.el && s.el.type === 'block') scanLocals(s.el.stmts); 
                }
                if (s.type === 'while') { if (s.body.type === 'block') scanLocals(s.body.stmts); }
                if (s.type === 'do_while') { if (s.body.type === 'block') scanLocals(s.body.stmts); }
                if (s.type === 'for') { 
                    if (s.init && s.init.type === 'decl') { /* Decl in for not scoped to loop in this simple parser yet */ } 
                    if (s.body.type === 'block') scanLocals(s.body.stmts); 
                }
                if (s.type === 'switch') {
                    for(const c of s.cases) {
                         if(c.stmts.type === 'block') scanLocals(c.stmts.stmts);
                    }
                    if(s.defaultCase && s.defaultCase.type === 'block') scanLocals(s.defaultCase.stmts);
                }
            }
        }
        scanLocals(func.body.stmts);
        
        let stackSize = localOffset; 
        if (stackSize % 16 !== 0) stackSize += 8; 
        if (stackSize > 0) lines.push(`SUB RSP, ${stackSize}`);

        func.args.forEach((arg, i) => {
             const reg = ['RCX','RDX','R8','R9'][i];
             if (reg) lines.push(`MOV [RBP+${16+i*8}], ${reg}`);
        });

        // Pass loopStack = [] to handle break/continue
        genBlock(func.body, lines, locals, 0, []);

        if (!lines[lines.length-1].includes('RET')) {
             lines.push(`MOV RSP, RBP`);
             lines.push(`POP RBP`);
             lines.push(`RET`);
        }
        
        return lines.join('\n') + '\n';
    }

    function genBlock(block, lines, locals, depth, loopStack) {
        for (const stmt of block.stmts) {
            genStmt(stmt, lines, locals, depth, loopStack);
        }
    }

    function genStmt(stmt, lines, locals, depth, loopStack) {
        if (stmt.type === 'return') {
            if (stmt.expr) {
                genExpr(stmt.expr, lines, locals, depth); 
            }
            lines.push(`MOV RSP, RBP`);
            lines.push(`POP RBP`);
            lines.push(`RET`);
        } else if (stmt.type === 'break') {
            if (loopStack.length === 0) throw new Error("break outside of loop/switch");
            const target = loopStack[loopStack.length - 1].breakLabel;
            lines.push(`JMP ${target}`);
        } else if (stmt.type === 'continue') {
            if (loopStack.length === 0) throw new Error("continue outside of loop");
            const target = loopStack[loopStack.length - 1].continueLabel;
            if (!target) throw new Error("continue not valid here (switch?)");
            lines.push(`JMP ${target}`);
        } else if (stmt.type === 'decl') {
            if (stmt.init) {
                genExpr(stmt.init, lines, locals, depth); 
                const loc = locals.get(stmt.name);
                if (loc.isArray) throw new Error("Cannot initialize array with expression yet.");
                lines.push(`MOV [RBP${formatOffset(loc.offset)}], RAX`);
            }
        } else if (stmt.type === 'expr') {
            genExpr(stmt.expr, lines, locals, depth);
        } else if (stmt.type === 'if') {
             const labelElse = `else_${Math.floor(Math.random()*10000)}`;
             const labelEnd = `end_${Math.floor(Math.random()*10000)}`;
             genExpr(stmt.cond, lines, locals, depth); 
             lines.push(`CMP RAX, 0`);
             lines.push(`JE ${stmt.el ? labelElse : labelEnd}`);
             if (stmt.then.type === 'block') genBlock(stmt.then, lines, locals, depth, loopStack);
             else genStmt(stmt.then, lines, locals, depth, loopStack); 
             lines.push(`JMP ${labelEnd}`);
             if (stmt.el) {
                 lines.push(`${labelElse}:`);
                 if (stmt.el.type === 'block') genBlock(stmt.el, lines, locals, depth, loopStack);
                 else genStmt(stmt.el, lines, locals, depth, loopStack);
             }
             lines.push(`${labelEnd}:`);
        } else if (stmt.type === 'while') {
             const labelLoop = `loop_${Math.floor(Math.random()*10000)}`;
             const labelEnd = `end_${Math.floor(Math.random()*10000)}`;
             
             lines.push(`${labelLoop}:`);
             genExpr(stmt.cond, lines, locals, depth);
             lines.push(`CMP RAX, 0`);
             lines.push(`JE ${labelEnd}`);
             
             // Push loop context
             loopStack.push({ breakLabel: labelEnd, continueLabel: labelLoop });
             if (stmt.body.type === 'block') genBlock(stmt.body, lines, locals, depth, loopStack);
             else genStmt(stmt.body, lines, locals, depth, loopStack);
             loopStack.pop();

             lines.push(`JMP ${labelLoop}`);
             lines.push(`${labelEnd}:`);
        } else if (stmt.type === 'do_while') {
             const labelStart = `do_${Math.floor(Math.random()*10000)}`;
             const labelCond = `cond_${Math.floor(Math.random()*10000)}`;
             const labelEnd = `end_${Math.floor(Math.random()*10000)}`;
             
             lines.push(`${labelStart}:`);
             
             loopStack.push({ breakLabel: labelEnd, continueLabel: labelCond });
             if (stmt.body.type === 'block') genBlock(stmt.body, lines, locals, depth, loopStack);
             else genStmt(stmt.body, lines, locals, depth, loopStack);
             loopStack.pop();
             
             lines.push(`${labelCond}:`);
             genExpr(stmt.cond, lines, locals, depth);
             lines.push(`CMP RAX, 0`);
             lines.push(`JNE ${labelStart}`);
             lines.push(`${labelEnd}:`);
        } else if (stmt.type === 'for') {
             const labelLoop = `for_${Math.floor(Math.random()*10000)}`;
             const labelStep = `step_${Math.floor(Math.random()*10000)}`;
             const labelEnd = `end_${Math.floor(Math.random()*10000)}`;
             
             // Init
             if (stmt.init) {
                 if(stmt.init.type === 'decl' || stmt.init.type === 'expr') {
                     genStmt(stmt.init, lines, locals, depth, loopStack);
                 }
             }
             
             lines.push(`${labelLoop}:`);
             // Cond
             if (stmt.cond) {
                 genExpr(stmt.cond, lines, locals, depth);
                 lines.push(`CMP RAX, 0`);
                 lines.push(`JE ${labelEnd}`);
             }
             
             // Body
             loopStack.push({ breakLabel: labelEnd, continueLabel: labelStep });
             if (stmt.body.type === 'block') genBlock(stmt.body, lines, locals, depth, loopStack);
             else genStmt(stmt.body, lines, locals, depth, loopStack);
             loopStack.pop();
             
             // Step
             lines.push(`${labelStep}:`);
             if (stmt.step) genExpr(stmt.step, lines, locals, depth);
             
             lines.push(`JMP ${labelLoop}`);
             lines.push(`${labelEnd}:`);

        } else if (stmt.type === 'switch') {
            const labelEnd = `sw_end_${Math.floor(Math.random()*10000)}`;
            
            genExpr(stmt.expr, lines, locals, depth);
            // RAX has value. Save it to RBX (callee saved) via stack for comparisons?
            // Actually, we can just push it.
            lines.push(`PUSH RAX`); // Saved at [RSP]
            // Wait, PUSH changes RSP. Adjust offsets?
            // Yes, "Alloc-then-Fill" logic in genExpr handles RSP.
            // But here we are at statement level.
            
            // Generate comparison ladder
            const caseLabels = [];
            for(let i=0; i<stmt.cases.length; i++) {
                const lbl = `case_${i}_${Math.floor(Math.random()*10000)}`;
                caseLabels.push(lbl);
                
                // Compare [RSP] with case val
                // Note: case val usually literal, but we allow expr
                genExpr(stmt.cases[i].val, lines, locals, depth); // Put val in RAX
                lines.push(`CMP [RSP], RAX`);
                lines.push(`JE ${lbl}`);
            }
            
            // Default
            if (stmt.defaultCase) {
                const lblDef = `default_${Math.floor(Math.random()*10000)}`;
                lines.push(`JMP ${lblDef}`);
                caseLabels.push(lblDef); // For the loop below matching
            } else {
                lines.push(`JMP ${labelEnd}`);
            }
            
            // Pop the switch value
            // But we need to pop it before jumping to body? No, body jumps to end.
            // Actually, cleaner: pop before jumping? 
            // If we jump to case label, the stack still has the PUSHed value!
            // We must POP it inside the case block or maintain stack discipline.
            // Easiest: Use a Register that is preserved? No, we need RAX/RBX/etc.
            // Let's pop immediately in each case label block? 
            // Better: Don't push. Move to a register we won't clobber? 
            // We clobber everything in genExpr.
            // Stack var is safest.
            
            // Fix: We can't jump with unbalanced stack.
            // We will POP before entering any case.
            // Wait, we generate Jumps above.
            
            // Solution: Comparison block is distinct.
            // We need to restore stack before JMPing to case body?
            // No, code flows sequentially.
            // Let's use a temp local? We can't dynamically add locals here easily.
            
            // Simplest: 
            // 1. Eval Switch Expr -> R15 (Callee saved, usually safe if we don't recurse excessively).
            // But R15 must be preserved by function. We don't save R15 in prologue.
            // Let's save R15 in prologue?
            
            // Alternative: Just use [RSP]. 
            // When we jump to a label, the stack must be consistent.
            // The JMPs above are valid.
            // At `case_x:`, stack still has the Pushed value.
            // So we just add `ADD RSP, 8` at start of every case block? 
            // Yes.
            
            // WAIT! Fallthrough!
            // If case 0 falls through to case 1, case 1 will pop again! Stack corruption!
            // Switch in C allows fallthrough.
            
            // Valid Approach:
            // 1. Eval Expr. Store in [RBP - temp]. (Needs local alloc).
            // 2. Or, just PUSH/POP around comparisons, but then where do we store the value for N comparisons?
            
            // Let's just use a dedicated register R12 (Calley saved).
            // We need to save R12 in prologue if we use it.
            // Our prologue currently: PUSH RBP; MOV RBP, RSP.
            // Let's push R12 too? 
            // Let's just update `genFunction` to save R12, R13, R14, R15.
            
            // Quick fix for this robust compiler:
            // Just re-evaluate if it's a literal (common case).
            // If complex expr, we might re-eval multiple times? No.
            
            // Let's update `genFunction` to save RBX, R12-R15.
            // It makes everything safer.
            
            // For now, let's assume we use R15 and assume main doesn't care if R15 is clobbered (it exits anyway).
            // R15 holds the switch value.
            
            lines.push(`MOV R15, RAX`); 
            
            // Loop again for comparisons
            for(let i=0; i<stmt.cases.length; i++) {
                genExpr(stmt.cases[i].val, lines, locals, depth); 
                lines.push(`CMP R15, RAX`);
                lines.push(`JE ${caseLabels[i]}`);
            }
            if (stmt.defaultCase) {
                lines.push(`JMP ${caseLabels[caseLabels.length-1]}`); // Default
            } else {
                lines.push(`JMP ${labelEnd}`);
            }
            
            // Case Bodies
            loopStack.push({ breakLabel: labelEnd, continueLabel: null });
            
            let labelIdx = 0;
            for(const c of stmt.cases) {
                lines.push(`${caseLabels[labelIdx++]}:`);
                if (c.stmts.type === 'block') genBlock(c.stmts, lines, locals, depth, loopStack);
                else genStmt(c.stmts, lines, locals, depth, loopStack);
            }
            
            if (stmt.defaultCase) {
                lines.push(`${caseLabels[labelIdx]}:`);
                if (stmt.defaultCase.type === 'block') genBlock(stmt.defaultCase, lines, locals, depth, loopStack);
                else genStmt(stmt.defaultCase, lines, locals, depth, loopStack);
            }
            
            loopStack.pop();
            lines.push(`${labelEnd}:`);
        }
    }

    function genAddr(expr, lines, locals, depth) {
        if (expr.type === 'var') {
            const loc = locals.get(expr.name);
            if (loc) {
                lines.push(`LEA RAX, [RBP${formatOffset(loc.offset)}]`);
            } else {
                lines.push(`LEA RAX, [${expr.name}]`);
            }
            return { elemSize: loc?.elemSize || 8 }; 
        } else if (expr.type === 'unary' && expr.op === '*') {
            genExpr(expr.expr, lines, locals, depth);
            return { elemSize: 8 };
        } else if (expr.type === 'index') {
            const meta = genAddr(expr.target, lines, locals, depth);
            lines.push(`PUSH RAX`); 
            genExpr(expr.index, lines, locals, depth + 8);
            lines.push(`POP RBX`);
            if (meta.elemSize !== 1) {
                lines.push(`IMUL RAX, 8`);
            }
            lines.push(`ADD RAX, RBX`); 
            return { elemSize: meta.elemSize };
        }
        throw new Error("Cannot take address of this expression");
    }

    function genExpr(expr, lines, locals, depth) {
        if (expr.type === 'literal') {
            lines.push(`MOV RAX, ${expr.val}`);
        } else if (expr.type === 'string') {
            const lbl = getStringLabel(expr.val);
            lines.push(`LEA RAX, ${lbl}`);
        } else if (expr.type === 'var') {
            const loc = locals.get(expr.name);
            if (loc) {
                if (loc.isArray) {
                    lines.push(`LEA RAX, [RBP${formatOffset(loc.offset)}]`);
                } else {
                    lines.push(`MOV RAX, [RBP${formatOffset(loc.offset)}]`);
                }
            } else {
                if (definedFunctions.has(expr.name)) {
                     lines.push(`LEA RAX, ${expr.name}`); 
                } else {
                     lines.push(`MOV RAX, [${expr.name}]`);
                }
            }
        } else if (expr.type === 'index') {
            const meta = genAddr(expr, lines, locals, depth);
            if (meta.elemSize === 1) {
                lines.push(`MOVSX RAX, BYTE PTR [RAX]`);
            } else {
                lines.push(`MOV RAX, [RAX]`);
            }
        } else if (expr.type === 'unary') {
            if (expr.op === '*') {
                genExpr(expr.expr, lines, locals, depth);
                let isChar = false;
                if (expr.expr.type === 'var') {
                    const l = locals.get(expr.expr.name);
                    if (l && l.varType.base === 'char' && l.varType.ptr === 1) isChar = true;
                }
                if (isChar) lines.push(`MOVSX RAX, [RAX]`);
                else lines.push(`MOV RAX, [RAX]`);
                
            } else if (expr.op === '&') {
                genAddr(expr.expr, lines, locals, depth);
            } else if (expr.op === '-') {
                genExpr(expr.expr, lines, locals, depth);
                lines.push(`NEG RAX`);
            } else if (expr.op === '!') {
                genExpr(expr.expr, lines, locals, depth);
                lines.push(`CMP RAX, 0`);
                lines.push(`MOV RAX, 0`);
                lines.push(`SETE AL`);
            }
        } else if (expr.type === 'assign') {
            genExpr(expr.right, lines, locals, depth);
            lines.push(`PUSH RAX`); 
            const meta = genAddr(expr.left, lines, locals, depth + 8);
            lines.push(`POP RBX`); 
            if (meta.elemSize === 1) lines.push(`MOV [RAX], BL`);
            else lines.push(`MOV [RAX], RBX`);
            lines.push(`MOV RAX, RBX`); 
        } else if (expr.type === 'binop') {
            genExpr(expr.right, lines, locals, depth);
            lines.push(`PUSH RAX`); 
            genExpr(expr.left, lines, locals, depth + 8);
            lines.push(`POP RBX`);
            
            if (expr.op === '+') lines.push(`ADD RAX, RBX`);
            if (expr.op === '-') lines.push(`SUB RAX, RBX`);
            if (expr.op === '*') lines.push(`IMUL RAX, RBX`);
            if (expr.op === '/') { lines.push(`CQO`); lines.push(`IDIV RBX`); }
            if (expr.op === '%') { lines.push(`CQO`); lines.push(`IDIV RBX`); lines.push(`MOV RAX, RDX`); } // Modulo
            if (expr.op === '==') { lines.push(`CMP RAX, RBX`); lines.push(`MOV RAX, 0`); lines.push(`SETE AL`); }
            if (expr.op === '!=') { lines.push(`CMP RAX, RBX`); lines.push(`MOV RAX, 0`); lines.push(`SETNE AL`); }
            if (expr.op === '<') { lines.push(`CMP RAX, RBX`); lines.push(`MOV RAX, 0`); lines.push(`SETL AL`); }
            if (expr.op === '>') { lines.push(`CMP RAX, RBX`); lines.push(`MOV RAX, 0`); lines.push(`SETG AL`); }
            if (expr.op === '<=') { lines.push(`CMP RAX, RBX`); lines.push(`MOV RAX, 0`); lines.push(`SETLE AL`); }
            if (expr.op === '>=') { lines.push(`CMP RAX, RBX`); lines.push(`MOV RAX, 0`); lines.push(`SETGE AL`); }
            
            // Logical AND/OR (Strictly Boolean 0/1 result, no short-circuit logic in this codegen yet, eager eval)
            if (expr.op === '&&') { lines.push(`AND RAX, RBX`); lines.push(`CMP RAX, 0`); lines.push(`SETNE AL`); }
            if (expr.op === '||') { lines.push(`OR RAX, RBX`); lines.push(`CMP RAX, 0`); lines.push(`SETNE AL`); }

        } else if (expr.type === 'call') {
             const argRegs = ['RCX', 'RDX', 'R8', 'R9'];
             const numArgs = expr.args.length;
             const slots = Math.max(4, numArgs);
             let alloc = slots * 8;
             if ((depth + alloc) % 16 !== 0) alloc += 8;
             
             lines.push(`SUB RSP, ${alloc}`);
             for (let i = 0; i < numArgs; i++) {
                 genExpr(expr.args[i], lines, locals, depth); 
                 lines.push(`MOV [RSP+${i*8}], RAX`);
             }
             for (let i = 0; i < Math.min(4, numArgs); i++) {
                 lines.push(`MOV ${argRegs[i]}, [RSP+${i*8}]`);
             }
             lines.push(`CALL ${expr.name}`);
             lines.push(`ADD RSP, ${alloc}`);
        }
    }
}