// B"H
import { InteractionCompiler as FoodInteractionCompiler } from '../actions/InteractionCompiler.js';
import { InteractionCompiler } from '../../interactions/InteractionCompiler.js';

/** Compiles dialogue, performance, object life, interactions, and automatic shot grammar into timeline events. */
export class DialogueBeatCompiler {
  static compile(beats = []) { return beats.flatMap(beat => [...this.camera(beat), ...this.speech(beat), ...this.listener(beat), ...this.move(beat), ...this.actorActions(beat), ...this.prop(beat), ...InteractionCompiler.compile(beat), ...FoodInteractionCompiler.compile(beat)]).sort((a, b) => (a.start || 0) - (b.start || 0)); }
  static camera(beat) { const hasShot = beat.autoShot || beat.cameraId || beat.shot || beat.shotIntent || beat.targets || beat.angleIntent || beat.movementIntent; return hasShot ? [{ type: 'camera', start: beat.start, end: beat.end, cameraId: beat.cameraId, shot: beat.shot, autoShot: beat.autoShot !== false && Boolean(beat.autoShot || beat.shotIntent || beat.targets), targets: beat.targets || [beat.speaker, beat.listener, beat.prop?.id, beat.objectTarget].filter(Boolean), primaryTarget: beat.primaryTarget || beat.speaker, objectTarget: beat.objectTarget || beat.prop?.id, shotIntent: beat.shotIntent, angleIntent: beat.angleIntent, movementIntent: beat.movementIntent, speaker: beat.speaker, listener: beat.listener, prop: beat.prop?.id, transition: beat.transition || (beat.cut ? 'cut' : 'ease'), duration: beat.transitionDuration || 420 }] : []; }
  static speech(beat) { return beat.speaker && beat.text ? [{ type: 'speech', id: beat.speaker, start: beat.start, end: beat.end, speech: beat.text, emotion: beat.emotion, moment: beat.moment, gesture: beat.gesture, lookAt: beat.listener, attentionTarget: beat.attentionTarget, speechEnergy: beat.speechEnergy, mode: beat.mode || 'subtitle', actions: beat.speechActions || [] }] : []; }
  static listener(beat) { return beat.listener ? [{ type: 'character', id: beat.listener, start: beat.start + 160, end: beat.end + 220, lookAt: beat.speaker, attentionTarget: beat.listenerAttentionTarget, emotion: beat.listenerEmotion || 'attentive', moment: beat.listenerMoment, gesture: beat.reaction || 'react_nod' }] : []; }
  static move(beat) { return beat.move ? [{ type: 'character', id: beat.move.id, start: beat.move.start ?? beat.start, end: beat.move.end ?? beat.end, pos: { from: beat.move.from, to: beat.move.to }, locomotion: beat.move.action || 'walk', gesture: beat.move.gesture || beat.gesture || 'none', view: beat.move.view || 'side', flipX: beat.move.flipX === true, motionMode: 'worldTravel' }] : []; }
  static actorActions(beat) { return (beat.actorActions || []).map(item => ({ type: 'character', id: item.id, start: item.start ?? beat.start, end: item.end ?? beat.end, actions: item.actions || [], ...item })); }
  static prop(beat) { return beat.prop ? [{ type: 'prop', id: beat.prop.id, start: beat.prop.start ?? beat.start, end: beat.prop.end ?? beat.end, propType: beat.prop.propType || beat.prop.type || 'ball', action: beat.prop.action || beat.prop.objectAction || 'slide', objectAction: beat.prop.objectAction, lifecycle: beat.prop.lifecycle || 'moving', from: beat.prop.from, to: beat.prop.to, height: beat.prop.height || 10, size: beat.prop.size || 14, color: beat.prop.color || '#ffd45a' }] : []; }
}
