// B"H
/** @file renderers.js @description Worker UI event renderers preserving public event names. */
import { esc, mount, rows } from "./domCore.js?compact=true&v=compact-all-visible-npc-never-cull-20260708-bh11";
import { markerSymbol, renderWorldQuestMarkers } from "./worldMarkers.js?compact=true&v=compact-all-visible-npc-never-cull-20260708-bh11";
import { safeClone } from "./safeClone.js?compact=true&v=compact-all-visible-npc-never-cull-20260708-bh11";
import { closeAllPanels } from "./closePanels.js?compact=true&v=compact-all-visible-npc-never-cull-20260708-bh11";
const money = r => Number(r?.perutah || r?.money || r?.coins || 0);
function rewards(r = {}) { return `${r.xp ? `<div class="mitzvahReward">XP: ${esc(r.xp)}</div>` : ""}${rows(r.items, id => `<div class="mitzvahReward">Reward: ${esc(id)}</div>`)}${money(r) ? `<div class="mitzvahReward">Perutah: ${money(r)}</div>` : ""}`; }
export function renderQuestTracker(p = {}) { return mount("mitzvahTopRight", "uiQuestTracker", "Shlichus Tracker", rows(p.active, q => `<div class="mitzvahQuestLine ${q.complete ? "mitzvahDone" : ""}"><b>${esc(q.line || q.title)}</b>${rows(q.objectives, o => `<br><small class="${o.complete ? "mitzvahDone" : ""}">${esc(o.line || o.text)}</small>`)}${q.returnTo ? `<br><small>Return to ${esc(q.returnTo)}</small>` : ""}</div>`)); }
export function renderQuestMarkers(p = {}) { renderWorldQuestMarkers(p); return mount("mitzvahTopRight", "uiQuestMarkers", "Quest Markers", rows(p.markers, m => `<div>${markerSymbol(m.marker)} ${esc(m.npcName)} <small>${esc(m.title)}</small></div>`)); }
export function renderQuestPanel(p = {}, mode = "quest") { const state = p.state || (p.ok ? "accepted" : p.reason || mode), obj = rows(p.objectives, o => `<li class="${o.complete ? "mitzvahDone" : ""}">${esc(o.text || o.label || o.line)} ${Number.isFinite(o.current) ? `${o.current}/${o.needed}` : ""}</li>`), id = esc(p.id || p.missionId), npc = esc(p.npcId || "rebbe"); const buttons = `${p.buttons?.accept ? `<button class="mitzvahChoice" onclick="window.__MITZVAH_CHOOSE_NPC__?.('${npc}','accept:${id}')">Accept</button>` : ""}${p.buttons?.complete || p.turnInReady ? `<button class="mitzvahChoice" onclick="window.__MITZVAH_CHOOSE_NPC__?.('${npc}','turnin:${id}')">Complete Shlichus</button>` : ""}`; return mount("mitzvahCenter", "uiQuestPanel", p.title || p.missionId || "Shlichus", `<small>${esc(p.giverNpc || p.returnTo || "Starter Zone")} - ${esc(state)}</small><p>${esc(p.story || p.text || "Carry this shlichus into the world.")}</p><ul>${obj}</ul>${rewards(p.rewards)}${buttons}`, "mitzvahQuestPanel"); }
export function renderGossip(p = {}) { if (!p.open) return null; const choices = rows(p.choices, raw => { const c = typeof raw === "string" ? { id:raw, label:raw } : (raw || {}); return `<button class="mitzvahChoice" data-npc="${esc(p.npcId)}" data-choice="${esc(c.id || c.kind || c.label)}" onclick="window.__MITZVAH_CHOOSE_NPC__?.(this.dataset.npc,this.dataset.choice)">${esc(c.label || c.kind || c.id)}</button>`; }); return mount("mitzvahCenter", "uiGossip", p.npcName || p.title || "NPC", `<p>${esc(p.greeting || p.line || "B'H, how can I help?")}</p>${choices}`); }
export function renderLootSparkle(p = {}) { return mount("mitzvahBottomCenter", "uiLootSparkle", "Loot", rows(p.corpses, c => `<button class="mitzvahChoice mitzvahSparkle" onclick="window.__MITZVAH_OPEN_LOOT__?.('${esc(c.corpseId)}')">* ${esc(c.name || c.corpseId)} sparkles</button>`)); }
export function renderLoot(p = {}) { if (!p.open && !p.looted) return null; const items = rows(p.table?.items, i => `<div class="mitzvahReward">${esc(i.id)} x${i.qty || 1}</div>`), all = p.corpseId && !p.looted ? `<button class="mitzvahChoice" onclick="window.__MITZVAH_LOOT_ALL__?.('${esc(p.corpseId)}')">Loot All</button>` : `<div class="mitzvahDone">Looted</div>`; return mount("mitzvahCenter", "uiLootWindow", p.creatureName || "Loot", `${items}<div class="mitzvahReward">${p.table?.money || p.perutah || 0} perutah</div>${all}`); }
export function renderSimple(title, p = {}) { return mount("mitzvahTopLeft", `ui${title.replace(/\W/g, "")}`, title, `<p>${esc(p.text || p.message || p.status || p.reason || "Ready")}</p>`); }
export function renderMap(p = {}) { const bits = [`${(p.markers || p.discovered || []).length} markers`, p.corpse ? "corpse" : "no corpse", p.hearth ? "hearth bound" : "no hearth"]; return mount("mitzvahTopRight", "uiMiniMap", "Map / FPS", bits.map(esc).join("<br>")); }
export function renderNameplates(p = {}) { const plates = Array.isArray(p) ? p : (p.plates || []); return mount("mitzvahTopLeft", "uiNameplates", "Nameplates", rows(plates, x => `<div>${x.rare ? "* " : ""}${x.elite ? "Elite " : ""}${esc(x.name)} ${x.hp ?? "?"}/${x.maxHp ?? "?"}</div>`)); }
export function renderCastBar(p = {}) { if (!p.active) return mount("mitzvahBottomCenter", "uiCastBar", "Cast", "<span class='mitzvahMuted'>--</span>"); const pct = Math.max(0, Math.min(100, Math.floor((p.progress || 0) * 100))); return mount("mitzvahBottomCenter", "uiCastBar", p.spell || "Cast", `<small>${esc(p.caster)} ${p.interruptible ? "interruptible" : "locked"}</small><div class="mitzvahCastTrack"><div class="mitzvahCastFill" style="width:${pct}%"></div></div>`); }
export function renderLivingWorldVisible(p = {}) { renderQuestTracker(p.questTracker || {}); renderQuestMarkers(p.questMarkers || {}); mount("mitzvahBottomCenter", "uiLivingWorldFeed", "Village Life", rows((p.ambientFeed?.events || []).slice(-6), e => `<div>${esc(String(e.type || e.reason || "event").replace(/_/g, " "))}</div>`)); globalThis.__MITZVAH_LAST_VISIBLE_LIVING_WORLD__ = safeClone(p); return true; }
export function renderStarterHud(p = {}) { if (p.questTracker) renderQuestTracker(p.questTracker); if (p.questMarkers) renderQuestMarkers(p.questMarkers); if (p.minimap) renderMap(p.minimap); if (p.loot) renderLootSparkle(p.loot); if (p.nameplates) renderNameplates(p.nameplates); if (p.castbar) renderCastBar(p.castbar); if (p.activeNpc) renderGossip(p.activeNpc); return true; }
export function rendererMap() { return { livingWorldVisible:renderLivingWorldVisible, starterZoneHud:renderStarterHud, npcGossip:renderGossip, questAccepted:p=>renderQuestPanel(p,"accepted"), questProgress:p=>mount("mitzvahTopLeft","uiQuestProgress","Quest Progress",esc(p.progress || p.objectiveId || "Progress")), questTurnedIn:p=>renderQuestPanel({ ...p, state:"turned-in", story:"Shlichus complete. The reward has entered your pack." },"turned-in"), questTracker:renderQuestTracker, questMarkers:renderQuestMarkers, lootSparkle:renderLootSparkle, loot:renderLoot, spiritHealer:p=>mount("mitzvahCenter","uiSpiritHealer","Spirit Healer",rows(p.choices, c=>`<div class="mitzvahChoice ${c.enabled ? "" : "mitzvahMuted"}">${esc(c.label)}</div>`)), deathState:p=>mount("mitzvahCenter","uiSpiritHealer","Spirit Healer",p.ghost ? "Return to your corpse or ask for help." : "Alive"), minimap:renderMap, mapReveal:renderMap, castBar:renderCastBar, nameplates:renderNameplates, closeTopPanel:closeAllPanels, trainerScreen:p=>renderSimple("Trainer", p), vendorScreen:p=>renderSimple("Vendor", p), innRest:p=>renderSimple("Inn", p), hearthBind:p=>renderSimple("Hearth", p), bankScreen:p=>renderSimple("Bank", p), mailboxScreen:p=>renderSimple("Mailbox", p), worldAnnouncement:p=>mount("mitzvahBottomCenter","uiWorld",p.title || "World",p.text || "Announcement") }; }
