// B"H
/**
 * The single THREE gateway for Mitzvah World.
 *
 * It imports real THREE once and re-exports only symbols the game source asks
 * for. Compact can fold the game around this gateway without multiplying the
 * browser's THREE module identity or dragging unused names into the vessel.
 */
import * as THREE from "/games/scripts/build/three.module.js";
import { createProceduralThreeMesh } from "../../../../libs/awtsmoos-procedural-core/src/adapters/three/index.js";
export { THREE };
export default THREE;
export const ACESFilmicToneMapping = THREE.ACESFilmicToneMapping;
export const AdditiveBlending = THREE.AdditiveBlending;
export const AmbientLight = THREE.AmbientLight;
export const AnimationClip = THREE.AnimationClip;
export const AnimationMixer = THREE.AnimationMixer;
export const BackSide = THREE.BackSide;
export const Bone = THREE.Bone;
export const Box3 = THREE.Box3;
export const Box3Helper = THREE.Box3Helper;
export const BoxGeometry = THREE.BoxGeometry;
export const BufferAttribute = THREE.BufferAttribute;
export const BufferGeometry = THREE.BufferGeometry;
export const Camera = THREE.Camera;
export const CanvasTexture = THREE.CanvasTexture;
export const Capsule = THREE.Capsule;
export const CapsuleGeometry = THREE.CapsuleGeometry;
export const CatmullRomCurve3 = THREE.CatmullRomCurve3;
export const CircleGeometry = THREE.CircleGeometry;
export const ClampToEdgeWrapping = THREE.ClampToEdgeWrapping;
export const Clock = THREE.Clock;
export const Color = THREE.Color;
export const ConeGeometry = THREE.ConeGeometry;
export const CylinderGeometry = THREE.CylinderGeometry;
export const DataTexture = THREE.DataTexture;
export const DirectionalLight = THREE.DirectionalLight;
export const DodecahedronGeometry = THREE.DodecahedronGeometry;
export const DoubleSide = THREE.DoubleSide;
export const DynamicDrawUsage = THREE.DynamicDrawUsage;
export const Euler = THREE.Euler;
export const ExtrudeGeometry = THREE.ExtrudeGeometry;
export const Float32BufferAttribute = THREE.Float32BufferAttribute;
export const Fog = THREE.Fog;
export const FogExp2 = THREE.FogExp2;
export const FrontSide = THREE.FrontSide;
export const GridHelper = THREE.GridHelper;
export const Group = THREE.Group;
export const HalfFloatType = THREE.HalfFloatType;
export const HemisphereLight = THREE.HemisphereLight;
export const IcosahedronGeometry = THREE.IcosahedronGeometry;
export const InstancedBufferAttribute = THREE.InstancedBufferAttribute;
export const InstancedBufferGeometry = THREE.InstancedBufferGeometry;
export const InstancedMesh = THREE.InstancedMesh;
export const Layers = THREE.Layers;
export const Light = THREE.Light;
export const Line3 = THREE.Line3;
export const LineSegments = THREE.LineSegments;
export const LinearFilter = THREE.LinearFilter;
export const LinearMipMapLinearFilter = THREE.LinearMipMapLinearFilter;
export const LinearMipmapLinearFilter = THREE.LinearMipmapLinearFilter;
export const LoopOnce = THREE.LoopOnce;
export const LoopRepeat = THREE.LoopRepeat;
export const Material = THREE.Material;
export const MathUtils = THREE.MathUtils;
export const Matrix3 = THREE.Matrix3;
export const Matrix4 = THREE.Matrix4;
export const Mesh = THREE.Mesh;
export const MeshBasicMaterial = THREE.MeshBasicMaterial;
export const MeshDepthMaterial = THREE.MeshDepthMaterial;
export const MeshLambertMaterial = THREE.MeshLambertMaterial;
export const MeshPhongMaterial = THREE.MeshPhongMaterial;
export const MeshPhysicalMaterial = THREE.MeshPhysicalMaterial;
export const MeshStandardMaterial = THREE.MeshStandardMaterial;
export const MirroredRepeatWrapping = THREE.MirroredRepeatWrapping;
export const NearestFilter = THREE.NearestFilter;
export const Object3D = THREE.Object3D;
export const OctahedronGeometry = THREE.OctahedronGeometry;
export const OrthographicCamera = THREE.OrthographicCamera;
export const PCFSoftShadowMap = THREE.PCFSoftShadowMap;
export const PerspectiveCamera = THREE.PerspectiveCamera;
export const Plane = THREE.Plane;
export const PlaneGeometry = THREE.PlaneGeometry;
export const PointLight = THREE.PointLight;
export const Points = THREE.Points;
export const PointsMaterial = THREE.PointsMaterial;
export const Quaternion = THREE.Quaternion;
export const QuaternionKeyframeTrack = THREE.QuaternionKeyframeTrack;
export const RGBAFormat = THREE.RGBAFormat;
export const Ray = THREE.Ray;
export const Raycaster = THREE.Raycaster;
export const RenderTarget = THREE.RenderTarget;
export const RepeatWrapping = THREE.RepeatWrapping;
export const RingGeometry = THREE.RingGeometry;
export const SRGBColorSpace = THREE.SRGBColorSpace;
export const Scene = THREE.Scene;
export const ShaderChunk = THREE.ShaderChunk;
export const ShaderMaterial = THREE.ShaderMaterial;
export const Shape = THREE.Shape;
export const ShapeGeometry = THREE.ShapeGeometry;
export const Skeleton = THREE.Skeleton;
export const SkinnedMesh = THREE.SkinnedMesh;
export const Sphere = THREE.Sphere;
export const SphereGeometry = THREE.SphereGeometry;
export const Sprite = THREE.Sprite;
export const SpriteMaterial = THREE.SpriteMaterial;
export const Texture = THREE.Texture;
export const TextureLoader = THREE.TextureLoader;
export const TorusGeometry = THREE.TorusGeometry;
export const Triangle = THREE.Triangle;
export const TubeGeometry = THREE.TubeGeometry;
export const Uint16BufferAttribute = THREE.Uint16BufferAttribute;
export const UnsignedByteType = THREE.UnsignedByteType;
export const Vector2 = THREE.Vector2;
export const Vector3 = THREE.Vector3;
export const Vector4 = THREE.Vector4;
export const VectorKeyframeTrack = THREE.VectorKeyframeTrack;
export const WebGL1Renderer = THREE.WebGL1Renderer;
export const WebGLRenderTarget = THREE.WebGLRenderTarget;
export const WebGLRenderer = THREE.WebGLRenderer;
export function awtsmoosThree() { return THREE; }
export function createAwtsmoosMesh(config) { return createProceduralThreeMesh(THREE, config); }
export const THREE_MIGRATION_NOTE = "All game code imports this gateway; direct three.module.js imports are forbidden.";
