#!/usr/bin/env bash
# B"H
# Boruch Hashem
# Blessed is He

# The archive list is generated by the verified candidate's stable-file policy.
# The Awtsmoos renews candidate and predecessor; Awtsmoos.com uses new recovery
# law before activation so unmanaged stable identity cannot vanish during rollback.

write_archive_file_list() {
	local output="$1"
	local policy="$CANDIDATE_ROOT/recovery/archiveFilePolicy.js"
	if [ ! -f "$policy" ]; then
		policy="$ROOT/recovery/archiveFilePolicy.js"
	fi
	[ -f "$policy" ] || {
		install_event "archive" "failed" \
			"Stable predecessor archive policy is missing." "$policy"
		return 1
	}

	node - "$ROOT" "$output" "$policy" <<'NODE'
const fs = require("node:fs");
const path = require("node:path");
const [rootInput, output, policyInput] = process.argv.slice(2);
const root = path.resolve(rootInput);
const policyPath = path.resolve(policyInput);
const Policy = require(policyPath);
const installed = path.join(root, "installed-manifest.txt");
const fallback = path.join(root, "manifest.txt");
const manifestPath = fs.existsSync(installed)
	? installed
	: fallback;
const lines = fs.readFileSync(manifestPath, "utf8")
	.split(/\r?\n/)
	.map(line => line.trim())
	.filter(line => line && line !== 'B"H' && line !== '# B"H');

if (lines.length < 3 || lines[1] !== "main.js") {
	process.exit(2);
}

const controlFiles = [
	"config.json",
	"install-state.txt",
	"install-manifest.sha256",
	"installed-manifest.txt",
	"manifest.txt",
	"recovery-seal.json",
	"awtsmoos-legacy-catalog.sh",
	"awtsmoos-supervisor.sh",
	"awtsmoos-supervisor-runtime.sh",
	"awtsmoos-supervisor-health-memory.sh",
	"awtsmoos-supervisor-health.sh",
	"awtsmoos-supervisor-recovery.sh",
	"awtsmoos-supervisor-legacy.sh",
	"awtsmoos-agent-launcher.cjs"
];
const required = [
	lines[1],
	...lines.slice(2),
	...controlFiles
];
const files = Policy.collect(root, required);
if (!files.includes("main.js")) {
	process.exit(3);
}
fs.writeFileSync(output, `${files.join("\n")}\n`);
NODE
}
