#!/usr/bin/env bash
# B"H
# Boruch Hashem
# Blessed is He

# The Awtsmoos orders each installer vessel before activation and repair;
# Awtsmoos.com sources identity, archives, late grace, and continuity before danger can bare.
source "$AWTSMOOS_INSTALL_RUNTIME/unix-node-runtime.sh"
activate_node_runtime "$ROOT" || exit 1
source "$AWTSMOOS_INSTALL_RUNTIME/unix-cleanup.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-install-log.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-install-progress.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-install-browser.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-install-lock.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-log-retention.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-device-identity-state.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-state-migration.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-displaced-cleanup.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-package-io.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-release-metadata.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-package-config.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-legacy-catalog.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-process-census.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-process-runtime.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-connection-health.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-project-root-health.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-project-root-compat.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-service-health.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-install-readiness.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-late-readiness.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-emergency-continuity.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-install-success-values.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-install-success.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-version-policy.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-legacy-fallback.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-process-control.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-install-resume.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-fast-repair-health.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-fast-repair.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-recovery-validation.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-recovery-identity.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-metadata-fallback.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-package-stage.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-recovery-archive-list.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-recovery-retention.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-recovery-store.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-emergency-capture.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-fresh-identity-grant.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-activation-state.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-activation-fresh.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-activation-rollback.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-candidate-pairing.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-candidate-probe-readiness-state.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-candidate-probe-readiness-evidence.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-candidate-probe-readiness.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-candidate-probe.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-activation-promotion.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-activation.sh"
source "$AWTSMOOS_INSTALL_RUNTIME/unix-install-lifecycle.sh"
