#!/usr/bin/env bash
# B"H
# Boruch Hashem
# Blessed is He

# The archive inventory is generated by the candidate runtime policy, measured, and
# rejected before tar when mutable state or unmanaged growth exceeds safe bounds.
write_archive_file_list() {
	local runtime_root="$1"
	local list_file="$2"
	local manifest_path="$3"
	local policy_path="${4:-$CANDIDATE_ROOT/recovery/archiveFilePolicy.js}"
	local metrics_path="${5:-$(dirname "$list_file")/inventory.json}"
	[ -f "$policy_path" ] || install_fail \
		"archive" "Archive file policy is unavailable." "$policy_path"
	node - "$runtime_root" "$list_file" "$manifest_path" \
		"$policy_path" "$metrics_path" <<'NODE'
const fs = require("node:fs");
const path = require("node:path");
const [runtimeRoot, listFile, manifestPath, policyPath, metricsPath] = process.argv.slice(2);
const Policy = require(path.resolve(policyPath));
const Metrics = require(path.join(path.dirname(path.resolve(policyPath)), "archiveMetrics.js"));
const lines = fs.readFileSync(manifestPath, "utf8")
	.split(/\r?\n/)
	.map(line => line.trim())
	.filter(line => line && line !== 'B"H' && line !== '# B"H');
const required = [
	...lines.slice(2),
	"config.json",
	"install-state.txt",
	"install-manifest.sha256",
	"installed-manifest.txt",
	"recovery-seal.json",
	"awtsmoos-supervisor.sh",
	"awtsmoos-supervisor-runtime.sh"
];
const startedAt = Date.now();
const collected = Policy.collectDetailed(runtimeRoot, required);
const metrics = Metrics.measure(
	runtimeRoot,
	collected.files,
	collected.metrics,
	startedAt
);
const validation = Metrics.validate(metrics);
fs.writeFileSync(metricsPath, `${JSON.stringify({
	...validation,
	generatedAt: new Date().toISOString()
}, null, 2)}\n`);
if (!validation.ok) {
	console.error(`${validation.error}:${metrics.files}:${metrics.bytes}`);
	process.exit(23);
}
fs.writeFileSync(listFile, collected.files.map(file => `${file}\n`).join(""));
NODE
}
