//B"H
import state from'./modules/state.js';import*as Audio from'./audio.js';import*as Network from'./modules/network.js';import*as Store from'./store.js';import*as Render from'./render.js';import*as VideoGen from'./modules/video-gen.js';import*as Browser from'./controllers/browser.js';import{initStudio,closeStudio}from'./modules/studio/index.js';import{initViz}from'./viz.js';import{runBootSequence}from'./ui/boot.js';
export async function init(){await runBootSequence();Render.log("INIT CORE SYSTEM...");let bg=document.getElementById('matrix-bg');if(bg)initViz(bg,()=>Audio.getFreqData());
Render.initUI({onYearSelect:Browser.handleYearSelect,onFolderSelect:Browser.handleFolderSelect,onTrackSelect:Browser.handleTrackSelect,onBack:Browser.handleBack,onPlayPause:Audio.togglePlay,onNext:Browser.handleNext,onPrev:Browser.handlePrev,onSeek:Audio.seek,onSeekRelative:a=>Audio.seek(Audio.audioEl.currentTime+a),onSeekFraction:p=>{if(Audio.audioEl&&Audio.audioEl.duration)Audio.seek(Audio.audioEl.duration*p)},checkStatus:Store.isCached,onDownloadAction:t=>{},onSearch:handleSearch,onSearchResultSelect:handleSearchResultSelect,onClearDB:handleClearDB,onShare:()=>{let u=window.location.href;navigator.clipboard.writeText(u).then(()=>alert("LINK COPIED: "+u))},isPlaying:Audio.isPlaying,
onOpenSliceModal:async()=>{if(Audio.audioEl&&Audio.audioEl.duration>0){Render.openModal('modal-video');Render.updateVideoProgress("OPENING FULL NLE...",.05);await VideoGen.handleAnalyzeVideo(0,Audio.audioEl.duration,state.resolutionSetting||'portrait',state,()=>{Render.closeModal('modal-video');Render.openModal('modal-studio');initStudio()})}else VideoGen.initEmptyStudio(()=>{Render.openModal('modal-studio');initStudio()})},
onAnalyzeVideo:async(s,d,r)=>{await VideoGen.handleAnalyzeVideo(s,d,r,state,()=>{Render.closeModal('modal-video');Render.openModal('modal-studio');initStudio()})},onDownloadAudioSlice:s=>VideoGen.handleDownloadAudioSlice(s),onRenderFinal:s=>VideoGen.renderFinalVideo(s),onCloseStudio:()=>{closeStudio();Render.closeModal('modal-studio')}});
let term=document.getElementById('btn-term-toggle');if(term)term.onclick=()=>Render.toggleTerminal();
Audio.setCallbacks({onUpdate:(c,d)=>{state.currentTime=c;state.currentDuration=d;Render.updatePlayer(state.currentTracks[state.trackIndex]?.title,c,d)},onEnd:Browser.handleNext,onError:()=>Render.log("AUDIO ERROR",true)});
try{await Store.initDB();Render.log("FETCHING INDEX...");let yrs=await Network.fetchIndex();Render.renderYears(yrs,Browser.handleYearSelect);Render.log("READY.");await deepLink()}catch(e){Render.log("BOOT ERROR: "+e.message,true);console.error(e)}}
async function deepLink(){let p=new URLSearchParams(location.search),y=p.get('year');if(!y)return;await Browser.handleYearSelect(y);let f=p.get('folder');if(!f)return;let m=Browser.getFolderMap(),fi=m.indexOf(f);if(fi===-1)return Render.log(`FOLDER NOT FOUND: ${f}`,true);await Browser.handleFolderSelect(fi);let t=p.get('track');if(!t)return;let ti=parseInt(t);if(isNaN(ti))return;setTimeout(async()=>{await Browser.handleTrackSelect(ti);let tm=p.get('time');if(tm)setTimeout(()=>Audio.audioEl&&Audio.seek(parseFloat(tm)),500)},100)}
async function handleSearch(filters){Render.log("SEARCHING DATE INDEX...");try{let res=await Network.search(filters);Render.renderSearchResults(res,handleSearchResultSelect);Render.log(`FOUND ${res.length} ENTRIES`)}catch(e){console.error(e);Render.log("SEARCH FAILED",true)}}
async function handleSearchResultSelect(item){if(!item||!item.year||!item.folder)return;let u=new URL(location);u.searchParams.set('year',String(item.year));u.searchParams.set('folder',item.folder);u.searchParams.set('track','0');u.searchParams.set('autoplay','1');location.href=u.toString()}
async function handleClearDB(){await Store.clearAllTracks();alert("CACHE CLEARED");location.reload()}
init();
