//B"H
const { put, list } = require('./platformStore.js');
function registerMedia({ $i, mediaId, aliasId, metadata={} }) { const media={mediaId,aliasId,metadata,status:'registered',createdAt:Date.now()}; put({$i,shard:'core',parts:['media',mediaId],value:media,meta:{kind:'media'}}); return media; }
function attachMedia({ $i, mediaId, entity={} }) { const attach={mediaId,entity,attachedAt:Date.now()}; put({$i,shard:'graph',parts:['mediaAttachments',mediaId,entity.type,entity.id],value:attach,meta:{kind:'mediaAttachment'}}); return attach; }
function createModerationRecord({ $i, type='report', target={}, actor='', reason='' }) { const id=`mod_${type}_${Date.now()}_${Math.random().toString(36).slice(2)}`; const rec={id,type,target,actor,reason,status:'open',createdAt:Date.now()}; put({$i,shard:'audit',parts:['moderation',type,id],value:rec,meta:{kind:'moderation',type}}); return rec; }
function enqueueJob({ $i, type, payload={}, runAt=Date.now() }) { const id=`job_${Date.now()}_${Math.random().toString(36).slice(2)}`; const job={id,type,payload,runAt,status:'queued',attempts:0,createdAt:Date.now()}; put({$i,shard:'audit',parts:['jobs',type,id],value:job,meta:{kind:'job',type,status:'queued'}}); return job; }
function recordMetric({ $i, name, value=1, tags={} }) { const metric={name,value:Number(value),tags,createdAt:Date.now()}; put({$i,shard:'audit',parts:['analytics',name,metric.createdAt],value:metric,meta:{kind:'metric',name}}); return metric; }
function cacheSet({ $i, key, value, ttlMs=60000 }) { const rec={key,value,expiresAt:Date.now()+Number(ttlMs),createdAt:Date.now()}; put({$i,shard:'feed',parts:['cache',key],value:rec,meta:{kind:'cache'}}); return rec; }
function syncOp({ $i, aliasId, op, payload={} }) { const rec={id:`sync_${Date.now()}_${Math.random().toString(36).slice(2)}`,aliasId,op,payload,createdAt:Date.now()}; put({$i,shard:'audit',parts:['sync',aliasId,rec.id],value:rec,meta:{kind:'syncOp',aliasId}}); return rec; }
function compilePermission({ $i, subject, resource, rules={} }) { const rec={subject,resource,rules,compiledAt:Date.now(),allow:Boolean(rules.allow)}; put({$i,shard:'core',parts:['permissions',subject,resource],value:rec,meta:{kind:'permissionSnapshot'}}); return rec; }
function federationImport({ $i, remoteHeichel, signedPayload={} }) { const rec={id:`fed_${Date.now()}_${Math.random().toString(36).slice(2)}`,remoteHeichel,signedPayload,importedAt:Date.now()}; put({$i,shard:'audit',parts:['federation',remoteHeichel,rec.id],value:rec,meta:{kind:'federationImport'}}); return rec; }
function listOps({ $i, kind }) { return { success:list({$i,shard:'audit',predicate:r=>!kind || r.meta?.kind===kind}).map(r=>r.value) }; }
module.exports={registerMedia,attachMedia,createModerationRecord,enqueueJob,recordMetric,cacheSet,syncOp,compilePermission,federationImport,listOps};
