// B"H
/** @file CottageRoofBuilder.js @description Roof rafters, shingles, ridge beam, and chimney builder. */
import * as THREE from "/games/scripts/build/three.module.js";
import { COTTAGE_BRICK_PALETTE as P } from "../CottageBrickPalette.js";
import { cottageStyleProfile } from "./CottageStyleProfiles.js";
function mat(color){ return new THREE.MeshLambertMaterial({ color, transparent:false, opacity:1, depthWrite:true, depthTest:true }); }
function box(name,size,pos,color,data={}){ const m=new THREE.Mesh(new THREE.BoxGeometry(...size),mat(color)); m.name=name; m.position.set(...pos); Object.assign(m.userData||={},data,{cottageRoofPart:true,opacitySealed:true}); return m; }
function gableMesh(name,w,d,rise,color,data={}){ const shape=new THREE.Shape(); shape.moveTo(-w/2,0); shape.lineTo(0,rise); shape.lineTo(w/2,0); shape.lineTo(-w/2,0); const geo=new THREE.ExtrudeGeometry(shape,{depth:d,bevelEnabled:false}); geo.translate(0,0,-d/2); const mesh=new THREE.Mesh(geo,mat(color)); mesh.name=name; mesh.receiveShadow=true; Object.assign(mesh.userData||={},data,{cottageRoofPart:true,cleanGable:true,opacitySealed:true}); return mesh; }
export function buildCottageRoof(house={}, spec={}){ const style=cottageStyleProfile(house), root=new THREE.Group(), w=(spec.width||house.sx||6.2)+.9, d=(spec.depth||house.sz||5.4)+.9, h=(spec.height||house.sy||3.2)+.14, rise=Math.max(.82,w*.22), roofColor=style.roof||P.roof.color; root.name=`cottage_roof_system_${house.id}`; const roof=gableMesh(`${house.id}_single_clean_gable_roof`,w,d,rise,roofColor,{visualOnly:true,roofGable:true}); roof.position.y=h; root.add(roof); root.add(box(`${house.id}_ridge_beam`,[.22,.2,d+.24],[0,h+rise+.08,0],P.beam.color,{ridge:true})); for(let i=0;i<6;i++){ const z=-d/2+(i+.5)*d/6; const left=box(`${house.id}_left_shingle_row_${i}`,[w*.46,.055,.08],[-w*.18,h+rise*(.58-i*.055),z],P.roof.alt||roofColor,{shingle:true}); left.rotation.z=.42; const right=box(`${house.id}_right_shingle_row_${i}`,[w*.46,.055,.08],[w*.18,h+rise*(.58-i*.055),z],P.roof.alt||roofColor,{shingle:true}); right.rotation.z=-.42; root.add(left,right); } root.add(box(`${house.id}_chimney`,[.42,.9,.42],[w*.22,h+rise+.42,-d*.18],P.foundation.color,{chimney:true, smokeKind:style.smoke})); return root; }
export default buildCottageRoof;
