// B"H
/**
 * Solid cottage roof: two sloped panels, ceiling cap, and gable closures.
 * This is a visual roof made from real closed panels, not an extruded triangle
 * that leaves the house looking opened from mobile camera angles.
 */
import * as THREE from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
import { COTTAGE_BRICK_PALETTE as P } from "../CottageBrickPalette.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { cottageStyleProfile } from "./CottageStyleProfiles.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { materialWithTexture } from "../../../materials/ProceduralTextureKit.js?compact=true&v=ping-pong-crisp-textures-20260622-bh1";
function basic(color){return new THREE.MeshLambertMaterial({color,transparent:false,opacity:1,depthWrite:true,depthTest:true,side:THREE.DoubleSide});}
function roofMat(color){const m=materialWithTexture("brick",{size:256});m.color.set(color);m.name="solid_sloped_cottage_roof_material";m.side=THREE.DoubleSide;return m;}
function box(name,size,pos,mat,data={}){const mesh=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);mesh.name=name;mesh.position.set(...pos);mesh.castShadow=false;mesh.receiveShadow=true;Object.assign(mesh.userData||={},data,{cottageRoofPart:true,opacitySealed:true,skipOctree:true,noOctree:true,visualOnly:true});return mesh;}
function roofPanel(name,w,d,thick,pos,rot,mat,data={}){const mesh=box(name,[w,thick,d],pos,mat,data);mesh.rotation.z=rot;return mesh;}
function gableFill(name,w,rise,z,h,mat,data={}){const shape=new THREE.Shape();shape.moveTo(-w/2,0);shape.lineTo(0,rise);shape.lineTo(w/2,0);shape.lineTo(-w/2,0);const geo=new THREE.ExtrudeGeometry(shape,{depth:.28,bevelEnabled:false});geo.translate(0,0,-.14);const mesh=new THREE.Mesh(geo,mat);mesh.name=name;mesh.position.set(0,h,z);mesh.castShadow=false;mesh.receiveShadow=true;Object.assign(mesh.userData||={},data,{cottageRoofPart:true,gableClosure:true,skipOctree:true,noOctree:true,visualOnly:true,opacitySealed:true});return mesh;}
export function buildCottageRoof(house={},spec={}){const style=cottageStyleProfile(house),root=new THREE.Group(),bodyW=spec.width||house.sx||6.2,bodyD=spec.depth||house.sz||5.4,h=spec.height||house.sy||3.2,w=bodyW+1.35,d=bodyD+1.25,rise=Math.max(1.45,w*.28),slope=Math.atan2(rise,w/2),panelLen=Math.hypot(w/2,rise)+.42,roofColor=style.roof||P.roof.color,rm=roofMat(roofColor),gm=basic(P.wall.color||0xb0714a);root.name=`solid_closed_cottage_roof_${house.id}_bh3`;root.add(roofPanel(`${house.id}_left_solid_sloped_roof_panel`,panelLen,d,.34,[-w*.255,h+rise*.52,0],slope,rm,{leftRoofPanel:true}));root.add(roofPanel(`${house.id}_right_solid_sloped_roof_panel`,panelLen,d,.34,[w*.255,h+rise*.52,0],-slope,rm,{rightRoofPanel:true}));root.add(box(`${house.id}_closed_ceiling_under_roof`,[bodyW+.18,.24,bodyD+.18],[0,h+.02,0],basic(P.beam.color||0x8c5a33),{ceilingClosure:true,noVisibleOpenInterior:true}));root.add(gableFill(`${house.id}_front_solid_gable_closure`,w*.92,rise,d/2+.16,h,gm,{frontGableClosure:true}));root.add(gableFill(`${house.id}_back_solid_gable_closure`,w*.92,rise,-d/2-.16,h,gm,{backGableClosure:true}));root.add(box(`${house.id}_ridge_cap`,[.32,.32,d+.35],[0,h+rise+.08,0],basic(P.beam.color||0x7b3f22),{ridgeCap:true}));root.add(box(`${house.id}_left_eave_board`,[.22,.38,d+.25],[-w/2,h+.18,0],basic(roofColor),{eaveBoard:true}));root.add(box(`${house.id}_right_eave_board`,[.22,.38,d+.25],[w/2,h+.18,0],basic(roofColor),{eaveBoard:true}));root.add(box(`${house.id}_chimney`,[.42,.9,.42],[w*.22,h+rise+.42,-d*.18],basic(P.foundation.color||0x777777),{chimney:true,smokeKind:style.smoke}));Object.assign(root.userData||={}, {solidClosedRoof:true,sealedRoof:true,noOpenRoofEdge:true,noVisibleOpenInterior:true,roofMeshes:9,seal:"solid-two-panel-roof-gable-closures-source-bh3"});return root;}
export default buildCottageRoof;
