// B"H
/** @file build.js @description Three-style octree build: triangles are real objects, not fragile flat indices. */
import { Box3, Triangle, Vector3 } from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
const _half = new Vector3(), _corner = new Vector3();
const MAX_TRIANGLES = 65000;
function sourceAlive(tri) { const s = tri?.sourceMesh; return !s || s.parent || s.userData?.inMainWorld || s.userData?.finalOctreeOnly; }
function copyMeta(to, from) { to.sourceMesh = from.sourceMesh; to.object = from.object || from.sourceMesh || null; return to; }
function triFromAttr(attr, i, matrix, source) { const t = new Triangle(new Vector3().fromBufferAttribute(attr, i), new Vector3().fromBufferAttribute(attr, i + 1), new Vector3().fromBufferAttribute(attr, i + 2)); t.a.applyMatrix4(matrix); t.b.applyMatrix4(matrix); t.c.applyMatrix4(matrix); t.sourceMesh = source; t.object = source; return t; }
export default {
  addTriangle(triangle) { if (!triangle || this.allTriangles.length >= MAX_TRIANGLES) return this; this.bounds.min.min(triangle.a).min(triangle.b).min(triangle.c); this.bounds.max.max(triangle.a).max(triangle.b).max(triangle.c); this.triangles.push(triangle); this.allTriangles.push(triangle); this.isBuilt = false; return this; },
  addDynamicTriangle(triangle) { if (!triangle || (this.box && !this.box.isEmpty() && !this.box.intersectsTriangle(triangle))) return this; const clone = copyMeta(triangle.clone(), triangle); this.dynamicTriangles.push(clone); return this; },
  calcBox() { if (this._isManaged && this.box && !this.box.isEmpty()) return this; this.box = this.bounds.clone(); this.box.min.addScalar(-.01); this.box.max.addScalar(.01); return this; },
  split(level = 0) { if (!this.box || this.triangles.length <= this.trianglesPerLeaf || level >= this.maxLevel) return this; const subTrees = [], half = _half.copy(this.box.max).sub(this.box.min).multiplyScalar(.5); if (half.lengthSq() < 1e-8) return this; for (let x=0;x<2;x++) for (let y=0;y<2;y++) for (let z=0;z<2;z++) { const box = new Box3(); _corner.set(x,y,z); box.min.copy(this.box.min).add(_corner.multiply(half)); box.max.copy(box.min).add(half); const child = new this.constructor(box); child.layers.mask = this.layers.mask; child.trianglesPerLeaf = this.trianglesPerLeaf; child.maxLevel = this.maxLevel; child.allTriangles = this.allTriangles; child.bounds.copy(this.bounds); child._isManaged = this._isManaged; subTrees.push(child); }
    let tri; while ((tri = this.triangles.pop())) for (const child of subTrees) if (child.box.intersectsTriangle(tri)) child.triangles.push(tri);
    for (const child of subTrees) { const len = child.triangles.length; if (len > child.trianglesPerLeaf && level < child.maxLevel) child.split(level + 1); if (len) this.subTrees.push(child); }
    return this; },
  build() { this.subTrees.length = 0; this.triangles = this.allTriangles.filter(sourceAlive); this.allTriangles = this.triangles.slice(); this.bounds.makeEmpty(); for (const tri of this.allTriangles) { this.bounds.min.min(tri.a).min(tri.b).min(tri.c); this.bounds.max.max(tri.a).max(tri.b).max(tri.c); } this.calcBox(); this.split(0); this.isBuilt = true; return this; },
  fromGraphNode(group) { if (!group) return this; group.updateWorldMatrix?.(true, true); group.traverse?.(obj => { if (obj.isMesh !== true || !obj.geometry || !this.layers.test(obj.layers)) return; this.removeMesh(obj, false); let geometry = obj.geometry, temp = false; if (geometry.index) { geometry = geometry.toNonIndexed(); temp = true; } const attr = geometry.getAttribute('position'); for (let i = 0; attr && i + 2 < attr.count && this.allTriangles.length < MAX_TRIANGLES; i += 3) this.addTriangle(triFromAttr(attr, i, obj.matrixWorld, obj)); if (temp) geometry.dispose(); }); return this.build(); },
  removeMesh(mesh, rebuild = true) { const before = this.allTriangles.length; this.allTriangles = this.allTriangles.filter(t => t.sourceMesh !== mesh && t.object !== mesh); this.dynamicTriangles = this.dynamicTriangles.filter(t => t.sourceMesh !== mesh && t.object !== mesh); if (rebuild && before !== this.allTriangles.length) this.build(); return this; },
  pruneDeadTriangles() { const before = this.allTriangles.length; this.allTriangles = this.allTriangles.filter(sourceAlive); this.dynamicTriangles = this.dynamicTriangles.filter(sourceAlive); if (before !== this.allTriangles.length) this.build(); return this; }
};
