// B"H
/** @file intersection.js @description Stable Octree capsule, sphere, box, and ray intersections with source objects. */
import { Box3, Line3, Plane, Sphere, Triangle, Vector3 } from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
import { lineToLineClosestPoints } from './ClosestPoints.js?compact=true&v=stable-three-octree-20260708-bh3';
const _v1=new Vector3(), _v2=new Vector3(), _p1=new Vector3(), _p2=new Vector3(), _plane=new Plane(), _line1=new Line3(), _line2=new Line3(), _box=new Box3(), _sphere=new Sphere();
function alive(tri){const s=tri?.sourceMesh||tri?.object;return !s||s.parent||s.userData?.inMainWorld||s.userData?.finalOctreeOnly;}
function finiteHit(v){return v&&Number.isFinite(v.depth)&&Number.isFinite(v.normal?.x)&&Number.isFinite(v.normal?.y)&&Number.isFinite(v.normal?.z);}
function attach(result, tri){ if (result) { result.triangle = tri; result.object = tri.object || tri.sourceMesh || null; } return result; }
export default {
  getRayTriangles(ray, out){ for(const s of this.subTrees){ if(ray.intersectsBox(s.box)) s.getRayTriangles(ray,out); } for(const t of this.triangles) if(alive(t)&&!out.includes(t)) out.push(t); for(const t of this.dynamicTriangles||[]) if(alive(t)&&!out.includes(t)) out.push(t); },
  getSphereTriangles(sphere,out){ for(const s of this.subTrees){ if(sphere.intersectsBox(s.box)) s.getSphereTriangles(sphere,out); } for(const t of this.triangles) if(alive(t)&&!out.includes(t)) out.push(t); for(const t of this.dynamicTriangles||[]) if(alive(t)&&!out.includes(t)) out.push(t); },
  getBoxTriangles(box,out){ for(const s of this.subTrees){ if(box.intersectsBox(s.box)) s.getBoxTriangles(box,out); } for(const t of this.triangles) if(alive(t)&&!out.includes(t)) out.push(t); for(const t of this.dynamicTriangles||[]) if(alive(t)&&!out.includes(t)) out.push(t); },
  getCapsuleTriangles(capsule,out){ for(const s of this.subTrees){ if(capsule.intersectsBox(s.box)) s.getCapsuleTriangles(capsule,out); } for(const t of this.triangles) if(alive(t)&&!out.includes(t)) out.push(t); for(const t of this.dynamicTriangles||[]) if(alive(t)&&!out.includes(t)) out.push(t); },
  triangleCapsuleIntersect(capsule, triangle){ triangle.getPlane(_plane); const d1=_plane.distanceToPoint(capsule.start)-capsule.radius, d2=_plane.distanceToPoint(capsule.end)-capsule.radius; if((d1>0&&d2>0)||(d1<-capsule.radius&&d2<-capsule.radius)) return false; const denom=Math.abs(d1)+Math.abs(d2); const delta=denom>1e-10?Math.abs(d1/denom):0; const ip=_v1.copy(capsule.start).lerp(capsule.end,delta); if(triangle.containsPoint(ip)) return attach({normal:_plane.normal.clone(),point:ip.clone(),depth:Math.abs(Math.min(d1,d2))}, triangle); const r2=capsule.radius*capsule.radius; _line1.set(capsule.start,capsule.end); const lines=[[triangle.a,triangle.b],[triangle.b,triangle.c],[triangle.c,triangle.a]]; for(const edge of lines){ _line2.set(edge[0],edge[1]); lineToLineClosestPoints(_line1,_line2,_p1,_p2); const d=_p1.distanceTo(_p2); if(d*d<r2){ const n=_p1.clone().sub(_p2); if(n.lengthSq()<1e-10)n.copy(_plane.normal); else n.normalize(); return attach({normal:n,point:_p2.clone(),depth:capsule.radius-d}, triangle); } } return false; },
  triangleBoxIntersect(box, tri){ if(Math.max(tri.a.x,tri.b.x,tri.c.x)<box.min.x||Math.min(tri.a.x,tri.b.x,tri.c.x)>box.max.x||Math.max(tri.a.y,tri.b.y,tri.c.y)<box.min.y||Math.min(tri.a.y,tri.b.y,tri.c.y)>box.max.y||Math.max(tri.a.z,tri.b.z,tri.c.z)<box.min.z||Math.min(tri.a.z,tri.b.z,tri.c.z)>box.max.z) return false; if(!box.intersectsTriangle(tri)) return false; tri.getPlane(_plane); _v1.set(_plane.normal.x>0?box.min.x:box.max.x,_plane.normal.y>0?box.min.y:box.max.y,_plane.normal.z>0?box.min.z:box.max.z); const distance=_plane.distanceToPoint(_v1); return attach({depth:-distance,normal:_plane.normal.clone(),point:_v1.clone().addScaledVector(_plane.normal,distance)}, tri); },
  triangleSphereIntersect(sphere, tri){ tri.getPlane(_plane); if(!sphere.intersectsPlane(_plane)) return false; const depth=Math.abs(_plane.distanceToSphere(sphere)), r2=sphere.radius*sphere.radius-depth*depth, plain=_plane.projectPoint(sphere.center,_v1); if(tri.containsPoint(sphere.center)) return attach({normal:_plane.normal.clone(),point:plain.clone(),depth}, tri); const lines=[[tri.a,tri.b],[tri.b,tri.c],[tri.c,tri.a]]; for(const edge of lines){ _line1.set(edge[0],edge[1]); _line1.closestPointToPoint(plain,true,_v2); const d=_v2.distanceToSquared(sphere.center); if(d<r2)return attach({normal:sphere.center.clone().sub(_v2).normalize(),point:_v2.clone(),depth:sphere.radius-Math.sqrt(d)}, tri); } return false; },
  boxIntersect(box){ if(!this.isBuilt)this.build(); _box.copy(box); const tris=[]; let hit=false,result; this.getBoxTriangles(_box,tris); for(const tri of tris) if((result=this.triangleBoxIntersect(_box,tri))&&finiteHit(result)){hit=true;_box.translate(result.normal.clone().multiplyScalar(Math.min(result.depth,2)));} if(!hit)return false; const cv=_box.getCenter(_v1).sub(box.getCenter(_v2)), depth=cv.length(); return depth>1e-10?{normal:cv.normalize(),depth}:false; },
  sphereIntersect(sphere){ if(!this.isBuilt)this.build(); _sphere.copy(sphere); const tris=[]; let hit=false,result; this.getSphereTriangles(_sphere,tris); for(const tri of tris) if((result=this.triangleSphereIntersect(_sphere,tri))&&finiteHit(result)){hit=true;_sphere.center.add(result.normal.clone().multiplyScalar(Math.min(result.depth,2)));} if(!hit)return false; const cv=_sphere.center.clone().sub(sphere.center), depth=cv.length(); return depth>1e-10?{normal:cv.normalize(),depth}:false; },
  capsuleIntersect(capsule){ if(!this.isBuilt)this.build(); if(!this.box||this.box.isEmpty()||!capsule.intersectsBox(this.box))return false; const c=capsule.clone(), tris=[]; let hit=false,last=false; this.getCapsuleTriangles(c,tris); for(const tri of tris){ const r=this.triangleCapsuleIntersect(c,tri); if(r&&finiteHit(r)){ const d=Math.min(Math.max(r.depth,0),1.2); c.translate(r.normal.clone().multiplyScalar(d)); hit=true; last=r; } } if(!hit)return false; const cv=c.getCenter(_v1).sub(capsule.getCenter(_v2)), depth=cv.length(); return depth>1e-10?{normal:cv.normalize(),depth:Math.min(depth,1.2),object:last?.object,triangle:last?.triangle}:false; },
  rayIntersect(ray){ if(!this.isBuilt)this.build(); if(!this.box||this.box.isEmpty()||!ray.intersectsBox(this.box))return false; const tris=[]; let best=false; this.getRayTriangles(ray,tris); for(const tri of tris){ const p=ray.intersectTriangle(tri.a,tri.b,tri.c,false,_v1); if(!p)continue; const d=ray.origin.distanceTo(p); if(!best||d<best.distance){ const normal=new Vector3(); tri.getNormal(normal); best={distance:d,triangle:tri,position:p.clone(),normal,object:tri.object||tri.sourceMesh||null}; } } return best; },
  getTriangleCount(){return this.allTriangles?.length||0;},
  getTotalTriangleCount(){let n=this.triangles?.length||0;for(const s of this.subTrees||[])n+=s.getTotalTriangleCount();return n;}
};
