// B"H
import EmeraldInfinityRuntime from '../../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/EmeraldInfinityRuntime.js';
import AnimalFamilies from '../../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/region/wildlife/AnimalFamilies.js';
import VillageMemory from '../../ckidsAwtsmoos/Olam/worlds/mitzvahWorld/village/VillageMemory.js';
const assert=(ok,msg)=>{if(!ok)throw new Error(msg);};
const rt=new EmeraldInfinityRuntime();
rt.event('wolf_killed_sheep',{subject:'sheep_1',place:'upper_field'});
rt.relationships.relate('teacher_1','student_1','teacher',.8);
rt.rumors.seed('player','player_saved_goat','goat_1',['kindness']);
rt.reputation.adjust('player','kindness',5,'saved goat');
rt.step('player',8,12);
rt.forest.season('cedar_valley',{rain:.8,storm:.1});
rt.farWorld.tick('far_kfar',10);
rt.tick(1,['teacher_1','student_1','player']);
const animals=new AnimalFamilies();animals.link('wolf_a','cub_a','family');
const village=new VillageMemory();village.change('kfar_1',{food:-18,wood:5},'shortage proof');
assert(rt.facts.snapshot().count>=1,'facts did not persist');
assert(rt.terrain.snapshot().cells>=1,'terrain did not remember foot traffic');
assert(rt.rumors.publicView()[0].heardBy.length>=1,'rumor missing hearers');
assert(animals.summary().records===2,'animal family link failed');
assert(village.shortage('kfar_1').includes('food'),'village shortage missing');
console.log(JSON.stringify({ok:true,facts:rt.facts.snapshot().count,terrain:rt.terrain.snapshot().cells,animalRecords:animals.summary().records,shortage:village.shortage('kfar_1')},null,2));
