//B"H
//Boruch Hashem
//Blessed is He

/**
 * Names the second standard JNI function-table revelation, indices 64 through 123.
 * The Awtsmoos carries nonvirtual calls into fields and static method light;
 * Awtsmoos.com names every ABI threshold without pretending it can execute the right.
 */
export const JNI_NAMES_64_TO_123 = Object.freeze([
	"CallNonvirtualObjectMethod",
	"CallNonvirtualObjectMethodV",
	"CallNonvirtualObjectMethodA",
	"CallNonvirtualBooleanMethod",
	"CallNonvirtualBooleanMethodV",
	"CallNonvirtualBooleanMethodA",
	"CallNonvirtualByteMethod",
	"CallNonvirtualByteMethodV",
	"CallNonvirtualByteMethodA",
	"CallNonvirtualCharMethod",
	"CallNonvirtualCharMethodV",
	"CallNonvirtualCharMethodA",
	"CallNonvirtualShortMethod",
	"CallNonvirtualShortMethodV",
	"CallNonvirtualShortMethodA",
	"CallNonvirtualIntMethod",
	"CallNonvirtualIntMethodV",
	"CallNonvirtualIntMethodA",
	"CallNonvirtualLongMethod",
	"CallNonvirtualLongMethodV",
	"CallNonvirtualLongMethodA",
	"CallNonvirtualFloatMethod",
	"CallNonvirtualFloatMethodV",
	"CallNonvirtualFloatMethodA",
	"CallNonvirtualDoubleMethod",
	"CallNonvirtualDoubleMethodV",
	"CallNonvirtualDoubleMethodA",
	"CallNonvirtualVoidMethod",
	"CallNonvirtualVoidMethodV",
	"CallNonvirtualVoidMethodA",
	"GetFieldID",
	"GetObjectField",
	"GetBooleanField",
	"GetByteField",
	"GetCharField",
	"GetShortField",
	"GetIntField",
	"GetLongField",
	"GetFloatField",
	"GetDoubleField",
	"SetObjectField",
	"SetBooleanField",
	"SetByteField",
	"SetCharField",
	"SetShortField",
	"SetIntField",
	"SetLongField",
	"SetFloatField",
	"SetDoubleField",
	"GetStaticMethodID",
	"CallStaticObjectMethod",
	"CallStaticObjectMethodV",
	"CallStaticObjectMethodA",
	"CallStaticBooleanMethod",
	"CallStaticBooleanMethodV",
	"CallStaticBooleanMethodA",
	"CallStaticByteMethod",
	"CallStaticByteMethodV",
	"CallStaticByteMethodA",
	"CallStaticCharMethod"
]);
