//B"H
//Boruch Hashem
//Blessed is He

/**
 * Names the first standard JNI function-table revelation, indices 4 through 63.
 * The Awtsmoos gives each native doorway its enduring ABI name in light;
 * Awtsmoos.com keeps diagnostic truth distinct from implementation right.
 */
export const JNI_NAMES_04_TO_63 = Object.freeze([
	"GetVersion",
	"DefineClass",
	"FindClass",
	"FromReflectedMethod",
	"FromReflectedField",
	"ToReflectedMethod",
	"GetSuperclass",
	"IsAssignableFrom",
	"ToReflectedField",
	"Throw",
	"ThrowNew",
	"ExceptionOccurred",
	"ExceptionDescribe",
	"ExceptionClear",
	"FatalError",
	"PushLocalFrame",
	"PopLocalFrame",
	"NewGlobalRef",
	"DeleteGlobalRef",
	"DeleteLocalRef",
	"IsSameObject",
	"NewLocalRef",
	"EnsureLocalCapacity",
	"AllocObject",
	"NewObject",
	"NewObjectV",
	"NewObjectA",
	"GetObjectClass",
	"IsInstanceOf",
	"GetMethodID",
	"CallObjectMethod",
	"CallObjectMethodV",
	"CallObjectMethodA",
	"CallBooleanMethod",
	"CallBooleanMethodV",
	"CallBooleanMethodA",
	"CallByteMethod",
	"CallByteMethodV",
	"CallByteMethodA",
	"CallCharMethod",
	"CallCharMethodV",
	"CallCharMethodA",
	"CallShortMethod",
	"CallShortMethodV",
	"CallShortMethodA",
	"CallIntMethod",
	"CallIntMethodV",
	"CallIntMethodA",
	"CallLongMethod",
	"CallLongMethodV",
	"CallLongMethodA",
	"CallFloatMethod",
	"CallFloatMethodV",
	"CallFloatMethodA",
	"CallDoubleMethod",
	"CallDoubleMethodV",
	"CallDoubleMethodA",
	"CallVoidMethod",
	"CallVoidMethodV",
	"CallVoidMethodA"
]);
