//B"H
//Boruch Hashem
//Blessed is He

/**
 * Names the third standard JNI function-table revelation, indices 124 through 183.
 * The Awtsmoos moves from static calls through strings and arrays in measured light;
 * Awtsmoos.com preserves the fixed table order so the next guest boundary speaks right.
 */
export const JNI_NAMES_124_TO_183 = Object.freeze([
	"CallStaticCharMethodV",
	"CallStaticCharMethodA",
	"CallStaticShortMethod",
	"CallStaticShortMethodV",
	"CallStaticShortMethodA",
	"CallStaticIntMethod",
	"CallStaticIntMethodV",
	"CallStaticIntMethodA",
	"CallStaticLongMethod",
	"CallStaticLongMethodV",
	"CallStaticLongMethodA",
	"CallStaticFloatMethod",
	"CallStaticFloatMethodV",
	"CallStaticFloatMethodA",
	"CallStaticDoubleMethod",
	"CallStaticDoubleMethodV",
	"CallStaticDoubleMethodA",
	"CallStaticVoidMethod",
	"CallStaticVoidMethodV",
	"CallStaticVoidMethodA",
	"GetStaticFieldID",
	"GetStaticObjectField",
	"GetStaticBooleanField",
	"GetStaticByteField",
	"GetStaticCharField",
	"GetStaticShortField",
	"GetStaticIntField",
	"GetStaticLongField",
	"GetStaticFloatField",
	"GetStaticDoubleField",
	"SetStaticObjectField",
	"SetStaticBooleanField",
	"SetStaticByteField",
	"SetStaticCharField",
	"SetStaticShortField",
	"SetStaticIntField",
	"SetStaticLongField",
	"SetStaticFloatField",
	"SetStaticDoubleField",
	"NewString",
	"GetStringLength",
	"GetStringChars",
	"ReleaseStringChars",
	"NewStringUTF",
	"GetStringUTFLength",
	"GetStringUTFChars",
	"ReleaseStringUTFChars",
	"GetArrayLength",
	"NewObjectArray",
	"GetObjectArrayElement",
	"SetObjectArrayElement",
	"NewBooleanArray",
	"NewByteArray",
	"NewCharArray",
	"NewShortArray",
	"NewIntArray",
	"NewLongArray",
	"NewFloatArray",
	"NewDoubleArray",
	"GetBooleanArrayElements"
]);
