//B"H
//Boruch Hashem
//Blessed is He

/**
 * Names the conservative WebGL2-class capability floor exposed to GLES guests.
 * The Awtsmoos renews each measured ceiling while Awtsmoos.com keeps the boast small;
 * these values are resource promises the later WebGL2 vessel can honor for all.
 */
export const NATIVE_GLES_CAPABILITY_VALUES = Object.freeze({
	ALIASED_LINE_WIDTH_RANGE: 0x846e,
	ALIASED_POINT_SIZE_RANGE: 0x846d,
	MAJOR_VERSION: 0x821b,
	MAX_3D_TEXTURE_SIZE: 0x8073,
	MAX_ARRAY_TEXTURE_LAYERS: 0x88ff,
	MAX_COLOR_ATTACHMENTS: 0x8cdf,
	MAX_COMBINED_TEXTURE_IMAGE_UNITS: 0x8b4d,
	MAX_CUBE_MAP_TEXTURE_SIZE: 0x851c,
	MAX_DRAW_BUFFERS: 0x8824,
	MAX_FRAGMENT_UNIFORM_VECTORS: 0x8dfd,
	MAX_RENDERBUFFER_SIZE: 0x84e8,
	MAX_SAMPLES: 0x8d57,
	MAX_TEXTURE_IMAGE_UNITS: 0x8872,
	MAX_TEXTURE_LOD_BIAS: 0x84fd,
	MAX_TEXTURE_SIZE: 0x0d33,
	MAX_VARYING_VECTORS: 0x8dfc,
	MAX_VERTEX_ATTRIBS: 0x8869,
	MAX_VERTEX_TEXTURE_IMAGE_UNITS: 0x8b4c,
	MAX_VERTEX_UNIFORM_VECTORS: 0x8dfb,
	MAX_VIEWPORT_DIMS: 0x0d3a,
	MINOR_VERSION: 0x821c
});

const CAPABILITY_VECTORS = new Map([
	[NATIVE_GLES_CAPABILITY_VALUES.ALIASED_LINE_WIDTH_RANGE, values(1, 1)],
	[NATIVE_GLES_CAPABILITY_VALUES.ALIASED_POINT_SIZE_RANGE, values(1, 1)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAJOR_VERSION, values(3)],
	[NATIVE_GLES_CAPABILITY_VALUES.MINOR_VERSION, values(0)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_TEXTURE_SIZE, values(2048)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_CUBE_MAP_TEXTURE_SIZE, values(2048)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_RENDERBUFFER_SIZE, values(2048)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_VIEWPORT_DIMS, values(2048, 2048)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_3D_TEXTURE_SIZE, values(256)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_ARRAY_TEXTURE_LAYERS, values(256)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_TEXTURE_IMAGE_UNITS, values(16)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_VERTEX_TEXTURE_IMAGE_UNITS, values(16)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_COMBINED_TEXTURE_IMAGE_UNITS, values(32)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_VERTEX_ATTRIBS, values(16)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_VERTEX_UNIFORM_VECTORS, values(256)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_FRAGMENT_UNIFORM_VECTORS, values(224)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_VARYING_VECTORS, values(15)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_DRAW_BUFFERS, values(4)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_COLOR_ATTACHMENTS, values(4)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_SAMPLES, values(4)],
	[NATIVE_GLES_CAPABILITY_VALUES.MAX_TEXTURE_LOD_BIAS, values(2)]
]);

/** Returns one immutable numeric state vector for a GLES get-style pname. */
export function findNativeGlesCapabilityValues(pname) {
	const found = CAPABILITY_VECTORS.get(Number(pname));
	return Object.freeze({
		supported: Boolean(found),
		values: found || Object.freeze([])
	});
}

function values(...items) {
	return Object.freeze(items);
}
