// B"H
// Forty doors: each deposit begins as a ceremony, not a form.
const raw = [
["seed","Plant a Seed","Press the earth and hide a bright beginning."],["lantern","Release a Lantern","Let the hachlatah rise into the night."],["star","Repair a Star","Drag a broken point back into the sky."],["flame","Ignite a Flame","Hold until the promise catches fire."],["pebble","Drop a Pebble","Send ripples through a lake of days."],["gate","Open a Gate","Step into the next tiny world."],["crystal","Carve a Crystal","Shape resolve from pressure."],["window","Light a Window","Make one dark house glow."],["branch","Graft a Branch","Add growth to a living tree."],["bell","Tune a Bell","Let one clear sound call the soul."],
["river","Pour a River Drop","Feed the current of return."],["thread","Weave a Thread","Bind today to tomorrow."],["ember","Bury an Ember","Trust the heat beneath the ash."],["mirror","Polish a Mirror","Let the soul see without noise."],["bridge","Build a Bridge","Carry kindness over separation."],["nest","Build a Nest","Make a safe place for another spark."],["scroll","Seal a Scroll","Give your decision a sacred memory."],["crown","Place a Crown","Honor the quiet royal point within."],["well","Open a Well","Draw water for a thirsty future."],["dove","Send a Dove","Let peace fly ahead of you."],
["ladder","Raise a Ladder","Climb by one honest rung."],["harp","Strike a Harp","Tune the day toward rachamim."],["honey","Pour Honey","Sweeten what felt sharp."],["shield","Raise a Shield","Protect speech, time, and trust."],["compass","Open a Compass","Find the north of the neshama."],["rain","Catch Rain","Receive help without shame."],["orchard","Plant an Orchard","Begin what will feed later."],["moon","Repair the Moon","Make borrowed light whole again."],["kite","Raise a Kite","Let joy pull against gravity."],["bowl","Fill a Bowl","Give shape to gratitude."],
["shofar","Sound a Shofar","Wake what fell asleep."],["mezuzah","Touch the Doorpost","Enter the moment with awe."],["ark","Open an Ark","Let hidden holiness become near."],["map","Draw a Map","Turn confusion into a path."],["dewdrop","Gather Dew","Collect small mercies before they vanish."],["cloak","Stitch a Cloak","Cover another person with dignity."],["sail","Raise a Sail","Let a new wind carry you."],["coinriver","Release a Coin River","Let giving flow past the self."],["firefly","Release a Firefly","Make one tiny darkness navigable."],["garden","Open the Garden","Let the whole world answer amen."]
];
const tones = ["soil","sky","repair","fire","water"];
export const rituals = raw.map(([id, name, story], i) => ({ id, name, story, tone: tones[i % tones.length] }));
export const ritualById = id => rituals.find(r => r.id === id) || rituals[0];
export const ritualOptions = () => rituals.map(r => [r.id, r.name, r.story]);
