// B"H

const FOUR_MINUTES_MS = 240000;
const ONE_DAY_MS = 86400000;
const SAFE_RELAY_WAIT_MS = Number(process.env.AWTSMOOS_TUNNEL_RELAY_SAFE_WAIT_MS || 5000);
const PENDING_TTL_MS = Number(process.env.AWTSMOOS_TUNNEL_PENDING_TTL_MS || ONE_DAY_MS);
const COMPLETED_LIMIT = Number(process.env.AWTSMOOS_TUNNEL_COMPLETED_LIMIT || 5000);
const QUARANTINE_LIMIT = Number(process.env.AWTSMOOS_TUNNEL_QUARANTINE_LIMIT || 1000);

module.exports = {
	FOUR_MINUTES_MS,
	ONE_DAY_MS,
	SAFE_RELAY_WAIT_MS,
	PENDING_TTL_MS,
	COMPLETED_LIMIT,
	QUARANTINE_LIMIT
};
