// B"H
/**
 * @file roofAndExterior.js
 * @description
 * Chapter 389: The roof is generated by gable math, not overlapping slabs.
 *
 * Two exact sloped planes meet at one ridge. Their inner edges touch, their
 * outer edges hang only a little beyond the wall, and the end caps are thin
 * triangular gables instead of random red boards fighting each other.
 */
import * as THREE from "/games/scripts/build/three.module.js";
import { add, light, material } from "../geometryKit.js";
import { PICTURE_COLORS as C } from "../palette.js";
import { ENTRANCE_TRIM, OUTSIDE_DETAIL_BLOCKS } from "./houseShellPlan.js?v=split-front-no-mortar-door-20260603-bh369";

const cube = (g, color, p, s, r = [0, 0, 0], mode = "stone", extra = {}) => add(g, "cube", color, p, s, r, { textureMode: mode, ...extra });
const ROOF = Object.freeze({ halfRun: 2.95, halfDepth: 2.82, ridgeY: 3.45, eaveY: 2.74, thickness: 0.16 });

function roofPlane(group, side) {
  const angle = side > 0 ? -0.43 : 0.43;
  const length = Math.hypot(ROOF.halfRun, ROOF.ridgeY - ROOF.eaveY);
  const x = side * ROOF.halfRun * 0.5;
  const y = (ROOF.ridgeY + ROOF.eaveY) * 0.5;
  const mesh = cube(group, C.roof, [x, y, 0], [length, ROOF.thickness, ROOF.halfDepth * 2.06], [0, 0, angle], "roof");
  mesh.name = `mathematical_gable_roof_plane_${side}`;
  return mesh;
}
function ridge(group) { cube(group, C.roofDark, [0, ROOF.ridgeY + 0.065, 0], [0.22, 0.16, ROOF.halfDepth * 2.12], [0, 0, 0], "roof").name = "single_clean_roof_ridge_cap"; }
function eaves(group) {
  cube(group, C.roofDark, [-ROOF.halfRun - 0.13, ROOF.eaveY - 0.05, 0], [0.16, 0.16, ROOF.halfDepth * 2.12], [0, 0, 0.43], "roof").name = "left_short_eave_edge";
  cube(group, C.roofDark, [ROOF.halfRun + 0.13, ROOF.eaveY - 0.05, 0], [0.16, 0.16, ROOF.halfDepth * 2.12], [0, 0, -0.43], "roof").name = "right_short_eave_edge";
}
function gableCapGeometry() {
  const geo = new THREE.BufferGeometry();
  geo.setAttribute("position", new THREE.BufferAttribute(new Float32Array([-ROOF.halfRun, ROOF.eaveY, 0, ROOF.halfRun, ROOF.eaveY, 0, 0, ROOF.ridgeY, 0]), 3));
  geo.setIndex([0, 1, 2]);
  geo.computeVertexNormals();
  return geo;
}
function gableCap(group, z, name) {
  const mesh = new THREE.Mesh(gableCapGeometry(), material(C.stone, { textureMode: "stone" }));
  mesh.name = name;
  mesh.position.z = z;
  mesh.userData.skipOctree = true;
  group.add(mesh);
}
function framedWindow(group, x, z = 2.55) {
  cube(group, C.wood, [x, 1.42, z], [0.86, 0.6, 0.12], [0, 0, 0], "wood");
  cube(group, C.warm, [x, 1.42, z + 0.065], [0.54, 0.36, 0.075], [0, 0, 0], "cloth", { emissive: C.warm, emissiveIntensity: 0.34 });
  cube(group, C.wood, [x, 1.42, z + 0.12], [0.08, 0.5, 0.08], [0, 0, 0], "wood");
  cube(group, C.wood, [x, 1.42, z + 0.13], [0.54, 0.08, 0.08], [0, 0, 0], "wood");
  cube(group, C.wood, [x, 1.08, z + 0.1], [0.98, 0.1, 0.16], [0, 0, 0], "wood");
  light(group, C.warm, [x, 1.42, z + 0.46], 0.34, 4.8);
}
export function buildDoorTrim(group) { for (const block of ENTRANCE_TRIM) { const mesh = cube(group, block.color, block.p, block.s, [0, 0, 0], block.mode); mesh.name = block.name; } }
export function buildWindowsRoofAndExterior(group) {
  framedWindow(group, -2.25);
  framedWindow(group, 2.25);
  gableCap(group, -ROOF.halfDepth - 0.025, "rear_triangular_gable_wall_under_roof");
  gableCap(group, ROOF.halfDepth + 0.025, "front_triangular_gable_wall_under_roof");
  roofPlane(group, -1);
  roofPlane(group, 1);
  ridge(group);
  eaves(group);
  for (const block of OUTSIDE_DETAIL_BLOCKS) cube(group, block.color, block.p, block.s, [0, 0, 0], block.mode);
}
