// B"H
/** @file roofAndExterior.js @description High-quality Jewish cottage exterior with mezuzah, shutters, warm windows, clean roof, chimney, and planters. */
import * as THREE from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
import { add, light, material } from "../geometryKit.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { PICTURE_COLORS as C } from "../palette.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { ENTRANCE_TRIM, OUTSIDE_DETAIL_BLOCKS } from "./houseShellPlan.js?compact=true&v=jewish-house-quality-20260621-bh1";

const cube = (g, color, p, s, r = [0, 0, 0], mode = "stone", extra = {}) => add(g, "cube", color, p, s, r, { textureMode:mode, ...extra });
const ROOF = Object.freeze({ halfRun:2.95, halfDepth:2.82, ridgeY:3.45, eaveY:2.74, thickness:.16 });

function roofPlane(group, side) { const angle = side > 0 ? -.43 : .43, length = Math.hypot(ROOF.halfRun, ROOF.ridgeY - ROOF.eaveY); const mesh = cube(group, C.roof, [side * ROOF.halfRun * .5, (ROOF.ridgeY + ROOF.eaveY) * .5, 0], [length, ROOF.thickness, ROOF.halfDepth * 2.08], [0, 0, angle], "roof"); mesh.name = `clean_single_gable_roof_plane_${side}`; return mesh; }
function ridge(group) { cube(group, C.roofDark, [0, ROOF.ridgeY + .065, 0], [.22, .16, ROOF.halfDepth * 2.16], [0, 0, 0], "roof").name = "single_clean_roof_ridge_cap"; }
function roofRows(group) { for (let i = 0; i < 11; i++) { const t = i / 10, y = ROOF.eaveY + .08 + t * (ROOF.ridgeY - ROOF.eaveY - .08), x = ROOF.halfRun - t * ROOF.halfRun; cube(group, C.roofDark, [-x, y, 0], [.065, .07, ROOF.halfDepth * 2.2], [0, 0, .43], "roof"); cube(group, C.roofDark, [x, y, 0], [.065, .07, ROOF.halfDepth * 2.2], [0, 0, -.43], "roof"); } }
function eaves(group) { cube(group, C.roofDark, [-ROOF.halfRun - .13, ROOF.eaveY - .05, 0], [.16, .16, ROOF.halfDepth * 2.15], [0, 0, .43], "roof"); cube(group, C.roofDark, [ROOF.halfRun + .13, ROOF.eaveY - .05, 0], [.16, .16, ROOF.halfDepth * 2.15], [0, 0, -.43], "roof"); }
function gableCapGeometry() { const geo = new THREE.BufferGeometry(); geo.setAttribute("position", new THREE.BufferAttribute(new Float32Array([-ROOF.halfRun, ROOF.eaveY, 0, ROOF.halfRun, ROOF.eaveY, 0, 0, ROOF.ridgeY, 0]), 3)); geo.setIndex([0, 1, 2]); geo.computeVertexNormals(); return geo; }
function gableCap(group, z, name) { const mesh = new THREE.Mesh(gableCapGeometry(), material(C.stone, { textureMode:"stone" })); mesh.name = name; mesh.position.z = z; mesh.userData.skipOctree = true; group.add(mesh); }
function windowFrame(group, x, z = 2.56, name = "front") { cube(group, C.wood, [x, 1.42, z], [.98, .7, .12], [0, 0, 0], "wood").name = `${name}_outer_window_frame`; cube(group, C.warm, [x, 1.42, z + .07], [.62, .42, .075], [0, 0, 0], "cloth", { emissive:C.warm, emissiveIntensity:.8 }).name = `${name}_warm_window_glass`; cube(group, C.darkWood, [x, 1.42, z + .13], [.07, .58, .08], [0, 0, 0], "wood"); cube(group, C.darkWood, [x, 1.42, z + .14], [.62, .07, .08], [0, 0, 0], "wood"); cube(group, C.darkWood, [x - .62, 1.42, z + .04], [.12, .72, .09], [0, 0, .08], "wood").name = `${name}_left_shutter`; cube(group, C.darkWood, [x + .62, 1.42, z + .04], [.12, .72, .09], [0, 0, -.08], "wood").name = `${name}_right_shutter`; cube(group, C.wood, [x, 1.06, z + .1], [1.12, .1, .16], [0, 0, 0], "wood").name = `${name}_window_sill`; light(group, C.warm, [x, 1.42, z + .48], .5, 5.8); }
function mezuzah(group) { const m = cube(group, 0xd9c27a, [.91, 1.72, 3.085], [.045, .42, .055], [0, 0, -.18], "cloth", { emissive:0x4a3400, emissiveIntensity:.18 }); m.name = "right_doorpost_mezuzah_case_visible"; m.userData.jewishDetail = "mezuzah"; }
function entry(group) { for (const b of ENTRANCE_TRIM) { const mesh = cube(group, b.color, b.p, b.s, [0, 0, 0], b.mode); mesh.name = b.name; } mezuzah(group); cube(group, C.darkWood, [0, 2.57, 3.04], [1.95, .08, .11], [0, 0, 0], "wood").name = "strong_entry_header_beam"; }
function chimney(group) { cube(group, C.stoneDark, [1.78, 3.58, -1.4], [.42, .92, .42], [0, 0, 0], "stone").name = "warm_stone_chimney_stack"; cube(group, C.roofDark, [1.78, 4.08, -1.4], [.56, .16, .56], [0, 0, 0], "roof").name = "small_chimney_cap"; }
function gableTrim(group) { for (const z of [2.95, -2.95]) { cube(group, C.darkWood, [-1.46, 3.12, z], [3.15, .09, .1], [0, 0, .43], "wood"); cube(group, C.darkWood, [1.46, 3.12, z], [3.15, .09, .1], [0, 0, -.43], "wood"); } }
function lamps(group) { for (const x of [-1.08, 1.08]) { cube(group, C.warm, [x, 2.07, 3.07], [.12, .24, .08], [0, 0, 0], "cloth", { emissive:C.warm, emissiveIntensity:1.1 }); light(group, C.warm, [x, 2.08, 3.38], .42, 4.4); } }
function planters(group) { [-3.05, 3.05].forEach((x, index) => { cube(group, 0x6b3a1f, [x, .22, 2.72], [.5, .28, .34], [0, 0, 0], "wood").name = `front_planter_box_${index}`; for (let i = 0; i < 6; i++) cube(group, i % 2 ? C.pinkFlower : C.yellowFlower, [x - .24 + i * .096, .45 + i * .01, 2.84], [.055, .085, .055], [0, i, 0], "cloth"); }); }
function rearDetails(group) { windowFrame(group, -1.7, -2.96, "rear_left"); windowFrame(group, 1.7, -2.96, "rear_right"); }

export function buildDoorTrim(group) { entry(group); }
export function buildWindowsRoofAndExterior(group) { windowFrame(group, -2.25, 2.56, "front_left"); windowFrame(group, 2.25, 2.56, "front_right"); rearDetails(group); gableCap(group, -ROOF.halfDepth - .025, "rear_triangular_gable_wall_under_roof"); gableCap(group, ROOF.halfDepth + .025, "front_triangular_gable_wall_under_roof"); roofPlane(group, -1); roofPlane(group, 1); ridge(group); roofRows(group); eaves(group); chimney(group); gableTrim(group); entry(group); lamps(group); planters(group); for (const block of OUTSIDE_DETAIL_BLOCKS) cube(group, block.color, block.p, block.s, [0, 0, 0], block.mode); }
