// B"H
/**
 * @file AnimalBodyForge.js
 * @description
 * Chapter 448: the animal forge uses real geelooy/libs math and corrected paths.
 */
import * as THREE from "/games/scripts/build/three.module.js";
import FurGenerator from "../../../../../../utils/TextureForge/Generators/Fur.js?v=fur-generator-20260614-bh1";
import { speciesProfile } from "./AnimalSpeciesProfiles.js?v=realistic-wildlife-profiles-20260614-bh1";
import { hash, finite } from "../../../../../../../../../libs/awtsmoos3d/math.js?v=animal-forge-20260614-bh1";
const MAT_CACHE = new Map();
function textureFor(fur) { const canvas = FurGenerator.generate(fur, 384, 384); const tex = new THREE.CanvasTexture(canvas); tex.colorSpace = THREE.SRGBColorSpace; tex.wrapS = tex.wrapT = THREE.RepeatWrapping; tex.repeat.set(1.8, 1.2); tex.userData.furType = fur; return tex; }
function furMaterial(fur) { if (MAT_CACHE.has(fur)) return MAT_CACHE.get(fur); const mat = new THREE.MeshLambertMaterial({ map: textureFor(fur), color: 0xffffff }); mat.name = `animal_fur_material_${fur}`; mat.userData.furTexture = fur; MAT_CACHE.set(fur, mat); return mat; }
function colorMat(name, color) { const key = `${name}:${color}`; if (!MAT_CACHE.has(key)) MAT_CACHE.set(key, new THREE.MeshLambertMaterial({ color })); return MAT_CACHE.get(key); }
function ellipsoid(size, pos, rot = [0,0,0], seg = 12) { const geo = new THREE.SphereGeometry(.5, seg, Math.max(6, Math.floor(seg*.65))); geo.scale(size[0], size[1], size[2]); geo.rotateX(rot[0] || 0); geo.rotateY(rot[1] || 0); geo.rotateZ(rot[2] || 0); geo.translate(pos[0], pos[1], pos[2]); return geo; }
function cone(size, pos, rot = [0,0,0], seg = 10) { const geo = new THREE.ConeGeometry(.5, 1, seg); geo.scale(size[0], size[1], size[2]); geo.rotateX(rot[0] || 0); geo.rotateY(rot[1] || 0); geo.rotateZ(rot[2] || 0); geo.translate(pos[0], pos[1], pos[2]); return geo; }
function cyl(size, pos, rot = [0,0,0], seg = 8) { const geo = new THREE.CylinderGeometry(.5,.5,1,seg); geo.scale(size[0], size[1], size[2]); geo.rotateX(rot[0] || 0); geo.rotateY(rot[1] || 0); geo.rotateZ(rot[2] || 0); geo.translate(pos[0], pos[1], pos[2]); return geo; }
function mergeGeometries(items) { const geometries = items.filter(Boolean); const positions = [], normals = [], uvs = [], indices = []; let offset = 0; for (const g of geometries) { const p = g.getAttribute("position"), n = g.getAttribute("normal"), uv = g.getAttribute("uv"); for (let i=0;i<p.count;i++) positions.push(p.getX(i),p.getY(i),p.getZ(i)); for (let i=0;i<p.count;i++) normals.push(n?.getX(i)||0,n?.getY(i)||1,n?.getZ(i)||0); for (let i=0;i<p.count;i++) uvs.push(uv?.getX(i)||0,uv?.getY(i)||0); if (g.index) for (let i=0;i<g.index.count;i++) indices.push(g.index.getX(i)+offset); else for (let i=0;i<p.count;i++) indices.push(i+offset); offset += p.count; } const out = new THREE.BufferGeometry(); out.setAttribute("position", new THREE.Float32BufferAttribute(positions,3)); out.setAttribute("normal", new THREE.Float32BufferAttribute(normals,3)); out.setAttribute("uv", new THREE.Float32BufferAttribute(uvs,2)); out.setIndex(indices); out.computeVertexNormals(); out.computeBoundingBox(); out.computeBoundingSphere(); geometries.forEach(g=>g.dispose?.()); return out; }
function bodyGeometry(profile) { const b = profile.body; return mergeGeometries([ellipsoid(b.torso, [0, profile.height*.62, 0]), ellipsoid(b.chest, [0, profile.height*.72, b.torso[2]*.34]), ellipsoid(b.hips, [0, profile.height*.58, -b.torso[2]*.34]), ellipsoid(b.neck, [0, profile.height*.95, b.torso[2]*.57], [.35,0,0]), ellipsoid(b.head, [0, profile.height*1.08, b.torso[2]*.82]), cone(b.snout, [0, profile.height*1.02, b.torso[2]*1.1], [Math.PI/2,0,0])]); }
function addPart(root, key, mesh) { mesh.name = `animal_${key}`; root.userData.parts[key] = mesh; root.add(mesh); return mesh; }
function makeMesh(geometry, material, pos=[0,0,0], scale=[1,1,1], rot=[0,0,0]) { const m = new THREE.Mesh(geometry, material); m.position.set(...pos); m.scale.set(...scale); m.rotation.set(...rot); m.castShadow = false; m.receiveShadow = true; return m; }
function addLegs(root, profile, fur) { const l = profile.legs, mat = furMaterial(fur); for (const side of [-1,1]) for (const fore of [-1,1]) { const back = fore < 0, scale = l.hindScale && back ? l.hindScale : 1; const x=side*l.stanceX, z=fore*l.stanceZ; addPart(root,`leg_${side}_${fore}_upper`,makeMesh(cyl([l.thickness,l.length*.55*scale,l.thickness],[0,0,0]),mat,[x,profile.height*.32,z],[1,1,1],[0,0,side*.08])); addPart(root,`leg_${side}_${fore}_lower`,makeMesh(cyl([l.thickness*.82,l.length*.5*scale,l.thickness*.82],[0,0,0]),mat,[x,profile.height*.08,z+.05*fore],[1,1,1],[fore*.12,0,side*.05])); addPart(root,`foot_${side}_${fore}`,makeMesh(ellipsoid(l.foot,[0,0,0],[0,0,0],8),mat,[x,profile.height*.02,z+.13*fore])); if(l.sock) addPart(root,`sock_${side}_${fore}`,makeMesh(cyl([l.thickness*.92,l.length*.22,l.thickness*.92],[0,0,0]),colorMat("darkSock",0x211611),[x,profile.height*.03,z+.04*fore])); } }
function addEars(root, profile, fur) { const e = profile.ears; if (!e.height) return; const mat = furMaterial(fur); for (const side of [-1,1]) addPart(root,`ear_${side}`,makeMesh(cone([e.width,e.height,e.width*.7],[0,0,0]),mat,[side*profile.body.head[0]*.38,profile.height*1.35,profile.body.torso[2]*.82],[1,1,1],[0,0,side*.28])); }
function addTail(root, profile, fur) { const t=profile.tail; if(!t.length) return; const tail = makeMesh(cyl([t.radius,t.length,t.radius],[0,0,0]),furMaterial(fur),[0,profile.height*.72,-profile.body.torso[2]*.72],[1,1,1],[Math.PI/2,0,0]); addPart(root,"tail",tail); if(t.tip) addPart(root,"tail_tip",makeMesh(ellipsoid([t.radius*1.18,t.radius*.9,t.radius*1.18],[0,0,0],[0,0,0],8),colorMat("tailTip",0xfff3d8),[0,profile.height*.72,-profile.body.torso[2]*.72-t.length*.5])); }
function addFace(root, profile) { const eyeMat=colorMat("eye",profile.colors.eye||0x050505), white=colorMat("muzzleWhite",0xf4ead2); for (const s of [-1,1]) addPart(root,`eye_${s}`,makeMesh(ellipsoid([.045,.045,.045],[0,0,0],[0,0,0],8),eyeMat,[s*profile.body.head[0]*.28,profile.height*1.12,profile.body.torso[2]*1.08])); if(profile.markings.muzzle) addPart(root,"muzzle_patch",makeMesh(ellipsoid([profile.body.head[0]*.32,.07,.18],[0,0,0],[0,0,0],8),white,[0,profile.height*.98,profile.body.torso[2]*1.1])); if(profile.markings.chest||profile.markings.belly) addPart(root,"belly_patch",makeMesh(ellipsoid([profile.body.torso[0]*.38,.08,profile.body.torso[2]*.35],[0,0,0],[0,0,0],8),white,[0,profile.height*.47,profile.body.torso[2]*.18])); }
function addHornsWings(root, profile) { if(profile.markings.horns){ const horn=colorMat("horn",0xd8c28c); for(const s of[-1,1]) addPart(root,`horn_${s}`,makeMesh(cone([.06,.35,.06],[0,0,0]),horn,[s*.16,profile.height*1.38,profile.body.torso[2]*.72],[1,1,1],[-.22,0,s*.18])); } if(profile.wings){ const mat=furMaterial(profile.fur); for(const s of[-1,1]) addPart(root,`wing_${s}`,makeMesh(ellipsoid([.08,.25,.48],[0,0,0],[0,0,0],8),mat,[s*.33,profile.height*.7,0],[1,1,1],[0,0,s*.9])); } }
function addShadow(root, profile) { const g=new THREE.CircleGeometry(Math.max(profile.body.torso[0],profile.body.torso[2])*.62,24), m=new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.18,depthWrite:false}); const shadow=new THREE.Mesh(g,m); shadow.name="animal_soft_shadow"; shadow.rotation.x=-Math.PI/2; shadow.position.y=.012; shadow.userData.skipRaycast=true; root.add(shadow); }
export function buildAnimal(species="rabbit", data={}) { const profile=speciesProfile(species), root=new THREE.Group(); root.name=`realistic_${species}_${data.id||Math.floor(hash(finite(data.x),finite(data.z))*9999)}`; root.userData.parts={}; const body=new THREE.Mesh(bodyGeometry(profile),furMaterial(profile.fur)); body.name="solid_fur_textured_body_mesh"; body.castShadow=false; body.receiveShadow=true; root.add(body); addLegs(root,profile,profile.fur); addEars(root,profile,profile.fur); addTail(root,profile,profile.fur); addFace(root,profile); addHornsWings(root,profile); addShadow(root,profile); Object.assign(root.userData,{wildlifeActor:true,species,furType:profile.fur,solidAnimalBody:true,selectableCombatTarget:true,realisticAnimal:true,parts:root.userData.parts,profile}); root.traverse(o=>Object.assign(o.userData||={}, {animalPart:true,skipOctree:true,noOctree:true})); return root; }
