/* B"H */
import assert from 'node:assert/strict';
import { createAssetDatabase, addAssetRecord, getAssetRecord } from '../modules/bin/AssetDatabase.js';
import { createMetadataStore, setMetadata } from '../modules/bin/MetadataStore.js';
import { createAssetIndexer, indexAsset } from '../modules/bin/AssetIndexer.js';
import { searchAssets } from '../modules/bin/SearchEngine.js';
import { createProxyManager, queueProxy, markProxyReady } from '../modules/bin/ProxyManager.js';
import { createThumbnailDescriptor, addThumbnail } from '../modules/bin/ThumbnailGenerator.js';
import { createRelinkEngine, markOffline, relinkAsset } from '../modules/bin/RelinkEngine.js';
import { createEffectStack, addEffect, applyEffectStack } from '../modules/effects/EffectStack.js';
import { createTransformEffect } from '../modules/effects/TransformEffect.js';
import { createCropEffect } from '../modules/effects/CropEffect.js';
import { createColorCorrection, correctPixel } from '../modules/effects/ColorCorrection.js';
import { createChromaKeyEffect, chromaAlpha } from '../modules/effects/ChromaKeyEffect.js';
import { createColorPipeline, processPixels } from '../modules/color/ColorPipeline.js';
import { createLUTManager, registerLUT, getLUT } from '../modules/color/LUTManager.js';
import { sampleRGB, averageRGB } from '../modules/color/RGBScope.js';
import { createSubtitleTrack, addCue, cuesAt } from '../modules/titles/SubtitleTrack.js';
import { exportVtt } from '../modules/titles/CaptionExporter.js';
import { importSimpleVtt } from '../modules/titles/CaptionImporter.js';
import { createTitleLayer, titleAtTime } from '../modules/titles/TitleLayer.js';
const db = createAssetDatabase();
const asset = addAssetRecord(db, { id:'asset-1', name:'Interview A', mediaKind:'video', tags:['talk'], uri:'/tmp/source.mov' });
assert.equal(getAssetRecord(db, 'asset-1').name, 'Interview A');
const store = createMetadataStore(); setMetadata(store, asset.id, { camera:'A' }); asset.metadata = store.records[asset.id];
const indexer = createAssetIndexer(); assert.ok(indexAsset(indexer, asset).includes('interview'));
assert.equal(searchAssets(db.assets, 'camera').length, 1);
const proxy = queueProxy(createProxyManager(), asset); markProxyReady(proxy, 'proxy.mp4'); assert.equal(asset.proxies[0].status, 'ready');
addThumbnail(asset, createThumbnailDescriptor(asset, { time:1 })); assert.equal(asset.thumbnails.length, 1);
const relink = createRelinkEngine(); markOffline(asset); relinkAsset(relink, asset, '/new/source.mov'); assert.equal(asset.offline, false);
const stack = createEffectStack(); addEffect(stack, createTransformEffect({ position:{ x:5, y:7 }, scale:{ x:2, y:1 }, opacity:.5 })); addEffect(stack, createCropEffect({ left:2 }));
const target = applyEffectStack({ x:1, y:1, w:10, h:10, opacity:1 }, stack); assert.deepEqual([target.x, target.y, target.w, target.opacity, target.crop.left], [6,8,20,.5,2]);
assert.equal(chromaAlpha([0,255,0,255], createChromaKeyEffect({ tolerance:1 })), 0);
assert.deepEqual(correctPixel([10,20,30,255], createColorCorrection({ exposure:10 })), [20,30,40,255]);
const luts = createLUTManager(); registerLUT(luts, 'invert', ([r,g,b,a=255]) => [255-r,255-g,255-b,a]);
const pipe = createColorPipeline({ lut:getLUT(luts, 'invert') }); assert.deepEqual(processPixels(pipe, [[10,20,30,255]])[0], [245,235,225,255]);
assert.equal(Math.round(averageRGB(sampleRGB([[10,20,30],[30,40,50]])).r), 20);
const track = createSubtitleTrack(); addCue(track, { start:1, end:2, text:'Hello' }); assert.equal(cuesAt(track, 1.5)[0].text, 'Hello');
const vtt = exportVtt(track); assert.ok(vtt.includes('WEBVTT'));
assert.equal(importSimpleVtt(vtt).cues[0].text, 'Hello');
assert.equal(titleAtTime(createTitleLayer({ start:2, duration:3 }), 4), true);
console.log(JSON.stringify({ ok:true, assets:db.assets.length, proxies:asset.proxies.length, cues:track.cues.length, hist:pipe.scopes.histogram.luma.reduce((a,b)=>a+b,0) }));
