// B"H
/**
 * @file GeometryEngine.js
 * @description Manifest geometry engine with parser-clear variable resolution and no legacy tree generator.
 */
import * as THREE from "/games/scripts/build/three.module.js";
import { getMaterial } from "./materials/MaterialFactory.js?v=awtsmoos-material-factory-20260614-bh2";
import { GeometryModifiers } from "./GeometryModifiers.js?v=awtsmoos-geometry-modifiers-20260614-bh2";
import { ProceduralGeometryFactory } from "./ProceduralGeometryFactory.js?v=awtsmoos-procedural-geometry-20260614-bh2";
import { shapeGeometry } from "./procedural/ShapeGeometryFactory.js?v=awtsmoos-json-shapes-20260619-bh1";
import { geometryFromAwtsmoosMeshData } from "./procedural/AwtsmoosProceduralMeshBridge.js?v=awtsmoos-core-mesh-bridge-20260619-bh1";
function varsOf(blueprint, context) { return Object.assign({}, blueprint.variables || {}, context.vars || {}); }
function resolveWith(vars, value) { if (typeof value !== "string" || !value.includes("$")) return value; let expression = value; for (const key of Object.keys(vars).sort((a,b)=>b.length-a.length)) expression = expression.split("$" + key).join(vars[key]); try { return new Function(`return (${expression.replace(/\$/g, "")})`)(); } catch (_) { return expression; } }
function list(value) { return Array.isArray(value) ? value : []; }
export class GeometryEngine {
  static manifest(blueprint, context = {}) { const group = new THREE.Group(), vars = varsOf(blueprint, context), resolve = value => resolveWith(vars, value); const local = Object.assign({}, context, { vars, resolve }); for (const comp of list(blueprint.components)) { try { this._processComponent(group, comp, local); } catch (error) { console.error("B\"H - GeometryEngine component error", comp, error); } } return group; }
  static _processComponent(group, comp, ctx) { const resolve = ctx.resolve; if (comp.type === "group") { const sub = this.manifest({ components:list(comp.children || comp.components), variables:ctx.vars }, ctx), p = list(comp.position || [0,0,0]).map(resolve), r = list(comp.rotation || [0,0,0]).map(resolve); sub.name = comp.name || "json_component_group"; sub.position.set(p[0] || 0, p[1] || 0, p[2] || 0); sub.rotation.set(r[0] || 0, r[1] || 0, r[2] || 0); group.add(sub); return; } if (comp.type === "repeat" || comp.type === "array") { const count = resolve(comp.count || comp.params?.count) || 0, offset = list(comp.offset || comp.params?.offset || [0,0,0]).map(resolve); for (let i=0; i<count; i++) { const sub = this.manifest({ components:[comp.component], variables:ctx.vars }, Object.assign({}, ctx, { vars:Object.assign({}, ctx.vars, { INDEX:i }) })); sub.position.set((offset[0] || 0)*i, (offset[1] || 0)*i, (offset[2] || 0)*i); group.add(sub); } return; } if (comp.blueprint && ctx.blueprints && ctx.blueprints[comp.blueprint]) { const sub = this.manifest(ctx.blueprints[comp.blueprint], Object.assign({}, ctx, { vars:Object.assign({}, ctx.vars, comp.vars || {}) })); const p = list(comp.position || [0,0,0]).map(resolve); sub.position.set(p[0], p[1], p[2]); group.add(sub); return; } for (const mesh of this._createMesh(comp, resolve)) group.add(mesh); }
  static _geometry(type, params, comp, resolve) { if (type === "box") return new THREE.BoxGeometry(...params); if (type === "cylinder") return new THREE.CylinderGeometry(...params); if (type === "sphere") return new THREE.SphereGeometry(...params); if (type === "plane") return new THREE.PlaneGeometry(...params); if (type === "icosphere") return new THREE.IcosahedronGeometry(...params); if (["star","arc","polygon","ring","starShape","arcTube"].includes(type)) return shapeGeometry(type, comp.options || {}); if (type === "awtsmoosMeshData") return geometryFromAwtsmoosMeshData(THREE, comp.meshData || comp.data || {}); if (type === "proceduralGrass") return ProceduralGeometryFactory.createGrass(comp.options || {}); if (type === "proceduralTube") { const opts = Object.assign({}, comp.options || {}); if (opts.path) opts.path = opts.path.map(p => new THREE.Vector3(...p.map(resolve))); if (opts.bezier && opts.bezier.points) opts.bezier.points = opts.bezier.points.map(p => new THREE.Vector3(...p.map(resolve))); return ProceduralGeometryFactory.createTube(opts); } return null; }
  static _createMesh(comp, resolve) { const type = comp.type, params = list(comp.params || []).map(resolve), position = list(comp.position || [0,0,0]).map(resolve), rotation = list(comp.rotation || [0,0,0]).map(resolve), scale = list(comp.scale || [1,1,1]).map(resolve), material = comp.material || "JERUSALEM_STONE", isSolid = comp.isSolid !== false; let geo = this._geometry(type, params, comp, resolve); if (!geo) return []; if (comp.modifiers) geo = GeometryModifiers.applyModifiers(geo, comp.modifiers, resolve); const mesh = new THREE.Mesh(geo, getMaterial(material)); mesh.name = comp.name || `json_${type}`; mesh.position.set(position[0] || 0, position[1] || 0, position[2] || 0); mesh.rotation.set(rotation[0] || 0, rotation[1] || 0, rotation[2] || 0); mesh.scale.set(scale[0] || 1, scale[1] || 1, scale[2] || 1); mesh.castShadow = false; mesh.receiveShadow = false; mesh.userData.isSolid = isSolid; mesh.userData.proceduralJsonComponent = true; return [mesh]; }
}
