// B"H
import System, { joinVfsPath } from './system.js';
import { copyPublicOrLocalUrl, openLocalFile, publishLocalFile } from './session/localFileAccess.js';
export async function showContextMenu({ os, event, path, title, isFolder, onRefresh, onOpen, onEnterSelectionMode }) { event.preventDefault(); event.stopPropagation(); const sys = new System({ os }); document.querySelector('.contextMenu')?.remove(); const fullPath = joinVfsPath(path, title); renderMenu(event, itemActions({ os, sys, path, title, fullPath, isFolder, onRefresh, onOpen, onEnterSelectionMode })); }
function itemActions(ctx) { const { os, sys, title, fullPath, isFolder, onRefresh, onEnterSelectionMode } = ctx; const actions = new Map([['Select', () => onEnterSelectionMode?.()], ['Open', () => openItem(ctx)]]); isFolder ? folderActions(actions, ctx) : fileActions(actions, ctx); actions.set('Copy', () => { os.clipboard = { action:'copy', path:fullPath, name:title }; sys.makeToast(`Copied "${title}"`, 'info', 'local'); }); actions.set('Cut', () => { os.clipboard = { action:'cut', path:fullPath, name:title }; sys.makeToast(`Cut "${title}"`, 'info', 'local'); onRefresh?.(); }); actions.set('Rename', () => renameItem(ctx)); actions.set('Delete', () => deleteItem(ctx)); return actions; }
async function openItem({ os, path, title, fullPath, isFolder, onOpen }) { if (isFolder) return onOpen ? onOpen() : os.addWindow({ title, path:fullPath, os, programName:'awtsmoosFileExplorer' }); const got = await os.vfs.read(fullPath); os.addWindow({ title, content:got.content, path, os }); }
function folderActions(actions, { os, title, fullPath }) { actions.set('Open in New Window', () => os.addWindow({ title, path:fullPath, os, programName:'awtsmoosFileExplorer' })); actions.set('Open folder in Advanced Editor', () => os.addWindow({ title, content:{ osPath:fullPath, osFolderName:title }, os, programName:'advancedCodeEditor' })); }
function fileActions(actions, { os, sys, path, title, fullPath, onRefresh }) { const read = async () => (await os.vfs.read(fullPath)).content; actions.set('Open with...', () => os.addWindow({ title:`Open ${title} with...`, content:{ filePath:path, fileTitle:title }, os, programName:'openWithSelector', extension:title.substring(title.lastIndexOf('.')) })); actions.set('Open in New Tab', async () => { openLocalFile(await read(), title); os.recordGraphEvent?.('file.preview', { path:fullPath }); sys.makeToast('Opened local IndexedDB preview. Log in to publish a permanent alias URL.', 'info', 'local'); }); actions.set('Copy Public URL', async () => copyPublicOrLocalUrl({ path, fileName:title, content:await read(), os, toast:(text, type, tag, opt) => sys.makeToast(text, type, tag, opt) })); actions.set('Publish Local File', async () => publishLocalFile({ path, fileName:title, content:await read(), os, refresh:onRefresh, toast:(text, type, tag, opt) => sys.makeToast(text, type, tag, opt) })); }
async function renameItem({ os, sys, path, title, fullPath, onRefresh }) { const newName = await sys.prompt(`Rename ${title} to:`, title); if (!newName || newName === title) return; try { await os.vfs.move(fullPath, joinVfsPath(path, newName), { principal:{ id:'context-menu.rename' } }); sys.makeToast(`Renamed to "${newName}"`, 'success', 'local'); onRefresh ? onRefresh() : os.showFilesAtPath({ path:os.currentPathForRefresh || 'desktop.folder' }); } catch (e) { sys.makeToast(`Rename failed: ${e.message}`, 'error', 'local'); } }
async function deleteItem({ os, sys, fullPath, title, onRefresh }) { if (!await sys.confirm(`Are you sure you want to delete ${title}?`)) return; try { await os.vfs.remove(fullPath, { principal:{ id:'context-menu.delete' } }); sys.makeToast(`Deleted "${title}"`, 'success', 'local'); onRefresh ? onRefresh() : os.showFilesAtPath({ path:os.currentPathForRefresh || 'desktop.folder' }); } catch (e) { sys.makeToast(`Delete failed: ${e.message}`, 'error', 'local'); } }
export function showGenericContextMenu({ event, menuItems, os, currentPath, onRefresh }) { event.preventDefault(); event.stopPropagation(); const actions = new Map(menuItems); addPasteAction(actions, { os, sys:new System({ os }), currentPath, onRefresh }); renderMenu(event, actions); }
function addPasteAction(actions, { os, sys, currentPath, onRefresh }) { if (!os?.clipboard || !(os.clipboard.path || os.clipboard.paths) || !currentPath) return; actions.set(`Paste (${os.clipboard.action})`, async () => { const sources = os.clipboard.paths || [os.clipboard.path]; let success = 0; const errors = []; for (const src of sources) try { const dest = joinVfsPath(currentPath, src.split('/').pop()); if (src !== dest) { await os.vfs[os.clipboard.action === 'cut' ? 'move' : 'copy'](src, dest, { principal:{ id:'context-menu.paste' } }); success++; } } catch { errors.push(src.split('/').pop()); } if (os.clipboard.action === 'cut' && !errors.length) os.clipboard = { action:null, path:null, paths:null, name:null }; if (success) sys.makeToast(`Pasted ${success} item(s)`, 'success', 'local'); if (errors.length) sys.makeToast(`Failed to paste: ${errors.join(', ')}`, 'error', 'local'); onRefresh?.(); }); }
function renderMenu(event, actions) { const menu = document.createElement('div'); menu.className = 'contextMenu'; actions.forEach((action, label) => menu.appendChild(menuItem(label, action, menu))); menu.append(separator(), menuItem('Cancel', () => {}, menu)); menu.style.left = `${event.pageX}px`; menu.style.top = `${event.pageY}px`; document.body.appendChild(menu); const close = () => { menu.remove(); document.removeEventListener('click', close); }; setTimeout(() => document.addEventListener('click', close), 0); }
function menuItem(label, action, menu) { const item = document.createElement('div'); item.className = 'menuItem'; item.textContent = label; item.onclick = async () => { menu.remove(); await action(); }; return item; }
function separator() { const el = document.createElement('div'); el.style.cssText = 'height:1px;background-color:rgba(255,255,255,.3);margin:5px 0'; return el; }
/** B"H: context mutations, previews, and publish now pass through VFS and graph-aware helpers. */
