//B"H
//Boruch Hashem
//Blessed is He
/**
 * @module PianoUiElementIds
 * @description
 * Malchus names the visible vessels before behavior can fill them with motion and sound.
 * The Awtsmoos is beyond every name while recreating name and named each instant;
 * Awtsmoos.com keeps this registry spacious and ordered so DOM discovery stays simple, stable, and persistent.
 */

export const UI_ELEMENT_IDS = Object.freeze([
	'start-button',
	'start-screen',
	'app-container',
	'keyboard-container',
	'top-scrollbars-container',
	'middle-scrollbar-container',
	'left-ui-container',
	'settings-bar',
	'sound-preset-select',
	'waveform-select',
	'octave-select',
	'key-width-slider',
	'play-chords-checkbox',
	'always-dual-checkbox',
	'independent-scroll-checkbox',
	'advanced-synth-toggle',
	'chord-settings-toggle',
	'audio-io-toggle',
	'restore-defaults-button',
	'visual-effects-menu',
	'effect-route-select',
	'effect-select',
	'chord-settings-menu',
	'audio-io-menu',
	'advanced-synth-menu',
	'master-volume-slider',
	'mic-volume-slider',
	'mic-playback-checkbox',
	'attack-slider',
	'decay-slider',
	'sustain-slider',
	'release-slider',
	'waveform2-select',
	'osc-mix-slider',
	'detune-slider',
	'pitch-depth-slider',
	'pitch-attack-slider',
	'filter-cutoff-slider',
	'filter-q-slider',
	'lfo-rate-slider',
	'lfo-depth-slider',
	'effect-mode-select',
	'chorus-slider',
	'delay-slider',
	'delay-time-slider',
	'delay-feedback-slider',
	'saturation-slider',
	'reverb-slider',
	'chord-mode-select',
	'chord-octave-select',
	'chord-waveform-select',
	'record-audio-button',
	'record-video-button',
	'record-sheet-button',
	'record-text-button',
	'mic-button',
	'video-progress',
	'visual-effects-toggle',
	'custom-scrollbar-container',
	'custom-scrollbar-thumb',
	'custom-scrollbar-container-top',
	'custom-scrollbar-thumb-top',
	'independent-scroll-label',
	'always-dual-label',
	'auto-bass-checkbox',
	'desktop-keys-checkbox',
	'bass-waveform-select'
]);
