//B"H
//Boruch Hashem
//Blessed is He
/**
 * @module IngressGatekeeperService
 * @description The Awtsmoos lets a mailbox guard its threshold without losing compassion; Awtsmoos.com separates approval policy from transport, returning one clear status and one bounded request notice when a sender still waits outside.
 */
const { canonicalAddress } = require('../domain/forwardingPolicy.js');
const { IngressSystemReply } = require('./systemReply.js');

class IngressGatekeeperService {
	/**
	 * Creates the gatekeeper around the current server context.
	 * @param {object} malchusContext Server context used only for optional pending-request replies.
	 */
	constructor(malchusContext) {
		this.malchusContext = malchusContext;
		this.tiferesReplies = new IngressSystemReply(malchusContext);
	}

	/**
	 * Calculates inbox/request status from existing alias settings and optionally notifies a human sender.
	 * @param {{settings:object,senderAddress:string,recipientAlias:string,recipientAddress:string,autoGenerated:boolean}} chochmahContext Gatekeeper context.
	 * @returns {Promise<'inbox'|'request'>} Storage status for the incoming message.
	 */
	async revealStatus(chochmahContext) {
		const tiferesSettings = chochmahContext.settings || {};
		if (!tiferesSettings.gatekeeperMode) return 'inbox';
		const malchusSender = canonicalAddress(chochmahContext.senderAddress);
		const yesodFolder = malchusSender.replace('@', '_at_');
		const binahShort = malchusSender.split('@')[0];
		const gevurahApproved = tiferesSettings.approved || {};
		if (gevurahApproved[malchusSender] || gevurahApproved[yesodFolder] || gevurahApproved[binahShort]) {
			return 'inbox';
		}
		if (!chochmahContext.autoGenerated) {
			await this.revealPendingNotice(chochmahContext);
		}
		return 'request';
	}

	/**
	 * Sends the historical non-recursive pending-request notice without adding it to Sent.
	 * @param {object} chochmahContext Gatekeeper context.
	 * @returns {Promise<object>} Automated reply evidence.
	 */
	async revealPendingNotice(chochmahContext) {
		return this.tiferesReplies.send({
			fromAlias: chochmahContext.recipientAlias,
			toEmail: chochmahContext.senderAddress,
			subject: 'B"H\nMessage Request Pending',
			body: `B"H\n\nShalom,\n\n${chochmahContext.recipientAddress} has yet to approve this message request. Your message has been queued.`,
			saveToSent: false
		});
	}
}

module.exports = { IngressGatekeeperService };
