//B"H
//Boruch Hashem
//Blessed is He
/**
 * @module IngressMessageSafety
 * @description The Awtsmoos distinguishes a living human reply from mechanical echoes; Awtsmoos.com keeps loop detection and automation suppression in one pure gate so every downstream service receives the same verdict.
 */
const { canonicalAddress, normalizeTrail } = require('../domain/forwardingPolicy.js');

class IngressMessageSafety {
	/**
	 * Detects auto-generated mail from standard transport headers and historical sender/subject conventions.
	 * @param {{headers?:object,from?:string,subject?:string}} chochmahMessage Parsed message identity.
	 * @returns {boolean} True when rules and automatic replies should stay silent.
	 */
	static isAutoGenerated(chochmahMessage) {
		const tiferesHeaders = chochmahMessage.headers || {};
		const malchusAuto = String(tiferesHeaders['auto-submitted'] || '').toLowerCase();
		const yesodPrecedence = String(tiferesHeaders.precedence || '').toLowerCase();
		const binahSuppress = String(tiferesHeaders['x-auto-response-suppress'] || '').toLowerCase();
		const gevurahFrom = String(chochmahMessage.from || '');
		const hodSubject = String(chochmahMessage.subject || '');
		if (malchusAuto && malchusAuto !== 'no') return true;
		if (/(bulk|junk|list)/.test(yesodPrecedence)) return true;
		if (binahSuppress && binahSuppress !== 'none') return true;
		return /no-?reply|daemon|notification|auto|mailer-daemon/i.test(gevurahFrom)
			|| /automatic reply|out of office/i.test(hodSubject);
	}

	/**
	 * Reads the cross-system forwarding trail emitted by Awtsmoos SMTP forwarding.
	 * @param {object} tiferesHeaders Parsed top-level headers.
	 * @returns {string[]} Canonical bounded forwarding trail.
	 */
	static forwardingTrail(tiferesHeaders = {}) {
		const malchusTrail = String(tiferesHeaders['x-awtsmoos-forwarding-trail'] || '')
			.split(',')
			.map(yesodAddress => yesodAddress.trim())
			.filter(Boolean);
		return normalizeTrail(malchusTrail);
	}

	/**
	 * Detects direct sender-recipient loops before automation emits another message.
	 * @param {string} chesedSender Sender mailbox.
	 * @param {string} gevurahRecipient Recipient mailbox.
	 * @returns {boolean} True when both addresses identify the same mailbox.
	 */
	static isSelfLoop(chesedSender, gevurahRecipient) {
		return canonicalAddress(chesedSender) === canonicalAddress(gevurahRecipient);
	}
}

module.exports = { IngressMessageSafety };
