// B"H
/** @file VillageGroundNavigator.js @description Smooth terrain movement; animals face forward, not backwards; no optional parser paths. */
import * as THREE from "/games/scripts/build/three.module.js";
import TerrainMath from "../../../../dvarim/terrain/core/TerrainMath.js";
const down = new THREE.Vector3(0,-1,0), ray = new THREE.Ray(), proposed = new THREE.Vector3(), direction = new THREE.Vector3(), side = new THREE.Vector3();
const CACHE_MS = 950, CELL = 1.5;
function n(v, f = 0) { return Number.isFinite(Number(v)) ? Number(v) : f; }
function perfNow() { const p = typeof globalThis !== "undefined" ? globalThis.performance : null; return p && typeof p.now === "function" ? p.now() : Date.now(); }
function lawOf(olam) { return olam && olam.awtsmoosTerrainLaw ? olam.awtsmoosTerrainLaw : null; }
function worldOctree(olam) { return olam && olam.worldOctree ? olam.worldOctree : null; }
function rayIntersect(olam) { const oct = worldOctree(olam); return oct && typeof oct.rayIntersect === "function" ? oct.rayIntersect(ray) : null; }
function meshOf(mob) { return mob && mob.mesh ? mob.mesh : null; }
export default class VillageGroundNavigator {
  constructor(olam) { this.olam = olam; this.groundCache = new Map(); this.obstacleCache = new Map(); }
  terrainLawY(x, z, fallback = 0) { const law = lawOf(this.olam); if (!law || !law.data) return fallback; const pos = law.position || {}; return n(pos.y) + TerrainMath.calculateHeightAt(x - n(pos.x), z - n(pos.z), law.data); }
  groundY(x, z, fallback = 0, fast = false) { const lawY = this.terrainLawY(x,z,fallback); if (fast) return Number.isFinite(lawY) ? lawY : fallback; const key = `${Math.round(x/CELL)}:${Math.round(z/CELL)}`, old = this.groundCache.get(key), stamp = perfNow(); if (old && stamp - old.at < CACHE_MS) return old.y; ray.origin.set(x, Math.max(lawY+18, 40), z); ray.direction.copy(down); const hit = rayIntersect(this.olam); const octY = hit && hit.position && Number.isFinite(hit.position.y) ? hit.position.y : hit && Number.isFinite(hit.distance) ? ray.origin.y - hit.distance : NaN; const normal = hit && hit.normal ? hit.normal : {}; const normalY = Number(normal.y !== undefined ? normal.y : 1); const y = Number.isFinite(octY) && normalY > .45 && Math.abs(octY-lawY) < 2.5 ? Math.max(lawY, octY) : lawY; const safe = Number.isFinite(y) ? y : fallback; this.groundCache.set(key, { y:safe, at:stamp }); if (this.groundCache.size > 900) this.groundCache.delete(this.groundCache.keys().next().value); return safe; }
  blocked(from, dir, distance, mob) { if (mob && mob.lowCostChase && mob.__navFrame % 6 !== 0) return false; const octant = Math.round(Math.atan2(dir.x,dir.z)/(Math.PI/4)), key = `${Math.round(from.x/CELL)}:${Math.round(from.z/CELL)}:${octant}`, old = this.obstacleCache.get(key), stamp = perfNow(); if (old && stamp - old.at < 360) return old.blocked; ray.origin.set(from.x, from.y+.75, from.z); ray.direction.copy(dir); const hit = rayIntersect(this.olam); const normal = hit && hit.normal ? hit.normal : {}; const blocked = Boolean(hit && hit.distance <= distance + .72 && Number(normal.y !== undefined ? normal.y : 0) < .68); this.obstacleCache.set(key, { blocked, at:stamp }); if (this.obstacleCache.size > 650) this.obstacleCache.delete(this.obstacleCache.keys().next().value); return blocked; }
  move(mob, goal, dt, scale, stopDistance = 0) { const mesh = meshOf(mob); if (!mesh || !goal) return; mob.__navFrame = (mob.__navFrame || 0) + 1; direction.copy(goal).sub(mesh.position); direction.y = 0; const distance = direction.length(); if (distance < .01) return this.snap(mob); direction.normalize(); const tooClose = stopDistance > 0 && distance < stopDistance * .82, closeEnough = stopDistance > 0 && Math.abs(distance - stopDistance) < .18; if (tooClose) direction.multiplyScalar(-1); else if (closeEnough && !mob.lowCostChase) direction.set(direction.z,0,-direction.x).multiplyScalar(mob.orbitSign || 1); const maxStep = mob.lowCostChase ? .16 : tooClose ? .24 : .32, step = Math.min(Math.max(0, mob.speed * scale * dt), maxStep); if (!mob.lowCostChase && this.blocked(mesh.position, direction, step, mob)) { side.set(direction.z,0,-direction.x); if (this.blocked(mesh.position, side, step, mob)) side.multiplyScalar(-1); direction.lerp(side,.82).normalize(); } if (!mob.__smoothDir) mob.__smoothDir = new THREE.Vector3(); mob.__smoothDir.lerp(direction, mob.lowCostChase ? .34 : .62).normalize(); proposed.copy(mesh.position).addScaledVector(mob.__smoothDir, step); proposed.y = this.groundY(proposed.x, proposed.z, mesh.position.y - mob.groundLift, Boolean(mob.lowCostChase)) + mob.groundLift; mesh.position.lerp(proposed, mob.lowCostChase ? .82 : 1); mesh.rotation.y = Math.atan2(mob.__smoothDir.x, mob.__smoothDir.z); mesh.userData.forwardFix = "plusZ"; }
  snap(mob) { const mesh = meshOf(mob); if (mesh) mesh.position.y = this.groundY(mesh.position.x, mesh.position.z, mesh.position.y - mob.groundLift, true) + mob.groundLift; }
}
export function getVillageGroundNavigator(olam) { if (!olam.__villageGroundNavigator) olam.__villageGroundNavigator = new VillageGroundNavigator(olam); return olam.__villageGroundNavigator; }
