// B"H
/**
 * @file VillageAnimalMob.js
 * @purpose Runs grounded village animal pursuit, forage, windup, strike, and loot drops.
 * @owner Live mitzvahWorld village combat wildlife runtime.
 * @inputs Olam world, animal definitions, player position, navigator, and combat state.
 * @outputs Grounded animal movement, hit events, carcasses, food drops, and UI proof.
 * @runtimeAuthority Animal combat only; Y remains controlled by VillageGroundNavigator.
 * @updateOrder Spawn, navigator snap, partitioned update, state action, animation, debug.
 * @callers Village combat/world spawn controllers.
 * @invariants Strike pulse timing never adds vertical attack drift to mesh position.
 * @failureModes Missing player or food target falls back to patrol/forage safely.
 */
import * as THREE from "/games/scripts/build/three.module.js";
import { getVillageGroundNavigator } from "./VillageGroundNavigator.js?v=plus-z-facing-20260614-bh1";
import { createVillageAnimal, disposeVillageAnimal } from "./VillageAnimalFactory.js?v=awtsmoos-village-animal-factory-20260614-bh2";
import { animateAnimal } from "../region/wildlife/render/AnimalAnimator.js?v=awtsmoos-animal-gait-20260614-bh2";
import { getDynamicActorPartition } from "../runtime/DynamicActorPartition.js?v=awtsmoos-dynamic-partition-20260614-bh2";
import { createCarcass } from "../../../../systems/kosher/CarcassRuntime.js";
import { makeLootableCorpse } from "../../../../systems/loot/LootRuntime.js";
const scratch = new THREE.Vector3(), away = new THREE.Vector3(), FOOD_CACHE = new WeakMap();
const ACTIVE_STATES = new Set(["chase","windup","strike","recover","attack","flee","fleePlayer"]);
const ATK = Object.freeze({ fox:{name:"snap",color:"#ff9b45",windupRange:2.85,hitRange:2.35,cooldown:1.05,windup:.22,strike:.18,recover:.48,lungeSpeed:6.8}, wolf:{name:"lunge",color:"#d7e6ff",windupRange:3.15,hitRange:2.65,cooldown:1.25,windup:.26,strike:.22,recover:.55,lungeSpeed:7.2}, ram:{name:"bash",color:"#fff0a8",windupRange:3.35,hitRange:2.9,cooldown:1.45,windup:.34,strike:.24,recover:.62,lungeSpeed:6.2}, stag:{name:"antler sweep",color:"#c9ff9d",windupRange:3.55,hitRange:3.05,cooldown:1.55,windup:.36,strike:.26,recover:.64,lungeSpeed:6.4} });
function now() { const p = typeof globalThis !== "undefined" && globalThis.performance ? globalThis.performance : null; return (p && typeof p.now === "function" ? p.now() : Date.now()) / 1000; }
function n(v, f = 0) { return Number.isFinite(Number(v)) ? Number(v) : f; }
function v3(p = {}) { return new THREE.Vector3(n(p.x), n(p.y), n(p.z)); }
function playerPos(p) { if (!p) return null; if (p.mesh) return p.mesh.position; if (p.modelMesh) return p.modelMesh.position; if (p.guf) return p.guf.position; return null; }
function d2(a,b) { return a && b ? a.distanceToSquared(b) : Infinity; }
function traverse(root, fn) { if (root && typeof root.traverse === "function") root.traverse(fn); }
function flash(root, color, ms) { const hex = new THREE.Color(color).getHex(); traverse(root, c => { if (c.material && c.material.emissive && typeof c.material.emissive.setHex === "function") c.material.emissive.setHex(hex); }); setTimeout(() => traverse(root, c => { if (c.material && c.material.emissive && typeof c.material.emissive.setHex === "function") c.material.emissive.setHex(0); }), ms); }
function damage(player, amount, olam) { if (player && typeof player.takeDamage === "function") return player.takeDamage(amount); const stats = player && player.currentStats ? player.currentStats : null; if (!stats) return 0; stats.maxHealth = stats.maxHealth || 100; stats.health = Math.max(0, n(stats.health, stats.maxHealth) - amount); if (olam && typeof olam.ayshPeula === "function") olam.ayshPeula("ui event", "gameHUD", { updateStats:{ hp:stats.health, maxHp:stats.maxHealth } }); return amount; }
function foodObjects(olam) { const stamp = now(), cached = FOOD_CACHE.get(olam); if (cached && stamp - cached.at < 1.5) return cached.items; const out = [], scene = olam && olam.scene ? olam.scene : null; if (scene && typeof scene.traverse === "function") scene.traverse(o => { const u = o.userData || {}, name = String(o.name || "").toLowerCase(); if (u.foodSource || u.itemId === "Fruit" || u.itemId === "food" || name.includes("fruit") || name.includes("berry") || name.includes("rabbit")) out.push(o); }); FOOD_CACHE.set(olam, { at:stamp, items:out }); return out; }
function nearestFood(olam, from, predator) { let best = null, score = Infinity; for (const o of foodObjects(olam)) { if (!o.position || o.visible === false) continue; const name = String(o.name || "").toLowerCase(), data = o.userData || {}; if (predator && !(name.includes("rabbit") || data.preyFood)) continue; const dist = from.distanceToSquared(o.position); if (dist < score) { best = o; score = dist; } } return best; }
function attackData(species) { return ATK[species] || ATK.fox; }
function callOverlay(olam, text, color) { if (olam && typeof olam.ayshPeula === "function") olam.ayshPeula("ui event", "effectsOverlay", { text, color }); }
function sceneAdd(olam, mesh) { if (olam && olam.scene && typeof olam.scene.add === "function") olam.scene.add(mesh); }
function scopeOf(olam) { return olam?.aysh?.window || globalThis; }
function animalProof(olam) { const scope = scopeOf(olam); return scope.__MITZVAH_ANIMAL_KILL_CONFIRMATION__ ||= { seal:"animal-kill-proof-20260623-bh1", totalKills:0, missionKills:0, foodDropped:0, kills:[] }; }
function publishAnimalEvent(olam, kind, payload) { const scope = scopeOf(olam), proof = animalProof(olam); proof.lastEvent = { kind, ...payload, at:Date.now() }; try { scope.dispatchEvent?.(new CustomEvent("mitzvah-world:animal-" + kind, { detail:proof.lastEvent })); } catch {} }
function registerLiveAnimal(olam, mob) { const proof=animalProof(olam); proof.liveIds ||= []; proof.liveIds.push(mob.id); const scope=scopeOf(olam); scope.__MITZVAH_LIVE_ANIMAL_MOBS__ ||= {}; scope.__MITZVAH_LIVE_ANIMAL_MOBS__[mob.id]=mob; scope.__MITZVAH_TEST_DAMAGE_ANIMAL__ ||= (id, amount=999) => { const m=scope.__MITZVAH_LIVE_ANIMAL_MOBS__?.[id]; if(!m) return { ok:false, error:"animal_not_found", id }; m.takeDamage(amount); return { ok:true, id, dead:!!m.isDead, hp:m.hp }; }; }
function removeSoon(mesh, ms) { setTimeout(() => { if (mesh.material && typeof mesh.material.dispose === "function") mesh.material.dispose(); if (mesh.geometry && typeof mesh.geometry.dispose === "function") mesh.geometry.dispose(); if (typeof mesh.removeFromParent === "function") mesh.removeFromParent(); }, ms); }
function defaultHunger(species) { return species === "fox" ? 0.72 : 0.38; }
export default class VillageAnimalMob {
  constructor(olam, def, state) { this.olam=olam; this.def=def; this.state=state; this.id=def.id; this.name=def.name; this.type="mazik"; this.elementalType="wildAnimal"; this.species=def.species || "fox"; this.hp=n(def.hp,60); this.maxHp=this.hp; this.damage=n(def.damage,8); this.xpValue=n(def.xp,25); this.perutas=n(def.perutas,3); this.speed=Math.min(n(def.speed,3.7),4.2); this.groundLift=n(def.groundLift,.28); this.aggroRange=n(def.aggro,18); this.attackData=Object.assign({}, attackData(this.species)); this.windupRange=n(def.windupRange,this.attackData.windupRange); this.hitRange=n(def.hitRange,n(def.attackRange,this.attackData.hitRange)); this.chaseStopDistance=n(def.chaseStopDistance,Math.max(1.05,this.hitRange*.68)); this.attackCooldown=n(def.attackCooldown,this.attackData.cooldown); this.attackPulseUntil=0; this.spawn=v3(def.position); this.target=this.spawn.clone(); this.clock=n(def.clockSeed, Math.random()*100); this.stateName="patrol"; this.stateUntil=0; this.lastAttackAt=-99; this.damageDone=false; this.isReady=true; this.heesHawveh=true; this.isDead=false; this.hunger=n(def.hunger,defaultHunger(this.species)); this.foodTarget=null; this.__debugAt=0; this.mesh=this.buildMesh(); this.mesh.position.copy(this.spawn); this.navigator=getVillageGroundNavigator(olam); this.navigator.snap(this); const proof=animalProof(olam); proof.spawned=(proof.spawned||0)+1; proof.lastSpawn={id:this.id,name:this.name,species:this.species,at:Date.now()}; registerLiveAnimal(olam,this); publishAnimalEvent(olam,"spawn",proof.lastSpawn); }
  buildMesh() { const group = createVillageAnimal(this.def, this); group.name = this.name; Object.assign(group.userData, { isEnemy:true, isVillageWildlife:true, foodAware:true, correctForward:"plusZ" }); return group; }
  heesHawvoos(dt = 1 / 60) { const partition = getDynamicActorPartition(this.olam); if (!partition.shouldUpdate(this, this.olam)) return; return this.__partitionedUpdate(dt); }
  __partitionedUpdate(dt = 1 / 60) { if (this.isDead || !this.mesh) return; const delta = Math.min(.04, n(dt, 1/60)); this.clock += delta; this.hunger = Math.min(1, this.hunger + delta * (this.species === "fox" ? .025 : .012)); const player = this.olam ? this.olam.player || this.olam.chossid : null, pos = playerPos(player); if (!pos) return this.foodOrPatrol(delta); const dist2 = d2(this.mesh.position, pos); if (dist2 > this.aggroRange*this.aggroRange && !["patrol","eat","forage"].includes(this.stateName)) this.setState("patrol"); const fn = { patrol:()=>this.patrol(delta,pos,dist2), forage:()=>this.forage(delta), eat:()=>this.eat(delta), chase:()=>this.chase(delta,player,pos,dist2), windup:()=>this.windup(pos), strike:()=>this.strike(delta,player,pos), recover:()=>this.recover(delta,pos) }[this.stateName] || (()=>this.patrol(delta,pos,dist2)); fn(); this.animateRig(delta,pos); this.writeDebug(dist2); }
  setState(name, seconds = 0) { this.stateName = name; this.stateUntil = now() + seconds; this.damageDone = false; if (this.mesh) { this.mesh.userData.animalState = name; this.mesh.userData.partitionCritical = ACTIVE_STATES.has(name); } }
  ready() { return now() - this.lastAttackAt >= this.attackCooldown; }
  face(point) { if (!point || !this.mesh) return; scratch.copy(point).sub(this.mesh.position); scratch.y = 0; if (scratch.lengthSq() > .0001) this.mesh.rotation.y = Math.atan2(scratch.x, scratch.z); }
  foodOrPatrol(dt) { return this.hunger > .64 ? this.beginForage() : this.patrol(dt); }
  beginForage() { this.foodTarget = nearestFood(this.olam, this.mesh.position, this.species === "fox"); this.setState(this.foodTarget ? "forage" : "patrol"); }
  forage(dt) { if (!this.foodTarget || this.foodTarget.visible === false) return this.setState("patrol"); this.navigator.move(this, this.foodTarget.position, dt, .72, .7); this.face(this.foodTarget.position); if (d2(this.mesh.position, this.foodTarget.position) < 1.2) this.setState("eat", .85); }
  eat(dt) { this.hunger = Math.max(0, this.hunger - dt*.9); const base = this.mesh.userData.baseVisualScale || this.mesh.scale, pulse = .98 + Math.sin(this.clock*8)*.018; this.mesh.scale.set(base.x*pulse, base.y*pulse, base.z*pulse); if (now() >= this.stateUntil || this.hunger < .25) { this.mesh.scale.copy(base); this.setState("patrol"); } }
  patrol(dt, pos = null, dist2 = Infinity) { if (pos && this.hasBeenProvoked && dist2 < this.aggroRange*this.aggroRange) return this.setState("chase"); if (this.hunger > .72) return this.beginForage(); this.navigator.move(this, this.patrolTarget(), dt, .38, 0); }
  chase(dt, player, pos, dist2) { if (this.hunger > .95 && dist2 > 36) return this.beginForage(); if (dist2 <= this.windupRange*this.windupRange && this.ready()) return this.beginWindup(pos); this.navigator.move(this, pos, dt, 1.05, this.chaseStopDistance); if (d2(this.mesh.position, playerPos(player)) <= this.windupRange*this.windupRange && this.ready()) this.beginWindup(playerPos(player)); }
  beginWindup(pos) { this.windupTarget = pos && typeof pos.clone === "function" ? pos.clone() : null; flash(this.mesh, this.attackData.color, 120); this.spawnWarningRing(); this.setState("windup", this.attackData.windup); }
  windup(pos) { this.face(pos || this.windupTarget); if (now() >= this.stateUntil) { this.attackPulseUntil = now() + this.attackData.strike; this.setState("strike", this.attackData.strike); } }
  strike(dt, player, pos) { this.attackPulseUntil = Math.max(this.attackPulseUntil || 0, now()); if (pos) { this.face(pos); this.navigator.move(this, pos, dt, this.attackData.lungeSpeed / Math.max(.1, this.speed), .72); } if (!this.damageDone && d2(this.mesh.position, playerPos(player)) <= (this.hitRange+.35)*(this.hitRange+.35)) this.dealHit(player); if (now() >= this.stateUntil) { this.lastAttackAt = now(); this.setState("recover", this.attackData.recover); } }
  recover(dt, pos) { if (pos) { away.copy(this.mesh.position).sub(pos); away.y = 0; if (away.lengthSq() < .01) away.set(1,0,0); away.normalize(); scratch.copy(this.mesh.position).addScaledVector(away, 2.2); this.navigator.move(this, scratch, dt, .72, 0); } if (now() >= this.stateUntil) this.setState("chase"); }
  patrolTarget() { if (this.mesh.position.distanceToSquared(this.target) < 1.21) { const r = n(this.def.patrol, 8); this.target.set(this.spawn.x + (Math.random()-.5)*r*2, this.spawn.y, this.spawn.z + (Math.random()-.5)*r*2); } return this.target; }
  dealHit(player) { this.damageDone = true; const dealt = damage(player, this.damage, this.olam); this.hunger = Math.max(0, this.hunger-.08); this.spawnHitArc(playerPos(player)); flash(this.mesh, "#fff6b0", 90); callOverlay(this.olam, `${this.name} ${this.attackData.name}: -${Math.round(dealt || this.damage)} HP`, this.attackData.color); }
  spawnWarningRing() { if (this.__warnAt && now() - this.__warnAt < .18) return; this.__warnAt = now(); const ring = new THREE.Mesh(new THREE.TorusGeometry(this.hitRange*.42,.025,6,24), new THREE.MeshBasicMaterial({ color:new THREE.Color(this.attackData.color), transparent:true, opacity:.7 })); ring.name = `${this.name}_windup_warning_ring`; ring.rotation.x = Math.PI/2; ring.position.copy(this.mesh.position); ring.position.y += .08; sceneAdd(this.olam, ring); removeSoon(ring, 170); }
  spawnHitArc(pos) { if (!pos) return; const arc = new THREE.Mesh(new THREE.TorusGeometry(.7,.045,6,20,Math.PI*1.25), new THREE.MeshBasicMaterial({ color:new THREE.Color(this.attackData.color), transparent:true, opacity:.95 })); arc.name = `${this.name}_hit_arc`; arc.position.copy(pos); arc.position.y += 1.05; arc.rotation.set(Math.PI/2,0,this.clock); sceneAdd(this.olam, arc); removeSoon(arc, 130); }
  animateRig(dt, target) { animateAnimal(this.mesh, dt, this.stateName); if (target && ["windup","strike"].includes(this.stateName)) this.face(target); }
  writeDebug(dist2) { const t = now(); if (t - this.__debugAt < .25) return; this.__debugAt = t; this.mesh.userData.__debugAnimalState = { state:this.stateName, tier:this.__partitionTier, hunger:Number(this.hunger.toFixed(2)), distance:Number(Math.sqrt(dist2).toFixed(2)), fur:this.mesh.userData.furType || "fur" }; }
  takeDamage(amount) { if (this.isDead) return; this.hasBeenProvoked = true; this.setState("chase"); this.hp = Math.max(0, this.hp - n(amount,0)); flash(this.mesh, "#fff1a8", 90); if (this.hp <= 0) this.die(); publishAnimalEvent(this.olam,"damage",{id:this.id,name:this.name,species:this.species,hp:this.hp,maxHp:this.maxHp}); }
  die() { this.isDead = true; if (this.mesh?.userData?.health) { this.mesh.userData.health.current = 0; this.mesh.userData.health.dead = true; } if (this.state && typeof this.state.recordKill === "function") this.state.recordKill(this); this.dropFood(); publishAnimalEvent(this.olam,"kill",{id:this.id,name:this.name,species:this.species,hp:0}); if (this.olam && this.olam.combatManager && typeof this.olam.combatManager.unregisterEnemy === "function") this.olam.combatManager.unregisterEnemy(this); const carcass = createCarcass(this.olam, this.mesh, { species:this.species }); const corpse = makeLootableCorpse(this.olam, this, { carcassId:carcass.id, position:this.mesh.position.clone() }); this.mesh.userData.lootableCorpseId = corpse?.corpseId || this.lootableCorpseId; this.mesh.userData.interactable = true; this.mesh.userData.interactionLabel = "Loot carcass"; this.mesh.userData.onInteract = () => globalThis.__MITZVAH_OPEN_LOOT__?.(this.mesh.userData.lootableCorpseId); this.mesh.rotation.z = Math.PI / 2; this.mesh.scale.multiplyScalar(.92); traverse(this.mesh, c => { if (c.material) c.material.transparent = false; }); callOverlay(this.olam, `${this.name} can be looted`, "#ffd966"); }
  dropFood() { if (this.olam && typeof this.olam.addObject === "function") this.olam.addObject("Collectable", { itemId:"Food", itemName:this.species === "fox" ? "Wild Meat" : "Foraged Food", itemType:"food", amount:1, position:this.mesh.position.clone().add(new THREE.Vector3(0,1,0)), color:"#d99855", meshType:"sphere", sellValue:3 }); if (this.state && typeof this.state.recordFoodDrop === "function") this.state.recordFoodDrop(this); const proof=animalProof(this.olam); proof.foodDropped=(proof.foodDropped||0)+1; publishAnimalEvent(this.olam,"food-drop",{id:this.id,name:this.name,species:this.species,foodDropped:proof.foodDropped}); }
  dispose() { disposeVillageAnimal(this.mesh); this.mesh = null; }
}
