// B"H
/** B"H — Chapter 918: Forty-nine sparks became named gates. */
const rows = [
["oneTimeToken","Trust","One-time approval token", "planned"],["quickFiveMinuteGrant","Trust","Approve for 5 minutes", "policy"],["untilTargetCloses","Trust","Grant until window/tab closes", "planned"],["controlEscalationConfirm","Trust","Confirm before control escalation", "policy"],["privilegedActionConfirm","Trust","Confirm privileged actions", "policy"],["invisibleCursorWatch","Trust","View-only without cursor", "planned"],["keyboardOnly","Trust","Allow keyboard only", "policy"],["mouseOnly","Trust","Allow mouse only", "policy"],["deviceTrustHistory","Trust","Per-device trust history", "policy"],["riskScore","Trust","Risk score before consent", "policy"],
["appWhitelist","Permissions","Whitelist specific apps", "planned"],["tabOnlyShare","Permissions","Share one browser tab", "policy"],["monitorOnlyShare","Permissions","Share one monitor", "planned"],["windowBlacklist","Permissions","Blacklist windows", "planned"],["hideNotifications","Permissions","Hide notifications", "planned"],["blurPasswords","Permissions","Blur password fields", "planned"],["blurConfiguredApps","Permissions","Blur configured apps", "planned"],["protectedWindowClicks","Permissions","Block protected-window clicks", "planned"],["clipboardBlocked","Permissions","Block clipboard independently", "policy"],["temporaryClipboard","Permissions","Temporary clipboard grant", "planned"],
["webrtcFingerprint","Security","WebRTC fingerprint verification", "planned"],["rotatingSessionKeys","Security","Rotate session keys", "planned"],["mutualChallenge","Security","Mutual auth challenge", "planned"],["rapidInputDetection","Security","Detect rapid input", "policy"],["automationPatternDetection","Security","Detect automation patterns", "policy"],["geoAnomaly","Security","Geographic anomaly warning", "planned"],["impossibleTravel","Security","Impossible-travel detection", "planned"],["watermark","Security","Requester watermark", "planned"],["tamperDetection","Security","Live tamper detection", "planned"],["integrityChecksum","Security","Session integrity checksum", "planned"],
["countdown","UX","Live countdown timer", "policy"],["activeOverlay","UX","Sharing active overlay", "planned"],["pauseSharing","UX","Pause sharing", "policy"],["resumeSharing","UX","Resume sharing", "policy"],["pipPreview","UX","Picture-in-picture preview", "planned"],["timeline","UX","Session timeline", "policy"],["permissionSummary","UX","Permission summary card", "policy"],["humanAudit","UX","Human-readable audit log", "policy"],["bookmarks","UX","Session bookmarks", "policy"],["copySupportInfo","UX","Copy support session info", "policy"],
["multiViewer","Collaboration","Multiple viewers", "planned"],["controllerQueue","Collaboration","One controller queue", "planned"],["requestControl","Collaboration","Request control button", "policy"],["transferControl","Collaboration","Transfer control", "planned"],["voiceSignaling","Collaboration","Voice signaling", "planned"],["annotationTools","Collaboration","Annotation tools", "planned"],["highlightClick","Collaboration","Highlight-click mode", "planned"],["guidedWalkthrough","Collaboration","Guided walkthrough", "planned"],["aiCopilot","Collaboration","AI copilot explains permissions", "planned"]
];
function featureCatalog() { return rows.map(([id, category, title, status], index) => ({ index:index + 1, id, category, title, status })); }
function implementedFeatures() { return featureCatalog().filter(f => f.status === "policy"); }
function plannedFeatures() { return featureCatalog().filter(f => f.status === "planned"); }
function featureById(id) { return featureCatalog().find(f => f.id === id) || null; }
module.exports = { featureCatalog, implementedFeatures, plannedFeatures, featureById };
