// B"H
const { allowInputType } = require("./policy.js");
const { audit, publicSession } = require("./store.js");
function requireOpen(session) { if (!session) return { ok:false, status:404, error:"remote_desktop_session_not_found" }; if (session.status !== "open") return { ok:false, status:409, error:"remote_desktop_session_not_open", session:publicSession(session) }; return null; }
function addSignal(session, type, payload = {}) { const blocked = requireOpen(session); if (blocked) return blocked; const signal = { at:Date.now(), type, payload:safeSignal(payload) }; session.signals.push(signal); audit(session, "signal", { type }); return { ok:true, action:"remoteDesktopSignal", signal, session:publicSession(session) }; }
function pushFrame(session, payload = {}) { const blocked = requireOpen(session); if (blocked) return blocked; const frame = { at:Date.now(), contentType:payload.contentType || "image/jpeg", bytes:Number(payload.bytes || payload.frame64?.length || 0), note:payload.note || "frame accepted" }; session.frames.push(frame); audit(session, "frame", { bytes:frame.bytes, contentType:frame.contentType }); return { ok:true, action:"remoteDesktopFramePush", frame, session:publicSession(session) }; }
function inputEvent(session, payload = {}) { const blocked = requireOpen(session); if (blocked) return blocked; if (!session.controlGranted) return { ok:false, status:403, error:"remote_desktop_control_not_granted", session:publicSession(session) }; const type = String(payload.type || payload.inputType || "").toLowerCase(); if (!allowInputType(type)) return { ok:false, status:400, error:"remote_desktop_input_type_not_allowed", allowed:false, type }; const event = { at:Date.now(), type, x:numberOrNull(payload.x), y:numberOrNull(payload.y), key:payload.key || null, text:payload.text || null }; session.inputEvents.push(event); audit(session, "input", { type }); return { ok:true, action:"remoteDesktopInputEvent", event, session:publicSession(session) }; }
function safeSignal(payload) { return { sdp:payload.sdp ? "configured" : undefined, candidate:payload.candidate ? "configured" : undefined, label:payload.label || "" }; }
function numberOrNull(value) { const n = Number(value); return Number.isFinite(n) ? n : null; }
module.exports = { addSignal, pushFrame, inputEvent };
