// B"H
const { allowInputType, inputFamily } = require("./policy.js");
const { audit, persist, publicSession } = require("./store.js");
function requireOpen(session) { if (!session) return block(404, "remote_desktop_session_not_found"); if (session.status !== "open") return block(409, "remote_desktop_session_not_open", session); if (session.paused) return block(423, "remote_desktop_session_paused", session); if (session.revoked || session.denied) return block(403, "remote_desktop_session_closed", session); return null; }
function block(status, error, session) { return { ok:false, status, error, session:publicSession(session) }; }
function addSignal(session, type, payload = {}) { const blocked = requireOpen(session); if (blocked) return blocked; const signal = { at:Date.now(), type, payload:safeSignal(payload) }; session.signals.push(signal); audit(session, "signal", { type }); persist(); return { ok:true, action:"remoteDesktopSignal", signal, session:publicSession(session) }; }
function heartbeat(session, payload = {}) { const blocked = requireOpen(session); if (blocked) return blocked; const beat = { at:Date.now(), fingerprint:fingerprint(payload), label:payload.label || "heartbeat" }; session.signals.push({ at:beat.at, type:"heartbeat", payload:beat }); audit(session, "heartbeat", { fingerprint:beat.fingerprint }); persist(); return { ok:true, action:"remoteDesktopHeartbeat", heartbeat:beat, session:publicSession(session) }; }
function pushFrame(session, payload = {}) { const blocked = requireOpen(session); if (blocked) return blocked; const frame = { at:Date.now(), contentType:payload.contentType || "image/jpeg", bytes:Number(payload.bytes || payload.frame64?.length || 0), frame64:payload.frame64 || "", note:payload.note || "frame accepted" }; session.frames.push(frame); session.frames = session.frames.slice(-10); audit(session, "frame", { bytes:frame.bytes, contentType:frame.contentType }); persist(); return { ok:true, action:"remoteDesktopFramePush", frame:publicFrame(frame), session:publicSession(session) }; }
function latestFrame(session) { if (!session) return block(404, "remote_desktop_session_not_found"); const frame = session.frames.at(-1) || null; return { ok:true, action:"remoteDesktopFrameLatest", frame:frame && publicFrame(frame), session:publicSession(session) }; }
function inputEvent(session, payload = {}) { const blocked = requireOpen(session); if (blocked) return blocked; if (!session.controlGranted) return block(403, "remote_desktop_control_not_granted", session); const type = String(payload.type || payload.inputType || "").toLowerCase(); if (!allowInputType(type)) return { ok:false, status:400, error:"remote_desktop_input_type_not_allowed", allowed:false, type }; const family = inputFamily(type); if (family === "mouse" && !session.mouseGranted) return block(403, "remote_desktop_mouse_not_granted", session); if (family === "keyboard" && !session.keyboardGranted) return block(403, "remote_desktop_keyboard_not_granted", session); const event = { at:Date.now(), type, x:numberOrNull(payload.x), y:numberOrNull(payload.y), key:payload.key || null, text:payload.text || null }; session.inputEvents.push(event); audit(session, "input", { type }); persist(); return { ok:true, action:"remoteDesktopInputEvent", event, session:publicSession(session) }; }
function publicFrame(frame) { return frame ? { at:frame.at, contentType:frame.contentType, bytes:frame.bytes, frame64:frame.frame64, note:frame.note } : null; }
function safeSignal(payload) { return { sdp:payload.sdp ? "configured" : undefined, candidate:payload.candidate ? "configured" : undefined, fingerprint:fingerprint(payload), label:payload.label || "" }; }
function fingerprint(payload) { return payload.fingerprint || (payload.sdp ? String(payload.sdp).slice(0, 24) : "not-provided"); }
function numberOrNull(value) { const n = Number(value); return Number.isFinite(n) ? n : null; }
module.exports = { addSignal, heartbeat, pushFrame, latestFrame, inputEvent };
