// B"H
/** @file treeGeometryBuilder.js @brief Branch tubes and curved leaf clusters with real normals. */
export class TreeGeometryBuilder {
  constructor(){this.verts=[];this.normals=[];this.uvs=[];this.indices=[];this.leafVerts=[];this.leafNorms=[];this.leafUVs=[];this.leafIndices=[];this.leafColors=[];this.vertOffset=0;this.leafOffset=0;}
  basis(q){const[x,y,z,w]=q,x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;return{r:[1-(yy+zz),xy+wz,xz-wy],f:[xz+wy,yz-wx,1-(xx+yy)],u:[2*(x*y-w*z),1-2*(x*x+z*z),2*(y*z+w*x)]};}
  addBranchSection(center, orientation, radius, segments, vCoord){const start=this.vertOffset,b=this.basis(orientation);for(let i=0;i<=segments;i++){const u=i/segments,t=u*Math.PI*2,c=Math.cos(t),s=Math.sin(t),nx=b.r[0]*c+b.f[0]*s,ny=b.r[1]*c+b.f[1]*s,nz=b.r[2]*c+b.f[2]*s;this.verts.push(center[0]+nx*radius,center[1]+ny*radius,center[2]+nz*radius);this.normals.push(nx,ny,nz);this.uvs.push(u,vCoord);this.vertOffset++;}return start;}
  stitch(a,b,segments){for(let i=0;i<segments;i++){this.indices.push(a+i,b+i,a+i+1,b+i,b+i+1,a+i+1);}}
  addCap(center, orientation, ringStart, segments, vCoord){const tip=this.vertOffset,u=this.basis(orientation).u;this.verts.push(...center);this.normals.push(...u);this.uvs.push(.5,vCoord+.1);this.vertOffset++;for(let i=0;i<segments;i++)this.indices.push(ringStart+i,ringStart+i+1,tip);}
  rotEuler(v, r){let[x,y,z]=v;const cx=Math.cos(r[0]),sx=Math.sin(r[0]),cy=Math.cos(r[1]),sy=Math.sin(r[1]),cz=Math.cos(r[2]),sz=Math.sin(r[2]);let nx=x*cz-y*sz,ny=x*sz+y*cz,nz=z;x=nx;y=ny;nx=x*cy+z*sy;nz=-x*sy+z*cy;x=nx;z=nz;ny=y*cx-z*sx;nz=y*sx+z*cx;return[x,ny,nz];}
  addLeaf(pos, size, rotation, color){const idx=this.leafOffset,curve=size*.12,half=size*.36;const local=[[-half,0,0],[half,0,0],[-half*.55,size*.52,curve],[half*.55,size*.52,curve],[0,size,curve*.35]];const uv=[[0,0],[1,0],[.15,.55],[.85,.55],[.5,1]];const a=this.rotEuler([0,0,1],rotation);for(let i=0;i<local.length;i++){const v=this.rotEuler(local[i],rotation);this.leafVerts.push(pos[0]+v[0],pos[1]+v[1],pos[2]+v[2]);this.leafNorms.push(a[0],a[1],a[2]);this.leafUVs.push(...uv[i]);this.leafColors.push(...color);}this.leafIndices.push(idx,idx+1,idx+2,idx+1,idx+3,idx+2,idx+2,idx+3,idx+4);this.leafOffset+=5;}
}
