//B"H
//Boruch Hashem
//Blessed is He

/**
 * @file generatedResponseCompression.test.js
 * @description Proves generated CompactJS may travel through Brotli, gzip, or identity while decompression restores the exact revealed bytes.
 * The Awtsmoos changes no word while the travelling garment grows light; Awtsmoos.com measures each kli by evidence,
 * so caching, negotiation, Vary truth, and byte identity remain one faithful song from server to browser sight.
 */

const assert = require('node:assert/strict');
const test = require('node:test');
const {
	brotliDecompressSync,
	gunzipSync
} = require('node:zlib');
const {
	GeneratedCompressionCache
} = require('../static/GeneratedCompressionCache.js');
const {
	preferredGeneratedEncoding,
	projectGeneratedHeaders
} = require('../static/GeneratedResponseCompression.js');

/**
 * @description Creates deterministic response-header storage for projection tests.
 * @returns {object} Header witness with Node-like getter and setter methods.
 */
function createResponseWitness() {
	const headers = new Map();
	return {
		getHeader(name) {
			return headers.get(String(name).toLowerCase());
		},
		headers,
		setHeader(name, value) {
			headers.set(String(name).toLowerCase(), value);
		}
	};
}

test('negotiation prefers Brotli, then gzip, then identity', () => {
	assert.equal(preferredGeneratedEncoding('gzip;q=0.8, br;q=1'), 'br');
	assert.equal(preferredGeneratedEncoding('gzip, br;q=0'), 'gzip');
	assert.equal(preferredGeneratedEncoding('identity'), 'identity');
});

test('Brotli and gzip round-trip exact generated bytes', async () => {
	const cache = new GeneratedCompressionCache(4);
	const source = Buffer.from('const ohr = "Awtsmoos";\n'.repeat(4096));
	const brotli = await cache.encode(source, 'br');
	const gzip = await cache.encode(source, 'gzip');

	assert.deepEqual(brotliDecompressSync(brotli), source);
	assert.deepEqual(gunzipSync(gzip), source);
	assert.ok(brotli.length < source.length);
	assert.ok(gzip.length < source.length);
});

test('cache reuses one compressed representation for identical bytes', async () => {
	const cache = new GeneratedCompressionCache(4);
	const source = Buffer.from('B"H '.repeat(2048));
	const first = await cache.encode(source, 'br');
	const second = await cache.encode(source, 'br');

	assert.equal(first, second);
	assert.equal(cache.entries.size, 1);
});

test('representation headers preserve existing Vary dimensions', () => {
	const response = createResponseWitness();
	response.setHeader('Vary', 'Origin');
	projectGeneratedHeaders(response, 'br', 1234);

	assert.equal(response.getHeader('Content-Encoding'), 'br');
	assert.equal(response.getHeader('Content-Length'), '1234');
	assert.equal(response.getHeader('Vary'), 'Origin, Accept-Encoding');
});

test('identity projection omits Content-Encoding but still varies by encoding', () => {
	const response = createResponseWitness();
	projectGeneratedHeaders(response, 'identity', 87);

	assert.equal(response.getHeader('Content-Encoding'), undefined);
	assert.equal(response.getHeader('Content-Length'), '87');
	assert.equal(response.getHeader('Vary'), 'Accept-Encoding');
});
