//B"H
/**
 * B"H
 * Chapter 183: The Settings Palace Became Clean Fire.
 *
 * The Awtsmoos reveals action without clutter: provider archives become a short
 * control deck in Settings, while the full row-list remains only in Archive.
 */
export const TAB_LABELS = { conversations: "Conversations", automation: "Automation", graph: "Graph", archive: "Archive", settings: "Settings", trace: "Trace filters" };
export const PROMPT_EXAMPLES = ["continue with the next precise verified step", "inspect the most uncertain result, then do the next safe action", "summarize what changed, then keep building without losing context", "choose one failing or unverified item and fix it completely", "continue the story naturally with vivid detail and real verification"];
const INSTALL_BASE = "https://awtsmoos.com/ai/relay/install";
const WINDOWS_COMMAND = `powershell -ExecutionPolicy Bypass -NoProfile -Command "irm ${INSTALL_BASE}/install-awtsmoos-chatgpt-relay.ps1 | iex"`;
const UNIX_COMMAND = `curl -fsSL ${INSTALL_BASE}/install-awtsmoos-chatgpt-relay.sh | sh`;

export function menu(tabName) { return `<details class="right-menu"><summary aria-label="Open settings sections"><span class="hamburger-bars">☰</span><span class="right-menu-current">${TAB_LABELS[tabName]}</span></summary><div class="right-tabs">${Object.entries(TAB_LABELS).map(([name, label]) => tab(name, label, tabName)).join("")}</div></details>`; }
export function automationFields(settings, conversationId) {
  const mode = settings.promptMode || "single";
  const promptCount = promptLines(settings.promptListText).length;
  return `<h3 class="panel-section-label">Automation Pipeline</h3><div class="automation-status chat-scope-pill">This chat: ${conversationId ? text(conversationId).slice(0, 26) : "new chat"} · ${settings.enabled ? "on" : "off"}</div><label class="automation-toggle-row automation-enable"><span><b>Enable auto-continue</b><small>Only this chat. Sends through the exact same controller as the normal Send button.</small></span><input data-auto="enabled" type="checkbox" ${checked(settings.enabled)}></label><div class="automation-card automation-timing-card"><h4>Timing</h4><p>Each turn waits a random delay between min and max.</p><div class="automation-grid timing-grid">${field("maxTurns", "Max turns", "number", settings.maxTurns)}${field("delayMinMs", "Delay min ms", "number", settings.delayMinMs)}${field("delayMaxMs", "Delay max ms", "number", settings.delayMaxMs)}${field("streamSettleMs", "Stream settle ms", "number", settings.streamSettleMs)}</div></div><div class="automation-card automation-prompt-card"><h4>Prompt</h4><label class="automation-field prompt-mode-field">Prompt mode<select data-auto="promptMode"><option value="single" ${sel(mode, "single")}>single prompt</option><option value="cycle" ${sel(mode, "cycle")}>cycle list</option><option value="random" ${sel(mode, "random")}>random from list</option></select></label><label class="automation-field prompt-field">Single prompt<textarea data-auto="prompt" rows="4">${text(settings.prompt)}</textarea></label>${promptListField(settings, promptCount)}</div><div class="automation-card automation-safety-card"><h4>Safety</h4><label class="automation-toggle-row compact"><span><b>Stop on error</b><small>Recommended when auth, 403, or transport errors appear.</small></span><input data-auto="stopOnError" type="checkbox" ${checked(settings.stopOnError !== false)}></label><button type="button" class="automation-stop-button" data-auto-action="stop">Stop this chat now</button></div><div class="automation-status" id="automation-status">${settings.enabled ? "automation armed for this chat" : "automation off for this chat"}</div>`;
}
function promptListField(settings, promptCount) { return `<label class="automation-field prompt-list-field">Prompt list, one per line<textarea data-auto="promptListText" rows="7">${text(settings.promptListText)}</textarea><small>${promptCount} prompt${promptCount === 1 ? "" : "s"}. Cycle walks the list; random chooses a line each turn.</small></label><div class="prompt-action-row"><button type="button" data-prompt-action="add-empty">Add prompt</button><button type="button" data-prompt-action="add-sample">Add sample</button><button type="button" data-prompt-action="remove-last">Remove last</button><button type="button" data-prompt-action="dedupe">Dedupe</button></div>`; }
export function conversationFields() { return `<section class="automation-card conversation-portal-card"><h3 class="panel-section-label">Conversations</h3><p class="panel-note">Open the left drawer on desktop or mobile, refresh history, or begin a clean chat.</p><div class="conversation-portal-actions"><button type="button" data-conversation-action="open">Open conversations drawer</button><button type="button" data-conversation-action="new">New chat</button><button type="button" data-conversation-action="refresh">Refresh list</button></div><div class="automation-status" id="conversation-status">conversation controls ready</div></section>`; }
export function exportFields() { return `<section class="automation-card chat-export-card settings-hero-card"><h3>Chat export</h3><p class="panel-note">Download the loaded RAM conversation as HTML or debug JSON.</p><div class="relay-actions"><button type="button" data-settings-action="download-chat-html">Download chat HTML</button><button type="button" data-settings-action="download-chat-json">Download debug JSON</button></div><div class="automation-status" id="settings-status">ready</div></section>`; }
export function providerArchiveFields(groups = [], compact = false) {
  if (compact) return providerCompactFields(groups);
  const rows = groups.flatMap(group => group.chats.map(chat => `<label class="provider-chat-row"><input type="checkbox" data-provider-chat-id="${attr(chat.id)}"><span><b>${text(group.provider.name)}</b>${text(chat.title || chat.id)}</span></label>`)).join("");
  return `<section class="automation-card provider-archive-card"><h3>MiniMax / OpenRouter / Groq chats</h3><p class="panel-note">Export all chats as JSON, import an existing JSON, or select specific chats to download or clear.</p><div class="provider-chat-list">${rows || `<p class="panel-note">No provider chats saved yet.</p>`}</div><div class="relay-actions"><button type="button" data-provider-chat-action="export-all">Export all JSON</button><button type="button" data-provider-chat-action="export-selected">Export selected</button><button type="button" data-provider-chat-action="clear-selected">Clear selected</button><button type="button" data-provider-chat-action="clear-all">Clear all provider chats</button><label class="provider-import-button">Import JSON<input type="file" accept="application/json,.json" data-provider-chat-import hidden></label></div><div class="automation-status" id="provider-chat-status">provider archive ready</div></section>`;
}
function providerCompactFields(groups) {
  const count = groups.reduce((sum, group) => sum + group.chats.length, 0);
  return `<section class="automation-card provider-archive-card provider-compact-card"><h3>Provider archive tools</h3><p class="panel-note">${count} saved MiniMax / OpenRouter / Groq chat${count === 1 ? "" : "s"}. Full per-chat selection lives in Archive.</p><div class="relay-actions compact-provider-actions"><button type="button" data-provider-chat-action="export-all">Download all provider chats</button><label class="provider-import-button">Import provider JSON<input type="file" accept="application/json,.json" data-provider-chat-import hidden></label><button type="button" data-provider-chat-action="clear-all">Clear all provider chats</button></div><div class="automation-status" id="provider-chat-status">provider archive tools ready</div></section>`;
}
export function archiveFields() { return `<section class="automation-archive-panel"><h3 class="panel-section-label">Automation Archive</h3><p class="panel-note">Assistant replies are stored for graph runs.</p><div class="graph-toolbar"><button type="button" data-archive-action="download">Download archive JSON</button><button type="button" data-archive-action="clear">Clear archive</button><button type="button" data-archive-action="count">Count messages</button></div><div class="automation-status" id="archive-status">archive ready</div></section>`; }
export function relayFields(relaySettings = {}) {
  return `<section class="automation-card relay-card settings-hero-card"><h3>ChatGPT transport</h3><p class="panel-note">Default is extension bridge. Node relay is experimental, downloadable, and local.</p><label class="automation-field">Relay URL<input data-relay="url" value="${attr(relaySettings.url)}"></label><label class="automation-toggle-row compact"><span><b>Use Node relay</b><small>Only enable after the local relay answers health.</small></span><input data-relay="enabled" type="checkbox" ${checked(relaySettings.enabled)}></label><div class="relay-actions"><button type="button" data-relay-action="health">Check relay</button><button type="button" data-relay-action="control">Open control</button><button type="button" data-relay-action="relay">Download relay</button><button type="button" data-relay-action="extension">Use extension</button></div>${installCards()}<div class="automation-status" id="relay-status">${relaySettings.enabled ? "Node relay selected" : "Extension bridge selected"}</div></section>`;
}
function installCards() { return `<div class="relay-install-grid">${installCard("Windows PowerShell", WINDOWS_COMMAND, "powershell")}${installCard("macOS / Linux", UNIX_COMMAND, "unix")}</div>`; }
function installCard(title, command, action) { return `<article class="relay-install-card"><b>${title}</b><p>Downloads relay to a fixed Awtsmoos folder, installs Node when possible, then starts it.</p><code>${text(command)}</code><div class="relay-install-buttons"><button type="button" data-relay-action="${action}">Download script</button><button type="button" data-relay-copy>Copy command</button></div></article>`; }
export function visibilityFields(types = [], eventVisibility = {}, label) { return `<div class="event-filter-grid">${types.map(type => `<label class="automation-field event-filter"><input data-event-type="${type}" type="checkbox" ${checked(eventVisibility[type] !== false)}> Show ${label(type)}</label>`).join("")}</div>`; }
export function promptLines(value = "") { return String(value || "").split(/\r?\n+/).map(item => item.trim()).filter(Boolean); }
function tab(name, label, active) { return `<button type="button" data-tab="${name}" class="${active === name ? "active" : ""}">${label}</button>`; }
function field(name, label, type, value) { return `<label class="automation-field">${label}<input data-auto="${name}" type="${type}" value="${attr(value)}"></label>`; }
export function attr(value) { return String(value ?? "").replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }
export function text(value) { return String(value ?? "").replace(/[&<>]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c])); }
function checked(value) { return value ? "checked" : ""; }
function sel(value, option) { return value === option ? "selected" : ""; }
