//B"H
/**
 * Chapter 13: The Transport Panel Became A Three-Gated City.
 *
 * Extension, Node relay, and Awtsmoos Tunnel now appear together. The Tunnel
 * card carries install commands, a local API URL, ChatGPT login checks, and a
 * MerkavaExecutor fallback for places where Chrome is not available.
 */
export const TAB_LABELS = { conversations: "Conversations", automation: "Automation", graph: "Graph", archive: "Archive", settings: "Settings", trace: "Trace filters" };
export const PROMPT_EXAMPLES = ["continue with the next precise verified step", "inspect the most uncertain result, then do the next safe action", "summarize what changed, then keep building without losing context", "choose one failing or unverified item and fix it completely", "continue the story naturally with vivid detail and real verification"];
const INSTALL_BASE = "https://awtsmoos.com/ai/relay/install";
const WINDOWS_COMMAND = `powershell -ExecutionPolicy Bypass -NoProfile -Command "irm ${INSTALL_BASE}/install-awtsmoos-chatgpt-relay.ps1 | iex"`;
const UNIX_COMMAND = `curl -fsSL ${INSTALL_BASE}/install-awtsmoos-chatgpt-relay.sh | sh`;
const TUNNEL_WINDOWS_COMMAND = "irm https://awtsmoos.com/api/tunnel/install/windows | iex";
const TUNNEL_UNIX_COMMAND = "curl -fsSL https://awtsmoos.com/api/tunnel/install/unix | bash";

export function menu(tabName) { return `<details class="right-menu"><summary aria-label="Open settings sections"><span class="hamburger-bars">☰</span><span class="right-menu-current">${TAB_LABELS[tabName]}</span></summary><div class="right-tabs">${Object.entries(TAB_LABELS).map(([name, label]) => tab(name, label, tabName)).join("")}</div></details>`; }
export function automationFields(settings, conversationId) { const mode = settings.promptMode || "single"; const promptCount = promptLines(settings.promptListText).length; return `<h3 class="panel-section-label">Automation Pipeline</h3><div class="automation-status chat-scope-pill">This chat: ${conversationId ? text(conversationId).slice(0, 26) : "new chat"} · ${settings.enabled ? "on" : "off"}</div><label class="automation-toggle-row automation-enable"><span><b>Enable auto-continue</b><small>Only this chat. Visible-page mode sends through the exact same controller as the normal Send button.</small></span><input data-auto="enabled" type="checkbox" ${checked(settings.enabled)}></label><label class="automation-toggle-row automation-background-owner"><span><b>Keep running after this tab closes</b><small>Uses extension background when available, otherwise Node relay or Awtsmoos Tunnel.</small></span><input data-auto="backgroundOwned" type="checkbox" ${checked(settings.backgroundOwned || settings.background)}></label><div class="automation-card automation-timing-card"><h4>Timing</h4><p>Each turn waits a random delay between min and max.</p><div class="automation-grid timing-grid">${field("maxTurns", "Max turns", "number", settings.maxTurns)}${field("delayMinMs", "Delay min ms", "number", settings.delayMinMs)}${field("delayMaxMs", "Delay max ms", "number", settings.delayMaxMs)}${field("streamSettleMs", "Stream settle ms", "number", settings.streamSettleMs)}</div></div><div class="automation-card automation-prompt-card"><h4>Prompt</h4><label class="automation-field prompt-mode-field">Prompt mode<select data-auto="promptMode"><option value="single" ${sel(mode, "single")}>single prompt</option><option value="cycle" ${sel(mode, "cycle")}>cycle list</option><option value="random" ${sel(mode, "random")}>random from list</option></select></label><label class="automation-field prompt-field">Single prompt<textarea data-auto="prompt" rows="4">${text(settings.prompt)}</textarea></label>${promptListField(settings, promptCount)}</div><div class="automation-card automation-safety-card"><h4>Safety</h4><label class="automation-toggle-row compact"><span><b>Stop on error</b><small>Recommended when auth, 403, or transport errors appear.</small></span><input data-auto="stopOnError" type="checkbox" ${checked(settings.stopOnError !== false)}></label><button type="button" class="automation-stop-button" data-auto-action="stop">Stop this chat now</button></div><div class="automation-status" id="automation-status">${automationStatusText(settings)}</div>`; }
function automationStatusText(settings = {}) { if (!settings.enabled) return "automation off for this chat"; return settings.backgroundOwned || settings.background ? "automation armed · background owner after tab close" : "automation armed · visible Send path"; }
function promptListField(settings, promptCount) { return `<label class="automation-field prompt-list-field">Prompt list, one per line<textarea data-auto="promptListText" rows="7">${text(settings.promptListText)}</textarea><small>${promptCount} prompt${promptCount === 1 ? "" : "s"}. Cycle walks the list; random chooses a line each turn.</small></label><div class="prompt-action-row"><button type="button" data-prompt-action="add-empty">Add prompt</button><button type="button" data-prompt-action="add-sample">Add sample</button><button type="button" data-prompt-action="remove-last">Remove last</button><button type="button" data-prompt-action="dedupe">Dedupe</button></div>`; }
export function conversationFields() { return `<section class="automation-card conversation-portal-card"><h3 class="panel-section-label">Conversations</h3><p class="panel-note">Open the left drawer on desktop or mobile, refresh history, or begin a clean chat.</p><div class="conversation-portal-actions"><button type="button" data-conversation-action="open">Open conversations drawer</button><button type="button" data-conversation-action="new">New chat</button><button type="button" data-conversation-action="refresh">Refresh list</button></div><div class="automation-status" id="conversation-status">conversation controls ready</div></section>`; }
export function exportFields() { return `<section class="automation-card chat-export-card settings-hero-card"><h3>Chat export</h3><p class="panel-note">Download the loaded RAM conversation as HTML or debug JSON.</p><div class="relay-actions"><button type="button" data-settings-action="download-chat-html">Download chat HTML</button><button type="button" data-settings-action="download-chat-json">Download debug JSON</button></div><div class="automation-status" id="settings-status">ready</div></section>`; }
export function providerArchiveFields(groups = [], compact = false) { if (compact) return providerCompactFields(groups); const rows = groups.flatMap(group => group.chats.map(chat => `<label class="provider-chat-row"><input type="checkbox" data-provider-chat-id="${attr(chat.id)}"><span><b>${text(group.provider.name)}</b>${text(chat.title || chat.id)}</span></label>`)).join(""); return `<section class="automation-card provider-archive-card"><h3>MiniMax / OpenRouter / Groq chats</h3><p class="panel-note">Export all chats as JSON, import an existing JSON, or select specific chats to download or clear.</p><div class="provider-chat-list">${rows || `<p class="panel-note">No provider chats saved yet.</p>`}</div><div class="relay-actions"><button type="button" data-provider-chat-action="export-all">Export all JSON</button><button type="button" data-provider-chat-action="export-selected">Export selected</button><button type="button" data-provider-chat-action="clear-selected">Clear selected</button><button type="button" data-provider-chat-action="clear-all">Clear all provider chats</button><label class="provider-import-button">Import JSON<input type="file" accept="application/json,.json" data-provider-chat-import hidden></label></div><div class="automation-status" id="provider-chat-status">provider archive ready</div></section>`; }
function providerCompactFields(groups) { const count = groups.reduce((sum, group) => sum + group.chats.length, 0); return `<section class="automation-card provider-archive-card provider-compact-card"><h3>Provider archive tools</h3><p class="panel-note">${count} saved MiniMax / OpenRouter / Groq chat${count === 1 ? "" : "s"}. Full per-chat selection lives in Archive.</p><div class="relay-actions compact-provider-actions"><button type="button" data-provider-chat-action="export-all">Download all provider chats</button><label class="provider-import-button">Import provider JSON<input type="file" accept="application/json,.json" data-provider-chat-import hidden></label><button type="button" data-provider-chat-action="clear-all">Clear all provider chats</button></div><div class="automation-status" id="provider-chat-status">provider archive tools ready</div></section>`; }
export function archiveFields() { return `<section class="automation-archive-panel"><h3 class="panel-section-label">Automation Archive</h3><p class="panel-note">Assistant replies are stored for graph runs.</p><div class="graph-toolbar"><button type="button" data-archive-action="download">Download archive JSON</button><button type="button" data-archive-action="clear">Clear archive</button><button type="button" data-archive-action="count">Count messages</button></div><div class="automation-status" id="archive-status">archive ready</div></section>`; }
export function relayFields(relaySettings = {}) { const mode = relaySettings.mode || (relaySettings.enabled ? "node" : "extension"); return `<section class="automation-card relay-card settings-hero-card"><h3>ChatGPT transport</h3><p class="panel-note">Choose Extension, standalone Node relay, or Awtsmoos Tunnel. Tunnel is useful for ChatGPT and other AI tools because it exposes the shared local API.</p><label class="automation-field">Transport<select data-relay="mode"><option value="extension" ${sel(mode, "extension")}>Extension bridge</option><option value="node" ${sel(mode, "node")}>Standalone Node relay</option><option value="tunnel" ${sel(mode, "tunnel")}>Awtsmoos Tunnel local API</option></select></label><label class="automation-field">Node relay URL<input data-relay="url" value="${attr(relaySettings.url)}"></label><label class="automation-field">Awtsmoos Tunnel local API<input data-relay="tunnelUrl" value="${attr(relaySettings.tunnelUrl)}"></label><label class="automation-toggle-row compact"><span><b>Use MerkavaExecutor when Chrome is unavailable</b><small>Runs tunnel simulateRuntime with engine=merkava as an optional fallback/login diagnostic.</small></span><input data-relay="useMerkavaExecutor" type="checkbox" ${checked(relaySettings.useMerkavaExecutor !== false)}></label><div class="relay-actions"><button type="button" data-relay-action="health">Check selected</button><button type="button" data-relay-action="control">Open Node control</button><button type="button" data-relay-action="tunnel-health">Try tunnel</button><button type="button" data-relay-action="tunnel-login">ChatGPT login via tunnel</button><button type="button" data-relay-action="tunnel-merkava">MerkavaExecutor test</button><button type="button" data-relay-action="extension">Use extension</button></div>${installCards()}${tunnelInstallCards()}<div class="automation-status" id="relay-status">${statusText(mode)}</div></section>`; }
function statusText(mode) { return mode === "tunnel" ? "Awtsmoos Tunnel selected" : mode === "node" ? "Node relay selected" : "Extension bridge selected"; }
function installCards() { return `<div class="relay-install-grid">${installCard("Node relay · Windows PowerShell", WINDOWS_COMMAND, "powershell", "Downloads the split-browser relay, installs Node when possible, starts the local server, then prints the control URL.")}${installCard("Node relay · macOS / Linux / Termux", UNIX_COMMAND, "unix", "Downloads the split-browser relay and starts the local relay server.")}</div>`; }
function tunnelInstallCards() { return `<div class="relay-install-grid">${installCard("Awtsmoos Tunnel · Windows", TUNNEL_WINDOWS_COMMAND, "tunnel-control", "Installs or refreshes Awtsmoos Tunnel, reuses the saved tunnel name, and starts the local API.")}${installCard("Awtsmoos Tunnel · macOS / Linux / Termux", TUNNEL_UNIX_COMMAND, "tunnel-control", "Installs or refreshes Awtsmoos Tunnel, reuses the saved tunnel name, and starts the local API.")}</div>`; }
function installCard(title, command, action, description) { return `<article class="relay-install-card"><b>${title}</b><p>${description}</p><code>${text(command)}</code><div class="relay-install-buttons"><button type="button" data-relay-action="${action}">${action === "tunnel-control" ? "Open install page" : "Download script"}</button><button type="button" data-relay-copy>Copy command</button></div></article>`; }
export function visibilityFields(types = [], eventVisibility = {}, label) { return `<div class="event-filter-grid">${types.map(type => `<label class="automation-field event-filter"><input data-event-type="${type}" type="checkbox" ${checked(eventVisibility[type] !== false)}> Show ${label(type)}</label>`).join("")}</div>`; }
export function promptLines(value = "") { return String(value || "").split(/\r?\n+/).map(item => item.trim()).filter(Boolean); }
function tab(name, label, active) { return `<button type="button" data-tab="${name}" class="${active === name ? "active" : ""}">${label}</button>`; }
function field(name, label, type, value) { return `<label class="automation-field">${label}<input data-auto="${name}" type="${type}" value="${attr(value)}"></label>`; }
export function attr(value) { return String(value ?? "").replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c])); }
export function text(value) { return String(value ?? "").replace(/[&<>]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c])); }
function checked(value) { return value ? "checked" : ""; }
function sel(value, option) { return value === option ? "selected" : ""; }
