// B"H
// Boruch Hashem
// Blessed is He

/**
 * @file test/lightning/tests.js
 * @chapter The Gates Of Verification Stand As One Court
 * @description
 * Declares every strict test in deterministic order. The Awtsmoos renews each
 * gate independently, so a later success can never conceal an earlier failure.
 * Awtsmoos.com carries the full court through storage, vacuum, recovery, leases,
 * search, vectors, isolation, and production behavior.
 */

module.exports = [
	'dosdb_parallel_awtsmoosdb_test.js',
	'ai_search_bridge_test.js',
	'ai_search_internals_test.js',
	'ai_search_embedder_config_test.js',
	'ai_search_model_root_precedence_test.js',
	'omni_test.js',
	'live_test.js',
	'pashut.js',
	'api_methods_test.js',
	'blog_engine_simulation.js',
	'circular_stress.js',
	'class_resurrection.js',
	'comprehensive_features.js',
	'compression_extreme_test.js',
	'storage_density_test.js',
	'compact_json_test.js',
	'compact_cli_refusal_test.js',
	'storage_reuse_test.js',
	'packed_object_test.js',
	'packed_density_test.js',
	'packed_array_test.js',
	'migration_density_test.js',
	'migration_searchable_packed_test.js',
	'packed_features_index_vector_test.js',
	'runtime_features_test.js',
	'pager_sparse_test.js',
	'gc_verify_test.js',
	'verified_free_list_test.js',
	'verified_complement_reuse_test.js',
	'verify_blob_tokens_test.js',
	'strict_read_only_test.js',
	'strict_read_only_virtual_fs_test.js',
	'storage_report_test.js',
	'atomic_swap_rollback_test.js',
	'vacuum_out_of_place_test.js',
	'vacuum_sequence_density_test.js',
	'sequence_metadata_test.js',
	'live_handle_identity_test.js',
	'vacuum_virtual_fs_test.js',
	'vacuum_search_index_test.js',
	'vector_bulk_load_test.js',
	'vector_verified_complement_test.js',
	'vacuum_vector_index_test.js',
	'indexed_restart_mutation_test.js',
	'map_root_split_test.js',
	'search_bulk_reindex_test.js',
	'wal_recovery_test.js',
	'blob_fs_test.js',
	'unlinked_blob_lease_test.js',
	'concurrent_text_test.js',
	'turbo_writebehind_test.js',
	'deep_turbo_ai_test.js',
	'semantic_ai_dosdb_test.js',
	'polyglot_api_test.js',
	'sparse_array_dream_test.js',
	'production_features_test.js',
	'production_hardening_test.js',
	'complex.js',
	'comprehensive_v2.js',
	'function_test.js',
	'consistency.js',
	'final_boss.js',
	'genesis.js',
	'graph_algo_test.js',
	'interactive.js',
	'mega_simulation.js',
	'nested.js',
	'nested_literal_proof.js',
	'object_order.js',
	'omega_simulation.js',
	'persistence_stress.js',
	'production_ready.js',
	'query_complex.js',
	'query_test.js',
	'range_test.js',
	'search_test.js',
	'simulation_omniverse.js',
	'simulate_eternity.js',
	'singularity.js',
	'splice_test.js',
	'stress_test.js',
	'suite.js',
	'type_confirmation.js',
	'ultimate.js',
	'ultimate_chaos.js',
	'ultimate_feature_test.js',
	'universal_types.js',
	'usage.js',
	'v2_flawless.js',
	'v2_test.js',
	'vector_test.js'
];
