
// B"H

/**
 * @file test/lightning/tests.js
 * @chapter The Forty Three Gates
 * @description
 * One data list. No runner logic mixed in.
 */

module.exports = [
  'omni_test.js',
  'live_test.js',
  'pashut.js',
  'api_methods_test.js',
  'blog_engine_simulation.js',
  'circular_stress.js',
  'class_resurrection.js',
  'comprehensive_features.js',
  'compression_extreme_test.js',
  'storage_density_test.js',
  'storage_reuse_test.js',
  'runtime_features_test.js',
  'pager_sparse_test.js',
  'gc_verify_test.js',
  'wal_recovery_test.js',
  'blob_fs_test.js',
  'concurrent_text_test.js',
  'turbo_writebehind_test.js',
  'deep_turbo_ai_test.js',
  'semantic_ai_dosdb_test.js',
  'polyglot_api_test.js',
  'sparse_array_dream_test.js',
  'production_features_test.js',
  'production_hardening_test.js',
  'complex.js',
  'comprehensive_v2.js',
  'function_test.js',
  'consistency.js',
  'final_boss.js',
  'genesis.js',
  'graph_algo_test.js',
  'interactive.js',
  'mega_simulation.js',
  'nested.js',
  'nested_literal_proof.js',
  'object_order.js',
  'omega_simulation.js',
  'persistence_stress.js',
  'production_ready.js',
  'query_complex.js',
  'query_test.js',
  'range_test.js',
  'search_test.js',
  'simulation_omniverse.js',
  'simulate_eternity.js',
  'singularity.js',
  'splice_test.js',
  'stress_test.js',
  'suite.js',
  'type_confirmation.js',
  'ultimate.js',
  'ultimate_chaos.js',
  'ultimate_feature_test.js',
  'universal_types.js',
  'usage.js',
  'v2_flawless.js',
  'v2_test.js',
  'vector_test.js'
];
