// B"H
/** @file LevelCurveRuntime.js @description Levels are ascent: similar struggle gives fuller XP, ascent grants new strength. */
export function xpForLevel(level=1){ return Math.max(0,Math.round(80*Math.pow(Math.max(1,level)-1,1.55))); }
export function levelFromXp(xp=0){ let level=1; while(xp>=xpForLevel(level+1)) level++; return level; }
export function xpReward({victorLevel=1,targetLevel=1,base=18}={}){ const gap=Math.abs(victorLevel-targetLevel), similarity=Math.max(.15,1-gap*.16), challenge=targetLevel>=victorLevel?1+(targetLevel-victorLevel)*.18:1; return Math.max(1,Math.round(base*targetLevel*similarity*challenge)); }
export function statGrowth(level=1){ return {maxHealth:Math.round(90+level*12),maxStamina:Math.round(80+level*7),attack:Math.round(5+level*1.8),defense:Math.round(2+level*1.25),speed:+(1+Math.min(.75,level*.018)).toFixed(3),focus:Math.round(3+level*1.4)}; }
export class ProgressionRuntime{ constructor(runtime){ this.runtime=runtime; this.records=new Map(); this.history=[]; } ensure(actorId="player",seed={}){ const seedXp=seed.xp??(seed.level?xpForLevel(seed.level):0), seedLevel=seed.level||levelFromXp(seedXp); if(!this.records.has(actorId)){ this.records.set(actorId,{actorId,xp:seedXp,level:seedLevel,stats:statGrowth(seedLevel)}); } else if(seed.level||seed.xp){ const rec=this.records.get(actorId); rec.xp=Math.max(rec.xp,seedXp); rec.level=Math.max(rec.level,seedLevel,levelFromXp(rec.xp)); rec.stats=statGrowth(rec.level); } return this.records.get(actorId); } award(actorId="player",target={level:1},source={}){ const rec=this.ensure(actorId), gained=xpReward({victorLevel:rec.level,targetLevel:target.level||1,base:source.baseXp||18}); rec.xp+=gained; const before=rec.level; rec.level=levelFromXp(rec.xp); rec.stats=statGrowth(rec.level); const tx={ok:true,actorId,gained,beforeLevel:before,afterLevel:rec.level,leveledUp:rec.level>before,stats:rec.stats,source}; this.history.push(tx); return tx; } snapshot(actorId="player"){ return {...this.ensure(actorId),history:this.history.filter(x=>x.actorId===actorId).slice(-20)}; } }
export function createProgressionRuntime(runtime){ return new ProgressionRuntime(runtime); }
export default createProgressionRuntime;
