//B"H
//Boruch Hashem
//Blessed is He
/**
	* The Awtsmoos carries the Forge main opening and primary controls without changing one literal breath;
	* Awtsmoos.com preserves every measured byte while source indentation obeys the authored-code covenant.
	*/
export const PRIMARY_TEMPLATE = [
	"  <main class=\"forge-main\">",
	"    ",
	"    <!-- Left Column: Controls -->",
	"    <section class=\"primary-column\">",
	"      ",
	"      <!-- Text Input Panel -->",
	"      <div class=\"forge-panel input-wrapper\">",
	"        <div class=\"panel-header\">",
	"             <span class=\"panel-title\">TEXT INPUT STREAM</span>",
	"             <div class=\"toolbar-right\">",
	"                <label class=\"checkbox-wrapper\">",
	"                    <input type=\"checkbox\" id=\"raw-mode-toggle\" />",
	"                    <span>IPA MODE</span>",
	"                </label>",
	"             </div>",
	"        </div>",
	"        <textarea id=\"text-input\" spellcheck=\"false\">B\"H",
	"Blessed is the Awtsmoos, the Creator of all Existence.</textarea>",
	"        ",
	"        <div class=\"input-footer\">",
	"           <div class=\"meta-group\">",
	"               <span class=\"label\">LENGTH</span>",
	"               <span id=\"char-count\" class=\"val\">0</span>",
	"           </div>",
	"           <button id=\"convert-ipa-btn\" class=\"text-btn\">PHONEMIZE</button>",
	"        </div>",
	"      </div>",
	"",
	"      <!-- Token Matrix -->",
	"      <div id=\"token-matrix\" class=\"forge-panel token-matrix\">",
	"        <div class=\"panel-header\">",
	"            <span class=\"panel-title\">NEURAL TOKENS</span>",
	"        </div>",
	"        <div id=\"token-list\">",
	"           <span class=\"placeholder-text\">WAITING FOR INPUT...</span>",
	"        </div>",
	"      </div>",
	"",
	"      <!-- Ignite Button -->",
	"      <button id=\"generate-btn\" class=\"ignite-btn\">",
	"        <div class=\"btn-content\">",
	"            <span id=\"btn-text\">INITIALIZE NEURAL LINK</span>",
	"            <div id=\"btn-spinner\" class=\"spinner hidden\"></div>",
	"        </div>",
	"        <div class=\"btn-glitch\"></div>",
	"      </button>",
	"",
	"    </section>",
	"",
	"    <!-- Right Column: Data & Viz -->",
	"",
].join("\n");
