//B"H
//Boruch Hashem
//Blessed is He
/**
	* The Awtsmoos carries the secondary Forge instruments through the closing main tag in measured order;
	* Awtsmoos.com preserves every measured byte while source indentation obeys the authored-code covenant.
	*/
export const SECONDARY_TEMPLATE = [
	"    <section class=\"secondary-column\">",
	"      ",
	"      <!-- Visualizer -->",
	"      <div class=\"forge-panel viz-panel\">",
	"        <canvas id=\"visualizer\"></canvas>",
	"        <div id=\"visualizer-placeholder\" class=\"viz-overlay\">",
	"            <span>AWAITING VIBRATION</span>",
	"        </div>",
	"      </div>",
	"",
	"      <!-- Audio Controls -->",
	"      <div class=\"forge-panel audio-panel\">",
	"         <audio id=\"audio-player\" controls></audio>",
	"         <a id=\"download-btn\" class=\"download-btn disabled\" download=\"manifestation.wav\">",
	"            DOWNLOAD WAV",
	"         </a>",
	"      </div>",
	"",
	"      <!-- Progress Module -->",
	"      <div class=\"forge-panel progress-panel\">",
	"        <div class=\"panel-header\"><span class=\"panel-title\">SYSTEM STATUS</span></div>",
	"        ",
	"        <div class=\"progress-row\">",
	"            <div class=\"prog-label\">",
	"                <span>MODEL WEIGHTS</span>",
	"                <span id=\"load-progress-val\">0%</span>",
	"            </div>",
	"            <div class=\"track\"><div id=\"load-progress-fill\" class=\"fill cyan\"></div></div>",
	"        </div>",
	"",
	"        <div class=\"progress-row\">",
	"            <div class=\"prog-label\">",
	"                <span>VOICE BANK</span>",
	"                <span id=\"voice-progress-val\">0%</span>",
	"            </div>",
	"            <div class=\"track\"><div id=\"voice-progress-fill\" class=\"fill purple\"></div></div>",
	"        </div>",
	"",
	"        <div class=\"progress-row\">",
	"            <div class=\"prog-label\">",
	"                <span>SYNTHESIS</span>",
	"                <span id=\"gen-progress-val\">0%</span>",
	"            </div>",
	"            <div class=\"track\"><div id=\"gen-progress-fill\" class=\"fill white\"></div></div>",
	"        </div>",
	"      </div>",
	"",
	"      <!-- Data Management -->",
	"      <div class=\"forge-panel data-panel\">",
	"         <div class=\"panel-header\"><span class=\"panel-title\">STORAGE MATRIX (IndexedDB)</span></div>",
	"         <div class=\"data-grid\">",
	"             <div class=\"data-item\">",
	"                 <span>MODEL</span>",
	"                 <span id=\"model-status\" class=\"status-badge missing\">MISSING</span>",
	"             </div>",
	"             <div class=\"data-item\">",
	"                 <span>VOICE</span>",
	"                 <span id=\"voice-status\" class=\"status-badge missing\">MISSING</span>",
	"             </div>",
	"             <div class=\"data-item\">",
	"                 <span>TOKENIZER</span>",
	"                 <span id=\"tokenizer-status\" class=\"status-badge missing\">MISSING</span>",
	"             </div>",
	"         </div>",
	"         <div class=\"data-actions\">",
	"            <button id=\"purge-btn\" class=\"danger-btn\">PURGE CACHE</button>",
	"         </div>",
	"      </div>",
	"      ",
	"      <!-- Speed Control -->",
	"      <div class=\"forge-panel control-panel\">",
	"          <div class=\"panel-header\">",
	"            <span class=\"panel-title\">TEMPORAL DENSITY</span>",
	"            <span id=\"speed-val\">1.0</span>",
	"          </div>",
	"          <input type=\"range\" id=\"speed-slider\" min=\"0.5\" max=\"2.0\" step=\"0.1\" value=\"1.0\">",
	"      </div>",
	"",
	"      <!-- Logs -->",
	"      <div class=\"log-panel\" id=\"logs\"></div>",
	"",
	"    </section>",
	"  </main>",
	"",
].join("\n");
