// B"H
const fs = require("fs");
const path = require("path");
const childProcess = require("child_process");
const { ROOT, loadConfig, saveConfigPatch } = require("../../lib/config.js");
const { findChrome, chromeFindDetails } = require("./finder.js");
const { version, pages, newPage, closePage, ensurePage, cdpCall, navigateAndWait, leaseTarget, releaseTarget, targetLease, targetLeaseSnapshot } = require("./cdp.js");
const { boolish, chromeLaunchArgs } = require("./launchArgs.js");
const { addChromeLog, readChromeLogs } = require("./logs.js");
const { pageSnapshot } = require("./snapshot.js");
const { compactRemoteResult, compactLogs, compactExpression } = require("./compact.js");
function wait(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }
function requireChromeEnabled(config, action) { return !config.chrome.enabled || !config.tools.chrome ? { ok:false, action, error:"chrome_disabled", message:"Enable Chrome tool in dashboard and Save Config." } : null; }
function logOptions(payload = {}) { return { maxLogs:Number(payload.maxLogs ?? 20), clear:!!payload.clearLogs }; }
function readCompactLogs(payload = {}) { return compactLogs(readChromeLogs(logOptions(payload)), payload.maxLogs ?? 20); }
function timeoutOf(payload = {}, fallback = 30000) { const n = Number(payload.timeoutMs || fallback); return Number.isFinite(n) ? Math.max(1000, Math.min(n, Number(process.env.AWTSMOOS_CHROME_MAX_TIMEOUT_MS || 86400000))) : fallback; }
function chromeConfig(payload, action) { const config = loadConfig(), blocked = requireChromeEnabled(config, action); return { config, blocked, port:Number(payload.port || config.chrome.port || 9222) }; }
async function chromeFind() { return { ok:true, action:"chromeFind", ...chromeFindDetails() }; }
async function chromeLaunch(payload = {}) { const config = loadConfig(), blocked = requireChromeEnabled(config, "chromeLaunch"); if (blocked) return blocked; const port = Number(payload.port || config.chrome.port || 9222), chromePath = payload.chromePath || config.chrome.path || findChrome(); if (!chromePath) return { ok:false, action:"chromeLaunch", error:"chrome_not_found", ...chromeFindDetails(), message:"Could not auto-detect browser executable." }; const userDataDir = payload.userDataDir || config.chrome.userDataDir || path.join(ROOT, "chrome-profile"), headless = boolish(payload.headless, boolish(config.chrome.headless, false)), args = chromeLaunchArgs({ port, userDataDir, headless, url:payload.url }); fs.mkdirSync(userDataDir, { recursive:true }); const proc = childProcess.spawn(chromePath, args, { detached:true, stdio:["ignore", "pipe", "pipe"] }); proc.stdout?.on("data", c => addChromeLog("process.stdout", "info", c.toString("utf8").trim())); proc.stderr?.on("data", c => addChromeLog("process.stderr", "error", c.toString("utf8").trim())); proc.on("error", err => addChromeLog("process", "error", err.message, { stack:err.stack })); proc.unref(); saveConfigPatch({ chrome:{ enabled:true, path:chromePath, chromePath, port, userDataDir, headless }, tools:{ chrome:true } }); await wait(Number(payload.startupWaitMs || 1600)); await ensurePage(port, { forceReconnect:true, timeoutMs:timeoutOf(payload, 15000) }); return { ok:true, action:"chromeLaunch", chromePath, port, userDataDir, headless, argsCount:args.length, url:payload.url || "", logs:readCompactLogs(payload) }; }
async function chromeStatus(payload = {}) { const { config, port } = chromeConfig(payload, "chromeStatus"); try { const info = await version(port), list = await pages(port); return { ok:true, action:"chromeStatus", connected:true, port, chromePath:config.chrome.path || findChrome(), headless:!!config.chrome.headless, info:{ Browser:info.Browser, ProtocolVersion:info.ProtocolVersion, webSocketDebuggerUrl:Boolean(info.webSocketDebuggerUrl) }, pageCount:list.length, pages:list.map(targetView).slice(0, Number(payload.maxPages || 10)), targetLeases:targetLeaseSnapshot(), logs:readCompactLogs(payload) }; } catch (e) { return { ok:true, action:"chromeStatus", connected:false, port, chromePath:config.chrome.path || findChrome(), ...chromeFindDetails(), error:e.message, logs:readCompactLogs(payload) }; } }
async function chromeTargets(payload = {}) { const { blocked, port } = chromeConfig(payload, "chromeTargets"); if (blocked) return blocked; const list = await pages(port); return { ok:true, action:"chromeTargets", port, count:list.length, targets:list.map(targetView), targetLeases:targetLeaseSnapshot() }; }
async function chromeNewPage(payload = {}) { const { blocked, port } = chromeConfig(payload, "chromeNewPage"); if (blocked) return blocked; const target = await newPage(port, payload.url || "about:blank"); const lease = leaseTarget(target.id, targetOptions(payload)); await ensurePage(port, { ...targetOptions(payload), pageId:target.id, forceReconnect:true }); return { ok:true, action:"chromeNewPage", port, target:targetView(target), chromeTargetId:target.id, pageId:target.id, lease }; }
async function chromeClosePage(payload = {}) { const { blocked, port } = chromeConfig(payload, "chromeClosePage"); if (blocked) return blocked; const targetId = payload.chromeTargetId || payload.pageId || payload.targetId; if (!targetId) return { ok:false, action:"chromeClosePage", error:"missing_chromeTargetId" }; const lease = targetLease(targetId); if (lease && !lease.shared && !leaseMatches(lease, payload) && payload.force !== true) return { ok:false, action:"chromeClosePage", error:"target_lease_mismatch", chromeTargetId:targetId, lease }; const closed = await closePage(port, targetId); releaseTarget(targetId); return { ok:true, action:"chromeClosePage", port, chromeTargetId:targetId, closed, released:true }; }
async function chromeNavigate(payload = {}) { const { blocked, port } = chromeConfig(payload, "chromeNavigate"); if (blocked) return blocked; if (payload.clearLogs !== false) readChromeLogs({ clear:true }); const url = payload.url || "about:blank", timeout = timeoutOf(payload, 30000), options = targetOptions(payload); const nav = await navigateAndWait(url, timeout, port, options); if (payload.waitMs) await wait(Math.min(Number(payload.waitMs), 30000)); const out = { ok:nav.ok !== false, action:"chromeNavigate", url, port, navigation:nav, target:options, logs:readCompactLogs(payload) }; if (out.ok === false) out.diagnostics = await navigationDiagnostics(port, payload, nav); if (payload.snapshot === true) out.snapshot = await pageSnapshot({ ...payload, maxText:Math.min(Number(payload.maxText || 1200), 3000), maxLogs:20 }); return out; }
async function chromeEval(payload = {}) { const { blocked, port } = chromeConfig(payload, "chromeEval"); if (blocked) return blocked; await ensurePage(port, targetOptions(payload)); const expression = payload.expression || payload.script || "document.title"; try { const result = await cdpCall("Runtime.evaluate", { expression, awaitPromise:true, returnByValue:true }, timeoutOf(payload)); return { ok:true, action:"chromeEval", expression:compactExpression(expression), target:targetOptions(payload), result:compactRemoteResult(result, Number(payload.maxValueChars || payload.maxChars || 12000)), logs:readCompactLogs(payload) }; } catch (e) { return { ok:false, action:"chromeEval", error:e.message, expression:compactExpression(expression), target:targetOptions(payload), logs:readCompactLogs(payload) }; } }
async function chromeWaitForSelector(payload = {}) { const { blocked, port } = chromeConfig(payload, "chromeWaitForSelector"); if (blocked) return blocked; await ensurePage(port, targetOptions(payload)); const selector = payload.selector, timeout = timeoutOf(payload, 10000); if (!selector) return { ok:false, action:"chromeWaitForSelector", error:"missing_selector" }; const start = Date.now(); while (Date.now() - start < timeout) { const result = await cdpCall("Runtime.evaluate", { expression:"!!document.querySelector(" + JSON.stringify(selector) + ")", returnByValue:true }, Math.min(timeout, 5000)); if (result.result?.value) return { ok:true, action:"chromeWaitForSelector", selector, found:true, durationMs:Date.now() - start, target:targetOptions(payload) }; await wait(250); } return { ok:false, action:"chromeWaitForSelector", selector, found:false, timeout, target:targetOptions(payload), logs:readCompactLogs(payload) }; }
async function chromeClick(payload = {}) { return await evalElementAction("chromeClick", payload, `el.scrollIntoView({block:"center",inline:"center"}); el.click(); return {ok:true,text:el.innerText||el.value||el.getAttribute("aria-label")||""};`); }
async function chromeType(payload = {}) { const text = payload.text || ""; return await evalElementAction("chromeType", payload, `el.focus(); el.value=${JSON.stringify(text)}; el.dispatchEvent(new Event("input",{bubbles:true})); el.dispatchEvent(new Event("change",{bubbles:true})); return {ok:true,value:el.value};`, { textLength:text.length }); }
async function evalElementAction(action, payload, body, extra = {}) { const { blocked, port } = chromeConfig(payload, action); if (blocked) return blocked; await ensurePage(port, targetOptions(payload)); const selector = payload.selector; if (!selector) return { ok:false, action, error:"missing_selector" }; const expression = `(() => { const el=document.querySelector(${JSON.stringify(selector)}); if(!el) return {ok:false,error:"not_found"}; ${body} })()`; const result = await cdpCall("Runtime.evaluate", { expression, awaitPromise:true, returnByValue:true }, timeoutOf(payload)); return { ok:true, action, selector, target:targetOptions(payload), ...extra, result:compactRemoteResult(result, Number(payload.maxValueChars || 8000)), logs:readCompactLogs(payload) }; }
async function chromeLogs(payload = {}) { return { ok:true, action:"chromeLogs", ...readCompactLogs({ ...payload, maxLogs:payload.maxLogs ?? 40 }) }; }
async function chromeSnapshot(payload = {}) { const { blocked, port } = chromeConfig(payload, "chromeSnapshot"); if (blocked) return blocked; await ensurePage(port, targetOptions(payload)); return { ok:true, action:"chromeSnapshot", target:targetOptions(payload), ...(await pageSnapshot({ ...payload, maxText:Math.min(Number(payload.maxText || 3000), 8000), maxLogs:40 })) }; }
async function chromeScreenshot(payload = {}) { const { blocked, port } = chromeConfig(payload, "chromeScreenshot"); if (blocked) return blocked; await ensurePage(port, targetOptions(payload)); const format = payload.format === "png" ? "png" : "jpeg", quality = format === "jpeg" ? Math.max(1, Math.min(Number(payload.quality || 70), 100)) : undefined; const params = { format, fromSurface:payload.fromSurface !== false, captureBeyondViewport:payload.captureBeyondViewport === true }; if (quality) params.quality = quality; const result = await cdpCall("Page.captureScreenshot", params, timeoutOf(payload, 20000)); const data = result.data || ""; return { ok:true, action:"chromeScreenshot", target:targetOptions(payload), contentType:"image/" + format, format, bytes:data.length, frame64:data, logs:readCompactLogs(payload) }; }
async function chromeRunScript(payload = {}) { const steps = Array.isArray(payload.script) ? payload.script : [], results = []; const dispatch = { goto:s => chromeNavigate({ ...payload, url:s.url, timeoutMs:s.timeoutMs || payload.timeoutMs }), navigate:s => chromeNavigate({ ...payload, url:s.url, timeoutMs:s.timeoutMs || payload.timeoutMs }), waitForSelector:s => chromeWaitForSelector({ ...payload, selector:s.selector, timeoutMs:s.timeoutMs || payload.timeoutMs }), click:s => chromeClick({ ...payload, selector:s.selector }), type:s => chromeType({ ...payload, selector:s.selector, text:s.text || "" }), eval:s => chromeEval({ ...payload, expression:s.expression || "document.title" }), logs:s => chromeLogs({ ...payload, ...s }), snapshot:s => chromeSnapshot({ ...payload, ...s }), screenshot:s => chromeScreenshot({ ...payload, ...s }) }; for (const step of steps) results.push(dispatch[step.type || step.action] ? await dispatch[step.type || step.action](step) : { ok:false, error:"unknown_step", stepType:step.type || step.action }); return { ok:results.every(x => x.ok !== false), action:"chromeRunScript", count:steps.length, results:results.slice(0, Number(payload.maxStepResults || 25)), logs:readCompactLogs(payload) }; }
function targetOptions(payload = {}) { return { pageId:payload.pageId || payload.chromeTargetId || payload.targetId || '', chromeTargetId:payload.chromeTargetId || payload.pageId || payload.targetId || '', browserSessionId:payload.browserSessionId || '', roomId:payload.roomId || '', missionId:payload.missionId || '', agentSessionId:payload.agentSessionId || '', logicalAgentId:payload.logicalAgentId || '', shared:payload.shared === true, inspectShared:payload.inspectShared === true, force:payload.force === true }; }
function targetView(target = {}) { const lease = targetLease(target.id); return { id:target.id, chromeTargetId:target.id, title:String(target.title || '').slice(0, 120), url:String(target.url || '').slice(0, 300), type:target.type, attached:Boolean(target.webSocketDebuggerUrl), lease }; }
function leaseMatches(lease = {}, payload = {}) { const options = targetOptions(payload); return [lease.browserSessionId, lease.roomId, lease.missionId, lease.agentSessionId, lease.logicalAgentId].every((value, index) => !value || value === [options.browserSessionId, options.roomId, options.missionId, options.agentSessionId, options.logicalAgentId][index]); }
async function navigationDiagnostics(port, payload, navigation) { let targets = []; try { targets = (await pages(port)).map(targetView); } catch (_) {} return { navigation, currentTargets:targets.slice(0, 20), logs:readCompactLogs({ ...payload, maxLogs:80 }), suggestedNextAction:{ action:'chromeDoctor', port, url:payload.url || '', chromeTargetId:payload.chromeTargetId || payload.pageId || '' } }; }
module.exports = { chromeFind, chromeLaunch, chromeStatus, chromeTargets, chromeNewPage, chromeClosePage, chromeTargetSelector:chromeTargets, chromeNavigate, chromeEval, chromeWaitForSelector, chromeClick, chromeType, chromeLogs, chromeSnapshot, chromeScreenshot, chromeRunScript, targetOptions, targetView, leaseMatches };
