// B"H
/**
 * @file style.js
 * @description
 * Chapter 51: The bag is calm. The Awtsmoos removes white focus flashes,
 * keeps the grid compact, and lets the peruta stack sit beside clothing.
 */
const css = String.raw`
#inventoryScreen.awtsmoosInventoryViewer{position:fixed!important;left:20px!important;right:auto!important;top:94px!important;bottom:92px!important;width:min(760px,calc(100vw - 40px))!important;height:auto!important;z-index:26000!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;pointer-events:auto!important;touch-action:none!important;color:#fff3c4!important;font-family:Arial,sans-serif!important;background:linear-gradient(150deg,rgba(25,22,16,.97),rgba(5,8,7,.985))!important;border:1px solid rgba(255,211,101,.72)!important;border-radius:18px!important;box-shadow:0 18px 52px rgba(0,0,0,.68),inset 0 1px 0 rgba(255,255,255,.11)!important;transform:none!important}
#inventoryScreen.hidden{display:none!important}#inventoryScreen *{box-sizing:border-box!important;touch-action:manipulation!important;-webkit-tap-highlight-color:transparent!important;outline:none!important}#inventoryScreen button:focus,#inventoryScreen button:active{outline:none!important;background:inherit!important}
#inventoryScreen::before{content:""!important;position:absolute!important;top:0!important;left:0!important;right:0!important;height:3px!important;background:linear-gradient(90deg,transparent,#e9ba41,transparent)!important;z-index:4!important}
#inventoryScreen .header{height:58px!important;flex:0 0 58px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:10px!important;padding:10px 12px 9px 17px!important;border-bottom:1px solid rgba(255,205,87,.22)!important;background:rgba(0,0,0,.25)!important}
#inventoryScreen .text{font-weight:900!important;letter-spacing:.06em!important;color:#ffd76b!important;font-size:22px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;text-shadow:0 2px 8px #000!important}#inventoryScreen button{pointer-events:auto!important;color:#ffe9a8!important;font-weight:900!important;font-family:Arial,sans-serif!important}#inventoryScreen .close{width:38px!important;height:38px!important;min-width:38px!important;border-radius:11px!important;background:rgba(255,204,73,.12)!important;border:1px solid rgba(255,214,102,.44)!important;font-size:25px!important;line-height:1!important}
#inventoryScreen .inventory-body{flex:1 1 auto!important;min-height:0!important;display:grid!important;grid-template-rows:48px minmax(0,1fr) 72px!important;gap:9px!important;padding:10px 11px 11px!important;overflow:hidden!important}#inventoryScreen .wardrobe-tabs{display:grid!important;grid-template-columns:repeat(6,minmax(0,1fr))!important;grid-auto-rows:44px!important;gap:6px!important;overflow:hidden!important;padding:0!important}#inventoryScreen .wardrobe-tab{height:44px!important;border:1px solid rgba(255,213,91,.35)!important;border-radius:11px!important;background:rgba(255,255,255,.045)!important;color:#ffe9a8!important;font-size:10px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:5px!important;padding:4px!important;min-width:0!important}#inventoryScreen .wardrobe-tab.active{background:linear-gradient(180deg,#e5b944,#98651a)!important;color:#140d02!important;box-shadow:inset 0 1px rgba(255,255,255,.35)!important}#inventoryScreen .wardrobe-tab .ico{font-size:16px!important;line-height:1!important}
#inventoryScreen .main-slots-holder{min-height:0!important;overflow:auto!important;-webkit-overflow-scrolling:touch!important;padding:5px!important;border:1px solid rgba(255,255,255,.05)!important;border-radius:13px!important;background:rgba(0,0,0,.2)!important;scrollbar-color:#ba8a2c transparent!important}#inventoryScreen .slots{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:7px!important;padding:0!important;margin:0!important;align-content:start!important}#inventoryScreen .inv-card{height:78px!important;min-height:78px!important;border:1px solid rgba(196,145,38,.58)!important;border-radius:12px!important;background:linear-gradient(145deg,rgba(56,48,30,.72),rgba(4,6,5,.84))!important;display:flex!important;align-items:center!important;justify-content:center!important;position:relative!important;overflow:hidden!important;pointer-events:auto!important;padding:0!important;transition:transform .12s,border-color .12s!important}#inventoryScreen .inv-card:hover{transform:translateY(-2px)!important;border-color:#efc95f!important}#inventoryScreen .inv-card.locked{border-color:#d7b14b!important;background:linear-gradient(145deg,rgba(88,64,20,.7),rgba(5,6,4,.86))!important}#inventoryScreen .inv-card.selected{border-color:#76ff8a!important;box-shadow:0 0 0 2px rgba(118,255,138,.16),0 0 14px rgba(118,255,138,.2)!important}#inventoryScreen .slotBtn{font-size:29px!important;line-height:1!important}#inventoryScreen .slotName{position:absolute!important;left:4px!important;right:4px!important;bottom:4px!important;text-align:center!important;font-size:10px!important;text-shadow:0 1px 4px #000!important;background:rgba(0,0,0,.64)!important;border-radius:7px!important;padding:3px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}#inventoryScreen .equippedMark{position:absolute!important;right:5px!important;top:5px!important;width:21px!important;height:21px!important;border-radius:50%!important;display:flex!important;align-items:center!important;justify-content:center!important;background:#58b957!important;color:#fff!important;font-weight:900!important;font-size:12px!important}
#inventoryScreen .empty-inventory-note{grid-column:1/-1!important;text-align:center!important;color:#ffe9a8!important;font-size:15px!important;padding:26px 8px!important;opacity:.9!important}#inventoryScreen .wardrobe-footer{display:grid!important;grid-template-columns:minmax(0,1fr) 210px!important;grid-template-rows:56px!important;gap:8px!important;min-height:0!important;align-items:center!important}#inventoryScreen .selected-label{text-align:left!important;padding:0 12px!important;color:#ffe9a8!important;font-size:14px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}#inventoryScreen .equip-main-btn{height:52px!important;border-radius:13px!important;background:linear-gradient(180deg,#efbd43,#9a6718)!important;color:#1a1000!important;font-size:18px!important;width:100%!important;border:0!important;box-shadow:inset 0 1px rgba(255,255,255,.4)!important}
@media(max-width:760px){#inventoryScreen.awtsmoosInventoryViewer{left:7px!important;right:7px!important;top:66px!important;bottom:calc(72px + env(safe-area-inset-bottom))!important;width:auto!important;border-radius:17px!important}#inventoryScreen .header{height:50px!important;flex-basis:50px!important;padding:7px 9px 6px 13px!important}#inventoryScreen .text{font-size:18px!important}#inventoryScreen .close{width:35px!important;height:35px!important;min-width:35px!important}#inventoryScreen .inventory-body{grid-template-rows:94px minmax(0,1fr) 66px!important;padding:7px!important;gap:7px!important}#inventoryScreen .wardrobe-tabs{grid-template-columns:repeat(3,minmax(0,1fr))!important;grid-auto-rows:43px!important;gap:5px!important}#inventoryScreen .wardrobe-tab{height:43px!important}#inventoryScreen .slots{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:6px!important}#inventoryScreen .inv-card{height:70px!important;min-height:70px!important}#inventoryScreen .wardrobe-footer{grid-template-columns:minmax(0,1fr) 132px!important;grid-template-rows:58px!important}#inventoryScreen .selected-label{font-size:12px!important;padding:0 5px!important}#inventoryScreen .equip-main-btn{height:50px!important;font-size:16px!important}}
@media(max-height:620px){#inventoryScreen.awtsmoosInventoryViewer{top:58px!important;bottom:66px!important}#inventoryScreen .inventory-body{grid-template-rows:44px minmax(0,1fr) 54px!important}#inventoryScreen .wardrobe-tabs{display:flex!important;overflow-x:auto!important}.wardrobe-tab{min-width:94px!important}.inv-card{height:58px!important;min-height:58px!important}}
`;
export default { tag: "style", innerHTML: css };
