// B"H
/**
 * @file style.js
 * @description
 * Chapter 51: The bag is calm. The Awtsmoos removes white focus flashes,
 * keeps the grid compact, and lets the peruta stack sit beside clothing.
 */
const css = String.raw`
#inventoryScreen.awtsmoosInventoryViewer{position:fixed!important;left:12px!important;right:12px!important;top:14px!important;bottom:calc(92px + env(safe-area-inset-bottom))!important;width:auto!important;height:auto!important;z-index:26000!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;pointer-events:auto!important;touch-action:none!important;color:#fff3c4!important;font-family:Arial,sans-serif!important;background:linear-gradient(180deg,rgba(23,17,8,.98),rgba(2,3,1,.995))!important;border:2px solid rgba(255,206,82,.95)!important;border-radius:22px!important;box-shadow:0 0 30px rgba(0,0,0,.74),inset 0 0 18px rgba(255,198,62,.08)!important;transform:none!important}
#inventoryScreen.hidden{display:none!important}#inventoryScreen *{box-sizing:border-box!important;touch-action:manipulation!important;-webkit-tap-highlight-color:transparent!important;outline:none!important}#inventoryScreen button:focus,#inventoryScreen button:active{outline:none!important;background:inherit!important}
#inventoryScreen::before{content:""!important;position:absolute!important;top:8px!important;left:50%!important;transform:translateX(-50%)!important;width:68px!important;height:7px!important;border-radius:999px!important;background:#d6a94a!important;z-index:4!important}
#inventoryScreen .header{height:66px!important;flex:0 0 66px!important;display:flex!important;align-items:end!important;justify-content:space-between!important;gap:10px!important;padding:18px 14px 8px!important;border-bottom:1px solid rgba(255,205,87,.28)!important;background:rgba(0,0,0,.28)!important}
#inventoryScreen .text{font-weight:900!important;letter-spacing:.045em!important;color:#ffd25c!important;font-size:clamp(19px,5.6vw,27px)!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;text-shadow:0 2px 8px #000!important}#inventoryScreen button{pointer-events:auto!important;color:#ffe9a8!important;font-weight:900!important;font-family:Arial,sans-serif!important}#inventoryScreen .close{width:48px!important;height:48px!important;min-width:48px!important;border-radius:16px!important;background:rgba(255,204,73,.18)!important;border:1px solid rgba(255,214,102,.55)!important;font-size:32px!important;line-height:1!important}
#inventoryScreen .inventory-body{flex:1 1 auto!important;min-height:0!important;display:grid!important;grid-template-rows:116px minmax(0,1fr) 92px!important;gap:10px!important;padding:10px 12px 14px!important;overflow:hidden!important}#inventoryScreen .wardrobe-tabs{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;grid-auto-rows:52px!important;gap:8px!important;overflow:hidden!important;padding:0!important}#inventoryScreen .wardrobe-tab{height:52px!important;border:1px solid rgba(255,213,91,.48)!important;border-radius:15px!important;background:rgba(255,255,255,.06)!important;color:#ffe9a8!important;font-size:11px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:7px!important;padding:4px!important;min-width:0!important}#inventoryScreen .wardrobe-tab.active{background:linear-gradient(180deg,#e9ba41,#9d6816)!important;color:#140d02!important;box-shadow:0 5px 0 rgba(255,224,113,.55)!important}#inventoryScreen .wardrobe-tab .ico{font-size:20px!important;line-height:1!important}
#inventoryScreen .main-slots-holder{min-height:0!important;overflow:auto!important;-webkit-overflow-scrolling:touch!important;padding:2px 2px 6px!important;border-radius:16px!important;background:rgba(255,255,255,.025)!important}#inventoryScreen .slots{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:9px!important;padding:0!important;margin:0!important;align-content:start!important}#inventoryScreen .inv-card{height:86px!important;min-height:86px!important;border:2px solid rgba(196,145,38,.62)!important;border-radius:17px!important;background:radial-gradient(circle at 50% 18%,rgba(255,255,255,.14),rgba(0,0,0,.46))!important;display:flex!important;align-items:center!important;justify-content:center!important;position:relative!important;overflow:hidden!important;pointer-events:auto!important;padding:0!important}#inventoryScreen .inv-card.locked{border-color:#d7b14b!important;background:radial-gradient(circle at 50% 18%,rgba(255,215,75,.2),rgba(0,0,0,.52))!important}#inventoryScreen .inv-card.selected{border-color:#76ff8a!important;box-shadow:0 0 0 3px rgba(118,255,138,.2),0 0 18px rgba(118,255,138,.3)!important}#inventoryScreen .slotBtn{font-size:32px!important;line-height:1!important}#inventoryScreen .slotName{position:absolute!important;left:5px!important;right:5px!important;bottom:5px!important;text-align:center!important;font-size:11px!important;text-shadow:0 1px 4px #000!important;background:rgba(0,0,0,.55)!important;border-radius:8px!important;padding:2px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}#inventoryScreen .equippedMark{position:absolute!important;right:5px!important;top:5px!important;width:25px!important;height:25px!important;border-radius:50%!important;display:flex!important;align-items:center!important;justify-content:center!important;background:#58b957!important;color:#fff!important;font-weight:900!important}
#inventoryScreen .empty-inventory-note{grid-column:1/-1!important;text-align:center!important;color:#ffe9a8!important;font-size:16px!important;padding:26px 8px!important;opacity:.9!important}#inventoryScreen .wardrobe-footer{display:grid!important;grid-template-columns:1fr!important;grid-template-rows:24px 58px!important;gap:8px!important;min-height:0!important}#inventoryScreen .selected-label{text-align:center!important;color:#ffe9a8!important;font-size:15px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}#inventoryScreen .equip-main-btn{height:58px!important;border-radius:18px!important;background:linear-gradient(180deg,#efbd43,#9a6718)!important;color:#1a1000!important;font-size:22px!important;width:100%!important;border:0!important;box-shadow:0 5px 0 rgba(93,55,0,.9)!important}
@media (max-height:700px){#inventoryScreen{top:8px!important;bottom:calc(74px + env(safe-area-inset-bottom))!important;left:8px!important;right:8px!important}#inventoryScreen .header{height:54px!important;flex-basis:54px!important;padding:12px 12px 7px!important}#inventoryScreen .inventory-body{grid-template-rows:96px minmax(0,1fr) 74px!important;gap:7px!important;padding:8px!important}#inventoryScreen .wardrobe-tabs{grid-auto-rows:44px!important;gap:6px!important}#inventoryScreen .wardrobe-tab{height:44px!important;font-size:10px!important}#inventoryScreen .inv-card{height:64px!important;min-height:64px!important}#inventoryScreen .slotBtn{font-size:25px!important}#inventoryScreen .equip-main-btn{height:48px!important;font-size:19px!important}}
`;
export default { tag: "style", innerHTML: css };
