// B'H
import { SEFIROT, addBurst, addText } from './state.js';
import { createLevel, updateLevelStream, WORLDS } from './level.js';
import { saveGame } from './save.js';
import { spiralToward, suctionStep } from './engine/physics.js';
import { clamp, heightAt, len, mix, norm } from './math.js';
export function step(w,dt){if(w.mode!=='playing')return camera(w,dt);move(w,dt);updateLevelStream(w.level,w.player.x,w.player.y);absorb(w,dt);animate(w,dt);upgrades(w);camera(w,dt);w.timeLeft-=dt;if(w.score>=w.level.target)win(w);if(w.timeLeft<=0&&!w.won)lose(w)}
export function start(w){w.mode='playing';w.message='Streaming chunks awaken around the portal.';w.events.push(['start'])}
export function restart(){location.reload()}
export function nextWorld(w){w.save.completed=[...new Set([...w.save.completed,w.level.name])];saveGame(w.save);w.level=createLevel(w.save,w.level.worldIndex+1);Object.assign(w,{mode:'playing',score:0,timeLeft:w.level.time,won:false,lost:false,sefirah:0,absorbers:[],particles:[],floaters:[],message:'Entered '+w.level.name+' via '+w.level.engine})}
function move(w,dt){const p=w.player,v=norm(w.input),mag=clamp(len(w.input.x,w.input.y),0,1),surge=w.sefirah>=4&&w.input.pulse>0?1.45:1;p.x+=v.x*p.speed*mag*surge*dt;p.y+=v.y*p.speed*mag*surge*dt;p.x=clamp(p.x,-w.level.bounds,w.level.bounds);p.y=clamp(p.y,-w.level.bounds,w.level.bounds);p.z=heightAt(p.x,p.y,w.level.worldIndex);w.input.pulse=Math.max(0,w.input.pulse-dt);p.glow=Math.max(0,p.glow-dt*1.3);p.comboT=Math.max(0,p.comboT-dt);if(!p.comboT)p.combo=mix(p.combo,1,dt*2)}
function absorb(w,dt){const p=w.player,gev=w.sefirah>=2?1.18:.98,power=w.sefirah>=1?1.7:.4;for(const o of w.level.objects){if(o.taken)continue;const can=o.r<p.r*gev;if(w.input.pulse>0&&can)suctionStep(o,p,dt,w.level.worldIndex,power);if(can&&Math.hypot(p.x-o.x,p.y-o.y)<p.r*.85)reveal(w,o)}}
function reveal(w,o){o.taken=true;w.absorbers.push({...o,life:.65,ox:o.x,oy:o.y});const p=w.player;p.combo=w.sefirah>=3?Math.min(5,p.combo+.16):1;p.comboT=3;const gain=Math.round(o.sparks*p.combo);w.score+=gain;p.r+=Math.sqrt(o.sparks)*.22;p.h=p.r*1.5;p.speed=Math.max(135,p.speed-o.sparks*.006);p.glow=1;w.camera.shake=.35;addText(w,o.x,o.y,o.z+o.h,'+'+gain+' x'+p.combo.toFixed(1));w.message=o.hood+': '+o.name+' +'+gain+' · chunks '+w.level.streamer.active.length;w.events.push(['reveal',o.sparks])}
function animate(w,dt){w.absorbers=w.absorbers.filter(a=>{const alive=spiralToward(a,w.player,dt);if(!alive)addBurst(w,a);return alive});w.particles=w.particles.filter(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.z+=q.vz*dt;q.vz-=260*dt;q.life-=dt;return q.life>0&&q.z>0});w.floaters=w.floaters.filter(f=>{f.z+=50*dt;f.life-=dt;return f.life>0})}
function upgrades(w){const n=Math.min(SEFIROT.length-1,Math.floor(w.score/1000));if(n>w.sefirah){w.sefirah=n;w.message='Sefirah: '+SEFIROT[n][0]+' — '+SEFIROT[n][1];w.events.push(['upgrade'])}}
function camera(w,dt){const c=w.camera,p=w.player;if(w.won)c.victory+=dt;const drift=w.won?c.victory*.55:Math.atan2(w.input.x,-w.input.y||.001)*.22;c.angle=mix(c.angle,drift,dt*2.2);c.distance=mix(c.distance,clamp(380+p.r*4.4,430,980),dt*1.8);c.x=mix(c.x,p.x-Math.sin(c.angle)*c.distance,dt*3.4);c.y=mix(c.y,p.y-Math.cos(c.angle)*c.distance,dt*3.4);c.z=mix(c.z,230+p.r*3.2+p.z+(w.input.pulse>0?-70:0),dt*2);c.shake=Math.max(0,c.shake-dt)}
function win(w){w.won=true;w.mode='won';w.save.best=Math.max(w.save.best,w.score);w.save.completed=[...new Set([...w.save.completed,w.level.name])];saveGame(w.save);w.message=w.level.name+' revealed. Next: '+WORLDS[(w.level.worldIndex+1)%WORLDS.length][0];w.events.push(['win'])}
function lose(w){w.lost=true;w.mode='lost';w.save.best=Math.max(w.save.best,w.score);saveGame(w.save);w.message='Concealment returned. Best saved: '+w.save.best;w.events.push(['lose'])}
