// B'H
const VS=`attribute vec3 aPos;attribute vec3 aNormal;uniform mat4 uVP;uniform vec3 uPos,uScale;uniform float uRot;varying float vLight;void main(){float c=cos(uRot),s=sin(uRot);vec3 p=vec3(aPos.x*uScale.x,aPos.y*uScale.y,aPos.z*uScale.z);p=vec3(p.x*c-p.z*s,p.y,p.x*s+p.z*c)+uPos;vec3 n=normalize(vec3(aNormal.x*c-aNormal.z*s,aNormal.y,aNormal.x*s+aNormal.z*c));vLight=.42+max(dot(n,normalize(vec3(-.35,.82,.45))),0.)*.62;gl_Position=uVP*vec4(p,1.);}`;
const FS=`precision mediump float;uniform vec3 uColor;uniform float uAlpha,uGlow;varying float vLight;void main(){gl_FragColor=vec4(uColor*(vLight+uGlow*.55),uAlpha);}`;
export function createGL(canvas){const gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)throw Error('WebGL unavailable');const program=prog(gl,VS,FS);const api={gl,program,meshes:meshes(gl),loc:locs(gl,program)};gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);return api}
export function bindMesh(r,m){const gl=r.gl,l=r.loc;gl.bindBuffer(gl.ARRAY_BUFFER,m.buffer);gl.enableVertexAttribArray(l.aPos);gl.vertexAttribPointer(l.aPos,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(l.aNormal);gl.vertexAttribPointer(l.aNormal,3,gl.FLOAT,false,24,12)}
function locs(gl,p){return{aPos:gl.getAttribLocation(p,'aPos'),aNormal:gl.getAttribLocation(p,'aNormal'),uVP:gl.getUniformLocation(p,'uVP'),uPos:gl.getUniformLocation(p,'uPos'),uScale:gl.getUniformLocation(p,'uScale'),uRot:gl.getUniformLocation(p,'uRot'),uColor:gl.getUniformLocation(p,'uColor'),uAlpha:gl.getUniformLocation(p,'uAlpha'),uGlow:gl.getUniformLocation(p,'uGlow')}}
function meshes(gl){return{cube:up(gl,cube()),disc:up(gl,disc(64)),plane:up(gl,plane()),sphere:up(gl,sphere(10,16)),ring:up(gl,ring(40)),cylinder:up(gl,cylinder(28)),star:up(gl,star(5)),letter:up(gl,letter()),arch:up(gl,arch())}}
function up(gl,d){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(d),gl.STATIC_DRAW);return{buffer:b,count:d.length/6}}
function tri(a,b,c,n){return[...a,...n,...b,...n,...c,...n]}function face(a,b,c,d,n){return[...tri(a,b,c,n),...tri(a,c,d,n)]}
function cube(){const p=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]];return[...face(p[0],p[1],p[2],p[3],[0,0,-1]),...face(p[5],p[4],p[7],p[6],[0,0,1]),...face(p[4],p[0],p[3],p[7],[-1,0,0]),...face(p[1],p[5],p[6],p[2],[1,0,0]),...face(p[3],p[2],p[6],p[7],[0,1,0]),...face(p[4],p[5],p[1],p[0],[0,-1,0])]}
function disc(n){let a=[];for(let i=0;i<n;i++){let A=i/n*Math.PI*2,B=(i+1)/n*Math.PI*2;a.push(...tri([0,0,0],[Math.cos(A),0,Math.sin(A)],[Math.cos(B),0,Math.sin(B)],[0,1,0]))}return a}
function plane(){return face([-1,0,-1],[1,0,-1],[1,0,1],[-1,0,1],[0,1,0])}
function sphere(R,C){let a=[];for(let y=0;y<R;y++)for(let x=0;x<C;x++){let A=pt(y/R,x/C),B=pt((y+1)/R,x/C),C1=pt((y+1)/R,(x+1)/C),D=pt(y/R,(x+1)/C);a.push(...tri(A,B,C1,A),...tri(A,C1,D,A))}return a}
function pt(v,u){let th=u*Math.PI*2,ph=v*Math.PI;return[Math.sin(ph)*Math.cos(th),Math.cos(ph),Math.sin(ph)*Math.sin(th)]}
function ring(n){let a=[];for(let i=0;i<n;i++){let A=i/n*Math.PI*2,B=(i+1)/n*Math.PI*2,p=t=>[Math.cos(t),0,Math.sin(t)],q=t=>[Math.cos(t)*.68,0,Math.sin(t)*.68];a.push(...tri(p(A),p(B),q(B),[0,1,0]),...tri(p(A),q(B),q(A),[0,1,0]))}return a}
function cylinder(n){let a=[];for(let i=0;i<n;i++){let A=i/n*Math.PI*2,B=(i+1)/n*Math.PI*2,p=t=>[Math.cos(t),-1,Math.sin(t)],q=t=>[Math.cos(t),1,Math.sin(t)],N=[Math.cos((A+B)/2),0,Math.sin((A+B)/2)];a.push(...face(p(A),p(B),q(B),q(A),N),...tri([0,1,0],q(A),q(B),[0,1,0]),...tri([0,-1,0],p(B),p(A),[0,-1,0]))}return a}
function star(n){let a=[];for(let i=0;i<n*2;i++){let A=i/(n*2)*Math.PI*2,B=(i+1)/(n*2)*Math.PI*2,ra=i%2?0.45:1,rb=(i+1)%2?0.45:1;a.push(...tri([0,1.2,0],[Math.cos(A)*ra,0,Math.sin(A)*ra],[Math.cos(B)*rb,0,Math.sin(B)*rb],[0,1,0]))}return a}
function letter(){return[...cube().map((v,i)=>i%6<3?v*.5:v),...face([-.2,-1,0],[.2,-1,0],[.2,1,0],[-.2,1,0],[0,0,1])]}
function arch(){return[...cube(),...ring(32)]}
function prog(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,sh(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,sh(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}
function sh(gl,t,s){const h=gl.createShader(t);gl.shaderSource(h,s);gl.compileShader(h);if(!gl.getShaderParameter(h,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(h));return h}
