// B"H
/** @file KosherProcessingRuntime.js @description Educational kosher processing with knife, facing, meat, leather, and profession XP. */
import { addBagItem } from "../inventory/BagRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { hasEquipped } from "../equipment/EquipmentRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { animalKosherData } from "./KosherAnimalIndex.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { nearestCarcass, openCarcassUi } from "./CarcassRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { grantProfessionXp } from "../professions/ProfessionRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
function playerOf(olam) { return olam?.player || olam?.chossid || null; }
function posOf(x) { return x?.mesh?.position || x?.position || { x:0, z:0 }; }
function yawOf(player) { return Number.isFinite(player?.__awtsmoosUnifiedFacingYaw) ? player.__awtsmoosUnifiedFacingYaw : Number(player?.mesh?.rotation?.y || 0); }
function facingDot(player, carcass) { const pp = posOf(player); const yaw = yawOf(player); const forward = { x:Math.sin(yaw + Math.PI), z:Math.cos(yaw + Math.PI) }; const dx = (carcass.x || 0) - (pp.x || 0); const dz = (carcass.z || 0) - (pp.z || 0); const len = Math.max(.001, Math.hypot(dx, dz)); return (forward.x * dx + forward.z * dz) / len; }
function distance(player, carcass) { const pp = posOf(player); return Math.hypot((pp.x || 0) - (carcass?.x || 0), (pp.z || 0) - (carcass?.z || 0)); }
function normalizeSelection(selection = "basar_shechuta") { const s = String(selection || "").toLowerCase().replace(/\s+/g, "_"); if (["meat", "basar", "basar_schura", "basar_shechuta", "basar_shechuta_meat"].includes(s)) return "basar_shechuta"; if (["skin", "hide", "leather"].includes(s)) return "leather"; if (["fur", "fur_scrap"].includes(s)) return "fur"; return s; }
function baseItem(baseId) { const map = { basar_shechuta:{ name:"Basar Shechuta", category:"Food", kosherMeat:true }, non_kosher_meat:{ name:"Non-Kosher Meat", category:"Food", kosherMeat:false }, cow_hide:{ name:"Cow Hide", category:"Materials" }, kosher_cow_leather:{ name:"Kosher Cow Leather", category:"Materials", kosherLeather:true, tefillinReady:true }, fur_scrap:{ name:"Fur Scrap", category:"Materials" } }; return map[baseId] || { name:baseId, category:"Materials" }; }
function item(baseId, carcassId, i) { return { id:`${baseId}_${carcassId}_${i}`, baseId, ...baseItem(baseId) }; }
function grantMany(olam, carcass, yields = {}) { const out = []; for (const [baseId, count] of Object.entries(yields)) for (let i = 0; i < Number(count || 1); i++) out.push(addBagItem(olam, item(baseId, carcass.id, i))); return out.filter(Boolean); }
export function canKosherProcess(olam, carcass) { const data = animalKosherData(carcass?.species), player = playerOf(olam); if (!carcass) return { ok:false, reason:"no-carcass" }; if (carcass.processed) return { ok:false, reason:"already-processed" }; if (!player) return { ok:false, reason:"no-player" }; if (distance(player, carcass) > 5.5) return { ok:false, reason:"too-far-from-carcass" }; if (facingDot(player, carcass) < .2) return { ok:false, reason:"face-carcass-first" }; if (!data.kosherSpecies) return { ok:false, reason:"not-kosher-species" }; if (data.requiresShechitaKnife && !hasEquipped(olam, "shechita_knife", "tool")) return { ok:false, reason:"requires-equipped-shechita-knife" }; return { ok:true, data }; }
export function processNearestCarcass(olam, selection = "basar_shechuta") { const hit = nearestCarcass(olam); if (!hit) return { ok:false, reason:"no-nearby-carcass" }; return processCarcass(olam, hit.carcass, selection); }
export function processCarcass(olam, carcass, selection = "basar_shechuta") { const normalized = normalizeSelection(selection), check = canKosherProcess(olam, carcass), data = animalKosherData(carcass?.species); if (!check.ok) { olam?.ayshPeula?.("ui event", "carcassPanel", { open:true, carcass, blocked:true, reason:check.reason }); return { ok:false, reason:check.reason, carcass }; } const yields = normalized === "basar_shechuta" ? data.yields : normalized === "leather" ? { kosher_cow_leather:data.yields.kosher_cow_leather || 0, cow_hide:data.yields.cow_hide || 1 } : normalized === "fur" ? { fur_scrap:data.yields.fur_scrap || 1 } : data.yields; const granted = grantMany(olam, carcass, yields); grantProfessionXp(olam, normalized === "leather" ? "sofer" : "cooking", 12 + granted.length * 3); carcass.processed = true; carcass.selections.push(normalized); carcass.outputs = granted.map(i => i.id); carcass.kosherProcessed = true; openCarcassUi(olam, carcass); olam?.ayshPeula?.("ui event", "effectsOverlay", { text:"Kosher processing complete", color:"#d7c8ff" }); return { ok:true, carcass, granted, selection:normalized }; }
export { normalizeSelection, facingDot };
export default { canKosherProcess, processNearestCarcass, processCarcass, normalizeSelection, facingDot };
