// B"H
/**
 * @file PlacementManager.js
 * @description
 * Chapter 1009: placement no longer spawns old tree classes.
 * Build mode still places blocks/furniture/wood; tree items are redirected to
 * the current geelooy/libs hero tree vessel and never to legacy generators.
 */
import * as THREE from '/games/scripts/build/three.module.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1';
export default class PlacementManager {
  constructor(olam) { this.olam = olam; this.isActive = false; this.currentItem = null; this.ghostMesh = null; this.raycaster = new THREE.Raycaster(); this.mouse = new THREE.Vector2(0, 0); this._onClick = this.onClick.bind(this); }
  startPlacement(itemData) { if (!itemData) return; this.isActive = true; this.currentItem = itemData; const geo = new THREE.BoxGeometry(1, 1, 1), mat = new THREE.MeshBasicMaterial({ color: 0x00ff00, transparent: true, opacity: 0.5, wireframe: true }); if (itemData.type === 'furniture' || itemData.id?.includes('chair')) geo.scale(1.2, 2, 1.2); else if (itemData.type === 'tree' || itemData.id?.includes('tree')) geo.scale(2, 7, 2); this.ghostMesh = new THREE.Mesh(geo, mat); this.olam.scene.add(this.ghostMesh); this.rotationY = 0; this._onWheel = e => { if (!this.isActive || !this.ghostMesh) return; this.rotationY += Math.sign(e.deltaY) * (Math.PI / 4); this.ghostMesh.rotation.y = this.rotationY; }; document.addEventListener('mousedown', this._onClick); window.addEventListener('wheel', this._onWheel); this.olam.ayshPeula("ui event", "toast", { message: `Placing: ${itemData.name}. Click to anchor.` }); }
  stopPlacement() { this.isActive = false; this.currentItem = null; if (this.ghostMesh) { this.olam.scene.remove(this.ghostMesh); this.ghostMesh.geometry.dispose(); this.ghostMesh.material.dispose(); this.ghostMesh = null; } document.removeEventListener('mousedown', this._onClick); window.removeEventListener('wheel', this._onWheel); }
  update() { if (!this.isActive || !this.ghostMesh || !this.olam.camera) return; this.raycaster.setFromCamera(this.mouse, this.olam.camera); const solids = []; this.olam.scene.traverse(child => { if (child.isMesh && child.userData.isSolid && child !== this.ghostMesh && child.name !== 'cameraAnchor' && child.name !== 'characterModel') solids.push(child); }); const hit = this.raycaster.intersectObjects(solids, false)[0]; if (hit) { this.ghostMesh.position.copy(hit.point); this.ghostMesh.position.y += this.ghostMesh.scale.y / 2; this.ghostMesh.material.color.setHex(0x00ff00); } else { this.raycaster.ray.at(5, this.ghostMesh.position); this.ghostMesh.material.color.setHex(0xff0000); } }
  onClick(e) { if (e.button !== 0 || !this.isActive || !this.currentItem) return; if (this.ghostMesh.material.color.getHex() === 0xff0000) return void this.olam.ayshPeula("ui event", "toast", { message: "Cannot place here." }); const pos = this.ghostMesh.position.clone(); this.olam.chossid?.inventory?.removeItem?.(this.currentItem.id); this.spawnEntity(this.currentItem, pos); this.olam.ayshPeula("ui event", "toast", { message: `${this.currentItem.name} placed.` }); this.stopPlacement(); }
  spawnEntity(itemData, position) { let type = "SolidBlock"; const options = { position: { x: position.x, y: position.y, z: position.z }, rotation: { x: 0, y: this.rotationY || 0, z: 0 }, name: `${itemData.name}_placed_${Date.now()}` }; if (itemData.id?.includes("brick")) { options.width = 1; options.height = 1; options.depth = 1; options.color = itemData.id.includes("gold") ? 0xffd700 : 0xb22222; } else if (itemData.id?.includes("chair") || itemData.id?.includes("table") || itemData.id?.includes("couch")) { type = "ProceduralFurniture"; options.furnitureType = itemData.id.split('_')[0]; } else if (itemData.id?.includes("tree") || itemData.type === "tree") { type = "VillageHeroTree"; options.scale = 1; options.trunkHeight = 8.5; options.leafCount = 720; options.limbCount = 44; } else if (itemData.id?.includes("wood")) { options.width = 2; options.height = 0.2; options.depth = 4; options.color = 0x8b4513; } if (typeof this.olam.addObject === "function") this.olam.addObject(type, options); }
}
