// B"H
/**
 * GeminiAdapter - AI dialogue and world refinement.
 * World refinement now instructs only approved tree seeds, never removed tree archetypes.
 */
import ApiKeyManager from "./ApiKeyManager.js";
export default class GeminiAdapter {
  static async generateDialogue(entityId, systemInstruction, history, userMessage, levState) { const mood = levState ? (`[MOOD: Joy:${levState.simcha}, Anger:${levState.kaas}]`) : ""; const finalInstruction = systemInstruction + "\n" + mood + "\nYou are a soul in Mitzvah World. Keep responses short and conversational."; try { return await this.tryRequest({ contents: [...history, { role: "user", parts: [{ text: userMessage }] }], systemInstruction: { parts: [{ text: finalInstruction }] } }, { model: "gemini-2.5-flash-lite", temperature: 1, maxOutputTokens: 500 }); } catch (error) { console.error("B\"H\n - Dialogue generation failed:", error); return "..."; } }
  static async refineWorldExistence(worldState, customPrompt) { const systemInstructionText = `B"H\nYou are Bezalel, architect of Mitzvah World JSON. Output ONLY valid JSON: { "NivraType": [ { name, position, ... } ] }. Use archetypes: VillageHeroTree, Brick, CustomNpc, Coin, Portal, Mazik. Trees must use VillageHeroTree with treeSource /libs/awtsmoos3d/tree/heroTree.js. Prompt: ${customPrompt}`; try { const jsonText = await this.tryRequest({ contents: [{ role: "user", parts: [{ text: `CURRENT WORLD STATE: ${JSON.stringify(worldState)}\n\nREFINEMENT COMMAND: ${customPrompt}` }] }], systemInstruction: { parts: [{ text: systemInstructionText }] } }, { responseMimeType: "application/json", temperature: .2, thinkingBudget: 0 }); return JSON.parse(jsonText); } catch (e) { console.error("B\"H - The AI Forge encountered a veil:", e); return null; } }
  static async tryRequest(body, config) { if (!ApiKeyManager.hasKeys()) { this.requestUserKeys(); throw new Error("No Divine Keys found."); } let key = await ApiKeyManager.getActiveKey(), attempts = 0; while (attempts < 3) { try { return await getGeminiResponse(body, key, config); } catch (error) { if (error.message.includes("429")) { key = ApiKeyManager.rotateKey(); attempts++; } else throw error; } } this.requestUserKeys(); throw new Error("All Divine Keys exhausted or rate limited."); }
  static requestUserKeys() { if (typeof postMessage === 'function' && typeof window === 'undefined') postMessage({ sendUiEvent: { shaym: "apiKeyModal", ob: { open: true } } }); else if (typeof window !== 'undefined') document.getElementById("ikar")?.dispatchEvent(new CustomEvent("olamPeula", { detail: { sendUiEvent: { shaym: "apiKeyModal", ob: { open: true } } } })); }
}
async function getGeminiResponse(chatBody, apiKey, { temperature = .2, topP = .95, topK = 40, maxOutputTokens = 65536, model = "gemini-2.5-flash-lite", responseMimeType = "text/plain", thinkingBudget = 0 } = {}) { const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`; const generationConfig = { temperature, topP, topK, maxOutputTokens, responseMimeType }; if (thinkingBudget > 0) generationConfig.thinkingConfig = { includeThoughts: true }; const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...chatBody, generationConfig }) }); if (!response.ok) { if (response.status === 429) throw new Error("429"); throw new Error(`Gemini API Error ${response.status}: ${await response.text()}`); } const data = await response.json(); return data.candidates?.[0]?.content?.parts?.[0]?.text || ""; }
