// B"H
const fsp = require("fs/promises");
const path = require("path");
const { safePath, assertNotSecret } = require("./pathGuard.js");
const DEFAULT_SKIPS = ["node_modules", ".git", ".next", "dist", "build", ".cache", "coverage", ".turbo", ".parcel-cache", ".Awtsmoos", "command-jobs", ".awtsmoos-agent-thoughts"];
function int(value, fallback) { const n = Number(value); return Number.isFinite(n) && n >= 0 ? Math.floor(n) : fallback; }
function lowerSet(values = []) { return new Set(values.map(x => String(x).toLowerCase()).filter(Boolean)); }
function options(payload = {}) { return { query:String(payload.query || payload.find || "").toLowerCase(), ext:String(payload.ext || "").toLowerCase().replace(/^\*/, ""), includeDirs:payload.includeDirs === true || payload.includeDirs === "true", metadata:payload.metadata === true || payload.stat === true, maxVisited:int(payload.maxVisited || payload.maxEntries, 25000), skip:lowerSet([...DEFAULT_SKIPS, ...(Array.isArray(payload.skipDirs) ? payload.skipDirs : [])]) }; }
function matches(item, opt) { const name = item.name.toLowerCase(), rel = item.relativePath.toLowerCase(); if (opt.ext && !name.endsWith(opt.ext.startsWith(".") ? opt.ext : "." + opt.ext)) return false; if (opt.query && !name.includes(opt.query) && !rel.includes(opt.query)) return false; return true; }
async function findFiles(config, payload = {}) { const start = safePath(config, payload.path || payload.p || "."), opt = options(payload); const pageSize = Math.max(1, Math.min(int(payload.pageSize || payload.maxResults || payload.limit, 100), 1000)); const cursor = int(payload.cursor || payload.offset || 0, 0); const results = []; let visited = 0, matched = 0, skipped = 0, stoppedReason = "";
  async function push(item, full) { if (!matches(item, opt)) return; if (matched >= cursor && results.length < pageSize) results.push(opt.metadata ? await withStat(config, item, full) : item); matched++; }
  async function walk(dir) { if (visited >= opt.maxVisited || results.length >= pageSize) { stoppedReason = results.length >= pageSize ? "page_full" : "max_visited"; return; } let entries = []; try { entries = await fsp.readdir(dir, { withFileTypes:true }); } catch { skipped++; return; }
    for (const entry of entries) { if (visited >= opt.maxVisited || results.length >= pageSize) { stoppedReason = results.length >= pageSize ? "page_full" : "max_visited"; return; } const next = path.join(dir, entry.name); const rel = path.relative(config.root, next).replace(/\\/g, "/"); visited++; if (entry.isDirectory()) { if (opt.skip.has(entry.name.toLowerCase())) { skipped++; continue; } if (opt.includeDirs) await push({ path:rel, relativePath:rel, name:entry.name, isDirectory:true }, next); await walk(next); continue; } if (!entry.isFile()) continue; try { assertNotSecret(config, next); await push({ path:rel, relativePath:rel, name:entry.name, isFile:true }, next); } catch { skipped++; } }
  }
  await walk(start); const nextCursor = stoppedReason === "page_full" ? cursor + results.length : null; return { ok:true, action:payload.action || "findFiles", path:payload.path || payload.p || ".", absolutePath:start, query:payload.query || payload.find || "", ext:payload.ext || "", cursor, nextCursor, pageSize, visited, matchedSoFar:matched, returnedResults:results.length, skippedFiles:skipped, stoppedReason, hasNextPage:nextCursor !== null, partial:nextCursor !== null, defaultSkips:DEFAULT_SKIPS, nextRequest:nextCursor !== null ? { ...payload, action:payload.action || "findFiles", cursor:nextCursor, pageSize } : null, results };
}
async function withStat(config, item, full) { try { const st = await fsp.stat(full); return { ...item, sizeBytes:item.isDirectory ? 0 : st.size, mtimeMs:st.mtimeMs }; } catch { return item; } }
module.exports = { findFiles, matches, DEFAULT_SKIPS, options };
