// B"H
/** @file userInput.js @description Fresh input bridge: gestures target/talk once, door misses open nearest door. */
import { castTorahSlot, ensureTorahActionBar, openTorahCodex } from "../../systems/torah/TorahActionRuntime.js?compact=true&v=mmo-chat-macros-20260615-bh1";
import { openBag } from "../../systems/inventory/BagRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { ensureMissionState } from "../../systems/missions/MissionRuntime.js?compact=true&v=starter-contracts-20260628-bh9";
import { openChat } from "../../systems/chat/ChatRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { executeCommand } from "../../systems/chat/CommandRuntime.js?compact=true&v=starter-contracts-20260628-bh9";
import { ensureMacros, openMacros, runMacro, assignMacroToSlot } from "../../systems/macros/MacroRuntime.js?compact=true&v=starter-contracts-20260628-bh9";
import { bindInput, runCombatAttack } from "./input/InputCombat.js?compact=true&v=mobile-gameplay-revamp-20260705-bh1";
import { hotkey, openMissionLog, toggleFPS } from "./input/InputHotkeys.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { interact, toggleNearestDoor } from "./input/InputInteract.js?compact=true&v=door-roof-target-20260708-bh2";
import { selectFromTap } from "./input/InputTargeting.js?compact=true&v=door-roof-target-20260708-bh2";
import { trace } from "./input/InputTrace.js?compact=true&v=mobile-gameplay-revamp-20260705-bh1";
function bindBasics(olam){olam.on("keydown",peula=>{ensureTorahActionBar(olam);ensureMissionState(olam);ensureMacros(olam);if(hotkey(olam,peula))return;const code=peula?.code;if(!olam.keyStates[code])olam.ayshPeula("keypressed",peula);bindInput(olam,code,true,"keydown");});olam.on("keyup",peula=>bindInput(olam,peula?.code,false,"keyup"));olam.on("setInput",peula=>bindInput(olam,peula?.code,true,"setInput"));olam.on("setInputOut",peula=>bindInput(olam,peula?.code,false,"setInputOut"));}
function bindActions(olam){olam.on("combatAttack",peula=>runCombatAttack(olam,peula,"ui"));olam.on("combatEquip",peula=>olam.combatManager?.equipWeapon?.(peula?.weaponId,peula||{}));olam.on("interact",peula=>interact(olam,peula||{}));olam.on("toggleNearestDoor",()=>toggleNearestDoor(olam));olam.on("castTorahSlot",peula=>castTorahSlot(olam,peula?.slot||1));olam.on("openTorahCodex",()=>openTorahCodex(olam));olam.on("openMissionLog",()=>openMissionLog(olam));olam.on("openBag",()=>openBag(olam));olam.on("openChat",peula=>openChat(olam,peula?.tab||"General"));olam.on("submitChat",peula=>executeCommand(olam,peula?.text||"","chat"));olam.on("openMacros",()=>openMacros(olam));olam.on("runMacro",peula=>runMacro(olam,peula?.macroId||peula?.id));olam.on("assignMacroSlot",peula=>assignMacroToSlot(olam,peula?.macroId,peula?.slot||9));}
function bindWorld(olam){olam.on("acceptVillageMission",()=>olam.__villageCombatState?.accept?.());olam.on("learnNpcSkill",peula=>(olam.player||olam.chossid)?.learnSkill?.(peula?.skillId));olam.on("toggleFPS",()=>toggleFPS(olam));olam.on("returnVillage",()=>olam.ayshPeula("ui event","navigateLevel",{next:"village.json",reason:"return village loses progress"}));olam.on("setRunMode",peula=>{const running=peula?.running!==false;olam.inputs.RUNNING=running;olam.runMode=running?"run":"walk";trace(olam,"setRunMode",{running,active:Object.keys(olam.inputs).filter(k=>olam.inputs[k])});olam.ayshPeula("ui event","effectsOverlay",{text:running?"Run Mode":"Walk Mode",color:running?"#76ff8a":"#ffd966"});});olam.on("presskey",()=>{});}
function bindPointer(olam){olam.on("combatSelectPointer",peula=>selectFromTap(olam,peula,"combatSelectPointer"));olam.on("pointerdown",peula=>selectFromTap(olam,peula,"pointerdown"));olam.on("touchstart",peula=>selectFromTap(olam,peula,"touchstart"));olam.on("touchend",peula=>{const hit=selectFromTap(olam,peula,"touchend");if(!hit)interact(olam,{...peula,source:"mobile-door-tap",tap:true,isTouch:true});});olam.on("mousedown",peula=>{const selected=peula?.button===0?selectFromTap(olam,peula,"mousedown"):false;if(peula?.button===0&&selected)return;olam.ayin.onMouseDown(peula);olam.mouseDown=true;});olam.on("mouseup",peula=>{olam.ayshPeula("mouseRelease",true);olam.ayin.onMouseUp(peula);olam.mouseDown=false;});olam.on("wheel",peula=>{if(olam.ayin&&typeof olam.ayin.zoom==="function")olam.ayin.zoom(peula.deltaY);});}
export default function userInputEvents(){bindBasics(this);bindActions(this);bindWorld(this);bindPointer(this);}
