// B"H

/** B"H — Chapter 816: the preview links crossed the pruning sea whole. */
const CORE_KEYS = new Set(["BH","ok","status","error","message","note","diagnostics","action","actualAction","requestAction","actionMismatch","type","id","tunnelName","requestedTunnelName","vessel","routeReason","queuedMs","queueStats","lane","controlRequestId","clientRequestId","conversationId","conversationName","agentSessionId","logicalAgentId","missionId","projectRoot","targetVessel","nonce","jobId","stream","running","done","exitCode","signal","timedOut","statusPayload","waitPayload","stdoutPagePayload","stderrPagePayload","content","content64","stdout","stderr","files","order","items","detailedItems","results","result","record","history","timeline","count","returnedCount","totalChars","returnedChars","hasNextPage","nextPagePayload","nextOffsetChars","responseMode","externalized","outputRef","resultRef","inputRef","contentUrl","handoffUrl","ephemeral","expiresAt","expiresInSeconds","bytes","sha256","summary","inline","originalBytes","createdPreview","previewId","viewUrl","rawUrl","wsUrl","url","createUrl","previewLinks","previewInstruction","previewDisplayHint","links","artifacts","responseFocus","awtsmoosNext","mustCallNext","mustContinue","finalAnswerAllowed","multipleChoiceSelfInterrogation","allCapsPrompt","acceptedAnswerFormat","aiInstructions"]);
function pruneTunnelResponse(result = {}, payload = {}) { if (!result || typeof result !== "object" || wantsDebug(payload)) return result; const out = {}; for (const key of Object.keys(result)) if (CORE_KEYS.has(key)) out[key] = result[key]; if (result.ok === false && !out.diagnostics) out.diagnostics = compactDiagnostics(result); preservePreviewShortcut(result, out); if (out.previewLinks?.length || out.viewUrl || out.createdPreview) out.responseFocus = { ...(out.responseFocus || {}), previewRequired:true }; return out; }
function wantsDebug(payload = {}) { return payload.guidanceDebug === true || payload.guidanceDebug === "true"; }
function preservePreviewShortcut(result, out) { const preview = result.createdPreview; if (!preview || typeof preview !== "object") return; const viewUrl = preview.viewUrl || preview.url || out.viewUrl; if (!viewUrl) return; out.viewUrl = out.viewUrl || viewUrl; out.rawUrl = out.rawUrl || preview.rawUrl || result.rawUrl || ""; out.wsUrl = out.wsUrl || preview.wsUrl || result.wsUrl || ""; out.previewDisplayHint = out.previewDisplayHint || preview.previewDisplayHint || preview.source?.previewDisplayHint || ""; if (Array.isArray(out.previewLinks) && out.previewLinks.length) return; out.previewLinks = [{ id:preview.id || result.previewId || "", title:preview.title || "Awtsmoos preview", kind:preview.kind || "preview", visibility:preview.visibility || "private", viewUrl, rawUrl:out.rawUrl, wsUrl:out.wsUrl, accessSummary:preview.accessSummary || "", expiresAt:preview.expiresAt, previewDisplayHint:out.previewDisplayHint }]; out.previewInstruction = out.previewInstruction || `Open ${viewUrl}.`; }
function compactDiagnostics(result = {}) { return { routeReason:result.routeReason, tunnelName:result.tunnelName, mismatchProof:result.mismatchProof, expected:result.expected, actual:result.actual }; }
module.exports = { pruneTunnelResponse, CORE_KEYS };
