// B"H
/** @file index.js @description Quiet Mitzvah World gate plus live starter UI bridge with clickable gossip choices and NPC controls. */
let bootStarted = false;
const SEAL = "player-facing-starter-ui-live-chain-20260615-bh2";
const trace = () => window.__AWTSMOOS_BOOT_TRACE__ === true;
const esc = v => String(v ?? "").replace(/[&<>'"]/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[c]));
function safeClone(v, d = 0) { if (d > 3) return "[MaxDepth]"; if (v == null || ["string","number","boolean"].includes(typeof v)) return v; if (typeof v === "function") return `[Function ${v.name || "anonymous"}]`; if (v instanceof Error) return { name:v.name, message:v.message, stack:String(v.stack || "").slice(0, 2000) }; if (Array.isArray(v)) return v.slice(0, 24).map(x => safeClone(x, d + 1)); if (typeof v === "object") { const o = { kind:v?.constructor?.name || "Object" }; for (const k of Object.keys(v).slice(0, 30)) try { o[k] = safeClone(v[k], d + 1); } catch { o[k] = "[Unreadable]"; } return o; } return String(v).slice(0, 500); }
function mount(parentId, id, title, body = "", cls = "") { const p = document.getElementById(parentId); if (!p) return null; let el = document.getElementById(id); if (!el) { el = document.createElement("div"); el.id = id; el.className = `mitzvahPanel ${cls}`.trim(); p.appendChild(el); } el.innerHTML = `<div class="mitzvahTitle">${esc(title)}</div>${body}`; return el; }
function rows(xs, fn) { return (xs || []).slice(0, 10).map(fn).join("") || `<div class="mitzvahMuted">—</div>`; }
function olamOf(scope = window) { return scope.__AWTSMOOS_OLAM__ || scope.olam || scope.ikar?.olam || scope.mana?.activeOlam || scope.mana?.olam || null; }
function renderQuestTracker(p = {}) { return mount("mitzvahTopRight", "uiQuestTracker", "Shlichus Tracker", rows(p.active, q => `<div class="mitzvahQuestLine ${q.complete ? "mitzvahDone" : ""}">${esc(q.line || q.title)}${q.returnTo ? `<br><small>Return to ${esc(q.returnTo)}</small>` : ""}</div>`)); }
function renderQuestMarkers(p = {}) { return mount("mitzvahTopRight", "uiQuestMarkers", "Quest Markers", rows(p.markers, m => `<div>${m.marker?.includes("question") ? "?" : "!"} ${esc(m.npcName)} <small>${esc(m.title)}</small></div>`)); }
function renderGossip(p = {}) { if (!p.open) return null; window.__MITZVAH_ACTIVE_GOSSIP__ = p; const choices = rows(p.choices, c => `<button class="mitzvahChoice" data-npc="${esc(p.npcId)}" data-choice="${esc(c.id)}" onclick="window.__MITZVAH_CHOOSE_NPC__?.(this.dataset.npc,this.dataset.choice)">${esc(c.label || c.kind)}</button>`); return mount("mitzvahCenter", "uiGossip", p.npcName || "NPC", `<p>${esc(p.greeting || "B\"H, how can I help?")}</p>${choices}`); }
function renderLootSparkle(p = {}) { return mount("mitzvahBottomCenter", "uiLootSparkle", "Loot", rows(p.corpses, c => `<span class="mitzvahSparkle">✦ ${esc(c.name || c.corpseId)} sparkles</span>`)); }
function renderLoot(p = {}) { if (!p.open && !p.looted) return null; const items = rows(p.table?.items, i => `<div>${esc(i.id)} x${i.qty || 1}</div>`); return mount("mitzvahCenter", "uiLootWindow", p.creatureName || "Loot", `${items}<div class="mitzvahReward">${p.table?.money || p.perutah || 0} perutah</div><div class="mitzvahBtn">Loot all</div>`); }
function renderSpirit(p = {}) { if (!p.open && !p.ghost) return null; return mount("mitzvahCenter", "uiSpiritHealer", "Spirit Healer", rows(p.choices, c => `<div class="mitzvahChoice ${c.enabled ? "" : "mitzvahMuted"}">${esc(c.label)} ${c.enabled ? "" : "(not yet)"}</div>`)); }
function renderMinimap(p = {}) { const bits = [`${(p.markers || p.discovered || []).length} markers`, p.corpse ? "corpse" : "no corpse", p.hearth ? "hearth bound" : "no hearth"]; return mount("mitzvahTopRight", "uiMiniMap", "Minimap", bits.map(esc).join("<br>")); }
function renderNameplates(p = {}) { const plates = Array.isArray(p) ? p : (p.plates || []); return mount("mitzvahTopLeft", "uiNameplates", "Nameplates", rows(plates, x => `<div>${x.rare ? "★ " : ""}${x.elite ? "Elite " : ""}${esc(x.name)} ${x.hp ?? "?"}/${x.maxHp ?? "?"}</div>`)); }
function renderCastBar(p = {}) { if (!p.active) return mount("mitzvahBottomCenter", "uiCastBar", "Cast", "<span class='mitzvahMuted'>—</span>"); const pct = Math.max(0, Math.min(100, Math.floor((p.progress || 0) * 100))); return mount("mitzvahBottomCenter", "uiCastBar", p.spell || "Cast", `<small>${esc(p.caster)} ${p.interruptible ? "interruptible" : "locked"}</small><div class="mitzvahCastTrack"><div class="mitzvahCastFill" style="width:${pct}%"></div></div>`); }
function renderService(title, p = {}) { return mount("mitzvahTopLeft", `ui${title.replace(/\W/g, "")}`, title, `<pre style="white-space:pre-wrap;margin:0">${esc(JSON.stringify(safeClone(p), null, 2)).slice(0, 900)}</pre>`); }
function renderStarterHud(p = {}) { if (p.questTracker) renderQuestTracker(p.questTracker); if (p.questMarkers) renderQuestMarkers(p.questMarkers); if (p.minimap) renderMinimap(p.minimap); if (p.loot) renderLootSparkle(p.loot); if (p.spiritHealer) renderSpirit(p.spiritHealer); if (p.nameplates) renderNameplates(p.nameplates); if (p.castbar) renderCastBar(p.castbar); if (p.activeNpc) renderGossip(p.activeNpc); return true; }
function installSoloWowUiBridge() { window.__MITZVAH_UI_STATE__ ||= {}; const r = { starterZoneHud:renderStarterHud, npcGossip:renderGossip, questAccepted:p => renderService("Quest Accepted", p), questProgress:p => renderService("Quest Progress", p), questTurnedIn:p => renderService("Quest Turned In", p), questTracker:renderQuestTracker, questMarkers:renderQuestMarkers, lootSparkle:renderLootSparkle, loot:renderLoot, spiritHealer:renderSpirit, deathState:p => renderSpirit({ open:p.ghost, ghost:p.ghost, choices:[{ label:"Return to corpse", enabled:Boolean(p.corpse) }, { label:"Spirit healer", enabled:p.ghost }] }), minimap:renderMinimap, mapReveal:renderMinimap, castBar:renderCastBar, nameplates:renderNameplates, corpseMarker:p => mount("mitzvahTopRight", "uiCorpse", "Corpse", p.hasCorpse ? `x:${Math.round(p.corpse?.x || 0)} z:${Math.round(p.corpse?.z || 0)}` : "none"), rareAnnouncement:p => mount("mitzvahBottomCenter", "uiRare", "Rare", p.text || p.name || "Rare sighted"), trainerScreen:p => renderService("Trainer", p), vendorScreen:p => renderService("Vendor", p), innRest:p => renderService("Inn", p), hearthBind:p => renderService("Hearth", p), bankScreen:p => renderService("Bank", p), mailboxScreen:p => renderService("Mailbox", p), worldAnnouncement:p => mount("mitzvahBottomCenter", "uiWorld", p.title || "World", p.text || "Announcement") };
  window.__MITZVAH_UI_BRIDGE__ = { receive(name, payload) { window.__MITZVAH_UI_STATE__[name] = safeClone(payload); r[name]?.(payload || {}); return true; }, state:window.__MITZVAH_UI_STATE__ };
  window.__MITZVAH_CHOOSE_NPC__ = (npcId, choiceId) => window.__MITZVAH_NPC_INTERACTION__?.choose?.(npcId, choiceId);
  window.addEventListener("message", e => { const d = e.data || {}; if (d.type === "ui event" && d.name) window.__MITZVAH_UI_BRIDGE__.receive(d.name, d.payload); }); }
function renderErrorPanel(details) { let p = document.getElementById("awtsmoosBootErrorPanel"); if (!p) { p = document.createElement("pre"); p.id = "awtsmoosBootErrorPanel"; p.style.cssText = "position:fixed;inset:12px;z-index:999999;padding:16px;overflow:auto;white-space:pre-wrap;background:#190000;color:#ffd7a0;border:2px solid #ff6b2a;font:13px/1.4 monospace;"; document.body.appendChild(p); } p.textContent = `B\"H — Mitzvah World boot error\n\n${JSON.stringify(details, null, 2)}`; }
function describeAwtsmoosError(error, context = {}) { const details = { context:safeClone(context), thrown:safeClone(error), at:new Date().toISOString(), page:location?.href || null }; window.__AWTSMOOS_LAST_ERROR__ = details; window.__AWTSMOOS_LAST_ERROR_JSON__ = JSON.stringify(details, null, 2); window.__AWTSMOOS_ERROR_COUNT__ = Number(window.__AWTSMOOS_ERROR_COUNT__ || 0) + 1; if (trace()) console.error(`B"H - ${context.label || "Runtime error"}`, details); renderErrorPanel(details); return details; }
async function installBrowserHelpers() { try { const smoke = await import(`./ckidsAwtsmoos/testing/CompactLiveSmoke.js?bh=${SEAL}`); smoke.installCompactLiveSmoke?.(window); } catch (e) { window.__MITZVAH_COMPACT_SMOKE_INSTALL_ERROR__ = safeClone(e); } try { const npc = await import(`./ckidsAwtsmoos/systems/npc/NpcInteractionRuntime.js?bh=${SEAL}`); npc.installNpcInteractionControls?.(window, () => olamOf(window)); } catch (e) { window.__MITZVAH_NPC_INSTALL_ERROR__ = safeClone(e); } }
function bootIkarNow() { if (bootStarted || typeof window === "undefined" || !window.document) return; bootStarted = true; window.__AWTSMOOS_BOOT_STARTED__ = { at:new Date().toISOString(), readyState:document.readyState, seal:SEAL }; installSoloWowUiBridge(); installBrowserHelpers(); const url = `./ckidsAwtsmoos/ikar.js?compact=true&bh=${SEAL}`; import(url).then(m => { window.__AWTSMOOS_BOOT_LOADED__ = { at:new Date().toISOString(), keys:Object.keys(m || {}).slice(0, 20), seal:SEAL }; }).catch(e => describeAwtsmoosError(e, { label:"Index [Main]: Failed to load UI starter", phase:"dynamic import", moduleURL:new URL(url, import.meta.url).href })); }
window.addEventListener("error", e => describeAwtsmoosError(e.error || e.message, { label:"Global error", phase:"window.error", moduleURL:e.filename, line:e.lineno, column:e.colno }));
window.addEventListener("unhandledrejection", e => describeAwtsmoosError(e.reason, { label:"Unhandled promise rejection", phase:"window.unhandledrejection" }));
export async function heescheel(ctx) { if (trace()) console.info("B\"H - Index [Worker]: data-driven level hook.", Boolean(ctx)); }
export function ready(ctx) { ctx.postMsg({ type:"game started", payload:true }); }
export function afterBriyah(ctx) { if (trace()) console.info("B\"H - Index [Worker]: afterBriyah() called", Boolean(ctx)); }
if (document.readyState === "loading") window.addEventListener("DOMContentLoaded", bootIkarNow, { once:true }); else bootIkarNow();
