// B"H
/**
 * collisions.js
 *
 * Chapter 98: when an invisible wall pushes the chossid, the wall must give its
 * name. The Awtsmoos does not erase collision; He reveals the owner, the normal,
 * the depth, and the place, so the false fence can be repaired without deleting
 * true solidity.
 */
function finiteCollision(result) { return result && Number.isFinite(result.depth) && Number.isFinite(result.normal?.x) && Number.isFinite(result.normal?.y) && Number.isFinite(result.normal?.z); }
function finiteCapsule(collider) { return collider?.start && collider?.end && Number.isFinite(collider.start.x) && Number.isFinite(collider.start.y) && Number.isFinite(collider.start.z) && Number.isFinite(collider.end.x) && Number.isFinite(collider.end.y) && Number.isFinite(collider.end.z); }
function playerPos(self) { return self?.mesh?.position || self?.position || self?.modelMesh?.position || null; }
function ownerOf(result) { const obj = result?.object || result?.mesh || result?.triangle?.object || result?.collider || null; const d = obj?.userData || {}; return { name:obj?.name || d.name || d.ownerName || d.colliderOwner || "unknown-octree-collider", kind:d.colliderKind || d.kind || d.ownerKind || (d.isTreeTrunkCollider ? "tree-trunk" : d.houseCollider ? "house" : d.parcelCollider ? "parcel" : d.fenceCollider ? "fence" : "unknown"), userData:d }; }
function emitWallDebug(self, result, dirX, dirZ) { const p = playerPos(self), owner = ownerOf(result), payload = { at:Date.now(), owner:owner.name, kind:owner.kind, depth:result.depth, normal:{ x:dirX, y:result.normal.y, z:dirZ }, position:p ? { x:p.x, y:p.y, z:p.z } : null }; self.olam.__lastInvisibleWallHit = payload; self.olam.__wallHitHistory ||= []; self.olam.__wallHitHistory.push(payload); if (self.olam.__wallHitHistory.length > 30) self.olam.__wallHitHistory.shift(); if (self.olam.__AWTSMOOS_SHOW_COLLIDER_DEBUG__ || globalThis.__AWTSMOOS_SHOW_COLLIDER_DEBUG__) self.olam?.ayshPeula?.("ui event", "combatLog", { text:`WALL ${payload.kind}: ${payload.owner}`, category:"Collider" }); }
export default { collisions() { if (!this.olam || !this.olam.worldOctree || !this.collider || !this.velocity) return; if (!finiteCapsule(this.collider)) return; const WALL_STEP_HEIGHT = 0.2; this.collider.start.y += WALL_STEP_HEIGHT; this.collider.end.y += WALL_STEP_HEIGHT; for (let i = 0; i < 3; i += 1) { const result = this.olam.worldOctree.capsuleIntersect(this.collider); if (!result) break; if (!finiteCollision(result)) break; const isFloor = result.normal.y >= 0.15; if (isFloor || result.depth < 1e-10) continue; const nx = result.normal.x, nz = result.normal.z, horizontalLenSq = nx * nx + nz * nz; if (!Number.isFinite(horizontalLenSq) || horizontalLenSq <= 1e-5) continue; const horizontalLen = Math.sqrt(horizontalLenSq), dirX = nx / horizontalLen, dirZ = nz / horizontalLen; if (!Number.isFinite(dirX) || !Number.isFinite(dirZ)) continue; if (!this._frameWallNormals) this._frameWallNormals = []; this._frameWallNormals.push({ x:dirX, z:dirZ }); emitWallDebug(this, result, dirX, dirZ); const dot = this.velocity.x * dirX + this.velocity.z * dirZ; if (Number.isFinite(dot) && dot < 0) { this.velocity.x -= dirX * dot; this.velocity.z -= dirZ * dot; } const push = { x:nx * result.depth, y:0, z:nz * result.depth }; if (Number.isFinite(push.x) && Number.isFinite(push.z)) this.collider.translate(push); } this.collider.start.y -= WALL_STEP_HEIGHT; this.collider.end.y -= WALL_STEP_HEIGHT; } };
