// B"H
const { ByteWriter } = require('./ByteWriter.js');
const { ByteReader } = require('./ByteReader.js');
const { createDocumentStub } = require('./WebBinaryRuntime.js');
const { tokenizeSelector, selectorTextFromTokens } = require('./ModeSelectorCodec.js');
const { specificity } = require('./CssSelectorEngine.js');
const { writeText, readText, writeRef, readRef, writeValue, readValue } = require('./Mode2ValueCodec.js');
const { compressRepeatNodes } = require('./Mode2RepeatNodes.js');
const { buildTemplateTable, templateIdFor } = require('./Mode2Templates.js');
const { canEncodeCssBits, encodeCssBits, decodeCssBits } = require('./Mode2CssBitCodec.js');
const { choosePoolEncoding, readPoolSmart } = require('./Mode2PoolCodec.js');
const { needsBits, encodeJsBits, decodeJsBits, encodeJsScopeBits, decodeJsScopeBits } = require('./Mode2JsBitCodec.js');
const MAGIC = 'MD2\0';
const OP = Object.freeze({ END:0, NODE:1, STYLE:3, JS:4, REPEAT_NODE:5, TEMPLATE_NODE:6, STYLE_BITS:7, STYLE_STREAM_BITS:8, TEMPLATE_STREAM:9, JS_BITS:10, JS_SCOPE_BITS:11 });

function writePool(w, pool) { w.varUint(pool.length); for (const s of pool) writeText(w, s); }
function readPool(r) { const n = r.varUint(), pool = []; for (let i = 0; i < n; i++) pool.push(readText(r)); return pool; }
function selectorKey(sel, table) { let i = table.indexOf(sel); if (i < 0) { i = table.length; table.push(sel); } return i; }
function attrsOfNode(node) { return Object.entries(node.attrs || {}).filter(([k]) => k !== 'id'); }
function writeAttrs(w, pool, attrs) { w.varUint(attrs.length); for (const [k, v] of attrs) { writeRef(w, pool, k); writeValue(w, pool, v === '' ? 'true' : v); } }
function readAttrs(r, pool) { const attrs = [], n = r.varUint(); for (let i = 0; i < n; i++) attrs.push([readRef(r, pool), readValue(r, pool)]); return attrs; }
function writeTemplate(w, pool, t) { writeRef(w, pool, t.tag); writeRef(w, pool, t.parent); writeAttrs(w, pool, Object.entries(t.attrs || {})); }
function readTemplate(r, pool) { return { tag: readRef(r, pool), parent: readRef(r, pool), attrs: readAttrs(r, pool) }; }
function writeNode(w, pool, n) { writeRef(w, pool, n.tag); writeRef(w, pool, n.id); writeRef(w, pool, n.parent); writeValue(w, pool, n.text || ''); writeAttrs(w, pool, attrsOfNode(n)); }
function writeTemplateNode(w, pool, id, n) { w.varUint(id); writeRef(w, pool, n.id); writeValue(w, pool, n.text || ''); }
function writeRepeat(w, pool, run) { writeRef(w, pool, run.first.tag); writeRef(w, pool, run.first.parent); writeRef(w, pool, run.id0.prefix); w.varUint(run.id0.num).varUint(run.count); writeRef(w, pool, run.text0?.prefix || ''); w.varUint(run.text0?.num || 0); writeAttrs(w, pool, attrsOfNode(run.first)); }
function writeStyles(body, pool, selectors, styles) { const allBit = styles.length > 1 && styles.every(s => canEncodeCssBits(Object.entries(s.props || {}), pool)); if (allBit) { body.varUint(1).u8(OP.STYLE_STREAM_BITS).varUint(styles.length); for (const s of styles) { const sid = selectorKey(s.selector || s.target || '', selectors); body.varUint(sid).bytesWithLength(encodeCssBits(Object.entries(s.props || {}), pool)); } return; } body.varUint(styles.length); for (const s of styles) { const sid = selectorKey(s.selector || s.target || '', selectors), props = Object.entries(s.props || {}); if (canEncodeCssBits(props, pool)) { body.u8(OP.STYLE_BITS).varUint(sid).bytesWithLength(encodeCssBits(props, pool)); } else { body.u8(OP.STYLE).varUint(sid).varUint(props.length); for (const [k, v] of props) { writeRef(body, pool, k); writeValue(body, pool, v); } } } }
function ensureProgramPool(pool, program) { if (!program) return; for (const v of [program.label, program.suffix, ...(program.targets || [])]) if (v && !pool.includes(String(v))) pool.push(String(v)); }
function writeProgram(body, pool, program) { if (program?.setText) { body.u8(OP.JS).u8(1); writeRef(body, pool, program.setText.target); writeValue(body, pool, program.setText.value); } else if (program?.webgl) { const w = program.webgl; body.u8(OP.JS).u8(2); writeRef(body, pool, w.target || 'stage'); for (const n of (w.viewport || [0,0,160,90])) body.varUint(Number(n) || 0); for (const n of (w.clearColor || [0,0,0,1])) body.varUint(Math.round((Number(n) || 0) * 1000)); for (const n of (w.drawArrays || [0,3])) body.varUint(Number(n) || 0); } else if (program && needsBits(program)) { ensureProgramPool(pool, program); body.u8(OP.JS_SCOPE_BITS).bytesWithLength(encodeJsScopeBits(program, pool)); } else if (program) { body.u8(OP.JS).u8(0).varUint(program.base || 0).varUint(program.extra || 0).varUint((program.yields || []).length); for (const n of program.yields || []) body.varUint(n); writeValue(body, pool, program.label || ''); writeValue(body, pool, program.suffix || ''); body.varUint((program.targets || []).length); for (const t of program.targets || []) writeRef(body, pool, t); } body.u8(OP.END); }
function writeNodeEntry(body, pool, table, entry) { if (entry.type === 'repeat') { body.u8(OP.REPEAT_NODE); writeRepeat(body, pool, entry); return; } const tid = templateIdFor(table.index, entry.node); if (tid >= 0) { body.u8(OP.TEMPLATE_NODE); writeTemplateNode(body, pool, tid, entry.node); return; } body.u8(OP.NODE); writeNode(body, pool, entry.node); }
function writeNodeEntries(body, pool, table, entries) { const records = []; for (let i = 0; i < entries.length; i++) { const entry = entries[i], tid = entry.type === 'node' ? templateIdFor(table.index, entry.node) : -1; if (tid >= 0) { const run = []; while (i < entries.length) { const e = entries[i], id = e.type === 'node' ? templateIdFor(table.index, e.node) : -1; if (id < 0) break; run.push([id, e.node]); i++; } i--; if (run.length >= 3) records.push({ stream: run }); else for (const [id, node] of run) records.push({ entry: { type: 'node', node } }); } else records.push({ entry }); } body.varUint(records.length); for (const rec of records) { if (rec.stream) { body.u8(OP.TEMPLATE_STREAM).varUint(rec.stream.length); for (const [tid, node] of rec.stream) writeTemplateNode(body, pool, tid, node); } else writeNodeEntry(body, pool, table, rec.entry); } }
function encodeMode2App({ nodes = [], styles = [], program = null } = {}) { const pool = [], selectors = [], body = new ByteWriter(), table = buildTemplateTable(nodes), entries = compressRepeatNodes(nodes); body.varUint(table.templates.length); for (const t of table.templates) writeTemplate(body, pool, t); writeNodeEntries(body, pool, table, entries); writeStyles(body, pool, selectors, styles); writeProgram(body, pool, program); const poolPlan = choosePoolEncoding(pool); const w = new ByteWriter(); w.raw(Buffer.from(MAGIC, 'binary')).u8(poolPlan.version); if (poolPlan.version >= 4) w.u8(poolPlan.kind); w.raw(poolPlan.bytes); w.varUint(selectors.length); for (const s of selectors) { const toks = tokenizeSelector(s, pool); w.varUint(toks.length); for (const t of toks) w.varUint(t); } w.bytesWithLength(body.toBuffer()); return w.toBuffer(); }
function decodeMode2App(buffer) { const r = new ByteReader(buffer); if (r.bytes(4).toString('binary') !== MAGIC) throw Error('Bad MD2 magic'); const version = r.u8(), pool = version >= 4 ? readPoolSmart(r) : readPool(r), selectors = []; const sc = r.varUint(); for (let i = 0; i < sc; i++) { const n = r.varUint(), toks = []; for (let t = 0; t < n; t++) toks.push(r.varUint()); selectors.push(selectorTextFromTokens(toks, pool)); } return { version, pool, selectors, body: new ByteReader(r.bytesWithLength()) }; }
function setStyle(el, prop, value, score, order) { el.__styleMeta = el.__styleMeta || {}; const old = el.__styleMeta[prop]; if (!old || score > old.score || (score === old.score && order >= old.order)) { el.style[prop] = String(value); el.__styleMeta[prop] = { score, order }; } }
function appendEl(document, byId, tag, id, parent, text, attrs) { const el = document.createElement(tag); el.id = id; el.textContent = String(text || ''); if (id) document.byId.set(id, el); (byId(parent) || document.body).appendChild(el); for (const [a, v] of attrs) el.setAttribute(a, v === true ? '' : v); return el; }
function readNode(r, app, document, byId) { appendEl(document, byId, readRef(r, app.pool), readRef(r, app.pool), readRef(r, app.pool), readValue(r, app.pool), readAttrs(r, app.pool)); }
function readTemplateNode(r, app, document, byId, templates) { const t = templates[r.varUint()]; appendEl(document, byId, t.tag, readRef(r, app.pool), t.parent, readValue(r, app.pool), t.attrs); }
function readRepeat(r, app, document, byId) { const tag = readRef(r, app.pool), parent = readRef(r, app.pool), idPrefix = readRef(r, app.pool), start = r.varUint(), count = r.varUint(); const textPrefix = readRef(r, app.pool), textStart = r.varUint(), attrs = readAttrs(r, app.pool); for (let i = 0; i < count; i++) appendEl(document, byId, tag, idPrefix + (start + i), parent, textPrefix ? textPrefix + (textStart + i) : '', attrs); }
function readNodes(app, r, document, byId) { const templates = [], tc = r.varUint(); for (let i = 0; i < tc; i++) templates.push(readTemplate(r, app.pool)); const nc = r.varUint(); for (let i = 0; i < nc; i++) { const op = r.u8(); if (op === OP.NODE) readNode(r, app, document, byId); else if (op === OP.REPEAT_NODE) readRepeat(r, app, document, byId); else if (op === OP.TEMPLATE_NODE) readTemplateNode(r, app, document, byId, templates); else if (op === OP.TEMPLATE_STREAM) { const count = r.varUint(); for (let j = 0; j < count; j++) readTemplateNode(r, app, document, byId, templates); } else throw Error('Bad node op ' + op); } }
function applyStylePairs(app, document, order, sid, pairs) { const sel = app.selectors[sid] || '', score = specificity(sel); for (const el of document.querySelectorAll(sel)) for (const [prop, value] of pairs) setStyle(el, prop, value, score, order++); return order; }
function readStyles(app, r, document, order) { const sc = r.varUint(); for (let i = 0; i < sc; i++) { const op = r.u8(); if (op === OP.STYLE_STREAM_BITS) { const count = r.varUint(); for (let j = 0; j < count; j++) order = applyStylePairs(app, document, order, r.varUint(), decodeCssBits(r.bytesWithLength(), app.pool)); continue; } const sid = r.varUint(); let pairs = []; if (op === OP.STYLE_BITS) pairs = decodeCssBits(r.bytesWithLength(), app.pool); else { const pc = r.varUint(); for (let p = 0; p < pc; p++) pairs.push([readRef(r, app.pool), readValue(r, app.pool)]); } order = applyStylePairs(app, document, order, sid, pairs); } return order; }
function readProgram(app, r, byId) { let result = ''; while (!r.done()) { const op = r.u8(); if (op === OP.END) break; if (op === OP.JS_SCOPE_BITS) { const packed = decodeJsScopeBits(r.bytesWithLength(), app.pool); result = packed.result; for (const target of packed.targets) { const el = byId(target); if (el) el.textContent = result; } continue; } if (op === OP.JS_SCOPE_BITS) { const packed = decodeJsScopeBits(r.bytesWithLength(), app.pool); result = packed.result; for (const target of packed.targets) { const el = byId(target); if (el) el.textContent = result; } continue; } if (op === OP.JS_BITS) { const packed = decodeJsBits(r.bytesWithLength(), app.pool); result = packed.result; for (const target of packed.targets) { const el = byId(target); if (el) el.textContent = result; } continue; } if (op === OP.JS_SCOPE_BITS) { const packed = decodeJsScopeBits(r.bytesWithLength(), app.pool); result = packed.result; for (const target of packed.targets) { const el = byId(target); if (el) el.textContent = result; } continue; } if (op === OP.JS_SCOPE_BITS) { const packed = decodeJsScopeBits(r.bytesWithLength(), app.pool); result = packed.result; for (const target of packed.targets) { const el = byId(target); if (el) el.textContent = result; } continue; } if (op === OP.JS_BITS) { const packed = decodeJsBits(r.bytesWithLength(), app.pool); result = packed.result; for (const target of packed.targets) { const el = byId(target); if (el) el.textContent = result; } continue; } if (op !== OP.JS) continue; const kind = r.u8(); if (kind === 1) { const el = byId(readRef(r, app.pool)); result = String(readValue(r, app.pool)); if (el) el.textContent = result; } else if (kind === 2) { const target = readRef(r, app.pool); const viewport = [r.varUint(), r.varUint(), r.varUint(), r.varUint()]; const clearColor = [r.varUint(), r.varUint(), r.varUint(), r.varUint()].map(n => n / 1000); const drawArrays = [r.varUint(), r.varUint()]; result = { webgl: { target, viewport, clearColor, drawArrays } }; } else { const base = r.varUint(), extra = r.varUint(), yc = r.varUint(); let sum = base + extra; for (let i = 0; i < yc; i++) sum += r.varUint(); const label = readValue(r, app.pool), suffix = readValue(r, app.pool); result = `${label}:${sum}${suffix ? ':' + suffix : ''}`; const tc = r.varUint(); for (let i = 0; i < tc; i++) { const el = byId(readRef(r, app.pool)); if (el) el.textContent = result; } } } return result; }
function runMode2App(buffer, options = {}) { const app = decodeMode2App(buffer), r = app.body, document = options.document || createDocumentStub(); const byId = id => id ? document.getElementById(id) : document.body; readNodes(app, r, document, byId); readStyles(app, r, document, 0); const result = readProgram(app, r, byId); return { ok: true, document, result, app }; }
module.exports = { MAGIC, encodeMode2App, decodeMode2App, runMode2App, OP, MODE2_OP: OP };
