// B"H
import { obedienceMonitor, mountObedienceMonitor } from "../features/obedienceMonitor.js";
/**
 * B"H
 * Chapter 914: The command center opened a guarded remote eye.
 */
const groups = Object.freeze({ core:"Command center", files:"Files", automation:"Live", ai:"Agents", system:"Advanced" });
export const PAGE_GROUPS = groups;
export const PAGE_SPECS = [
  { key:"missionRooms", group:"ai", badges:["core","rooms"], icon:"agents", emoji:"💬", title:"Mission control", desc:"Room OS lobby, conversation workspace, selected-room event stream, metrics, agents, files, and artifacts.", ids:["roomLobby","roomSearch","roomFilter","discoverRoomsBtn","roomStatus","roomList","roomWorkspace","newRoomGoal","createRoomBtn","roomOut"] },
  { key:"live", group:"automation", badges:["core","table"], icon:"live", emoji:"🟢", title:"Live commands", desc:"Grouped current-chat tool activity: agent, action, target, result, and time.", ids:["liveGroupBy","liveFilter","liveLimit","livePollMs","startLiveBtn","stopLiveBtn","refreshLiveBtn","clearLiveBtn","liveSocketState","liveGroups","liveSummary","liveViewport","liveWindow","liveOut"] },
  { key:"explorer", group:"files", badges:["core","tree"], icon:"explorer", emoji:"📁", title:"Project explorer", desc:"VS Code style tree and preview for files inside the chosen root.", ids:["explorerPath","treeDepth","treeLimit","listBtn","treeBtn","readBtn","mdBtn","explorerList","explorerPreview","explorerOut"], selectors:["[data-viewer]"] },
  { key:"usage", group:"system", badges:["core","tools"], icon:"actions", emoji:"⌘", title:"Tool codex", desc:"Search and run tunnel actions from one command palette style catalog.", ids:["loadUsageBtn","usageBox","actionCatalogSearch","actionCatalogGrid","actionDetail","actionName","actionPath","maxChars","writeContent","bulkPaths","bulkWriteJson","runActionBtn","copyActionUrlBtn","actionUrlOut","actionOut"] },
  { key:"remoteDesktop", group:"automation", badges:["core","consent"], icon:"preview", emoji:"🖥️", title:"Remote desktop", desc:"Create consent-first watch/control sessions over the tunnel." },
  { key:"setup", group:"core", badges:["core","safe"], icon:"setup", emoji:"🛠️", title:"Root and permissions", desc:"Set the project root and exactly what the agent may do.", ids:["loadConfigBtn","saveConfigBtn","rootPath","chooseRootBtn","openRootBtn","rootsBtn","useRepoRootBtn","applyRootToExplorerBtn","quickRoots","allowWrite","allowSecrets","enableLocalHttpProxy","toolFsList","toolFsTree","toolFsRead","toolFsWrite","toolFsBulk","allowCommands","toolCommand","toolChrome","gitAutoUpdateGitignore","gitIgnoreAwtsmoosTemp","gitIgnoreAiThoughts","configOut"] },
  { key:"obedienceMonitor", create:obedienceMonitor, mount:mountObedienceMonitor, group:"core", badges:["core"], icon:"agents", emoji:"🧭", title:"Obedience monitor", desc:"Watch what the current agent is doing and why." },
  { key:"terminal", group:"automation", badges:["advanced"], icon:"terminal", emoji:"⌁", title:"Command runner", desc:"Run controlled shell and node commands.", ids:["commandShell","commandCwd","commandTimeout","commandMaxChars","commandText","runCommandBtn","testCommandBtn","testPwdBtn","clearTerminalBtn","terminalResult","nodeScriptText","runNodeScriptBtn","clearNodeScriptBtn","nodeScriptResult","terminalOut"] },
  { key:"chrome", group:"automation", badges:["advanced","browser"], icon:"chrome", emoji:"🌐", title:"Browser control", desc:"Launch, navigate, inspect, click, type, evaluate, and script Chrome.", ids:["chromePath","chromePort","chromeUrl","chromeSelector","chromeText","chromeWaitTimeout","chromeExpression","chromeScript","chromeOut"], buttonText:["Find Chrome","Launch / Connect","Status","Navigate","Wait","Click","Type","Evaluate JS","Run script"] },
  { key:"previewGateway", group:"automation", badges:["advanced","share"], icon:"preview", emoji:"🔭", title:"Preview gateway", desc:"Protected view links, dynamic pages, live streams, and local server previews.", ids:["conversationName","conversationId","registerConversationBtn","refreshConversationsBtn","previewKind","previewVisibility","previewTitle","previewPath","previewTtl","previewTunnelName","previewTargetVessel","previewHtml","createPreviewBtn","refreshPreviewsBtn","previewFrame","previewList","conversationHistory","previewOut","loadPreviewSettingsBtn","savePreviewSettingsBtn","allowAiManagePreview","allowAiCreatePrivate","allowAiCreatePublic","allowAiExtendTtl","allowAiEnableDownload","allowAiExposeFolders","allowAiExposeLocalServers"] },
  { key:"apiKeys", group:"system", badges:["advanced","secure"], icon:"keys", emoji:"🔐", title:"API key vault", desc:"Create, save, mask, and activate keys.", ids:["refreshKeysBtn","keyName","keyRate","keyBytes","createKeyBtn","apiKeyInput","saveApiKeyBtn","clearApiKeyBtn","activeKeySummary","savedKeysList","keysOut"], classes:["scopeBox"] },
  { key:"compute", group:"system", badges:["advanced","billing"], icon:"compute", emoji:"🪙", title:"Compute / Perutas", desc:"Sandbox PayPal packs, peruta balance, and Talmudic coin converter.", ids:["refreshComputeBtn","computeBalance","computePacks","coinAmount","coinType","convertCoinsBtn","coinResults","coinLadder","computeOut"] },
  { key:"docs", group:"system", badges:["advanced","safe"], icon:"docs", emoji:"📜", title:"Agent docs", desc:"Prompt, human docs, JSON docs, OpenAPI, and instructions.", ids:["projectPath","promptMode","promptExtra","savePromptBtn","copyPromptBtn","promptBox"], links:["/api/tunnel/control/docs","/api/tunnel/control/docs.json","/apps/tunnel-control/openapi.yaml"] },
  { key:"aiAgents", group:"ai", badges:["advanced"], icon:"agents", emoji:"🧠", title:"AI agents", desc:"Provider keys, delegates, tasks, target vessel, and messages.", ids:["aiTargetVessel","aiTargetVesselDisplay","aiProviderStatus","aiProviderId","aiModelSelect","aiProviderKey","saveProviderKeyToAccount","saveAiProviderKeyBtn","removeProviderKeyBtn","loadAiAgentsBtn","aiMaxDepth","aiMaxChildren","aiMaxTotalTasks","aiAllowRecursive","saveAiConfigBtn","aiAgentId","aiAgentModel","aiAgentSystem","aiAgentMessage","sendAiAgentBtn","spawnAiTaskBtn","listAiTasksBtn","aiTaskId","aiTaskStatusBtn","aiTaskResultBtn","aiAgentsOut"] },
  { key:"account", group:"core", badges:["advanced","status"], icon:"account", emoji:"👤", title:"Account and connection", desc:"Login, device, tunnel, and identity state.", ids:["identitySummary","deviceSummary","identityBox","deviceBox","miniStatus","refreshBtn","refreshDeviceBtn","tunnelName","targetVesselSelect","selectedTargetVessel"] },
  { key:"install", group:"core", badges:["advanced","safe"], icon:"install", emoji:"⚡", title:"Install or restart", desc:"Copy installer commands.", commandPage:true },
  { key:"mesh", group:"system", badges:["advanced"], icon:"mesh", emoji:"🕸️", title:"Runtime mesh", desc:"Runtimes, mounts, graph, and timeline." }
];
export const PAGE_ORDER = PAGE_SPECS.map(page => page.key);
export const PAGE_META = Object.fromEntries(PAGE_SPECS.map(page => [page.key, page]));
