// B"H
/**
 * @file heesHawvoos.js
 * @description Chapter 45: lightning gameplay. The player receives every breath;
 * quiet NPCs sleep on precomputed paths, stirring rarely, never stealing motion.
 */
import UniversePulsator from '../oyved/UniversePulsator.js?v=worker-60fps-timer-20260702-bh1';
import RenderTrace from './canvas/RenderTrace.js?v=village-polish-20260612-bh811';
import { signalWorldFinalReady } from '../worlds/mitzvahWorld/runtime/WorldFinalReadySignal.js?v=zone-reality-20260614-bh817';
import { getDynamicActorPartition } from '../worlds/mitzvahWorld/runtime/DynamicActorPartition.js?v=awtsmoos-dynamic-partition-20260614-bh2';
import { hardGroundPlayer } from './loadNivrayim/villageGrounding.js?v=hard-player-grounding-20260701-bh1';
import { DYNAMIC, FOCUS_EPS, NIVRA_CACHE_MS, NON_PLAYER_ENTITY_BUDGET, READY_SIGNAL_MS, SIMPLE_NPC_NEAR_SQ, STATIC, VANITY, WARN_LIMIT } from './heesHawvoos/HeesFrameConfig.js?v=mitzvah-aggressive-split-20260703-bh1';
import { applyAdaptiveRenderResolution } from '../../systems/performance/AdaptiveRenderResolution.js?v=mobile-crisp-no-downscale-20260706-bh1';
import { maybeRefreshRenderBudgetDiagnostics } from '../../systems/performance/RenderBudgetDiagnostics.js?v=material-visible-budget-20260706-bh1';
const now=()=>performance.now(),typeKey=n=>String(n?.type||n?.constructor?.name||'').toLowerCase(),okNum=v=>Number.isFinite(Number(v));
const okVec=v=>!v||(okNum(v.x)&&okNum(v.y)&&okNum(v.z)),okMat=m=>!m?.elements||m.elements.every(okNum),vcopy=v=>v?{x:Number(v.x),y:Number(v.y),z:Number(v.z)}:null;
function ensureWorkerWindowVessel(){if(typeof globalThis.window!=='undefined')return globalThis.window;try{Object.defineProperty(globalThis,'window',{value:globalThis,configurable:true});}catch{globalThis.window=globalThis;}globalThis.window.wowd||=false;return globalThis.window;}
function compactError(e){return{name:e?.name||'Error',message:e?.message||String(e),stack:String(e?.stack||'').split('\n').slice(0,5).join(' | ')}}
function safeRenderTrace(name,data){if(globalThis.__AWTSMOOS_RENDER_TRACE__!==true)return;try{RenderTrace.speak(name,data)}catch(e){console.warn('B"H | RENDER_TRACE_FAILED',{name,message:e?.message||String(e)})}}
function budgetOf(){return globalThis?.__AWTSMOOS_PERFORMANCE_MODE__?.budget||{}}
function partitionFor(self){const b=budgetOf();return getDynamicActorPartition(self).configure({near:b.npcDistance||48,mid:(b.npcDistance||48)*1.8,far:(b.treeDistance||120)*2.2})}
function isSimpleNpc(n){return Boolean(n?.type==='interactiveNpc'||n?.__awtsmoosSimplePrecomputedNpc||n?.__npcLowCost||n?.mesh?.userData?.lowCostNpc)}
function nearPlayer(n,self){const a=n?.mesh?.position,b=(self.chossid||self.player)?.mesh?.position;if(!a||!b)return false;const dx=a.x-b.x,dz=a.z-b.z;return dx*dx+dz*dz<SIMPLE_NPC_NEAR_SQ}
function hasMotion(n){if(isSimpleNpc(n))return false;const m=n?.moving||{};return Boolean(m.forward||m.backward||m.stridingLeft||m.stridingRight||m.turningLeft||m.turningRight||m.jump||n?.movingAutomatically||n?.navTarget||n?.currentPath||n?._isMoving||((n?.velocity?.lengthSq?.()||0)>FOCUS_EPS))}
function shouldDriveOctreeFocus(n,self){if(!n||isSimpleNpc(n))return false;if(n===self.chossid||n===self.player||typeKey(n)==='chossid')return true;return hasMotion(n)}
function shouldPartitionNivra(n,self){if(!n||n===self.chossid||n===self.player||typeKey(n)==='chossid')return false;const key=typeKey(n);return Boolean(n.mesh&&(DYNAMIC.has(key)||n.userData?.wildlifeActor||n.isNpc||n.isEnemy))}
function tickerInterval(n){const name=String(n?.name||'').toLowerCase();if(name.includes('wildlife'))return .11;if(name.includes('npc'))return .2;return .25}
function staticVisual(n,self){if(!n||n===self.chossid||n===self.player)return false;if(n.forceEveryFrame||n.__awtsmoosNeedsFrame||n.userData?.forceEveryFrame)return false;if(hasMotion(n))return false;const key=typeKey(n);return STATIC.has(key)||(n.userData?.visualOnly&&!DYNAMIC.has(key))}
function hostile(node){if(!node)return false;if(node.isLine||node.isLineSegments||node.isPoints||VANITY.has(node.type))return true;const gt=String(node.geometry?.type||''),mat=Array.isArray(node.material)?node.material[0]:node.material;return gt.includes('BufferGeometry')&&(mat?.isLineBasicMaterial||mat?.isPointsMaterial)}
function renderNodeRecord(node,reason){return{name:node?.name||'(unnamed)',type:node?.type||null,material:Array.isArray(node?.material)?node.material.map(m=>m?.type||m?.name).filter(Boolean).join(','):node?.material?.type||node?.material?.name||null,geometry:node?.geometry?.type||null,parent:node?.parent?.name||null,owner:node?.nivraAwtsmoos?.name||node?.userData?.ownerNpc||node?.userData?.species||null,reason}}
function rememberRenderExile(scene,record){const scope=globalThis;scope.__AWTSMOOS_RENDER_EXILE_TRACE__||=[];scope.__AWTSMOOS_RENDER_EXILE_TRACE__.push({...record,at:Date.now()});scope.__AWTSMOOS_RENDER_EXILE_TRACE__=scope.__AWTSMOOS_RENDER_EXILE_TRACE__.slice(-80);scene&&(scene.userData ||= {},scene.userData.renderExileTrace=scope.__AWTSMOOS_RENDER_EXILE_TRACE__)}
function purgeWorkerHostileRenderNodes(scene){let hidden=0;scene?.traverse?.(node=>{if(!hostile(node))return;if(node.visible!==false){hidden++;rememberRenderExile(scene,renderNodeRecord(node,'unsupported-worker-render-node'))}node.visible=false;node.frustumCulled=true;node.renderOrder=-999;node.userData||={};Object.assign(node.userData,{workerRenderExiled:true,skipRaycast:true,skipOctree:true,noOctree:true})});return hidden}
function purgeRenderHazards(self,frame){const due=frame<=12||frame%15===0||self.__renderTreeDirty;if(!due)return 0;const exiled=purgeWorkerHostileRenderNodes(self.scene);self.__renderTreeDirty=false;if(exiled)self.__lastRenderHazardPurge={frame,exiled,at:Date.now(),trace:globalThis.__AWTSMOOS_RENDER_EXILE_TRACE__?.slice(-8)||[]};return exiled}
function badNodes(scene,limit=8){const out=[];scene?.traverse?.(node=>{if(out.length>=limit)return;if(okVec(node.position)&&okVec(node.scale)&&okVec(node.rotation)&&okMat(node.matrix)&&okMat(node.matrixWorld))return;out.push({name:node?.nivraAwtsmoos?.name||node?.name||'(unnamed)',type:node.type,position:vcopy(node.position),scale:vcopy(node.scale)})});return out}
function exileBadRenderNodes(scene){let count=0;scene?.traverse?.(node=>{if(okVec(node.position)&&okVec(node.scale)&&okVec(node.rotation)&&okMat(node.matrix)&&okMat(node.matrixWorld))return;node.visible=false;node.userData||={};node.userData.awtsmoosRenderExiled=true;count++});return count}
function stopRenderLoop(self){self.__renderPausedAfterFatal=true;self.pulsator?.stop?.();self.renderer?.setAnimationLoop?.(null)}
function handleRenderFailure(self,frame,error){if(self.__renderPausedAfterFatal)return;const compact=compactError(error),nodes=badNodes(self.scene),exiled=exileBadRenderNodes(self.scene)+purgeWorkerHostileRenderNodes(self.scene);stopRenderLoop(self);console.error('B"H | AWTSMOOS_RENDER_FATAL_ONCE',{frame,...compact,badNodes:nodes,exiled,paused:true});globalThis.postMessage?.({type:'awtsmoosRenderFatal',payload:{frame,...compact,badNodes:nodes,exiled}})}
function warnOnce(self,n,error){self.__entityLoopWarnings||=new Set();const key=`${n?.type}:${n?.name}:${error?.message||error}`;if(self.__entityLoopWarnings.size>=WARN_LIMIT||self.__entityLoopWarnings.has(key))return;self.__entityLoopWarnings.add(key);console.warn('B"H | ENTITY_LOOP_FAILED_ONCE',{type:n?.type,name:n?.name,...compactError(error)})}
function confirmRenderedFrame(self,frame,eye){if(!self.__firstRenderConfirmed){self.__firstRenderConfirmed=true;safeRenderTrace('heesHawvoos:first_render_confirmed',{frame,sceneChildren:self.scene?.children?.length||0,cameraPosition:vcopy(eye.position)});self.ayshPeula?.('rendered first time')}const t=now();if(!self.__lastFinalReadySignalAt||t-self.__lastFinalReadySignalAt>READY_SIGNAL_MS){self.__lastFinalReadySignalAt=t;signalWorldFinalReady(self,{frame})}}
function rememberFrame(payload){globalThis.__AWTSMOOS_WORKER_FRAME_HISTORY__||=[];globalThis.__AWTSMOOS_WORKER_FRAME_HISTORY__.push(payload);globalThis.__AWTSMOOS_WORKER_FRAME_HISTORY__=globalThis.__AWTSMOOS_WORKER_FRAME_HISTORY__.slice(-240)}
function reportWorkerFps(self,dt,frame){
 self.__workerFpsStats||={at:0,frameAt:0,frames:0,dtTotal:0,dtMax:0,wallTotal:0,wallMax:0,stageTotals:{},stageMax:{}};
 const s=self.__workerFpsStats,t=Date.now();
 if(s.frameAt){const wall=(t-s.frameAt)/1000;s.wallTotal+=wall;s.wallMax=Math.max(s.wallMax,wall)}
 s.frameAt=t;s.frames++;s.dtTotal+=dt;s.dtMax=Math.max(s.dtMax,dt);
 for(const[k,v]of Object.entries(self.__lastFrameStages||{})){s.stageTotals[k]=(s.stageTotals[k]||0)+Number(v||0);s.stageMax[k]=Math.max(s.stageMax[k]||0,Number(v||0))}
 if(!s.at)s.at=t;if(t-s.at<1000)return;
 const div=Math.max(1,s.frames),info=self.renderer?.info?.render||{},avgStages=Object.fromEntries(Object.entries(s.stageTotals).map(([k,v])=>[k,Math.round(v/div*10)/10]));
 const payload={fps:Math.round(s.frames/Math.max(.001,(t-s.at)/1000)),avgFrameMs:Math.round(s.dtTotal/div*10000)/10,maxFrameMs:Math.round(s.dtMax*10000)/10,avgWallFrameMs:Math.round(s.wallTotal/Math.max(1,s.frames-1)*10000)/10,maxWallFrameMs:Math.round(s.wallMax*10000)/10,renderCostMs:Math.round(Number(self.__lastRenderCostMs||0)*10)/10,updateCostMs:Math.round(Number(self.__lastUpdateCostMs||0)*10)/10,stages:self.__lastFrameStages||null,avgStages,stageMax:s.stageMax,entityStats:self.__lastEntityFrameStats||null,playerPhysicsStats:self.__lastPlayerPhysicsStats||null,playerAnimationStats:self.__lastPlayerAnimationStats||null,octreeStats:self.__lastOctreeFocusStats||null,partitionStats:self.__AWTSMOOS_DYNAMIC_PARTITION_STATS__||null,renderBudget:self.__renderBudgetDiag||null,adaptiveResolution:self.__adaptiveRenderResolutionDiag||null,renderInfo:{calls:Number(info.calls||0),triangles:Number(info.triangles||0),points:Number(info.points||0),lines:Number(info.lines||0)},pixelRatio:Number(self.renderer?.getPixelRatio?.()||0)||null,frame,source:'worker-gameplay-moving-loop-bh14-player-stage-timing'};
 s.frames=s.dtTotal=s.dtMax=s.wallTotal=s.wallMax=0;s.stageTotals={};s.stageMax={};s.at=t;
 globalThis.__AWTSMOOS_WORKER_GAMEPLAY_FPS__=payload;rememberFrame(payload);globalThis.postMessage?.({type:'worker_gameplay_fps',payload})
}
function isPlayerActor(n,self){return Boolean(n&&(n===self.chossid||n===self.player||typeKey(n)==='chossid'))}
function classifyNivrayim(self){const t=now(),c=self.__nivraClassCache;if(c&&t-c.at<NIVRA_CACHE_MS)return c;const player=[],live=[],simple=[],tickers=[],staticSkipped=[];for(const n of self.nivrayim||[]){if(!n?.isReady||!n?.heesHawveh||typeof n.heesHawvoos!=='function')continue;if(isPlayerActor(n,self)){player.push(n);continue}if(staticVisual(n,self)){staticSkipped.push(n);continue}if(typeKey(n)==='livingregionticker'){tickers.push(n);continue}if(isSimpleNpc(n)){simple.push(n);continue}live.push(n)}return self.__nivraClassCache={at:t,player,live,simple,tickers,staticSkipped}}
export default class HeesHawvoosManager{
 async heesHawvoos(){const self=this;let frame=0;ensureWorkerWindowVessel();safeRenderTrace('heesHawvoos:ignite',{hasRenderer:Boolean(self.renderer),hasScene:Boolean(self.scene),nivrayim:self.nivrayim?.length||0});this.updateStep=dt=>{if(self.__renderPausedAfterFatal)return;const start=now(),stages={};frame++;let t=now();try{this.updateSystems(self,dt)}catch(e){if(frame<=3)console.error('B"H | HEES_SYSTEM_FAILED_ONCE',compactError(e))}stages.systems=Math.round((now()-t)*10)/10;t=now();try{this.updateOctreeFoci(self)}catch(e){if(frame<=3)console.error('B"H | HEES_OCTREE_FAILED_ONCE',compactError(e))}stages.octree=Math.round((now()-t)*10)/10;t=now();try{this.updateNivrayim(self,dt)}catch(e){if(frame<=3)console.error('B"H | HEES_ENTITY_LOOP_FAILED_ONCE',compactError(e))}stages.nivrayim=Math.round((now()-t)*10)/10;t=now();try{const c=self.combatManager,hot=Boolean(c?.projectiles?.projectiles?.length);if(hot)c.update?.(dt);else this.runEvery(self,'combat',.25,dt,step=>c?.update?.(step))}catch(e){if(frame<=3)console.error('B"H | HEES_COMBAT_FAILED_ONCE',compactError(e))}stages.combat=Math.round((now()-t)*10)/10;t=now();try{self.ayin?.update?.(dt)}catch(e){if(frame<=3)console.error('B"H | HEES_CAMERA_FAILED_ONCE',compactError(e))}stages.camera=Math.round((now()-t)*10)/10;t=now();purgeRenderHazards(self,frame);stages.purge=Math.round((now()-t)*10)/10;const rs=now();this.renderFrame(self,frame);self.__lastRenderCostMs=now()-rs;stages.render=Math.round(self.__lastRenderCostMs*10)/10;self.__lastUpdateCostMs=now()-start-self.__lastRenderCostMs;stages.total=Math.round((now()-start)*10)/10;try{maybeRefreshRenderBudgetDiagnostics(self);applyAdaptiveRenderResolution(self,stages)}catch(e){if(frame<=3)console.warn('B"H | RENDER_BUDGET_DIAG_FAILED_ONCE',compactError(e))}self.__lastFrameStages=stages;reportWorkerFps(self,Number(dt)||1/60,frame)};this.pulsator=new UniversePulsator(this);this.pulsator.ignite()}
 runEvery(self,key,interval,dt,callback){const bag=self.__frameBudgetAccumulators||={},slot=bag[key]||={acc:0};self.__frameBudgetAccumulators=bag;slot.acc+=Math.min(.05,Number(dt)||1/60);if(slot.acc<interval)return false;const step=Math.min(.25,slot.acc);slot.acc=0;callback(step);return true}
 updateSystems(self,dt){self.shlichusHandler?.update?.(dt);this.runEvery(self,'placement',.1,dt,step=>self.placementManager?.update?.(step));this.runEvery(self,'environment',.35,dt,step=>self.environment?.update?.(step))}
 focusCandidates(self){const cache=self.__octreeFocusCache,t=now();if(cache&&t-cache.at<800)return cache.list;const p=self.chossid||self.player;const list=(self.nivrayim||[]).filter(n=>n&&n!==p&&!isSimpleNpc(n)&&n.velocity&&n.mesh?.position&&n.onFloor!==undefined&&n.isReady&&!n.__spikeColliderDisabled&&shouldDriveOctreeFocus(n,self));self.__octreeFocusCache={at:t,list};return list}
 updateOctreeFoci(self){if(!self.worldOctree)return;const t=now(),p=self.chossid||self.player,pos=p?.mesh?.position,last=self.__lastOctreeFocusPosition,movedSq=pos&&last?((pos.x-last.x)**2+(pos.y-last.y)**2+(pos.z-last.z)**2):Infinity,velSq=p?.velocity?.lengthSq?.()||0;const stale=t-(self.__lastOctreeFocusAt||0);if(self.__lastOctreeFocusAt&&movedSq<.09&&velSq<.01){self.__lastOctreeFocusStats={at:Date.now(),foci:0,movedSq:Math.round(movedSq*1000)/1000,skipped:true,reason:'still-player-no-octree-update'};return}if(self.__lastOctreeFocusAt&&stale<650&&movedSq<1.2){self.__lastOctreeFocusStats={at:Date.now(),foci:0,movedSq:Math.round(movedSq*1000)/1000,skipped:true,reason:'throttled'};return}const foci=[];if(p?.mesh?.position&&p?.velocity&&!p.__spikeColliderDisabled)foci.push({position:p.mesh.position,velocity:p.velocity});if(!foci.length)return;self.worldOctree.update(foci,null);self.__lastOctreeFocusAt=t;if(pos)self.__lastOctreeFocusPosition={x:pos.x,y:pos.y,z:pos.z};self.__lastOctreeFocusStats={at:Date.now(),foci:foci.length,movedSq:Math.round(movedSq*1000)/1000,throttleMs:650,seal:'player-only-octree-focus-bh1'}}
 updateSimpleNpcs(self,classes,dt,stats){let ticked=0;for(let i=0;i<classes.simple.length;i++){const n=classes.simple[i],interval=nearPlayer(n,self)?2.5:12;const did=ticked<1&&this.runEvery(self,`simpleNpc:${n.name||i}`,interval,dt,step=>{try{n.heesHawvoos(step);stats.updated++;stats.simpleNpcTicked++;ticked++}catch(e){stats.errors++;warnOnce(self,n,e)}});if(!did)stats.simpleNpcSkipped++}}
 updateNivrayim(self,dt){const partition=partitionFor(self),classes=classifyNivrayim(self),stats={scanned:classes.live.length,updated:0,playerUpdated:0,tickers:classes.tickers.length,simpleNpcs:classes.simple.length,simpleNpcTicked:0,simpleNpcSkipped:0,skippedStatic:classes.staticSkipped.length,skippedPartition:0,budgetSkipped:0,noFrame:0,errors:0,cached:true,budget:NON_PLAYER_ENTITY_BUDGET};for(const n of classes.player){try{n.heesHawvoos(dt);hardGroundPlayer(self,n);stats.updated++;stats.playerUpdated++}catch(e){stats.errors++;warnOnce(self,n,e)}}this.updateSimpleNpcs(self,classes,dt,stats);for(const n of classes.tickers){this.runEvery(self,`ticker:${n.name||'living'}`,tickerInterval(n),dt,step=>{try{n.heesHawvoos(step);stats.updated++}catch(e){stats.errors++;warnOnce(self,n,e)}})}const live=classes.live;let index=self.__nivraRoundRobinIndex||0,used=0,visited=0;while(live.length&&visited<live.length&&used<NON_PLAYER_ENTITY_BUDGET){const n=live[index%live.length];index++;visited++;if(shouldPartitionNivra(n,self)&&!partition.shouldUpdate(n,self)){stats.skippedPartition++;continue}try{n.heesHawvoos(dt);stats.updated++;used++}catch(e){stats.errors++;warnOnce(self,n,e)}}stats.budgetSkipped=Math.max(0,live.length-visited)+Math.max(0,visited-used-stats.skippedPartition);self.__nivraRoundRobinIndex=live.length?index%live.length:0;self.__AWTSMOOS_DYNAMIC_PARTITION_STATS__=partition.stats;self.__lastEntityFrameStats=stats}
 renderFrame(self,frame){if(!self.renderer||!self.scene)return frame<=5&&safeRenderTrace('heesHawvoos:no_renderer_or_scene',{frame});const eye=self.activeCamera||self.ayin?.camera||null;if(!eye)return frame<=5&&safeRenderTrace('heesHawvoos:no_active_camera',{frame});try{ensureWorkerWindowVessel();const asyncRender=self.__useAsyncRenderFrames===true&&typeof self.renderer.renderAsync==='function';if(asyncRender&&self.__renderInFlight)return;const result=asyncRender?self.renderer.renderAsync(self.scene,eye):self.renderer.render(self.scene,eye);if(result?.then){self.__renderInFlight=true;result.then(()=>confirmRenderedFrame(self,frame,eye)).catch(e=>handleRenderFailure(self,frame,e)).finally(()=>{self.__renderInFlight=false})}else confirmRenderedFrame(self,frame,eye)}catch(e){handleRenderFailure(self,frame,e)}}
}
