// B"H
/** @file heesHawvoos.js @description Measured frame loop: named stages, static skips, and per-frame truth. */
import UniversePulsator from '../oyved/UniversePulsator.js?v=no-alert-perf-jump-20260701-bh9';
import RenderTrace from './canvas/RenderTrace.js?v=village-polish-20260612-bh811';
import { signalWorldFinalReady } from '../worlds/mitzvahWorld/runtime/WorldFinalReadySignal.js?v=zone-reality-20260614-bh817';
import { getDynamicActorPartition } from '../worlds/mitzvahWorld/runtime/DynamicActorPartition.js?v=awtsmoos-dynamic-partition-20260614-bh2';
const FOCUS_EPS = 0.0001, WARN_LIMIT = 10;
const VANITY = new Set(['LineSegments','Line','Points','AxesHelper','GridHelper','BoxHelper']);
const DYNAMIC = new Set(['interactiveNpc','customNpc','medabeir','mazik','enemy','animal','wildlife','chossid','livingregionticker','discoveryticker']);
const STATIC = new Set(['proceduralsky','proceduralterrain','villagepictureprop','villagetreefield','villageherotree','villagegrassfield','villagestonepath','villagebackdrop','villageskylayers','villagefencecollider','villagehousecollider','villagelightingrig','villagecamerapreset']);
const now = () => performance.now();
const typeKey = n => String(n?.type || n?.constructor?.name || '').toLowerCase();
const okNum = v => Number.isFinite(Number(v));
const okVec = v => !v || (okNum(v.x) && okNum(v.y) && okNum(v.z));
const okMat = m => !m?.elements || m.elements.every(okNum);
const vcopy = v => v ? { x:Number(v.x), y:Number(v.y), z:Number(v.z) } : null;
function ensureWorkerWindowVessel() { if (typeof globalThis.window !== 'undefined') return globalThis.window; try { Object.defineProperty(globalThis, 'window', { value:globalThis, configurable:true }); } catch { globalThis.window = globalThis; } globalThis.window.wowd ||= false; return globalThis.window; }
function compactError(e) { return { name:e?.name || 'Error', message:e?.message || String(e), stack:String(e?.stack || '').split('\n').slice(0, 5).join(' | ') }; }
function safeRenderTrace(name, data) { if (globalThis.__AWTSMOOS_RENDER_TRACE__ !== true) return; try { RenderTrace.speak(name, data); } catch (e) { console.warn('B"H | RENDER_TRACE_FAILED', { name, message:e?.message || String(e) }); } }
function budgetOf() { return globalThis?.__AWTSMOOS_PERFORMANCE_MODE__?.budget || {}; }
function partitionFor(self) { const b = budgetOf(); return getDynamicActorPartition(self).configure({ near:b.npcDistance || 48, mid:(b.npcDistance || 48) * 1.8, far:(b.treeDistance || 120) * 2.2 }); }
function hasMotion(n) { const m = n?.moving || {}; return Boolean(m.forward || m.backward || m.stridingLeft || m.stridingRight || m.turningLeft || m.turningRight || m.jump || n?.movingAutomatically || n?.navTarget || n?.currentPath || n?._isMoving || ((n?.velocity?.lengthSq?.() || 0) > FOCUS_EPS)); }
function shouldDriveOctreeFocus(n, self) { if (!n) return false; if (n === self.chossid || n === self.player || typeKey(n) === 'chossid') return true; return hasMotion(n); }
function shouldPartitionNivra(n, self) { if (!n || n === self.chossid || n === self.player || typeKey(n) === 'chossid') return false; const key = typeKey(n); return Boolean(n.mesh && (DYNAMIC.has(key) || n.userData?.wildlifeActor || n.isNpc || n.isEnemy)); }
function staticVisual(n, self) { if (!n || n === self.chossid || n === self.player) return false; if (n.forceEveryFrame || n.__awtsmoosNeedsFrame || n.userData?.forceEveryFrame) return false; if (hasMotion(n)) return false; const key = typeKey(n); return STATIC.has(key) || (n.userData?.visualOnly && !DYNAMIC.has(key)); }
function hostile(node) { if (!node) return false; if (node.isLine || node.isLineSegments || node.isPoints || VANITY.has(node.type)) return true; const gt = String(node.geometry?.type || ''); return gt.includes('BufferGeometry') && (node.material?.isLineBasicMaterial || node.material?.isPointsMaterial); }
function purgeWorkerHostileRenderNodes(scene) { let hidden = 0; scene?.traverse?.(node => { if (!hostile(node)) return; if (node.visible !== false) hidden++; node.visible = false; node.frustumCulled = true; node.renderOrder = -999; node.userData ||= {}; node.userData.workerRenderExiled = true; }); return hidden; }
function badNodes(scene, limit = 8) { const out = []; scene?.traverse?.(node => { if (out.length >= limit) return; if (okVec(node.position) && okVec(node.scale) && okVec(node.rotation) && okMat(node.matrix) && okMat(node.matrixWorld)) return; out.push({ name:node?.nivraAwtsmoos?.name || node?.name || '(unnamed)', type:node.type, position:vcopy(node.position), scale:vcopy(node.scale) }); }); return out; }
function exileBadRenderNodes(scene) { let count = 0; scene?.traverse?.(node => { if (okVec(node.position) && okVec(node.scale) && okVec(node.rotation) && okMat(node.matrix) && okMat(node.matrixWorld)) return; node.visible = false; node.userData ||= {}; node.userData.awtsmoosRenderExiled = true; count++; }); return count; }
function stopRenderLoop(self) { self.__renderPausedAfterFatal = true; self.pulsator?.stop?.(); self.renderer?.setAnimationLoop?.(null); }
function handleRenderFailure(self, frame, error) { if (self.__renderPausedAfterFatal) return; const compact = compactError(error), nodes = badNodes(self.scene), exiled = exileBadRenderNodes(self.scene) + purgeWorkerHostileRenderNodes(self.scene); stopRenderLoop(self); console.error('B"H | AWTSMOOS_RENDER_FATAL_ONCE', { frame, ...compact, badNodes:nodes, exiled, paused:true }); globalThis.postMessage?.({ type:'awtsmoosRenderFatal', payload:{ frame, ...compact, badNodes:nodes, exiled } }); }
function warnOnce(self, n, error) { self.__entityLoopWarnings ||= new Set(); const key = `${n?.type}:${n?.name}:${error?.message || error}`; if (self.__entityLoopWarnings.size >= WARN_LIMIT || self.__entityLoopWarnings.has(key)) return; self.__entityLoopWarnings.add(key); console.warn('B"H | ENTITY_LOOP_FAILED_ONCE', { type:n?.type, name:n?.name, ...compactError(error) }); }
function confirmRenderedFrame(self, frame, eye) { if (!self.__firstRenderConfirmed) { self.__firstRenderConfirmed = true; safeRenderTrace('heesHawvoos:first_render_confirmed', { frame, sceneChildren:self.scene?.children?.length || 0, cameraPosition:vcopy(eye.position) }); self.ayshPeula?.('rendered first time'); } signalWorldFinalReady(self, { frame }); }
function renderLayerStats(scene) { const roots = []; const region = scene?.getObjectByName?.('AWTSMOOS_LIVING_REGION_FULLY_GROUNDED_RUNTIME'); if (region?.children?.length) roots.push(...region.children); else if (scene?.children?.length) roots.push(...scene.children); return roots.map(root => { const s = { name:root.name || root.type || 'layer', meshes:0, instanced:0, instances:0, visible:root.visible !== false, triangles:0 }; root.traverse?.(o => { if (o.visible === false) return; if (o.isMesh || o.isInstancedMesh || o.isSkinnedMesh) { s.meshes++; if (o.isInstancedMesh) { s.instanced++; s.instances += Number(o.count || 0); } const g = o.geometry, tris = g?.index ? g.index.count / 3 : (g?.attributes?.position?.count || 0) / 3; s.triangles += Math.round(tris * Math.max(1, Number(o.count || 1))); } }); return s; }).sort((a,b) => b.triangles - a.triangles || b.meshes - a.meshes).slice(0, 10); }
function rememberFrame(payload) { globalThis.__AWTSMOOS_WORKER_FRAME_HISTORY__ ||= []; globalThis.__AWTSMOOS_WORKER_FRAME_HISTORY__.push(payload); globalThis.__AWTSMOOS_WORKER_FRAME_HISTORY__ = globalThis.__AWTSMOOS_WORKER_FRAME_HISTORY__.slice(-180); }
function reportWorkerFps(self, dt, frame) { self.__workerFpsStats ||= { at:0, frameAt:0, frames:0, dtTotal:0, dtMax:0, wallTotal:0, wallMax:0 }; const s = self.__workerFpsStats, t = Date.now(); if (s.frameAt) { const wall = (t - s.frameAt) / 1000; s.wallTotal += wall; s.wallMax = Math.max(s.wallMax, wall); } s.frameAt = t; s.frames++; s.dtTotal += dt; s.dtMax = Math.max(s.dtMax, dt); if (!s.at) s.at = t; if (t - s.at < 1000) return; const seconds = Math.max(.001, (t - s.at) / 1000), info = self.renderer?.info?.render || {}; const payload = { fps:Math.round(s.frames / seconds), avgFrameMs:Math.round((s.dtTotal / Math.max(1, s.frames)) * 10000) / 10, maxFrameMs:Math.round(s.dtMax * 10000) / 10, avgWallFrameMs:Math.round((s.wallTotal / Math.max(1, s.frames - 1)) * 10000) / 10, maxWallFrameMs:Math.round(s.wallMax * 10000) / 10, renderCostMs:Math.round(Number(self.__lastRenderCostMs || 0) * 10) / 10, updateCostMs:Math.round(Number(self.__lastUpdateCostMs || 0) * 10) / 10, stages:self.__lastFrameStages || null, entityStats:self.__lastEntityFrameStats || null, octreeStats:self.__lastOctreeFocusStats || null, partitionStats:self.__AWTSMOOS_DYNAMIC_PARTITION_STATS__ || null, renderInfo:{ calls:Number(info.calls || 0), triangles:Number(info.triangles || 0), points:Number(info.points || 0), lines:Number(info.lines || 0) }, layerStats:renderLayerStats(self.scene), pixelRatio:Number(self.renderer?.getPixelRatio?.() || 0) || null, frame, source:'worker-gameplay-render-loop-bh11' }; s.frames = s.dtTotal = s.dtMax = s.wallTotal = s.wallMax = 0; s.at = t; globalThis.__AWTSMOOS_WORKER_GAMEPLAY_FPS__ = payload; rememberFrame(payload); globalThis.postMessage?.({ type:'worker_gameplay_fps', payload }); }
export default class HeesHawvoosManager {
  async heesHawvoos() { const self = this; let frame = 0; ensureWorkerWindowVessel(); safeRenderTrace('heesHawvoos:ignite', { hasRenderer:Boolean(self.renderer), hasScene:Boolean(self.scene), nivrayim:self.nivrayim?.length || 0 }); this.updateStep = dt => { if (self.__renderPausedAfterFatal) return; const start = now(), stages = {}; frame++; let t = now(); try { this.updateSystems(self, dt); } catch (e) { if (frame <= 3) console.error('B"H | HEES_SYSTEM_FAILED_ONCE', compactError(e)); } stages.systems = Math.round((now() - t) * 10) / 10; t = now(); try { this.updateOctreeFoci(self); } catch (e) { if (frame <= 3) console.error('B"H | HEES_OCTREE_FAILED_ONCE', compactError(e)); } stages.octree = Math.round((now() - t) * 10) / 10; t = now(); try { this.updateNivrayim(self, dt); } catch (e) { if (frame <= 3) console.error('B"H | HEES_ENTITY_LOOP_FAILED_ONCE', compactError(e)); } stages.nivrayim = Math.round((now() - t) * 10) / 10; t = now(); try { const c = self.combatManager, hot = Boolean(c?.projectiles?.projectiles?.length); if (hot) c.update?.(dt); else this.runEvery(self, 'combat', .18, dt, step => c?.update?.(step)); } catch (e) { if (frame <= 3) console.error('B"H | HEES_COMBAT_FAILED_ONCE', compactError(e)); } stages.combat = Math.round((now() - t) * 10) / 10; t = now(); try { self.ayin?.update?.(dt); } catch (e) { if (frame <= 3) console.error('B"H | HEES_CAMERA_FAILED_ONCE', compactError(e)); } stages.camera = Math.round((now() - t) * 10) / 10; t = now(); if (frame === 1 || self.__renderTreeDirty) { purgeWorkerHostileRenderNodes(self.scene); self.__renderTreeDirty = false; } stages.purge = Math.round((now() - t) * 10) / 10; const rs = now(); this.renderFrame(self, frame); self.__lastRenderCostMs = now() - rs; stages.render = Math.round(self.__lastRenderCostMs * 10) / 10; self.__lastUpdateCostMs = now() - start - self.__lastRenderCostMs; stages.total = Math.round((now() - start) * 10) / 10; self.__lastFrameStages = stages; reportWorkerFps(self, Number(dt) || 1 / 60, frame); }; this.pulsator = new UniversePulsator(this); this.pulsator.ignite(); }
  runEvery(self, key, interval, dt, callback) { const bag = self.__frameBudgetAccumulators ||= {}, slot = bag[key] ||= { acc:0 }; slot.acc += Math.min(.05, Number(dt) || 1 / 60); if (slot.acc < interval) return false; const step = Math.min(.25, slot.acc); slot.acc = 0; callback(step); return true; }
  updateSystems(self, dt) { self.shlichusHandler?.update?.(dt); self.placementManager?.update?.(dt); this.runEvery(self, 'environment', .16, dt, step => self.environment?.update?.(step)); }
  focusCandidates(self) { const cache = self.__octreeFocusCache; const t = now(); if (cache && t - cache.at < 500) return cache.list; const p = self.chossid || self.player; const list = (self.nivrayim || []).filter(n => n && n !== p && n.velocity && n.mesh?.position && n.onFloor !== undefined && n.isReady && !n.__spikeColliderDisabled && shouldDriveOctreeFocus(n, self)); self.__octreeFocusCache = { at:t, list }; return list; }
  updateOctreeFoci(self) { if (!self.worldOctree) return; const t = now(), p = self.chossid || self.player, pos = p?.mesh?.position, last = self.__lastOctreeFocusPosition, movedSq = pos && last ? ((pos.x-last.x)**2 + (pos.y-last.y)**2 + (pos.z-last.z)**2) : Infinity; if (self.__lastOctreeFocusAt && t - self.__lastOctreeFocusAt < 120 && movedSq < .09) return; const foci = []; if (p?.mesh?.position && p?.velocity && !p.__spikeColliderDisabled) foci.push({ position:p.mesh.position, velocity:p.velocity }); for (const n of this.focusCandidates(self)) foci.push({ position:n.mesh.position, velocity:n.velocity }); if (!foci.length) return; self.worldOctree.update(foci, null); self.__lastOctreeFocusAt = t; if (pos) self.__lastOctreeFocusPosition = { x:pos.x, y:pos.y, z:pos.z }; self.__lastOctreeFocusStats = { at:Date.now(), foci:foci.length, movedSq:Math.round(movedSq * 1000) / 1000 }; }
  updateNivrayim(self, dt) { const partition = partitionFor(self), stats = { scanned:0, updated:0, skippedStatic:0, skippedPartition:0, noFrame:0, errors:0 }; for (const n of self.nivrayim || []) { stats.scanned++; if (!n?.isReady || !n?.heesHawveh || typeof n.heesHawvoos !== 'function') { stats.noFrame++; continue; } if (staticVisual(n, self)) { stats.skippedStatic++; continue; } if (typeKey(n) === 'livingregionticker') { this.runEvery(self, `ticker:${n.name || 'living'}`, .22, dt, step => { try { n.heesHawvoos(step); } catch (e) { stats.errors++; warnOnce(self, n, e); } }); stats.updated++; continue; } if (shouldPartitionNivra(n, self) && !partition.shouldUpdate(n, self)) { stats.skippedPartition++; continue; } try { n.heesHawvoos(dt); stats.updated++; } catch (e) { stats.errors++; warnOnce(self, n, e); } } self.__AWTSMOOS_DYNAMIC_PARTITION_STATS__ = partition.stats; self.__lastEntityFrameStats = stats; }
  renderFrame(self, frame) { if (!self.renderer || !self.scene) return frame <= 5 && safeRenderTrace('heesHawvoos:no_renderer_or_scene', { frame }); const eye = self.activeCamera || self.ayin?.camera || null; if (!eye) return frame <= 5 && safeRenderTrace('heesHawvoos:no_active_camera', { frame }); try { ensureWorkerWindowVessel(); const asyncRender = self.__useAsyncRenderFrames === true && typeof self.renderer.renderAsync === 'function'; if (asyncRender && self.__renderInFlight) return; const result = asyncRender ? self.renderer.renderAsync(self.scene, eye) : self.renderer.render(self.scene, eye); if (result?.then) { self.__renderInFlight = true; result.then(() => confirmRenderedFrame(self, frame, eye)).catch(e => handleRenderFailure(self, frame, e)).finally(() => { self.__renderInFlight = false; }); } else confirmRenderedFrame(self, frame, eye); } catch (e) { handleRenderFailure(self, frame, e); } }
}
