// B"H
// Boruch Hashem
// Blessed is He
/** Shader nodes expose physical surface, volume, emission, and displacement closures. */

import { input, node, output } from "./nodeDefinitionHelpers.js";

export const MATERIAL_SHADER_NODES = Object.freeze([
	node("material.shader.principled", "Principled Surface", [input("base-color", "color", [0.8, 0.8, 0.8, 1]), input("metallic", "factor", 0), input("roughness", "factor", 0.5), input("ior", "float", 1.45), input("alpha", "factor", 1), input("normal", "normal"), input("weight", "factor", 1), input("subsurface-weight", "factor", 0), input("subsurface-radius", "vector", [1, 0.2, 0.1]), input("coat-weight", "factor", 0), input("coat-roughness", "factor", 0.03), input("sheen-weight", "factor", 0), input("emission-color", "color", [0, 0, 0, 1]), input("emission-strength", "float", 0), input("thin-film-thickness", "distance", 0), input("thin-film-ior", "float", 1.33)], [output("surface", "shader.surface")], { category: "surface", requiredCapabilities: ["principled-surface"] }),
	node("material.shader.diffuse", "Diffuse Surface", [input("color", "color"), input("roughness", "factor", 0), input("normal", "normal"), input("weight", "factor", 1)], [output("surface", "shader.surface")], { category: "surface" }),
	node("material.shader.glossy", "Glossy Surface", [input("color", "color"), input("roughness", "factor", 0.2), input("normal", "normal"), input("weight", "factor", 1)], [output("surface", "shader.surface")], { category: "surface" }),
	node("material.shader.glass", "Glass Surface", [input("color", "color"), input("roughness", "factor", 0), input("ior", "float", 1.45), input("normal", "normal"), input("weight", "factor", 1)], [output("surface", "shader.surface")], { category: "surface", requiredCapabilities: ["transmission"] }),
	node("material.shader.refraction", "Refraction Surface", [input("color", "color"), input("roughness", "factor", 0), input("ior", "float", 1.45), input("normal", "normal"), input("weight", "factor", 1)], [output("surface", "shader.surface")], { category: "surface", requiredCapabilities: ["transmission"] }),
	node("material.shader.translucent", "Translucent Surface", [input("color", "color"), input("normal", "normal"), input("weight", "factor", 1)], [output("surface", "shader.surface")], { category: "surface" }),
	node("material.shader.transparent", "Transparent Surface", [input("color", "color"), input("weight", "factor", 1)], [output("surface", "shader.surface")], { category: "surface" }),
	node("material.shader.sheen", "Sheen Surface", [input("color", "color"), input("roughness", "factor", 0.5), input("normal", "normal"), input("weight", "factor", 1)], [output("surface", "shader.surface")], { category: "surface", requiredCapabilities: ["microfiber-sheen"] }),
	node("material.shader.toon", "Toon Surface", [input("color", "color"), input("size", "factor", 0.5), input("smooth", "factor", 0), input("normal", "normal"), input("weight", "factor", 1)], [output("surface", "shader.surface")], { category: "surface" }),
	node("material.shader.subsurface", "Subsurface Scattering", [input("color", "color"), input("scale", "distance", 1), input("radius", "vector", [1, 0.2, 0.1]), input("ior", "float", 1.4), input("anisotropy", "factor", 0), input("normal", "normal"), input("weight", "factor", 1)], [output("surface", "shader.surface")], { category: "surface", requiredCapabilities: ["subsurface-scattering"] }),
	node("material.shader.hair-principled", "Principled Hair", [input("color", "color"), input("melanin", "factor", 0.5), input("melanin-redness", "factor", 0.5), input("tint", "color"), input("roughness", "factor", 0.3), input("radial-roughness", "factor", 0.3), input("coat", "factor", 0), input("ior", "float", 1.55), input("random-color", "factor", 0), input("random-roughness", "factor", 0), input("random", "factor", 0)], [output("surface", "shader.surface")], { category: "hair", requiredCapabilities: ["hair-bsdf"] }),
	node("material.shader.emission", "Emission", [input("color", "color"), input("strength", "float", 1), input("weight", "factor", 1)], [output("surface", "shader.surface"), output("emission", "shader.emission")], { category: "emission" }),
	node("material.shader.holdout", "Holdout", [input("weight", "factor", 1)], [output("surface", "shader.surface")], { category: "surface" }),
	node("material.shader.mix-surface", "Mix Surface", [input("factor", "factor", 0.5), input("a", "shader.surface"), input("b", "shader.surface")], [output("surface", "shader.surface")], { category: "closure" }),
	node("material.shader.add-surface", "Add Surface", [input("a", "shader.surface"), input("b", "shader.surface")], [output("surface", "shader.surface")], { category: "closure" }),
	node("material.shader.volume-principled", "Principled Volume", [input("density", "float", 1), input("color", "color"), input("temperature", "temperature", 1000), input("blackbody-intensity", "float", 0), input("anisotropy", "factor", 0), input("emission-color", "color"), input("emission-strength", "float", 0)], [output("volume", "shader.volume")], { category: "volume", requiredCapabilities: ["heterogeneous-volume"] }),
	node("material.shader.volume-absorption", "Volume Absorption", [input("color", "color"), input("density", "float", 1)], [output("volume", "shader.volume")], { category: "volume" }),
	node("material.shader.volume-scatter", "Volume Scatter", [input("color", "color"), input("density", "float", 1), input("anisotropy", "factor", 0)], [output("volume", "shader.volume")], { category: "volume" }),
	node("material.shader.mix-volume", "Mix Volume", [input("factor", "factor", 0.5), input("a", "shader.volume"), input("b", "shader.volume")], [output("volume", "shader.volume")], { category: "closure" }),
	node("material.shader.displacement", "Displacement", [input("height", "float"), input("midlevel", "float", 0.5), input("scale", "float", 1), input("normal", "normal")], [output("displacement", "shader.displacement")], { category: "displacement" }),
	node("material.shader.vector-displacement", "Vector Displacement", [input("vector", "vector"), input("midlevel", "float", 0.5), input("scale", "float", 1)], [output("displacement", "shader.displacement")], { category: "displacement" }),
	node("material.shader.thin-film", "Thin Film", [input("thickness", "distance", 400), input("ior", "float", 1.33), input("base-ior", "float", 1.5), input("normal", "normal")], [output("color", "color"), output("factor", "factor")], { category: "optics", requiredCapabilities: ["thin-film-interference"] })
]);
