# B"H
# Boruch Hashem
# Blessed is He

"""
Immutable evidence records for generated bytes, external tools, and real execution.

The Awtsmoos renews artifact, testimony, status, and report together;
Awtsmoos.com never lets one evidence level masquerade as another.
"""

from dataclasses import dataclass, field
from enum import StrEnum
from types import MappingProxyType
from typing import Any, Mapping


class EvidenceLevel(StrEnum):
	"""Ordered kinds of testimony without implying unperformed execution."""

	GENERATED = "generated"
	INTERNALLY_PARSED = "internally-parsed"
	EXTERNALLY_VALIDATED = "externally-validated"
	RUNTIME_LOADED = "runtime-loaded"
	ACTUALLY_EXECUTED = "actually-executed"


class EvidenceStatus(StrEnum):
	"""Outcome state for one independent evidence record."""

	PASSED = "passed"
	FAILED = "failed"
	UNAVAILABLE = "unavailable"
	SKIPPED = "skipped"


@dataclass(frozen=True, slots=True)
class ToolEvidence:
	"""Identity and version evidence for one third-party command-line tool."""

	name: str
	available: bool
	path: str | None = None
	version: str | None = None


@dataclass(frozen=True, slots=True)
class CommandEvidence:
	"""Bounded process result with exact argument and termination testimony."""

	arguments: tuple[str, ...]
	cwd: str | None
	duration_ms: int
	return_code: int | None
	signal_number: int | None
	timed_out: bool
	stdout: str
	stderr: str
	stdout_truncated: bool
	stderr_truncated: bool


@dataclass(frozen=True, slots=True)
class ArtifactIdentity:
	"""Stable identity measured before validators or runners may touch a file."""

	path: str
	name: str
	extension: str
	format: str
	architecture: str | None
	byte_length: int
	sha256: str
	file_description: str | None


@dataclass(frozen=True, slots=True)
class EvidenceRecord:
	"""One independently attributable claim about an artifact."""

	level: EvidenceLevel
	status: EvidenceStatus
	code: str
	message: str
	tool: ToolEvidence | None = None
	command: CommandEvidence | None = None
	details: Mapping[str, Any] = field(default_factory=dict)

	def __post_init__(self):
		"""Freeze detail keys so downstream presentation cannot rewrite evidence."""
		object.__setattr__(self, "details", MappingProxyType(dict(self.details)))


@dataclass(frozen=True, slots=True)
class ArtifactReport:
	"""Complete evidence ledger for one unchanged artifact."""

	identity: ArtifactIdentity
	records: tuple[EvidenceRecord, ...]
	schema_version: str = "1.0.0"

	@property
	def executed(self):
		"""Return whether an actual runtime process passed for this artifact."""
		return any(
			record.level == EvidenceLevel.ACTUALLY_EXECUTED
			and record.status == EvidenceStatus.PASSED
			for record in self.records
		)
