// B"H
import * as THREE from '/games/scripts/build/three.module.js';
export default {
  needs: { energy: 100, hunger: 0, social: 100, wealth: 0 }, currentActionState: "IDLE", targetEntity: null, navTarget: null, lastDecisionTime: 0, decisionInterval: 2.0,
  updateBrain(dt) { if (!this.isReady || !this.mesh) return; this.updateNeeds(dt); const now = this.olam.clock.getElapsedTime(); if (now - this.lastDecisionTime > this.decisionInterval) { this.makeDecision(); this.lastDecisionTime = now; } this.executeState(dt); },
  updateNeeds(dt) { const moveCost = this.velocity.lengthSq() > .1 ? 2 : .5; this.needs.energy = Math.max(0, this.needs.energy - moveCost * dt); this.needs.hunger = Math.min(100, this.needs.hunger + dt); this.needs.social = Math.max(0, this.needs.social - .5 * dt); },
  makeDecision() { const time = this.olam.environment ? this.olam.environment.gameTime : 12, isNight = time < 6 || time > 20; if (isNight || this.needs.energy < 10) return this.setDecision("SLEEP", this.findHome()); if (this.needs.hunger > 80) return this.setDecision("EAT", this.findFoodSource()); if (time >= 8 && time <= 18 && this.needs.wealth < 50) return this.setDecision("WORK", this.findWorkplace()); if (Math.random() < .1 && this.needs.energy > 30) return this.setDecision("BUILD", this.getRandomPoint()); if (this.needs.social < 30) { const friend = this.findNearestSoul(); if (friend) { this.targetEntity = friend; return this.setDecision("TALK", friend.mesh.position); } } if (this.currentActionState === "IDLE" || Math.random() < .1) this.setDecision("WANDER", this.getRandomPoint()); },
  setDecision(state, target) { if (this.currentActionState === state && this.navTarget) return; this.currentActionState = state; this.navTarget = target; },
  executeState(dt) { if (!this.navTarget) return; const dist = this.mesh.position.distanceTo(this.navTarget); if (dist > 1.5) { const dir = new THREE.Vector3().subVectors(this.navTarget, this.mesh.position).normalize(); if (this.onFloor && Math.random() < .005) this.velocity.y = 8; if (![dt, this.speed, dir.x, dir.z].every(Number.isFinite)) return; this.velocity.x = dir.x * this.speed * dt; this.velocity.z = dir.z * this.speed * dt; const targetRot = Math.atan2(dir.x, dir.z); let rotDiff = targetRot - this.rotation.y; while (rotDiff > Math.PI) rotDiff -= Math.PI * 2; while (rotDiff < -Math.PI) rotDiff += Math.PI * 2; this.rotation.y += rotDiff * dt * 5; this.playChaweeyoos("run"); } else { this.velocity.set(0, 0, 0); this.processArrivalAction(dt); } },
  processArrivalAction(dt) { switch (this.currentActionState) { case "SLEEP": this.playChaweeyoos("idle"); this.needs.energy += 10 * dt; break; case "EAT": this.playChaweeyoos("idle"); this.needs.hunger = Math.max(0, this.needs.hunger - 20 * dt); break; case "WORK": this.playChaweeyoos("attack"); this.needs.wealth += dt; break; case "BUILD": this.playChaweeyoos("attack"); if (Math.random() < .01) { const pos = this.navTarget.clone(); pos.y += .5; this.olam.addObject("Brick", { position: pos, isSolid: true, name: "NPC Brick", interactable: true, golem: { guf: { BoxGeometry: [1,1,1] }, toyr: { MeshLambertMaterial: { color: "gold" } } } }); this.olam.player?.spawnHebrewParticles?.(pos, 10); this.setDecision("IDLE", null); } break; case "TALK": this.playChaweeyoos("idle"); this.mesh.lookAt(this.targetEntity ? this.targetEntity.mesh.position : this.mesh.position); this.needs.social += 10 * dt; break; default: this.playChaweeyoos("idle"); } },
  findHome() { return this.originalSpawnPosition || new THREE.Vector3(0,0,0); }, findFoodSource() { return new THREE.Vector3(10,0,10); }, findWorkplace() { return new THREE.Vector3(-10,0,-10); },
  findNearestSoul() { if (!this.olam.nivrayim) return null; let closest = null, minDist = Infinity; const candidates = [...this.olam.nivrayim]; if (this.olam.player) candidates.push(this.olam.player); for (const n of candidates) { if (n === this || !n.mesh) continue; const d = this.mesh.position.distanceTo(n.mesh.position); if (d < minDist && d < 20) { minDist = d; closest = n; } } return closest; },
  getRandomPoint() { const r = 20; return new THREE.Vector3((Math.random() - .5) * r, 0, (Math.random() - .5) * r).add(this.mesh.position); }
};
