// B"H
/**
 * @file heroTree.js
 * @description Chapter 76: the hero tree now drinks hosted EZ Tree bark and leaf textures.
 */
import * as THREE from "/games/scripts/build/three.module.js";
import { finite, hash, setInstance, segmentBetween } from "../math.js";
import { finishInstanced, markDecorative } from "../decor.js";
import { lambertBark, lambertLeaf } from "../lambert.js?v=leaflet-textures-20260614-bh1";
const textureCache = new Map();
const trunkGeo = h => new THREE.CylinderGeometry(.72,1.16,h,14,6);
const limbGeo = () => new THREE.CylinderGeometry(.07,.2,1,8,1);
function leafletGeo(){ const s=new THREE.Shape(); s.moveTo(0,.5); s.bezierCurveTo(.34,.32,.36,-.22,0,-.52); s.bezierCurveTo(-.36,-.22,-.34,.32,0,.5); const g=new THREE.ExtrudeGeometry(s,{depth:.025,bevelEnabled:true,bevelSize:.012,bevelThickness:.01,bevelSegments:1}); g.rotateX(Math.PI/2); g.translate(0,.1,0); g.computeVertexNormals(); return g; }
function berryGeo(){ return new THREE.SphereGeometry(.06,6,4); }
function loadTexture(url, srgb=false){ if(!url) return null; if(textureCache.has(url)) return textureCache.get(url); const loader=new THREE.TextureLoader(); loader.setCrossOrigin?.("anonymous"); const tex=loader.load(url); if(srgb&&THREE.SRGBColorSpace) tex.colorSpace=THREE.SRGBColorSpace; tex.wrapS=tex.wrapT=THREE.RepeatWrapping; tex.anisotropy=4; textureCache.set(url,tex); return tex; }
function texturedBark(op,ctx,color){ const mat=lambertBark(color,ctx); const map=loadTexture(op.barkMapUrl,true); if(map){map.repeat.set(op.barkRepeatX||2,op.barkRepeatY||4); mat.map=map; mat.userData.staticTextureUrl=op.barkMapUrl; mat.needsUpdate=true;} return mat; }
function texturedLeaf(op,ctx,color){ const mat=lambertLeaf(color,ctx); const map=loadTexture(op.leafMapUrl,true); if(map){map.repeat.set(op.leafRepeatX||1,op.leafRepeatY||1); mat.map=map; mat.alphaTest=0.24; mat.transparent=true; mat.userData.staticTextureUrl=op.leafMapUrl; mat.needsUpdate=true;} return mat; }
function crownPoint(i,op){ const cluster=Math.floor(i/7),slot=i%7,a=cluster*2.399963+hash(cluster,4,8)*.35,r=finite(op.crownRadius,5.4)*(.28+.68*Math.sqrt(hash(cluster,2,7))),baseY=finite(op.trunkHeight,7.5)*.66+hash(cluster,4,8)*finite(op.crownHeight,3.8);const spread=.34+.22*hash(cluster,7,3),local=(slot-3)*.31;return new THREE.Vector3(Math.cos(a)*r+Math.cos(a+Math.PI/2)*local*spread,baseY+(slot%3-1)*.2+hash(i,8,5)*.22,Math.sin(a)*r*.74+Math.sin(a+Math.PI/2)*local*spread); }
function placeLimb(mesh,i,h){ const a=i*2.399963+hash(i,1,1), start=new THREE.Vector3(0,h*(.42+hash(i,2,2)*.42),0), end=start.clone().add(new THREE.Vector3(Math.cos(a)*(2+hash(i,3,3)*3.4),.5+hash(i,4,4)*1.8,Math.sin(a)*(1.4+hash(i,5,5)*2.7))); const seg=segmentBetween(start,end); setInstance(mesh,i,seg.mid,seg.q,new THREE.Vector3(.85,seg.length,.85)); }
function placeLeaf(mesh,i,op){ const p=crownPoint(i,op),cluster=Math.floor(i/7),fan=(i%7-3)*.16,a=cluster*2.399963; const q=new THREE.Quaternion().setFromEuler(new THREE.Euler((hash(i,9,1)-.5)*.75,a+fan,(hash(i,9,3)-.5)*.8)); const s=.32+hash(i,3,1)*.34; setInstance(mesh,i,p,q,new THREE.Vector3(s,s*(.74+hash(i,3,2)*.28),.34+hash(i,3,3)*.2)); }
function placeBerry(mesh,i,op){ const p=crownPoint(i*7+13,op); const q=new THREE.Quaternion(); setInstance(mesh,i,p,q,new THREE.Vector3(1,1,1)); }
export function createHeroTree(op={},ctx={}){ const h=finite(op.trunkHeight,7.5), limbsN=Math.max(8,Math.floor(finite(op.limbCount,24))), leavesN=Math.max(126,Math.floor(finite(op.leafCount,294))), berryN=Math.floor(leavesN/34); const group=new THREE.Group(), renderCtx={renderer:ctx.renderer||ctx.olam?.renderer||op.renderer}; group.name=op.name||"AwtsmoosHeroTree_textured_3d_leaflets"; const trunk=new THREE.Mesh(trunkGeo(h),texturedBark(op,renderCtx,finite(op.barkColor,0x5a351d))); const limbs=new THREE.InstancedMesh(limbGeo(),texturedBark(op,renderCtx,finite(op.branchColor,0x4d2d19)),limbsN); const leaves=new THREE.InstancedMesh(leafletGeo(),texturedLeaf(op,renderCtx,finite(op.leafColor,0x5fa83a)),leavesN); const berries=new THREE.InstancedMesh(berryGeo(),new THREE.MeshLambertMaterial({color:op.fruitColor||0xd56b32}),berryN); trunk.position.y=h/2; for(let i=0;i<limbsN;i++)placeLimb(limbs,i,h); for(let i=0;i<leavesN;i++)placeLeaf(leaves,i,op); for(let i=0;i<berryN;i++)placeBerry(berries,i,op); finishInstanced([limbs,leaves,berries]); group.add(trunk,limbs,leaves,berries); group.position.set(finite(op.position?.x),finite(op.position?.y),finite(op.position?.z)); group.rotation.y=finite(op.rotationY,0); group.scale.setScalar(finite(op.scale,1)); group.userData.textured3DLeaflets=true; group.userData.noLeafPlanes=true; group.userData.leafClusters=Math.ceil(leavesN/7); group.userData.staticTextureUrls={bark:op.barkMapUrl||null,leaf:op.leafMapUrl||null}; return markDecorative(group); }
