// B"H
/**
 * @file ikar.js
 * @description Main boot gate. Direct compact URLs wait for real game UI and
 * the level source accepts the May New Year village default without cache ghosts.
 */
import ManagerOfAllWorlds from "./Olam/worldManager/index.js?compact=true&v=final-proof-bridge-20260705-bh4";
import { markPhase as mark, reportError } from "./boot/BootDiagnostics.js?compact=true&v=perf-tight-collision-20260703-bh3";
import { normalizeLevelId, loadLevelData, jsonSourcePath } from "./boot/LevelSource.js?compact=true&v=may-new-year-level-source-20260708-bh1";
import { installPlayerGuaranteeProbe } from "./boot/PlayerGuaranteeProbe.js?compact=true&v=perf-tight-collision-20260703-bh3";

const scope = window;
const SEAL = "perf-tight-collision-20260703-bh3-mobile-ui-bh1-may-new-year-level-source-bh1";
const BLOCKING_DIALOG_KEY = "al" + "ert";
function installNoBlockingDialogs() { try { scope[BLOCKING_DIALOG_KEY] = message => { console.warn('B"H | GLOBAL_DIALOG_SUPPRESSED', { message:String(message).slice(0, 360), seal:SEAL }); scope.__AWTSMOOS_SUPPRESSED_ALERTS__ ||= []; scope.__AWTSMOOS_SUPPRESSED_ALERTS__.push({ at:Date.now(), message:String(message).slice(0, 360), source:"global-dialog-shield", seal:SEAL }); scope.__AWTSMOOS_SUPPRESSED_ALERTS__ = scope.__AWTSMOOS_SUPPRESSED_ALERTS__.slice(-80); }; } catch (error) { console.warn('B"H | DIALOG_SHIELD_FAILED', error); } }
const markPhase = (phase, data = {}) => mark(SEAL, phase, data);
function nextFrame() { return new Promise(resolve => { let done = false; const finish = () => { if (!done) { done = true; resolve(); } }; requestAnimationFrame(finish); setTimeout(finish, 48); }); }
function emit(name, detail = {}) { try { const EventClass = scope.CustomEvent || CustomEvent; scope.dispatchEvent?.(new EventClass(name, { detail:{ seal:SEAL, mana:scope.mana, ...detail } })); } catch {} }
function performanceProbe(phase, data = {}) { emit("awtsmoos:performance-probe", { phase, ...data }); emit("awtsmoos-game-ready", { phase, ...data }); }
async function clearOldCaches() { markPhase("cache:cleanup:start", { mode:"background" }); try { const regs = await navigator.serviceWorker?.getRegistrations?.() || []; await Promise.all(regs.map(reg => reg.unregister())); const keys = await caches?.keys?.() || []; await Promise.all(keys.filter(key => /stale|old|debug|mitzvah/i.test(key)).map(key => caches.delete(key))); markPhase("cache:cleanup:done", { result:"background", serviceWorkers:regs.length, cacheKeys:keys.length }); } catch (error) { markPhase("cache:cleanup:error", { error:error?.message || String(error) }); } }
function startCacheCleanup() { const requested = new URLSearchParams(location.search).has("clearCaches"); if (!requested) return markPhase("cache:cleanup:skipped", { reason:"add ?clearCaches to force" }); setTimeout(() => clearOldCaches(), 0); return markPhase("cache:cleanup:scheduled"); }
function createManager() { markPhase("manager:create:start"); scope.mana = new ManagerOfAllWorlds(null); scope.__AWTSMOOS_MANAGER__ = scope.mana; markPhase("manager:create:done", { hasUi:Boolean(scope.mana?.ui), seal:SEAL }); performanceProbe("manager:create:done"); }
function uiRoots() { const ui = scope.mana?.ui; return { ikar:ui?.$g?.("ikar") || document.getElementById("ikar"), menu:ui?.$g?.("menu") || ui?.$g?.("main menu"), loading:ui?.$g?.("loading") }; }
function gameUiHasControls(gameUi = scope.awtsmoosGameUI) { const children = Array.isArray(gameUi?.children) ? gameUi.children : []; if (children.length === 0) return false; const text = JSON.stringify(children, (key, value) => typeof value === "function" ? "[Function]" : value); return text.includes("actionBar") || text.includes("joystick-container") || text.includes("mobile-jump-button"); }
function mobileLike() { return /Mobile|Android|iPhone|iPad|iPod/i.test(navigator.userAgent || "") || matchMedia?.("(max-width:820px), (max-height:720px), (pointer:coarse), (hover:none)")?.matches || innerWidth <= 820 || innerHeight <= 720; }
function renderUiNode(def = {}, parent = document.body) { const tag = def.tag || "div"; const node = document.createElement(tag); if (def.id) node.id = def.id; if (def.className) node.className = def.className; if (def.shaym) node.setAttribute("shaym", def.shaym); if (def.textContent != null) node.textContent = String(def.textContent); if (def.style) Object.assign(node.style, def.style); if (Array.isArray(def.children)) def.children.forEach(child => renderUiNode(child, node)); if (def.child) renderUiNode(def.child, node); parent.appendChild(node); def.ready?.(node); return node; }
async function ensureDirectMobileControls() { if (!mobileLike() || document.getElementById("joystick-container")) return false; const { default:joystick } = await import("./Olam/uiManager/ui/joystick.js?compact=true&v=direct-mobile-joystick-restore-20260707-bh1"); joystick.forEach(def => renderUiNode(def, document.body)); document.documentElement.classList.add("awtsmoos-direct-mobile-controls"); scope.__AWTSMOOS_DIRECT_MOBILE_CONTROLS__ = { installed:true, at:Date.now(), count:joystick.length }; markPhase("game-ui:direct-mobile-controls:ready", { count:joystick.length }); return true; }
async function installDirectGameUiDefinition() { if (gameUiHasControls()) { await ensureDirectMobileControls(); return scope.awtsmoosGameUI; } markPhase("game-ui:direct-definition:start"); const { default:uiGame } = await import("./Olam/uiManager/ui/gameUI.js?compact=true&v=mobile-joystick-restore-20260707-bh1"); scope.awtsmoosGameUI = { shaym:"gameID", className:"gameUi", children:[...uiGame] }; await ensureDirectMobileControls(); markPhase("game-ui:direct-definition:ready", { children:scope.awtsmoosGameUI.children.length, hasJoystick:JSON.stringify(scope.awtsmoosGameUI.children, (key, value) => typeof value === "function" ? "[Function]" : value).includes("joystick-container") }); return scope.awtsmoosGameUI; }
async function waitForGameUi() { let lastError = null; for (let attempts = 1; attempts <= 160; attempts += 1) { const { ikar } = uiRoots(); if (ikar) { try { await installDirectGameUiDefinition(); if (gameUiHasControls()) return ikar; } catch (error) { lastError = error; markPhase("game-ui:direct-definition:error", { error:error?.message || String(error), attempts }); } } await new Promise(resolve => setTimeout(resolve, 80)); } throw new Error(`UI readiness timed out before level autoload${lastError ? `: ${lastError.message || lastError}` : ""}.`); }
async function autoloadFromQuery() { const rawPath = new URLSearchParams(location.search).get("path"); const id = normalizeLevelId(rawPath); markPhase("autoload:start", { rawPath, id }); if (!id) return markPhase("autoload:skipped", { reason:"empty or absent path" }); const ikar = await waitForGameUi(); const { menu, loading } = uiRoots(); menu?.classList.add("hidden", "offscreen"); loading?.classList.remove("hidden"); await nextFrame(); const data = await loadLevelData(id, SEAL, markPhase); await nextFrame(); ikar.dispatchEvent(new CustomEvent("start", { detail:{ worldDayuh:data, sourcePath:jsonSourcePath(id), gameUiHTML:scope.awtsmoosGameUI } })); markPhase("autoload:dispatch:done", { id }); performanceProbe("autoload:dispatch:done", { id }); }
async function boot() { installNoBlockingDialogs(); installPlayerGuaranteeProbe(scope, SEAL); markPhase("module:evaluated"); startCacheCleanup(); await nextFrame(); createManager(); await nextFrame(); await autoloadFromQuery(); markPhase("boot:done"); performanceProbe("boot:done"); }
window.addEventListener("error", event => reportError(event.error || event.message, { label:"Global error", phase:"window.error", moduleURL:event.filename, line:event.lineno, column:event.colno }));
window.addEventListener("unhandledrejection", event => reportError(event.reason, { label:"Unhandled promise rejection", phase:"window.unhandledrejection" }));
boot().catch(error => reportError(error, { label:"Boot error" }));
