// B"H
/**
 * @module combat
 * @description THE TEFILLAH OF WAR. The same old sword now remembers XP,
 * levels, rewards, and HUD proof instead of scattering sparks into silence.
 */
import * as THREE from '/games/scripts/build/three.module.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1';
import { TORAH_PASSAGES } from '../../../tochen/skills/TorahPassages.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1';
import SpiritualWeaponManifestor from '../../../tochen/combat/SpiritualWeaponManifestor.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1';
const PROGRESS_KEY = "awtsmoosMitzvahPlayerProgress";
const num = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
function scopeOf(self) { return self?.olam?.aysh?.window || globalThis; }
function readProgress(self) { try { return JSON.parse(scopeOf(self)?.localStorage?.getItem(PROGRESS_KEY) || "null") || null; } catch { return null; } }
function writeProgress(self) { try { scopeOf(self)?.localStorage?.setItem(PROGRESS_KEY, JSON.stringify({ level:num(self.level,1), xp:num(self.xp), maxXp:num(self.maxXp,100), maxHp:num(self.maxHp,100), maxKoach:num(self.maxKoach,100) })); } catch {} }
function emitProgress(self, reason) { self.olam?.ayshPeula?.("ui event", "gameHUD", { updateStats:{ level:num(self.level,1), xp:num(self.xp), maxXp:num(self.maxXp,100), hp:num(self.hp), maxHp:num(self.maxHp,100), koach:num(self.koach), maxKoach:num(self.maxKoach,100), reason } }); }
function hydrateProgress(self) { if (self.__combatProgressHydrated) return; self.__combatProgressHydrated = true; const saved = readProgress(self); if (!saved) return; self.level = Math.max(num(self.level,1), num(saved.level,1)); self.xp = Math.max(num(self.xp), num(saved.xp)); self.maxXp = Math.max(num(self.maxXp,100), num(saved.maxXp,100)); self.maxHp = Math.max(num(self.maxHp,100), num(saved.maxHp,100)); self.maxKoach = Math.max(num(self.maxKoach,100), num(saved.maxKoach,100)); }
export default {
  learnedSkills: ["shema_yisrael", "shmoneh_esray"],
  learnSkill(skillId) { const skill = TORAH_PASSAGES[skillId]; if (!skill) return; if (this.level < skill.levelRequired) return this.olam.ayshPeula("ui event", "effectsOverlay", { text:`Level ${skill.levelRequired} required!`, color:"red" }); if (!this.learnedSkills.includes(skillId)) { this.learnedSkills.push(skillId); this.olam.ayshPeula("ui event", "effectsOverlay", { text:`Learned: ${skill.name}!`, color:"#00ff00" }); this.updateSkillsUI(); } },
  castSkill(skillId) { const skill = TORAH_PASSAGES[skillId]; if (!skill || !this.learnedSkills.includes(skillId)) return; if (this.koach < skill.cost) return this.olam.ayshPeula("ui event", "effectsOverlay", { text:"Low Koach!", color:"blue" }); if (skill.bookRequired && !this.hasItemInAnyPocket(skill.bookRequired)) return this.olam.ayshPeula("ui event", "effectsOverlay", { text:`Requires ${skill.bookRequired} in pocket!`, color:"orange" }); this.koach -= skill.cost; this.updateStatsUI(); let visualData = null; if (skill.weaponAffinity) visualData = SpiritualWeaponManifestor.compileVisuals(skill.weaponAffinity, skill.color); const payload = { damage:this.calculatePower() + (skill.damage || 0), isAttack:true, color:skill.color, aoe:skill.aoe, element:skill.element, weaponType:skill.weaponAffinity, rangeType:skill.rangeType, visuals:visualData, doubleEdged:skill.doubleEdged }; this.throwBall(this.olam.randomLetter(), payload); this.olam.ayshPeula("ui event", "effectsOverlay", { text:skill.name.toUpperCase(), color:skill.color }); },
  hasItemInAnyPocket(itemId) { if (!this.inventory) return false; const allSlots = [...(this.inventory.slots || []), ...Object.values(this.inventory.equipment || {})]; return allSlots.some(item => { if (!item) return false; const actualId = item.id || (item.index !== undefined ? (item.sourceType === 'inventory' ? this.inventory.slots[item.index]?.id : this.inventory.actionSlots[item.index]?.id) : null); return actualId === itemId; }); },
  applyDamage(target, payload) { let multiplier = 1; const dist = this.mesh.position.distanceTo(target.position); if (payload.weaponType === "sword") { if (dist < 10) multiplier = 2.5; if (payload.doubleEdged) multiplier *= 1.2; } else if (payload.weaponType === "bow" && dist > 30) multiplier = 3.0; if (payload.element && target.elementalType === payload.element) multiplier *= 2; const finalDamage = payload.damage * multiplier; if (target.takeDamage) target.takeDamage(finalDamage); },
  gainXP(amount) { return this.gainXp(amount); },
  gainXp(amount) { hydrateProgress(this); let gained = Math.max(0, num(amount)); if (!gained) return; this.level = Math.max(1, num(this.level,1)); this.xp = Math.max(0, num(this.xp)); this.maxXp = Math.max(25, num(this.maxXp,100)); this.xp += gained; while (this.xp >= this.maxXp) { this.xp -= this.maxXp; this.levelUp(true); } this.updateStatsUI?.(); writeProgress(this); emitProgress(this, "xp gain"); this.olam?.ayshPeula?.("ui event", "effectsOverlay", { text:`+${Math.round(gained)} XP`, color:"#9effd0" }); },
  levelUp(keepOverflow = false) { this.level = Math.max(1, num(this.level,1)) + 1; if (!keepOverflow) this.xp = 0; this.maxXp = Math.max(25, Math.floor(Math.max(25, num(this.maxXp,100)) * 1.5)); this.maxHp = num(this.maxHp,100) + 20; this.hp = this.maxHp; this.maxKoach = num(this.maxKoach,100) + 15; this.koach = this.maxKoach; this.olam.ayshPeula("ui event", "effectsOverlay", { text:"LEVEL UP!", color:"#ffd700" }); writeProgress(this); emitProgress(this, "level up"); },
  die() { if (this.isDead) return; this.isDead = true; if (this.type === "mazik") { this.spawnHebrewParticles(this.mesh.position, 30, this.color || "#ff0000"); const player = this.olam.player || this.olam.chossid; if (this.xpValue && player) { player.gainXp?.(this.xpValue); player.updateQuestProgress?.("kill", this.elementalType); } if (this.olam) this.olam.sealayk(this); } else if (this.type === "chai") { this.olam.ayshPeula("ui event", "effectsOverlay", { text:"R'L - YOUR SOUL IS IN FLUX", color:"red" }); setTimeout(() => location.reload(), 3000); } },
  updateSkillsUI() { const skillData = this.learnedSkills.map(id => ({ ...TORAH_PASSAGES[id], id })); this.olam.ayshPeula("ui event", "skillBar", { updateSkills:skillData }); this.olam.ayshPeula("ui event", "knowledgeMenu", { updateKnowledge:skillData }); },
  calculatePower() { let p = 10 + (num(this.level,1) * 2); if (this.checkEquipmentForItem("book_tehillim")) p += 15; if (this.checkEquipmentForItem("book_tanya")) p += 25; return p; },
  checkEquipmentForItem(itemId) { if (!this.inventory || !this.inventory.equipment) return false; return Object.values(this.inventory.equipment).some(ref => { if (!ref) return false; const item = ref.sourceType === 'inventory' ? this.inventory.slots[ref.index] : this.inventory.actionSlots[ref.index]; return item && item.id === itemId; }); }
};
