//B"H

/**
 * Chapter 383: The Control Page Put The No-Debug Login First.
 *
 * The Awtsmoos opens the primary gate through `/chatgpt`, a localhost proxy
 * login path that works without Chrome DevTools. Debug Chrome remains optional.
 */
function renderControlPage(config) {
  const control = `http://127.0.0.1:${config.port}`;
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Awtsmoos Relay</title>${style()}</head><body><main><section><p class="eye">B&quot;H Awtsmoos Split Browser</p><h1>Node relay control</h1><p>Target: <code>${escapeHtml(config.targetOrigin)}</code></p><div class="badges"><span id="healthBadge">health unknown</span><span id="sessionBadge">session unknown</span><span id="chromeBadge">debug Chrome optional</span></div><div class="primary"><a data-open-chatgpt href="/chatgpt">Open ChatGPT through Node — no debug Chrome needed</a><p>Use this first on Termux/mobile or any browser without remote debugging. Login stays on localhost; cookies and token requests are captured by Node.</p></div><div class="grid"><button data-action="health">Check health</button><button data-action="session">Check session</button><button data-action="automationStatus">Automation status</button><button data-action="clientState">Client state</button><button data-action="debugChromeOpen">Optional debug Chrome</button><button data-action="debugChromeSave">Optional save debug cookies</button><button data-action="debugSession">Optional debug queue</button></div><p class="hint">Normal login route: <code>/chatgpt</code>. Debug Chrome is not required.</p><pre id="status">${escapeHtml(control)}</pre></section></main><div id="loader" hidden>Loading ChatGPT through Node…</div><script>${script()}</script></body></html>`;
}

function style() {
  return `<style>*{box-sizing:border-box}body{margin:0;font-family:system-ui,Segoe UI,sans-serif;background:#080b12;color:#eef3ff}main{min-height:100vh;display:grid;place-items:center;padding:14px}section{width:min(860px,100%);background:#111827;border:1px solid #263247;border-radius:18px;padding:18px;box-shadow:0 16px 48px #0007}.eye{letter-spacing:.12em;text-transform:uppercase;color:#9db7ff;font-size:11px}h1{font-size:clamp(24px,6vw,34px);margin:.2rem 0}.badges{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.badges span{border-radius:999px;padding:6px 10px;font-size:12px;font-weight:800;border:1px solid #33415c;background:#172033}.ok{background:#12351f!important;color:#b9ffd0}.warn{background:#3b2b11!important;color:#ffe4a6}.bad{background:#3a1720!important;color:#ffc4d0}.primary{border:1px solid #31537f;border-radius:16px;background:#0b1d34;padding:14px;margin:14px 0}.primary a,.grid button{display:block;border:0;border-radius:12px;padding:11px 12px;background:#dbe7ff;color:#07111f;font-weight:900;text-decoration:none;text-align:center}.primary a{background:linear-gradient(135deg,#67e8f9,#a78bfa);font-size:16px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}p,.hint{color:#cbd7ee;overflow-wrap:anywhere}pre{max-height:46vh;overflow:auto;white-space:pre-wrap;word-break:break-word;background:#05070b;border-radius:14px;padding:12px;color:#b7ffc7;font-size:12px}#loader{position:fixed;inset:0;display:grid;place-items:center;background:#05070bd9;z-index:99}#loader[hidden]{display:none}</style>`;
}

function script() {
  return `const out=document.getElementById('status'),hb=document.getElementById('healthBadge'),sb=document.getElementById('sessionBadge'),cb=document.getElementById('chromeBadge');const paths={health:'/health',session:'/session-status',debugChromeOpen:'/debug-chrome/open',debugChromeSave:'/debug-chrome/save-cookies',debugSession:'/debug/session',automationStatus:'/automation-status',clientState:'/client-state'};function badge(el,text,kind){el.textContent=text;el.className=kind}function sessionKind(s){return s==='logged_in'?'ok':s==='not_logged_in'?'warn':'bad'}async function show(path){out.textContent='loading '+path;const r=await fetch(path,{cache:'no-store'}),j=await r.json();out.textContent=JSON.stringify(j,null,2);if(path==='/health'){badge(hb,j.ok?'health ok':'health failed',j.ok?'ok':'bad');badge(sb,j.session?.status||'session unknown',sessionKind(j.session?.status));badge(cb,j.debugChrome?.ok?'debug Chrome ready':'debug Chrome optional',j.debugChrome?.ok?'ok':'warn')}if(path==='/session-status')badge(sb,j.status||'session failed',sessionKind(j.status));return j}document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>show(paths[b.dataset.action]).catch(e=>out.textContent=e.stack||e.message));document.querySelector('[data-open-chatgpt]').onclick=e=>{e.preventDefault();document.getElementById('loader').hidden=false;setTimeout(()=>location.href='/chatgpt',80)};show('/health').catch(()=>{});`;
}
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])); }
module.exports = { renderControlPage };
