// B"H
import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { findBrowser } from "./ChromePath.js";
import { launchChrome } from "./ChromeLauncher.js";
import { connectCdp } from "./ChromeDevTools.js";
const proofDir="ai_thoughts/20260707-004045-full-repair-no-freeze-loading-ui-targeting-doors/proof";
const base=process.env.MITZVAH_WORLD_URL||"http://127.0.0.1:8080/games/mitzvahWorld/";
const url=`${base}?compact=true&path=village.json&awtsAudit=two-minute-${Date.now()}`;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function ev(client,expression,timeoutMs=20000){const r=await client.send("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true},timeoutMs);if(r.exceptionDetails)throw new Error(r.exceptionDetails.text||"eval failed");return r.result?.value;}
async function shot(client,name){const out=await client.send("Page.captureScreenshot",{format:"png",captureBeyondViewport:false},15000);const file=`${proofDir}/${name}.png`;await writeFile(file,Buffer.from(out.data,"base64"));return file;}
async function waitPlayable(client){for(let i=0;i<120;i++){const p=await ev(client,`(()=>{const c=document.querySelector('canvas'),h=window.__AWTSMOOS_PLAYER_FACING_HUD_GUARANTEE__?.has?.(),hidden=!document.getElementById('awtsmoosLoadingVeil');return{ok:Boolean(c&&hidden&&h?.health&&h?.targeting&&h?.x&&h?.r&&h?.quest&&h?.joystick&&h?.jump),hidden,h,loading:window.__MITZVAH_LOADING_DIAG__?.()?.loading||null}})()`).catch(e=>({ok:false,error:String(e.message||e)}));if(p.ok)return p;await sleep(500)}throw new Error("playable hud proof timeout");}
const sampler=`new Promise(resolve=>{const start=performance.now(),end=start+120000,frames=[],longTasks=[],errors=[];let last=start,tick=0;try{new PerformanceObserver(l=>l.getEntries().forEach(e=>longTasks.push({duration:e.duration,startTime:e.startTime}))).observe({entryTypes:['longtask']})}catch(e){errors.push(String(e?.message||e))}function key(code,type='keydown'){const e=new KeyboardEvent(type,{bubbles:true,cancelable:true,code,key:code.replace('Key','').replace('Digit','')});window.dispatchEvent(e);document.dispatchEvent(e);document.querySelector('canvas')?.dispatchEvent(e)}function click(){const c=document.querySelector('canvas'),r=c?.getBoundingClientRect?.();if(!r)return;const x=r.left+r.width*(.42+(tick%7)*.025),y=r.top+r.height*.55;for(const t of ['mousemove','pointerdown','mousedown','pointerup','mouseup','click'])c.dispatchEvent(new MouseEvent(t,{bubbles:true,cancelable:true,clientX:x,clientY:y,button:0,buttons:t.includes('down')?1:0}))}const input=setInterval(()=>{key('KeyW','keydown');if(tick%5===0)key('Space');if(tick%7===0)key('KeyR');if(tick%9===0)key('KeyX');if(tick%4===0)click();tick++},260);function done(){clearInterval(input);['KeyW','KeyA','KeyD','Space','KeyR','KeyX'].forEach(c=>key(c,'keyup'));const xs=frames.slice(1),sorted=xs.slice().sort((a,b)=>a-b),sum=xs.reduce((a,b)=>a+b,0),avg=sum/Math.max(1,xs.length),q=p=>sorted[Math.min(sorted.length-1,Math.floor(sorted.length*p))]||0,h=window.__AWTSMOOS_PLAYER_FACING_HUD_GUARANTEE__?.has?.()||{},c=document.querySelector('canvas');resolve({ok:xs.length>300,durationMs:performance.now()-start,frameCount:xs.length,avgBrowserRafFps:1000/Math.max(.001,avg),minBrowserRafFps:1000/Math.max(.001,sorted.at(-1)||avg),p95FrameMs:q(.95),p99FrameMs:q(.99),worstFrameMs:sorted.at(-1)||0,longTaskCount:longTasks.length,longTasks:longTasks.slice(-30),hud:h,engineFps:window.__AWTSMOOS_WORKER_GAMEPLAY_FPS__?.fps||null,loading:window.__MITZVAH_LOADING_DIAG__?.()?.loading||null,canvas:{width:c?.width||0,height:c?.height||0},errors})}function frame(now){frames.push(now-last);last=now;now>=end?done():requestAnimationFrame(frame)}requestAnimationFrame(frame)})`;
await mkdir(proofDir,{recursive:true});
const browser=findBrowser(); if(!browser.path) throw new Error("No Chrome found");
const chrome=await launchChrome(browser.path,url,9241,{width:390,height:844}); const events=[];
try{const client=await connectCdp(chrome.page.webSocketDebuggerUrl,e=>events.push(e)); await client.send("Runtime.enable");await client.send("Log.enable");await client.send("Network.enable");await client.send("Page.enable");
 await sleep(1200); const loadingShot=await shot(client,"two_minute_loading_start"); const playable=await waitPlayable(client); const playableShot=await shot(client,"two_minute_first_playable"); const sample=await ev(client,sampler,150000); const endShot=await shot(client,"two_minute_no_freeze_end_state"); const fatal=events.filter(e=>e.method==="Runtime.exceptionThrown"||e.method==="Network.loadingFailed");
 for(const k of ["health","targeting","x","r","quest","joystick","jump"]) assert.equal(sample.hud[k],true,`missing ${k}`); assert.equal(fatal.length,0,JSON.stringify(fatal.slice(0,5))); assert(sample.ok,"not enough rAF frames");
 const report={ok:true,test:"twoMinuteNoFreezeAudit",url,screenshots:{loadingShot,playableShot,endShot},playable,sample,fatalConsoleOrNetwork:0}; await writeFile(`${proofDir}/twoMinuteNoFreezeAudit.json`,JSON.stringify(report,null,2)); console.log(JSON.stringify(report,null,2)); client.close?.();
}finally{await chrome.close();}
