// B"H
/** @file WeaponActionCatalog.js @description Custom weapon actions: one-hand, off-hand, two-hand, staff cast, bow draw, release. */
const P=(name,ms,bones,ease="easeInOut")=>({name,ms,bones,ease});
const B=(right,left=null,spine=null)=>({right,left,spine});
const rightSwing=[P("ready",90,B("draw-back",null,"twist-right")),P("startup",120,B("raise-right",null,"coil")),P("active",150,B("slash-right",null,"uncoil")),P("recover",190,B("return-right",null,"settle"))];
const leftAssist=[P("ready",80,B("guard-right","left-balance","twist-right")),P("active",130,B("slash-right","left-counter","uncoil")),P("recover",170,B("return-right","left-release","settle"))];
const twoHand=[P("grip",120,B("right-grip","left-grip","brace")),P("windup",180,B("right-high","left-low","coil-heavy")),P("active",220,B("two-hand-cut","left-pull","heavy-uncoil")),P("recover",260,B("lower-right","left-follow","settle-heavy"))];
const staffCast=[P("plant",140,B("staff-plant","left-channel","root")),P("cast",320,B("right-pulse","left-circle","lift")),P("release",150,B("staff-release","left-open","extend")),P("recover",180,B("staff-idle","left-rest","settle"))];
const bowDraw=[P("nock",120,B("string-ready","bow-hold","aim")),P("draw",360,B("string-draw","bow-extend","focus")),P("hold",999,B("string-hold","bow-steady","breathe"))];
const bowRelease=[P("release",90,B("string-release","bow-kick","focus-release")),P("recover",210,B("string-reset","bow-lower","settle"))];
export const WEAPON_ACTIONS=Object.freeze({ unarmed_jab:{id:"unarmed_jab",clip:"mw_unarmed_jab",handMode:"right",phases:rightSwing,hitPhase:"active"}, one_hand_slash_right:{id:"one_hand_slash_right",clip:"mw_sword_1h_slash_r",handMode:"right",phases:rightSwing,hitPhase:"active"}, one_hand_slash_left_assist:{id:"one_hand_slash_left_assist",clip:"mw_sword_1h_guard_assist",handMode:"right-left-assist",phases:leftAssist,hitPhase:"active"}, two_hand_heavy_slash:{id:"two_hand_heavy_slash",clip:"mw_weapon_2h_heavy_slash",handMode:"two",phases:twoHand,hitPhase:"active"}, staff_cast:{id:"staff_cast",clip:"mw_staff_cast",handMode:"two-cast",phases:staffCast,hitPhase:"release"}, staff_swing:{id:"staff_swing",clip:"mw_staff_swing",handMode:"two",phases:twoHand,hitPhase:"active"}, bow_draw_hold:{id:"bow_draw_hold",clip:"mw_bow_draw_hold",handMode:"two-ranged",phases:bowDraw,hitPhase:"hold"}, bow_release:{id:"bow_release",clip:"mw_bow_release",handMode:"two-ranged",phases:bowRelease,hitPhase:"release"}, hebrew_letter_release:{id:"hebrew_letter_release",clip:"mw_hebrew_bow_letter_release",handMode:"two-ranged",phases:[...bowDraw,...bowRelease],hitPhase:"release",projectile:"hebrew-letter"} });
export function weaponAction(id="one_hand_slash_right"){ return WEAPON_ACTIONS[id]||WEAPON_ACTIONS.one_hand_slash_right; }
export function actionForItem(item={},action="attack",phase="release"){ if(!item) return weaponAction("unarmed_jab"); if(item.genre==="hebrewBow") return weaponAction(phase==="hold"?"bow_draw_hold":"hebrew_letter_release"); if(item.genre==="bow"||item.genre==="crossbow") return weaponAction(phase==="hold"?"bow_draw_hold":"bow_release"); if(item.genre==="staff"||item.grip==="staff") return weaponAction(action==="cast"||item.castTime>0?"staff_cast":"staff_swing"); if(item.handedness==="two") return weaponAction("two_hand_heavy_slash"); if(action==="guard"||action==="parry") return weaponAction("one_hand_slash_left_assist"); return weaponAction("one_hand_slash_right"); }
export default WEAPON_ACTIONS;
