// B"H
/** @file ShopUiState.js @description Icon-first shop state: minimal text, maximal readable symbols. */
import { merchantProfile, merchantItems } from "../runtime/MerchantInventoryRuntime.js";
import { buyPrice, sellPrice, repairPrice } from "../runtime/PerutaPricingRuntime.js";
import { weaponStats } from "../../equipment/runtime/WeaponStatCatalog.js";
import { statsUiState } from "../../ui/runtime/StatsUiState.js";
import { iconAction, iconLock, iconTabs, iconStat } from "../../ui/runtime/IconUiHelpers.js";
function diff(a={},b={}){ const keys=["damage","range","weight","staminaCost","criticalChance","knockback","stagger","blockStrength","minLevel"]; return Object.fromEntries(keys.map(k=>[k,(b[k]??0)-(a[k]??0)]).filter(([,v])=>v)); }
function itemIcon(item={}){ return item.icon || (item.genre?.includes("bow")?"🏹":item.genre?.includes("staff")?"杖":item.genre?.includes("sword")?"🗡️":item.kind==="ammo"?"➵":"•"); }
export function shopUiState({actorId="player",merchantId="blacksmith",wallet,buySell,selectedId=null,runtime=null,equippedId=null}={}){ const merchant=merchantProfile(merchantId), snap=buySell?.snapshot?.(actorId)||{inventory:[]}, walletSnap=wallet?.snapshot?.(actorId)||{perutas:0}; const items=merchantItems(merchantId).map(item=>{ const gate=runtime?.trainers?.canUse?.(actorId,item)||{ok:true,missing:[],levelMissing:false}, owned=snap.inventory.includes(item.id), bp=buyPrice(item,merchant), sp=sellPrice({...item,condition:buySell?.condition?.(actorId,item.id)},merchant), rp=repairPrice({...item,condition:buySell?.condition?.(actorId,item.id)},merchant), locked=!gate.ok; return {...item,icon:itemIcon(item),buyPrice:bp,sellPrice:sp,repairPrice:rp,selected:item.id===selectedId,owned,insufficientFunds:walletSnap.perutas<bp,trainerState:gate,locked,condition:buySell?.condition?.(actorId,item.id)??item.condition??1,iconRow:[iconStat("level",item.minLevel||1),iconStat("damage",item.damage||0),iconStat("range",item.range||0),iconStat("condition",Math.round(((buySell?.condition?.(actorId,item.id)??item.condition??1))*100))]}; }); const selected=items.find(x=>x.id===selectedId)||items[0]||null, equipped=weaponStats(equippedId)||null, playerInventory=snap.inventory, actions={canBuy:Boolean(selected&&!selected.owned&&!selected.insufficientFunds&&!selected.locked),canSell:Boolean(selected&&playerInventory.includes(selected.id)),canRepair:Boolean(selected&&playerInventory.includes(selected.id)&&(selected.condition??1)<1),canUpgrade:Boolean(selected&&playerInventory.includes(selected.id)&&selected.upgradePath?.length),insufficientFunds:Boolean(selected?.insufficientFunds),owned:Boolean(selected?.owned),trainerRequired:Boolean(selected?.locked),missingTraining:selected?.trainerState?.missing||[],levelMissing:Boolean(selected?.trainerState?.levelMissing)}; return {actorId,merchant:{...merchant,text:"",chip:{icon:merchant.icon||"🏪",text:""}},minimalText:true,iconFirst:true,modeTabs:iconTabs(["buy","sell"]),tabs:iconTabs(merchant.categories),wallet:{...walletSnap,icon:"🟡"},playerInventory,items,selected,preview:{rotate:true,compare:true,icon:selected?.icon||"•",stats:statsUiState({entity:selected||{},compare:equipped||null}),rarity:selected?.rarity||"common",condition:selected?.condition??1,statDiff:diff(equipped||{},selected||{})},actions,actionIcons:{buy:iconAction("buy",actions.canBuy,actions.insufficientFunds?"funds":actions.trainerRequired?"lock":""),sell:iconAction("sell",actions.canSell),repair:iconAction("repair",actions.canRepair),upgrade:iconAction("upgrade",actions.canUpgrade),lock:iconLock(!actions.trainerRequired,actions.missingTraining)},dialogueIcon:actions.trainerRequired?"🔒":actions.insufficientFunds?"🟡":"✅",dialogue:""}; }
export default shopUiState;
