// B"H
/**
 * @file ShopManager.js
 * @description
 * Chapter 9: The shop reads the same purse that combat, coins, doors, and HUD
 * already illuminate. No second wallet is invented; all known fields are synced.
 */
import AwtsmoosHTMLGenerator from "../../../../utils/ui/AwtsmoosHTMLGenerator.js";
const BAG_KEY = "awtsmoosMitzvahPersonalPerutas";
const num = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
function storageScope(player) { return player?.olam?.aysh?.window || player?.olam?.window || globalThis; }
function readBag(player) { try { return num(storageScope(player)?.localStorage?.getItem(BAG_KEY), 0); } catch { return 0; } }
const moneyOf = player => Math.max(num(player?.currency), num(player?.personalPerutas), num(player?.inventory?.personalPerutas), num(player?.inventory?.perutas), readBag(player));
function writeBag(player, value) { try { storageScope(player)?.localStorage?.setItem(BAG_KEY, String(Math.max(0, Math.floor(num(value))))); } catch {} }
function emitWallet(player, value, delta, reason) { const payload = { personalPerutas:value, delta, reason }; player?.olam?.ayshPeula?.("ui event", "gameHUD", { personalPerutas:payload }); player?.olam?.ayshPeula?.("ui event", "personalPerutas", payload); }
function setMoney(player, value, reason = "shop") { if (!player) return 0; const before = moneyOf(player), next = Math.max(0, Math.floor(num(value))); player.personalPerutas = next; player.currency = next; if (player.inventory) { player.inventory.personalPerutas = next; player.inventory.perutas = next; } writeBag(player, next); emitWallet(player, next, next - before, reason); return next; }
function itemClass(item) { return item.className || (item.equipSlot ? "Clothing" : "Item"); }
export default class ShopManager {
  constructor(npc, olam) { this.npc = npc; this.olam = olam; this.view = "buy"; this.shopInventory = npc?.options?.shopInventory || npc?.shopInventory || []; }
  openShop(chossid) { this.chossid = chossid || this.olam?.chossid || this.olam?.player || null; if (this.chossid && !this.chossid.olam) this.chossid.olam = this.olam; if (!this.chossid) return false; setMoney(this.chossid, moneyOf(this.chossid), "shop open sync"); this.renderUI(); return true; }
  closeShop() { this.olam?.ayshPeula?.("ui event", "shopScreen", { hideShop: true }); if (this.npc?.siach) this.npc.siach.render(); }
  buyItem(itemId) { const item = this.shopInventory.find(i => i.id === itemId); if (!item || !this.chossid) return; const price = num(item.price); const wallet = moneyOf(this.chossid); if (wallet < price) return this.olam?.ayshPeula?.("ui event", "effectsOverlay", { text: "Not enough bag perutas!", color: "#ff6b6b" }); setMoney(this.chossid, wallet - price, "shop buy"); this.chossid.inventory?.addItem?.({ ...item, className: itemClass(item), price, sellValue: num(item.sellValue, Math.floor(price * 0.5)) }); this.olam?.ayshPeula?.("ui event", "toast", { message: `Bought ${item.name}` }); this.chossid.applyGarments?.(); this.renderUI(); }
  sellItem(itemIndex) { const slots = this.chossid?.inventory?.slots || []; const item = slots[itemIndex]; if (!item) return; const sellPrice = num(item.sellValue, Math.floor(num(item.price, 2) * 0.6)); setMoney(this.chossid, moneyOf(this.chossid) + sellPrice, "shop sell"); this.chossid.inventory.removeItem?.(itemIndex); this.olam?.ayshPeula?.("ui event", "toast", { message: `Sold ${item.name} for ${sellPrice}` }); this.renderUI(); }
  renderUI() { if (!this.chossid) return; const rows = this.view === "buy" ? this.buyRows() : this.sellRows(); const html = AwtsmoosHTMLGenerator.emanate(this.blueprint(rows)); this.olam?.ayshPeula?.("ui event", "shopScreen", { html, styles: this.styles(), setupListeners: () => this.setupListeners() }); }
  buyRows() { return this.shopInventory.map(item => this.row(item, item.price, "Buy", "shop-buy-btn", { "data-id": item.id })); }
  sellRows() { const rows = []; (this.chossid?.inventory?.slots || []).forEach((item, index) => { if (item) rows.push(this.row(item, item.sellValue || Math.floor((item.price || 2) * 0.6), "Sell", "shop-sell-btn", { "data-index": index })); }); return rows.length ? rows : [{ tag:"p", style:{ textAlign:"center", color:"#4a3512" }, text:"No sellable items yet." }]; }
  row(item, price, verb, klass, attrs) { return { className:"shop-item", children:[{ tag:"div", className:"shop-icon", text:item.icon || "📦" }, { tag:"div", className:"shop-info", children:[{ tag:"h3", text:item.name }, { tag:"p", text:item.description || "Holy clothing vessel." }, { tag:"b", text:`${price || 0} perutas` }] }, { tag:"button", className:`shop-action ${klass}`, attributes:attrs, text:verb }] }; }
  blueprint(rows) { return { className:"shop-container", children:[{ className:"shop-head", children:[{ tag:"h2", text:`${this.npc?.name || "Guide"} Shop` }, { tag:"button", className:"shop-close-btn", text:"×" }] }, { className:"shop-wallet", text:`Bag: ${moneyOf(this.chossid)} perutas` }, { className:"shop-tabs", children:[{ tag:"button", className:"view-buy-btn", text:"Buy" }, { tag:"button", className:"view-sell-btn", text:"Sell" }] }, { className:"shop-items", children:rows }] }; }
  setupListeners() { document.querySelectorAll(".shop-buy-btn").forEach(btn => { btn.onclick = () => this.buyItem(btn.getAttribute("data-id")); }); document.querySelectorAll(".shop-sell-btn").forEach(btn => { btn.onclick = () => this.sellItem(Number(btn.getAttribute("data-index"))); }); document.querySelector(".view-buy-btn")?.addEventListener("click", () => { this.view = "buy"; this.renderUI(); }); document.querySelector(".view-sell-btn")?.addEventListener("click", () => { this.view = "sell"; this.renderUI(); }); document.querySelector(".shop-close-btn")?.addEventListener("click", () => this.closeShop()); }
  styles() { return `.shop-container{position:fixed;inset:auto 12px 86px 12px;max-width:620px;margin:auto;background:#fff5c9;color:#1c1207;border:3px solid #d7aa45;border-radius:22px;padding:14px;z-index:30001;pointer-events:auto;font-family:Arial,sans-serif;box-shadow:0 12px 32px #0008}.shop-head{display:flex;justify-content:space-between;align-items:center}.shop-head h2{margin:0;font-size:24px}.shop-close-btn{font-size:30px;border:0;background:#8a5d17;color:white;border-radius:14px;width:50px;height:50px}.shop-wallet{text-align:center;font-weight:900;margin:8px}.shop-tabs{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:10px 0}.shop-tabs button,.shop-action{border:0;border-radius:14px;padding:12px;font-weight:900;background:#c37d0c;color:white}.shop-item{display:grid;grid-template-columns:52px 1fr 76px;gap:10px;align-items:center;background:#fffbe0;border:2px solid #d7aa45;border-radius:16px;padding:10px;margin:8px 0}.shop-icon{font-size:34px}.shop-info h3{margin:0;font-size:18px}.shop-info p{margin:3px 0;font-size:13px}`; }
}
