/*
B"H
Boruch Hashem
Biezrash Hashem
*/
import { genFunction } from './functions.js';
import { resolveStructs } from './structs.js';

export function generateAsm(ast) {
    let output = `; B"H - Generated by Awtsmoos C\n.subsystem console\n`;
    
    // 1. Resolve Struct Layouts
    const structLayouts = resolveStructs(ast.structs);

    // 2. Imports
    const dlls = {};
    const importedFunctions = new Set();
    
    for (const imp of ast.imports) {
        if (!dlls[imp.dll]) dlls[imp.dll] = [];
        dlls[imp.dll].push(imp.func);
        importedFunctions.add(imp.func);
    }
    for (const dll in dlls) {
        output += `.import ${dll} ${dlls[dll].join(' ')}\n`;
    }

    // 3. Data & Globals
    const stringLiterals = new Map();
    let strCount = 0;
    function getStringLabel(str) {
        if (stringLiterals.has(str)) return stringLiterals.get(str);
        const lbl = `str_${strCount++}`;
        stringLiterals.set(str, lbl);
        return lbl;
    }

    output += `\n.data\n`;
    
    // Globals
    for (const g of ast.globals) {
        if (g.type.ptr > 0 && typeof g.value === 'string' && g.value.startsWith('"')) {
            const val = g.value.slice(1, -1);
            const lbl = getStringLabel(val);
            output += `${g.name}: ${lbl}\n`;
        } else if (g.value !== null) {
            // If it's a number, output bytes (little endian)
            if (/^-?\d+$/.test(g.value) || /^-?0x[0-9a-fA-F]+$/.test(g.value)) {
                output += `${g.name}: ${g.value}\n`;
            } else {
                output += `${g.name}: ${g.value}\n`;
            }
        } else {
             // Zero init
             let size = 8;
             if (g.type.base !== 'int' && g.type.base !== 'char' && g.type.ptr === 0) {
                 const sl = structLayouts.get(g.type.base);
                 if (sl) size = sl.size;
             }
             const zeros = new Array(size).fill(0).join(', ');
             output += `${g.name}: ${zeros}\n`;
        }
    }

    let codeOutput = `\n.code\n`;
    const definedFunctions = new Set(ast.functions.map(f => f.name));
    
    // Validate Calls: Ensure all called functions are defined or imported
    // This is a rough check; detailed checking happens during genFunction traversal,
    // but we can pass the sets to the context.

    const ctx = {
        structLayouts,
        definedFunctions,
        importedFunctions,
        getStringLabel
    };

    for (const func of ast.functions) {
        codeOutput += genFunction(func, ctx);
    }
    
    if (ast.functions.find(f => f.name === 'main')) {
         codeOutput += `
start:
SUB RSP, 40
CALL main
XOR RCX, RCX
`;
         // Handle exit/ExitProcess resolution for start
         if (definedFunctions.has('exit') || importedFunctions.has('exit')) {
             codeOutput += `CALL exit\n`;
         } else if (importedFunctions.has('ExitProcess')) {
             codeOutput += `CALL ExitProcess\n`;
         } else {
             // Fallback: Assume ExitProcess is available if standard KERNEL32 was imported
             // But if not, we might crash.
             // We'll output ExitProcess and hope it was imported.
             codeOutput += `CALL ExitProcess\n`;
         }
    }

    // Emit String Literals
    for (const [str, lbl] of stringLiterals) {
        output += `${lbl}: "${str}"\n`;
    }

    output += codeOutput;
    return output;
}