// B"H
/** @file GossipRuntime.js @description NPC gossip panel contracts: greeting, quest markers, service choices, and starter-zone clarity. */
import { npcById } from "./NpcServiceRegistry.js";
import { availableQuestsForNpc, completeQuestsForNpc, ensureMissionState } from "../missions/QuestGossipRuntime.js";
function serviceLabel(service) { return ({ trainer:"Train abilities", vendor:"Browse goods", repair:"Repair gear", inn:"Rest at inn", hearth:"Make this inn your home", bank:"Open storehouse", mailbox:"Open mailbox", profession:"Learn profession", guard:"Ask about danger", quest:"Available shlichus" }[service] || service); }
export function questMarkerForNpc(olam, npcId) { const npc = npcById(npcId); if (!npc) return "none"; if (completeQuestsForNpc(olam, npc.name).length) return "quest-complete"; if (availableQuestsForNpc(olam, npc.name).length) return "quest-available"; const s = ensureMissionState(olam); if ((npc.quests || []).some(id => s.active[id])) return "quest-progress"; return "none"; }
export function serviceChoicesForNpc(olam, npcId) { const npc = npcById(npcId); if (!npc) return []; const choices = []; for (const q of completeQuestsForNpc(olam, npc.name)) choices.push({ id:`turnin:${q.id}`, kind:"questTurnIn", label:`Complete: ${q.title}`, missionId:q.id }); for (const q of availableQuestsForNpc(olam, npc.name)) choices.push({ id:`accept:${q.id}`, kind:"questAccept", label:`Accept: ${q.title}`, missionId:q.id }); for (const service of npc.services || []) if (service !== "quest") choices.push({ id:`${service}:${npc[`${service}Id`] || npc.vendorId || npc.trainerId || npc.innId || npc.id}`, kind:service, label:serviceLabel(service), service }); return choices; }
export function gossipPayload(olam, npcId) { const npc = npcById(npcId); if (!npc) return { open:false, ok:false, reason:"missing-npc", npcId }; const payload = { open:true, ok:true, npcId:npc.id, npcName:npc.name, greeting:npc.greeting, marker:questMarkerForNpc(olam, npc.id), choices:serviceChoicesForNpc(olam, npc.id) }; olam?.ayshPeula?.("ui event", "npcGossip", payload); return payload; }
export default { gossipPayload, questMarkerForNpc, serviceChoicesForNpc };
