// B"H
/** @file NpcChossidDirect.js @description Tight NPC proxy without duplicate pointer hijack. */
import * as THREE from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
import { buildNpcChossid } from "../../Olam/worlds/mitzvahWorld/builders/npc/buildNpcChossid.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
import { selectNpcTarget, isNpcTargeted } from "./NpcTargetRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
const LOG='B"H | NPC_TIGHT_PROXY_HIT_PROOF';
const arr=v=>Array.isArray(v)?v:v&&typeof v==='object'?[v.x||0,v.y||0,v.z||0]:[0,0,0];
function norm(o={}){const id=o.id||o.name||'npc_chossid_real_glb';return{...o,id,name:o.name||id,displayName:o.displayName||o.name||id,position:arr(o.position),rotation:arr(o.rotation),scale:o.scale??1,proximity:o.proximity??9,talkDistance:o.talkDistance??7};}
function push(list,item){if(Array.isArray(list)&&item&&!list.includes(item))list.push(item);}function root(o){return o?.scene||o?.nivrayimGroup?.parent||null;}function inTree(r,n){for(let p=n;p;p=p.parent)if(p===r)return true;return false;}
function mount(o,m,id){const r=root(o);if(r&&!inTree(r,m))r.add(m);Object.assign(m.userData||={},{npcDirectId:id,singleCanonicalNpcRoot:true,realChossidGlbNpc:true,nefeshId:id});}
function pos(n){const r=n?.mesh||n?.raycastMesh||n?.interactionMesh;if(r?.getWorldPosition)return r.getWorldPosition(new THREE.Vector3());return r?.position||null;}function dist(b){const a=pos(b?.olam?.player||b?.olam?.chossid),c=pos(b);return a&&c?Math.hypot(a.x-c.x,a.z-c.z):Infinity;}
function toast(o,text,color='#ffd966'){o?.ayshPeula?.('ui event','effectsOverlay',{text,color});}
function bbox(x){x.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(x),s=new THREE.Vector3();b.getSize(s);return{min:b.min.toArray(),max:b.max.toArray(),size:s.toArray()};}
function makeProxy(mesh,bridge){const p=new THREE.Mesh(new THREE.CapsuleGeometry(.38,1.35,4,8),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,colorWrite:false}));p.name=(bridge.name||mesh.name)+'_TIGHT_NPC_TAP_PROXY';p.position.set(0,1.35,0);p.visible=true;p.frustumCulled=false;p.nivraAwtsmoos=bridge;Object.assign(p.userData||={},{tightNpcTapProxy:true,mobileTapProxy:true,selectableTarget:true,dialogueTarget:true,friendlyNpc:true,npc:true,skipRaycast:false,skipOctree:true,noOctree:true});mesh.add(p);return p;}
function openOrMessage(b,actor={}){const d=dist(b),max=Number(b.talkDistance||b.proximity||7);if(d>max){toast(b.olam,`Move closer to ${b.name||'the chossid'} to talk.`, '#ffd966');b.__lastFarNpcTalkProof={at:Date.now(),distance:d,max,keptTarget:true};console.info(LOG,{stage:'too-far-kept-target',name:b.name,distance:d,max});return true;}b.__openingDialogueNow=true;const ok=b.__originalNpcAyshPeula?.('accepted interaction',{...actor,directHit:true});b.__openingDialogueNow=false;console.info(LOG,{stage:'open-dialogue-normal-input',name:b.name,ok});return ok!==false;}
function patchBridge(b){if(b.__npcDirectPatched)return;b.__originalNpcAyshPeula=b.ayshPeula?.bind(b);b.ayshPeula=(action,actor={})=>{const s=String(action||'');if(/pointerdown|touchstart/i.test(s))return true;if(/accepted interaction|interact|click|tap|pointerup|target/i.test(s)){if(!isNpcTargeted(b.olam,b)){selectNpcTarget(b,{source:s,type:s,isTouch:true,directHit:true,gestureId:actor?.gestureId||Date.now()});return true;}if(Date.now()-Number(b.__targetSelectOnlyAt||0)<420)return true;return openOrMessage(b,actor);}return b.__originalNpcAyshPeula?b.__originalNpcAyshPeula(action,actor):true;};b.__npcDirectPatched=true;}
function markVisual(mesh,bridge){mesh.traverse?.(o=>{o.frustumCulled=false;o.nivraAwtsmoos=bridge;Object.assign(o.userData||={},{npcVisualOnly:true,skipOctree:true,noOctree:true});if((o.isMesh||o.isSkinnedMesh)&&!o.userData.invisibleRayProxy)o.visible=true;});}
export default class NpcChossidDirect{type='interactiveNpc';interactable=true;friendlyNpc=true;dialogueTarget=true;selectableTarget=true;heesHawveh=true;constructor(options={},olam=null){this.options=options;this.definition=norm(options);this.name=this.definition.displayName;this.id=this.definition.id;this.position=this.definition.position;this.rotation=this.definition.rotation;this.proximity=this.definition.proximity;this.talkDistance=this.definition.talkDistance;this.olam=olam;}async heescheel(o){this.olam=o||this.olam;const [mesh]=await buildNpcChossid(this.olam?.scene,null,this.definition,this.olam);mesh.name=this.definition.id;this.mesh=mesh;this.scene=mesh;mount(this.olam,mesh,this.definition.id);const bridge=mesh?.nivraAwtsmoos||this;this.bridge=bridge;Object.assign(bridge,{olam:this.olam,mesh,selectableTarget:true,dialogueTarget:true,friendlyNpc:true,interactable:true,talkDistance:this.talkDistance,proximity:this.proximity});markVisual(mesh,bridge);const proxy=makeProxy(mesh,bridge);bridge.raycastMesh=proxy;bridge.interactionMesh=proxy;patchBridge(bridge);push(this.olam?.interactableNivrayim,bridge);push(this.olam?.meshesToInteractWith,proxy);this.isReady=true;this.olam.__npcChossidReports||=[];const proof={stage:'tight-proxy-normal-input-no-hijack',name:bridge.name,raycastMesh:proxy.name,bbox:bbox(proxy),visualBBox:bbox(mesh)};this.olam.__npcChossidReports.push(proof);globalThis.__MITZVAH_NPC_CHOSSID_PROOF__=()=>this.olam.__npcChossidReports;console.info(LOG,proof);return this;}ayshPeula(action,actor){return this.bridge?.ayshPeula?.(action,actor)||false;}heesHawvoos(dt=1/60){this.bridge?.heesHawvoos?.(dt);}}
