// B"H
/**
 * @file NpcTargetRuntime.js
 * @description Friendly NPC targeting covenant. The first clean tap only
 * selects: the ring and the top frame appear. A later clean tap, after the same
 * browser gesture has passed, opens dialogue. Thus the Awtsmoos prevents one
 * physical tap from becoming two actions in the vessel.
 */
import { clearFriendlyNpcTarget as clearVisualTarget, clearNpcTargetVisual, ensureNpcTargetVisual } from "./NpcTargetVisualRuntime.js?compact=true&v=visible-house-mesh-only-octree-20260708-bh1";
const FRAME_ID="awts-friendly-target-frame",EFFECT_COLOR="#8de8ff",OPEN_DELAY=520;
const now=()=>Date.now();
const eventOf=(ctx={})=>ctx.event||ctx.originalEvent||ctx;
const nameOf=npc=>npc?.name||npc?.displayName||npc?.definition?.displayName||npc?.options?.title||"NPC";
const rootOf=n=>n?.raycastMesh||n?.interactionMesh||n?.mesh||n?.modelMesh||n?.guf||null;
const list=olam=>(olam?.interactableNivrayim||[]).filter(n=>n?.friendlyNpc||n?.interactable);
const selected=olam=>olam?.__selectedFriendlyNpc||null;
function posOf(n){const r=rootOf(n);if(r?.getWorldPosition)return r.getWorldPosition(r.position?.clone?.()||{x:0,y:0,z:0});return r?.position||n?.position||null;}
function playerOf(olam){return olam?.chossid||olam?.player||null;}
function distance(olam,npc){const a=posOf(playerOf(olam)),b=posOf(npc);return a&&b?Math.hypot(a.x-b.x,a.z-b.z):Infinity;}
function facing(){return true;}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function hp(npc){const cur=Number(npc?.hp??npc?.health?.current??npc?.mesh?.userData?.hp??100),max=Number(npc?.maxHp??npc?.health?.max??npc?.mesh?.userData?.maxHp??cur??100);return{cur:Number.isFinite(cur)?cur:100,max:Number.isFinite(max)&&max>0?max:100};}
function ensureTargetFrame(){if(typeof document==="undefined")return null;let el=document.getElementById(FRAME_ID),style=document.getElementById(`${FRAME_ID}-style`);const css=`#${FRAME_ID}{position:fixed;top:max(102px,calc(env(safe-area-inset-top) + 102px));left:max(22px,env(safe-area-inset-left));z-index:2147482700;width:min(354px,calc(100vw - 44px));padding:9px 12px 10px;border-radius:18px;background:linear-gradient(145deg,rgba(8,13,23,.92),rgba(5,8,7,.86));border:2px solid rgba(255,220,90,.88);box-shadow:0 0 0 2px rgba(0,0,0,.24),0 12px 26px rgba(0,0,0,.38),inset 0 1px rgba(255,255,255,.1);font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#fff;text-shadow:0 2px 4px #000;pointer-events:none}.awts-target-title{display:flex;align-items:center;gap:10px;font-weight:900;font-size:16px}.awts-target-portrait{width:38px;height:38px;min-width:38px;border-radius:50%;display:grid;place-items:center;background:radial-gradient(circle at 35% 25%,#fff7b3,#966b18 70%);border:2px solid rgba(255,235,146,.92);color:#1b1100;text-shadow:none}.awts-target-readout{min-width:0;flex:1}.awts-target-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.awts-target-sub{font-size:11px;opacity:.86;margin-top:2px}.awts-target-bar{height:13px;border-radius:999px;overflow:hidden;background:rgba(255,255,255,.14);border:1px solid rgba(0,0,0,.35);margin-top:7px}.awts-target-fill{height:100%;background:linear-gradient(90deg,#277a35,#58dc72 65%,#9cffaa)}.awts-target-hint{font-size:11px;opacity:.9;margin-top:4px;color:#ffe28a}#${FRAME_ID}.hidden{display:none!important}@media(max-width:760px){#${FRAME_ID}{top:max(96px,calc(env(safe-area-inset-top) + 96px));left:22px;width:min(330px,calc(100vw - 44px));padding:8px 10px}.awts-target-title{font-size:15px}.awts-target-portrait{width:34px;height:34px;min-width:34px}.awts-target-bar{height:11px}}`;if(!style){style=document.createElement("style");style.id=`${FRAME_ID}-style`;document.head.appendChild(style);}style.textContent=css;if(!el){el=document.createElement("div");el.id=FRAME_ID;document.body.appendChild(el);}return el;}
function updateTargetFrame(npc,patch={}){const el=ensureTargetFrame();if(!el)return;const h=hp(npc),pct=Math.max(0,Math.min(100,h.cur/Math.max(1,h.max)*100)),d=distance(npc?.olam,npc);el.classList.remove("hidden");el.innerHTML=`<div class="awts-target-title"><div class="awts-target-portrait">ח</div><div class="awts-target-readout"><div class="awts-target-name">${esc(nameOf(npc))}</div><div class="awts-target-sub">Friendly NPC${Number.isFinite(d)?` · ${d.toFixed(1)}m`:""}</div></div></div><div class="awts-target-bar"><div class="awts-target-fill" style="width:${pct}%"></div></div><div class="awts-target-hint">${esc(patch.hint||"Target selected — tap again to talk")}</div>`;globalThis.__AWTSMOOS_TARGET_FRAME_PROOF__={at:now(),name:nameOf(npc),hp:h,persistent:true,frameVisible:true,position:"top-left-beside-health",twoTap:true};}
function hideTargetFrame(){const el=typeof document!=="undefined"&&document.getElementById(FRAME_ID);if(el)el.classList.add("hidden");}
function toast(olam,text,color=EFFECT_COLOR){if(!olam)return;const t=now();if(olam.__lastNpcTargetToast&&t-olam.__lastNpcTargetToast.at<650&&olam.__lastNpcTargetToast.text===text)return;olam.__lastNpcTargetToast={at:t,text};olam.ayshPeula?.("ui event","effectsOverlay",{text,color});}
function setFields(olam,npc){olam.__selectedFriendlyNpc=npc;olam.__selectedNpc=npc;olam.__selectedTarget=npc;olam.selectedTarget=npc;olam.currentTarget=npc;olam.targetedNivra=npc;olam.focusedNivra=npc;globalThis.__MITZVAH_SELECTED_TARGET__=npc;}
function publishDiag(olam,patch={}){if(!olam)return null;olam.__mitzvahNpcDiag={...(olam.__mitzvahNpcDiag||{}),at:now(),friendlyCount:list(olam).length,targetableCount:list(olam).filter(n=>n?.interactable&&rootOf(n)).length,selected:nameOf(selected(olam)),selectedPersistent:Boolean(selected(olam)),...patch};globalThis.__MITZVAH_NPC_DIAG__=()=>olam.__mitzvahNpcDiag;return olam.__mitzvahNpcDiag;}
function meta(ctx={}){const e=eventOf(ctx),raw=ctx.button??e?.button,type=String(ctx.pointerType||e?.pointerType||ctx.type||e?.type||ctx.source||"").toLowerCase(),kind=ctx.isTouch||/touch|tap|mobile/.test(type)?"touch":"mouse",button=Number.isFinite(Number(raw))?Number(raw):0;return{kind,button,right:button===2||ctx.contextMenu===true||e?.type==="contextmenu",touch:kind==="touch",primary:button===0||button===-1||!Number.isFinite(button)};}
export function npcTargetMeta(ctx={}){return meta(ctx);}
export function isNpcTargeted(olam,npc){return Boolean(npc&&selected(olam)===npc);}
export function selectNpcTarget(npc,ctx={}){const olam=npc?.olam;if(!olam||!npc)return false;if(olam.__selectedFriendlyNpc&&olam.__selectedFriendlyNpc!==npc)clearNpcTargetVisual(olam.__selectedFriendlyNpc);setFields(olam,npc);const t=now();npc.__targetedAt=t;npc.__targetSelectOnlyAt=t;npc.__targetGestureId=ctx.gestureId||t;npc.isSelectedTarget=true;ensureNpcTargetVisual(npc,meta(ctx));olam.ayshPeula?.("ui event","targetFrame",{id:npc.id||npc.name,name:nameOf(npc),type:npc.type||"friendly-npc",hp:hp(npc).cur,maxHp:hp(npc).max,persistent:true,position:"top-left-beside-health"});updateTargetFrame(npc,{hint:"Target selected. Tap again to talk."});toast(olam,`Targeted ${nameOf(npc)}.`);publishDiag(olam,{lastClickedNpc:nameOf(npc),lastAction:"target-only",twoTap:true,proof:"first-tap-targets-second-tap-talks-20260708-bh1"});return true;}
export function clearFriendlyNpcTarget(olam,reason="explicit-clear"){if(!olam)return false;if(reason==="empty-click"||reason==="synthetic-miss")return false;olam.ayshPeula?.("ui event","clearTargetFrame",{clear:true,reason});const cleared=clearVisualTarget(olam);olam.__selectedFriendlyNpc=olam.__selectedNpc=olam.__selectedTarget=olam.selectedTarget=olam.currentTarget=olam.targetedNivra=olam.focusedNivra=null;hideTargetFrame();publishDiag(olam,{lastAction:"clear",reason});return cleared;}
export function npcInteractionDecision(npc,ctx={}){const olam=npc?.olam,m=meta(ctx);if(!isNpcTargeted(olam,npc))return{action:"target",meta:m,reason:"not-selected"};const age=now()-Number(npc.__targetSelectOnlyAt||0),sameGesture=ctx.gestureId&&ctx.gestureId===npc.__targetGestureId;if(age<OPEN_DELAY||sameGesture)return{action:"wait",meta:m,reason:"same-gesture-target-only",message:"Target selected. Tap again to talk."};const d=distance(olam,npc),max=Number(npc?.talkDistance||npc?.proximity||7);updateTargetFrame(npc,{hint:"Tap confirmed — opening dialogue"});if(!ctx.directHit)return{action:"wait",meta:m,reason:"not-direct-hit",distance:d,maxDistance:max,message:"Tap the selected target to talk."};if(d>max)return{action:"wait",meta:m,reason:"too-far",distance:d,maxDistance:max,message:"Move closer to interact."};if(!facing(olam,npc))return{action:"wait",meta:m,reason:"not-facing",distance:d,maxDistance:max,message:"Face the target to interact."};publishDiag(olam,{lastClickedNpc:nameOf(npc),lastAction:"second-tap-open",distance:d,twoTap:true});return{action:"open",meta:m,reason:"second-clean-tap",distance:d,maxDistance:max};}
export function explainNpcWait(npc){return`Tap ${nameOf(npc)} again to talk.`;}
