// B"H
/** @file ChossidNpcTransform.js @description Single real GLB NPC transform, target proxy, animation, and two-tap dialogue bridge. */
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { createChossidNpcInventory } from "./ChossidNpcInventory.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { applyChossidNpcStyle } from "./ChossidNpcStyle.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { attachChossidNpcAnimator } from "./ChossidNpcAnimator.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { applyNpcVisualLod, npcVisualTreeProof } from "../../../../systems/npc/NpcVisualLod.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { attachQuestMarker } from "../../../../systems/quests/QuestMarkers.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { handleQuestTalk, questDialoguePayload } from "../../../../systems/quests/QuestDialogueRuntime.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { npcInteractionDecision, selectNpcTarget } from "../../../../dvarim/npc/NpcTargetRuntime.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
const at=(list,i,f)=>list?.[i]!==undefined?list[i]:f,arr=(v,f)=>Array.isArray(v)?v:f;
function scaleNpc(npc,scale){Array.isArray(scale)?npc.scale.set(at(scale,0,1),at(scale,1,1),at(scale,2,1)):npc.scale.setScalar(scale||1);}
function pushUnique(list,item){if(Array.isArray(list)&&item&&!list.includes(item))list.push(item);}
function show(olam,text,color="#ffffff"){olam?.ayshPeula?.("ui event","effectsOverlay",{text,color});}
function diag(bridge,patch={}){const olam=bridge?.olam;if(!olam)return null;const list=(olam.interactableNivrayim||[]).filter(n=>["customNpc","medabeir","interactiveNpc"].includes(n?.type));olam.__mitzvahNpcDiag={...(olam.__mitzvahNpcDiag||{}),at:Date.now(),friendlyCount:list.length,targetableCount:list.filter(n=>n?.interactable&&(n?.raycastMesh||n?.interactionMesh||n?.mesh)).length,selected:olam.__selectedFriendlyNpc?.name||null,...patch};globalThis.__MITZVAH_NPC_DIAG__=()=>olam.__mitzvahNpcDiag;return olam.__mitzvahNpcDiag;}
function defaultDialogues(name){return[`B"H! I am ${name}.`,"Every mitzvah reveals another spark of the Awtsmoos."];}
function openDialogue(bridge,chossid){bridge.state="talking";const qp=questDialoguePayload(bridge.olam,bridge),hq=handleQuestTalk(bridge.olam,bridge);attachQuestMarker(bridge.mesh,bridge,bridge.olam);const first=hq?.line||qp?.line||bridge.dialogues[0]||`B"H! ${bridge.name} is here.`;diag(bridge,{lastClickedNpc:bridge.name,lastAction:"talk-second-tap",lastDialoguePayload:{name:bridge.name,line:first,source:"second-tap-chossid-glb-npc"}});show(bridge.olam,`${bridge.name}: ${first}`,"#9fffe0");bridge.olam?.ayshPeula?.("ui event","openNpcChallengeOverlay",{name:bridge.name,npcName:bridge.name,lines:[first,...bridge.dialogues],quest:hq||qp,source:"second-tap-chossid-glb-npc"});if(chossid){chossid.nivraTalkingTo=bridge;chossid.state="talking";}return true;}
function handleAccepted(bridge,chossid,actor={}){applyNpcVisualLod(bridge,bridge.olam);attachQuestMarker(bridge.mesh,bridge,bridge.olam);const decision=npcInteractionDecision(bridge,{...actor,directHit:true});if(decision.action==="target"){selectNpcTarget(bridge,{...actor,directHit:true});diag(bridge,{lastClickedNpc:bridge.name,lastAction:"target-only",decision});return true;}if(decision.action==="wait"){show(bridge.olam,decision.message||"Target selected. Tap again to talk.","#ffd966");diag(bridge,{lastClickedNpc:bridge.name,lastAction:"target-wait",decision});return true;}return openDialogue(bridge,chossid);}
function bridgeFor(npc,def,inventory){const name=def.displayName||def.id||"Chossid",lines=def.dialogues?.length?def.dialogues:defaultDialogues(name);return{type:"interactiveNpc",id:def.id,name,role:def.role||"friend",definition:def,questId:def.questId||null,mesh:npc,raycastMesh:npc,interactionMesh:npc,interactable:true,selectableTarget:true,dialogueTarget:true,friendlyNpc:true,npc:true,proximity:def.proximity||7,talkDistance:def.proximity||7,dialogue:true,dialogues:lines,state:"idle",hp:def.hp||100,maxHp:def.hp||100,faction:def.faction||"chossidim",isFriendly:def.isFriendly!==false,isReady:true,heesHawveh:true,__npcLowCost:true,__awtsmoosSimplePrecomputedNpc:true,inventory,equipped:inventory.equipped,shop:def.shop||null,quests:def.quests||[],takeDamage(amount=0){this.hp=Math.max(0,this.hp-Math.max(0,Number(amount)||0));npc.userData.hp=this.hp;if(this.hp<=0){this.wasSealayked=true;npc.visible=false;}},heal(amount=10){this.hp=Math.min(this.maxHp,this.hp+Math.max(0,Number(amount)||0));npc.userData.hp=this.hp;},ayshPeula(action,chossid){const text=String(action);if(text==="mouseEnter"){npc.userData.isHovered=true;applyNpcVisualLod(this,this.olam);attachQuestMarker(npc,this,this.olam);diag(this,{lastAction:"hover"});return true;}if(text==="mouseLeave"){npc.userData.isHovered=false;return true;}if(/accepted interaction/i.test(text))return handleAccepted(this,chossid,chossid||{});if(/target|click|tap|pointer/i.test(text)){return handleAccepted(this,null,{source:text,directHit:true});}return false;}};}
function ensureNpcData(npc,def,bridge,inventory){Object.assign(npc.userData||={},{mitzvahWorldNpcRoot:true,isNpc:true,npc:true,friendly:true,friendlyNpc:true,selectableTarget:true,dialogueTarget:true,skipRaycast:false,isLiving:true,lowCostNpc:true,awtsmoosSimplePrecomputedNpc:true,skipOctree:true,noOctree:true,nefeshType:"chossidNpc",nefeshId:npc.name,displayName:def.displayName||npc.name,targetName:bridge.name,questId:bridge.questId,interactable:true,hp:bridge.hp,maxHp:bridge.maxHp,faction:bridge.faction,inventory,neverCullNpc:true,neverHideNpc:true,oneVisualNpcVessel:true,duplicateNpcBodyPreventedAtSource:true,twoTapDialogue:true});npc.visible=true;npc.frustumCulled=false;}
function markChild(child,bridge,inventory){if(!child)return;child.nivraAwtsmoos=bridge;Object.assign(child.userData||={},{ownerNpc:bridge,interactable:true,isNpcPart:true,isLiving:true,npc:true,friendlyNpc:true,selectableTarget:true,dialogueTarget:true,skipRaycast:false,lowCostNpc:true,skipOctree:true,noOctree:true,inventory,neverCullNpc:true,neverHideNpc:true});child.frustumCulled=false;if(child.isMesh||child.isSkinnedMesh){child.visible=true;child.castShadow=false;child.receiveShadow=true;}}
function createTargetProxy(npc,bridge){const proxy=new THREE.Mesh(new THREE.BoxGeometry(2.6,4.6,2),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,colorWrite:false}));proxy.name=`${bridge.name||npc.name}_NPC_TARGET_PROXY`;proxy.position.set(0,2.2,0);proxy.visible=true;proxy.frustumCulled=false;proxy.nivraAwtsmoos=bridge;Object.assign(proxy.userData||={},{awtsmoosRayProxy:true,mobileTapProxy:true,invisibleRayProxy:true,selectableTarget:true,dialogueTarget:true,friendlyNpc:true,npc:true,skipRaycast:false,skipOctree:true,noOctree:true,neverHideNpc:true,neverCullNpc:true});npc.add(proxy);bridge.raycastMesh=proxy;bridge.interactionMesh=proxy;return proxy;}
export function applyChossidNpcTransform(npc,def,olam=null,animations=[]){const pos=arr(def.position,[0,0,0]),rot=arr(def.rotation,[0,0,0]),scale=def.scale!==undefined?def.scale:1,inventory=createChossidNpcInventory(def);npc.name=def.id||"npc_chossid";npc.position.set(at(pos,0,0),at(pos,1,0),at(pos,2,0));npc.rotation.set(at(rot,0,0),at(rot,1,0),at(rot,2,0));scaleNpc(npc,scale);const bridge=bridgeFor(npc,def,inventory);bridge.olam=olam;attachChossidNpcAnimator(npc,animations,bridge);npc.nivraAwtsmoos=bridge;ensureNpcData(npc,def,bridge,inventory);applyChossidNpcStyle(npc,def);npc.traverse(child=>markChild(child,bridge,inventory));console.info('B"H | NPC_AFTER_APPLY_CHOSSID_TRANSFORM_TREE',npcVisualTreeProof(npc,"after-applyChossidNpcTransform-before-lod"));const proxy=createTargetProxy(npc,bridge);applyNpcVisualLod(bridge,olam,true);attachQuestMarker(npc,bridge,olam);if(olam){pushUnique(olam.nivrayim,bridge);olam.interactableNivrayim||=[];pushUnique(olam.interactableNivrayim,bridge);olam.meshesToInteractWith||=[];pushUnique(olam.meshesToInteractWith,proxy);pushUnique(olam.meshesToInteractWith,npc);diag(bridge,{lastAction:"registered-two-tap-glb",proxy:proxy.name,visualProof:npcVisualTreeProof(npc,"after-register-two-tap-glb")});}console.info('B"H | NPC_TARGET_PROXY_READY',{name:bridge.name,proxy:proxy.name,twoTapDialogue:true,firstTap:"target-only",secondTap:"dialogue",animations:animations?.map?.(a=>a.name)||[]});return npc;}
