/** B"H @module BattleCombatants Flat combatants. */
import { BATTLE_THEME as T } from './BattleTheme.js';
export const drawCombatantShowcase = (ctx, layout, stats, enemy) => { drawHero(ctx, layout.hero, stats); drawEnemy(ctx, layout.enemy, enemy); };
const drawHero = (ctx, spot, stats) => { ctx.save(); ctx.translate(spot.x, spot.y); const s = spot.size / 96; ctx.scale(s, s); drawHeroLegs(ctx); drawHeroCoat(ctx, stats?.garment?.icon || '✦'); drawHeroArms(ctx); drawHeroHead(ctx); ctx.restore(); };
const drawEnemy = (ctx, spot, enemy) => { ctx.save(); ctx.translate(spot.x, spot.y); const size = spot.size; ctx.fillStyle = '#090611'; ctx.beginPath(); ctx.arc(0, -size * .08, size * .31, 0, Math.PI * 2); ctx.fill(); ctx.fillRect(-size * .25, -size * .03, size * .5, size * .42); ctx.fillStyle = '#f9e36a'; ctx.fillRect(-size * .13, -size * .2, size * .08, size * .08); ctx.fillRect(size * .06, -size * .2, size * .08, size * .08); ctx.fillStyle = '#caa8ff'; ctx.font = `800 ${Math.round(size * .22)}px ${T.fonts.display}`; ctx.textAlign = 'center'; ctx.fillText(enemy?.glyph || 'נ', 0, size * .18); ctx.restore(); };
const drawHeroHead = ctx => { ctx.fillStyle = '#ffd9ad'; ctx.fillRect(-18, -55, 36, 32); ctx.fillStyle = '#0a0b10'; ctx.fillRect(-21, -65, 42, 13); ctx.fillRect(13, -62, 10, 42); ctx.fillStyle = '#111'; ctx.fillRect(-10, -43, 5, 5); ctx.fillRect(8, -43, 5, 5); ctx.fillRect(-6, -31, 18, 5); };
const drawHeroCoat = (ctx, icon) => { ctx.fillStyle = '#0b3b79'; ctx.fillRect(-24, -20, 48, 58); ctx.fillStyle = '#1976ba'; ctx.fillRect(-17, -18, 24, 55); ctx.fillStyle = '#dff7ff'; ctx.font = `800 18px ${T.fonts.display}`; ctx.textAlign = 'center'; ctx.fillText(icon, 0, 8); };
const drawHeroArms = ctx => { ctx.fillStyle = '#0b3b79'; ctx.fillRect(-37, -13, 13, 40); ctx.fillRect(24, -13, 13, 40); ctx.fillStyle = '#ffd9ad'; ctx.fillRect(-38, 27, 14, 14); ctx.fillRect(24, 27, 14, 14); };
const drawHeroLegs = ctx => { ctx.fillStyle = '#101723'; ctx.fillRect(-18, 36, 12, 42); ctx.fillRect(7, 36, 12, 42); ctx.fillStyle = '#050507'; ctx.fillRect(-20, 74, 17, 8); ctx.fillRect(5, 74, 17, 8); };
