// B"H

import { h, $ } from "../../ui/dom.js";
import { roomStatusLabel } from "./events.js";
import { metrics, selectedMission, selectedRoom } from "./store.js";
import { activityRows, fileRows, agentRows, actionRows, readableTime } from "./activity.js";
import { inspectorSections, selectedEvent } from "./inspector.js";
import { ROOM_TEMPLATES } from "./templates.js";
import { replayEvents, replayLabel } from "./replay.js";
import { reviewItems } from "./review.js";

/** B"H: Render the room OS as one action-derived mission control workspace. */
export function renderAll(state, api) { renderList(state, api); renderRoom(state); renderOut(state.lastResult); }
export function renderList(state, api) { const root = $("roomList"); if (!root) return; const rows = filteredMissions(state); root.replaceChildren(newRoomCard(state), commandCenter(state), ...(rows.length ? rows.map(row => roomButton(row, state, api)) : [emptyLobby(state)])); }
function filteredMissions(state) { const q = (state.search || "").toLowerCase(); return (state.missions || []).filter(row => { const status = roomStatusLabel(row); const text = `${row.mission?.goal || ""} ${row.mission?.id || ""} ${status}`.toLowerCase(); return (!q || text.includes(q)) && (state.filter === "all" || !state.filter || status === state.filter); }); }
function newRoomCard(state) { return h("article", { className: "awt-room-new-card" }, [h("strong", { text: "+ New room" }), h("select", { id: "roomTemplateSelect", value: state.selectedTemplate || "" }, [h("option", { value: "", text: "Choose template..." }), ...ROOM_TEMPLATES.map(t => h("option", { value: t.key, text: t.title }))]), h("textarea", { id: "newRoomGoal", placeholder: "Describe the mission room to create..." }), h("button", { id: "createRoomBtn", className: "primary", text: "Create room" })]); }
function commandCenter(state) { const counts = statusCounts(state); return h("article", { className: "awt-room-command-center" }, [h("strong", { text: "Command center" }), h("div", { className: "awt-room-card-metrics" }, [chip(`${state.missions.length} rooms`), chip(`${counts.running} running`), chip(`${counts.needs} needs human`), chip(`${counts.active} active`)])]); }
function statusCounts(state) { return (state.missions || []).reduce((a, row) => { const s = roomStatusLabel(row); if (s === "running") a.running++; if (s === "needs human") a.needs++; if (s === "active") a.active++; return a; }, { running: 0, needs: 0, active: 0 }); }
function emptyLobby(state) { const text = state.missions?.length ? "No rooms match this search." : "No mission rooms found yet."; return h("article", { className: "awt-room-empty" }, [h("strong", { text }), h("small", { text: "Create a room or refresh the lobby." })]); }
function roomButton(row, state, api) { const mission = row.mission || {}, room = row.collaboration || {}, status = roomStatusLabel(row); return h("button", { className: `awt-room-card is-${status.replace(/\s+/g, "-")} ${state.selectedMissionId === mission.id ? "is-active" : ""}`, data: { missionId: mission.id || "" }, on: { click: () => api.join(mission.id) } }, [h("span", { className: "awt-room-pulse", text: "●" }), h("strong", { text: mission.goal || mission.id || "Untitled room" }), h("small", { text: mission.id || "no-id" }), h("div", { className: "awt-room-card-metrics" }, [chip(status), chip(`${room.agents?.length || 0} agents`), chip(`${room.openUserMessages?.length || 0} open`)])]); }
function chip(text) { return h("span", { className: "awt-room-chip", text: String(text) }); }

export function renderRoom(state) { const workspace = $("roomWorkspace"); if (!workspace) return; if (!state.selectedMissionId) { workspace.className = "awt-room-workspace is-empty"; return workspace.replaceChildren(); } const mission = selectedMission(state), room = selectedRoom(state); workspace.className = "awt-room-workspace is-open"; workspace.replaceChildren(roomHeader(state, mission), quickNav(), metricsRibbon(state), replayBar(state), h("div", { className: "awt-room-os-grid" }, [conversationPane(room), activityPane(state), sidePane(state, room), inspectorPane(state), explorerPane(state), reviewPane(state)])); }
function quickNav() { return h("nav", { id: "roomQuickNav", className: "awt-room-quicknav" }, [jump("roomMessages", "Chat"), jump("roomCommandTable", "Activity"), jump("roomMembers", "Agents"), jump("roomExplorers", "Explorers"), jump("roomEventInspector", "Inspector"), jump("roomReviewQueue", "Review")]); }
function jump(id, text) { return h("a", { href: `#${id}`, text }); }
function roomHeader(state, mission) { return h("header", { className: "panel awt-room-open-head" }, [h("div", { className: "button-row" }, [button("closeRoomBtn", "← Rooms"), button("refreshRoomBtn", "Refresh"), button("copyRoomLinkBtn", "Copy link")]), h("div", { className: "awt-room-open-title" }, [h("p", { className: "eyebrow", text: "OPEN ROOM" }), h("h2", { id: "roomHeader", text: mission.goal || state.selectedMissionId }), h("small", { text: state.selectedMissionId })]), h("div", { id: "roomSocketState", className: `notice awt-room-socket is-${state.socketMode}`, text: socketText(state) })]); }
function metricsRibbon(state) { const m = metrics(state); return h("section", { id: "roomMetrics", className: "awt-room-metrics-ribbon" }, [metric("agents", m.agents), metric("actions", m.actions), metric("cmd", m.command || actionRows(state, "command").length), metric("files", m.writes), metric("browser", m.browser), metric("fails", m.failed || 0), metric("stream", m.status), metric("reviews", reviewItems(state).length)]); }
function metric(label, value) { return h("article", { className: "awt-room-metric" }, [h("span", { text: label }), h("strong", { text: String(value) })]); }
function replayBar(state) { return h("section", { className: "panel awt-room-replay" }, [h("strong", { text: replayLabel(state) }), h("div", { className: "button-row" }, [button("replayStartBtn", "Replay"), button("replayPrevBtn", "◀"), button("replayNextBtn", "▶"), button("replayLiveBtn", "Live")])]); }

function conversationPane(room) { const messages = [...(room.messages || []), ...(room.userMessages || []).map(msg => ({ ...msg, fromAgent: "human", kind: "user-message" }))].sort((a, b) => String(a.at).localeCompare(String(b.at))).slice(-100); return h("section", { className: "panel awt-room-conversation" }, [h("h3", { text: "Conversation" }), h("div", { id: "roomMessages", className: "awt-room-messages" }, messages.length ? messages.map(messageNode) : [h("div", { className: "empty-state", text: "No messages yet." })]), composer()]); }
function messageNode(msg) { return h("article", { className: `awt-room-message ${msg.fromAgent === "human" ? "is-user" : ""}` }, [h("strong", { text: msg.fromAgent || msg.from || "agent" }), h("p", { text: msg.body || msg.subject || msg.note || "" }), h("small", { text: `${msg.kind || "message"} · ${msg.at ? new Date(msg.at).toLocaleTimeString() : ""}` })]); }
function composer() { return h("div", { className: "awt-room-composer" }, [h("textarea", { id: "roomMessage", placeholder: "Continue fixing, approve, reject, or steer the agents..." }), h("div", { className: "button-row" }, [h("label", {}, ["Block", h("input", { id: "roomBlockAgents", type: "checkbox", checked: true })]), button("sendRoomMessageBtn", "Send", "primary"), button("allowRoomContinueBtn", "Continue")])]); }
function activityPane(state) { const events = activityRows({ ...state, events: replayEvents(state) }, state.eventSearch); return h("section", { className: "panel awt-room-activity" }, [h("h3", { id: "roomCommandsHeader", text: `Activity · ${events.length}` }), h("input", { id: "roomEventSearch", value: state.eventSearch || "", placeholder: "Search events, files, commands, stdout..." }), h("div", { id: "roomCommandTable", className: "awt-room-command-table" }, events.length ? events.map(evt => eventRow(evt, state)) : [h("div", { className: "empty-state", text: "No room activity yet." })])]); }
function eventRow(evt, state) { return h("button", { className: `awt-activity-row ${state.selectedEventId === evt.id ? "is-selected" : ""}`, data: { eventId: evt.id } }, [h("strong", { text: `${readableTime(evt.at)} · ${evt.actor} · ${evt.type}` }), h("small", { text: evt.title })]); }
function inspectorPane(state) { const event = selectedEvent(state); return h("section", { id: "roomEventInspector", className: "panel awt-room-inspector" }, [h("h3", { text: "Inspector / API Builder" }), ...inspectorSections(event).map(section)]); }
function section(item) { return h("details", { className: "awt-inspector-section", open: item.title === "Summary" || item.title === "Action JSON" }, [h("summary", { text: item.title }), h("pre", { text: item.body })]); }
function sidePane(state, room) { return h("aside", { className: "awt-room-side" }, [members(state, room), files(state), artifacts(state)]); }
function members(state, room) { const agents = agentRows(state), joined = room.agents || []; return h("section", { id: "roomMembers", className: "panel awt-room-members" }, [h("h3", { text: "Agents" }), ...(agents.length ? agents.slice(0, 12).map(a => h("span", { className: "awt-room-member", text: `${a.agentId} · ${a.count} actions · ${a.failures} fails` })) : joined.map(a => h("span", { className: "awt-room-member", text: `${a.name || a.agentId} · ${a.status || "active"}` }))) ]); }
function files(state) { const touched = fileRows(state).slice(0, 20); return h("section", { className: "panel awt-room-files" }, [h("h3", { text: "Filesystem" }), ...(touched.length ? touched.map(f => h("span", { className: "awt-room-file", text: `${f.path} · ${f.count}` })) : [h("p", { text: "No file events yet." })])]); }
function artifacts(state) { return h("section", { className: "panel awt-room-artifacts" }, [h("h3", { text: "Artifacts" }), h("p", { text: `${(state.events || []).filter(e => e.payload?.outputRef || e.payload?.artifact || e.payload?.screenshot).length} captured` })]); }
function explorerPane(state) { return h("section", { id: "roomExplorers", className: "panel awt-room-explorers" }, [h("h3", { text: "Explorers" }), explorer("Commands", actionRows(state, "command")), explorer("Browser", actionRows(state, "browser")), explorer("Mission", actionRows(state, "mission")), graphSummary(state)]); }
function explorer(title, rows) { return h("details", { open: title === "Commands" }, [h("summary", { text: `${title} · ${rows.length}` }), ...(rows.slice(-12).reverse().map(row => h("button", { className: "awt-activity-row", data: { eventId: row.id } }, [h("strong", { text: row.payload?.action || row.type }), h("small", { text: row.title })]))) ]); }
function graphSummary(state) { const nodes = new Set(), edges = []; for (const e of state.events || []) { nodes.add(e.actor); nodes.add(e.target); edges.push(`${e.actor} → ${e.target}`); } return h("details", {}, [h("summary", { text: `Knowledge graph · ${nodes.size} nodes / ${edges.length} edges` }), h("pre", { text: edges.slice(-30).join("\n") || "No edges yet." })]); }
function reviewPane(state) { const items = reviewItems(state); return h("section", { id: "roomReviewQueue", className: "panel awt-room-review" }, [h("h3", { text: `Review queue · ${items.length}` }), ...(items.length ? items.map(reviewRow) : [h("p", { text: "No write events awaiting review." })])]); }
function reviewRow(item) { return h("article", { className: `awt-review-row is-${item.status}` }, [h("strong", { text: item.file }), h("small", { text: `${item.status} · ${item.title}` }), h("div", { className: "button-row" }, [button(`reviewApprove:${item.id}`, "Approve"), button(`reviewReject:${item.id}`, "Reject"), button(`reviewChanges:${item.id}`, "Changes")])]); }
function socketText(state) { if (state.socketMode === "websocket") return "WebSocket live"; if (state.socketMode === "connecting") return "Connecting WebSocket..."; if (state.socketMode === "eventsource") return `EventSource live (${state.socketError || "websocket fallback"})`; if (state.socketMode === "fallback-poll") return `Fallback polling: ${state.socketError || "socket unavailable"}`; return "Stream idle"; }
function button(id, text, className = "") { return h("button", { id, text, className }); }
export function renderActivity(state) { renderRoom(state); }
export function renderOut(value) { if ($("roomOut")) $("roomOut").textContent = JSON.stringify(value || {}, null, 2); }
export function setStatus(text) { if ($("roomStatus")) $("roomStatus").textContent = text; }
