// B"H
/** @file QuestGossipRuntime.js @description WoW-like quest offer, accept, progress, tracker, marker, and turn-in contracts for solo starter play. */
import MissionRegistry, { getMission } from "./MissionRegistry.js";
import { addBagItem } from "../inventory/BagRuntime.js";
import { npcForGiver } from "../npc/NpcServiceRegistry.js";
function playerOf(olam) { return olam?.player || olam?.chossid || olam || {}; }
export function ensureMissionState(olam) { const p = playerOf(olam); p.missionState ||= { active:{}, completed:{}, turnedIn:{}, declined:{} }; return p.missionState; }
function progressRows(mission, saved = {}) { return (mission?.objectives || []).map(o => ({ id:o.id, type:o.type, text:o.label, current:Number(saved[o.id] ?? o.progress ?? 0), needed:Number(o.required || 1), complete:Number(saved[o.id] ?? o.progress ?? 0) >= Number(o.required || 1) })); }
export function missionProgress(olam, missionId) { const s = ensureMissionState(olam), mission = getMission(missionId); return progressRows(mission, s.active[missionId]?.progress || {}); }
export function isMissionComplete(olam, missionId) { const rows = missionProgress(olam, missionId); return rows.length > 0 && rows.every(r => r.complete); }
export function prerequisitesMet(olam, mission) { const s = ensureMissionState(olam); return (mission?.prerequisites || []).every(id => s.turnedIn[id] || s.completed[id]); }
function objectiveLine(mission, objective, row) { const current = Number(row?.current ?? 0), needed = Number(row?.needed ?? objective.required ?? 1); return { id:objective.id, type:objective.type, text:objective.label, current, needed, complete:current >= needed, line:`${objective.label}: ${current}/${needed}` }; }
export function questTrackerPayload(olam) { const s = ensureMissionState(olam), active = [], completedReady = []; for (const id of Object.keys(s.active)) { const m = getMission(id); if (!m) continue; const rows = missionProgress(olam, id), complete = isMissionComplete(olam, id); active.push({ id, title:m.title, line:`${m.title} (${rows.filter(r => r.complete).length}/${rows.length})`, complete, returnTo:complete ? m.giverNpc : null, objectives:m.objectives.map((o, i) => objectiveLine(m, o, rows[i])) }); if (complete && !s.turnedIn[id]) completedReady.push({ id, title:m.title, returnTo:m.giverNpc }); } return { active, completedReady, count:active.length }; }
function markerForMission(olam, mission) { const s = ensureMissionState(olam); if (s.turnedIn[mission.id]) return null; if (s.active[mission.id]) return isMissionComplete(olam, mission.id) ? "yellow-question" : "gray-question"; return prerequisitesMet(olam, mission) ? "yellow-exclamation" : "gray-exclamation"; }
export function questMarkersPayload(olam) { const markers = MissionRegistry.map(m => { const npc = npcForGiver(m.giverNpc), marker = markerForMission(olam, m); return npc && marker ? { npcId:npc.id, npcName:npc.name, missionId:m.id, title:m.title, marker, kind:marker.includes("question") ? "turn-in" : "offer" } : null; }).filter(Boolean); return { markers, byNpc:Object.fromEntries(markers.map(m => [m.npcId, m])), count:markers.length }; }
export function emitMissionUiRefresh(olam, reason = "mission-refresh") { const tracker = questTrackerPayload(olam), markers = questMarkersPayload(olam); olam?.ayshPeula?.("ui event", "questTracker", tracker); olam?.ayshPeula?.("ui event", "questMarkers", markers); olam?.ayshPeula?.("ui event", "starterZoneHud", { questTracker:tracker, questMarkers:markers, reason }); return { tracker, markers, reason }; }
export function questOfferPayload(olam, missionId) { const m = getMission(missionId), s = ensureMissionState(olam); if (!m) return { open:false, ok:false, reason:"missing-mission", missionId }; const active = Boolean(s.active[m.id]), complete = isMissionComplete(olam, m.id), turnedIn = Boolean(s.turnedIn[m.id]); return { open:true, ok:true, id:m.id, title:m.title, giverNpc:m.giverNpc, levelRange:m.levelRange, story:m.story, objectives:progressRows(m), rewards:m.rewards, startItems:m.startItems || [], state:turnedIn ? "turned-in" : complete ? "complete" : active ? "active" : prerequisitesMet(olam, m) ? "available" : "locked", buttons:{ accept:!active && !turnedIn && prerequisitesMet(olam, m), decline:!active && !turnedIn, complete:active && complete && !turnedIn } }; }
export function acceptQuest(olam, missionId) { const payload = questOfferPayload(olam, missionId), s = ensureMissionState(olam); if (!payload.ok || !payload.buttons.accept) return { ok:false, reason:payload.state || payload.reason, missionId }; s.active[missionId] ||= { acceptedAt:Date.now(), progress:{} }; delete s.declined[missionId]; for (const id of payload.startItems || []) addBagItem(olam, id, { silent:true }); olam?.ayshPeula?.("ui event", "questAccepted", payload); const ui = emitMissionUiRefresh(olam, "quest-accepted"); return { ok:true, missionId, payload, ui }; }
export function declineQuest(olam, missionId) { const s = ensureMissionState(olam); s.declined[missionId] = Date.now(); const ui = emitMissionUiRefresh(olam, "quest-declined"); return { ok:true, missionId, ui }; }
export function progressQuestObjective(olam, missionId, objectiveId, amount = 1) { const s = ensureMissionState(olam), m = getMission(missionId); if (!m || !s.active[missionId]) return { ok:false, reason:"not-active" }; const o = m.objectives.find(x => x.id === objectiveId || x.type === objectiveId); if (!o) return { ok:false, reason:"missing-objective" }; const p = s.active[missionId].progress; p[o.id] = Math.min(Number(o.required || 1), Number(p[o.id] || 0) + Math.max(1, amount)); if (isMissionComplete(olam, missionId)) s.completed[missionId] = Date.now(); const result = { ok:true, missionId, objectiveId:o.id, progress:p[o.id], complete:Boolean(s.completed[missionId]) }; olam?.ayshPeula?.("ui event", "questProgress", result); result.ui = emitMissionUiRefresh(olam, "quest-progress"); return result; }
export function questTurnInPayload(olam, missionId) { const offer = questOfferPayload(olam, missionId); return { ...offer, turnInReady:offer.state === "complete", rewards:offer.rewards, rewardChoices:offer.rewards?.items || [] }; }
export function turnInQuest(olam, missionId, rewardChoiceId = null) { const s = ensureMissionState(olam), m = getMission(missionId); if (!m || !isMissionComplete(olam, missionId)) return { ok:false, reason:"not-complete" }; s.turnedIn[missionId] = Date.now(); delete s.active[missionId]; for (const id of m.rewards?.items || []) if (!rewardChoiceId || id === rewardChoiceId) addBagItem(olam, id, { silent:true }); olam?.ayshPeula?.("ui event", "questTurnedIn", { missionId, rewards:m.rewards }); const ui = emitMissionUiRefresh(olam, "quest-turned-in"); return { ok:true, missionId, rewards:m.rewards, ui }; }
export function availableQuestsForNpc(olam, npcName) { const s = ensureMissionState(olam); return MissionRegistry.filter(m => m.giverNpc === npcName && !s.active[m.id] && !s.turnedIn[m.id] && prerequisitesMet(olam, m)); }
export function completeQuestsForNpc(olam, npcName) { return MissionRegistry.filter(m => m.giverNpc === npcName && isMissionComplete(olam, m.id) && !ensureMissionState(olam).turnedIn[m.id]); }
export default { ensureMissionState, questOfferPayload, acceptQuest, declineQuest, progressQuestObjective, questTurnInPayload, turnInQuest, availableQuestsForNpc, completeQuestsForNpc, isMissionComplete, questTrackerPayload, questMarkersPayload, emitMissionUiRefresh };
