// B"H
const { f16 } = require('./f16.js');
function signedByte(x){return x>127?x-256:x;}
function dequantF32(bytes,n){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);const out=new Float32Array(n);for(let i=0;i<n;i++)out[i]=v.getFloat32(i*4,true);return out;}
function dequantF16(bytes,n){const out=new Float32Array(n);for(let i=0;i<n;i++)out[i]=f16(bytes,i*2);return out;}
function dequantQ4_0(bytes,n){const out=new Float32Array(n);let p=0;for(let b=0;b<Math.ceil(n/32);b++){const d=f16(bytes,p);p+=2;const base=b*32;for(let i=0;i<16;i++){const x=bytes[p++];if(base+i<n)out[base+i]=((x&15)-8)*d;if(base+i+16<n)out[base+i+16]=((x>>4)-8)*d;}}return out;}
function dequantQ8_0(bytes,n){const out=new Float32Array(n);let p=0;for(let b=0;b<Math.ceil(n/32);b++){const d=f16(bytes,p);p+=2;const base=b*32;for(let i=0;i<32;i++){if(base+i<n)out[base+i]=signedByte(bytes[p])*d;p++;}}return out;}
function dequantQ2_K(bytes,n){const out=new Float32Array(n);let p=0;for(let b=0;b<Math.ceil(n/256);b++){const base=b*256,scales=p;p+=16;const qs=p;p+=64;const d=f16(bytes,p),dmin=f16(bytes,p+2);p+=4;for(let half=0;half<2;half++){for(let i=0;i<32;i++){const packed=bytes[qs+half*32+i];for(let lane=0;lane<4;lane++){const q=(packed>>(lane*2))&3;const group=half*8+lane*2+(i>>4);const sb=bytes[scales+group];const scale=sb&15,min=sb>>4;const idx=base+half*128+lane*32+i;if(idx<n)out[idx]=d*scale*q-dmin*min;}}}}return out;}
function kScale(scales,j){if(j<4)return scales[j]&63;return (scales[j+4]&15)|((scales[j-4]>>6)<<4);} 
function kMin(scales,j){if(j<4)return scales[j+4]&63;return (scales[j+4]>>4)|((scales[j]>>6)<<4);} 
function dequantQ4_K(bytes,n){const out=new Float32Array(n);let p=0;for(let b=0;b<Math.ceil(n/256);b++){const base=b*256;const d=f16(bytes,p),dmin=f16(bytes,p+2);p+=4;const scales=bytes.subarray(p,p+12);p+=12;const qs=p;p+=128;for(let g=0;g<8;g++){const sc=kScale(scales,g),mn=kMin(scales,g);for(let i=0;i<32;i++){const qbyte=bytes[qs+g*16+(i&15)];const q=i<16?(qbyte&15):(qbyte>>4);const idx=base+g*32+i;if(idx<n)out[idx]=d*sc*q-dmin*mn;}}}return out;}
function dequantQ3_K(bytes,n){const out=new Float32Array(n);let p=0;for(let b=0;b<Math.ceil(n/256);b++){const base=b*256;const hmask=p;p+=32;const qs=p;p+=64;const scales=p;p+=12;const d=f16(bytes,p);p+=2;for(let g=0;g<8;g++){const raw=bytes[scales+(g%12)]&63;const sc=(raw>31?raw-64:raw);for(let i=0;i<32;i++){const packed=bytes[qs+g*8+(i&7)];let q=i<8?packed&3:i<16?(packed>>2)&3:i<24?(packed>>4)&3:(packed>>6)&3;const hm=(bytes[hmask+(i>>3)]>>(i&7))&1;if(hm)q-=4;const idx=base+g*32+i;if(idx<n)out[idx]=d*sc*q;}}}return out;}
function dequantQ6_K(bytes,n){const out=new Float32Array(n);let p=0;for(let b=0;b<Math.ceil(n/256);b++){const base=b*256;const ql=p;p+=128;const qh=p;p+=64;const scales=p;p+=16;const d=f16(bytes,p);p+=2;for(let i=0;i<256;i++){const lowByte=bytes[ql+(i&127)];const low=i<128?(lowByte&15):(lowByte>>4);const high=(bytes[qh+(i>>2)]>>((i&3)*2))&3;const q=((high<<4)|low)-32;const sc=signedByte(bytes[scales+(i>>4)]);const idx=base+i;if(idx<n)out[idx]=d*sc*q;}}return out;}
function dequant(bytes,type,n){if(type===0)return dequantF32(bytes,n);if(type===1)return dequantF16(bytes,n);if(type===2)return dequantQ4_0(bytes,n);if(type===8)return dequantQ8_0(bytes,n);if(type===10)return dequantQ2_K(bytes,n);if(type===11)return dequantQ3_K(bytes,n);if(type===12)return dequantQ4_K(bytes,n);if(type===14)return dequantQ6_K(bytes,n);throw new Error("B'H dequant kernel not implemented for GGML type "+type);} 
module.exports={dequant,dequantF32,dequantF16,dequantQ4_0,dequantQ8_0,dequantQ2_K,dequantQ3_K,dequantQ4_K,dequantQ6_K};
