// B"H
/** @file cottageRecipe.js @description Visible cottage meshes are the only collision vessels. No invisible colliders, no sidecars. */
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
const URLS=Object.freeze({red:"https://awtsmoos-docs-base.web.app/full-resolution/red%20brick%201.png"});
const M=new Map(),T=new Map();
function tex(url,r){const k=url+JSON.stringify(r);if(T.has(k))return T.get(k);const t=new THREE.Texture();T.set(k,t);if(typeof fetch==="function"&&typeof createImageBitmap==="function")fetch(url,{mode:"cors",cache:"force-cache"}).then(x=>x.blob()).then(createImageBitmap).then(b=>{t.image=b;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(r.x,r.y);t.anisotropy=8;if(THREE.SRGBColorSpace)t.colorSpace=THREE.SRGBColorSpace;t.needsUpdate=true;}).catch(()=>{});return t;}
function mat(k,c,url=null,r={x:4,y:3}){const id=k+JSON.stringify(r);if(M.has(id))return M.get(id);const m=new THREE.MeshLambertMaterial({color:url?0xffffff:c,map:url?tex(url,r):null,side:THREE.DoubleSide});M.set(id,m);return m;}
function mark(o,d={}){Object.assign(o.userData||={},{villageDecor:true,skipOctree:true,noOctree:true,neverCullVillageProp:true,neverHideVillageProp:true,...d});o.frustumCulled=false;o.receiveShadow=true;return o;}
function solidVisible(o,d={}){return mark(o,{visibleHouseOctreeMesh:true,addToOctree:true,skipOctree:false,noOctree:false,isSolid:true,explicitCollision:true,collisionBody:true,noInvisibleCollider:true,...d});}
function box(g,name,ma,pos,scale,rot=[0,0,0],d={}){const m=mark(new THREE.Mesh(new THREE.BoxGeometry(1,1,1),ma),d);m.name=name;m.position.set(...pos);m.scale.set(...scale);m.rotation.set(...rot);g.add(m);return m;}
function addQuad(b,a,c,d,e,n=[0,0,1]){const s=b.p.length/3;[a,c,d,e].forEach(v=>b.p.push(...v));for(let i=0;i<4;i++)b.n.push(...n);b.u.push(0,0,1,0,1,1,0,1);b.i.push(s,s+1,s+2,s,s+2,s+3);}
function addTri(b,a,c,d,n=[0,0,1]){const s=b.p.length/3;[a,c,d].forEach(v=>b.p.push(...v));for(let i=0;i<3;i++)b.n.push(...n);b.u.push(0,0,.5,1,1,0);b.i.push(s,s+1,s+2);}
function shellGeometry(){const w=8.7,d=5.35,h=3.72,r=2.05,z=d/2,b={p:[],n:[],u:[],i:[]};const holes=[[-.9,.9,.38,3.05],[-3.38,-2.05,1.32,2.34],[2.05,3.38,1.32,2.34]],xs=[-w/2,w/2,...holes.flatMap(x=>[x[0],x[1]])].sort((a,b)=>a-b);for(let i=0;i<xs.length-1;i++){let x1=xs[i],x2=xs[i+1],y=.34;if(x2-x1<.03)continue;for(const H of holes.filter(H=>x1>=H[0]-.01&&x2<=H[1]+.01)){if(H[2]>y)addQuad(b,[x1,y,z],[x2,y,z],[x2,H[2],z],[x1,H[2],z]);y=Math.max(y,H[3]);}if(y<h)addQuad(b,[x1,y,z],[x2,y,z],[x2,h,z],[x1,h,z]);}addQuad(b,[-w/2,.34,-z],[-w/2,h,-z],[w/2,h,-z],[w/2,.34,-z],[0,0,-1]);addQuad(b,[-w/2,.34,-z],[-w/2,.34,z],[-w/2,h,z],[-w/2,h,-z],[-1,0,0]);addQuad(b,[w/2,.34,z],[w/2,.34,-z],[w/2,h,-z],[w/2,h,z],[1,0,0]);addTri(b,[-w/2,h,z],[0,h+r,z],[w/2,h,z],[0,0,1]);addTri(b,[w/2,h,-z],[0,h+r,-z],[-w/2,h,-z],[0,0,-1]);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(b.p,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(b.n,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(b.u,2));g.setIndex(b.i);g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();return g;}
function shell(g){const m=solidVisible(new THREE.Mesh(shellGeometry(),mat('brick',0xffffff,URLS.red,{x:5,y:3.8})),{singleSolidVisualShell:true,manualDoorCut:true,manualWindowCuts:true,solidTriangularGables:true});m.name='VISIBLE_OCTREE_brick_shell_with_real_gables';g.add(m);}
function foundation(g){const s=mat('stone',0x8b8173);solidVisible(box(g,'VISIBLE_OCTREE_stone_foundation',s,[0,.18,0],[9.35,.36,6.05]));solidVisible(box(g,'VISIBLE_OCTREE_stone_front_step',s,[0,.22,3.33],[2.45,.28,.86]));}
function roof(g){const r=mat('roof',0xa9472d),w=mat('wood',0x572817);const angle=.67,len=5.15,y=4.92,x=2.04;box(g,'left_balanced_roof_plane',r,[-x,y,0],[len,.32,6.8],[0,0,angle]);box(g,'right_balanced_roof_plane',r,[x,y,0],[len,.32,6.8],[0,0,-angle]);box(g,'center_ridge_cap',w,[0,5.98,0],[.32,.32,6.92]);box(g,'front_eave_trim',w,[0,3.83,3.06],[9.5,.2,.28]);box(g,'back_eave_trim',w,[0,3.83,-3.06],[9.5,.2,.28]);}
function door(g){const pivot=new THREE.Group();pivot.name='left_hinge_door_pivot_axis';Object.assign(pivot.userData||={},{clickableDoorPivot:true,doorClosedY:0,doorOpenY:-1.48,doorAnimates:true,skipOctree:true,noOctree:true});pivot.position.set(-.82,1.7,2.91);const p=mark(new THREE.Mesh(new THREE.BoxGeometry(1,1,1),mat('door',0x66331b)),{clickableDoor:true,tappableDoor:true,skipRaycast:false});p.name='visible_hinged_wood_door_panel';p.position.set(.82,0,0);p.scale.set(1.55,2.55,.14);pivot.add(p);g.add(pivot);box(pivot,'raised_door_crossbar',mat('door2',0x774024),[.82,.38,.09],[1.25,.16,.06]);box(pivot,'raised_door_vertical_plank',mat('door2',0x774024),[.82,0,.1],[.16,2.3,.06]);box(pivot,'round_gold_knob',mat('gold',0xffe68b),[1.32,.08,.13],[.13,.13,.06]);}
function trim(g){const s=mat('trim',0x918777),glass=mat('glass',0xaee7ff);box(g,'left_door_jamb',s,[-1.05,1.8,2.98],[.18,2.95,.18]);box(g,'right_door_jamb',s,[1.05,1.8,2.98],[.18,2.95,.18]);box(g,'door_top_lintel',s,[0,3.28,2.99],[2.5,.28,.2]);for(const x of[-2.72,2.72]){box(g,'stone_window_frame',s,[x,1.82,2.99],[1.58,1.28,.16]);box(g,'blue_window_glass',glass,[x,1.82,3.08],[1.05,.78,.06]);box(g,'stone_window_sill',s,[x,1.12,3.1],[1.66,.16,.22]);}}
export function gableHouse(){const g=new THREE.Group();g.name='cottage_visible_meshes_only_in_octree';foundation(g);shell(g);roof(g);door(g);trim(g);Object.assign(g.userData||={visibleHouseMeshOnlyOctree:true,noInvisibleColliders:true,noColliderSources:true,solidTriangularGables:true,roofMatchedAtRidge:true,doorHingePivot:true,seal:'full-chain-cache-bust-20260708-bh10'});return g;}
