// B"H
/** @file EcologySpecialMaterials.js @description Structural ecology materials with parser-clear warm progress. */
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { add, byte, branchVeins, capsule, cellInfo, clamp01, cmix, crackNetwork, crystalMask, fbm, line, petalSdf, potatoEyes, rgb, ringLayer, smooth, stripe, threadWeave } from "./MaterialSynthesisPrimitives.js?compact=true&v=sharp-primitives-20260612-bh1";
export const ECOLOGY_MATERIAL_KINDS = ["barkOak","barkPine","marbleWhite","goldHammered","cottonFiber","linenFabric","cabbageLeaf","carrotSkin","potatoSkin","onionSkin","graniteRock","slateStone","mossPatch","mushroomCap","daisyPetal","lavenderFlower"];
const CHANNELS = ["albedo","normal","roughness","height","ao"], textureCache = new Map(), materialCache = new Map();
function barkStructure(u, v, pine = false) { const plate = crystalMask(u + fbm(u * 2, v * 9, 5) * .08, v, pine ? 9 : 7, pine ? 11 : 7); const vertical = stripe((u + fbm(u * 5, v * 18, 8) * .16) * (pine ? 12 : 8), .035); const split = crackNetwork(u, v, pine ? 31 : 29, pine ? 13 : 10); const scar = capsule(u, v, .28, .28, .72, .46, .055) * (fbm(u * 6, v * 6, 40) > .58 ? 1 : 0); return { plate, vertical, split, scar }; }
function marbleStructure(u, v) { const veinA = 1 - smooth(.012, .07, Math.abs(Math.sin((u + fbm(u * 2, v * 3, 6) * .55 + Math.sin(v * 5) * .09) * Math.PI * 7))); const veinB = 1 - smooth(.006, .035, Math.abs(Math.sin((u * 1.6 - v * .4 + fbm(u * 5, v * 4, 9) * .25) * Math.PI * 18))); return clamp01(veinA * .75 + veinB * .5); }
function goldStructure(u, v) { const c = cellInfo(u, v, 22, 17); const dent = 1 - smooth(.2, .72, c.d); const scratch = stripe((u * 44 + v * 6 + fbm(u * 12, v * 4, 44) * 2), .011) * .35; return { dent, scratch, id:c.id }; }
function graniteStructure(u, v) { const c = cellInfo(u, v, 24, 22); return { c, boundary:1 - smooth(.006, .045, c.edge), mica:c.id > .82 ? 1 : 0, quartz:c.id > .46 && c.id < .64 ? 1 : 0 }; }
function leafStructure(u, v) { const edge = 1 - smooth(.44, .52, Math.hypot(u - .5, v - .5)); const veins = branchVeins(u, v, 4); const ci = cellInfo(u, v, 6, 91); const bites = ci.d < .18 && ci.id > .72 ? .4 : 0; return { edge, veins, bites }; }
function flowerStructure(u, v, lavender = false) { const petals = petalSdf(u, v, lavender ? 5 : 11, lavender ? 70 : 60); const center = 1 - smooth(.04, .17, Math.hypot((u * 2.8) % 1 - .5, (v * 2.8) % 1 - .5)); const ribs = stripe((Math.atan2((v % .36) - .18, (u % .36) - .18) * (lavender ? 8 : 13)), .025); return { petals, center, ribs }; }
function height(kind, u, v) { const micro = fbm(u * 64, v * 64, 101) * .06; if (kind === "barkOak" || kind === "barkPine") { const b = barkStructure(u, v, kind === "barkPine"); return clamp01(.36 + b.plate.core * .24 - b.plate.boundary * .34 + b.vertical * .22 - b.split * .3 + b.scar * .38 + micro); } if (kind === "marbleWhite") return clamp01(.48 + marbleStructure(u, v) * .26 + fbm(u * 28, v * 28, 4) * .05); if (kind === "goldHammered") { const g = goldStructure(u, v); return clamp01(.58 + g.dent * .28 - g.scratch * .08 + micro); } if (kind === "cottonFiber" || kind === "linenFabric") return clamp01(.28 + threadWeave(u, v, kind === "linenFabric" ? 64 : 46, 5).weave * .48 + micro); if (kind === "cabbageLeaf") { const l = leafStructure(u, v); return clamp01(.22 + l.veins * .62 + l.edge * .08 - l.bites * .18 + micro); } if (kind === "carrotSkin") return clamp01(.34 + ringLayer(v, u, 34, .05, 12) * .25 + stripe((u + fbm(u * 6, v * 4, 3) * .04) * 12, .02) * .12 + micro); if (kind === "potatoSkin") return clamp01(.36 + potatoEyes(u, v, 81) * .38 + fbm(u * 18, v * 18, 9) * .22 + micro); if (kind === "onionSkin") return clamp01(.34 + ringLayer(u, v, 13, .1, 18) * .36 + line(v, .08, .018) * .12 + line(v, .92, .018) * .12 + micro); if (kind === "graniteRock") { const g = graniteStructure(u, v); return clamp01(.3 + g.c.id * .36 - g.boundary * .2 + g.mica * .2 + micro); } if (kind === "slateStone") return clamp01(.3 + stripe((v + fbm(u * 4, v * 10, 24) * .16) * 22, .025) * .32 + crackNetwork(u, v, 18, 14) * .16 + micro); if (kind === "mossPatch") return clamp01(.18 + fbm(u * 38, v * 38, 20) * .42 + threadWeave(u, v, 32, 9).weave * .18 + micro); if (kind === "mushroomCap") { const f = flowerStructure(u, v, false); return clamp01(.36 + f.ribs * .18 + f.center * .26 + (cellInfo(u, v, 8, 30).d < .1 ? .3 : 0) + micro); } if (kind === "daisyPetal" || kind === "lavenderFlower") { const f = flowerStructure(u, v, kind === "lavenderFlower"); return clamp01(.25 + f.petals * .46 + f.ribs * .12 + f.center * .18 + micro); } return clamp01(.4 + micro); }
function albedo(kind, u, v) { const h = height(kind, u, v), grime = fbm(u * 17, v * 17, 111); if (kind === "barkOak") { const b = barkStructure(u, v, false); return add(cmix(rgb(.10,.048,.02), rgb(.62,.34,.13), h), rgb(.90,.55,.25), b.scar * .32); } if (kind === "barkPine") return cmix(rgb(.055,.032,.018), rgb(.36,.17,.065), h); if (kind === "marbleWhite") return add(cmix(rgb(.68,.68,.65), rgb(1,.985,.93), h), rgb(.18,.18,.18), marbleStructure(u, v) * .55); if (kind === "goldHammered") { const g = goldStructure(u, v); return add(cmix(rgb(.58,.32,.045), rgb(1,.82,.18), h), rgb(1,.9,.35), g.scratch * .12); } if (kind === "cottonFiber") return add(cmix(rgb(.74,.73,.68), rgb(1,.985,.93), h), rgb(.2,.16,.08), grime > .82 ? .14 : 0); if (kind === "linenFabric") return cmix(rgb(.38,.31,.20), rgb(.84,.75,.54), h); if (kind === "cabbageLeaf") { const l = leafStructure(u, v); return add(cmix(rgb(.055,.23,.035), rgb(.78,.96,.32), h), rgb(.16,.05,.02), l.bites * .32); } if (kind === "carrotSkin") return cmix(rgb(.52,.15,.02), rgb(1,.48,.07), h); if (kind === "potatoSkin") return add(cmix(rgb(.28,.18,.08), rgb(.78,.58,.29), h), rgb(.16,.07,.025), potatoEyes(u, v, 81) * .55); if (kind === "onionSkin") return cmix(rgb(.42,.18,.045), rgb(1,.67,.24), h); if (kind === "graniteRock") { const g = graniteStructure(u, v); let base = cmix(rgb(.20,.20,.19), rgb(.76,.74,.67), g.c.id); if (g.quartz) base = cmix(base, rgb(.86,.84,.78), .62); if (g.mica) base = cmix(base, rgb(.10,.09,.08), .65); return base; } if (kind === "slateStone") return cmix(rgb(.055,.09,.11), rgb(.48,.57,.61), h); if (kind === "mossPatch") return cmix(rgb(.028,.12,.015), rgb(.43,.78,.16), h); if (kind === "mushroomCap") return add(cmix(rgb(.48,.14,.06), rgb(.86,.42,.18), h), rgb(.95,.82,.62), cellInfo(u, v, 8, 30).d < .1 ? .55 : 0); if (kind === "daisyPetal") return cmix(rgb(.92,.88,.68), rgb(1,1,1), h + flowerStructure(u, v, false).petals * .15); if (kind === "lavenderFlower") return cmix(rgb(.20,.095,.52), rgb(.88,.64,1), h); return rgb(h,h,h); }
function roughness(kind, u, v) { if (kind === "goldHammered") return .2 + goldStructure(u, v).scratch * .18 + fbm(u * 50, v * 50, 12) * .08; if (kind === "marbleWhite") return .32 + marbleStructure(u, v) * .2; if (kind === "cottonFiber" || kind === "linenFabric" || kind === "mossPatch") return .9; if (kind === "cabbageLeaf" || kind.endsWith("Skin") || kind.endsWith("Petal") || kind.endsWith("Flower")) return .68; return .82; }
function sample(kind, channel, x, y, size) { const u = (x + .5) / size, v = (y + .5) / size; if (channel === "albedo") return albedo(kind, u, v); if (channel === "roughness") { const r = roughness(kind, u, v); return [r,r,r]; } if (channel === "height") { const h = height(kind, u, v); return [h,h,h]; } if (channel === "ao") { const a = clamp01(.46 + height(kind, u, v) * .54); return [a,a,a]; } const e = 1 / size, l = height(kind, u - e, v), rr = height(kind, u + e, v), d = height(kind, u, v - e), up = height(kind, u, v + e); const nx = (l - rr) * 11, ny = (d - up) * 11, nz = 1, len = Math.hypot(nx, ny, nz) || 1; return [nx / len * .5 + .5, ny / len * .5 + .5, nz / len * .5 + .5]; }
export function ecologyTexture(kind = "graniteRock", channel = "albedo", options = {}) { const size = options.size || 128, key = `${kind}:${channel}:${size}:complete-v4`; if (textureCache.has(key)) return textureCache.get(key); const data = new Uint8Array(size * size * 4); let p = 0; for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) { const c = sample(kind, channel, x, y, size); data[p++] = byte(c[0]); data[p++] = byte(c[1]); data[p++] = byte(c[2]); data[p++] = 255; } const t = new THREE.DataTexture(data, size, size, THREE.RGBAFormat); t.wrapS = THREE.RepeatWrapping; t.wrapT = THREE.RepeatWrapping; t.repeat.set(options.repeat || 2, options.repeat || 2); if (channel === "albedo") t.colorSpace = THREE.SRGBColorSpace; t.needsUpdate = true; t.userData.ecologyMaterial = { kind, channel, size, completeV4:true }; textureCache.set(key, t); return t; }
export function ecologyMaterial(kind = "graniteRock", options = {}) { const size = options.size || 128, simple = options.simple !== false && options.highQuality !== true, key = `${kind}:${size}:${simple ? 1 : 0}:${options.unlit ? 1 : 0}:complete-v4`; if (materialCache.has(key)) return materialCache.get(key); const Ctor = options.unlit ? THREE.MeshBasicMaterial : simple ? THREE.MeshLambertMaterial : THREE.MeshStandardMaterial; const params = { map:ecologyTexture(kind, "albedo", { size, repeat:options.repeat || 2 }), color:options.color || 0xffffff, side:options.side || THREE.FrontSide }; if (!simple && !options.unlit) { params.normalMap = ecologyTexture(kind, "normal", { size }); params.roughnessMap = ecologyTexture(kind, "roughness", { size }); params.roughness = roughness(kind, .5, .5); params.metalness = kind === "goldHammered" ? .86 : 0; } const m = new Ctor(params); m.name = `ecology_${kind}_complete_v4_material`; m.userData.ecologyMaterial = true; materialCache.set(key, m); return m; }
function tick() { return new Promise(resolve => setTimeout(resolve, 0)); }
function notifyProgress(options, payload) { if (typeof options.onProgress === "function") options.onProgress(payload); const olam = options.olam || null; try { if (olam && typeof olam.ayshPeula === "function") olam.ayshPeula("increase loading percentage", { total:payload.percent, reset:false, action:`Complete material synthesis: ${payload.kind}`, subAction:`${payload.percent}% (${payload.done}/${payload.total}) ${payload.channel}` }); } catch (_) {} }
export async function warmEcologySpecialMaterials(options = {}) { const size = options.size || 128, total = ECOLOGY_MATERIAL_KINDS.length * CHANNELS.length; let done = 0; for (const kind of ECOLOGY_MATERIAL_KINDS) for (const channel of CHANNELS) { ecologyTexture(kind, channel, { size }); done++; notifyProgress(options, { done, total, percent:Math.round(done / total * 100), kind, channel, backend:"complete-structural-synthesis-v4" }); await tick(); } return ecologyMaterialStats(); }
export function ecologyMaterialStats() { return { kinds:ECOLOGY_MATERIAL_KINDS.length, channels:CHANNELS.length, textures:textureCache.size, materials:materialCache.size, mode:"complete-structural-synthesis-v4-parser-clear" }; }
