// B"H
/** @file FoliageAtlas.js @description Procedural foliage atlas without DOM, parser-clear wind updates. */
import * as THREE from "/games/scripts/build/three.module.js";
const textures = new Map(), materials = new Map(), geometries = new Map();
const ATLAS_COLUMNS = 4, ATLAS_ROWS = 2, CELL = 32, WIDTH = ATLAS_COLUMNS * CELL, HEIGHT = ATLAS_ROWS * CELL;
function colorForFile(file = "") { const lower = String(file).toLowerCase(); if (lower.includes("grass")) return [86,153,68]; if (lower.includes("flower")) return [232,196,76]; if (lower.includes("dry")) return [146,116,58]; return [70,127,58]; }
function paintCell(data, cell, base) { const col = cell % ATLAS_COLUMNS, row = Math.floor(cell / ATLAS_COLUMNS), cx = col * CELL + CELL / 2, cy = row * CELL + CELL / 2, seed = (cell + 1) * 19; for (let y = 0; y < CELL; y++) for (let x = 0; x < CELL; x++) { const px = col * CELL + x, py = row * CELL + y, dx = (x - CELL / 2) / (CELL / 2), dy = (y - CELL / 2) / (CELL / 2); const wobble = Math.sin((x + seed) * .41) * .13 + Math.cos((y - seed) * .37) * .11; const leaf = Math.abs(dx + wobble) * (1.15 + row * .1) + Math.abs(dy) * (.82 + col * .04); const vein = Math.abs((px - cx) * .18 + Math.sin((py + seed) * .2)); const alpha = leaf < .92 || vein < .16 ? 245 : 0, shade = Math.max(.58, Math.min(1.35, 1.05 - dy * .28 + Math.sin((px + py + seed) * .08) * .12)); const index = (py * WIDTH + px) * 4; data[index] = Math.min(255, base[0] * shade + cell * 3); data[index+1] = Math.min(255, base[1] * shade + row * 10); data[index+2] = Math.min(255, base[2] * shade + col * 4); data[index+3] = alpha; } }
function makeProceduralAtlas(file) { const data = new Uint8Array(WIDTH * HEIGHT * 4), base = colorForFile(file); for (let cell = 0; cell < ATLAS_COLUMNS * ATLAS_ROWS; cell++) paintCell(data, cell, base); const texture = new THREE.DataTexture(data, WIDTH, HEIGHT, THREE.RGBAFormat); texture.colorSpace = THREE.SRGBColorSpace; texture.wrapS = THREE.ClampToEdgeWrapping; texture.wrapT = THREE.ClampToEdgeWrapping; texture.minFilter = THREE.LinearFilter; texture.magFilter = THREE.LinearFilter; texture.generateMipmaps = false; texture.needsUpdate = true; texture.userData.worldPersistentAsset = true; texture.userData.awtsmoosNoDocumentTexture = true; texture.name = `awtsmoos_procedural_foliage_${file || "atlas"}`; return texture; }
export function foliageTexture(file = "grass-atlas.png") { if (textures.has(file)) return textures.get(file); const texture = makeProceduralAtlas(file); textures.set(file, texture); return texture; }
function currentTimeSeconds() { const perf = typeof globalThis !== "undefined" ? globalThis.performance : null; return perf && typeof perf.now === "function" ? perf.now() * .001 : Date.now() * .001; }
export function foliageMaterial(options = {}) { const file = options.file || "grass-atlas.png", wind = Number(options.wind || 0), key = `${file}:${wind}:${options.alphaTest || .34}:${options.color || 0xffffff}`; if (materials.has(key)) return materials.get(key); const material = new THREE.MeshLambertMaterial({ map:foliageTexture(file), color:options.color || 0xffffff, side:THREE.DoubleSide, transparent:false, alphaTest:options.alphaTest || .34, depthWrite:true, vertexColors:Boolean(options.vertexColors) }); material.onBeforeCompile = shader => { shader.uniforms.awtsTime = { value:0 }; shader.vertexShader = `uniform float awtsTime;\n${shader.vertexShader}`.replace("#include <begin_vertex>", `#include <begin_vertex>\n#ifdef USE_INSTANCING\nfloat awtsPhase = instanceMatrix[3].x * 0.17 + instanceMatrix[3].z * 0.11;\ntransformed.x += sin(awtsTime * 0.9 + awtsPhase + position.y * 1.7) * ${wind.toFixed(4)} * uv.y;\ntransformed.z += cos(awtsTime * 0.7 + awtsPhase) * ${(wind * .35).toFixed(4)} * uv.y;\n#endif`); material.userData.shader = shader; }; material.customProgramCacheKey = () => key; material.userData.worldPersistentAsset = true; material.userData.awtsmoosProceduralFoliage = true; materials.set(key, material); return material; }
export function crossedAtlasGeometry(cell, planes = 2) { const key = `${cell}:${planes}`; if (geometries.has(key)) return geometries.get(key); const col = cell % ATLAS_COLUMNS, row = Math.floor(cell / ATLAS_COLUMNS), inset = .004; const u0 = col / ATLAS_COLUMNS + inset, u1 = (col + 1) / ATLAS_COLUMNS - inset, v0 = 1 - (row + 1) / ATLAS_ROWS + inset, v1 = 1 - row / ATLAS_ROWS - inset; const positions = [], uvs = [], indices = []; for (let plane = 0; plane < planes; plane++) { const angle = plane * Math.PI / planes, dx = Math.cos(angle) * .5, dz = Math.sin(angle) * .5, base = positions.length / 3; positions.push(-dx,0,-dz, dx,0,dz, dx,1,dz, -dx,1,-dz); uvs.push(u0,v0,u1,v0,u1,v1,u0,v1); indices.push(base,base+1,base+2,base,base+2,base+3); } const geometry = new THREE.BufferGeometry(); geometry.setAttribute("position", new THREE.Float32BufferAttribute(positions, 3)); geometry.setAttribute("uv", new THREE.Float32BufferAttribute(uvs, 2)); geometry.setIndex(indices); geometry.computeVertexNormals(); geometry.computeBoundingSphere(); geometry.userData.worldPersistentAsset = true; geometries.set(key, geometry); return geometry; }
export function foliageBatch(options = {}) { const mesh = new THREE.InstancedMesh(crossedAtlasGeometry(options.cell || 0, options.planes || 2), foliageMaterial(options), options.count || 1); mesh.name = options.name || "atlas_foliage_batch"; mesh.castShadow = false; mesh.receiveShadow = false; mesh.frustumCulled = true; mesh.onBeforeRender = () => { const shader = mesh.material && mesh.material.userData ? mesh.material.userData.shader : null; if (shader && shader.uniforms && shader.uniforms.awtsTime) shader.uniforms.awtsTime.value = currentTimeSeconds(); }; Object.assign(mesh.userData, { skipOctree:true, noOctree:true, skipRaycast:true, villageDecor:true, generatedAtlasFoliage:true }); return mesh; }
export function setFoliageInstance(mesh, index, position, rotation, scale) { const matrix = new THREE.Matrix4().compose(position, new THREE.Quaternion().setFromEuler(rotation), scale); mesh.setMatrixAt(index, matrix); }
