// B"H
/** @file geometryKit.js @description Parser-clear geometry, texture, light, and decorative marking helpers, with quiet procedural generation. */
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
import { generateProceduralGeometry } from "../../../../../../libs/awtsmoos-procedural-core/src/core/geometry/geometryGenerator.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
const cache = new Map();
export const finite = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const smooth = t => t * t * (3 - 2 * t), mix = (a, b, t) => a + (b - a) * t, clamp = v => Math.max(0, Math.min(255, Math.round(v)));
function at(values, index, fallback = 0) { return Array.isArray(values) && values[index] !== undefined ? values[index] : fallback; }
function maxValue(values = []) { let max = 0; for (let i = 0; i < values.length; i++) if (values[i] > max) max = values[i]; return max; }
function quietGeometry(factory) { const originals = { log:console.log, info:console.info, warn:console.warn }; const mute = () => {}; console.log = mute; console.info = mute; console.warn = mute; try { return factory(); } finally { console.log = originals.log; console.info = originals.info; console.warn = originals.warn; } }
export function vec3(values) { return [finite(at(values,0,1),1), finite(at(values,1,1),1), finite(at(values,2,1),1)]; }
export function geometry(kind) { if (kind === "cube" || kind === "box") { const g = new THREE.BoxGeometry(1,1,1); g.computeBoundingBox(); g.computeBoundingSphere(); return g; } const data = quietGeometry(() => generateProceduralGeometry(kind, { size:1 }, [], { id:`picture_${kind}` })); const g = new THREE.BufferGeometry(), pos = data.positions || data.verts || data.vertices || [], nor = data.normals || [], uv = data.uvs || [], ind = data.indices || []; g.setAttribute("position", new THREE.BufferAttribute(new Float32Array(pos), 3)); if (nor.length) g.setAttribute("normal", new THREE.BufferAttribute(new Float32Array(nor), 3)); if (uv.length) g.setAttribute("uv", new THREE.BufferAttribute(new Float32Array(uv), 2)); if (ind.length) g.setIndex(new THREE.BufferAttribute(maxValue(ind) > 65535 ? new Uint32Array(ind) : new Uint16Array(ind), 1)); if (!nor.length) g.computeVertexNormals(); g.computeBoundingBox(); g.computeBoundingSphere(); return g; }
function parts(hex) { return [(hex >> 16) & 255, (hex >> 8) & 255, hex & 255]; }
function put(data, i, rgb, a = 255) { data[i] = clamp(rgb[0]); data[i+1] = clamp(rgb[1]); data[i+2] = clamp(rgb[2]); data[i+3] = clamp(a); }
function n2(x, y, s = 1) { const a = Math.sin(x * 127.1 + y * 311.7 + s * 91.3) * 43758.5453; return a - Math.floor(a); }
function valueNoise(x, y, s = 1) { const ix = Math.floor(x), iy = Math.floor(y), fx = smooth(x - ix), fy = smooth(y - iy); return mix(mix(n2(ix, iy, s), n2(ix+1, iy, s), fx), mix(n2(ix, iy+1, s), n2(ix+1, iy+1, s), fx), fy); }
function fbm(x, y, s) { return valueNoise(x,y,s)*.55 + valueNoise(x*2.1,y*2.1,s+7)*.3 + valueNoise(x*4.2,y*4.2,s+19)*.15; }
function shade(base, amount, tint = [0,0,0]) { return [base[0]+amount+tint[0], base[1]+amount+tint[1], base[2]+amount+tint[2]]; }
function drawBrick(data, size, base, side = false) { const bw = side ? 46 : 54, bh = 21, mortar = [142,139,116]; for (let y=0;y<size;y++) for (let x=0;x<size;x++) { const row=Math.floor(y/bh), off=row%2?bw/2:0, mx=(x+off)%bw, my=y%bh, i=(y*size+x)*4; const mortarMask=Math.min(mx,bw-mx,my,bh-my), mortarBlend=1-smooth(Math.min(1,mortarMask/3.2)); const grain=(fbm(x/23,y/18,30)-.5)*44, chip=fbm((x+row*11)/7,y/7,41)>.78?-26:0; const brick=shade(base,18+grain+chip,[8,6,-4]); put(data,i,[mix(brick[0],mortar[0],mortarBlend),mix(brick[1],mortar[1],mortarBlend),mix(brick[2],mortar[2],mortarBlend)]); } }
function drawRock(data, size, base) { for (let y=0;y<size;y++) for (let x=0;x<size;x++) { const mineral=(fbm(x/29,y/25,71)-.5)*54, pores=fbm(x/5.5,y/5.5,83)>.82?-24:0; const vein=Math.abs(Math.sin((x+fbm(x/21,y/21,92)*28)*.07+y*.025))<.035?-18:0; put(data,(y*size+x)*4,shade(base,14+mineral+pores+vein+(Math.sin(x*.033)+Math.sin(y*.041))*5,[4,3,-2])); } }
function drawWood(data, size, base) { for (let y=0;y<size;y++) for (let x=0;x<size;x++) { const wave=Math.sin(y*.09+fbm(x/18,y/32,3)*5.5)*26, seam=1-smooth(Math.min(1,Math.min(x%64,64-(x%64))/5)); const knot=smooth(Math.max(0,1-Math.hypot((x%96)-52,(y%88)-43)/18))*-58; put(data,(y*size+x)*4,shade(base,10+wave+knot-seam*32,[8,2,-4])); } }
function drawRoof(data, size, base) { for (let y=0;y<size;y++) for (let x=0;x<size;x++) put(data,(y*size+x)*4,shade(base,12+Math.sin(x*.11)*22+(y%42<5?-28:0)+(fbm(x/18,y/18,6)-.5)*36,[14,-4,-8])); }
function drawCloth(data, size, base) { for (let y=0;y<size;y++) for (let x=0;x<size;x++) put(data,(y*size+x)*4,shade(base,(fbm(x/12,y/12,9)-.5)*38+(Math.sin(x*.4)+Math.sin(y*.4))*6)); }
function drawLeaf(data, size, base) { for (let y=0;y<size;y++) for (let x=0;x<size;x++) { const u=x/(size-1), v=y/(size-1), edge=Math.min(u,v,1-u,1-v), vein=Math.exp(-Math.abs(u-.5-Math.sin(v*10)*.035)*42); const rib=Math.max(0,Math.sin((u+v)*38))*10, dap=(fbm(x/14,y/14,13)-.5)*42, gold=fbm(x/9,y/9,29)>.82?28:0; put(data,(y*size+x)*4,shade(base,edge*80+vein*32-rib+dap+gold,[-28,8,-24])); } }
export function textureFor(color, mode = "stone") { const key = `${color}:${mode}:smooth-rock-quiet-310`; if (cache.has(key)) return cache.get(key); const size=256, data=new Uint8Array(size*size*4), base=parts(color || 0xffffff); if (mode==="wood") drawWood(data,size,base); else if (mode==="roof") drawRoof(data,size,base); else if (mode==="cloth") drawCloth(data,size,base); else if (mode==="leaf") drawLeaf(data,size,base); else if (mode==="rock") drawRock(data,size,base); else drawBrick(data,size,base,mode==="alignedBrickSide"); const tex=new THREE.DataTexture(data,size,size,THREE.RGBAFormat,THREE.UnsignedByteType); tex.wrapS=THREE.RepeatWrapping; tex.wrapT=THREE.RepeatWrapping; tex.magFilter=THREE.LinearFilter; tex.minFilter=THREE.LinearMipmapLinearFilter; tex.generateMipmaps=true; const rep = mode==="floor" ? 3.5 : mode==="leaf" ? 1 : mode==="rock" ? 1.25 : mode.startsWith("alignedBrick") ? 2.2 : 2.4; tex.repeat.set(rep, rep); tex.needsUpdate=true; cache.set(key,tex); return tex; }
export function material(color, extra = {}) { const textureMode = extra.textureMode || "stone"; const rest = Object.assign({}, extra); delete rest.textureMode; const mat = textureMode === "leaf" ? new THREE.MeshBasicMaterial(Object.assign({ color:0xffffff, map:textureFor(color, textureMode) }, rest)) : new THREE.MeshLambertMaterial(Object.assign({ color:0xffffff, map:textureFor(color, textureMode) }, rest)); if (extra.emissive !== undefined && mat.emissive) mat.emissive.setHex(extra.emissive); if (extra.emissiveIntensity !== undefined) mat.emissiveIntensity = extra.emissiveIntensity; return mat; }
export function add(group, kind, color, pos, scale, rot = [0,0,0], extra = {}) { const mesh = new THREE.Mesh(geometry(kind), material(color, extra)); mesh.position.set(finite(at(pos,0)), finite(at(pos,1)), finite(at(pos,2))); const s = vec3(scale); mesh.scale.set(s[0], s[1], s[2]); mesh.rotation.set(finite(at(rot,0)), finite(at(rot,1)), finite(at(rot,2))); mesh.castShadow=false; mesh.receiveShadow=false; group.add(mesh); return mesh; }
export function light(group, color, pos, intensity = 1, distance = 7) { const point = new THREE.PointLight(color, finite(intensity,1), finite(distance,7), 2); point.position.set(finite(at(pos,0)), finite(at(pos,1)), finite(at(pos,2))); group.add(point); return point; }
export function markDecorative(root) { const mark = child => { if (!child.userData) child.userData = {}; Object.assign(child.userData, { skipOctree:true, noOctree:true, skipRaycast:true, villageDecor:true }); if (child.isMesh) child.frustumCulled = true; }; if (root && typeof root.traverse === "function") root.traverse(mark); else if (root) mark(root); }
