// B"H
/** @file grounding.js @description Parser-clear terrain-like grounding for decorative and living village objects. */
import * as THREE from "/games/scripts/build/three.module.js?compact=true&v=full-chain-cache-bust-20260708-bh10";
const DOWN = new THREE.Vector3(0,-1,0), RAY = new THREE.Raycaster(), ORIGIN = new THREE.Vector3();
const DEFAULT_GROUND_Y = -0.05, DEFAULT_LIFT = 0, LIVING_GROUND_KEY = "visualGroundOffsetY";
const finite = (value, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
function dataOf(object) { return object && object.userData ? object.userData : {}; }
function parentName(child) { return child && child.parent && child.parent.name ? child.parent.name : ""; }
function visualOf(owner) { if (!owner) return null; return owner.modelMesh || owner.visualObject || owner.guf || owner.mesh || null; }
function ensureData(object) { if (!object.userData) object.userData = {}; return object.userData; }
export function measuredBox(root) { if (!root || typeof root.updateMatrixWorld !== "function") return null; root.updateMatrixWorld(true); const box = new THREE.Box3().setFromObject(root); return Number.isFinite(box.min.y) && Number.isFinite(box.max.y) && !box.isEmpty() ? box : null; }
function isInside(child, root) { for (let node = child; node; node = node.parent) if (node === root) return true; return false; }
function isTerrainLike(child) { const data = dataOf(child), nivra = child && child.nivraAwtsmoos ? child.nivraAwtsmoos : {}; const text = `${child && child.name ? child.name : ""} ${parentName(child)}`.toLowerCase(); return Boolean(data.isTerrain || nivra.type === "proceduralTerrain" || text.includes("terrain") || text.includes("ground")); }
function groundCandidates(scene, root) { const out = []; if (!scene || typeof scene.traverse !== "function") return out; scene.traverse(child => { if (!child || !child.isMesh || !child.geometry || child.visible === false) return; if (isInside(child, root) || !isTerrainLike(child)) return; out.push(child); }); return out; }
export function fallbackGroundY(options = {}) { if (options.skipAutoGround) return null; const value = options.groundY !== undefined ? options.groundY : options.worldGroundY; return finite(value, DEFAULT_GROUND_Y); }
export function terrainRayGroundY(root, scene, box, options = {}) { const fallback = fallbackGroundY(options); if (!scene || options.skipVillageRayGround) return fallback; ORIGIN.set((box.min.x + box.max.x) / 2, box.max.y + 40, (box.min.z + box.max.z) / 2); RAY.set(ORIGIN, DOWN); RAY.near = 0; RAY.far = 120; const hits = RAY.intersectObjects(groundCandidates(scene, root), true); const hit = hits.find(row => row && row.point && Number.isFinite(row.point.y)); return hit && hit.point && Number.isFinite(hit.point.y) ? hit.point.y : fallback; }
export function pinRootToGround(root, options = {}, mode = "flat-pin", pass = 0) { const box = measuredBox(root), targetY = fallbackGroundY(options), lift = finite(options.groundLift, DEFAULT_LIFT); if (!box || !Number.isFinite(targetY)) return { grounded:false, groundY:targetY, lift, deltaY:0, mode, pass }; const deltaY = targetY + lift - box.min.y; if (Math.abs(deltaY) > .00001) root.position.y += deltaY; ensureData(root).awtsmoosGrounding = { mode, pass, groundY:targetY, lift, deltaY, minYBefore:box.min.y }; root.updateMatrixWorld(true); return { grounded:true, groundY:targetY, lift, deltaY, mode, pass }; }
export function groundPictureProp(root, options = {}) { return pinRootToGround(root, options, "immediate-flat-pin", 0); }
export function groundPicturePropToVillageRay(root, scene, options = {}, pass = 0) { const box = measuredBox(root), lift = finite(options.groundLift, DEFAULT_LIFT); if (!box) return { grounded:false, groundY:null, lift, deltaY:0, mode:"village-terrain-ray", pass }; const groundY = terrainRayGroundY(root, scene, box, options); if (!Number.isFinite(groundY)) return pinRootToGround(root, options, "terrain-ray-fallback-flat", pass); const deltaY = groundY + lift - box.min.y; if (Math.abs(deltaY) > .00001) root.position.y += deltaY; ensureData(root).awtsmoosGrounding = { mode:"village-terrain-ray", pass, groundY, lift, deltaY, minYBefore:box.min.y }; root.updateMatrixWorld(true); return { grounded:true, groundY, lift, deltaY, mode:"village-terrain-ray", pass }; }
export function pinLivingVisualToGround(owner, options = {}, pass = 0) { const visual = visualOf(owner), box = measuredBox(visual), groundY = fallbackGroundY(options), lift = finite(options.groundLift, DEFAULT_LIFT); if (!visual || !box || !Number.isFinite(groundY)) return { grounded:false, groundY, lift, deltaY:0, pass }; const deltaY = groundY + lift - box.min.y; const data = ensureData(visual); if (Math.abs(deltaY) > .00001) { visual.position.y += deltaY; data[LIVING_GROUND_KEY] = finite(data[LIVING_GROUND_KEY], 0) + deltaY; } data.awtsmoosLivingGrounding = { mode:"living-flat-pin", pass, groundY, lift, deltaY, minYBefore:box.min.y }; data.awtsmoosLivingGrounded = true; owner.visualYOffset = -finite(data[LIVING_GROUND_KEY], 0); visual.updateMatrixWorld(true); return { grounded:true, groundY, lift, deltaY, mode:"living-flat-pin", pass }; }
export function groundLivingVisualToVillageRay(owner, scene, options = {}, pass = 0) { const visual = visualOf(owner), box = measuredBox(visual); if (!visual || !box) return { grounded:false, groundY:null, lift:finite(options.groundLift), deltaY:0, pass }; const rayY = terrainRayGroundY(visual, scene, box, options), nextGroundY = Number.isFinite(rayY) ? rayY : fallbackGroundY(options); const nextOptions = Object.assign({}, options, { groundY:nextGroundY }); return pinLivingVisualToGround(owner, nextOptions, pass); }
