// B"H
/** @file ProceduralShaderTextureLibrary.js @description Chapter 943: RAM shaders now grow roads, flowers, lamps, leaves, and lichen rocks. */
import * as THREE from "/games/scripts/build/three.module.js";
import { tryRenderWebGLTexture } from "./ProceduralWebGLTextureBackend.js?v=webgl-offscreen-textures-20260612-bh1";
const KINDS = ["grass_meadow","dry_grass","dirt_path","mud_dark","gravel_pebble","cobble_stone","plaster_limestone","weathered_wood","dark_beam_wood","clay_roof_tiles","woven_rug","burlap_sack","straw_thatch","yellow_brick","flower_petal","leaf_vein","lamp_shade","lichen_rock"];
const CHANNELS = ["albedo","normal","roughness","height","ao"];
const ALIAS = Object.freeze({ grass:"grass_meadow", dry:"dry_grass", dirt:"dirt_path", mud:"mud_dark", gravel:"gravel_pebble", cobble:"cobble_stone", plaster:"plaster_limestone", wood:"weathered_wood", darkWood:"dark_beam_wood", roof:"clay_roof_tiles", rug:"woven_rug", burlap:"burlap_sack", straw:"straw_thatch", yellowBrick:"yellow_brick", flowerPetal:"flower_petal", leaf:"leaf_vein", lampShade:"lamp_shade", lichenRock:"lichen_rock" });
const textureCache = new Map(), materialCache = new Map();
const clamp01=v=>Math.max(0,Math.min(1,v)), mix=(a,b,t)=>a+(b-a)*t, fract=x=>x-Math.floor(x);
const smooth=(a,b,x)=>{const t=clamp01((x-a)/Math.max(.00001,b-a));return t*t*(3-2*t)};
const kindOf=k=>ALIAS[k]||k||"weathered_wood", byte=v=>Math.max(0,Math.min(255,Math.round(v*255)));
function hash2(x,y,s=1){return fract(Math.sin(x*127.1+y*311.7+s*74.7)*43758.5453123)}
function noise(x,y,s=1){const ix=Math.floor(x),iy=Math.floor(y),fx=smooth(0,1,x-ix),fy=smooth(0,1,y-iy);return mix(mix(hash2(ix,iy,s),hash2(ix+1,iy,s),fx),mix(hash2(ix,iy+1,s),hash2(ix+1,iy+1,s),fx),fy)}
function fbm(x,y,s=1){let v=0,a=.52,f=1;for(let i=0;i<5;i++){v+=noise(x*f,y*f,s+i*19.7)*a;f*=2.07;a*=.48}return v}
function voronoi(u,v,cells,s){const x=u*cells,y=v*cells,ix=Math.floor(x),iy=Math.floor(y);let best=9,second=9,id=0;for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){const cx=ix+ox+hash2(ix+ox,iy+oy,s),cy=iy+oy+hash2(ix+ox,iy+oy,s+4),d=Math.hypot(x-cx,y-cy);if(d<best){second=best;best=d;id=hash2(ix+ox,iy+oy,s+11)}else if(d<second)second=d}return{d:best,edge:second-best,id}}
function rgb(r,g,b){return[r,g,b]} function cmix(a,b,t){return[mix(a[0],b[0],t),mix(a[1],b[1],t),mix(a[2],b[2],t)]} function add(a,b,k=1){return[a[0]+b[0]*k,a[1]+b[1]*k,a[2]+b[2]*k]}
function seam(x,w=.018){return 1-smooth(0,w,Math.min(fract(x),1-fract(x)))}
function brickMask(u,v){const row=Math.floor(v*8), off=row%2*.5, x=fract(u*6+off), y=fract(v*8);const m=Math.max(seam(x,.04),seam(y,.045));return{m,cell:hash2(Math.floor(u*6+off),row,77)}}
function flowerMask(u,v,s){const x=fract(u*8),y=fract(v*8),cx=x-.5,cy=y-.5,ang=Math.atan2(cy,cx),rad=Math.hypot(cx,cy),petal=Math.abs(Math.sin(ang*5))*smooth(.44,.05,rad);return petal*smooth(.52,.18,rad)*(hash2(Math.floor(u*8),Math.floor(v*8),s)>.35?1:0)}
function leafVein(u,v){const mid=1-smooth(.015,.08,Math.abs(fract(u*2)-.5));const side=1-smooth(.006,.04,Math.abs(Math.sin((u*14+v*7)*Math.PI)));return clamp01(mid*.6+side*.18)}
function heightAt(kindRaw,uRaw,vRaw,seed=3){const kind=kindOf(kindRaw),u=fract(uRaw),v=fract(vRaw),n=fbm(u*12,v*12,seed);if(kind==="yellow_brick"){const b=brickMask(u,v);return clamp01(.5+b.cell*.16-b.m*.34+fbm(u*40,v*40,seed)*.08)}if(kind==="flower_petal")return clamp01(.25+flowerMask(u,v,seed)*.6+fbm(u*36,v*36,seed)*.09);if(kind==="leaf_vein")return clamp01(.32+leafVein(u,v)+fbm(u*30,v*30,seed)*.13);if(kind==="lamp_shade")return clamp01(.45+fbm(u*14,v*18,seed)*.16+Math.sin(v*Math.PI*12)*.04);if(kind==="lichen_rock"){const vo=voronoi(u,v,9,seed);return clamp01(.26+vo.id*.3+smooth(.03,.14,vo.edge)*.38+fbm(u*31,v*31,seed)*.1)}if(kind==="grass_meadow")return clamp01(.35+n*.35+Math.abs(Math.sin((u*71+v*19)*Math.PI))*.1);if(kind==="dry_grass"||kind==="straw_thatch")return clamp01(.34+n*.38+Math.abs(Math.sin((u*37+v*57)*Math.PI))*.16);if(kind==="dirt_path"||kind==="mud_dark")return clamp01(.28+n*.42-(fbm(u*44,v*19,seed+8)>.72?.16:0));if(kind==="gravel_pebble"){const vo=voronoi(u,v,22,seed);return clamp01(.22+vo.id*.32+smooth(.04,.16,vo.edge)*.28)}if(kind==="cobble_stone"){const vo=voronoi(u,v,8,seed);return clamp01(.18+vo.id*.32+smooth(.03,.13,vo.edge)*.44)}if(kind==="plaster_limestone")return clamp01(.42+n*.23-(Math.abs(Math.sin((u*5.2+v*8.7+n)*Math.PI))<.035?.3:0));if(kind==="weathered_wood"||kind==="dark_beam_wood")return clamp01(.36+Math.sin(v*42+fbm(u*7,v*19,seed)*7)*.17+n*.19-seam(u*6,.035)*.28);if(kind==="clay_roof_tiles")return clamp01(.36+n*.25-seam(v*9,.045)*.25+Math.sin(u*Math.PI*16)*.08);if(kind==="woven_rug"||kind==="burlap_sack")return clamp01(.34+n*.26+(Math.sin(u*160)+Math.sin(v*160))*.045);return clamp01(.4+n*.3)}
function albedoAt(kindRaw,u,v,seed=3){const kind=kindOf(kindRaw),h=heightAt(kind,u,v,seed),n=fbm(u*18,v*18,seed+2),f=fbm(u*64,v*64,seed+6);if(kind==="yellow_brick"){const b=brickMask(u,v);return cmix(cmix(rgb(.62,.42,.10),rgb(.98,.78,.24),h),rgb(.34,.27,.15),b.m*.75)}if(kind==="flower_petal"){const tint=hash2(Math.floor(u*8),Math.floor(v*8),seed);return cmix(cmix(rgb(1,.88,.18),rgb(1,.55,.82),tint),rgb(1,1,1),.18+flowerMask(u,v,seed)*.2)}if(kind==="leaf_vein")return cmix(rgb(.08,.24,.07),rgb(.45,.82,.25),h+leafVein(u,v)*.25);if(kind==="lamp_shade")return cmix(rgb(.85,.56,.22),rgb(1,.86,.48),h);if(kind==="lichen_rock")return add(cmix(rgb(.30,.30,.27),rgb(.72,.70,.62),h),rgb(.20,.42,.12),f>.72?.42:0);if(kind==="grass_meadow")return add(cmix(rgb(.20,.45,.15),rgb(.68,.82,.28),h),rgb(.12,.22,.04),f>.82?.45:0);if(kind==="dry_grass")return cmix(rgb(.52,.45,.21),rgb(.86,.74,.34),h);if(kind==="dirt_path")return cmix(rgb(.28,.18,.11),rgb(.62,.43,.25),h);if(kind==="mud_dark")return cmix(rgb(.16,.12,.09),rgb(.42,.31,.20),h);if(kind==="gravel_pebble")return cmix(rgb(.34,.34,.32),rgb(.78,.76,.68),h);if(kind==="cobble_stone")return cmix(rgb(.35,.34,.31),rgb(.64,.62,.55),h);if(kind==="plaster_limestone")return cmix(rgb(.57,.51,.38),rgb(.92,.84,.64),h-n*.1);if(kind==="weathered_wood")return cmix(rgb(.28,.16,.08),rgb(.70,.44,.23),h);if(kind==="dark_beam_wood")return cmix(rgb(.12,.07,.035),rgb(.42,.25,.12),h);if(kind==="clay_roof_tiles")return cmix(rgb(.42,.16,.09),rgb(.86,.39,.18),h);if(kind==="woven_rug")return cmix(Math.floor(u*9)%2?rgb(.60,.16,.14):rgb(.10,.22,.44),rgb(.96,.70,.25),seam(v*4,.04)*.4+n*.2);if(kind==="burlap_sack")return cmix(rgb(.42,.31,.19),rgb(.78,.62,.38),h);if(kind==="straw_thatch")return cmix(rgb(.52,.40,.12),rgb(.95,.78,.34),h);return rgb(h,h,h)}
function roughnessAt(kind,u,v,seed){kind=kindOf(kind);if(kind==="lamp_shade")return .66;if(kind==="mud_dark")return .48+fbm(u*26,v*26,seed)*.25;if(kind.includes("wood"))return .55+fbm(u*26,v*26,seed)*.35;return clamp01(.78+fbm(u*26,v*26,seed+30)*.18-heightAt(kind,u,v,seed)*.08)}
function aoAt(kind,u,v,seed){kind=kindOf(kind);let crevice=1-heightAt(kind,u,v,seed);if(kind==="yellow_brick")crevice=brickMask(u,v).m;if(kind==="cobble_stone")crevice=1-smooth(.025,.12,voronoi(u,v,8,seed).edge);if(kind==="gravel_pebble"||kind==="lichen_rock")crevice=1-smooth(.025,.11,voronoi(u,v,18,seed).edge);return clamp01(1-crevice*.42-fbm(u*38,v*38,seed+40)*.08)}
function texel(kind,channel,x,y,size,seed){const u=(x+.5)/size,v=(y+.5)/size;if(channel==="albedo")return albedoAt(kind,u,v,seed);if(channel==="roughness"){const r=roughnessAt(kind,u,v,seed);return[r,r,r]}if(channel==="ao"){const a=aoAt(kind,u,v,seed);return[a,a,a]}if(channel==="height"){const h=heightAt(kind,u,v,seed);return[h,h,h]}const e=1/size,l=heightAt(kind,u-e,v,seed),r=heightAt(kind,u+e,v,seed),d=heightAt(kind,u,v-e,seed),up=heightAt(kind,u,v+e,seed);let nx=(l-r)*6,ny=(d-up)*6,nz=1,len=Math.hypot(nx,ny,nz)||1;return[nx/len*.5+.5,ny/len*.5+.5,nz/len*.5+.5]}
export function shaderTexture(kindRaw="wood",channel="albedo",options={}){const kind=kindOf(kindRaw),size=options.size||256,seed=options.seed||3,backendWanted=options.backend||"auto",key=`${kind}:${channel}:${size}:${seed}:${backendWanted}`;if(textureCache.has(key))return textureCache.get(key);let data=null,backend="cpu-js";if(backendWanted!=="cpu"){const gl=tryRenderWebGLTexture(kind,channel,size);if(gl?.data){data=gl.data;backend=gl.backend}}if(!data){data=new Uint8Array(size*size*4);let p=0;for(let y=0;y<size;y++)for(let x=0;x<size;x++){const c=texel(kind,channel,x,y,size,seed);data[p++]=byte(c[0]);data[p++]=byte(c[1]);data[p++]=byte(c[2]);data[p++]=255}}const tex=new THREE.DataTexture(data,size,size,THREE.RGBAFormat);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(options.repeat||2,options.repeat||2);if(channel==="albedo")tex.colorSpace=THREE.SRGBColorSpace;tex.needsUpdate=true;tex.name=`ram_shader_${kind}_${channel}_${size}_${backend}`;tex.userData={ramShaderTexture:true,backend,kind,channel,size};textureCache.set(key,tex);return tex}
function qualityFast(){try{return globalThis.__AWTSMOOS_MOBILE_SETTINGS__?.quality==="speed"}catch{return false}}
export function shaderVillageMaterial(kindRaw="wood",options={}){const kind=kindOf(kindRaw),size=options.size||(qualityFast()?128:256),repeat=options.repeat||2,simple=options.simple??qualityFast(),key=`${kind}:${size}:${repeat}:${simple}:${options.unlit?1:0}`;if(materialCache.has(key))return materialCache.get(key);const map=shaderTexture(kind,"albedo",{size,repeat,seed:options.seed||3});const Ctor=options.unlit?THREE.MeshBasicMaterial:simple?THREE.MeshLambertMaterial:THREE.MeshStandardMaterial;const params={color:options.color||0xffffff,map,side:options.side||THREE.FrontSide};if(!simple&&!options.unlit){params.normalMap=shaderTexture(kind,"normal",{size,repeat,seed:options.seed||3});params.roughnessMap=shaderTexture(kind,"roughness",{size,repeat,seed:options.seed||3});params.roughness=.82;params.metalness=0}const mat=new Ctor(params);mat.name=`ram_shader_material_${kind}`;mat.userData.ramShaderMaterial=true;materialCache.set(key,mat);return mat}
const yieldTick=()=>new Promise(r=>setTimeout(r,0));
export async function warmVillageShaderTextures(options={}){const size=options.size||(qualityFast()?128:256),channels=options.channels||CHANNELS,total=KINDS.length*channels.length;let made=0,last=null;for(const kind of KINDS)for(const channel of channels){const tex=shaderTexture(kind,channel,{size,repeat:2,seed:3,backend:options.backend||"auto"});last=tex?.userData?.backend||"unknown";made++;const payload={done:made,total,percent:Math.round(made/total*100),kind,channel,backend:last};options.onProgress?.(payload);try{options.olam?.ayshPeula?.("updateProgress",{shaderTextureProgress:payload})}catch{}if(made%1===0)await yieldTick()}return {...getVillageShaderTextureStats(),lastBackend:last,totalGenerated:made}}
export function getVillageShaderTextureStats(){return{textures:textureCache.size,materials:materialCache.size,kinds:KINDS.length,channels:CHANNELS.length,mode:"ram-js-or-webgl-offscreen-static-botanical"}}
export{KINDS as VILLAGE_SHADER_TEXTURE_KINDS,CHANNELS as VILLAGE_SHADER_TEXTURE_CHANNELS};
