// B"H
/** @file ProceduralShaderTextureLibrary.js @description Parser-clear CPU procedural texture library for village materials. */
import * as THREE from "/games/mitzvahWorld/systems/three/AwtsmoosThreeGateway.js";
export const VILLAGE_SHADER_TEXTURE_KINDS = ["grass_meadow","dry_grass","dirt_path","mud_dark","gravel_pebble","cobble_stone","plaster_limestone","weathered_wood","dark_beam_wood","clay_roof_tiles","woven_rug","burlap_sack","straw_thatch","yellow_brick","flower_petal","leaf_vein","lamp_shade","lichen_rock"];
export const VILLAGE_SHADER_TEXTURE_CHANNELS = ["albedo","normal","roughness","height","ao"];
const KINDS = VILLAGE_SHADER_TEXTURE_KINDS, CHANNELS = VILLAGE_SHADER_TEXTURE_CHANNELS;
const ALIAS = Object.freeze({ grass:"grass_meadow", dry:"dry_grass", dirt:"dirt_path", mud:"mud_dark", gravel:"gravel_pebble", cobble:"cobble_stone", plaster:"plaster_limestone", wood:"weathered_wood", darkWood:"dark_beam_wood", roof:"clay_roof_tiles", rug:"woven_rug", burlap:"burlap_sack", straw:"straw_thatch", yellowBrick:"yellow_brick", flowerPetal:"flower_petal", leaf:"leaf_vein", lampShade:"lamp_shade", lichenRock:"lichen_rock" });
const textureCache = new Map(), materialCache = new Map();
function kindOf(k) { return ALIAS[k] || k || "weathered_wood"; }
function fract(x) { return x - Math.floor(x); }
function clamp(v) { return Math.max(0, Math.min(1, v)); }
function hash(x, y, s) { return fract(Math.sin(x * 127.1 + y * 311.7 + s * 74.7) * 43758.5453123); }
function smooth(t) { t = clamp(t); return t * t * (3 - 2 * t); }
function mix(a, b, t) { return a + (b - a) * t; }
function noise(x, y, s) { const ix = Math.floor(x), iy = Math.floor(y), fx = smooth(x - ix), fy = smooth(y - iy); const a = mix(hash(ix, iy, s), hash(ix + 1, iy, s), fx); const b = mix(hash(ix, iy + 1, s), hash(ix + 1, iy + 1, s), fx); return mix(a, b, fy); }
function fbm(x, y, s) { let v = 0, a = .52, f = 1; for (let i = 0; i < 5; i++) { v += noise(x * f, y * f, s + i * 19.7) * a; f *= 2.07; a *= .48; } return v; }
function rgb(r, g, b) { return [r, g, b]; }
function cmix(a, b, t) { return [mix(a[0], b[0], t), mix(a[1], b[1], t), mix(a[2], b[2], t)]; }
function byte(v) { return Math.max(0, Math.min(255, Math.round(v * 255))); }
function basePalette(kind, h) { if (kind === "grass_meadow") return cmix(rgb(.20,.45,.15), rgb(.68,.82,.28), h); if (kind === "dry_grass" || kind === "straw_thatch") return cmix(rgb(.52,.45,.21), rgb(.86,.74,.34), h); if (kind === "yellow_brick") return cmix(rgb(.62,.42,.10), rgb(.98,.78,.24), h); if (kind === "flower_petal") return cmix(rgb(1,.88,.18), rgb(1,.55,.82), h); if (kind === "leaf_vein") return cmix(rgb(.08,.24,.07), rgb(.45,.82,.25), h); if (kind === "lamp_shade") return cmix(rgb(.85,.56,.22), rgb(1,.86,.48), h); if (kind === "lichen_rock" || kind === "gravel_pebble" || kind === "cobble_stone") return cmix(rgb(.30,.30,.27), rgb(.72,.70,.62), h); if (kind === "dirt_path") return cmix(rgb(.28,.18,.11), rgb(.62,.43,.25), h); if (kind === "mud_dark") return cmix(rgb(.16,.12,.09), rgb(.42,.31,.20), h); if (kind === "weathered_wood") return cmix(rgb(.28,.16,.08), rgb(.70,.44,.23), h); if (kind === "dark_beam_wood") return cmix(rgb(.12,.07,.035), rgb(.42,.25,.12), h); if (kind === "clay_roof_tiles") return cmix(rgb(.42,.16,.09), rgb(.86,.39,.18), h); if (kind === "woven_rug") return cmix(rgb(.60,.16,.14), rgb(.10,.22,.44), h); if (kind === "burlap_sack") return cmix(rgb(.42,.31,.19), rgb(.78,.62,.38), h); return cmix(rgb(.57,.51,.38), rgb(.92,.84,.64), h); }
function height(kind, u, v, seed) { const n = fbm(u * 12, v * 12, seed); const rings = Math.abs(Math.sin((u * 37 + v * 17) * Math.PI)) * .12; if (kind.includes("wood")) return clamp(.36 + Math.sin(v * 42 + n * 7) * .17 + n * .19); if (kind === "yellow_brick") return clamp(.50 + n * .18 - (fract(u * 6) < .04 || fract(v * 8) < .045 ? .30 : 0)); if (kind === "leaf_vein") return clamp(.32 + n * .25 + (Math.abs(fract(u * 2) - .5) < .025 ? .5 : 0)); return clamp(.28 + n * .44 + rings); }
function texel(kind, channel, x, y, size, seed) { const u = (x + .5) / size, v = (y + .5) / size, h = height(kind, u, v, seed); if (channel === "height") return [h, h, h]; if (channel === "roughness") { const r = kind === "lamp_shade" ? .66 : clamp(.78 + fbm(u * 26, v * 26, seed + 30) * .18 - h * .08); return [r, r, r]; } if (channel === "ao") { const a = clamp(1 - (1 - h) * .35); return [a, a, a]; } if (channel === "normal") { const e = 1 / size, l = height(kind, u - e, v, seed), r = height(kind, u + e, v, seed), d = height(kind, u, v - e, seed), up = height(kind, u, v + e, seed); const nx = (l - r) * 6, ny = (d - up) * 6, nz = 1, len = Math.hypot(nx, ny, nz) || 1; return [nx / len * .5 + .5, ny / len * .5 + .5, nz / len * .5 + .5]; } return basePalette(kind, h); }
export function shaderTexture(kindRaw = "wood", channel = "albedo", options = {}) { const kind = kindOf(kindRaw), size = options.size || 256, seed = options.seed || 3, repeat = options.repeat || 2, key = `${kind}:${channel}:${size}:${seed}:${repeat}`; if (textureCache.has(key)) return textureCache.get(key); const data = new Uint8Array(size * size * 4); let p = 0; for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) { const c = texel(kind, channel, x, y, size, seed); data[p++] = byte(c[0]); data[p++] = byte(c[1]); data[p++] = byte(c[2]); data[p++] = 255; } const tex = new THREE.DataTexture(data, size, size, THREE.RGBAFormat); tex.wrapS = THREE.RepeatWrapping; tex.wrapT = THREE.RepeatWrapping; tex.repeat.set(repeat, repeat); if (channel === "albedo") tex.colorSpace = THREE.SRGBColorSpace; tex.needsUpdate = true; tex.name = `ram_shader_${kind}_${channel}_${size}_cpu`; tex.userData = { ramShaderTexture:true, backend:"cpu-js", kind, channel, size }; textureCache.set(key, tex); return tex; }
function qualityFast() { const settings = typeof globalThis !== "undefined" ? globalThis.__AWTSMOOS_MOBILE_SETTINGS__ || {} : {}; return settings.quality === "speed"; }
function simpleFrom(options) { if (options.simple !== undefined) return Boolean(options.simple); return qualityFast(); }
export function shaderVillageMaterial(kindRaw = "wood", options = {}) { const kind = kindOf(kindRaw), size = options.size || (qualityFast() ? 128 : 256), repeat = options.repeat || 2, simple = simpleFrom(options), unlit = Boolean(options.unlit), key = `${kind}:${size}:${repeat}:${simple}:${unlit ? 1 : 0}`; if (materialCache.has(key)) return materialCache.get(key); const map = shaderTexture(kind, "albedo", { size, repeat, seed:options.seed || 3 }); const Ctor = unlit ? THREE.MeshBasicMaterial : simple ? THREE.MeshLambertMaterial : THREE.MeshStandardMaterial; const params = { color:options.color || 0xffffff, map, side:options.side || THREE.FrontSide }; if (!simple && !unlit) { params.normalMap = shaderTexture(kind, "normal", { size, repeat, seed:options.seed || 3 }); params.roughnessMap = shaderTexture(kind, "roughness", { size, repeat, seed:options.seed || 3 }); params.roughness = .82; params.metalness = 0; } const mat = new Ctor(params); mat.name = `ram_shader_material_${kind}`; mat.userData.ramShaderMaterial = true; materialCache.set(key, mat); return mat; }
function yieldTick() { return new Promise(resolve => setTimeout(resolve, 0)); }
function callProgress(options, payload) { if (typeof options.onProgress === "function") options.onProgress(payload); const olam = options.olam || null; try { if (olam && typeof olam.ayshPeula === "function") olam.ayshPeula("increaseLoadingPercentage", payload); } catch (_) {} }
export async function warmVillageShaderTextures(options = {}) { const size = options.size || (qualityFast() ? 128 : 256), channels = options.channels || CHANNELS, total = KINDS.length * channels.length; let made = 0, last = "cpu-js"; for (const kind of KINDS) for (const channel of channels) { const tex = shaderTexture(kind, channel, { size, repeat:2, seed:3 }); last = tex.userData.backend || "cpu-js"; made++; callProgress(options, { done:made, total, percent:Math.round(made / total * 100), kind, channel, backend:last }); await yieldTick(); } return Object.assign({}, getVillageShaderTextureStats(), { lastBackend:last, totalGenerated:made }); }
export function getVillageShaderTextureStats() { return { textures:textureCache.size, materials:materialCache.size, kinds:KINDS.length, channels:CHANNELS.length, mode:"ram-js-static-botanical-parser-clear" }; }
