// B"H
import assert from 'node:assert/strict';
import { HEALTHY_LUNCH_AUTHORED_SCENE } from '../../src/scenes/healthy-lunch/HealthyLunchScene.js';
import { SceneResolver } from '../../src/document/SceneResolver.js';
import { SceneComposer } from '../../src/scene/core/SceneComposer.js';
import { ModifierEngine } from '../../src/modifiers/ModifierEngine.js';
import { PathAttachment } from '../../src/paths/PathAttachment.js';
import { CharacterAssembler } from '../../src/character/rig/CharacterAssembler.js';
import { FaceRig } from '../../src/character/face/FaceRig.js';
import { Outfit } from '../../src/character/clothing/Outfit.js';
import { ShotPlanner } from '../../src/camera/production/ShotPlanner.js';
import { Timeline } from '../../src/animation/core/Timeline.js';
import { Track } from '../../src/animation/core/Track.js';
import { Keyframe } from '../../src/animation/core/Keyframe.js';
import { ScenePlanner } from '../../src/director/planning/ScenePlanner.js';
import { HierarchyModel } from '../../src/editor/model/HierarchyModel.js';
import { SceneDSL } from '../../src/ai/SceneDSL.js';
import { SceneCompiler } from '../../src/ai/SceneCompiler.js';

const cameraBoundScene = SceneComposer.build({ sceneData: { style: 'authored_world_2d' }, ctx: { width: 720, height: 1080 } });
assert.equal(HEALTHY_LUNCH_AUTHORED_SCENE.id, 'healthy_lunch_authored_v1');
assert.ok(JSON.stringify(SceneResolver.resolve(HEALTHY_LUNCH_AUTHORED_SCENE, { width: 720, height: 1080 })).includes('kitchen'));
assert.equal(cameraBoundScene.id, 'REAL_CHARACTER_CAMERA_BOUND_KITCHEN_STAGE');
assert.ok(JSON.stringify(cameraBoundScene).includes('world_kitchen_wall_upper'));
assert.equal(ModifierEngine.apply([{ id: 'x' }], [{ type: 'repeat', options: { count: 3, dx: 10 } }]).length, 3);
assert.equal(PathAttachment.distribute([{ id: 'a' }, { id: 'b' }], [{ x: 0, y: 0 }, { x: 10, y: 0 }])[1].x, 10);
assert.ok(CharacterAssembler.human('kid', { face: FaceRig.happy(), outfit: new Outfit() }).skeleton.includes('head'));
assert.ok(ShotPlanner.plan('insert').zoom <= 1.05);
assert.equal(new Timeline({ tracks: [new Track('a', [new Keyframe(0, { v: 1 })])] }).sample(0).a.v, 1);
assert.ok(ScenePlanner.plan().beats.length > 0);
assert.equal(HierarchyModel.fromDocument(HEALTHY_LUNCH_AUTHORED_SCENE).districts[0].id, 'kitchen_district');
assert.equal(SceneCompiler.compile(new SceneDSL().add('apple', { id: 'apple1' }))[0].assetId, 'apple');
console.log('B"H all 18 phase foundation smoke passed');
