// B"H
import assert from 'node:assert/strict';
import { DEFAULT_SCENE } from '../../src/data/scenes/default/index.js';
import { DirectingEngine } from '../../src/director/intent/index.js';

const plan = DEFAULT_SCENE.directing || DirectingEngine.outdoorStormLantern(DEFAULT_SCENE);
const characterCount = Object.keys(DEFAULT_SCENE.initialCharacters).length;
const keys = ['attention','motivation','microExpressions','secondaryMotion','visualHierarchy','emotionalColorScript','sceneState','directorBrain','storyArc','transitions','audioNarrative','gestures','blocking','lensLanguage','crowdBehavior','continuityMemory','dashboard','continuity','intentScore','cameraPsychology','report'];
for (const key of keys) assert.ok(plan[key], key);
assert.equal(Object.keys(plan.attention).length, characterCount);
assert.equal(Object.keys(plan.motivation).length, characterCount);
assert.equal(Object.keys(plan.microExpressions).length, characterCount);
assert.equal(Object.keys(plan.secondaryMotion.characters).length, characterCount);
assert.equal(Object.keys(plan.secondaryMotion.props).length, DEFAULT_SCENE.initialProps.length);
assert.equal(plan.visualHierarchy.length, plan.storyArc.length);
assert.equal(plan.emotionalColorScript.length, plan.storyArc.length);
assert.equal(plan.sceneState.final, 'shared_light_survives');
assert.equal(plan.directorBrain.ok, true);
assert.equal(plan.directorBrain.decision, 'renderable_with_living_direction');
assert.equal(plan.transitions.length, DEFAULT_SCENE.cameras.length);
assert.equal(plan.audioNarrative.length, plan.storyArc.length);
assert.equal(plan.blocking.length, plan.storyArc.length);
assert.equal(plan.lensLanguage.length, DEFAULT_SCENE.cameras.length);
assert.equal(Object.keys(plan.crowdBehavior).length, 6);
assert.equal(plan.dashboard.health, 'directed_scene_ready');
assert.equal(plan.continuity.score, 100);
assert.equal(plan.intentScore.score, 100);
assert.equal(plan.cameraPsychology.ok, true);
assert.equal(plan.report.warnings.length, 0);
console.log('B"H directing engine smoke passed');
