// B"H
import assert from 'node:assert/strict';
import { DEFAULT_SCENE } from '../../src/data/scenes/default/index.js';
import { DirectingEngine } from '../../src/director/intent/index.js';

const plan = DEFAULT_SCENE.directing || DirectingEngine.outdoorStormLantern(DEFAULT_SCENE);
const characterCount = Object.keys(DEFAULT_SCENE.initialCharacters).length;
for (const key of ['storyArc', 'relationships', 'lighting', 'performance', 'eyeContact', 'weatherNarrative', 'directorNotes', 'composition', 'rhythm', 'silenceBeats', 'propStates', 'environmentalMemory', 'transitions', 'audioNarrative', 'gestures', 'blocking', 'lensLanguage', 'crowdBehavior', 'continuityMemory', 'dashboard', 'continuity', 'intentScore', 'cameraPsychology', 'report']) assert.ok(plan[key], key);
assert.equal(plan.storyArc.length, 6);
assert.equal(plan.lensLanguage.length, DEFAULT_SCENE.cameras.length);
assert.equal(Object.keys(plan.crowdBehavior).length, 6);
assert.equal(plan.continuityMemory.carriesForward.lanternLit, true);
assert.equal(plan.continuityMemory.nextSceneHooks.length >= 4, true);
assert.equal(plan.transitions.length, DEFAULT_SCENE.cameras.length);
assert.equal(plan.audioNarrative.length, plan.storyArc.length);
assert.equal(plan.blocking.length, plan.storyArc.length);
assert.equal(Object.keys(plan.gestures).length, characterCount);
assert.equal(Object.keys(plan.performance).length, characterCount);
assert.equal(Object.keys(plan.propStates).length, DEFAULT_SCENE.initialProps.length);
assert.equal(plan.dashboard.health, 'directed_scene_ready');
assert.equal(plan.continuity.score, 100);
assert.equal(plan.intentScore.score, 100);
assert.equal(plan.cameraPsychology.ok, true);
assert.ok(plan.lensLanguage.some(mark => mark.focalFeeling === 'macro_story_object'));
assert.ok(plan.crowdBehavior.lamp_neighbor.some(mark => mark.goal === 'turn_toward_light'));
assert.ok(plan.transitions.some(mark => mark.transition === 'match_on_glow'));
assert.ok(plan.audioNarrative.some(mark => mark.silencePocket === true));
assert.ok(plan.gestures.goat_sidekick.some(mark => mark.gesture === 'all_legs_lock'));
assert.ok(plan.blocking.some(mark => mark.formation === 'protective_circle'));
assert.equal(plan.report.warnings.length, 0);
console.log('B"H directing engine smoke passed');
